### ISSUE TITLE
possibility of changing "syncDelay" through updating system repository

### ISSUE THREAD

**Issue by yyz1989** [eclipse/rdf4j#1004]
Dear all,

Has anybody tried to change the synchronization interval for an existing in memory repository? I know I can just create a new repository and load the data again, but is it also safe if I simply change this parameter stored at system repository?

Thank you very much for the information.

Best regards,
Yang

**Comment by jamesrdf** [comment]
This is a great question for the mailing list. The short answer, though, is yes you can change this parameter faster the repository has been loaded.
