### ISSUE TITLE
does the synchronization between memory and disk create full repository dump?

### ISSUE THREAD

**Issue by yyz1989** [eclipse/rdf4j#1005]
Dear all,

Another question concerning synchronization between memory and disk. Does it write a full repository dump to disk or only the updated statements are really synchronized? It seems that the synchronize time grows as the size of repository grows. I got only around 6 million triples and the syncDelay is set to 1 second, but changes on a few triples can cost around 1 minute for synchronization which blocks other repository operations as well. With less data this time is also less. Is there any related configuration I should think about here? I tried to change the syncDelay to 5 minutes, then kept performing update operations for some time, but was not able to reproduce this phenomenon any more. It is also possible that I did not seize the right moment to get trapped by the synchronization. 

Best regards,
Yang

**Comment by jamesrdf** [comment]
Another great question for the mailing list! The memory store does a full dump each time.
