### ISSUE TITLE
TriG parser fails on TriG roundtrip

### ISSUE THREAD

**Issue by ignazio1977** [eclipse/rdf4j#1012]
An exception is thrown in TriG parsing for a TriG output written with 2.3.0. 2.2.4 does not show the same behaviour.

Example output from 2.3.0:

    @prefix : <http://www.semanticweb.org/owlapi/test#> .
    @prefix owl: <http://www.w3.org/2002/07/owl#> .
    @prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
    @prefix xml: <http://www.w3.org/XML/1998/namespace> .
    @prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
    @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
    {
      _:genid1 a owl:Ontology.
      :prop a owl:DatatypeProperty;
        owl:deprecated true.
      :ClsA a owl:Class;
        owl:deprecated true.
    }

The crux of the issue is `true.`

In parsing, this fails - the parser reads past the `.` character and finds a carriage return while expecting a boolean value or an IRI.

    Expected ':', found '
    ' [line 10]        org.eclipse.rdf4j.rio.helpers.RDFParserHelper.reportFatalError(RDFParserHelper.java:403)
        org.eclipse.rdf4j.rio.helpers.AbstractRDFParser.reportFatalError(AbstractRDFParser.java:677)
        org.eclipse.rdf4j.rio.turtle.TurtleParser.reportFatalError(TurtleParser.java:1306)
        org.eclipse.rdf4j.rio.turtle.TurtleParser.verifyCharacterOrFail(TurtleParser.java:1141)
        org.eclipse.rdf4j.rio.turtle.TurtleParser.parseQNameOrBoolean(TurtleParser.java:988)
        org.eclipse.rdf4j.rio.turtle.TurtleParser.parseValue(TurtleParser.java:583)
        org.eclipse.rdf4j.rio.turtle.TurtleParser.parseObject(TurtleParser.java:475)
        org.eclipse.rdf4j.rio.turtle.TurtleParser.parseObjectList(TurtleParser.java:413)
        org.eclipse.rdf4j.rio.turtle.TurtleParser.parsePredicateObjectList(TurtleParser.java:408)
        org.eclipse.rdf4j.rio.trig.TriGParser.parseTriples(TriGParser.java:253)

In 2.2.4, the output is 

    @prefix : <http://www.semanticweb.org/owlapi/test#> .
    @prefix owl: <http://www.w3.org/2002/07/owl#> .
    @prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
    @prefix xml: <http://www.w3.org/XML/1998/namespace> .
    @prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
    @prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
    {
      _:genid1 a owl:Ontology.
      :prop a owl:DatatypeProperty;
        owl:deprecated true .
      :ClsA a owl:Class;
        owl:deprecated true .
    }

The space between `true` and `.` leads to correct parser behaviour.

This appears to be due to a rendering change in `org.eclipse.rdf4j.rio.turtle.TurtleWriter`: in 2.2.4, the rendering code includes a space before the dot.

	protected void closePreviousStatement()
		throws IOException
	{
		if (!statementClosed) {
			// The previous statement still needs to be closed:
			writer.write(" .");

That space is gone in 2.3.0.

From a quick look at the TriG grammar in the [W3C recommendation](https://www.w3.org/TR/trig/) it does not look like the space is mandatory according to the grammar; this suggests that the change in rendering is legal but the parser has a bug (it needs to account for a dot closing the statement, not rely on a space also occurring at that point).

**Comment by ansell** [comment]
Related to #1006 given the reliance on the Turtle parser by the TriG parser

**Comment by ignazio1977** [comment]
Looks like an exact duplicate of #1006 to me, please close this issue if you agree.
