### ISSUE TITLE
Upgrade to jsonld-java version 0.12.0, which contains critical performance enhancements

### ISSUE THREAD

**Issue by HansBrende** [eclipse/rdf4j#1016]
Cf. https://github.com/jsonld-java/jsonld-java/pull/228 (critical) and https://github.com/jsonld-java/jsonld-java/pull/224 (non-critical, but nice to have)

**Comment by jeenbroekstra** [comment]
This will require a new CQ.

**Comment by jeenbroekstra** [comment]
CQ opened at https://dev.eclipse.org/ipzilla/show_bug.cgi?id=16357

**Comment by jeenbroekstra** [comment]
CQ approved, so if someone wants to put up a PR with this version bump, we can include it.

**Comment by barthanssens** [comment]
And probably two  additional PRs for rdf4j-storage and rdf4j-tools ? 
Storage and tools are still using jsonld-java 0.8.3... 

- https://github.com/eclipse/rdf4j-storage/blob/develop/pom.xml
- https://github.com/eclipse/rdf4j-tools/blob/develop/pom.xml

**Comment by jeenbroekstra** [comment]
@barthanssens I wonder if those deps in storage and tools are just leftovers. Can they be removed instead of bumped? I would expect them to just use the version that rdf4j-client provides...

**Comment by barthanssens** [comment]
Could very well be... I'll guess the same goes voor the spring dependency (and maybe some others)

**Comment by jeenbroekstra** [comment]
All done :+1:
