### ISSUE TITLE
LocalRepositoryManager in rdf4j-runtime-osgi (version 2.3.1) does not support HTTPRepositories

### ISSUE THREAD

**Issue by manuelfiorelli** [eclipse/rdf4j#1023]
The `LocalRepositoryManager` inside `rdf4j-runtime-osgi` no longer supports (in version 2.3.1) `HTTPRepository`.

Below is an excerpt of the stacktrace:

> Caused by: org.eclipse.rdf4j.repository.config.RepositoryConfigException: Unsupported repository type: openrdf:HTTPRepository
        at org.eclipse.rdf4j.repository.config.AbstractRepositoryImplConfig.lambda$create$1(AbstractRepositoryImplConfig.java:101)
        at java.util.Optional.orElseThrow(Optional.java:290)
        at org.eclipse.rdf4j.repository.config.AbstractRepositoryImplConfig.create(AbstractRepositoryImplConfig.java:99)
        at org.eclipse.rdf4j.repository.config.RepositoryConfig.lambda$parse$2(RepositoryConfig.java:163)
        at java.util.Optional.ifPresent(Optional.java:159)
        at org.eclipse.rdf4j.repository.config.RepositoryConfig.parse(RepositoryConfig.java:162)
        at org.eclipse.rdf4j.repository.config.RepositoryConfig.create(RepositoryConfig.java:183)
        at org.eclipse.rdf4j.repository.config.RepositoryConfigUtil.getRepositoryConfig(RepositoryConfigUtil.java:43)
        at org.eclipse.rdf4j.repository.manager.LocalRepositoryManager.getRepositoryConfig(LocalRepositoryManager.java:345)
        at org.eclipse.rdf4j.repository.manager.LocalRepositoryManager.createRepository(LocalRepositoryManager.java:264)

The root cause of the problem might be that the file `rdf4j-runtime-osgi-2.3.1.jar\META-INF\services\org.eclipse.rdf4j.repository.config.RepositoryFactory` does not list the factory of HTTPRepositories.

**Comment by manuelfiorelli** [comment]
I analyzed the issue in order to understand the real cause of the problem.

Looking at the `pom.xml` of the project `rdf4j-runtime-osgi`, I noticed that the following line
```
META-INF/services=target/services/META-INF/services
```
The line above should mean to include the provider-configuration files generated during the build. 

Unfortunately, this folder is empty in my tests.

This observations puzzled me at first, since I could not explain why an incomplete provider-configuration is nonetheless present in the runtime jar. Then I realized that the bundle plugin is actually including the provider-configuration files contained in the (transitively) imported modules of RDF4J: configurations for the same service (which have the same name) overwrite each other, and thus only one provider-configuration for each service is included in the runtime jar.

If the folder `target/services/META-INF/services` were not empty, then it content would replace any homonym provider-configuration.

The generation of the provider-configuration is controlled by the ant script `build.xml`, which concatenates the different provider-configurations for some RDF4J services. The fact that it no longer produces any file is determined by the inability of the script to find any provider-configuration.

Looking at the following piece of code in `build.xml`:
```
<concat destfile="target/services/META-INF/services/${service}" fixlastline="yes">
    <fileset dir="${antfile.dir}/.." includes="**/src/main/resources/META-INF/services/${service}"/>
</concat>
```

The `fileset` is rooted in the folder `${antfile.dir}/..`, which is `rdf4j-tools`. This folder clearly does not contain the provider-configurations we would like to concatenate. This issue was probably a consequence of the subdivision of the code base into various Github repositories.

On my machine, I have the sources of the various repositories inside the same folder, so as a temporary solution to build the runtime, I simply appended another `/..` to the `dir` attribute of the fileset. However, I think that this solution is not suitable for the submission to the upstream, because:
1.  the repositories may not be stored in the same folder
2. the fileset would consider other sibling directories as well

A nicer solution would require to work at the level of maven dependencies, or at the level of the bundle-plugin: regarding the latter, I searched without success for a mechanism to tell the plugin to concatenate files with the same name.

**Comment by manuelfiorelli** [comment]
I managed to fix this issue by using:
1. `maven-shade-plugin` to gather the service files from the RDF4J modules
2. `maven-antrun-plugin` to remove duplicated entries in the service files and inject them in the main artifact of the project

However, when I was preparing the pull request, I noticed that I should create it against the repository `rdf4j-tools` instead of this repository (`repository`). In doing so, I should mention in the branch name and the commit message an issue (1023) that does not exist in that repository.
@jeenbroekstra: what do you suggest to do? For example, fill a new issue in the repository `rdf4j-tools`?

**Comment by jeenbroekstra** [comment]
@manualfiorelli you can refer to an issue in another repo in your commit message by prefixing it with <orgname>/<reponame>. For example, instead of just doing #1023, you can do eclipse/rdf4j#1023. If you use that in a commit or PR against rdf4j-tools, it will still link to this issue.

**Comment by manuelfiorelli** [comment]
@jeenbroekstra thank you. I'm going to create a PR with my proposed solution to this issue
