### ISSUE TITLE
Rename spanqit module to SparqlBuilder

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#1028]
Up for discussion: should the newly contributed spanqit module (a fluent api for SPARQL query composition) be renamed?

**Comment by barthanssens** [comment]
I can appreciate the humor in it :-) But a more business-appropriate name is probably desirable ...
So what about SparqlBuilder or SparqlQueryBuilder ?

**Comment by kenwenzel** [comment]
What about sparqit or sparqlit?

**Comment by jeenbroekstra** [comment]
Personally in favor of something like SparqlBuilder as well - does what it says on the tin. Which is also the main problem I have with the name spanqit. I can appreciate the fun aspect, but it's just not clear from the name what it actually _is_.
