### ISSUE TITLE
Use AssertJ as the assertion framework

### ISSUE THREAD

**Issue by josephw** [eclipse/rdf4j#1030]
As of 2018, Java Hamcrest development has [largely stalled](https://github.com/hamcrest/JavaHamcrest/issues/131). Although it's only lightly used in rdf4j's tests, I believe it's worth tracking a currently maintained framework.

To resolve this, switch all use of `org.hamcrest` over to the [Apache-licenced](https://github.com/joel-costigliola/assertj-core/blob/b0e3ed807784a679ccc34f57d6e672b527059976/LICENSE.md) [AssertJ](http://joel-costigliola.github.io/assertj/) (as of writing, last released in April 2018).

In most cases this is a direct translation:

    -assertThat(errorCollector.getFatalErrors(), empty());
    +assertThat(errorCollector.getFatalErrors()).isEmpty();

As a side benefit, some assertions are substantially more concise:

    -assertThat(stmts, Matchers.<Statement> iterableWithSize(2));
    +assertThat(stmts).hasSize(2);

This change will need to be made in all rdf4j repos:

* rdf4j
* rdf4j-storage
* rdf4j-tools
* rdf4j-testsuite

**Comment by jeenbroekstra** [comment]
CQ: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=16249

**Comment by jeenbroekstra** [comment]
CQ has been approved. @josephw are you available to put the update in for the other rdf4j repos as well?

**Comment by jeenbroekstra** [comment]
Good stuff, thanks.
