### ISSUE TITLE
SparqlBuilder to work with rdf4j model objects

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#1038]
Currently, the SparqlBuilder module has its own set of interfaces for RDF value objects: `RdfResource`, `Iri`, `Prefix`, etc. To facilitate better integration with the rest of the RDF4J framework we should make sure that the builder API (also) accepts RDF4J model objects, like `org.eclipse.rdf4j.model.IRI` etc.

**Comment by anqit** [comment]
Can this be done while maintaining the module's ability to be used independently?

**Comment by jeenbroekstra** [comment]
Well it will need a maven dependency on rdf4j-model, but we can extend the API in such a way that you don't _have_ to use rdf4j model objects if you don't want to, I think.

**Comment by reckart** [comment]
> Well it will need a maven dependency on rdf4j-model, but we can extend the API in such a way that you don't have to use rdf4j model objects if you don't want to, I think.

Having to carry around a `ValueFactory` in RDF4J is quite a pain. The way the query builder code does it using static factory methods is much more convenient.

**Comment by jeenbroekstra** [comment]
> Having to carry around a `ValueFactory` in RDF4J is quite a pain. The way the query builder code does it using static factory methods is much more convenient.

This (a closed issue) isn't really the best place to be having a conversation about this, but if you have a specific use case in mind where some other pattern than a `ValueFactory` would be better, please open a feature request (or alternatively, send a message to the user forum). We are currently mapping out our plans for rdf4j 3.0, so this is an ideal time to come with proposals for improvements, even if they are not necessarily backward compatible.

**Comment by reckart** [comment]
@jeenbroekstra see #1325
