### ISSUE TITLE
XXE in XML Parser

### ISSUE THREAD

**Issue by ProDigySML** [eclipse/rdf4j#1056]
# The Issue
An XML External Entity attack is a type of attack against an application that parses XML input. This attack occurs when XML input containing a reference to an external entity is processed by a weakly configured XML parser. This attack may lead to the disclosure of confidential data, denial of service, server side request forgery, port scanning from the perspective of the machine where the parser is located, and other system impacts.

# Where the Issue Occurred
The following code snippets display the usage of `XMLReader` without disabling entities:
https://github.com/eclipse/rdf4j/blob/e0718b2f53aea1385848c36bd8819b775ec5edb0/rio/trix/src/main/java/org/eclipse/rdf4j/rio/trix/TriXParser.java#L188

https://github.com/eclipse/rdf4j/blob/e0718b2f53aea1385848c36bd8819b775ec5edb0/rio/rdfxml/src/main/java/org/eclipse/rdf4j/rio/rdfxml/RDFXMLParser.java#L328

**Comment by jeenbroekstra** [comment]
relevant link https://www.owasp.org/index.php/XML_External_Entity_(XXE)_Prevention_Cheat_Sheet#JAXP_DocumentBuilderFactory.2C_SAXParserFactory_and_DOM4J

**Comment by barthanssens** [comment]
org.eclipse.rdf4j.rio.rdfxml.RDFXMLParser.java sets the XMLParserSettings.SECURE_PROCESSING (line 270), not sure if that covers all the settings mentioned in the OWASP cheat sheet

The TrixParser does not seem to do this

**Comment by barthanssens** [comment]
IMHO the TrixParser and RDFXMLParser should be reworked to extend a common AbstractRDFParserXML, there seems to be some code duplication (and I assume it would be better to fix this issue in this common parent)

**Comment by ruchim** [comment]
Is there any chance this vulnerability will be patched sometime soon?

**Comment by barthanssens** [comment]
a quick and dirty patch shouldn't be too hard, (testing can be a bit cumbersome though), but a more elegant solution as mentioned above is going to take a bit longer :-/

**Comment by ruchim** [comment]
I think a patch should work well enough for us! Is it possible to provide an estimate on when you think a patch could be released?

**Comment by kshakir** [comment]
Here are changes that copy-paste the code from @jeenbroekstra link, plus unit tests.

https://github.com/eclipse/rdf4j/compare/master...kshakir:xxe_xmlparser

I'll try to figure out the CLA stuff, but if anyone else wants to submit the changes please go ahead.

**Comment by jeenbroekstra** [comment]
A third place we also need to look at is the SparqlXmlResultsReader. I will try and make these settings configurable (with secure defaults) so that parsing files that legit use doctypes and (heaven forbid) external entities or external dtds is still possible.

**Comment by jeenbroekstra** [comment]
@ruchim @ProDigySML we've received a request to loosen some of these restrictions due to the fact that many valid RDF data sets use doctype declarations and DTDs, and these restrictions suddenly make it impossible to import these files. See #1202 - if you have any views on this could you comment on that issue?
