### ISSUE TITLE
Inefficient parsing of CSV files

### ISSUE THREAD

**Issue by andrewruckerjones** [eclipse/rdf4j#1060]
As a developer of opencsv, I am interested in how projects use opencsv, and trying to get projects to use the latest version, if it is to their advantage.

Upon reviewing the use of opencsv in rdf4j, I discovered two things that should greatly improve performance of parsing CSV files, as well as TSV files:

1. rdf4j uses version 3.5 of opencsv, which is 8 versions out of date. Versions starting with 4.0 can process CSV records in parallel, increasing performance.
2. Parsing of CSV and TSV files uses a regular expression that is recompiled on every pass through a loop, which is very inefficient.

I am submitting a pull request that updates the POM to use opencsv 4.2 and refactors parsing of CSV files to take advantage of the parallelism in opencsv. Parsing of TSV files could probably be improved the same way, but I have not examined that closely. (opencsv can easily use a tab as the separator.) The pull request also moves the reused regular expression to a final class variable to eliminate recompilation.

**Comment by jeenbroekstra** [comment]
Thanks for this Andrew! We'll need to put the new version of opencsv through Eclipse legal review before we can include it in a release, but I don't expect there to be any issues. 

CQ logged here https://dev.eclipse.org/ipzilla/show_bug.cgi?id=17088
