### ISSUE TITLE
SparqlQueryRenderer does not support SPARQL 1.1

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#107]
(Migrated from https://openrdf.atlassian.net/browse/SES-2206 )

SPARQL 1.1 constructs cannot be rendered via the SparqlQueryRenderer class.  

For example If I parse this query with QueryParserUtil.parseQuery:

{code}
SELECT * WHERE {
  ?s ?p ?o .
  BIND(uri("http://test-graph.com/") AS ?foo) .
}
{code}

And then render the ParsedQuery back out again with SPARQLQueryRenderer, it appears to lose the binding clause, returning the following string:

{code}
select ?g ?s ?p ?o ?g2
where {
  GRAPH ?g {
    ?s ?p ?o.
}}
{code}

Looking at renderTupleExpr in SparqlTupleExprRenderer I can see that the following lines are commented out:

{code:java}
        // aRenderer.mProjection = new ArrayList<ProjectionElemList>(mProjection);
        // aRenderer.mDistinct = mDistinct;
        // aRenderer.mReduced = mReduced;
        // aRenderer.mExtensions = new HashMap<String, ValueExpr>(mExtensions);
        // aRenderer.mOrdering = new ArrayList<OrderElem>(mOrdering);
        // aRenderer.mLimit = mLimit;
        // aRenderer.mOffset = mOffset;
{code}

With the following commented out in SPARQLQueryRenderer:

{code:java}
                        // SPARQL does not support this, its an artifact of copy and
                        // paste from the serql stuff
                        // aQuery.append(mRenderer.getExtensions().containsKey(aElem.getSourceName())
                        // ?
                        // mRenderer.renderValueExpr(mRenderer.getExtensions().get(aElem.getSourceName()))
                        // : "?"+aElem.getSourceName());
                        //
                        // if (!aElem.getSourceName().equals(aElem.getTargetName()) ||
                        // (mRenderer.getExtensions().containsKey(aElem.getTargetName())
                        // &&
                        // !mRenderer.getExtensions().containsKey(aElem.getSourceName())))
                        // {
                        // aQuery.append(" as ").append(mRenderer.getExtensions().containsKey(aElem.getTargetName())
                        // ?
                        // mRenderer.renderValueExpr(mRenderer.getExtensions().get(aElem.getTargetName()))
                        // : aElem.getTargetName());
                        // }
{code}

I believe these lines are commented out in error and that they should be commented back in in order to get be able to round trip queries from SPARQL text into the AST and back out again.  

Other SPARQL 1.1 queries that fail include:

{code}
SELECT (COUNT (*) as ?c) WHERE { ?s ?p ?o }
{code}

is rendered as

{code}
select ?c where { ?s ?p ?o }
{code}

and the query

{code}
SELECT (?p as ?x) WHERE { ?s ?p ?o }
{code}

is rendered as

{code}
select ?p WHERE { ?s ?p ?o }
{code}

**Comment by pulquero** [comment]
Hit this issue today. What is the best way to render sparql from the AST? I see FedX has its own utils for doing this: https://github.com/eclipse/rdf4j/blob/master/tools/federation/src/main/java/org/eclipse/rdf4j/federated/util/QueryStringUtil.java. I guess I could just extend the RDF4J class and add the missing visitors, oh wait, its final.... I guess I'll have to resort to copy&paste then 👎
