### ISSUE TITLE
Unable to register repository in LocalRepositoryManager in RDF4J 2.4.0-M3

### ISSUE THREAD

**Issue by reckart** [eclipse/rdf4j#1077]
A `NoSuchFileException` is generated when trying to register a new repository using the `LocalRepositoryManager` in RDF4J 2.4.0-M3. 

RDF4J 2.4.0-M1 and RDF4J 2.4.0-M2 are not affected.

```
org.eclipse.rdf4j.repository.config.RepositoryConfigException: java.nio.file.NoSuchFileException: /*snip*/config.ttl.part
	at org.eclipse.rdf4j.repository.manager.LocalRepositoryManager.addRepositoryConfig(LocalRepositoryManager.java:450) ~[rdf4j-repository-manager-2.4.0-M3.jar:2.4.0-M3+e7b4116]
	at org.eclipse.rdf4j.repository.manager.LocalRepositoryManager.addRepositoryConfig(LocalRepositoryManager.java:418) ~[rdf4j-repository-manager-2.4.0-M3.jar:2.4.0-M3+e7b4116]
	... *snip*
Caused by: java.nio.file.NoSuchFileException: /Users/bluefire/UKP/Library/inception/kb/repositories/pid-44-kbid-11/config.ttl.part
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86) ~[?:1.8.0_181]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:1.8.0_181]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:1.8.0_181]
	at sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:409) ~[?:1.8.0_181]
	at sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:262) ~[?:1.8.0_181]
	at java.nio.file.Files.move(Files.java:1395) ~[?:1.8.0_181]
	at org.eclipse.rdf4j.repository.manager.LocalRepositoryManager.addRepositoryConfig(LocalRepositoryManager.java:448) ~[rdf4j-repository-manager-2.4.0-M3.jar:2.4.0-M3+e7b4116]
	... 183 more
```

**Comment by reckart** [comment]
Not sure of that. I did a little tentative debugging and it seems to me that the registration is starting, and a `.part` file is written, then some notification mechanism is triggered which causes the the configuration to be written *again* to a `.part` file which is eventually renamed, then the notification ends and at that point, the originally calling code doesn't find the `.part` file for renaming anymore.

**Comment by barthanssens** [comment]
Would there any example code that we could take a look at ?

I've tried to reproduce it on Windows 10 with JDK 8 and RDF4J 2.4.0-M3, but the code below worked, so probably I'm missing something

```
RepositoryManager mgr = new LocalRepositoryManager(new File("."));
mgr.initialize();
InputStream is = Files.newInputStream(Paths.get("x:/temp/memory.ttl"));
Model res = Rio.parse(is, "http://example.com", RDFFormat.TURTLE);
Resource node = Models.subject(
    res.filter(null, RDF.TYPE, RepositoryConfigSchema.REPOSITORY))
         .orElseThrow(() -> new RepositoryConfigException("missing repository node"));
		
RepositoryConfig rc = RepositoryConfig.create(res, node);
rc.validate();
mgr.addRepositoryConfig(rc);

Repository repo = mgr.getRepository(rc.getID());
repo.initialize();
```

**Comment by reckart** [comment]
@barthanssens The problem happens when an old `SYSTEM` repository still lies around in the repositories directory. I cannot write a unit test for it because the methods for creating the system repo  have been remove. However, if it is present, then a `ConfigChangeListener` may be registered when adding repos which eventually triggers the reported problem.

So I guess the fix should be to remove more of the deprecated code which concerns the `SYSTEM` repo.

**Comment by reckart** [comment]
Actually, I can write test for it ;)

```
        RepositoryManager mgr = RepositoryProvider
                .getRepositoryManager("target/test-output/repo-manager");
        
        new File("target/test-output/repo-manager/repositories/SYSTEM").mkdirs();
        
        RepositoryImplConfig cfg = new SailRepositoryConfig(new NativeStoreConfig());

        mgr.addRepositoryConfig(new RepositoryConfig(mgr.getNewRepositoryID("pid-1-kbid-"), cfg));
        mgr.addRepositoryConfig(new RepositoryConfig(mgr.getNewRepositoryID("pid-1-kbid-"), cfg));
```

**Comment by barthanssens** [comment]
Indeed, moving the 
```
if (updateSystem) {
   super.addRepositoryConfig(config);
}
```
after the try/catch block at the end of the function `LocalRepositoryManager.addRepositoryConfig()` ,  line 445, seems to fix it (at least for the example mentioned above)

**Comment by jeenbroekstra** [comment]
Sounds like you've narrowed it down. Is either of you available to submit a PR with a regression test and a patch?

**Comment by barthanssens** [comment]
I've added a small patch (not sure if there are side-effects though, maybe @reckart can test it in a more realistic environment) + unit test.
Unfortunately Travis CI has some connection timeouts and, in the end, the job time limit is exceeded :-/

**Comment by HansBrende** [comment]
@jeenbroekstra @barthanssens 
FYI: @reckart was able to verify that PR #1078 fixed this bug. See [conversation](https://github.com/inception-project/inception/issues/508#issuecomment-425388276).

Does this mean that this issue can now be closed? (I ask since it is the last remaining open issue in the [2.4.0 milestone](https://github.com/eclipse/rdf4j/milestone/24)...)

**Comment by barthanssens** [comment]
As far as I'm concerned it can be closed

**Comment by jeenbroekstra** [comment]
:+1:
