### ISSUE TITLE
TurtleWriter with INLINE_BLANK_NODES loses bnode id when bnode is referenced more than once

### ISSUE THREAD

**Issue by pmaria** [eclipse/rdf4j#1079]
Writing Turtle using `BasicWriterSettings.INLINE_BLANK_NODES` where a blank node is referenced more than once leads to incorrect serialisation.

There is a warning in the Javadoc of this option that states

> Inline blanks nodes by their value and don't write any blank node labels when this setting is true.
This setting should only be used when blank nodes never appear in the context and there are no blank node cycles.

But I don't know if that covers this case. I don't understand what is meant by "never appear in the context".

Here is a snippet which reproduces the issue:

```java
ValueFactory vf = SimpleValueFactory.getInstance();
    
BNode bnode = vf.createBNode("bnode");

Model model = new ModelBuilder().subject("http://ex.com/subject")
	.add(vf.createIRI("http://ex.com/rel1"), bnode)
	.add(vf.createIRI("http://ex.com/rel2"), bnode)
	.subject(bnode)
	.add(RDFS.LABEL, "the bnode")
	.build();

model.setNamespace(RDFS.NS);
model.setNamespace("ex", "http://ex.com/");
StringWriter sw = new StringWriter();
BufferedWriter writer = new BufferedWriter(sw);
WriterConfig config = new WriterConfig();
config.set(BasicWriterSettings.INLINE_BLANK_NODES, true);
Rio.write(model, writer, RDFFormat.TURTLE, config);
System.out.println(sw.toString());
```

The result of this is:

```
@prefix ex: <http://ex.com/> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

ex:subject ex:rel1 [
      rdfs:label "the bnode"
    ];
  ex:rel2 [] .
```

While I would expect the writer not to inline the blank node, which in this case is the object of two triples.

```
@prefix ex: <http://ex.com/> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

ex:subject 
	ex:rel1 _:bnode ;
	ex:rel2 _:bnode .

_:bnode rdfs:label "the bnode" .

```

**Comment by Mirr99** [comment]
Hi
I would like to work on this issue. Can it be assigned to me?

**Comment by barthanssens** [comment]
Sure, any help is appreciated :-)

**Comment by Mirr99** [comment]
Hi

I have been successful in recreating the bug and have been looking at how to go about solving it. I just want to confirm my understanding of the expected output. It is the following, right?

@prefix ex: <http://ex.com/> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

ex:subject ex:rel1 [
      rdfs:label "the bnode"
    ];
  ex:rel2 [
      rdfs:label "the bnode"
    ];

**Comment by jeenbroekstra** [comment]
@Mirr99 sorry for not noticing your reply sooner. I believe the actual expected output is as described in the original comment:

```
@prefix ex: <http://ex.com/> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

ex:subject 
	ex:rel1 _:bnode ;
	ex:rel2 _:bnode .

_:bnode rdfs:label "the bnode" .
```

The difference between this and your proposed output is that here, it is explicit that the values of `ex:rel1` and `ex:rel2` are the same resource. In your solution, this is left implicit (and in fact, most readers of this will produce a result where `rel1` and `rel2` get _different_ bnode identifiers).

**Comment by Mirr99** [comment]
If I understand correctly, when a blank node is referenced multiple times and INLINE_BLANK_NODES is set to true, we want the writer not to inline the blank nodes at all.

So if we have two blank nodes, and only one of them is referenced more than once, is the writer expected to inline the one which is referenced once or not inline both of them?

**Comment by jeenbroekstra** [comment]
> If I understand correctly, when a blank node is referenced multiple times and INLINE_BLANK_NODES is set to true, we want the writer not to inline the blank nodes at all.
 
I think that's correct, yes.

> So if we have two blank nodes, and only one of them is referenced more than once, is the writer expected to inline the one which is referenced once or not inline both of them?

If I understand what you're saying,  you mean this situation where one bnode is referred to twice, and another only once:

```
@prefix ex: <http://ex.com/> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

ex:subject 
	ex:rel1 _:bnode1 ;
	ex:rel2 _:bnode1 ;
        ex:rel3 [ rdfs:label "bnode 2" ].

_:bnode1 rdfs:label "bnode 1" .

```

I'd say that I'd expect the output to be as I've shown it here.

**Comment by Mirr99** [comment]
Thanks for the clarification. I'll update the PR accordingly.
