### ISSUE TITLE
Add data to named graph

### ISSUE THREAD

**Issue by nicky508** [eclipse/rdf4j#1081]
I have develop a application which needs to add data to a graphstore. The connection works perfectly fine. However I want to add rdf data from a string to a named graph, but it does not work. I have the following method:

```
public void updateModelinGraph(String uri, Model model) {
		ValueFactory vf = conn.getValueFactory();
		ModelBuilder builder = new ModelBuilder();
		StringWriter sw = new StringWriter();
		RDFDataMgr.write(sw, model, RDFFormat.TURTLE);
		URI context= vf.createURI(uri);
		conn.begin();
		conn.add(new StringReader(sw.toString()), "", RDFFormat.TURTLE, context);
		conn.commit();
		conn.close();
	}
```

Eclipse underlines add and drops: 
`The method add(InputStream, String, RDFFormat, Resource...) in the type RepositoryConnection is not applicable for the arguments (StringReader, String, RDFFormat, URI)`

It seems it is caused by the context, but I do not have any clue how to make it work? The current method using the ValueFactory is described in the docs of RDF4J.

**Comment by barthanssens** [comment]
Hi,

hmz, the example seems to be a bit outdated (since it mentions the deprecated URI instead of IRI). Could you please point out where exactly (link/chapter), so it can be corrected ?

Is there a need for moving the code from the Model into a string ?
You may want to use something like this instead:

```
ValueFactory vf = conn.getValueFactory();
Resource context = vf.createIRI(uri);
conn.add(m, context);
```

**Comment by nicky508** [comment]
Hi,

Thnx for your help. I used the http://docs.rdf4j.org, however I cannot find it back. However the issue I have to solve. We a piece of software using jena internally, the software is using abstraction layers to communicate with different graphstores. Now I am working on a new layer for GraphDB, which works with RDF4J. The model in the argument is a jena model. I think the most convenient way to create a rdf4j model from the jena model is writing the content of the jena model to a string and read it into a rdf4j model.

**Comment by barthanssens** [comment]
Ah ok.
Well I don't use Eclipse, but it seems to be confused about the parameters (the Eclipse warning also mentions _InputStream,_ not _Reader_) perhaps this helps

> Resource context = vf.createIRI(uri);
> ...
> conn.add(new StringReader(sw.toString()), "", RDFFormat.TURTLE, context);

You may also want to check  the RDF4J version, is it 2.3.x ? (GraphDB 8.6.x)

**Comment by nicky508** [comment]
Yes, version are correct. I have found another solution. I use the statements from Jena and figure out the datatypes of the objects and create them in a RDF4j Model. For now it works, probably it needs some improvements later on:

```
public void updateModelinGraph(String uri, Model model) {
		ValueFactory vf = conn.getValueFactory();
		ModelBuilder builder = new ModelBuilder();
		Iterator<Statement> mStats = model.listStatements();
		while(mStats.hasNext()){
			Statement s = mStats.next();
			RDFNode obj = s.getObject();

			if(obj.isResource()){
				builder.namedGraph(uri).add(s.getSubject().toString(), s.getPredicate().toString(), vf.createIRI(s.getObject().asNode().getURI()));
			}else{
				builder.namedGraph(uri).add(s.getSubject().toString(), s.getPredicate().toString(), JenaObjToRdf4JObj(s.getObject(), vf));
			}

			conn.begin();
			conn.add(builder.build());
			conn.commit();
			conn.close();
		}
	}
```

Again thanks for your help!
