### ISSUE TITLE
Document docker image

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#1091]
_From @jeenbroekstra on June 22, 2018 5:3_

either in reference documentation or by adding a link to the download section of the project website (or both). 

_Copied from original issue: eclipse/rdf4j-doc#60_

**Comment by jeenbroekstra** [comment]
followup of eclipse/rdf4j-tools#15

**Comment by jeenbroekstra** [comment]
@barthanssens my docker-foo is rather rusty, so can you help me out with the following: 

1. should we be pushing this docker image to some public docker repo to make it easy to use? And if so, do you know how we should set that up? 
2. what do you think is a good spot to put a link to the README so people can find the docker image? Just on the download section of the website? Or should we put something in the doco instead?

**Comment by jeenbroekstra** [comment]
_From @barthanssens on July 15, 2018 21:43_

@jeenbroekstra IMHO the best way would be to add it to the "official" docker hub, as part of the Eclipse project.

I guess the Eclipse Project Management Committee should know more about this, since
a few projects like Eclipse Che and Mosquitto have found their way into this hub (https://hub.docker.com/r/eclipse/)

Eclipse Che puts the docker readme in the dockerfiles subdirectory, and there is the standard short description on the docker hub as well

https://github.com/eclipse/che/tree/master/dockerfiles

**Comment by barthanssens** [comment]
@jeenbroekstra just wondering: are you working on this, or do you want me to contact Eclipse PMC or one of the other Eclipse projects to check how they got their project into the docker hub ?

**Comment by jeenbroekstra** [comment]
I'm not actively working on this. If you could have a try that'd be great. Another possible forum to ask around might be the i[ncubation mailinglist](https://dev.eclipse.org/mailman/listinfo/incubation) - sign up for it if you haven't yet, it's a good source of info for the Eclipse Way of Doing Things(tm).

**Comment by barthanssens** [comment]
Some additional info https://www.eclipse.org/projects/handbook/#resources-dockerhub

**Comment by barthanssens** [comment]
Email was sent to EMO to get some help / permissions on the hub.docker.com Eclipse org
