### ISSUE TITLE
US-ASCII in TxnStatusFile is slower than using UTF-8

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#1108]
_From @hmottestad on February 16, 2018 16:13_

TxnStatusFile uses US-ASCII for encoding files. Switching to UTF-8 makes org.eclipse.rdf4j.sail.SailConcurrencyTest#testConcurrentAddLargeTxn 20% faster. StandardCharsets.UTF_8

Is there a reason for using US-ASCII?

Switching to UTF-8 will probably break existing NativeStores. So there needs to be some code for handling legacy stores. Options:
 - Autodetect encoding
 - Option for NativeStore (default: USC-ASCII)
 - Migrate existing stores automatically

_Copied from original issue: eclipse/rdf4j-storage#44_

**Comment by hmottestad** [comment]
@jeenbroekstra I was wondering about picking this up again. I'm a bit worried if this would be considered non-backwards compatible? My worry is if someone tries to upgrade while a transaction is running, then I reckon it would crash when starting up again. However, if the nativestore was properly shutdown it shouldn't cause any issues.
