### ISSUE TITLE
Upgrade Lucene, Solr and elastic search to Lucene 7.x

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#1114]
_From @aschwarte10 on June 7, 2018 9:15_

In https://github.com/eclipse/rdf4j-storage/issues/71 we updated lucene and derived modules to Lucene 6.x.

This issue is a follow up to update versions to Lucene 7.x

_Copied from original issue: eclipse/rdf4j-storage#77_

**Comment by jeenbroekstra** [comment]
@aschwarte10 if I give you a crash course in how the Eclipse review process works, do you think you could take the lead on actually submitting the required CQs for this? I'd rather enjoy it if someone else could do it for once... 

It's not actually hard, just a bit of a drag. For each dependency, and any transitive dependencies that come with that, you'd need to [create a CQ](https://www.eclipse.org/projects/handbook/#pmi-commands-cq) - this is basically just an issue in legal team's bugtracker, IPZilla. The CQ submission tool has some smarts - it will show versions of the library you're trying to add. If our version is already in there, pick that, and it will create a so-called "Piggyback CQ". This is just a record that rdf4j, too, uses this library which has already been approved for another Eclipse project. These CQs typically get approved almost instantly. 

If the version of the library doesn't already exist, you'll need to fill out a short form with the name and a short description (typically just a oneliner), what license it's distributed under, and a link to the project's website and source code repo. The last step is easy to forget: once the CQ issue is created, you should attach the actual source code of the library to the CQ. The easiest way to do this is just to download the source-jar from Maven Central and attach that. 

Things that make this a little easier: 
1. we don't need CQs for patch version bumps of dependencies.
2. we have a couple of "works-with" dependencies, for libraries that we use but don't actually include in our distribution (e.g. elasticsearch-testframework, assertj, and so on). For these kinds of dependencies, you don't need to log any CQs for transitive dependencies (so if assertj depended on, say, log4j, we don't need a CQ for log4j).

The goal of all of this is twofold:
1. we have an accurate of what third-party software we actually include. 
2. we can make a guarantee to our users that our software does not contain any hidden legal nastiness (e.g. stolen code, hidden patented stuff) that could bite them in the behind when they use rdf4j in their own project. 

Anyway, let me know if you want to give it a crack.

**Comment by barthanssens** [comment]
Hi @jeenbroekstra , @aschwarte10 

is one of you planning to create the CQ's ?
If not, I'd be willing to enter the CQ's (getting used to filing them anyway) and list them here.

Bart

**Comment by jeenbroekstra** [comment]
I'm currently a bit tied up at work so have little time for the next two weeks. If you want to give this a go please do! Keep in mind that for elasticsearch we logged a 'works-with' CQ. This means that we don't need to log CQs for its transitive dependencies, at the cost of not distributing those libraries in our releases.

**Comment by barthanssens** [comment]
Ok, I'v noticed ES 6.5 is available now (ES releases quite often these days), which uses Lucene 7.5.

And it happens to be that there are already Eclipse CQ's for various Lucene 7.5 parts, so using the latest and greatest saves quite a bit of time/effort.

**Comment by barthanssens** [comment]
[ ] Elasticsearch Transport 6.5.0 (CQ18241 - works_with)
[ ] Elasticsearch Test Framework (CQ18242 - works_with)

(rest to be added, piggyback on lucene 7.5.0)

**Comment by barthanssens** [comment]
added a comment on cq18299

**Comment by jeenbroekstra** [comment]
@barthanssens, I wonder what the holdup is. Diff review may be larger than we think (it's a major version bump after all). FYI when they "proceed with checkin" they mean that we are ok to use the dependency in our code repository, but _not yet_ do any official releases that include it.

I don't want to merge until we have full aproval though, so that we have the option to do a release without this particular improvement if CQs are still not complete.

**Comment by barthanssens** [comment]
Thanks for the info. Merging before approval would indeed not be OK...

But I guess we can start testing in a feature branch (from limited experience with ES, I do expect some things to break)

**Comment by jeenbroekstra** [comment]
@barthanssens good point. There's a feature branch for this, or rather a pull request submitted by @aschwarte10 . It needs some TLC though, it has merge conflicts with the current develop branch. I think @aschwarte10 's fork is editable for rdf4j committers, so if he's not available to fix we can do so ourselves, and use it for testing.

**Comment by barthanssens** [comment]
Still waiting for analysis of 4 of the libraries + added a new one (backwards-codecs, seems to be missing in the distribution of RDF4J 2.4)

**Comment by jeenbroekstra** [comment]
CQs are approved but as discussed, it's too close to release date and we have doubts about stability and backward compatibility. Postponed to 3.0.

**Comment by hmottestad** [comment]
Since we are on 3.0 now, I guess we can start working on this. Would the correct approach be to bump 
https://github.com/eclipse/rdf4j-storage/pull/78 to the versions described in the CQ?

**Comment by barthanssens** [comment]
Well, there's not that much choice from the Eclipse IPR point of view: 
* either we use ES 6.5.x + Solr 7.5.x mentioned above (which are fairly recent, though not the most recent, but a big step forward anyway)
* or it's another round of getting CQ's approved if older or newer minor releases are to be used...
