### ISSUE TITLE
Add description of repository types to Workbench documentation 

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#1121]
_From @jeenbroekstra on August 6, 2018 4:6_

From user feedback: 

I note the many new repository types. I already know (or I think I can guess) the meaning of most on the list.  But for a new user, a link to some documentation, or even a tooltip, that explains all of them would be nice. Actually, I'm not a new user, and I have no idea what some of them do.

The lists given in sections 2.1.4 and 3.2.5 of http://docs.rdf4j.org/server-workbench-console/ are incomplete, and I didn't (yet) find explanations of the missing ones elsewhere in the documentation.

_Copied from original issue: eclipse/rdf4j-doc#61_

**Comment by jeenbroekstra** [comment]
_From @rwalkerands on August 6, 2018 4:42_

Copy/pasting my follow-up message from the mailing list:

OK, now I found the descriptions tucked away in sections 3 and 5 of http://docs.rdf4j.org/programming/.

**Comment by zdkg** [comment]
Hi, I'd like to pick up this issue.
