### ISSUE TITLE
Announcement: Code Generation from RDF/OWL to Object Oriented compatible with RDF4J

### ISSUE THREAD

**Issue by charbull** [eclipse/rdf4j#1126]
Hello,

I was not sure if I should post this here but it could help the community.

We just released OLGA 0.0.4 on github https://ecostruxure.github.io/OLGA/ under MIT License.
OLGA is an Ontology Library Generator for developers to accelerate ontology development by providing Object Oriented libraries.
The current release supports the following features:
-	Reduced warning for the C# code generation with Trinity
-	Code generation support for RDF4J/ Java
-	Code generation support for RDFAlchemy/ Python
-	Support of OLGA Command Line Interface
-	Support for OLGA WebService through Spring

Please give it a try, or help us improve it. We are happy to help if you have any questions.

Best,
C.

**Comment by jeenbroekstra** [comment]
Hi @charbull, sounds intriguing! I look forward to taking OLGA for a test drive.

Perhaps a better place to announce your project is the [rdf4j-users forum ](https://groups.google.com/d/forum/rdf4j-users). Feel free to sign up and post an announcement there.

We could perhaps also do a short blurb about it on the rdf4j.org news page.

**Comment by charbull** [comment]
Thank you @jeenbroekstra I just announced there !
looking forward to get feedback from the community
