### ISSUE TITLE
GeoSPARQL: geof:buffer() does not work

### ISSUE THREAD

**Issue by barthanssens** [eclipse/rdf4j#1128]
(From RDF4J-users forum: https://groups.google.com/forum/#!topic/rdf4j-users/mZRv5MLCcNs)

Hi I have successfully tested some geospatial features of RDF4J 2.4.0-M3 such as geof:sfIntersects() but came accross some Ring Intersection problems with some complex polygons of the CORINE dataset.

I tried to follow the advice of some more experienced users and most of them suggested to use, as a common workaround, the  geof:buffer() on one or both geometries that I am trying to intersect.

However geof:buffer() does not work at all.

I have used it both through java api and I confirmed its failure through the workbench as well. I have enabled the geospatial algebra jar in the classpath of tomcat so geospatial is enabled.

The following query executes correctly by returning 'false' in the RDF4J Workbench and Java API solution. This query returns the same result with GraphDB v8.6.1:
```
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>  
PREFIX lgd: <http://data.linkedeodata.eu/ontology#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT (geof:sfIntersects(?o1, "POINT(24.708496093749996 37.95719224376526)"^^<http://www.opengis.net/ont/geosparql#wktLiteral>) as ?interO1)
WHERE {
    BIND(("POLYGON((23.708496093749996 37.95719224376526,22.906494140625 40.659805938378526,11.524658203125002 48.16425348854739,-0.1181030273437499 51.49506473014367,-3.2189941406250004 55.92766341247031,-5.940856933593749 54.59116279530599,-3.1668090820312504 51.47967237816337,23.708496093749996 37.95719224376526))"^^<http://www.opengis.net/ont/geosparql#wktLiteral>) as ?o1).
}
```

The following 2 queries fail in RDF4J Workbench and through Java API solution:
```
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>  
PREFIX lgd: <http://data.linkedeodata.eu/ontology#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT (geof:buffer("POINT(23.708496093749996 37.95719224376526)"^^<http://www.opengis.net/ont/geosparql#wktLiteral>, 1, <http://www.opengis.net/def/uom/OGC/1.0/metre>) as ?o2)
WHERE { }
```

```
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>  
PREFIX lgd: <http://data.linkedeodata.eu/ontology#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT ?o2
WHERE {
    BIND(geof:buffer("POINT(23.708496093749996 37.95719224376526)"^^<http://www.opengis.net/ont/geosparql#wktLiteral>, 1, <http://www.opengis.net/def/uom/OGC/1.0/metre>) as ?o2) .
}
```

**Comment by jeenbroekstra** [comment]
possibly related to #1127

**Comment by jeenbroekstra** [comment]
Looks like the cause is over-zealous function argument evaluation. The second argument translates internally to an xsd:integer literal, but for some reason the buffer function requires a double. I'll doublecheck the specs but I think this is likely just being too strict on the datatype.

**Comment by tioannid** [comment]
Hi
I tested the 2.4-SNAPSHOT for this issue and it seems it is fixed!
Thanks

**Comment by jeenbroekstra** [comment]
Thanks for confirming @tioannid ! Patch release 2.4.1 is scheduled to go out today or tomorrow.
