### ISSUE TITLE
how preserve blank node id

### ISSUE THREAD

**Issue by TamouzeAssi** [eclipse/rdf4j#1130]
I m looking for a tools to use in my project. Im checking RDF4J it is looks easy to use but before to go deep i have a question about blank nodes. does RDF4J preserve the the blank node id as it given in the rdf file before parsing. Infact suppose the id of a given blank node in a rdf file is nodexxxx, how i can get the same id (i.e. nodexxxx) after parsing? My obejctive is to make some treatement on blank node so if if the name change i cant keep track

**Comment by jeenbroekstra** [comment]
It's a matter of configuring the parser. Have a look at the rdf4j documentation, at docs.rdf4j.org, specifically Programming with RDF4J. It's got a section about parser configuration.

As an aside could you please use the rdf4j user forum for future support questions? The issue tracker is really only meant for bug report or feature requests. See http://rdf4j.org/support/
