### ISSUE TITLE
Misuse of pattern matching in URIUtil

### ISSUE THREAD

**Issue by HansBrende** [eclipse/rdf4j#1131]
In `URIUtil.isValidURIReference(String)`, I see the following misuse of pattern matching:

```java
// check that string contains no Unicode control characters.
boolean valid = !uriRef.matches("[\u0000-\u001F\u007F-\u009F]");
```

This pattern will only match a string if it contains exactly one character. I'm assuming the intended semantics was: `!uriRef.matches(".*[\u0000-\u001F\u007F-\u009F].*")`

Note the semantics of `String.matches()`:
```java
assert "aXb".matches("[0-9A-Z]") == false;
assert "aXb".matches(".*[0-9A-Z].*") == true;

assert Pattern.compile("[0-9A-Z]").matcher("aXb").matches() == false;
assert Pattern.compile("[0-9A-Z]").matcher("aXb").find() == true;
```

**Comment by jeenbroekstra** [comment]
This sounds like a bug to me. Fix should be straightforward.
