### ISSUE TITLE
Slightly more efficient usage of opencsv

### ISSUE THREAD

**Issue by andrewruckerjones** [eclipse/rdf4j#1132]
Just as in my issue 1060 for CSV processing, I have moved TSV processing over to take advantage of the multithreading opencsv offers and to reduce code duplication. At the same time, I bumped the version of opencsv used from 4.2 to 4.3.2. Expect a pull request shortly.

**Comment by barthanssens** [comment]
CQ 17911 submitted

**Comment by jeenbroekstra** [comment]
@barthanssens thanks for picking that up. Don't forget to attach the source code to the CQ (easiest way to do that is to download the source-jar from Maven Central and add it to the CQ as an attachment).

**Comment by barthanssens** [comment]
Ok, done, thanks for the info @jeenbroekstra

**Comment by barthanssens** [comment]
License has just been approved by Eclipse  PMC, "license_certified"
