### ISSUE TITLE
Deprecated URI in SPIN EvalFunction

### ISSUE THREAD

**Issue by barthanssens** [eclipse/rdf4j#1135]
In org.eclipse.rdf4j.spin.function.EvalFunction, the deprecated URI is used instead of IRI in `isQuery()` and `addArguments`

**Comment by navdhaagarwal** [comment]
Hi! 
We (me and @shubhi0108) were working on this issue. As said, the functions `isQuery()` and `addArguments()` were using deprecated URI hence we have replaced then with IRI. Please guide us with what needs to be done further in this issue. 

So far I have covered the legalities, forked the repository, created a new branch as per the [guidelines](https://github.com/eclipse/rdf4j/blob/master/.github/CONTRIBUTING.md#how-to-contribute) and have committed the changes on that branch and verifying the existing testcases.

**Comment by barthanssens** [comment]
Names have been added to the 3.3.0 release notes #2235

**Comment by navdhaagarwal** [comment]
Thank you @barthanssens
