### ISSUE TITLE
RDFSchemaMemoryRepositoryConnectionTest generates warnings

### ISSUE THREAD

**Issue by barthanssens** [eclipse/rdf4j#1143]
org.eclipse.rdf4j.repository.sail.memory.RDFSchemaMemoryRepositoryConnectionTest, org.eclipse.rdf4j.repository.sail.memory.CustomGraphQueryInferencerMemoryRepositoryConnectionTest and org.eclipse.rdf4j.repository.sail.memory.SchemaCachingRDFSInferencerRDFSchemaMemoryRepositoryConnectionTest generate a few warnings like this
`
[Rio error] Illegal language tag char: '_' (6, -1)`

**Comment by jeenbroekstra** [comment]
Fwiw I believe these warnings are "normal" in the sense that they are generated by tests that are specifically about how Rio handles illegal language tags. But it couldn't hurt to doublecheck and perhaps to see if this kind of "noise" on standard output can be suppressed.
