### ISSUE TITLE
Migrate to Hugo as platform for project website

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#1154]
We should look into easier/better ways to maintain our project website - we currently use Wordpress for the main site, and a custom-built AsciiDoc setup for the project documentation. Ideally, we can fold things into one, where the website is completely driven by a git repo. Less maintenance, less security concerns, and also we should ensure that our website conform to [Eclipse's requirements](https://www.eclipse.org/projects/handbook/#trademarks-website).

A good option is Hugo: https://gohugo.io/

Used by several Eclipse projects, it seems to fit in well with the general Eclipse modus operandi. Quoting from the incubation list:

> I recommend using our eclipsefdn-hugo-solstice-theme to get started since it includes all the Eclipse Foundation  project website requirements such as our cookie consent banner and our google tag manager ID.
> 
> Hugo is very flexible content management system. For example, iot.eclipse.org is now built using our eclipsefdn-hugo-solstice-theme without the usual EF look and feel. 
> 
> If you are looking for example on how to setup your project, I would recommend taking a look at the following website git repos:
> 
>     jakarta.ee https://github.com/jakartaee/jakartaee.github.io
>     iot.eclipse.org https://github.com/EclipseFdn/iot.eclipse.org
> 
> Our Hugo projects are using NPM to manage dependencies, such as our theme:
> https://www.npmjs.com/package/eclipsefdn-hugo-solstice-theme
> 
> You can install the latest version of the theme via the following command:
> npm install eclipsefdn-hugo-solstice-theme --save
> 
> The source code of our theme includes a website example via the exampleSite folder:
> https://github.com/EclipseFdn/hugo-solstice-theme/tree/master/exampleSite
> 
> If you chose to install our theme using NPM, you will need to update the themeDir variable in your config.toml file to let Hugo know where to find your theme:
> 
> themesDir = "node_modules/"

**Comment by barthanssens** [comment]
Interesting, especially the “static” aspect.

Best regards

Bart

**Comment by barthanssens** [comment]
On a related note, maybe enable HTTPS ? Less of an issue with static sites.
(LetsEncrypt offers certs for free, although auto-renewal requires some software to be installed) 

And another one: check if IPv6 is feasible ?

**Comment by jeenbroekstra** [comment]
@barthanssens both good points. My current thinking is that I want to migrate, as much as possible, to Foundation-maintained infrastructure and hosting first. When we have that set up, we can ask the Eclipse webmaster to arrange for an SSL certificate.

**Comment by jeenbroekstra** [comment]
Btw I pushed a branch with a test setup for Hugo. Needs a lot of work before we're ready to migrate, but it was reassuringly easy to get started, at least. Have a look, comments and additional hands most welcome :)

**Comment by jeenbroekstra** [comment]
The eclipse theme is currently a bit sparsely documented, but there's good examples to at least get something quick and dirty up. Issue EclipseFdn/hugo-solstice-theme#16 tracks a feature request for better getting started documentation, let's keep an eye on that and perhaps share our experiences.

**Comment by jeenbroekstra** [comment]
(copied from comment on PR): I had a closer look and I believe this is actually a problem in the SPARQL AST parser. It has explicit code inside it to "handle" escaped characters (specifically the UnicodeEscapeStream class), and I believe that is messing with things.

**Comment by jeenbroekstra** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=546648
