### ISSUE TITLE
CONCAT does not work on literals with language tags

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#1168]
The CONCAT operator in the SPARQL engine raises a type error when one of its arguments is not a string-typed literal. This causes it to fail on literals with a language tag, since these literals are of type rdf:langString. Root cause is probably a discrepancy between wording in the SPARQL 1.1 spec, and the changes made to literal datatypes in the subsequent RDF 1.1 spec. Whatever the case, the intent of https://www.w3.org/TR/sparql11-query/#func-concat is clearly that language-tagged literals should be accepted as valid input for this operator.

**Comment by VladimirAlexiev** [comment]
- Does it preserve the lang tag as shown in the spec example: output `"foobar"@en`
- Would be nice to extend this to work with subtags, eg
```concat("foo"@en-US,"bar"@en-GB)->"foobar"@en```
- IMHO the third example is slightly wrong: according to RDF 1.1, `"foobar"^^xsd:string` is exactly the same as `"foobar"` so this example shouldn't show the difference that it shows

**Comment by jeenbroekstra** [comment]
@VladimirAlexiev 

1. it does
2. interesting idea. Can you log a feature request for this as a followup?
3. you're right, but this is a result of the SPARQL 1.1 spec predating the RDF 1.1 spec. In the actual implementation in Rdf4j, the first and the second example both produce the same result (an RDF 1.1 string literal) - there is no distinction between a string literal with the xsd:string datatype or without.
