### ISSUE TITLE
Improvement for Federation sail PrepareOwnedTupleExpr optimizer

### ISSUE THREAD

**Issue by pulquero** [eclipse/rdf4j#1183]
Currently, PrepareOwnedTupleExpr does not support UNION. This can lead to the Federation sail breaking up a query that could otherwise be executed as a whole, leading to poor performance. The fix is to simply add a method to handle Union nodes:

> 

	public void meet(final Union node) throws RepositoryException
	{
		final Map<String, String> vars = new HashMap<>();
		final StringBuilder builder = new StringBuilder();
		node.getLeftArg().visit(this);
		if (patternNode != null)
		{
			builder.append("{").append(pattern).append(END_BLOCK);
			vars.putAll(variables);
			node.getRightArg().visit(this);
			if (patternNode != null)
			{
				builder.append("UNION {").append(pattern).append(END_BLOCK);
				vars.putAll(variables);
				this.variables = vars;
				this.pattern = builder.toString();
				this.patternNode = node;
			}
		}
		else
		{
			node.getRightArg().visit(this);
		}

	}

**Comment by pulquero** [comment]
Also, gc churn can be reduced by moving vars and builder declarations inside the first if statement, for all the similar meet() methods.

**Comment by jeenbroekstra** [comment]
Federation Sail was made obsolete a while back, recommended approach is to switch to FedX.
