### ISSUE TITLE
Update jsonld-java to 0.12.3

### ISSUE THREAD

**Issue by ansell** [eclipse/rdf4j#1185]
There is a bug in the new code for #1162 (PR #1186 ) that requires an update of the jsonld-java dependency to 0.12.3 which was released today. 

This is required to pick up a bug fix for non-standard JSON parsing that is optionally allowed by the new code.

I think there is some sort of internal Eclipse legal review required for all upgrades, so separating this into a new issue so it can be tracked separately, but the version bump is in #1186 as it is required for code review.

**Comment by barthanssens** [comment]
Thanks. It's a patch-level update (0.12.1 -> 0.12.3), so a legal review is not required.
