### ISSUE TITLE
Federation QueryMultiJoinOptimizer can NPE for infinite cardinalities

### ISSUE THREAD

**Issue by pulquero** [eclipse/rdf4j#1187]
selectNextTupleExpr() can fail to select a tupleExpr if all cardinalities are greater than Double.MAX_VALUE, i.e. Double.POSITIVE_INFINITY. This can happen for very large number of nested joins that cause cardinality to overflow.

**Comment by barthanssens** [comment]
Is there a query that can be used for testing ?

**Comment by pulquero** [comment]
A query with a lot of joins, around 30. Maybe with a union as the parent.
