### ISSUE TITLE
Add Hydra vocabulary

### ISSUE THREAD

**Issue by barthanssens** [eclipse/rdf4j#1190]
Add a vocabulary class for Hydra (http://www.hydra-cg.com/spec/latest/core/), which can be used by hypermedia APIs (like a semantic version of Swagger / OpenAPI) such as Linked Data Fragments (http://linkeddatafragments.org/specification/)

**Comment by navdhaagarwal** [comment]
Hi!
We (me and @shubhi0108) have started working on this issue. I have added the `HYDRA` class and have added all the classes and properties as stated in [http://www.hydra-cg.com/spec/latest/core/](http://www.hydra-cg.com/spec/latest/core/). We'll add the tests soon. Please let us know what else needs to be done. 
Thank you!

**Comment by navdhaagarwal** [comment]
Hi!
We have added the test and squashed the commits. I'll link the pull request. Please let us know the modification required.
Thank you.

**Comment by barthanssens** [comment]
Thanks for your help, looks good to me !

**Comment by barthanssens** [comment]
Perhaps one minor comment: since it is an enhancement (not a bug), could you make the pull request on the _develop_ branch instead of the _master_ branch ?

No need no create a new pull request, you should be able to just go to https://github.com/eclipse/rdf4j/pull/2291, click on the "edit" button and change the base from "base: master" to "base: develop")

@navdhaagarwal , @shubhi0108

And could you also add your full names as a comment in #2235 , so we can add them to the release notes ?

**Comment by navdhaagarwal** [comment]
Hi,
Please let me know whether some work is left regarding this issue.
Thanks

**Comment by jeenbroekstra** [comment]
Ah, no, thanks, I think this is done! Thanks again :)
