### ISSUE TITLE
Maven shade plugin fails to find rdf4j source jars and fails builds with NPE

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#1195]
We're getting errors in builds when the maven-shade-plugin is activated (in several places): for some reason it can't locate the rdf4j source jars, and then the build fails with a NullPointerException.

While the NullPointerException itself is fixed in a newer shade-plugin release (see https://issues.apache.org/jira/browse/MSHADE-247 ), the question remains why it can't find these source jars in the first place. I have been able to reproduce the same failure locally, even after manually verifying that the source jar it was looking for was available in my local repo. 

And if we take one step further back: why are we even including sources in the shaded jars?

**Comment by jeenbroekstra** [comment]
Right, so, we've fixed the immediate problem (NPE) by bumping the version of the shade plugin. However, the root issues: 
  1 ) why are source jars for rdf4j not found and 
  2) why do we create shaded source jars 

are still open

**Comment by barthanssens** [comment]
No idea why there are shaded sources... doesn't look very useful...

On the NPE / not found issue: jenkins glitch or can it be reproduced locally ? I had another build failure on ci.eclipse, but restarting the job without any changes at all solved the problem :-/

**Comment by jeenbroekstra** [comment]
From taking a closer look I think the shaded source jars are produced because we publish aggregated jars as maven dependencies, for rdf4j-client, rdf4j-storage, and so on. This is not really advertised but they are legit rdf4j maven dependencies and as such having accompanying source jars makes sense.
