### ISSUE TITLE
Add inferred statements to correct graph

### ISSUE THREAD

**Issue by hmottestad** [eclipse/rdf4j#1197]
I've recently discovered that it is very useful that inferred statements are added to the correct graph based on:

 - we use the graph from the added statement
 - we don't consider the potential graphs for the T-box statements (eg. subClassOf, subPropertyOf, ...)

Essentially if you have:
 - Man subClassOf Human

And add "Peter a Man graph1" then the inferred statements "Peter a Human graph1" is added.

**Comment by jeenbroekstra** [comment]
This will be very useful, but it's a backward-incompatible change (as also shown by the fact that it breaks several tests). I think we need to make this a configurable option.

**Comment by hmottestad** [comment]
I will check your example and get back to you.  Simplest is to try to run it. 

Wrt. to backwards compatibility I want to make this the default and make it configurable for those that want the old way. 

Some of the tests that break are fundamental SAIL tests, one of them adds a triple to a graph and checks the size of the graph. That test should also check the size of the default graph as well, but doesn’t. So I’m not very worried about that, except that the test should be counting only real triples and not inferred triples. 

Some of the other tests are tests to stop someone implanting graph support for the existing rdfs reasoner. So not too worried about those either.

**Comment by hmottestad** [comment]
Maybe it should be part of a more major release if I make it default? Or maybe we can make it configurable now and then default in the next major release?

**Comment by jeenbroekstra** [comment]
Yeah, that works. This becomes the configurable alternative in the next minor, then in the next major we switch.

**Comment by hmottestad** [comment]
@jeenbroekstra 

I tried with the following input:
```
		testCon.add(man, RDFS.SUBCLASSOF, human, graph1);
		testCon.add(human, RDFS.SUBCLASSOF, animal, graph2);
		testCon.add(bob, RDF.TYPE, man, graph3);
```

And the queried for:

```testCon.getStatements(man, RDFS.SUBCLASSOF, null,true)```

```
(http://example.org/Man, http://www.w3.org/2000/01/rdf-schema#subClassOf, http://www.w3.org/2000/01/rdf-schema#Resource) [http://example.org/graph1]
(http://example.org/Man, http://www.w3.org/2000/01/rdf-schema#subClassOf, http://www.w3.org/2000/01/rdf-schema#Resource) [http://example.org/graph3]
(http://example.org/Man, http://www.w3.org/2000/01/rdf-schema#subClassOf, http://example.org/Man) [null]
(http://example.org/Man, http://www.w3.org/2000/01/rdf-schema#subClassOf, http://example.org/Animal) [null]
(http://example.org/Man, http://www.w3.org/2000/01/rdf-schema#subClassOf, http://example.org/Human) [http://example.org/graph1]
```

And for:
```testCon.getStatements(bob, RDF.TYPE, null,true)```

```
(http://example.org/bob, http://www.w3.org/1999/02/22-rdf-syntax-ns#type, http://www.w3.org/2000/01/rdf-schema#Resource) [http://example.org/graph3]
(http://example.org/bob, http://www.w3.org/1999/02/22-rdf-syntax-ns#type, http://example.org/Human) [http://example.org/graph3]
(http://example.org/bob, http://www.w3.org/1999/02/22-rdf-syntax-ns#type, http://example.org/Animal) [http://example.org/graph3]
(http://example.org/bob, http://www.w3.org/1999/02/22-rdf-syntax-ns#type, http://example.org/Man) [http://example.org/graph3]
```

**Comment by hmottestad** [comment]
So I guess that it only correctly manages to infer the graph for A-box statements. For T-box statements some are added to the correct graph (two first ones), while some are added to the default graph (two second ones) and the ones that are real, not inferred, belong to the context they were added to.

**Comment by hmottestad** [comment]
It would have been nice if the T-box part worked correctly wrt. graph, but I'm not too worried. I think it's because I use a fixpoint approach to calculate the full T-box and then cache that result. That cache doesn't care about graphs.

Fixing that part is not really worth it I think. Also considerably easier to handle those kinds of things with query rewriting (backwards chaining).

**Comment by jeenbroekstra** [comment]
We'll also need to look at data migration: for example what happens to existing repos (with inferred statements persisted in the null context) when they upgrade and enable this feature?

**Comment by hmottestad** [comment]
Good point @jeenbroekstra. I'll have a little think about it.
