### ISSUE TITLE
Set up CI server

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#12]
Either (temporarily) using ci.rdf4j.net, or looking into using an Eclipse-hosted environment

**Comment by nikolavp** [comment]
Is travis an option? I have previously setup many projects in my account with travis and was more than happy with the results.

**Comment by jeenbroekstra** [comment]
Well Eclipse has its own [Common Build Infrastructure](https://wiki.eclipse.org/CBI) which they strongly encourage all new projects to use. If we are going to set up something new, I prefer to go that route, rather than set up a Travis account. But in the short term it's probably even easier to use the Jenkins server we are currently running Sesame build/test on. It's at https://ci.rdf4j.net/ and is owned by me, personally. It wouldn't require much config to get it to download the rdf4j git repo and validate the build.

**Comment by jeenbroekstra** [comment]
I've filed a request for a HIPP (Hudson Instance Per Project) instance to be created for us. See https://bugs.eclipse.org/bugs/show_bug.cgi?id=487907

**Comment by jeenbroekstra** [comment]
HIPP now available at https://hudson.eclipse.org/rdf4j/ . All committers can log in using their eclipse account. I'll keep this issue open until I'm done configuring Hudson to our satisfaction
