### ISSUE TITLE
Override the default values of the parser settings with -D

### ISSUE THREAD

**Issue by vassilmomtchev** [eclipse/rdf4j#1200]
Background: Often the RDF4J parsers are integrated into server logic. In specific scenarios, the server must support to override the default parser's behavior for common basic settings like "Verify the language tag".

Proposed change: As an administrator, I would like to reconfigure the RDF parser behavior by supplying a Java parameter with -D which overrides the default value:

``       java  -Dorg.eclipse.rdf4j.rio.failonunknownlanguages=true <parameter to initialize my server>``

If the value is recognizable and from the correct type it should override the `BasicParserSettings` default value. Otherwise, the parse should raise `WARN` message to indicate the failed parser setting with a proper message.

The same applies to all other RDF default parser values.

**Comment by jeenbroekstra** [comment]
Feature complete. We need to write some documentation before we can close this.
