### ISSUE TITLE
rdf4j Turtle validation too loose for quoted strings?

### ISSUE THREAD

**Issue by rickhg12hs** [eclipse/rdf4j#1205]
I have a Turtle file that `console.sh` reports as fine. (`console.sh` seems to use `org.eclipse.rdf4j.rio...`) However, `Jena`'s `riot` reports problems.

```bash
$ /path/to/rdf4j/eclipse-rdf4j-2.4.2/bin/console.sh 
20:18:35.779 [main] DEBUG o.e.r.c.platform.PlatformFactory - os.name = linux
20:18:35.791 [main] DEBUG o.e.r.c.platform.PlatformFactory - Detected Gnome window manager on Posix platform
Connected to default data directory
RDF4J Console 2.4.2+285c2b9

2.4.2+285c2b9
Type 'help' for help.
> verify data.ttl
RDF Format is Turtle
Verifying data...
Data verified, no errors were found
File contains 85499 statements
```

```bash
$ riot --validate ./data.ttl 
20:52:59 ERROR riot                 :: [line: 87123, col: 1 ] Broken token (newline): The reported vulnerability is fixed in version 4.0.0.39 of nPrtoect AVS.<br />

```
There is a newline (ASCII `x0a`) on line 87123 of `data.ttl` in the middle of a triple's string object.

In addition, I'm wondering why `rdf4j/rio/turtle/src/main/java/org/eclipse/rdf4j/rio/turtle/Turtle grammar.txt` isn't identical to `https://www.w3.org/TR/turtle/#sec-grammar-grammar`.

**Comment by barthanssens** [comment]
I assume the grammar.txt is still based on a very early version of Turtle... (the file itself dates back to at least OpenRDF Sesame 2.0, which is 11 years old... see also https://github.com/ansell/openrdf-sesame/blob/2.0/core/openrdf-rio/openrdf-rio-turtle/src/main/java/org/openrdf/rio/turtle/Turtle%20grammar.txt)

IIRC a newline is allowed if the object is surrounded by three quotes (""") , but I guess that's not the case in your data.ttl file ?

**Comment by rickhg12hs** [comment]
> IIRC a newline is allowed if the object is surrounded by three quotes (""") , but I guess that's not the case in your data.ttl file ?

Correct.

Is the fix to just simply update the grammar to the current standard?

**Comment by barthanssens** [comment]
I don't think so, looks like it's just included for reference. 

Method to be changed is probablye the `org.eclipse.rdf4j.rio.turtle.TurtleParser#parseString`

**Comment by rickhg12hs** [comment]
Ouch, that must be hard without using the standard's grammar directly.

Thanks for the fix!
