### ISSUE TITLE
Server: replace or update ziplet dependency

### ISSUE THREAD

**Issue by barthanssens** [eclipse/rdf4j#1209]
The HTTP server's pom.xml and web.xml includes a filter `com.github.ziplet.filter.compression.CompressingFilter` to compress HTTP responses.

(a newer version of) Jetty has a GZIP filter, but this filter does not support DEFLATE
(https://www.eclipse.org/jetty/documentation/current/gzip-filter.html)

So the suggestion would be to continue using ziplet but upgrade it to the latest 2.3.0 version (another issue: I couldn't find a CQ for ziplet...)

- [x] Ziplet 2.4.1 (CQ23235)

**Comment by barthanssens** [comment]
Created a CQ for the current ziplet 2.0.0 (CQ 18567), just to be sure

**Comment by barthanssens** [comment]
Withdrawn and re-entered as CQ 18873, marked as RESOLVED/FIXED by Eclipse

**Comment by barthanssens** [comment]
Upgrade to 2.3 would require a new CQ...
Perhaps wait a little while, since there are a few more urgent CQ's pending approval :-)

**Comment by jeenbroekstra** [comment]
@barthanssens this still relevant? I briefly checked and there seems to be a ziplet 2.4.1 now.

**Comment by barthanssens** [comment]
Thanks for the reminder, forgot about this one
