### ISSUE TITLE
zip_slip

### ISSUE THREAD

**Issue by 360CodeSafe** [eclipse/rdf4j#1210]
Hi all,
There is a path traversal vulnerability found by Qihoo360 CodeSafe Team.
Details as bellow:
![default](https://user-images.githubusercontent.com/39950310/50139352-690c8680-02dc-11e9-9612-56394c620268.png)

When decompressing zip files, entries are not checked, resulting in overwriting arbitrary files by traversing directories using “.. /”

**Comment by barthanssens** [comment]
Well, it sure is a small effort to backport it.
I'll take care of it this evening or tomorrow morning.
