### ISSUE TITLE
Graduate from incubation stage 🎓

### ISSUE THREAD

**Issue by barthanssens** [eclipse/rdf4j#1213]
The Eclipse project website still shows "incubating" logo (https://projects.eclipse.org/projects/technology.rdf4j), should be replaced by proper RDF4J logo

And the rdf4j.org website also has an Eclipse incubating logo

**Comment by jeenbroekstra** [comment]
Fwiw technically we are still in incubation stage - we never applied for it to be lifted, and it requires a formal review. It's worth having a chat with the PMC I guess, to see what would be required to change this.

**Comment by barthanssens** [comment]
Ah ok, that explains it.
Seems like graduation does take some effort in terms of regular releases, promotion and participation in other Eclipse projects

https://wiki.eclipse.org/Development_Resources/HOWTO/Criteria_for_Graduating_from_Incubation_Phase_to_Mature_Phase

**Comment by jeenbroekstra** [comment]
Fwiw I have requested that the PMC approve our graduation, to coincide with the 3.0 release. If there are any additional requirements in terms of documentation, I will try and take care of it.

**Comment by hmottestad** [comment]
Did we graduate?

**Comment by jeenbroekstra** [comment]
I'm still trying to get that confirmed, my emails have been ignored. I'll start insisting a little more loudly.

**Comment by jeenbroekstra** [comment]
I just had confirmation that we have been graduated from incubation. They just forgot to flip a switch on our project page. Wayne apologized and corrected.

I'll update our website: take off the incubation logo, and a small news item. Nothing changes much in how we do things so I don't really want to make a song and dance about this, but you know: it's nice :)

**Comment by barthanssens** [comment]
That's a job well done, congrats Jeen 👍
