### ISSUE TITLE
Upgrade maven plugins

### ISSUE THREAD

**Issue by barthanssens** [eclipse/rdf4j#1216]
Could be useful to upgrade different maven plugins (source, surefire etc plugins...) in pom.xml's

**Comment by jeenbroekstra** [comment]
Not a bad idea to have a look, but please be _very_ careful about upgrading. We've been bitten in the past by upgrading maven plugins to only find out at release time that it breaks something in our release/deploy cycle.

**Comment by barthanssens** [comment]
ok, sounds like a 3.0 thingie

**Comment by jeenbroekstra** [comment]
We've done a lot of this as part of #2925. Closing as done, if there are specific plugins that should still be bumped feel free to reopen or create followup tickets.
