### ISSUE TITLE
Set authentication and password for sparql endpoint in Workbench

### ISSUE THREAD

**Issue by abrokenjester** [eclipse/rdf4j#1220]
Some SPARQL endpoints require authentication. While the SPARQLRepository supports this, the RDF4J Workbench has no option fields to set these parameters when configuring a new SPARQL endpoint.

**Comment by jeenbroekstra** [comment]
I've noticed that the Console also doesn't support this.

**Comment by barthanssens** [comment]
related to #528

**Comment by adamretter** [comment]
Is this implemented yet?
