### ISSUE TITLE
Upgrade spatial4j to new release

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#1228]
The current release of spatial4j is distributed as a signed jar, which makes it problematic for rdf4j users who repackage dependencies as part of a shaded/uber-jar. @hmottestad submitted a fix for this to the spatial4j people (see https://github.com/locationtech/spatial4j/issues/168 ) which got merged and will be included in the next release.

When that release is done, we should try to bump our dependency as well.

**Comment by jeenbroekstra** [comment]
@hmottestad do you know if spatial4j have done a new release yet with this fix in place? Spatial4j 0.7 looks to be the most recent, and it was done on the same day your PR got merged. Was your fix included?

**Comment by hmottestad** [comment]
0.7 was released in December 2017. My PR was merged in 2018.

**Comment by jeenbroekstra** [comment]
Closing as this was addressed when we bumped to spatial4j version 0.8
