### ISSUE TITLE
GeoSparql Documentation Contains Wrong WKT Literals

### ISSUE THREAD

**Issue by greenwoodma** [eclipse/rdf4j#1232]
The documentation on using GeoSPARQL at http://docs.rdf4j.org/programming/#_geosparql contains both example triples and a SPARQL query. The triples encode the locations of Tower Bridge and the Eiffel Tower  as WKT literals each containing a single POINT object. The sample query then calculates the distance between them as being 384.02842030928696 kilometres. Unfortunately the answer is wrong as the real distance between them is only 334.355 kilometres (see [this WGS-84 distance calculator](http://www.cqsrg.org/tools/GCDistance/) if you want to be sure).

The problem isn't the distance calculation though, rather the locations in the sample data are wrong. A POINT object encoded as WKT should list the coordinates as X Y, which means when representing a geographical location we need Longitude Latitude, unfortunately the example triples list the locations as Latitude Longitude which results in the erroneous distance result.

I can't find the documentation in this repo or I'd have done a pull request, but the sample data should read as follows
```
@prefix geo: <http://www.opengis.net/ont/geosparql#> .
@prefix sf: <http://www.opengis.net/ont/sf> .
@prefix ex: <http://example.org/> .

ex:eiffelTower a ex:Landmark ;
          geo:hasGeometry ex:coordinates-et.
ex:coordinates-et a sf:Point;
        geo:asWKT "POINT(2.2945 48.8584)"^^geo:wktLiteral .
ex:towerBridge a ex:Landmark ;
          geo:hasGeometry ex:coordinates-tb.
ex:coordinates-tb a sf:Point;
        geo:asWKT "POINT(0.0754 51.5055)"^^geo:wktLiteral .
```

**Comment by barthanssens** [comment]
Thank you for reporting this, there is actually another (far less relevant) error: the Tower Bridge is located in the Western hemisphere, thus the X coordinate should read _minus_ 0.0754.

Note that the calculated distance in the corrected example can still be off by a few km, since spatial4j simplifies calculations by modeling the Earth as a perfect sphere (see #1161)

**Comment by greenwoodma** [comment]
Oh yes, I hadn't even spotted the East/West issue with Tower Bridge.

**Comment by barthanssens** [comment]
Should be fixed.
In case you were wondering, the documentation resides in the https://github.com/eclipse/rdf4j-doc (subproject / repo), but all issues are tracked here in the "main" rdf4j repo.

Feel free to create a PR if you would spot any other issue.
(in that case, there is also the small formality of creating an Eclipse account and signing the Contributor Agreement... https://github.com/eclipse/rdf4j/blob/master/.github/CONTRIBUTING.md)

**Comment by greenwoodma** [comment]
Looks good to me, thanks for sorting it so quick. If I spot anything else, I'll jump through the hoops for the CLA and do a PR now I know where everything lives.
