### ISSUE TITLE
SchemaCachingInferencer in Console does not infer properly

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#1234]
This is an issue I stumbled across while working on #1226 . 

To reproduce, checkout branch `issues/GH-1226-server-inferencer` from both the rdf4j and the rdf4j-storage repos, and make sure that you start an RDF4J Console that uses the compiled code from both those branches on its runtime classpath.

If I run a console, and create a new memory store with the schema-caching inferencer (using the new template as added in the the above branch), like so:

```
  > create memory-rdfs-new
Please specify values for the following variables:
Repository ID [memory-rdfs-new]: 
Repository title [Memory store with Schema-caching RDFS inferencing]: 
Query Iteration Cache size [10000]: 
Persist (true|false) [true]: 
Sync delay [0]: 
EvaluationStrategyFactory [org.eclipse.rdf4j.query.algebra.evaluation.impl.StrictEvaluationStrategyFactory]: 
Repository created
```
then open it:

```
open memory-rdfs-new
Opened repository 'memory-rdfs-new'
```

then add some triples:

```
memory-rdfs-new> sparql insert data { <foo:s1> a <foo:C1> . <foo:C1> rdfs:subClassOf <foo:C2> } 
sparql insert data { <foo:s1> a <foo:C1> . <foo:C1> rdfs:subClassOf <foo:C2> }Executing update...
Update executed in 14 ms
```

I would expect to see that `<foo:s1>` is of type `<foo:C2>`, and that `<foo:C1>` and `<foo:C2>` are both of type `rdfs:Class`. However:

```
memory-rdfs-new> select * where { <foo:s1> ?p ?y }
select * where { <foo:s1> ?p ?y }Evaluating SPARQL query...
+-------------------------------------+-------------------------------------+
| p                                   | y                                   |
+-------------------------------------+-------------------------------------+
| rdf:type                            | <foo:C1>                            |
+-------------------------------------+-------------------------------------+
1 result(s) (7 ms)
```

and

```
memory-rdfs-new> select * where { <foo:C1> ?p ?y } 
select * where { <foo:C1> ?p ?y }Evaluating SPARQL query...
+-------------------------------------+-------------------------------------+
| p                                   | y                                   |
+-------------------------------------+-------------------------------------+
| rdfs:subClassOf                     | <foo:C2>                            |
+-------------------------------------+-------------------------------------+
1 result(s) (5 ms)
```

The annoying thing is that I can't reproduce this in any sort of unit or compliance test. Everything I've tried with setting up a test case just works as expected, and does the expected inferences. @hmottestad I would appreciate if you could take a look and see if you spot where this might be going wrong. Keep in mind that you need the issue branch from rdf4j because it contains a new config template for the Console to use, and you need the issue branch from rdf4j-storage because it contains the SPI setup (Factory and Config class) for the SchemaCachingInferencer, which is what is used to create a sail stack out of the config file.

**Comment by hmottestad** [comment]
Odd. Ill take a look tomorrow. Maybe it’s something a simple as having to enable reasoning for the queries.

**Comment by jeenbroekstra** [comment]
@hmottestad thanks for looking into this. I'll need to revisit this to jog my memory but from the top of my head, yes, UpdateContext was added to handle isolation. IIRC the way it is set up is such that `addStatement` without a context is actually the "special case", that is, it translates to an addStatement with a null UpdateContext.

As for removing that line from the test: I did that because the compliance tests should validate the _default_ behavior of the Sail. Especially since this config option is not (yet) available as part of the sail config template. But if removing this line makes tests fail we should perhaps raise that as a separate bug instead of trying to fix everything in this branch.

**Comment by hmottestad** [comment]
If you can make some sort of concurrency test to show any isolation issues that would be awesome.

**Comment by jeenbroekstra** [comment]
@hmottestad well, there's `org.eclipse.rdf4j.sail.SailIsolationLevelTest` in the testsuite, which is precisely for that purpose. If we want to verify that a stack with a SC-inferencer does isolation correctly, we can just add a subclass of that testsuite that gets initialized with an inferencing sail stack.  I'm at work now but I'll try and add something like that this evening.

**Comment by jeenbroekstra** [comment]
Confirmed that your fix addresses the problem I saw in the console btw, great stuff! I'll close this now, and will take a closer look at the issue of compliance testing.
