### ISSUE TITLE
Update code formatting guidelines

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#1240]
The code formatting guidelines for RDF4J are "enshrined" in an [eclipse formatting config file](https://github.com/eclipse/rdf4j/blob/master/eclipse-settings/rdf4j-formatting.xml). This file is somewhat out of date with newer versions of Eclipse it seems, and occasionally causes weird reformatting issues.

Moreover, not everybody uses Eclipse IDE - some heretics (j/k) prefer IntelliJ or other editors. We should codify the formatting conventions in a way that is easier to transport across multiple tools.

One way to do that is to adopt standard code conventions (like the Oracle java conventions, or the Google conventions) - these are pretty universally supported. If we really feel we need to, we can document minor departures (line length, tabs vs. spaces, etc), and still provides a custom eclipse formatting file for RDF4J - just with fewer departures from common conventions. 

It's more important to have a commonly shared standard than to have something that I (or anyone else) personally find the most pleasing layout. Git diffs would become a lot less messy this way, for one.

**Comment by barthanssens** [comment]
Related to #822

**Comment by barthanssens** [comment]
Admittedly I'm probably one of the worst offenders, being used to the Oracle Java guidelines (way less newlines e.g. no newline before else and the { on the same line as method name... and thus more lines of codes per screen)  _and_ having joined the dark side a.k.a. Netbeans ;-)

I don't mind using the RDF4J coding rules, but it would definitely help if there would be a few good, short examples on how to format the code, without Eclipse. 

(side note: I know there is an Eclipse formating plugin  for Netbeans, but the results where mixed - literally and figuratively)

**Comment by jeenbroekstra** [comment]
Well I'm actually with you on the newlines thing. A lot of these guidelines were chosen when it was just me and Arjohn working on this code base, both in the same office, using the same tools, and still using 4:3 CRT monitors :)

So I'm happy to revisit and adapt. I don't want to get into a whole nit-picky discussion about individual formatting tweaks though, which is why I'd advocate something along the lines of just adopting [Eclipse Coding Conventions](https://wiki.eclipse.org/Coding_Conventions). 

These are basically just Sun/Oracle Java conventions with a few modifications, notably:

- standardize on 4-space tab-only indentation (Sun/Oracle allows mixed indents, that's a mess)
- Eclipse license header guidelines for beginning comment
- some more explicit package/class [naming conventions](https://wiki.eclipse.org/Naming_Conventions)

I would advocate two additional minor modifications/addendums of our own:

- standardize on max line length of 120 instead of 80 
- standardize on unix line endings

The thing about doing it along these lines is that we can still provide automated support for these settings in Eclipse with a formatting config file, while for people using other tools it is a lot clearer what they need to do to set up their tools correctly. 

I'm also keen to look at automated support in maven such as described in #822 but I'd like to get an updated consensus before we look at technical solutions.

**Comment by jeenbroekstra** [comment]
Hm, I just ran into this. Interesting read: https://blog.exxeta.com/java/2017/06/13/java-code-formatting-done-right-across-different-ides/
