### ISSUE TITLE
SparqlBuilder incorrect implementation of SPARQL 1.1 Section 13

### ISSUE THREAD

**Issue by bbagnall** [eclipse/rdf4j#1245]
The [Section13Test](https://github.com/eclipse/rdf4j/blob/master/sparqlbuilder/src/test/java/org/eclipse/rdf4j/sparqlbuilder/examples/sparql11spec/Section13Test.java) for SparqlQuery builder produces invalid SPARQL. According to the [SPARQL 1.1 Spec Section 13](https://www.w3.org/TR/sparql11-query/#rdfDataset), the FROM and FROM NAMED clauses are supposed to be after the SELECT.

Here are a few example outputs of the tests:

```
EXAMPLE 13.2.1:
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
FROM <http://example.org/foaf/aliceFoaf>
SELECT ?x0
WHERE { ?x1 foaf:name ?x0 . }

EXAMPLE 13.2.3:
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
FROM <http://example.org/dft.ttl>
FROM NAMED <http://example.org/alice>
FROM NAMED <http://example.org/bob>
SELECT ?x0 ?x1 ?x2
WHERE { ?x1 dc:publisher ?x0 .
GRAPH ?x1 { ?x3 foaf:mbox ?x2 . } }

EXAMPLE 13.3.1:
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
FROM NAMED <http://example.org/alice>
FROM NAMED <http://example.org/bob>
SELECT ?x0 ?x1
WHERE { GRAPH ?x0 { ?x2 foaf:nick ?x1 .
?x2 foaf:mbox <mailto:bob@work.example> . } }
```

These should actually be:
```
EXAMPLE 13.2.1:
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
SELECT ?x0
FROM <http://example.org/foaf/aliceFoaf>
WHERE { ?x1 foaf:name ?x0 . }

EXAMPLE 13.2.3:
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
SELECT ?x0 ?x1 ?x2
FROM <http://example.org/dft.ttl>
FROM NAMED <http://example.org/alice>
FROM NAMED <http://example.org/bob>
WHERE { ?x1 dc:publisher ?x0 .
GRAPH ?x1 { ?x3 foaf:mbox ?x2 . } }

EXAMPLE 13.3.1:
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
SELECT ?x0 ?x1
FROM NAMED <http://example.org/alice>
FROM NAMED <http://example.org/bob>
WHERE { GRAPH ?x0 { ?x2 foaf:nick ?x1 .
?x2 foaf:mbox <mailto:bob@work.example> . } }
```

This [commit](https://github.com/bbagnall/rdf4j/commit/bd3f338e0b84e509b4c58ba4125bf5a98679e1ce) shows how it can easily be fixed by moving the [Optional<Dataset> from](https://github.com/eclipse/rdf4j/blob/master/sparqlbuilder/src/main/java/org/eclipse/rdf4j/sparqlbuilder/core/query/OuterQuery.java#L86-L110) out of the [OuterQuery class](https://github.com/eclipse/rdf4j/blob/master/sparqlbuilder/src/main/java/org/eclipse/rdf4j/sparqlbuilder/core/query/OuterQuery.java), and into the [Query class](https://github.com/eclipse/rdf4j/blob/master/sparqlbuilder/src/main/java/org/eclipse/rdf4j/sparqlbuilder/core/query/Query.java).

**Comment by reckart** [comment]
@barthanssens would be nice if the fix indicated by @bbagnall could be integrated...

**Comment by barthanssens** [comment]
Hi @bbagnall , thanks for the bug report and the fix.

Would it be possible to create a pull request, and sign the Eclipse Contributor Agreement (ECA) ?
The process is quite straightforward and should not take long,
but the Eclipse foundation is quite serious about Intellectual Property Rights, 
so signing the ECA (once) is unfortunately a requirement.

See also https://github.com/eclipse/rdf4j/blob/master/.github/CONTRIBUTING.md#legal-stuff

Thanks.

**Comment by bbagnall** [comment]
#1427
