### ISSUE TITLE
Support transaction prepare() in ShaclSail

### ISSUE THREAD

**Issue by hmottestad** [eclipse/rdf4j#1249]
See https://github.com/eclipse/rdf4j-storage/pull/147

**Comment by hmottestad** [comment]
@jeenbroekstra do you still want this as part of the 2.5 release?

**Comment by jeenbroekstra** [comment]
If possible, yes. Apart from the rollback and the missing headers this looks fine to me.

**Comment by hmottestad** [comment]
There is a rather nasty merge conflict that needs to be fixed.
