### ISSUE TITLE
seconds() loses millisecond precision

### ISSUE THREAD

**Issue by VladimirAlexiev** [eclipse/rdf4j#1267]
https://www.w3.org/TR/sparql11-query/#func-seconds has an example where milliseconds are returned (`13.815`). Testing on GraphDB 8.8:
```
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
select (seconds("2011-01-10T14:45:13.815-05:00"^^xsd:dateTime) as ?sec) {
}
```
returns `13` and loses the milliseconds part.

**Comment by barthanssens** [comment]
`org.eclipse.rdf4j.query.algebra.evaluation.function.datetime.Seconds` uses `getSecond()` instead of `getMillisecond()` or `getFractionalSecond()`
