### ISSUE TITLE
GeoSPARQL query performance issue with Lucene Sail enabled for spatial indexing

### ISSUE THREAD

**Issue by tioannid** [eclipse/rdf4j#1281]
Hi, I am comparing the performance of a set of GeoSPARQL queries against two repo versions that contain the same set of data (several GB). The first repo has Lucene indexing enabled during creation and contains the corresponding subdirectory "luceneidx". The LuceneSail.WKT_FIELDS was set as:

LuceneSail.WKT_FIELDS = "http://www.opengis.net/ont/geosparql#asWKT http://geo.linkedopendata.gr/corine/ontology#asWKT"

According to the documentation Lucene spatialy indexes the data and the repo should be faster that the non-Lucene indexed version. Is there an example code or other document that confirms this claim, that we could refer to, probable check our code against it?

Extensive tests with a number of different very large repos confirm that the same GeoSPARQL queries execute 20%-30% slower in the Lucene indexed repos compared to the non-Lucene repos.

I am using RDF4J v2.4.1 and I was wondering if this is a bug or if I am doing something wrong when retrieving a repo connection from  a Lucene indexed repo. Is there a way for me to find out whether my GeoSPARQL queries use Lucene during execution?

I was also wordering how would someone would go about learning more (docs or papers) about the default spatial indexing of the latest RDF4J version and the spatial indexing employed by the Lucene Sail.

Thanks

**Comment by barthanssens** [comment]
Seems like a duplicate of #1160 ?

**Comment by tioannid** [comment]
I thought it was only a bug that appeared between versions.

Do you believe that the situation will be the same if I try v2.4.3?

**Comment by barthanssens** [comment]
Well, I haven't benchmarked the different versions, but 2.4.3 is probably the same as 2.4.1, since there are very few changes between 2.4.1 and 2.4.2/3 (https://github.com/eclipse/rdf4j/releases)

There were some GeoSPARQL changes in 2.4.1, but apparently they did not fix the performance issue...

**Comment by barthanssens** [comment]
There is a ticket for upgrading Lucene/Solr/ES to a more recent version, so maybe, just maybe, it might improve performance #1114 (to be tested...)

**Comment by pulquero** [comment]
For Lucene, geosparql is mapped to Lucene spatial ops as follows:

> 	private SpatialOperation toSpatialOp(String relation) {
		if (GEOF.SF_INTERSECTS.stringValue().equals(relation)) {
			return SpatialOperation.Intersects;
		}
		else if (GEOF.SF_DISJOINT.stringValue().equals(relation)) {
			return SpatialOperation.IsDisjointTo;
		}
		else if (GEOF.SF_EQUALS.stringValue().equals(relation)) {
			return SpatialOperation.IsEqualTo;
		}
		else if (GEOF.SF_OVERLAPS.stringValue().equals(relation)) {
			return SpatialOperation.Overlaps;
		}
		else if (GEOF.EH_COVERED_BY.stringValue().equals(relation)) {
			return SpatialOperation.IsWithin;
		}
		else if (GEOF.EH_COVERS.stringValue().equals(relation)) {
			return SpatialOperation.Contains;
		}
		return null;
	}

The actual Lucene query is:

>		final String geoField = SearchFields.getPropertyField(geoProperty); // asWKT
>		SpatialStrategy strategy = getSpatialStrategyMapper().apply(geoField);
>		Query q = strategy.makeQuery(new SpatialArgs(operation, shape));

But, if I remember correctly this all happens "early" and so will only apply to functions that have one fixed literal argument, e.g. geof:sfIntersects(?x, "....."^^WKT). Things like geof:sfIntersects(?x, ?y) won't be optimised. This would be fixed by "late" evaluation, which is an outstanding issue, https://github.com/eclipse/rdf4j/issues/716.

**Comment by tioannid** [comment]
I think that your analysis explains very well the performance I am experiencing. Since the most demanding of my queries are spatial joins geof:sfIntersects(?x, ?y) it makes sense that the augmented Lucene repo (> 50% larger than the plain repo) will underperform by a 10-20% factor.

Thanks for the pointers in the source code.
