### ISSUE TITLE
Null pointer exception on transaction UPDATE with wrong MIME type and missing update parameter

### ISSUE THREAD

**Issue by rdstn** [eclipse/rdf4j#1282]
If one opens a transaction Update with a wrong MIME type - "application/sparql-query", for example, and does not include "update" in the parameters, the result would be a Null Pointer Exception instead of something informative to the users.

Steps to reproduce:
1. Open a transaction:
curl -v -X POST --header 'Content-Type: application/json' --header 'Accept: text/plain' 'http://localhost:7200/repositories/test/transactions'
2. Submit an update with the wrong MIME type:
curl -v -X POST -H "Content-Type:application/sparql-query" --data-binary '@test.sparql' 'http://localhost:7200/repositories/test/transactions/<transaction-id>?action=UPDATE'

A simple fix would be a null check in the org.eclipse.rdf4j.http.server.repository.transaction.TransactionController#getSparqlUpdateResult method.

**Comment by rdstn** [comment]
I tried to push a fix, but I'm getting an access denied response from the git repo. I've followed the contribution guide, signed the Eclipse documentation, and am trying to push under issues/rdf4j#1282-NPEOnMimeMismatch. Is there something else I should do before contributing to rdf4j-tools, or I've just made a mistake with my git configuration?

**Comment by jeenbroekstra** [comment]
@rstdn ah, you can't push directly to the rdf4j repositories. You will need to create a fork, push your fixes there, and then open a pull request from your fork back to our repo.

**Comment by jeenbroekstra** [comment]
Sorry we should make this clearer in the contribution doco

**Comment by rdstn** [comment]
I'd say it's my fault for not reading carefully enough. I've submitted a Pull request now. It didn't recognise my signed-off-by footer, though (I added it via a patch commit since first time around I forgot it).
