### ISSUE TITLE
Duplicated Children in Hierarchy JSON-LD

### ISSUE THREAD

**Issue by mnmercer** [eclipse/rdf4j#1283]
**RDF4J Version:** 2.4.3

The Hierarchy JSON-LD View of a Model appears to depend on the alphabetical ordering of the IRIs. As a simple example, I have three entities that are connected by a `urn:child` property indicating a parent/child relationship. Depending on the alphabetical ordering of the IRIs of my three entities, I will end up with part of the hierarchy duplicated. Here's some code to reproduce the issue and the results.
```java
ValueFactory vf = SimpleValueFactory.getInstance();
ModelFactory mf = new LinkedHashModelFactory();
IRI child = vf.createIRI("urn:child");
IRI a = vf.createIRI("urn:A");
IRI b = vf.createIRI("urn:B");
IRI c = vf.createIRI("urn:C");
IRI e = vf.createIRI("urn:E");

Model test1 = mf.createEmptyModel();
test.add(a, child, b);
test.add(b, child, c);

Model test2 = mf.createEmptyModel();
test.add(e, child, b);
test.add(b, child, c);

StringWriter stringWriter = new StringWriter();
RDFWriter writer = Rio.createWriter(RDFFormat.JSONLD, stringWriter);
writer.getWriterConfig().set(JSONLDSettings.HIERARCHICAL_VIEW, true);
Rio.write(test1, writer);
System.out.println("A -> B -> C");
System.out.println(stringWriter.toString());

stringWriter = new StringWriter();
writer = Rio.createWriter(RDFFormat.JSONLD, stringWriter);
writer.getWriterConfig().set(JSONLDSettings.HIERARCHICAL_VIEW, true);
Rio.write(test2, writer);
System.out.println("E -> B -> C");
System.out.println(stringWriter.toString());
```
```
A -> B -> C
[ {
  "@id" : "urn:A",
  "urn:child" : [ {
    "@id" : "urn:B",
    "urn:child" : [ {
      "@id" : "urn:C"
    } ]
  } ]
} ]
E -> B -> C
[ {
  "@id" : "urn:B",
  "urn:child" : [ {
    "@id" : "urn:C"
  } ]
}, {
  "@id" : "urn:E",
  "urn:child" : [ {
    "@id" : "urn:B",
    "urn:child" : [ {
      "@id" : "urn:C"
    } ]
  } ]
} ]
```
I would expect in both instances, I would get a structure like the `A -> B -> C` result, but when the top level entity has an IRI that is alphabetically earlier than the middle entity, I end up with that duplication.

**Comment by barthanssens** [comment]
FWIW, same result with RDF4J 2.5.0-M1 (which uses jsonld-java 0.12.3 instead of 0.12.0)

**Comment by skahmann** [comment]
Any updates on this?

**Comment by jeenbroekstra** [comment]
Confirmed bug. The root cause is in our `JSONLDHierarchicalProcessor`, which picks the root node by ordering on (descending) number of direct children. Since in this case, both B and E have one direct child, it picks random/alphabetically. 

Not immediately sure what the easiest fix is. Ideally we'd reconstruct the full tree but that's potentially resource-intensive. Perhaps a simple "filter out all nodes that are also children of another node" is good enough.

**Comment by mnmercer** [comment]
@jeenbroekstra I think I figured out how to fix the issue doing a "filter out all nodes that are also children of another node" like you mentioned. I just added a `Set` in `JSONLDHierarchicalProcessor` that tracks any node id that has been determined as a child node and then filtered the `expanded` return object by removing any objects whose IDs were present in the children set. Changes aren't too complex. Would it be easier for me to send you my changes and you put in the fix, or for me to make a pull request myself?

**Comment by jeenbroekstra** [comment]
@mnmercer that's great, thanks! Usually we prefer receiving a pulley request.  If you do, make sure you follow the contribution guidelines, particularly the bit about (digitally) signing the Eclipse Contributor Agreement and the bit about signing off your git commits (using `git commit -s`). Shouldn't take more than 10 minutes or so to set that up.

**Comment by mnmercer** [comment]
@jeenbroekstra Should I branch off of the `issues/GH-1283-jsonld-hierarchy` branch that's already in the repo? Or should I start from `master` like the contributing guidelines specify?

**Comment by jeenbroekstra** [comment]
Ah good point. Not critical but if you can, branch off from the issue
branch.

**Comment by mnmercer** [comment]
@jeenbroekstra Created the pull request. Do I need to assign it to anyone? How soon do you think this will be put into a public release?

**Comment by jeenbroekstra** [comment]
@mnmercer nice! Thanks for the PR, all looks good, I will merge it shortly. We're planning a 2.5.0 release, to go out on March 7, this will definitely be included in that. Let us know if you can't/won't migrate to 2.5 yet, and we can push out a 2.4.x hotfix release at some point as well.

**Comment by mnmercer** [comment]
@jeenbroekstra If it is possible to get this into a hotfix for 2.4.x that would be great.

**Comment by barthanssens** [comment]
ok, we'll try to release a 2.4.6 during the weekend
