### ISSUE TITLE
Hash functions are not implemented correctly

### ISSUE THREAD

**Issue by pulquero** [eclipse/rdf4j#1284]
According to the spec, e.g. for MD5, it says:
"Returns the MD5 checksum, as a hex digit string, calculated on the UTF-8 representation of the simple literal or lexical form of the xsd:string".
But the code simply does text.getBytes() which uses the platform encoding. So it is neither correct nor consistent across different platforms. It should do text.getBytes("UTF-8") or better text.getBytes(StandardCharsets.UTF_8).

**Comment by barthanssens** [comment]
Could this be the cause of #1115 ?

**Comment by pulquero** [comment]
Yes, that is exactly the problem I encountered. Failure in the compliance tests.
