### ISSUE TITLE
Language tags in RDF4j 

### ISSUE THREAD

**Issue by MahekHanfi** [eclipse/rdf4j#1292]
When creating a literal, we can provide any language tag and RDF4J accepts it. It doesn't conform with the standards [https://www.w3.org/TR/rdf11-concepts/#bib-BCP47]. 

Forexample, RDF4J doesn't report for literal (France@en,en). I can create this literal, although it is not a valid language tag. But when I tried to read the file with this defined literal as Turtle, it complains as it is not a valid turtle file. But rdf-xml serialization works fine with this literal. Also we can define language tags in camel case (France@wrongLanguage). 

It is intentional or it is a bug at your side?

Thanks,
Mahek Hanfi
Semantic Web Company

**Comment by barthanssens** [comment]
Hi,

The (default) `SimpleValueFactory` does not do much input validation (for performance reasons), have you tried using the `org.eclipse.rdf4j.model.impl.ValidatingValueFactory` instead ?

The ValidatingValueFactory should check the conformity of the language tag... if that's not the case, then it is a bug...

**Comment by MahekHanfi** [comment]
Hi,

I tried with ValidatingValueFactory and it checks the conformity of language tags. 

Thanks for pointing out in the right direction.

Best,
Mahek

**Comment by barthanssens** [comment]
Ok, seems to work like expected, so I'll close the ticket 
(although maybe it should be mentioned in the RDF4J documentation, because it is a good question)

**Comment by barthanssens** [comment]
Might be added to doc/programming/02-model-api.adoc
