### ISSUE TITLE
NativeStore: Txncache files do not get cleaned up on Windows (file system leak)

### ISSUE THREAD

**Issue by aschwarte10** [eclipse/rdf4j#1294]
We encountered a leak in the file system causing _txncache.dat_ files to not be cleaned up. On Windows the deletion of these _temporary_ files fails apparently because the file is still locked. 

In our case we had systems with thousands of these files lying around during the runtime of the application. This caused performance issues in various scenarios (e.g. our backups, cleanup etc)

Note that on Linux / Unix systems the files are getting deleted due to a different file locking mechanism.

Note also that the DB state is consistent and correct from what we can see, i.e. there only these files left in the native store's data dir.

Example unit test to reproduce (only Windows):

`public class NativeStoreTest {

	@Rule
	public TemporaryFolder tempFolder = new TemporaryFolder();

	protected Repository repo;

	protected ValueFactory vf = SimpleValueFactory.getInstance();

	protected IRI ctx = vf.createIRI("http://ex.org/ctx");

	@Before
	public void before()
		throws Exception
	{

		File dataDir = tempFolder.newFolder("dbmodel");
		repo = new SailRepository(new NativeStore(dataDir, "spoc,posc"));
		repo.init();
	}

	@After
	public void after()
		throws Exception
	{
		repo.shutDown();
	}

	@Test
	public void testTxncacheCleanup()
		throws Exception
	{

		/*
		 * Test for issue # On windows the txncacheXXX.dat files did not get properly deleted, as the file is
		 * locked when the deletion is attempted.
		 */

		IRI res = vf.createIRI("http://ex.org/s");

		addStmt(vf.createStatement(res, RDF.TYPE, FOAF.PERSON));

		Statement st1 = vf.createStatement(res, RDFS.LABEL, vf.createLiteral("test"));
		addStmt(st1);

		Statement remStmt = vf.createStatement(res, RDFS.LABEL, vf.createLiteral("test"), ctx);
		removeStmt(remStmt);

		File repoDir = repo.getDataDir();
		System.out.println("Data dir: " + repoDir);

		for (File file : repoDir.listFiles()) {
			System.out.println("# " + file.getName());
		}
		Assert.assertEquals(14, repoDir.listFiles().length);

		// make sure there is no txncacheXXX.dat file
		Assert.assertFalse(Files.list(repoDir.getAbsoluteFile().toPath()).anyMatch(
				file -> file.toFile().getName().matches("txncache[0-9]+.*dat")));

		try (RepositoryConnection conn = repo.getConnection()) {
			Assert.assertEquals(1, conn.size());
		}
	}

	protected void addStmt(Statement stmt) {

		try (RepositoryConnection conn = repo.getConnection()) {

			conn.begin();
			conn.add(stmt, ctx);
			conn.commit();
		}
	}

	protected void removeStmt(Statement stmt) {
		try (RepositoryConnection conn = repo.getConnection()) {

			conn.begin();
			conn.remove(stmt);
			conn.commit();
		}
	}
}`

The issue seems to be in _org.eclipse.rdf4j.common.io.NioFile.delete()_ where the file cannot be deleted.

**Comment by aschwarte10** [comment]
@jeenbroekstra, @barthanssens  A unit test is provided in the testSuite repository, not sure if this is the right location. If not please provide a pointer where to put it.

Another question: would it make sense to backport to 2.3.x and 2.4.x? If yes, how is this done? Is there some documentation of where to merge to?

**Comment by barthanssens** [comment]
Patch LGTM, thanks.

As for backporting, it might be worthwhile if it would be combined with a few others bugfixes (maybe #1284)

The documentation for a hotfix release is in part 5, http://docs.rdf4j.org/developer/#_hotfix_releases.

**Comment by jetztgradnet** [comment]
While this is only exposed on Windows due to the files not being deleted this could also have similar but less visible problems on Linux (and other Unix-like systems):
If the file is still open when it is deleted, only the directory entry is actually deleted. The `inode` and all data is still there until the process closes the handle or the process exists. 
But in this case `close()` is called right after the delete so this should be ok on Linux and not leave behind any resource leaks.

**Comment by jeenbroekstra** [comment]
@aschwarte10 any reason you want backports for both 2.3 and 2.4? We don't usually do backports two minor versions back, and with 2.5 just around the corner...

**Comment by aschwarte10** [comment]
@jeen for us 2.4.x is fully sufficient, just proposed 2.3.x as well because I saw in one of the comments of the PR a reference to 2.3.3

**Comment by barthanssens** [comment]
Well, the 2.3.x was actually a bit of a one-off, since it takes manual effort to produce/upload/announce the releases, but apparently it provided a much needed workaround for quite a few users, hence the release ...

Thanks for the patch, I'll working on the 2.4.5 release this weekend.

**Comment by yyz1989** [comment]
Hi, this is Yang from Semantic Web Company. Is it possible to have this issue fixed for 2.3 series as well? We are not yet ready to move to 2.4. Thanks a lot.

**Comment by jeenbroekstra** [comment]
hi @yyz1989, we normally don't do patch releases for two minor versions back. Rdf4j 2.4 should be fully backward compatible with 2.3, is there a particular issue that is blocking you from upgrading?

**Comment by yyz1989** [comment]
@jeenbroekstra Thanks a lot Jeen. I don't have details about it. I will ask Robert David to join this discussion.
