### ISSUE TITLE
SHACL - support simple rdfs reasoner 

### ISSUE THREAD

**Issue by hmottestad** [eclipse/rdf4j#1298]
Since SHACL is pushed as a replacement for spin it has a bunch of quirky features, such as an embedded reasoner that only supports rdfs:subClassOf and only works during validation and not on SPARQL queries that run on the validated data.

**Comment by hmottestad** [comment]
Copy code from the schema chaching reasoner

**Comment by hmottestad** [comment]
Forward chain the added and removed memory stores. Backwards chain the base sail. Set a connection wide Boolean field “validating” to enable the backwardschaining.

**Comment by jeenbroekstra** [comment]
@hmottestad I see a PR was merged, is this issue done?

**Comment by hmottestad** [comment]
Yes
