### ISSUE TITLE
Unable to control precedence of connective operators such as AND and OR expressions

### ISSUE THREAD

**Issue by reckart** [eclipse/rdf4j#1301]
AND and OR expressions should be parenthesized by the SPARQL query builder to allow controlling their precedence.

Consider this code:

```
            GraphPattern pattern = VAR_SUBJECT.has(labelProperty, VAR_LABEL_CANDIDATES).filter(
                    or(
                            // Match without language
                            function(STRSTARTS, literalOf(aPrefixQuery)),
                            // Match with default language
                            and(function(STRSTARTS, literalOf(aPrefixQuery)), 
                                    function(LANGMATCHES, function(LANG, VAR_LABEL_CANDIDATES), 
                                            literalOf(language)))));
```

It should match either strings starting with a given prefix or strings in a given language starting with the given prefix, but the AND/OR precedence is lost when the query is rendered:

```
SELECT DISTINCT ?s
WHERE { { ?s <http://www.w3.org/2000/01/rdf-schema#label> ?lc .
FILTER ( STRSTARTS( "Barack" ) || STRSTARTS( "Barack" ) && LANGMATCHES( LANG( ?lc ), "en" ) ) } }
GROUP BY ?s
LIMIT 1000
```

It should be 

```
SELECT DISTINCT ?s
WHERE { { ?s <http://www.w3.org/2000/01/rdf-schema#label> ?lc .
FILTER ( STRSTARTS( "Barack" ) || ( STRSTARTS( "Barack" ) && LANGMATCHES( LANG( ?lc ), "en" ) ) ) } }
GROUP BY ?s
LIMIT 1000
```

**Comment by reckart** [comment]
Just found out that I can call `Expression.parenthesize()` on the `and(...)` - IMHO would be more intuitive if this happened automatically for disjunctions and conjunctions.

**Comment by abhishekag03** [comment]
Hi! We (Me, [@Kvatsx](https://github.com/Kvatsx/), [@ishaanbassi](https://github.com/ishaanbassi/))  would like to work on this issue. 
We have understood it and have implemented the solution suggested by [@reckart](https://github.com/reckart). We have parenthesized the expression in case of AND operator by calling the parenthesize function in the Operation method present in sparqlbuilder/constraint/Operation.java file. This is working for query mentioned by @reckart and for some other queries tested by us.
We have also attached a screenshot of the query and the output as shown in terminal on running the example file.
It would be great if you could assign us(Me, [@Kvatsx](https://github.com/Kvatsx/) [@ishaanbassi](https://github.com/ishaanbassi/)) the issue. Meanwhile, we are going through the contributor guidelines and would raise a pull request as soon as possible.

![query](https://user-images.githubusercontent.com/22664770/82249476-744b6200-9967-11ea-8b24-15f1eb4f7ff5.png)
![output](https://user-images.githubusercontent.com/22664770/82249479-76adbc00-9967-11ea-84e5-d6c123a55f58.png)

**Comment by barthanssens** [comment]
Ok, thanks for your help !

**Comment by abhishekag03** [comment]
I have linked a pull request for this issue. Please let me know in case any further modifications are required. Thanks!
