### ISSUE TITLE
LuceneSpinSail needs to be documented

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#1304]
The LuceneSpinSail combination is, from what I gather from looking at the code, something completely different from all our other full-text indexing Sails. It implements a completely different way of doing search patterns, unless I misunderstand the test cases in `AbstractLuceneSailSpinTest`. 

Regardless of whether this way of doing things is better or not, none of this is documented and it confuses the heck out of our users. Pending better documentation and clarification of the purpose of this specific sail, we may need to remove this option from the Workbench repository config menu.

**Comment by jeenbroekstra** [comment]
@jgrzebyta I know you worked on this part of the code. Could you perhaps give a short explanation of the purpose of the LuceneSpinSail and how you're supposed to use it?

**Comment by jgrzebyta** [comment]
OK.Thanks
