### ISSUE TITLE
New Workbench Option: Java Native Store + RDFS + Lucene

### ISSUE THREAD

**Issue by ry99** [eclipse/rdf4j#1311]
I'd like the option for creating RDFS+Lucene repositories via the workbench. Currently, the only option seems to be RDFS+SPIN+Lucene, and this appears not to work with Lucene queries.

**Comment by jeenbroekstra** [comment]
Note that there's a separate issue logged to look into the problems with the SPIN+Lucene combo: #1304 . But adding this option should be fairly straightforward.

**Comment by ry99** [comment]
When I tried to create a Native Store + RDFS + Lucene repository via the workbench, it seemed to revert to Memory Store + RDFS + Lucene on the second screen. I had to manually change the URL query string to create a Native repository
