### ISSUE TITLE
Update versions in developer doc

### ISSUE THREAD

**Issue by barthanssens** [eclipse/rdf4j#1316]
Trivial issue, update/align versions numbers in http://docs.rdf4j.org/developer
Doesn't really make a difference, but makes it more consistent and it looks "better" (e.g. more up to date)

**Comment by jeenbroekstra** [comment]
@barthanssens fwiw I'm getting to the stage with the new site where I'm copying over existing documentation to the new setup/formatting. We should probably hold off on editorial fixes in the existing sites to avoid losing those fixes again because the copy was made too early.
