### ISSUE TITLE
"file:" not a recognized protocol in SparqlBuilder

### ISSUE THREAD

**Issue by reckart** [eclipse/rdf4j#1321]
There is a list of IRI protocols in 

https://github.com/eclipse/rdf4j/blob/836f8ba06e3662c2356010004d1b0edfb1f6ef34/sparqlbuilder/src/main/java/org/eclipse/rdf4j/sparqlbuilder/rdf/Rdf.java#L35-L37

This causes a problem when running queries against the SPARQL endpoint of the [British Museum](http://collection.britishmuseum.org/sparql), because some of their resources have a `file:` IRI and the builder doesn't add the pointy brackets, e.g.:

```
          SELECT DISTINCT ?s
          WHERE { file:/data-to-load/07bde589-588c-4f0d-8715-c71c0ba2bfdb/crm-extensions/E12_Production <http://www.w3.org/2000/01/rdf-schema#subClassOf> ?s .
          FILTER EXISTS { { ?s <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2000/01/rdf-schema#Class> . } UNION { ?someSubClass <http://www.w3.org/2000/01/rdf-schema#subClassOf> ?s . } UNION { ?s <http://www.w3.org/2000/01/rdf-schema#subClassOf> ?someSuperClass . } } }
          GROUP BY ?s
          LIMIT 1000
```

(This query is supposed to retrieve all parent classes of `file:/data-to-load/07bde589-588c-4f0d-8715-c71c0ba2bfdb/crm-extensions/E12_Production`).

Why is the list of protocols restricted at all?

**Comment by jeenbroekstra** [comment]
@reckart main reason this is implemented this way is simply that the SparqlBuilder was originally an independent project. It has been contributed to rdf4j fully developed, but hasn't used any rdf4j-specific code (among which is rdf4j support for IRI validation). 

I've closed this issue as a duplicate as it's really a special case of #1270, we'll track progress on fixing this against the other ticket if you don't mind.

**Comment by reckart** [comment]
@reckart actually, I'm not sure if this is a case for #1270. The builder code uses the protocol only to determine whether to add pointy brackets around the value or not. If it doesn't recognize the value as an IRI, then it leaves the pointy brackets off. This is not really validation.

**Comment by jeenbroekstra** [comment]
You may have a point (sorry, I'm in the middle of prepping a release so somewhat distracted). At the very least we can treat this issue as a quick fix to add `file:` (and perhaps one or two other well-known schemes).

**Comment by reckart** [comment]
When I'm done upgrading our forks to 2.5.0, I'll provide a tentative PR for this one.

**Comment by reckart** [comment]
PR updated: https://github.com/eclipse/rdf4j/pull/1322
