### ISSUE TITLE
Provide static factory methods for Value creation

### ISSUE THREAD

**Issue by reckart** [eclipse/rdf4j#1325]
The SparqlBuilder has some nice factory classes such as `Rdf` which allows for nicely compact code:

```
Rdf.iri("http://www.openrdf.org/contrib/lucenesail#")
```

or even 

```
import static org.eclipse.rdf4j.sparqlbuilder.rdf.Rdf.iri;

iri("http://www.openrdf.org/contrib/lucenesail#")
```

This is much more convenient than the RDF4J approach which requires obtaining a value factory instance. It is also more compact because less verbose method names are chosen (`iri(...)` vs `createIri(...)`):

```
ValueFactory factory = SimpleValueFactory.getInstance();
factory.createIRI(iriString)
```

See also: https://github.com/eclipse/rdf4j/issues/1038#issuecomment-470449531

**Comment by jeenbroekstra** [comment]
Valuefactory is a central component in the framework and it's unlikely that we can replace it. However, it should be possible to provide convenience adapers that make this possible.

**Comment by jeenbroekstra** [comment]
Fwiw in which use cases/how often do you find yourself using the ValueFactory directly? 

Reason I ask is that in several places we have already provided convenience utilities or recommended patterns to make this easier. One example is the `ModelBuilder`, which has extensive support for minting new IRIs on the fly. It would be good to understand what angle we haven't covered.

**Comment by reckart** [comment]
We have ~70 matches for `SimpleValueFactory` in INCEpTION. It's partially being used during manual query construction (a use-case which will be removed and replaced by using the `SparqlBuilder`now). The rest of the uses seem to be related to the fact that it was chosen to use RDF4J IRIs in some of our data objects in favor of plain old Strings. My comment relates mostly to the pre-SparqlBuilder query construction which looks somewhat like this:

```
            String QUERY = <SOME SPARQL QUERY>;
            ValueFactory vf = SimpleValueFactory.getInstance();
            TupleQuery tupleQuery = conn.prepareTupleQuery(QueryLanguage.SPARQL, QUERY);
            tupleQuery.setBinding("s", vf.createIRI(aIdentifier));
            ...
```

**Comment by jeenbroekstra** [comment]
I'm thinking of a design where we provide a set of static functions that internally all use the SimpleValueFactory (though optionally injectable with another ValueFactory implementation), e.g. something like:

               public class Values {
                    public static IRI iri(String iriRef) {
                        return iri(SimpleValueFactory.getInstance(), iriRef);
                    }                
                    public static IRI iri(ValueFactory vf, String iriRef) {
                        return vf.createIRI(iriRef);
                    }
               }

and then the usage could be as simple as:

            import static org.eclipse.rdf4j.model.util.Values.iri;

            String QUERY = <SOME SPARQL QUERY>;
            TupleQuery tupleQuery = conn.prepareTupleQuery(QueryLanguage.SPARQL, QUERY);
            tupleQuery.setBinding("s", iri(aIdentifier));

**Comment by reckart** [comment]
How would you inject a different value factory into the static methods?

**Comment by jeenbroekstra** [comment]
> How would you inject a different value factory into the static methods?

(bit late, apologies - this fell off my radar)

By using the static method overload that takes a `ValueFactory` as an argument. For example, if you want to use a repository's own valuefactory:

```java
        import static org.eclipse.rdf4j.model.util.Values.iri;

        ValueFactory vf = conn.getValueFactory();
        TupleQuery tupleQuery = conn.prepareTupleQuery(query);
        tupleQuery.setBinding("s", iri(vf, aIdentifier));
```

**Comment by jeenbroekstra** [comment]
I've started work on this. In the first implementation I will actually not make `ValueFactory` injectable, to keep things simple. It means that you can use the convenience functions for common cases, and where a specific ValueFactory imlementation is really needed, you will have to fall back to using the ValueFactory directly.
