### ISSUE TITLE
Allow building and releasing using the Maven release plugin

### ISSUE THREAD

**Issue by reckart** [eclipse/rdf4j#1330]
Because of the intertwined dependencies between the different RDF4J repos, it does currently not seem to be possible to simply run a 

```
$ mvn -DautoVersionSubmodules release:prepare release:perform
```

to build a release version (I'm working on a fork).

E.g. the main RDF4J repo depends on the RDF4J storage repo for `org.eclipse.rdf4j:rdf4j-sail-memory`.

There should be no cyclic dependencies between the repos such that one can simply Maven-release one after the other in some specific order.

**Comment by jeenbroekstra** [comment]
Related: #1302

**Comment by jeenbroekstra** [comment]
In the dim past (when we were still using subversion) we used the maven release plugin, but it got abandoned because at the time we moved to git and its more flexible branching support, the release plugin didn't really handle it very well. It would be interesting to revisit, I assume they have fixed these problems by now :) 

I'd be interested to see a proposal for a setup that works with our branching model, and that combines well with doing deployments via Jenkins, over multiple repos. The current release process is a bit of a song and dance, if it can be simplified I'm all for it.

**Comment by reckart** [comment]
Well, to be honest, I didn't grok the branching model of RDF4J yet - in particular the difference between master and develop.

In my projects, I usually have a master branch and any number of maintenance branches (e.g. 1.2.x). It is no problem running a release on either of these branches. I'm working with feature branches that get merged either into master or into a maintenance branch. I regularly merge the maintenance branch into master so it gets the maintenance changes as well (this could be done differently by merging PRs into master + maintenance). After a release of a maintenance branch, I merge it using "-s ours" into master to avoid conflicts on the version in the POM later on. Works well for me any my colleagues.

**Comment by jeenbroekstra** [comment]
The workflow is explained here: http://docs.rdf4j.org/developer/ . In essense, our workflow is what is known as [gitflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow), with some minor variations.

The TL;DR of it is that the master branch tracks against the latest stable release (2.5 in our case) and the next upcoming patch release. It accepts any changes that are bug fixes or project-internal changes. Feature development (anything that is not suitable for inclusion in a patch release) happens against the develop branch, which therefore tracks the state of the next upcoming minor or major release. 

So if you start a new feature, you branch off of develop, when you do a bug fix, you branch off of master. If you're unsure, branch off of master. Branches off master can always be merged into develop if necessary, but we _never_ merge develop to master (until it's time for a new minor/major release that is). 
 
It's not so different from what you describe: your release maintenance branch is (roughly) our master, your master branch is more or less our develop. 

Fwiw I'm not so attached to the current workflow that I won't embrace something better when it comes along, but this has worked well enough for this project for now and I'm wary of changing things for the sake of it.

**Comment by reckart** [comment]
There is a gitflow plugin for Maven, but I haven't used it.

**Comment by jeenbroekstra** [comment]
To clarify my last remark slightly: if we find that we should adapt our branching strategy slightly to accomodate use of the maven release plugin, I think that counts as "not just for the sake of it" :)

**Comment by reckart** [comment]
The release plugin assumes that the development branches (master, maintenance branches) always have SNAPSHOT versions - I do not think it could accommodate the kind of master branch with a release version inside it that you are used to. I suppose one could run releases from the develop branch and after the release manually merge the intermediate non-SNAPSHOT revision that is created during the release into the master branch to simulate gitflow behavior.

**Comment by jeenbroekstra** [comment]
Unless I misunderstand I don't think we do that. Both our develop and our master branch are always set to SNAPSHOT versions, too.

**Comment by barthanssens** [comment]
related (duplicate ?) to #1302

**Comment by jeenbroekstra** [comment]
@barthanssens #1302 is specifically about circular dependencies in our maven modules, which is something worth looking into regardless of how we deploy our releases. This issue is more about using the maven release plugin as a sensible default for release tagging/branching etc.

**Comment by jeenbroekstra** [comment]
I took a look at the maven release plugin again, and it's as convoluted and tricky to use as I remember. We could _probably_ configure it to suit our needs but I don't really want to spend the time. Given that we now have a custom script that handles the release process (see #1598), I'm closing this for now.
