### ISSUE TITLE
SparqlBuilder does not allow blank nodes for predicates

### ISSUE THREAD

**Issue by reckart** [eclipse/rdf4j#1332]
The SparqlBuilder doesn't allow a blank node for a predicate, but it seems having a blank node as a predicate at least works with some triple stores.

```
select ?Concept where {?Concept [] []} LIMIT 100
```

It works on Virtuoso (e.g.: https://dbpedia.org/sparql)

It doesn't work with Blaze (e.g.: https://query.wikidata.org/#select%20%3FConcept%20where%20%7B%3FConcept%20%5B%5D%20%5B%5D%7D%20LIMIT%20100)

**Comment by jeenbroekstra** [comment]
I think this is by design. A blank node is not allowed in that position according to the SPARQL 1.1 Recommendation. Virtuoso is not compliant in allowing this.

**Comment by reckart** [comment]
Yep. It's a pity though. I don't understand why the SPARQL spec doesn't allow this. It seems like an excellent way of checking if any triple with a given subject exists.

I'm using `select ?Concept where {?Concept ?dummy []} LIMIT 100` now which seems to work but which I expect asks the query engine to do more than it would actually have to do (worse to optimize).

**Comment by jeenbroekstra** [comment]
If I remember correctly it's a side effect of the fact that in RDF itself, the predicate can only be an IRI. There was a desire for SPARQL triple patterns to remain "compatible" with RDF in that way. 

I kind of agree with you that it's a shame. I wouldn't worry about performance though - to most query engines this will make no real difference.
