### ISSUE TITLE
Static all loggers

### ISSUE THREAD

**Issue by hmottestad** [eclipse/rdf4j#1336]
Switch to use static loggers (so they can be used by static methods and also so we don't instantiate a bunch of them).

**Comment by hmottestad** [comment]
Done in rdf4j storage

**Comment by jeenbroekstra** [comment]
Unfortunately, this is giving me grief in Eclipse. I'm not sure why yet but running compliance tests from my Eclipse now regularly rails with this kind of error:

```
java.lang.IllegalAccessError: class org.eclipse.rdf4j.sail.memory.MemoryStore tried to access private field org.eclipse.rdf4j.sail.helpers.AbstractSail.logger (org.eclipse.rdf4j.sail.memory.MemoryStore and org.eclipse.rdf4j.sail.helpers.AbstractSail are in unnamed module of loader 'app')
	at org.eclipse.rdf4j.sail.memory.MemoryStore.initializeInternal(MemoryStore.java:245)
	at org.eclipse.rdf4j.sail.helpers.AbstractSail.init(AbstractSail.java:187)
	at org.eclipse.rdf4j.sail.helpers.AbstractSail.initialize(AbstractSail.java:176)
	at org.eclipse.rdf4j.sail.helpers.SailWrapper.initialize(SailWrapper.java:96)
	at org.eclipse.rdf4j.sail.inferencer.fc.SchemaCachingRDFSInferencer.initialize(SchemaCachingRDFSInferencer.java:211)
	at org.eclipse.rdf4j.sail.Sail.init(Sail.java:60)
```

Funnily enough I'm not getting this on the command line or when running in IntelliJ, so it might be something specific to my Eclipse environment. However, there's also the fact that this enhancement comes at a cost, namely that we lose the option of allowing different applications in the same application context to use their own logger (see http://www.slf4j.org/faq.html#declared_static). 

I wonder if the (fairly minimal) overhead reduction is worth it.

**Comment by hmottestad** [comment]
Being able to log from a static context is nice too.

**Comment by jeenbroekstra** [comment]
> Being able to log from a static context is nice too.

True of course. There's no rush with this but I'll try and take a closer look at what's going on with the classloader in Eclipse - it might be a build path config issue rather than an actual problem with the code. I also want to take a closer look at static vs instance on a case by case basis - for example in the AbstractSail there are no static methods, plus it is _intended_ to be inherited from, so a different approach might be useful there.
