### ISSUE TITLE
Spin is stupidly slow

### ISSUE THREAD

**Issue by hmottestad** [eclipse/rdf4j#1337]
Spin is so stupidly slow it's no wonder semantic tech has a bad rep.

Since we aren't going to remove it it's time to make it somewhat usable. 

For reference, same tests run in the context of the ShaclSail (top) and the SpinSail (bottom)

<img width="652" alt="Screenshot 2019-03-10 at 17 29 52" src="https://user-images.githubusercontent.com/797185/54088100-6b6e0200-435a-11e9-8a49-6ea91f9996fb.png">

<img width="650" alt="Screenshot 2019-03-10 at 17 30 36" src="https://user-images.githubusercontent.com/797185/54088101-6dd05c00-435a-11e9-9a0b-12a4d0e4e0db.png">

Notice how testSizeRollback() is "only" 33x slower when using Spin!

**Comment by hmottestad** [comment]
Marked as bug on purpose, since this is bug level performance issues.

**Comment by hmottestad** [comment]
```
Benchmark                        Mode  Cnt    Score    Error  Units
BasicBenchmarks.init             avgt   10  733.603 ± 12.599  ms/op
BasicBenchmarks.memoryStoreInit  avgt   10    0.019 ±  0.005  ms/op
```

**Comment by hmottestad** [comment]
After using IsolationLevels.NONE

```
Benchmark                        Mode  Cnt    Score    Error  Units
BasicBenchmarks.init             avgt   10  700.020 ± 19.515  ms/op
BasicBenchmarks.memoryStoreInit  avgt   10    0.019 ±  0.004  ms/op
```

**Comment by hmottestad** [comment]
Just don't use linked lists:
```
Benchmark                        Mode  Cnt    Score   Error  Units
BasicBenchmarks.init             avgt   10  413.157 ± 9.370  ms/op
BasicBenchmarks.memoryStoreInit  avgt   10    0.021 ± 0.004  ms/op
```

**Comment by hmottestad** [comment]
instanceof before .equals and linkedhashmodel 
```
Benchmark                        Mode  Cnt    Score   Error  Units
BasicBenchmarks.init             avgt   10  395.046 ± 7.605  ms/op
BasicBenchmarks.memoryStoreInit  avgt   10    0.019 ± 0.006  ms/op
```

**Comment by hmottestad** [comment]
For reference:

<img width="654" alt="Screenshot 2019-03-10 at 20 27 31" src="https://user-images.githubusercontent.com/797185/54090295-f3f89c80-4372-11e9-9c2a-69b0a186fee3.png">

**Comment by hmottestad** [comment]
Skip checking contraints during initilization. Doesn't actually make the SpinSail faster per say, but reduces the time it takes to init().

```
Benchmark                        Mode  Cnt    Score   Error  Units
BasicBenchmarks.init             avgt   10  129.928 ± 3.678  ms/op
BasicBenchmarks.memoryStoreInit  avgt   10    0.019 ± 0.004  ms/op
```

**Comment by jeenbroekstra** [comment]
Thanks for looking into this Havard. One minor remark: criticism is fine but please keep it constructive and courteous. Remember that the code you are reviewing was contributed by other people, who have given their volunteering time, and may have had different design criteria than you regarding performance.

**Comment by hmottestad** [comment]
@jeenbroekstra it wasn't very professional of me no :( I just makes me quite angry and sad, I've seen two projects in the million dollar class fail because of choosing SPIN.

**Comment by hmottestad** [comment]
@jeenbroekstra SPIN is still ridiculously slow. SPIN is basically running SPARQL queries for you. If you run them yourself instead of using SPIN, they will easily be 100-1000x faster. Especially for small datasets.

**Comment by jeenbroekstra** [comment]
@hmottestad I closed this because you committed and pushed several improvements to SPIN performance, and I needed a closed issue to mark this as part of the milestone. Happy for you to open a followup issue if you have further improvements in mind (or even if you don't and just think it's important to raise the issue).
