### ISSUE TITLE
Update Jackson dependency

### ISSUE THREAD

**Issue by barthanssens** [eclipse/rdf4j#1338]
Latest version is 2.9.8 and has some fixes and additional protection against some polymorphic deserialization attacks. Not sure if it affects RDF4J, but better safe than sorry I guess.

**Comment by daltontc** [comment]
Do you have an estimate for when this change will be released?

**Comment by barthanssens** [comment]
No release date has been set just yet, could be quite soon, it just depends on the level of interest and/or what else should be part of 2.5.1...

**Comment by barthanssens** [comment]
@daltontc FYI, 2.5.1 has just been released
