### ISSUE TITLE
Server: upgrade to Spring 5.1

### ISSUE THREAD

**Issue by barthanssens** [eclipse/rdf4j#1343]
Part of #1148

Spring 4.3 is only supported until 2020 or so, and no guarantee that it runs on JDK 9/10/11..
5.1 is recommended for JDK11, and upgrading should (hopefully) be straightforward
(https://github.com/spring-projects/spring-framework/wiki/Spring-Framework-Versions)

Not sure if we actually use that much Spring to begin with, or if it is a good idea to continue to use Spring framework ?

Version 5.1.2 in CQ's, but it means that more recent versions like 5.1.7 can also be used

- [x] Spring AOP (CQ19986, PB)
- [x] Spring Beans (CQ19989, PB)
- [x] Spring Context (CQ19990, PB)
- [x] Spring Core (CQ19991, PB)
- [x] Spring Expression (CQ19992, PB)
- [x] Spring Test (CQ19996, PB)
- [x] Spring Web (CQ19993, PB)
- [x] Spring Web MVC (CQ19994, PB)

- [x] Javax Servlet-API 3.1 (CQ20170, PB)

Also upgrade test to use Eclipse Jetty 9 (CQ not required, since it's an Eclipse project)

**Comment by jeenbroekstra** [comment]
We really only use Spring Web MVC I think, so it's fairly minimal. I'm happy to switch to something else but I imagine that doing would mean effectively reimplementing most of the Server and Workbench applications.

**Comment by hmottestad** [comment]
I’m a fan of spring-boot, but then I don’t have much experience with spring (without boot). Any chance spring-boot 2 could be our direction instead? Or too much to rewrite?

**Comment by barthanssens** [comment]
IMHO the easiest way is to just upgrade to 5.1...

Spring Boot is nice, but I'm not sure if it brings much to the table since (at least in my limited experience) it shines with Spring-data and convention-over-code integration with a bunch of other services which we don't use (JPA, messaging...)

For new projects I'd be tempted to look into smaller frameworks like micronaut or quarkus, or microprofile.io, but that's probably a more time-consuming task... Just my 2 cents

**Comment by hmottestad** [comment]
Sounds well thought through @barthanssens :)

**Comment by barthanssens** [comment]
Ok, I'll start entering the CQs for Spring 5.x then  :-)

**Comment by barthanssens** [comment]
related to #1148

**Comment by jeenbroekstra** [comment]
I marked this as not backwards compatible mainly because rdf4j server now _requires_ servlet api 3.1. It means anyone running rdf4j server or workbench on an older servlet container will have to upgrade. Minimal version of Apache Tomcat is now 8. Minimal version of Eclipse Jetty is now 9.

**Comment by barthanssens** [comment]
ah, good catch.... 
IMHO Jetty 9 is not unreasonable, since Jetty 8 is EOL since 2015 or so.
Tomcat 7 isn't EOL yet, but it's getting fairly old (latest versions are 8.5.x and 9.0.x)
