### ISSUE TITLE
spurious logback-classic dependency

### ISSUE THREAD

**Issue by jonenst** [eclipse/rdf4j#1346]
Hi,
since rdf4j 2.3.0, rdf4j-runtime has a transitive dependency to logback-classic
```
$  mvn dependency:tree
[INFO] +- org.eclipse.rdf4j:rdf4j-runtime:jar:2.3.0:compile
[INFO] |  +- org.eclipse.rdf4j:rdf4j-config:jar:2.3.0:compile
[INFO] |  |  \- ch.qos.logback:logback-classic:jar:1.1.8:runtime
```

This was not the case with rdf4j-runtime 2.2.2. Is this on purpose ?

It is a problem for projects using slf4j and another logging implementation. A library should not force a particular logging implementation onto its users.

Of course, a workaround is to manually exclude the dependency in a pom.xml but it would be nice if we didn't have to do it.

Cheers,
Jon

**Comment by barthanssens** [comment]
Indeed, the removal of this dependency is actually on the 3.0 roadmap (see #1106), not sure why it was  introduced.

**Comment by jonenst** [comment]
Thanks
