### ISSUE TITLE
RDFCollections asRDF should allow to pass ValueFactory

### ISSUE THREAD

**Issue by RavinderSinghMaan** [eclipse/rdf4j#1348]
I am using RDFCollections to convert values back and forth between Java lists and RDF lists. It works quite nice but the problem is that I have my own ValueFactory to create Bnodes and would like to pass the instance of ValueFactory to asRDF method. What do you guys think? I can raise the PR if you guys agree.

**Comment by jeenbroekstra** [comment]
That sounds like a good idea - I'm all for better dependency injection support in our APIs. If you want to put up PR that'd be great! 

Please be aware that we recently changed our code formatting conventions. Have a look at the [contributor guidelines](https://github.com/eclipse/rdf4j/blob/master/.github/CONTRIBUTING.md) for more information.
