### ISSUE TITLE
SHACL in workbench?

### ISSUE THREAD

**Issue by robertbbb** [eclipse/rdf4j#1357]
Hi, Very happy to see SHACL coming into RDF4J. However, the documentation does not make it clear how SHACL support must be activated in the server and workbench. Is it part of every type of repository? Will it replace the SPIN support?

**Comment by hmottestad** [comment]
@jeenbroekstra will know what needs to be added to make it work in the server and workbench.

SHACL does not replace SPIN, at least not all of it. SHACL supports restrictions on your data, but not arbitrary restrictions like SPIN does with SPARQL. This makes SHACL a lot faster, but also more restrictive. The SHACL engine is incremental, so it works best if you have a large database and make small changes to it. If your database is 100 triples or 100 million triples doesn't matter much for performance.

In the next release of RDF4J (3.0), SHACL will get even faster and support more of the SHACL standard (currently passing 46/98 compliance tests). In the works is also support for modifying the loaded SHACL shapes. 

SPIN is also a lot faster in 3.0, you should try out the 3.0-SNAPSHOT build if you use SPIN a lot!

**Comment by hmottestad** [comment]
https://github.com/eclipse/rdf4j/issues/1262

**Comment by hmottestad** [comment]
Previous discussions on SPIN vs SHACL: https://github.com/eclipse/rdf4j/issues/1262

**Comment by hmottestad** [comment]
@jeenbroekstra

**Comment by jeenbroekstra** [comment]
There's several possible ways we could enable SHACL support in the workbench. The simplest way is just to offer it as one possible sail configuration for a new repository. We'd need variants on top of a memory store, native store, and possibly combined with an RDFS inferencer as well?   

Another option is as a standalone tool inside the workbench - basically an option to quickly load a file, check it against a schema to see if it's consistent. This will be a lot more work to build though.

**Comment by hmottestad** [comment]
Two new options in the workbench:
 - memory-shacl
 - native-shacl

Shapes need to be "added" to the SHACL context. You have to use the "add" feature and not do it with SPARQL. 

This will all be available in the 3.0 release.
