### ISSUE TITLE
Clean up dependencies pom.xml files

### ISSUE THREAD

**Issue by barthanssens** [eclipse/rdf4j#1364]
It sems that, when the rdf4j project was splitted into different (rdf4j, rdf4j-storage, rdf4j-tools...) subprojects, the pom.xml files inherited most of the dependencies of the old pom.xml, whether they are actually used or not (e.g. commons-codec, file-upload)

Benefit: it works

Drawback: poms are bigger, unsure of dependencies are actually used or not, and arguably harder to maintain/avoid the "dependency hell"

**Comment by jeenbroekstra** [comment]
Related: #1467. I will need to re-shuffle and reorganize the main poms anyway, so I'll close this issue for now.
