### ISSUE TITLE
RDF/XML inline blank nodes, writing without rdf:nodeID ?

### ISSUE THREAD

**Issue by barthanssens** [eclipse/rdf4j#1368]
See https://groups.google.com/forum/#!topic/rdf4j-users/RR1d8JvhChU, reported by Manuel Fiorelli

> I need to produce a compact RDF/XML document representing an OWL ontology containing anonymous class descriptions. In particular, I need to inline blank nodes as follows:
> 
> <owl:Class rdf:about="http://example.org/Italian">
>     <owl:equivalentClass>
>         <owl:Restriction rdf:nodeID="node1d6qktouex1">
>             <owl:hasValue rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Italian</owl:hasValue>
>             <owl:onProperty>
>                 <owl:DatatypeProperty rdf:about="http://example.org/nationality" />
>             </owl:onProperty>
>         </owl:Restriction>
>     </owl:equivalentClass>
> </owl:Class>
> 
> I was able to produce the fragment above using a combination of:
> org.eclipse.rdf4j.rio.rdfxml.util.RDFXMLPrettyWriterFactory
> org.eclipse.rdf4j.rio.turtle.ArrangedWriter
> I used the ArrangedWriter to overcome the limitation of RDFXMLPrettyWriterFactory that requires  the statements in the "right order".
> 
> As you can see (highlighted in yellow), the output include the identifier of the blank node associated with the restriction.
> 
> It is uncommon to see such identifiers in a compact RDF/XML document: is there any option to remove them? Or is there a simpler mechanism to achieve my goal

**Comment by barthanssens** [comment]
Rio Turtle writer is wrapped in an ArrangedWriter to inline blank nodes (= duplicate them if needed, because they can be used/referenced in multiple places)

This could be moved to a higher / more abstract level + some changes in RdfxmlWriter to check whether the RioSetting INLINE_BLANK_NODES is active (and if that is indeed the case, to not write out the blank node id in RDF/XML)

**Comment by barthanssens** [comment]
See also #1079 , looks like the ArrangedWriter might need some bug fixing first.

**Comment by REVERB283** [comment]
Hi!
We (me, @iamaryananand & @Cool007Satyam) were working on the issue and facing some difficulties modelling the problem and want to confirm few things.

This is the test case (as mentioned in the issue #1079 ) we used to understand the working of library better.
`@prefix ex: <http://ex.com/> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

ex:subject 
	ex:rel1 _:bnode ;
	ex:rel2 _:bnode .

_:bnode rdfs:label "the bnode" .
`
This is the XML we got.
`<rdf:RDF
  xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
  xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about="http://ex.com/subject">
    <rel1 xmlns="http://ex.com/">
      <rdf:Description rdf:nodeID="bnode">
        <rdfs:label rdf:datatype="http://www.w3.org/2001/XMLSchema#string">the bnode</rdfs:label>
      </rdf:Description>
    </rel1>
  </rdf:Description>
</rdf:RDF>
`

So if we've understood the problem correctly is that what you're really looking for:
`<rdf:RDF
  xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
  xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about="http://ex.com/subject">
    <rel1 xmlns="http://ex.com/">
      <rdf:Description>
        <rdfs:label rdf:datatype="http://www.w3.org/2001/XMLSchema#string">the bnode</rdfs:label>
      </rdf:Description>
    </rel1>
  </rdf:Description>
</rdf:RDF>`

or maybe this:
`<rdf:RDF
  xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
  xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about="http://ex.com/subject">
    <rel1 xmlns="http://ex.com/">
        <rdfs:label rdf:datatype="http://www.w3.org/2001/XMLSchema#string">the bnode</rdfs:label>
    </rel1>
  </rdf:Description>
</rdf:RDF>`

**Comment by barthanssens** [comment]
Correct,your first example is the intended behavior. 

```
<rdf:RDF
xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
<rdf:Description rdf:about="http://ex.com/subject">
<rel1 xmlns="http://ex.com/">
<rdf:Description>
<rdfs:label rdf:datatype="http://www.w3.org/2001/XMLSchema#string">the bnode</rdfs:label>
</rdf:Description>
</rel1>
</rdf:Description>
</rdf:RDF>
```

As mentioned by Manuel Fiorelli, the current RDF4J behavior is technically not wrong, but it would indeed be nicer to produce the output above.

(your second suggestion is even more compact, but I'm not sure if it is actually valid RDF/XML)

**Comment by iamaryananand** [comment]
Yes, we have achieved your output as mentioned above. We would like to
generate a pull request. Once we commit to our own branch. Will mail you.
Will take approximately 30 minutes.

Thank you

**Comment by iamaryananand** [comment]
We have added a pull request for the current issue.
Kindly check.

Thanks & Regards

**Comment by REVERB283** [comment]
We've moved the CompactXML settings from BasicWriterSettings to XMLWriterSettings and also added the necessary test cases to check for the desired output.
