### ISSUE TITLE
Request for change of font in web gui

### ISSUE THREAD

**Issue by gregid** [eclipse/rdf4j#1371]
The problem with current font on web gui (rdf4j-server, rdf4j-workbench) is that all the digits are in lower case which makes it very hard (impossible?) to distinguish `o` from `0` (try creating `repo01` to see the problem)

Any font with upper case numbers will do.

**Comment by linnaung** [comment]
propose to change (screen.css, html, body)

From: 
font-family: Georgia, Times New Roman, Times Roman, Times, serif;

To:
font-family: Trebuchet MS, Arial, Helvetica, sans-serif;

since the rest of left panel are using the same font-family.
