### ISSUE TITLE
Update JSONLD-Java dependency to 0.8.3

### ISSUE THREAD

**Issue by ansell** [eclipse/rdf4j#138]
There have been a few bug fixes to JSONLD-Java between 0.7.0 and the 0.8.3 version that was released yesterday. Once the creation of the 1.0 branch is done may be a good time to upgrade. It is still Java-6 compatible so will work with both branches. At some stage in the future it will move to Java-8 but not sure of the timeline for that yet.

**Comment by jeenbroekstra** [comment]
Note that this will require that we file a [Contribution Questionnaire (CQ)](https://wiki.eclipse.org/Development_Resources/Contribution_Questionnaire) in [IPZilla](https://dev.eclipse.org/ipzilla/). 

As inspiration: the previous CQ, for JSONLD-Java  0.7.0, can be found here: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=10530 .

**Comment by ansell** [comment]
I can't see that bugzilla page as I am not a committer.

**Comment by jeenbroekstra** [comment]
No worries, I can take care of the CQ when the time comes. Just so you're aware that this is necessary before updating a dependency version.

**Comment by jeenbroekstra** [comment]
CQ filed: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=11532

**Comment by ansell** [comment]
Just to recap if Eclipse Legal look here, as mentioned on Issue #177 this is causing an actual software issue (Apache HttpClient dependencies) that would be helped by upgrading 0.7.0 and 0.8.3 so it is a higher priority than just pulling in the other minor bug fixes to JSONLD-Java during that period.

**Comment by jeenbroekstra** [comment]
CQ is approved. We can include v 0.8.3.
