### ISSUE TITLE
SparqlBuilder does not support DELETE WHERE queries

### ISSUE THREAD

**Issue by reckart** [eclipse/rdf4j#1381]
The SparqlBuilder currently only seems to support `DELETE_DATA` queries, but not `DELETE WHERE`queries. E.g. queries such as these:

```
PREFIX dc:  <http://purl.org/dc/elements/1.1/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

DELETE
 { ?book ?p ?v }
WHERE
 { ?book dc:date ?date .
   FILTER ( ?date > "1970-01-01T00:00:00-02:00"^^xsd:dateTime )
   ?book ?p ?v
 }
```
*Source: https://www.w3.org/TR/sparql11-update/#delete*

```
PREFIX foaf:  <http://xmlns.com/foaf/0.1/>

DELETE WHERE { ?person foaf:givenName 'Fred';
                       ?property      ?value }
```
*Source: https://www.w3.org/TR/sparql11-update/#deleteWhere*

**Comment by mhernandeza** [comment]
Hi @reckart, I found support for this functionality under `Queries.MODIFY().delete().where();`, hope this helps.

**Comment by barthanssens** [comment]
It is indeed part of Queries.MODIFY() 
It might be more intuitive to (also) have a Queries.DELETE(..) and Queries.INSERT(...) shortcut
