### ISSUE TITLE
License header should not use JavaDoc comment style

### ISSUE THREAD

**Issue by reckart** [eclipse/rdf4j#1382]
The license header uses JavaDoc style (`/** */`). 

```
/*******************************************************************************
 * Copyright (c) 2015 Eclipse RDF4J contributors, Aduna, and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *******************************************************************************/
```

This can cause some JavaDoc analyzers to wrongly recognize the license header as the JavaDoc for the class, in particular if there is no other class-level JavaDoc comment.

This can be fixed by changing the comment style to a normal block comment, e.g.:

```
/*
 * Copyright (c) 2015 Eclipse RDF4J contributors, Aduna, and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 */
```

or

```
/* *****************************************************************************
 * Copyright (c) 2015 Eclipse RDF4J contributors, Aduna, and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 * *****************************************************************************/
```

**Comment by reckart** [comment]
Also, the copyright year should probably either be removed or updated.

**Comment by jeenbroekstra** [comment]
We use the copyright year to indicate the original contribution. As such, it should not be updated but reflect the year the file was first added to the project. 

As an aside, note that the license header you quoted here is actually a legacy header that is only used for code that was originally part of OpenRDF Sesame. For any new contributions, we use this license header:

```
/*******************************************************************************
 * Copyright (c) ${year} Eclipse RDF4J contributors
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Distribution License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *******************************************************************************/
```

As for the formatting: our license header follows the prescribed format in general use within the Eclipse Foundation. See https://www.eclipse.org/projects/handbook/#ip-copyright-headers . I must admit I have never encountered any IDE or tool that had issues with this format in the way that you describe.

**Comment by jeenbroekstra** [comment]
I do notice that apparently we have not always been good at enforcing this format, there's a couple of places where the license header is not formatted as it should be....
