### ISSUE TITLE
Pass JsonLdOptions through parser configs 

### ISSUE THREAD

**Issue by RavinderSinghMaan** [eclipse/rdf4j#1387]
Hi all

We discussed [here](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/rdf4j-users/xrirAvWzcP8/2jXVDWsFBwAJ) if JsonLDOptions object should be allowed to pass through parser configs. We agree that it will help in some use cases to allow to do so hence raising this feature request.

Thanks
Ravinder

**Comment by barthanssens** [comment]
Related to #395
