### ISSUE TITLE
Support repository create in the RDF4J Server REST API

### ISSUE THREAD

**Issue by gregid** [eclipse/rdf4j#1389]
Other than reverse engineering workbench calls there is no way of creation of repositories with the REST API. This is something I rely on and would gladly have official and reliable RDF4J Server REST API.

**Comment by jeenbroekstra** [comment]
Part of the reason this is not officially documented is that the current method for creating repositories via REST is obsolete. It relies on using a SYSTEM repository, which we no long really have (the reason it still works is that there is code in place to "redirect" operations on the SYSTEM repo).

Before we document an official protocol for repository creation in the REST API, we should first actually _create_ a better protocol. 

The ideal method is to allow a PUT against the `/repositories/<repId>` endpoint with a repository configuration as the payload. On a non-existing `repId` this will create the new triplestore, and on an existing one it can be implemented to support re-configuration of the existing store.

**Comment by jeenbroekstra** [comment]
I'm introducing the use of Wiremock to do client-side testing of client-server interaction with this. CQ pending: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=20192
