### ISSUE TITLE
Should package names be named based on major version

### ISSUE THREAD

**Issue by ansell** [eclipse/rdf4j#139]
A major issue for compatibility between dependencies for projects are when package names overlap between major versions, but functionality has changed between the versions and both major versions need to be present to satistfy the dependencies.

One possibility given that this is a new project at Eclipse would be to start adding version numbers to the package (or class/interface) names to enable future users to have third-party dependencies on both RDF4J-1 and RDF4J-2 without conflicts.

There is a limited window for doing this before the first full releases are done, and it may not be judged to be necessary, but necessary to have the discussion now.

Another option could be to just change the RDF4J-1 package names to make them distinct, and put off changing the others until a future RDF4J-3 comes along.

**Comment by jeenbroekstra** [comment]
My (somewhat kneejerk) reaction is that it sounds like an awfully complicated solution to a corner case problem. Do you think the situation that a project will need _both_ RDF4J 1 and RDF4J 2 *in the same project* likely in practice?

**Comment by ansell** [comment]
It is a rarely used pattern as it requires a very large userbase to really have effects. However, doing that, together with versioning the Maven module names (forgot to mention that above), can alleviate issues that users may have.

Brought it up now as there is no other real chance to discuss it other than at the very start of a major version release cycle.

I haven't seen it yet, but that was possibly due to the very long Sesame-2.x series that was stable for a long time. If RDF4J-2.x will be API stable for a similar length of time (10+ years?) it would be more fuss than it is worth, as you say. Most users won't be starting with RDF4J-1.0 if they want others to reuse their libraries at this point.

Can always bring it up again if RDF4J-3.x starts up in the future while people don't want to move off 2.x.

**Comment by jeenbroekstra** [comment]
Thanks Peter. It's a good thing to bring up at this time, but unless you have a _really_ strong preference for doing this I'd rather close this for now. We can keep it as an idea in reserve for a next major release, for sure.

**Comment by ansell** [comment]
It can be closed. Good to have discussion about it, but not needed for versions 1 and 2.
