### ISSUE TITLE
Provide compatibility/transitional modules for old package hierarchy

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#14]
The goal would be to provide the old package hierarchy with all classes deprecated, and marked as (empty) subclasses of their equivalent.

**Comment by jeenbroekstra** [comment]
Followup of #13

**Comment by jeenbroekstra** [comment]
Received a tip that [Groovy](http://www.groovy-lang.org/) might be a good tool for this job. It has extensive metaprogramming capabilities.

**Comment by jeenbroekstra** [comment]
If we can't figure this out (it sounds like quite a challenge), we may end up doing what e.g. Jena also did, and just say "rename your imports" in the upgrade documentation. Or we can go one step further and provide a script that automatically replaces import statements in Java code.

**Comment by nikolavp** [comment]
I think that we should just provide a tool to find and replace the package imports. Creating dummy classes in the old packages will be a big bag to carry on with releases.

**Comment by jeenbroekstra** [comment]
@nikolavp upon reflection I think you are right. There's no doubt that the transition will be a pain for some of our users, but it's probably best to just make it a clean break and provide some basic support. In any case, the package rename is not very difficult:

s/org.openrdf/org.eclipse.rdf4j
s/info.aduna/org.eclipse.rdf4j.common

**Comment by ansell** [comment]
@nikolavp , we would only support a migration package for one or two releases, but it would be a burden in general as you say. The main reason for it would be to enable a small changeover period for transitions for third-party libraries, as it is simple to change ones own code with find-replace but more difficult to get upstream libraries to either change or rerelease.

**Comment by nikolavp** [comment]
Third-party libraries is a good point.

Most of the time if a library is moving to a major new version for one of it's dependencies, it should probably also increase it's major version. Maybe this should be pointed out in the upgrade guide?

Sadly this won't prevent the problem where the user is upgrading rdf4j(sesame) but forgets to upgrade a library that depends on sesame or even worse the library doesn't have a new release. I see no way to prevent that from happening.
