### ISSUE TITLE
Docs link broken in "Installing RDF4J Server and RDF4J Workbench"

### ISSUE THREAD

**Issue by berezovskyi** [eclipse/rdf4j#140]
1. Go to http://rdf4j.org/doc/rdf4j-server-workbench-and-console/installing-rdf4j-server-and-rdf4j-workbench/#RDF4J_Server_and_RDF4J_Workbench
2. Click on Download link http://new.rdf4j.org/download/
3. Get 404 from Rivuli Development blog

**Comment by berezovskyi** [comment]
I think it's best to link to http://rdf4j.org/download/#Get_RDF4J (or create a subheading like "RDF4j SDK" so that you can link to it in the future) and keep the latest link updated there.

**Comment by jeenbroekstra** [comment]
Thanks for reporting. Link is now fixed (and I also made sure that the subdomain redirects properly, in case other links still use it).
