### ISSUE TITLE
provide more concrete details on install page

### ISSUE THREAD

**Issue by timrdf** [eclipse/rdf4j#1400]
http://docs.rdf4j.org/server-workbench-console/#_installing_rdf4j_server_and_rdf4j_workbench

* Indicate specific version of "recent, stable version of Apache Tomcat", with link to download. (is [9](https://tomcat.apache.org/download-90.cgi) okay?)
* Provide link in "you will first need to download the RDF4J SDK" ([here?](http://rdf4j.org/download/))

Add instructions for how to deploy using https://hub.docker.com/r/eclipse/rdf4j-workbench
(including how to deal with the fact that there is no "latest" tag: Error response from daemon: manifest for eclipse/rdf4j-workbench:latest not found -- and get some tags that are not "testing")

**Comment by jeenbroekstra** [comment]
Thanks for raising this @timrdf - I've added some links to help clarify the installation instructions.

@barthanssens @hmottestad  you're more in touch with what the status of our docker deployments is. Can we add some instructions to the "Server, Workbench, Console" page on how to obtain the latest docker image and use it? Or are we not yet ready (I'm not immediately sure why the current image tags still use `testing`, tbh).

**Comment by barthanssens** [comment]
The docker images run just fine actually, butI'm still adding "testing" because the current setup does not use a username/password (and no HTTPS)

**Comment by hmottestad** [comment]
I’ve also revamped the build and added a docker-compose file (develop branch) that will let us/others play with the newest things in server/workbench. 

Is there any chance we can get Jenkins to automatically build and deploy docker images for us?
