### ISSUE TITLE
Investigate Lyo-store as a possible object mapping solution for rdf4j

### ISSUE THREAD

**Issue by abrokenjester** [eclipse/rdf4j#1401]
Lyo-store is the rdf-to-oslc object mapping solution from the Lyo project. Currently it provides bindings for Jena, but it looks potentially generally useful for rdf4j users as well. See https://github.com/eclipse/lyo.store

**Comment by kenwenzel** [comment]
Maybe you also like to have a look at [KOMMA](https://github.com/komma/komma)
It implements a flexible object-RDF-mapper with a JPA-like interface.
KOMMA is based on previous works like Empire, Alibaba and the Eclipse Modeling Framework (EMF).
There are also some basic [examples](https://github.com/komma/komma-examples).

**Comment by jeenbroekstra** [comment]
@kenwenzel that looks interesting, I wasn't aware of this project. I'll add a link to that on the [related projects](https://rdf4j.org/related/) section of the RDF4J website.

**Comment by kenwenzel** [comment]
Perfect! 
I also thought about an even deeper integration of KOMMA's mapping framework with Rdf4j. KOMMA uses its own interfaces for RDF concepts and is therefore framework agnostic. But currently it only implements one adapter to RDF frameworks and this one is for Rdf4j ;-)
