### ISSUE TITLE
SPARQL: Use of variable in expression puts it in scope

### ISSUE THREAD

**Issue by cygri** [eclipse/rdf4j#1403]
This query should have no variables in its `SELECT` list:
```sparql
SELECT * {
    FILTER (!bound(?a))
}
```
But in RDF4J, it has one variable, `?a`.

[SPARQL 1.1, § 16.1.1 Projection](https://www.w3.org/TR/2013/REC-sparql11-query-20130321/#selectproject) says (emphasis mine):

> The syntax SELECT * is an abbreviation that **selects all of the variables that are in-scope** at that point in the query. It **excludes variables only used in FILTER**, in the right-hand side of MINUS, and takes account of subqueries.

[18.2.1 Variable Scope](https://www.w3.org/TR/2013/REC-sparql11-query-20130321/#variableScope) repeats this:

> use of a variable in FILTER, or in MINUS **does not cause a variable to be in-scope** outside of those forms.

The problem also appears to affect other uses of expressions. This query should have `?b` in its `SELECT` list but not `?a`, but has both in RDF4J:
```sparql
SELECT * {
    BIND (?a AS ?b)
}
```

**Comment by jeenbroekstra** [comment]
This is a bug in the WildcardProjectionProcessor. It doesn't correctly ignore input variables in bind expressions (`ExtensionElem`s).
