### ISSUE TITLE
SPARQL: UNION is ignored if it binds no variables

### ISSUE THREAD

**Issue by cygri** [eclipse/rdf4j#1404]
This query should return two solutions with no variables, but in RDF4J returns only one such solution:
```sparql
SELECT * {
    {} UNION {}
}
```
Its behaviour should be the same as this equivalent query, which works fine in RDF4J:
```sparql
SELECT * {
    VALUES () { () () }
}
```
It appears that RDF4J simply ignores a `UNION` that does not bind any variables, even though the `UNION` can affect the number of results. This can be seen in the following query, which RDF4J evaluates as if the `UNION` was not there:
```sparql
SELECT * {
    BIND (1 AS ?a)
    {} UNION {}
}
```

**Comment by jeenbroekstra** [comment]
This is a bug in the `QueryModelNormalizer`, one of the standard optimizers. It actually deliberately replaces a union with two singleton sets as arguments with a single singleton.
