### ISSUE TITLE
SPARQL: Variables from outside group are visible inside group

### ISSUE THREAD

**Issue by cygri** [eclipse/rdf4j#1405]
The following query's query pattern has two group graph patterns:
```sparql
SELECT * {
  { BIND ("a" AS ?a) }
  { BIND (?a AS ?b) } 
}
```
According to the SPARQL spec, the result of the query is defined as the result of evaluating each group independently, and then joining the results:

- Evaluating the first group should yield a single solution with `?a` bound to `"a"`.
- Evaluating the second group should yield a single solution with no variables bound. Each group is evaluated independently, and `?a` is not bound within the group, so the `BIND` leaves `?b` unbound.
- Joining both results should yield a single solution with `?a` bound to `"a"`.

In RDF4J, however, the query returns a single solution with both `?a` and `?b` bound to `"a"`. This is incorrect.

Similar problems exists for other language constructs. For example, changing the second group to an `OPTIONAL` shows the same problem. But changing it to a subquery does not.

**Comment by jeenbroekstra** [comment]
Can you give an example query with an optional pattern that shows this issue? Reason I ask is that first glance the issue appears to be specific to how BIND is processed, but I may be overlooking something.

**Comment by cygri** [comment]
What I meant is, it's not just group graph patterns that are affected, but if the second group was replaced by, say, `OPTIONAL { BIND (?a AS ?b) }`, it shows the same problem (or so I seem to remember—haven't tried it again now).

It may well be specific to `BIND`.

**Comment by jeenbroekstra** [comment]
I have just realized that this fix is incomplete: while all the mechanics are put in place, the query planner doesn't actually _use_ the new logic to determine what join strategy to use. :man_facepalming: 

That'll teach me for adding a fix without a regression test.
