### ISSUE TITLE
Repository links are greyed out in Workbench after creation

### ISSUE THREAD

**Issue by berezovskyi** [eclipse/rdf4j#141]
RDF4J Workbench 2.0M1
Chrome 50

After I create the repository, I see the following screen:

<img width="588" alt="screen shot 2016-05-19 at 16 31 34" src="https://cloud.githubusercontent.com/assets/64734/15397167/660e49c6-1ddf-11e6-96c3-f5060181c23f.png">

Note grey links on the left. If I reload the page, now the links are active:

<img width="576" alt="screen shot 2016-05-19 at 16 33 37" src="https://cloud.githubusercontent.com/assets/64734/15397218/8bc69d30-1ddf-11e6-9e6a-0787241d5601.png">

**Comment by berezovskyi** [comment]
Note that if I just navigate to the "Repositories" and back without a full page refresh, the links still remain inactive.

**Comment by jeenbroekstra** [comment]
Confirmed, I can reproduce this. It appears to be specific to Chrome. I tested Firefox (46.0.1) and Safari (9.1) and there the problem does not occur.

**Comment by gwcox66** [comment]
For what it's worth, I've seen this problem with new repositories as well.  I too use Chrome.  However, I find that eventually without any specific action on my part the links all become active and I can proceed as normal.  My work-around is to create repositories as the last thing in the work day and start using them the next day.  I'd be curious as to whether @berezovskyi sees this eventual active links behavior as well.  Just thought this might be a clue in helping to track down the bug...
