### ISSUE TITLE
what is the right process to update rdf4j server without data corruption

### ISSUE THREAD

**Issue by yyz1989** [eclipse/rdf4j#1411]
Hi there,

I am trying to figure out what is the right way to update RDF4J Server so that existing data will not be damaged. I hope this can be documented somewhere or in release notes.

Basically the safe approach I can imagine is export existing data, update the server war, create new repository, and import the dump back again. But of course this requires some additional work. The simple approach would be just replacing the war file directly and assume everything works fine. 

I think for updating bug fix releases, like from 2.5.0 to 2.5.1, maybe replacing the war file is sufficient. But I am not sure about updates between minor releases, like from 2.3 to 2.4, 2.4 to 2.5. What is the general principles here?

Many thanks for the suggestion.

Best regards,
Yang

**Comment by hmottestad** [comment]
Have you experienced corruption while upgrading? 

Have you experienced corruption while restarting?

**Comment by jeenbroekstra** [comment]
For upgrading between minor releases, the general principle is that it's safe to do so: minor releases are always backwards-compatible. Of course, creating a backup before doing _any_ upgrade is a wise practice. But in general: a minor-release upgrade of Rdf4j Server should work without having to manually restore data.

Very occasionally, we do improvements that require some form of re-indexing of existing databases. But if this is the case, it is handled by the Server for you, and is typically mentioned in the release notes (so you are warned to take a backup in case you need to downgrade again).

**Comment by hmottestad** [comment]
I propose to close this @yyz1989 . Was Jeen’s answer what you were looking for?
