### ISSUE TITLE
Parser fails to recognise equal lexical/abbreviated datatypes for literals in turtle serialisation

### ISSUE THREAD

**Issue by ArkanEmre** [eclipse/rdf4j#1412]
Hello everyone,

I am trying to compare two semantically equal turtle files and the parser seems to not recognise that these are equal. 

I wrote this little test to demonstrate the problem:

```
    @Test
    public void testParser() throws Exception {
        String lexical = "<http://example.org/Resource> <http://example.org/Predicate> \"4.75\"^^xsd:double .";
        RDFParser rdfParser = Rio.createParser(RDFFormat.TURTLE);
        Model lexicalModel = new LinkedHashModel();
        rdfParser.setRDFHandler(new StatementCollector(lexicalModel));
        rdfParser.parse(new ByteArrayInputStream(lexical.getBytes()), "");

        String abbreviated = "<http://example.org/Resource> <http://example.org/Predicate> 4.75E0 .";
        Model abbreviatedModel = new LinkedHashModel();
        rdfParser.setRDFHandler(new StatementCollector(abbreviatedModel));
        rdfParser.parse(new ByteArrayInputStream(abbreviated.getBytes()), "");
        
        assertTrue(lexicalModel.filter(null, null, null).stream().map(x -> abbreviatedModel.contains(x.getSubject(), x.getPredicate(), x.getObject())).reduce(true, (a, b) -> a && b));
    }
```
Using Java 8 and RD4FJ 2.5.1
Do you know what might be the cause?

Best regards
Emre

**Comment by hmottestad** [comment]
Can you print all the statements in each model (toString() on each statement) so we can see what datatype RDF4J decided on, and post it here?

**Comment by ArkanEmre** [comment]
> Can you print all the statements in each model (toString() on each statement) so we can see what datatype RDF4J decided on, and post it here?

Here are the models:
```
Lexical Model: [(http://example.org/Resource, http://example.org/Predicate, "4.75"^^<http://www.w3.org/2001/XMLSchema#double>) [null]]

Abbreviated Model: [(http://example.org/Resource, http://example.org/Predicate, "4.75E0"^^<http://www.w3.org/2001/XMLSchema#double>) [null]]
```

**Comment by hmottestad** [comment]
I think the default is to not normalise literals. You can try to turn on normalisation like this:
```
rdfParser.getParserConfig().set(BasicParserSettings.NORMALIZE_DATATYPE_VALUES, true);
```

**Comment by hmottestad** [comment]
I propose to close this issue now.

**Comment by ArkanEmre** [comment]
> I think the default is to not normalise literals. You can try to turn on normalisation like this:
> 
> ```
> rdfParser.getParserConfig().set(BasicParserSettings.NORMALIZE_DATATYPE_VALUES, true);
> ```

Thank you very much, this was very helpful!
