### ISSUE TITLE
Upgrade japicmp-maven-plugin

### ISSUE THREAD

**Issue by hmottestad** [eclipse/rdf4j#1421]
Upgrade japicmp-maven-plugin to 0.14.0 because this one is compatible with Java 11.

**Comment by hmottestad** [comment]
relates to https://github.com/eclipse/rdf4j/issues/1148

**Comment by barthanssens** [comment]
To be checked if there is a need to be a CQ for the japicmp or not (IIRC there was a mail about maybe putting all build-tools in one request)

**Comment by hmottestad** [comment]
I merged the one on RDF4J storage already.
