### ISSUE TITLE
Custom dataset parameters for SPARQL Updates are not documented for requests to the statements endpoint

### ISSUE THREAD

**Issue by desislava-hristova-ontotext** [eclipse/rdf4j#1434]
Custom dataset parameters using-graph-uri, using-named-graph-uri, remove-graph-uri, insert-graph-uri are documented for SPARQL Updates for transaction API, but they are also supported for simple SPARQL Updates and are processed by the StatementsController, although they are not documented in https://rdf4j.eclipse.org/documentation/rest-api/#repository-statements . Is there any reason for this?

**Comment by jeenbroekstra** [comment]
I think the reason is simply that we overlooked it :) Thanks for notifying us!
