### ISSUE TITLE
Deprecation still uses Sesame versioning

### ISSUE THREAD

**Issue by woutermont** [eclipse/rdf4j#1437]
The version indications of deprecated parts of the api still seem to use the versioning of Sesame. A lot of code is, for example, _deprecated since 2.8_ or _deprecated since 4.0_. While not a major issue, it makes it hard to get a historical view on deprecation in rdf4j.

**Comment by jeenbroekstra** [comment]
A quick fix to this would be to just replace all old Sesame versions with '2.0' (the first "proper" rdf4j release). 

We haven't deprecated much since, anyway, and I think the notion of mentioning the version kinda fell into disuse. We may want to re-start doing that.
