### ISSUE TITLE
Broken link to sesame cookbook

### ISSUE THREAD

**Issue by barthanssens** [eclipse/rdf4j#1451]
Via RDF users forum
https://groups.google.com/forum/#!topic/rdf4j-users/uGqVYXMdYog

> Within the RDF4J docs https://rdf4j.eclipse.org/documentation/server-workbench-console/ a page is referenced that is not available:
> http://rivuli.nz/further-reading/sesame-cookbook/basic-security-with-http-authentication/
>

**Comment by jeenbroekstra** [comment]
Should be fixed by incorporating the text from http://graphdb.ontotext.com/documentation/6.6/free/access-rights-and-security.html (which was originally copied from the Rivuli cookbook article) back into the Server documentation.
