### ISSUE TITLE
Federated store basic SELECT / LIMIT regression

### ISSUE THREAD

**Issue by barthanssens** [eclipse/rdf4j#1452]
Via RDF4J user forum

https://groups.google.com/forum/#!topic/rdf4j-users/_j_zcPq3Jbc

> I am expriencing much slower performance on RDF4j v2.5.2 comparing with Sesame v2.7.12.
> Both are using Native store same data about 100 millions.
> 
> SELECT * WHERE {
> ?sub ?pred ?obj .
> }
> LIMIT 1
> 
> On Sesame it returns in seconds but RdF4J takes 2/3 minutes.
> If volume is lesser, RDF4j takes lesser time but on sesame it is really super fast.
> 
> After analyzing the code I have found that  RDF4j is using AbstractFederationConnection which has additional more filter to optimize the query comparing with sesame v2.7.12's NativeStoreConnection.
> 
> Based on by debuging/profiling FederationJoinOptimizer or EmptyPatternOptimizer is the cause.

**Comment by jeenbroekstra** [comment]
The issue as reported is not with the native store itself, but with the FederationJoinOptimizer - in other words in a setup where the (native) store is part of a Federated Store setup. For some reason the optimizer does a deep traversal of the query tree, and it looks like at the bottom of it ends up scanning the entire database.

**Comment by jeenbroekstra** [comment]
From what I can tell it looks like the hotspot is the retrieval of context identifiers by the join optimizer in `createContextToMembersMap` (line 86).

**Comment by jeenbroekstra** [comment]
Related issue #1453 - but I would like to see if apart from making getContextIDs more performant, we can get the JoinOptimizer to be a bit cleverer.
