### ISSUE TITLE
Umbrella CQ listing all build/test (maven...) tools

### ISSUE THREAD

**Issue by barthanssens** [eclipse/rdf4j#1464]
Create one big "works_with" CQ listing all the build / test tools and plugins.

- [x] https://dev.eclipse.org/ipzilla/show_bug.cgi?id=20318

See discussion on

- https://www.eclipse.org/lists/incubation/msg00658.html
- https://wiki.eclipse.org/Development_Resources/IP/Test_and_Build_Dependencies

| plugin | version | license | site |
|-----------------------|-|-|-|
|animal-sniffer-maven-plugin|1.16-1.18|MIT|https://www.mojohaus.org/animal-sniffer/|
|bndlib|2.4.0|Apache|https://mvnrepository.com/artifact/biz.aQute.bnd/bndlib/2.4.0|
|buildnumber-maven-plugin|1.4|MIT|https://www.mojohaus.org/buildnumber-maven-plugin/|
|extra-enforcer-rules|1.0-1.2|Apache|https://www.mojohaus.org/extra-enforcer-rules/|
|formatter-maven-plugin|2.8.1-2.10|Apache|https://code.revelc.net/formatter-maven-plugin/|
|japicmp-maven-plugin|0.11-0.14.1|Apache|https://github.com/siom79/japicmp|
|maven-antrun-plugin|1.0-1.8|Apache|http://maven.apache.org/plugins/maven-antrun-plugin/|
|maven-assembly-plugin|3.1.1|Apache|http://maven.apache.org/plugins/maven-assembly-plugin/|
|maven-bundle-plugin|3.3.0-4.2.0|Apache|http://felix.apache.org/components/bundle-plugin/|
|maven-clean-plugin|3.0.0-3.1.0|Apache|https://maven.apache.org/plugins/maven-clean-plugin/|
|maven-compiler-plugin|3.7.0-3.8.1|Apache|https://maven.apache.org/plugins/maven-compiler-plugin/|
|maven-dependency-plugin|2.8.0-3.1.1|Apache|https://maven.apache.org/plugins/maven-dependency-plugin/|
|maven-deploy-plugin|2.5.0-3.0.0|Apache|https://maven.apache.org/plugins/maven-deploy-plugin/|
|maven-eclipse-plugin|2.9-2.10|Apache|https://maven.apache.org/plugins/maven-eclipse-plugin/|
|maven-enforcer-plugin|1.4.1-3.0.0|Apache|https://maven.apache.org/enforcer/maven-enforcer-plugin/|
|maven-failsafe-plugin|2.19.1-3.0.0|Apache|https://maven.apache.org/surefire/maven-failsafe-plugin/|
|maven-gpg-plugin|1.6|Apache|https://maven.apache.org/plugins/maven-gpg-plugin/|
|maven-jar-plugin|2.3.1-3.1.2|Apache|https://maven.apache.org/plugins/maven-jar-plugin/|
|maven-javadoc-plugin|2.8.1-3.1.0|Apache|https://maven.apache.org/plugins/maven-javadoc-plugin/|
|maven-resources-plugin|3.0.2-3.1.0|Apache|https://maven.apache.org/plugins/maven-resources-plugin/|
|maven-shade-plugin|3.2.1|Apache|https://maven.apache.org/plugins/maven-shade-plugin/|
|maven-source-plugin|2.4-3.1.0|Apache|https://maven.apache.org/plugins/maven-source-plugin/|
|maven-surefire-plugin|2.21.0-3.0.0|Apache|https://maven.apache.org/surefire/maven-surefire-plugin/|
|maven-war-plugin|2.1.1-3.2.3|Apache|https://maven.apache.org/plugins/maven-war-plugin/|
|nexus-staging-maven-plugin|1.6.7-1.6.8|EPL|https://github.com/sonatype/nexus-maven-plugins/tree/master/staging/maven-plugin|
|tomcat7-maven-plugin|2.2|Apache|https://tomcat.apache.org/maven-plugin-2.2/|
|wagon-ssh-external|2.8-3.3.3|Apache|https://maven.apache.org/wagon/wagon-providers/wagon-ssh-external/|

**Comment by barthanssens** [comment]
Quick and dirty:
`find . -name pom.xml -exec grep artifactId\> {} \; | cut -d ">" -f 2 | cut -d "<" -f 1 | sort -u > dependencies`

**Comment by jeenbroekstra** [comment]
Thanks for raising @barthanssens . Do you want to log this CQ or do you prefer that I try?

**Comment by barthanssens** [comment]
if it's ok with you, I'll create the CQ this Monday or Tuesday, I'll add the versions for good measure

**Comment by jeenbroekstra** [comment]
That'd be great, thank you. If you can, be a bit liberal with the versions (I think they allow a range) - so that we don't have to update this every time we bump a version.

**Comment by barthanssens** [comment]
Got PMC approved, so should be good to go
