### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [eclipse/rdf4j#1475]
Hi
The following lines have cryptographic API misuses. <br> File name => rio/api/src/main/java/org/eclipse/rdf4j/rio/helpers/AbstractRDFParser.java: Line number => 120: API name => MessageDigest:Operation on object of type java.security.MessageDigest object not completed. Expected call to digest, update<BR>

**Comment by jeenbroekstra** [comment]
Reporter is a bot, issue is not relevant. Closing.
