### ISSUE TITLE
IRI - checking for : is not sufficient to determine if something is an IRI

### ISSUE THREAD

**Issue by logycon** [eclipse/rdf4j#1480]
https://github.com/eclipse/rdf4j/blob/de2f9de7d328897977aaaf6d2ce5d735d58cadf8/model/src/main/java/org/eclipse/rdf4j/model/impl/SimpleIRI.java#L73

setIRI method should do more to conform to IRI RFC 3987 than just checking whether string contains a : .

https://www.ietf.org/rfc/rfc3987.txt

**Comment by jeenbroekstra** [comment]
The `SimpleIRI` class is deliberately light on validation, for performance reasons. The various Rio parsers all handle the necessary validations of IRI strings, and if you need to programmatically create IRIs yourself and need this kind of validation, you can use the [ValidatingValueFactory](https://rdf4j.eclipse.org/javadoc/latest/org/eclipse/rdf4j/model/impl/ValidatingValueFactory.html).
