### ISSUE TITLE
DELETE WHERE queries do not accept graphs in the delete pattern

### ISSUE THREAD

**Issue by mhernandeza** [eclipse/rdf4j#1481]
The `Queries.MODIFY().delete()` method in the SPARQL Builder only accepts `TriplePatterns`, so building a query like the following, which is valid according to the Update grammar, is not possible with the actual implementation.

```
DELETE { 
  GRAPH ?g1 { 
    ?subject <http://my-example.com/anyIRI/> ?object .
    ?subject ?predicate <http://my-example.com/anyIRI/> . 
  } 
}
WHERE { 
  GRAPH ?g1 { 
    OPTIONAL { ?subject ?predicate <http://my-example.com/anyIRI/> . }
    OPTIONAL { ?subject <http://my-example.com/anyIRI/> ?object . } 
  } 
}
```

**Comment by 29kritika** [comment]
I, @anmolsinghal98 and @deepali17043 would like to work on this issue. Please suggest what needs to be done regarding this.

**Comment by jeenbroekstra** [comment]
Hi, great that you'd like to contribute! Please have a look at the [contributor guidelines](https://github.com/eclipse/rdf4j/blob/master/.github/CONTRIBUTING.md), in particular the points on how to sign the Eclipse ECA and what our code conventions are. Let me know if you need any help with any of it.

**Comment by 29kritika** [comment]
We have made a pull request adding some tests for the query given in the issue. We have also put a test assertion (assertEquals) to check that the resulting query string. Please suggest what needs to be done ahead.
