### ISSUE TITLE
Add support for nested triples storage and querying with RDF* and SPARQL* 

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#1484]
See  http://blog.liu.se/olafhartig/2019/01/10/position-statement-rdf-star-and-sparql-star/

RDF* is a proposal to extend RDF with "nested triples". 
SPARQL* is a proposal to extend SPARQL syntax with the ability to query such nested triples.

A basic form of support for this approach would involve a Rio parser that can read extended Turtle syntax and translate it to normal (reified / contextualized) RDF, as well as an extension to SPARQL that can use the extended syntax to query such reified structures.

Currently out of scope but possibly interesting for future work is to investigate lower-level support, e.g. at the level of the Java API (extending the Statement class to allow nested statements), or at the level of native storage extension to remove the need for verbose reification.

**Comment by hartig** [comment]
For inspiration for how RDF*/SPARQL* support may be implemented, you may take a look at: https://github.com/RDFstar/RDFstarTools

**Comment by hmottestad** [comment]
This is awesome. Property graphs are quite popular. Explaining to people that we can support it in the rdf world by using reification or graphs usually ends with someone asking why it’s so needlessly complex. 

I feel that performance is important if we implement something like this. It should be treated as a show stopper, eg. we won’t release it until fast enough to be as useful.

**Comment by pulquero** [comment]
For the impatient, it is possible to create a poor-man's version that somewhat resembles SPARQL*. I simply created a magic property (TupleFunction) ':id' that maps (s p o) to an IRI (bijection). You can then write queries like
`(:bob foaf:age 23) :id/ex:certainty 0.9 .`
which superficially looks like
`<<:bob foaf:age 23>> ex:certainty 0.9 .`
I also created an equivalent inverse property `?id <- :fromid (?s ?p ?o)` so
`:john :said/:fromid (:bob foaf:age 23) .`

Further, you can create the following TupleFunctions as well:
`?stmtId rdf:subject -> ?s`
`?stmtId rdf:predicate -> ?p`
`?stmtId rdf:object -> ?o`
