### ISSUE TITLE
Replace domain used in benchmark file

### ISSUE THREAD

**Issue by hmottestad** [eclipse/rdf4j#1493]
By request from the IP team at Eclipse we are replacing a dead domain in the DCAT file we sourced from the Belgium open data people with an example.org based domain. This old domain points to indecent materials.

**Comment by barthanssens** [comment]
Good catch, I'll notify the Flanders Region for good measure, it is indeed an old domain name that should not be used anymore in their publications / sites, but they might want to double check ...
