### ISSUE TITLE
Update project documentation and website

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#15]
The project documentation and website at http://rdf4j.org/ will need to be updated to reflect the changes from Sesame to RDF4J. In particular, we'll need:

- [x] remove logo
- [x] rename "(OpenRDF) Sesame" to "(Eclipse) RDF4J"
- [x] remove obsolete copyright notices
- [x] update documentation to use new package names, project names, etc.

**Comment by jeenbroekstra** [comment]
Instead of updating the current site, we will migrate to a new (Wordpress-based) site. I am currently prepping this.

**Comment by jeenbroekstra** [comment]
New WP site is up and running at http://new.rdf4j.org/ , but not yet publicly visible. If you want to help out authoring the content and migrating stuff from the old site, ping me and I'll provide you with a login.

**Comment by jeenbroekstra** [comment]
Site is mostly done. We'll keep the old site in the air on a different subdomain so we can link back to old Sesame documentation if needed. As soon as the subdomain config has been set up I'll activate the new site.

**Comment by jeenbroekstra** [comment]
@aschwarte10 @damyan-ognyanov @ansell , everyone else, can I get some eyeballs and feedback on the new website please? I've made the site publicly visible at http://new.rdf4j.org/ . Keen to hear any feedback you have, including mistakes, missing info, or anything else. 

As soon as I have an OK I'll reconfigure the DNS and we can go live.

**Comment by ansell** [comment]
I couldn't see any glaring mistakes on reading through it.

It may be useful to add a Maven POM and a Gradle dependency example to the download page which references the latest version, so it is a simple copy-paste to add the full RDF4J library to either Maven/Gradle as necessary, for those that do not want to pick and choose between the modules that they are sure they need.

Once a release happens, pointing to search.maven.org on the downloads page may be preferable to the Sonatype repository.

It may also be useful to delay the website until RDF4J-2.0-M1 is actually released, as not everyone will be aware of how to access the snapshots. Could add the details of how to get access to the sonatype snapshots repository on the download page if you want to advertise that as a method of people getting access to nightly builds, even if only until M1 is released.

**Comment by jeenbroekstra** [comment]
Good idea on the POM, I'll take a look at that. Of course, I do plan to point to Maven Central once release is done (the link to sonatype is purely for snapshot builds). 

As for waiting until 2.0-M1 is out: I'm trying to push things forward here, and make it clear in everybody's mind that Sesame is a closed chapter, and we're committed to RDF4J now. But perhaps you are right and we should do the M1 release at the same time as launching the new site. We're [about ready](https://github.com/eclipse/rdf4j/issues?q=is%3Aopen+is%3Aissue+milestone%3A%222.0M1+%28Java+8%29%22) to do the release anyway, so it will only be a few days one way or the other.

**Comment by jeenbroekstra** [comment]
We are waiting for a slight reconfiguration at the callimachus end (so that the old site can be reached at archive.rdf4j.org once we switch). Once that is done we can go live and publish the first milestone.

If there is a hiccup with the reconfig I'll go ahead with switching anyway - it just means that the old site will be (temporarily, until the config is sorted out) unavailable.
