### ISSUE TITLE
Archive rdf4j-tools

### ISSUE THREAD

**Issue by keilw** [eclipse/rdf4j#1513]
A former independent repository https://github.com/eclipse/rdf4j-tools says "this repository is now closed", can't it also be archived on GitHub?

**Comment by jeenbroekstra** [comment]
Yes, it can, but we're taking it one step at a time :) Same holds for rdf4j-storage btw

**Comment by jeenbroekstra** [comment]
One reason to temporarily keep these repos open is that makes it easier for us to run hotfix releases on previous versions. We will likely close once release 3.1 is out the door and we can confidently drop hotfix support for these older releases.

**Comment by jeenbroekstra** [comment]
Logged request with Eclipse maintainers to mark as archived: https://bugs.eclipse.org/bugs/show_bug.cgi?id=559899
