### ISSUE TITLE
SparqlBuilderUtils#getEnclosedString should not add PAD for empty contents

### ISSUE THREAD

**Issue by erikgb** [eclipse/rdf4j#1518]
There seems to be a bug in SparqlBuilderUtils#getEnclosedString. I am trying to create an empty string literal using the sparqlbuilder, but it seems impossible. The empty string ends up as a single space ' ' in the built query.

I think the problem is in the following line:
https://github.com/eclipse/rdf4j/blob/792f6b85e87b22a2cd654264fd9c02277ec77329/core/sparqlbuilder/src/main/java/org/eclipse/rdf4j/sparqlbuilder/util/SparqlBuilderUtils.java#L92

I think nothing should be appended to the StringBuilder (es) if contents is empty.

**Comment by jeenbroekstra** [comment]
Related: #1385

**Comment by jeenbroekstra** [comment]
@erikgb Can you tell me in more detail what exactly you're trying to do? How are you trying to create the empty literal?

**Comment by erikgb** [comment]
@jeenbroekstra Yes, I am trying to create the empty literal. Thanks for fixing this issue. 👍
