### ISSUE TITLE
N-Triples and Turtle writer produces non-compliant output for IRIs containing "

### ISSUE THREAD

**Issue by bennofs** [eclipse/rdf4j#1535]
When writing a triple with an IRI that contains a `"`, the Rio N-Triples writer produces an invalid triple like the following:

```
<https://example.org/subject> <https://example.org/predicate> <https://example.org/\"> .
```

This is not spec-compliant, because IRIs may only contain numeric escape sequences (https://www.w3.org/TR/n-triples/#h3_sec-iri) and `\"` is not a numeric escape sequence.

The Rio N-Triples parser actually validates that, so parsing the generated triple again produces an exception:

```
[main] WARN org.eclipse.rdf4j.rio.helpers.ParseErrorLogger - [Rio error] IRI includes string escapes: '\34' (1, -1)
```

<details>
<summary>Minimal example</summary>

```
import org.eclipse.rdf4j.model.impl.SimpleValueFactory;
import org.eclipse.rdf4j.rio.*;
import org.eclipse.rdf4j.model.*;
import java.io.*;

class Example {
    public static void main(String[] args) throws IOException {
        RDFWriter writer = Rio.createWriter(RDFFormat.NTRIPLES, System.out);
        final ValueFactory factory = SimpleValueFactory.getInstance();
        writer.startRDF();
        writer.handleStatement(SimpleValueFactory.getInstance().createStatement(
            factory.createIRI("https://example.org/subject"),
            factory.createIRI("https://example.org/predicate"),
            factory.createIRI("https://example.org/\"")
        ));
        writer.endRDF();
        // output: <https://example.org/subject> <https://example.org/predicate> <https://example.org/\">
        
        Rio.parse(
                new StringReader("<https://example.org/subject> <https://example.org/predicate> <https://example.org/\\\">"),
                "https://example.org",
                RDFFormat.NTRIPLES
        );
        // throws
        /*
        Exception in thread "main" org.eclipse.rdf4j.rio.RDFParseException: IRI includes string escapes: '\34' [line 1]
	    at org.eclipse.rdf4j.rio.helpers.RDFParserHelper.reportError(RDFParserHelper.java:322)
	    at org.eclipse.rdf4j.rio.helpers.AbstractRDFParser.reportError(AbstractRDFParser.java:684)
	    at org.eclipse.rdf4j.rio.ntriples.NTriplesParser.reportError(NTriplesParser.java:636)
	    at org.eclipse.rdf4j.rio.ntriples.NTriplesParser.parseUriRef(NTriplesParser.java:437)
	    at org.eclipse.rdf4j.rio.ntriples.NTriplesParser.parseObject(NTriplesParser.java:386)
	    at org.eclipse.rdf4j.rio.ntriples.NTriplesParser.parseTriple(NTriplesParser.java:290)
	    at org.eclipse.rdf4j.rio.ntriples.NTriplesParser.parse(NTriplesParser.java:177)
	    at org.eclipse.rdf4j.rio.Rio.parse(Rio.java:343)
	    at org.eclipse.rdf4j.rio.Rio.parse(Rio.java:254)
	    at Example.main(scratch_2.java:19)
         */
    }
}
```
</details>

**Comment by bennofs** [comment]
I just noticed that `"` is not allowed in URLs, according to https://tools.ietf.org/html/rfc3987#section-2.1 and https://tools.ietf.org/html/rfc3986#section-3.3, so perhaps this is not a bug in Rio?

**Comment by jeenbroekstra** [comment]
Thanks for reporting this, and for the clear sample code demonstrating the problem! 

I do think this is a bug in Rio. The NTriplesWriter should be resilient against use of possible illegal characters in its input by properly escaping them. Here it should use the numeric sequence for non-permitted characters in IRIs, instead of a string escape sequence (which is only allowed in literal values).

**Comment by barthanssens** [comment]
Looks like  NTriplesUtil.toNTriplesString is the crulpit, it calls the same escape method for URIs as for Literals.

**Comment by barthanssens** [comment]
On a related note, the TurtleWriter fails to escape other non-compliant IRIs where NTripleWriter does a good job

E.g. `http://www.example.com/=°\"`  

TurtleWriter generates: `<http://www.example.com/=°\u0022>`
NTriples generates `<http://www.example.com/=\u00B0\">`

**Comment by barthanssens** [comment]
IMHO, the illegal characters in URIs should be percent-encoded instead of numeric-encoded (see https://tools.ietf.org/html/rfc3986#section-2.1)
