### ISSUE TITLE
Integrate FedX into rdf4j

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#1538]
Move fedx codebase into rdf4j as a module `org.eclipse.rdf4j.federated`, under `tools/`.

CQ: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=20667

**Comment by aschwarte10** [comment]
@jeenbroekstra in PR https://github.com/eclipse/rdf4j/pull/1622 I have succesfully tested to create a FedX federation in the RDF4J workbench. Currently however this is a bit cumbersome as the integration is not very tight (i.e. the federation binary is not bundled with the rdf4j-server war and moreover there does not exist a template).

In my manual test I basically added a binary jar to the server webapp, and created a federation repository in the file system. This example test was successful.

For the release and for our users I would however like to pursue a more tight integration, i.e. make the federation feature more out-of-box usable. What would be the steps from your perspective to make the federation available also in the rdf4j-server webapp? Do you think we can aim for this in the release?

**Comment by jeenbroekstra** [comment]
Off the cuff I'd say that it's simply a matter of adding the dependency to the rdf4j-server's pom. Now that I think about it, we'll probably also need to add it to the bill of materials and to the rdf4j-runtime pom. I think we should deifnitely try and include that in the next release (we have some time anyway, at least another 4-6weeks before we can do a release as we'll need to finalize legal review for FedX as well as go through our own release review).

**Comment by jeenbroekstra** [comment]
CQ has been approved! :tada:
