### ISSUE TITLE
Merge/remove fedx nativestore extensions

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#1553]
Investigate if the fedx nativestore extensions are generally relevant and applicable, and if so, merge with the core native store implementation.

**Comment by aschwarte10** [comment]
I had a look at the code and the extensions / overrides and it looks that they are no longer required. In 3.0 the optimizer configuration has been moved to the evaluation strategy and I think with this API enhancement I no longer require the extensions.

Will do a final evaluation and possibly the implementation for this.

**Comment by aschwarte10** [comment]
PR with the relevant changes have been merged
