### ISSUE TITLE
deprecate federationsail in favor of fedx

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#1554]
Investigate if the existing federation sail can be made obsolete/deprecated or even immediately replaced by the fedx sail implementation.

**Comment by jeenbroekstra** [comment]
@aschwarte10 what's your opinion on this? The way I currently see it we should start marking the federation sail as deprecated now. Completely removing it won't happen until the next major release at the earliest of course.

**Comment by aschwarte10** [comment]
In my opinion it makes sense to start deprecating the federation SAIL. Particularly, we are starting to remove some support already (e.g. the federation create support in the workbench) and we have a good successor in place. I think migration for users should be pretty much OK, we could write a small guide with an example of the repository configuration.
