### ISSUE TITLE
Documentation for FedX

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#1555]
Documentation should be included as part of the wider rdf4j documentation.

**Comment by aschwarte10** [comment]
@jeenbroekstra can you point me to some developer help for this issue? I.e where an how can I create the documentation, haven't done this before

**Comment by jeenbroekstra** [comment]
Ah I just posted about this on the developer list.

**Comment by aschwarte10** [comment]
PR for the main documentation available in https://github.com/eclipse/rdf4j-doc/pull/118

Note: in addition to the above (which is the documentation for using the federation), I am planning to provide more documentation on the usage of FedX within the RDF4J workbench
