### ISSUE TITLE
SHACL - race condition with jdk11 when using multiple threads to access a shacl sail

### ISSUE THREAD

**Issue by hmottestad** [eclipse/rdf4j#1557]
With reference to the email from Bart there is a failing test that tests for race conditions.

org.eclipse.rdf4j.sail.shacl.MultithreadedTest#testDataAndShapes

We should try to figure out 
 - if this is only an issue when using parallel shacl validation?
 - if this is an issue with the shacl sail, with one of the added/removed repos or with the base sail

And also try to make it more reproducable!

**Comment by hmottestad** [comment]
This seems to be happening against the base sail. So it makes sense that it only happens when using parallel validation (since this shares a single connection from the base sail between multiple threads).

**Comment by hmottestad** [comment]
It doesn't seem to happen with `IsolationLevels.NONE`.

**Comment by hmottestad** [comment]
Next step is to try to figure out where the read locks are being taken.

**Comment by hmottestad** [comment]
Also, even after 8 hours the test still hangs!

**Comment by barthanssens** [comment]
Well, I guess it will hang forever: a back-off mechanism is being used, each time doubling the interval between  attempts ...

**Comment by hmottestad** [comment]
this seems like it might be caused by my read/write lock stuff directly in the shacl sail

**Comment by hmottestad** [comment]
It's definitively in the shacl code. Looks like there is some code that isn't releasing a read lock.....but I can't figure out where. I might instead end up switching to the lock manger instead.

**Comment by hmottestad** [comment]
<img width="1517" alt="Screenshot 2019-09-26 at 18 22 41" src="https://user-images.githubusercontent.com/797185/65706376-a4698c00-e08a-11e9-9daf-0234c976f9ca.png">

**Comment by hmottestad** [comment]
This seems very odd. All the work threads from the common pool have single stacks except for this thread here that has two stacks.

**Comment by hmottestad** [comment]
The top stack [2] is waiting for a lock that the bottom stack has acquired. I have never seen anything like this before!

**Comment by barthanssens** [comment]
Related to #1148

**Comment by hmottestad** [comment]
Maybe we should go ahead and deactivate parallel validation while I get this sorted. 

I have tried switching from stamped locks to the RDF4J common locks. It still hangs. 

Next is to use a custom thread pool. Maybe for the test rather than for the actuall validation.
