### ISSUE TITLE
Failing parsing wikidata ttl dump file

### ISSUE THREAD

**Issue by D063520** [eclipse/rdf4j#1566]
I'm trying to parse the current Wikidata dump and I get:

Unexpected character U+23 at index 102:
http://www.univ-paris3.fr/adminsite/webservices/export_rss.jsp?NOMBRE=10&CODE_RUBRIQUE=&LANGUE=0#KLINK#KLINK [line 10093827]

Can you tell me if this is an rdf4j bug or a Wikidata problem? In the second case I would report to the community ....

Maybe related to issue #1017

**Comment by barthanssens** [comment]
Looks like a wikidata issue, since there are two '#' 

The RFC (https://tools.ietf.org/html/rfc3986) appendix A mentions that a fragment (the part after the #) cannot contain another '#' (unless it is encoded like %23)

**Comment by D063520** [comment]
ok, I will report this to the community ....

**Comment by barthanssens** [comment]
If you want to parse it, even with errors, you can disable verification by setting the Rio parser setting to false

See https://rdf4j.eclipse.org/javadoc/latest/org/eclipse/rdf4j/rio/helpers/BasicParserSettings.html#VERIFY_URI_SYNTAX

**Comment by D063520** [comment]
I will try this. Thank you very much!
