### ISSUE TITLE
Nativestore, new context cache without Exception

### ISSUE THREAD

**Issue by barthanssens** [eclipse/rdf4j#1578]
See also https://www.eclipse.org/lists/rdf4j-dev/msg01242.html

When a new native store is created, the context cache file does not exist, so this files gets created. 
Unfortunately there is also an Exception being thrown, because there is currently no distinction between creating a cache for a new store, and recreating an invalid/corrupt cache.

It would be nicer to just log this, instead of throwing / propagating an Exception.

**Comment by jeenbroekstra** [comment]
This thing is driving me nuts in running tests on master. I'm gonna have a quick look at backporting your fix to the master branch.
