### ISSUE TITLE
Vocabularies: add DCAT2 constants

### ISSUE THREAD

**Issue by barthanssens** [eclipse/rdf4j#1580]
A new version of DCAT (v2) became available, so it would be helpful to add new properties and classes to the org.eclipse.rdf4j.model.vocabulary.DCAT convenience class

https://www.w3.org/TR/2019/CR-vocab-dcat-2-20191003/

This would also require a similar class for W3C ODRL, PROV and TIME vocabularies.
(which are also useful outside a DCAT-context)

**Comment by pwin** [comment]
https://github.com/pwin/dcat-v2-xml-schema is a preliminary draft that might also be useful

**Comment by barthanssens** [comment]
Thanks, I started generating the classes for DCAT and other (ODRL, PROV...) ontologies
