### ISSUE TITLE
Tuple Cardinality (Joins optimization)

### ISSUE THREAD

**Issue by AlyHdr** [eclipse/rdf4j#1588]
What is the logic behind the formulas on the cardinalities ? Is there any publications supporting those ? 
QueryJoinOptimizer.java (class)
getTupleCardinality (function line 342)

**Comment by hmottestad** [comment]
Can you give a link to the line?

**Comment by AlyHdr** [comment]
> Can you give a link to the line?

@hmottestad 
So there is this function "selectNextTupleExpr" that decides which tuple to be next queried in the expression and calculate the cardinality of this tuple using the function "getTupleExprCardinality", so I would like to know first if those cardinalities are accurate and what are the rules. Not to forget the fact that there is some values that are already calculated and put in the "cardinalityMap" for each tuple in the expression, where they appear to be constants for me.

https://github.com/eclipse/rdf4j/blob/931bf27f29e40a6eb496fcaf5e0cd82fc5386363/core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/QueryJoinOptimizer.java#L372
https://github.com/eclipse/rdf4j/blob/931bf27f29e40a6eb496fcaf5e0cd82fc5386363/core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/QueryJoinOptimizer.java#L396

**Comment by hmottestad** [comment]
Haven't looked at the code before. Only been working on RDF4J for the last 2-3 years.

Those cardinalities should be accurate. They are not any kind of stats based on the data in the store, but rather based on which variables have previously been joined (and are no bound). 

The same query should have the same cardinalities when run against the same data. When run against different data those cardinalities may be different if the stats make the initial join order different.

Are you experiencing issues with a query in particular?

**Comment by AlyHdr** [comment]
The thing is that we are working on a tool to optimize queries joins and we use rdf4j on top of it but we can get the exact cardinality of each tuple in our case, so the questions is do we need those calculations anymore ?? 
Because in the current implementation of rdf4j he considers constants for the cardinalities of the tuples for example if we have : ?s relation_1 object_1 
Then he assign a 100 for the variable and 1 for constants so the total of this tuple would be : 100 * 1 * 1.
And then this scenario mentioned before is applied to make coefficients with bounded and constant variables.

**Comment by hmottestad** [comment]
https://github.com/eclipse/rdf4j/blob/931bf27f29e40a6eb496fcaf5e0cd82fc5386363/core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/QueryJoinOptimizer.java#L112

There's that line there. So I must have wrong in my assumption that it's not based on stats. 

I guess if you don't provide any stats then it ends up ordering based on what constants you have. Not sure though.

Maybe you want to contact one of the authors directly.

```
/**
 * A query optimizer that re-orders nested Joins.
 * 
 * @author Arjohn Kampman
 * @author James Leigh
 */
```

I believe @jamesrdf is still around and maybe you can hire him to help you out?
