### ISSUE TITLE
Add templates for pull request opening

### ISSUE THREAD

**Issue by ansell** [eclipse/rdf4j#16]
GitHub released a new feature enabling a template to be created as the basis for new issues and pull requests. This is more visible than the guidelines for contributing as it is inserted into the comment for each pull request when it is opened, so may be useful to add support for.

https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by jeenbroekstra** [comment]
Sounds useful. I'm not immediately sure what precise info we should add to this though. Can you draft a proposal?

**Comment by jeenbroekstra** [comment]
Come to think of it, there's several things we can do: drop a hint to document the issue the PR is for, and include a check list that people can 'tick off', for example:

----

This PR addresses issue: # .

Changes proposed in this PR:
- 
- 
-

Make sure these boxes are ticked before submitting your PR:

- [ ] RDF4J code formatting applied
- [ ] tests included
- [ ] tests greenline
