### ISSUE TITLE
Maven warning/error

### ISSUE THREAD

**Issue by hmottestad** [eclipse/rdf4j#1600]
Getting an error about a dependency using a beta version of javax.el. Seems strange:

```
[INFO] ----------------< org.eclipse.rdf4j:rdf4j-http-server >-----------------
[INFO] Building RDF4J: HTTP server 3.0.1-SNAPSHOT                       [70/83]
[INFO] --------------------------------[ war ]---------------------------------
[WARNING] The POM for org.eclipse.m2e:lifecycle-mapping:jar:1.0.0 is missing, no dependency information available
[WARNING] Failed to retrieve plugin descriptor for org.eclipse.m2e:lifecycle-mapping:1.0.0: Plugin org.eclipse.m2e:lifecycle-mapping:1.0.0 or one of its dependencies could not be resolved: Failure to find org.eclipse.m2e:lifecycle-mapping:jar:1.0.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
[WARNING] The POM for org.glassfish:javax.el:jar:3.0.1-b06-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.glassfish:javax.el:jar:3.0.1-b07-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.glassfish:javax.el:jar:3.0.1-b08-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.glassfish:javax.el:jar:3.0.1-b11-SNAPSHOT is missing, no dependency information available
[INFO] 
```

I also don't know what org.eclipse.m2e:lifecycle-mapping is or if it is related to the javax.el issue.

**Comment by barthanssens** [comment]
Which maven version (and Java VM) are you using ?

**Comment by hmottestad** [comment]
```
$ mvn -v
Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-04T21:00:29+02:00)
Maven home: /usr/local/Cellar/maven/3.6.1/libexec
Java version: 1.8.0_144, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.6", arch: "x86_64", family: "mac"
```

**Comment by hmottestad** [comment]
I ran: `mvn dependency:tree`

**Comment by hmottestad** [comment]
I keep getting the same error about the javax.el deps in intellij.

**Comment by barthanssens** [comment]
Hmz, indeed, same warning with maven 3.6.2 and 1.8.0u232 64-bit x86 Debian
Building does seem to work just fine though...

**Comment by jeenbroekstra** [comment]
I've seen the same error. It doesn't influence the build, but it is annoying. I vaguely remember needing this in an older version of Eclipse, when using Eclipse maven support. It might be superfluous now. I'll take a closer look.

**Comment by jeenbroekstra** [comment]
@hmottestad I completely overlooked that you were not just looking at a warning regarding the m2e plugin, but also some glassfish-related warnings. I've put up a PR that removes the m2e-lifecycle warning, but it doesn't address the glassfish issues.

**Comment by hmottestad** [comment]
Awesome!

I tried to trace back to where those glass fish dependencies were being imported. But couldn’t find out. We definitely shouldn’t have them, especially since our users might get the same errors. Anyone got any tips?
