### ISSUE TITLE
regex filter for Russian is case sensitive

### ISSUE THREAD

**Issue by yyz1989** [eclipse/rdf4j#161]
Hi all,

I discovered that when matching Russian strings with regex filter in a SPARQL query, the case is still sensitive when you add case insensitive flag. For example, the query

ask {filter (regex("Валовой", "валовой", "i")) }

will return false. The version of Sesame is 2.8.9. Can someone help me to have a look? Thanks a lot for your efforts in advance.

Regards,
Yang

**Comment by jeenbroekstra** [comment]
The behavior as-is is actually correct, as by default case-insensitive matching is only defined against US-ASCII. However, XPath (on which SPARQL regex matching is based) does allow case-insensitive matching on non-ASCII to happen, when the 'u' flag is specified. However, our parser does not support this, which is a bug. Generally speaking the SPARQL parser should have better support for the various XPath flag arguments, as described here: https://www.w3.org/TR/xpath-functions/#flags

In this particular case, the query should be 

`ask {filter (regex("Валовой", "валовой", "iu")) }`

which should return true.

**Comment by jeenbroekstra** [comment]
I need to have a closer look at what the spec says here. It's not quite clear what expected behavior is on non US-ASCII chars when matching case-insensitive. Stay tuned.

**Comment by jeenbroekstra** [comment]
Relevant section in XPath definiton of fn:matches (on which the SPARQL REGEX is based): https://www.w3.org/TR/xpath-functions/#flags 

Looks as if case-insensitive matching in XPath is defined on the basis of Unicode codepoint collocation and not merely on US-ASCII case matching (which is the case in Java). 

The fix is fairly trivial. I'll put something up.

**Comment by yyz1989** [comment]
Hi Jeen,

Thanks a lot for your support. Is it also planned for a future bugfix release for Sesame 2?

Regards,
Yang

**Comment by jeenbroekstra** [comment]
I'm afraid not - there are no further Sesame releases planned. However we're working hard on getting RDF4J stable as quickly as possible.

**Comment by jeenbroekstra** [comment]
We are bringing out the first milestone build for RDF4J 1.0 tomorrow, which is a backport to Java 7. It is specifically intended for projects that can not yet upgrade to Java 8. 
You can see an overview of the planned releases and milestones on our [Eclipse project page](https://projects.eclipse.org/projects/technology.rdf4j). Both RDF4J 1.0 and 2.0 are tentatively planned for mid-July, but we plan to bring out several milestone builds in the mean time, which are intended to be stable.

**Comment by yyz1989** [comment]
Hi Jeen, thanks a lot for the pointers, that's very helpful to me!
