### ISSUE TITLE
rdf4j-runtime packaging is too low level in 3.0.1 compared to 3.0.0

### ISSUE THREAD

**Issue by hmottestad** [eclipse/rdf4j#1611]
Look at the difference for the compile dependencies between 3.0.0 and 3.0.1.

## 3.0.1:
https://mvnrepository.com/artifact/org.eclipse.rdf4j/rdf4j-runtime/3.0.1
<img width="536" alt="Screenshot 2019-10-14 at 12 51 23" src="https://user-images.githubusercontent.com/797185/66746144-54a80480-ee81-11e9-9088-54a77702ab91.png">

## 3.0.0:
https://mvnrepository.com/artifact/org.eclipse.rdf4j/rdf4j-runtime/3.0.0
<img width="600" alt="Screenshot 2019-10-14 at 12 51 55" src="https://user-images.githubusercontent.com/797185/66746166-68536b00-ee81-11e9-9de5-977fa2be3ec0.png">

Looks like the way that 3.0.1 is creating a fat jar is very different from 3.0.0. 3.0.0 seems to just depend on a bunch of other modules, while 3.0.1 is just including all the code from those modules directly.

This makes a big difference for end users because the rdf4j-runtime could previously be used with a bunch of exclusions for things like spin and lucene modules if the user didn't want these (usually because they cause conflicts). Now the rdf4j-runtime can pretty much only be used if you are willing to include everything.

**Comment by hmottestad** [comment]
@jeenbroekstra any chance you know how to convert back to how the runtime module was built for 3.0.0?

**Comment by jeenbroekstra** [comment]
I'm having a look. It's surprising to me that rdf4j-runtime is producing a fat jar at all. I may goofed when merging the various pom configurations as part of the repo merge.

**Comment by hmottestad** [comment]
https://mvnrepository.com/artifact/org.eclipse.rdf4j/rdf4j-runtime/3.0.2

Your fix worked @jeenbroekstra
