### ISSUE TITLE
Vulnerabilities identified by reshift

### ISSUE THREAD

**Issue by hmottestad** [eclipse/rdf4j#1614]
https://reshift.softwaresecured.com/community/rdf4j-rio-api-3.0.0-M1/index.html
https://reshift.softwaresecured.com/community/rdf4j-client-3.0.0-M1/index.html

**Comment by barthanssens** [comment]
Got a similar report on the client. Could be worthwhile to include a security scanner / code analysis tool in the tool chain (be it reshift, coverity or some other tool...),

**Comment by barthanssens** [comment]
The issue on using MD5 digest in AbstractRDFParser.java seems like a false positive (i.e. MD5 is indeed used, but apparently to generate fixed-length IDs from nodes, not for security)

**Comment by hmottestad** [comment]
https://github.com/eclipse/rdf4j/blob/d2a301dabcf9c051b019e3434327c15c29fc321e/core/rio/api/src/main/java/org/eclipse/rdf4j/rio/Rio.java#L550

**Comment by hmottestad** [comment]
Seems like these are all false positives.

**Comment by hmottestad** [comment]
Didn't see the one from the client that you added. Should probably sample that and check if any of them are true, if 5 random selections are false then I reckon we can scrap the entire thing and just ignore them all.

**Comment by jeenbroekstra** [comment]
Harrumph. Looks like that site doesn't play nice with Firefox. I can't see the details of the reports. I'll download Chrome again :(
