### ISSUE TITLE
Allows to compare literals with different date/time datatypes in SPARQL

### ISSUE THREAD

**Issue by Tpt** [eclipse/rdf4j#163]
It is not possible to compare literals with different date/time datatypes in SPARQL, e.g. "2005"^^xsd:gYear and "2015-01"^^xsd:gYearMonth.

A solution is to consider these literals as if they where xsd:dateTime and use xsd:dateTime comparison. So, for example, we would have "2005"^^xsd:gYear < "2015-01"^^xsd:gYearMonth = "true"^^xsd:boolean

SPARQL 1.1 specification does not talk about other date/time datatypes than xsd:dateTime so it would be compatible with the specification.

The comparison when a date/time is a prefix of an other like, "2005"^^xsd:gYear and "2005-01"^^xsd:gYearMonth, should be undefined.

**Comment by jeenbroekstra** [comment]
Looks sensible, but I'll need to have a quick look at the spec again to be absolutely sure - there's things that trip one up in the SPARQL spec when it comes to datatypes :)

**Comment by Tpt** [comment]
We should probably also have "2005"^^xsd:gYear != "2005-01"^^xsd:gYearMonth = "true"^^xsd:boolean and  "2005"^^xsd:gYear = "2005-01"^^xsd:gYearMonth = "false"^^xsd:boolean . The undefined behaviour is just for the <, >, <= and >= operators.

**Comment by jeenbroekstra** [comment]
You can extend the behavior of <, >, <= and >= (because they currently return a type error when you use an unknown datatype),  but for = and !=  you have to be a little bit careful. The [definition of RDFTerm-equal in the SPARQL spec](https://www.w3.org/TR/sparql11-query/#func-RDFterm-equal) is _incredibly_ convoluted. But from memory and from what I can see in the spec your proposal is sound, so go ahead and put it up for testing.

**Comment by ansell** [comment]
Personally I wouldn't expect 2005-01^^xsd:year to be automatically ordered before 2005^^xsd:year. In some ordering schemes the less specific cases may need to be ordered before the more specific cases.

Adding this behaviour would best be done with a flag that enables comparisons of different date types with the proprietary algorithm that this would implement, if it isn't already allowed for in the SPARQL-1.1 spec.

**Comment by jeenbroekstra** [comment]
I agree. More generally I think there should a be config option to run queries in 'strict' mode or 'extended' mode. See #164
