### ISSUE TITLE
Remove last.japicmp.compare.version

### ISSUE THREAD

**Issue by hmottestad** [eclipse/rdf4j#1636]
`<last.japicmp.compare.version>2.0</last.japicmp.compare.version>`
to 
`<last.japicmp.compare.version>3.0</last.japicmp.compare.version>`

In develop

**Comment by jeenbroekstra** [comment]
Good call. 

For what it's worth I think we should re-evaluate the use of this tool as well.

**Comment by hmottestad** [comment]
I propose we remove it. We usually have a pretty decent understanding of which changes are not backwards compatible.
