### ISSUE TITLE
SPARQL engine/repository configuration to run in 'strict' or 'extended' mode

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#164]
The SPARQL specification is extensible in nature. In particular, the behavior of boolean operators on datatyped literals is extensible: while the default specification has no support for all but a limited subset of XSD datatypes, implementors are free to extend behavior to include boolean comparison support - at least for those cases where in the strict minimal interpretation the comparison results in error.

There are several useful extensions that we can add, but some of these may trip up existing users that rely on the 'strict' behavior of the engine. To facilitate this, we should introduce a configuration option that sets the SPARQL engine to run in either 'strict' mode or in 'extended' mode.

**Comment by jeenbroekstra** [comment]
I'm thinking about the design of this. We could do this on a per-query basis, or make it a simple extension to the Repository API (a basic setter method and in addition make it part of the config template so it can be configured when creating a repo from the Workbench/Console). Thoughts?

**Comment by pulquero** [comment]
I think it should probably be a bit more generic than this else you could end up with a config zoo. To my mind this is all about being able to configure evaluation strategy being used. You should be able to set the class name/instance of the evaluation strategy supplier you want to use at the sail level. In workbench it is then a similar type option as async threshold or persist. The repo api seems the wrong place, how would it work for something like a sparqlrepo?

**Comment by pulquero** [comment]
I've sketched out an impl @ https://github.com/pulquero/rdf4j/tree/issues/%23164-config-evalstrat

**Comment by jeenbroekstra** [comment]
Basic mechanism now merged in. I'm keeping this open to track progress on actually making an extended evaluation strategy available as a config choice. Will do some work on that today.
