### ISSUE TITLE
Automated code quality check

### ISSUE THREAD

**Issue by barthanssens** [eclipse/rdf4j#1643]
Run Netbeans Inspect and Transform on the code base (unused imports, try-with-resources, possible issues ...)

Somewhat related to #790

- [x] unused imports
- [x] try-with-resources
- [x] diamond inference
- [x] @Override annotation
- [x] multi catch instead of repeating catch blocks
- [x] isEmpty() instead of size() == 0
- [x] isEmpty() instead of equals("")
- [x] lambda expression instead of anonymous class
- [x] auto (un)boxing

**Comment by hmottestad** [comment]
For try-with-resource you should check if this case shows up:

<img width="1493" alt="Screenshot 2019-10-30 at 11 05 17" src="https://user-images.githubusercontent.com/797185/67848580-3d197e80-fb05-11e9-9611-ed27d7399ede.png">

This is a false positive and should not be refactored.

**Comment by hmottestad** [comment]
@barthanssens  I hope you don't mind. After checking for try-with-resource with the intellij inspection I ended up fixing a couple of them.

**Comment by hmottestad** [comment]
`isEmpty() instead of size() == 0` will probably lead to some performance improvements ;)

**Comment by barthanssens** [comment]
Not at all :-) Most of the try-with-resources were fixed in a previous run
 
Most issues Netbeans I/T noticed are suggestions to use diamond inference, and using multi catch instead of multiple catch blocks repeating the same code

And a list of suggestions to make fields final
