### ISSUE TITLE
SHACL - testComplexPath fails on Windows

### ISSUE THREAD

**Issue by barthanssens** [eclipse/rdf4j#1649]
UnknownShapesTest.testComplexPath fails on MS-Windows 10 with OpenJDK 8, probably caused by different line endings when comparing log with set of expected strings.

**Comment by hmottestad** [comment]
Can you test if something like this works @barthanssens 

```
content = content.replaceAll("\\r\\n?", "\n")
```

**Comment by barthanssens** [comment]
I've fixed it in a slightly different way, though the result is of course the same
