### ISSUE TITLE
load large data set problem

### ISSUE THREAD

**Issue by ho9science** [eclipse/rdf4j#1650]
I have 10GB ttl dataset
it works on the server 
but it is very slow and become jammed in workbench 

>Repository Size
Number of Statements	Timed out while requesting repository size.
Number of Labeled Contexts	Timed out while requesting labeled contexts.

what can i do load large dataset?

**Comment by hmottestad** [comment]
Which version of RDF4J are you using. There were a number of fixes in 3.0 for things like getting the repository size  and bulkloading.

**Comment by hmottestad** [comment]
@ho9science we need more info to reproduce your issue. As well as the version number we need some more details for how you are loading the data, what transaction isolation level you are using, and if possible a test file.

**Comment by ho9science** [comment]
thank you for your comment. I was using old version.
now I am getting 3.0.2 and test it.
how was loading the data is using RepositoryConnection add method.
transaction isolation level is none.
sorry about cannot share test file.
However, it is one 10GB triple format data file.

**Comment by ho9science** [comment]
> try( RepositoryConnection con = repo.getConnection();)
     con.add(file, BASE_URI, RDFFormat.TURTLE, new Resource[0]);
}
I trying to add triple to repository like a example.
I tried to Xmx20G java heap size. but occur out of memory exception.

How can I use bulkloading? Do I try third party database?

**Comment by barthanssens** [comment]
It also depends on the store: the RDF4J MemoryStore is only designed for smaller datasets (say, 100 000 triples), the NativeStore should be able to handle 100 million triples.

Another option would perhaps be https://github.com/Merck/Halyard, which uses RDF4J with Apache HBase as storage, though that solution probably only shines on a cluster of machines...

**Comment by hmottestad** [comment]
@barthanssens I believe @ho9science is using the RDF4J server with NativeStore and a remote repository connection from java to add the file. 

@ho9science We can try to look into to see if using the RDF4J server with a remote repo is considerably slower than using the NativeStore directly. It would be very helpful if you could create a working code sample in a new github repo so we can see exactly how your code works.

Which process did you give 20GB of memory too? The rdf4j server or your java code? And which is running out of memory?

Can you tell us how many statements (triples) are in your file? Also, have you tried loading N-triples instead og Turtle?

You can also try to start a transaction directly with `con.begin(IsolationLevels.NONE)` and finally `con.commit()`.

And as a side note, we are all volunteering our spare time for the sheer joy of tinkering with some semantic tech....no one is paying us for our time.

**Comment by ho9science** [comment]
Thank you for your help, I really appreciate it.

I'm using NativeStore and connected to NativeStore directly from path.

I give 20GB memory to java code. 

My triple file is more than 100million triples.

Once again, really appreciate your comment.

**Comment by hmottestad** [comment]
So you are not using the RDF4J Server or Workbench?

**Comment by ho9science** [comment]
I'm using RDF4J server. not custom, only deploy on apache-tomcat-9.0
I have created java code (shell script) to load data for Repository Connection when I shut down tomcat.

**Comment by ho9science** [comment]
Finally, it works on. Maybe I was mistaken by wrong code.
In 3.0.2, no jammed, not slow. thank you very much.
