### ISSUE TITLE
Elasticsearch backed sail store

### ISSUE THREAD

**Issue by hmottestad** [eclipse/rdf4j#1662]
Create a sail store that stores and queries triples in Elasticsearch 6.x.

Consider
 - Bulkloading
 - optimizing for "hasStatement"
 - consider using cursor
 - considering caching the transaction in a local memorystore
 - consider caching in general for read operations
 - target higher performance for read operations rather than writes
 - this is meant for storing small datasets where transaction support is not needed, like storing reference data used in consortion with your current use of elasticsearch

Use the following for testing:

```xml
        <dependency>
            <groupId>pl.allegro.tech</groupId>
            <artifactId>embedded-elasticsearch</artifactId>
            <version>2.10.0</version>
            <scope>test</scope>
        </dependency>
```

```java
        private static EmbeddedElastic embeddedElastic;

	private static File installLocation = Files.newTemporaryFolder();


	@BeforeClass
	public static void beforeClass() throws IOException, InterruptedException {


		String version = "6.8.3";

		embeddedElastic = EmbeddedElastic.builder()
			.withElasticVersion(version)
			.withSetting(PopularProperties.TRANSPORT_TCP_PORT, 9350)
			.withSetting(PopularProperties.CLUSTER_NAME, "cluster")
			.withInstallationDirectory(installLocation)
			.withDownloadDirectory(new File("tempDownloads"))
//			.withPlugin("analysis-stempel")
//			.withIndex("cars", IndexSettings.builder()
//				.withType("car", getSystemResourceAsStream("car-mapping.json"))
//				.build())
//			.withIndex("books", IndexSettings.builder()
//				.withType(PAPER_BOOK_INDEX_TYPE, getSystemResourceAsStream("paper-book-mapping.json"))
//				.withType("audio_book", getSystemResourceAsStream("audio-book-mapping.json"))
//				.withSettings(getSystemResourceAsStream("elastic-settings.json"))
//				.build())
			.withStartTimeout(5, TimeUnit.MINUTES)
			.build();


		embeddedElastic.start();
	}
```

**Comment by hmottestad** [comment]
We can now add triples and query for them. Next will be support for blank nodes and for values. After than maybe bulk loading. Scroll for getting statements and removal of statements.

**Comment by barthanssens** [comment]
So you're using ES 6.8.x ?
That's a good thing IMHO, though it will require another round of CQs in IPZilla.

**Comment by hmottestad** [comment]
I believe I switched back to the one we already using. The code above was initially copied from another project I have.
