### ISSUE TITLE
The artifact rdf4j-runtime-osgi.jar is almost empty

### ISSUE THREAD

**Issue by manuelfiorelli** [eclipse/rdf4j#1674]
The artifact `rdf4j-runtime-osgi.jar` is almost empty: it doesn't contain most classes from RDF4J.

I noticed this issue in version 3.0.2, while version 3.0.0 seems fine.

**Comment by hmottestad** [comment]
Did you try setting <type>pom</type>?

**Comment by manuelfiorelli** [comment]
Unfortunately this issue is different from the one that we have already discussed on the ML:
https://groups.google.com/d/msg/rdf4j-users/eER3QQwoPOw/HpcYfadYAgAJ

Let me explain.

The issue on the ML concerns the project `rdf4j-runtime`, which is no longer available as a JAR artifact. This problem affects dependency management by Maven (which I use to build my projects).

This issue concerns the project `rdf4j-runtime-osgi` that should build an OSGi bundle containing all classes and resources corresponding to RDF4J's runtime: you can think of this bundle as a sort of fat JAR aggregating all RDF4J's jars (without the dependencies) plus some metadata (in `MANIFEST.MF`) of interest for an OSGi framework. I use this bundle when deploying my OSGi-based applications that use RDF4J.

I think that some change in the build process of  `rdf4j-runtime-osgi` has erroneously excluded most classes and resources from the aggregate.

**Comment by jeenbroekstra** [comment]
Possibly related to #1611, though it's unclear to me why that should happen (there is no obvious direct dependency between rdf4j-runtime-osgi and rdf4j-runtime).

**Comment by manuelfiorelli** [comment]
I was surprised to see that the pom of `rdf4-runtime-osgi` didn't change significantly between versions `3.0.0` and `3.0.1`. The latter seem almost empty, but at a closer inspection it seems to me that it just contains the classes of `rdf4j-http-server-spring`, which is the sole explicit dependency of the project.
Looking at the pom of `rdf4j-http-server-spring`, I noticed that a potentially relevant change.
In version 3.0.0
```
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>rdf4j-client</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>rdf4j-storage</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>rdf4j-config</artifactId>
			<version>${project.version}</version>
		</dependency>
```

In version 3.0.1
```
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>rdf4j-client</artifactId>
			<version>${project.version}</version>
                        <type>pom</type>
		</dependency>
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>rdf4j-storage</artifactId>
			<version>${project.version}</version>
                        <type>pom</type>
		</dependency>
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>rdf4j-config</artifactId>
			<version>${project.version}</version>
		</dependency>
```

Could it be that both `rdf4j-client` and `rdf4j-storage` were both JARs previously?
I think that the fact that these two dependencies are of type `pom` is relevant, because in the pom of `rdf4j-runtime-osgi` there is this line of configuration:
```
						<Embed-Dependency>
							*;
							groupId=org.eclipse.rdf4j;
							scope=compile|runtime;
							type=!pom;
							inline=true
						</Embed-Dependency>
```
I've still to check the precise meaning of this configuration, but perhaps it could be responsible for ignoring the pom-types dependencies.

**Comment by jeenbroekstra** [comment]
That is indeed the case, they were both fat jars previously. We changed it without announcing because they've never been publicly advertised, so we only use them internally. But I hadn't realised the OSGi module depended on them. Good find!

**Comment by manuelfiorelli** [comment]
It seems that I was able to "solve" this issue by updating the `maven-bundle-plugin` to version 4.2.1.
I couldn't find an explicit specification but I found empirically that when an artifact is excluded for embedding (i.e. `rdf4j-storage`), its dependencies are excluded as well by the current version of the plugin while version 4.2.1 continues to process them (which is the behavior we desire).
As an alternative, I tried to remove the filter on the type, but the current version of the plugin fails since it consider any inlined dependency (included those of type pom) as JARs.
If this solution seems ok to you, I cloud make a PR in the next days (once I figured out how to sign the CLA).

**Comment by jeenbroekstra** [comment]
I'm a little hesitant about relying on an (apparently) undocumented feature of a specific version of the plugin, but as a workaround short term fix this might be useful, so please do submit a PR!

If you have some time and availability though, we could really use some help with a more robust OSGi setup. None of the RDF4J core committers actively use OSGi, so none of us are very familiar with it. If there are ways we can make this easier and you have time to provide some pointers, I'd really appreciate it.
 
Regarding signing the contributor agreement, please have a look at the [contributor guidelines](https://github.com/eclipse/rdf4j/blob/master/.github/CONTRIBUTING.md), which gives the steps required and links to get going - it should only take you about 5-10 minutes to get it done.

**Comment by manuelfiorelli** [comment]
Hi, Jeen I'm sorry for the late reply.
I've just signed the CLA and I'm going to recheck my work and submit a PR in a few days.

Regarding the current OSGi setup, I think that it satisfies the requirements of the projects I work on. While I routinely work with OSGi, I don't feel an expert on that matter. Moreover, I've still to learn how OSGi and Java Platform Module System (JPMS) fit together.

**Comment by jeenbroekstra** [comment]
That'd be excellent! If you can get the PR done before Saturday, we can include it in the 3.0.3 release.

**Comment by manuelfiorelli** [comment]
Unfortunately, I was unable to meet the deadline for the 3.0.3. While I'm quite busy, I'll try to do my best to submit the PR by the next few days.
