### ISSUE TITLE
Use jdk11 for the Jenkins master/develop verification builds

### ISSUE THREAD

**Issue by hmottestad** [eclipse/rdf4j#1675]
This is to make sure we maintain compatibility with jdk11 after all the hard work of trying to support it. 

We can still use jdk8 for PR builds so we are sure that jdk8 still works.

**Comment by hmottestad** [comment]
Relates to #1148

**Comment by hmottestad** [comment]
@barthanssens

**Comment by barthanssens** [comment]
Also check if jenkins is using maven 3.6.x

**Comment by jeenbroekstra** [comment]
Our Jenkins instance currently doesn't have JDK 11 installed unfortunately, most recent is JDK 9. Not entirely sure about the maven version either.

I'll check if we can get this upgraded. There was also talk earlier about migrating Eclipse projects away from the old 'shared-resource' Jenkins instance we're on, to a setup on a Kubernetes cluster. It's possible that we can only bump these versions by migrating to that new setup. See https://wiki.eclipse.org/CBI#CI_Environment_.28Jenkins.29 for details.

**Comment by jeenbroekstra** [comment]
Our maven version is currently 3.6.0 according to this page: https://wiki.eclipse.org/Jenkins#Apache_Maven

**Comment by jeenbroekstra** [comment]
Logged a request to update our Jenkins instance: https://bugs.eclipse.org/bugs/show_bug.cgi?id=553127

**Comment by hmottestad** [comment]
We could start by bumping to jdk 9.

**Comment by barthanssens** [comment]
Not sure if  JDK 9 and 10 are worth the effort, since they aren't LTS releases (and already EOL ...)

- https://www.oracle.com/technetwork/java/java-se-support-roadmap.html
- https://access.redhat.com/articles/1299013

**Comment by hmottestad** [comment]
Wasn't thinking we use jdk9 for anything useful, just to use it to run the compliance tests on the master and develop branch. Most of the breaking changes are in jdk9, so if it builds on 9 it's likely to build on 11 too.

**Comment by jeenbroekstra** [comment]
Jdk 11 and maven 3.6 have been installed, so we can tweak Jenkins when we want.

**Comment by hmottestad** [comment]
Swapped to 11 on master verify now.

**Comment by hmottestad** [comment]
And on develop
