### ISSUE TITLE
3.0.x subClassOf inferences disappear - major bug ?

### ISSUE THREAD

**Issue by vujasm** [eclipse/rdf4j#1685]
Hi,
It seems there is a bug (v3.0.2, 3.0.1, 3.0.0) that somehow causes subClassOf inferences (inferred statements) to disappear . My config is Native + RDFS. 

Here are the steps that should help you to quickly replicate the issue and check it further.
 
1.
`INSERT data { graph <urn:test>   {<urn:A> <http://www.w3.org/2000/01/rdf-schema#subClassOf> <urn:B> .   <urn:B> <http://www.w3.org/2000/01/rdf-schema#subClassOf> <urn:C> .  <urn:C> <http://www.w3.org/2000/01/rdf-schema#subClassOf> <urn:D> .} }`

 2.   `SELECT * WHERE {?s <http://www.w3.org/2000/01/rdf-schema#subClassOf>  <urn:D>}`
Results with inferred statements:
<urn:A>
<urn:B>
<urn:D>
<urn:C>

3.  `DELETE data { graph <urn:test>  {<urn:A> <http://www.w3.org/2000/01/rdf-schema#subClassOf>  <urn:B>} }`

4. `SELECT * WHERE {?s <http://www.w3.org/2000/01/rdf-schema#subClassOf>  <urn:D>}`
Result (with  inferred statements true) is only <urn:C>. ??  It is expecting to get <urn:B>,  <urn:D>, <urn:C>. So there is some issue here.

Further,
5. I insert back what I just deleted (hoping inferred statements will get back)
 `INSERT data { graph <urn:test>  {<urn:A> <http://www.w3.org/2000/01/rdf-schema#subClassOf> <urn:B>} }`

6. `SELECT * WHERE {?s <http://www.w3.org/2000/01/rdf-schema#subClassOf>  <urn:D>}` , with  inferred statements true, again returns <urn:C> only, which is wrong.

7 I insert new triple with new resource urn:AA
`INSERT data { graph <urn:test>  {<urn:AA> <http://www.w3.org/2000/01/rdf-schema#subClassOf> <urn:B>} }`

and now `SELECT * WHERE {?s <http://www.w3.org/2000/01/rdf-schema#subClassOf>  <urn:D>}` , with  inferred statements true, gives back
<urn:A>
<urn:B>
<urn:D>
<urn:AA>
<urn:C>

Now run 
```
DELETE data { graph <urn:test> 
  {<urn:AA> <http://www.w3.org/2000/01/rdf-schema#subClassOf>  <urn:B>} }
```
then 
`SELECT * WHERE {?s <http://www.w3.org/2000/01/rdf-schema#subClassOf>  <urn:D>}` , with  inferred statements true, and you get  <urn:C> only, which is again wrong result.

Could you please check this urgently? In our project we use  taxonomic organization of concepts with subClassOf semantics/inference for information retrieval, so we cannot really have this situation where subClassOf inferences disappear as soon as DELETE or Clear/ DROP  is executed. By Clear/Drop we of course don't drop graphs where we keep taxonomies, but other graphs (data, instances)

I have checked this on v2.5.3 and it seems all fine on that version, but please double check.

Thanks a lot

**Comment by jeenbroekstra** [comment]
Reproduced and confirmed a bug. We'll look into it.

**Comment by jeenbroekstra** [comment]
Tested with native and memory stores, both exhibit same behavior.
