### ISSUE TITLE
Expressions.bnode().getQueryString() produces NullPointerException

### ISSUE THREAD

**Issue by RoKish** [eclipse/rdf4j#1687]
The issue is caused by the fact that `Expressions.bnode()` calls `Expressions#function(SparqlFunction, Operand...)` with `null` as an operand (`Expressions.function(BNODE, (Operand) null)`). Calling `getQueryString` will lead to calling `getQueryString` for all the operands and we get NPE since the operand is `null`.

I guess this can be fixed by removing the `null` argument from `Expressions.function(BNODE, (Operand) null)` call and setting `printBodyIfEmpty` to `true` for all `Function` objects.

I can create a MR, however I'm not sure where exactly I should put the unit test for the issue. The `sparql11spec` package contains only the examples from the specification and there's no example involving `BNODE()` function call in the spec. Should I create a separate class `ExpressionsTest` for the test case?

**Comment by jeenbroekstra** [comment]
Related issue: #1385

**Comment by jeenbroekstra** [comment]
@RoKish thanks for reporting this, and a Pull Request would be most welcome! 

The SparqlBuilder currently has poor unit test coverage, we're aware of this (see also #1385). Your help with making a start would be great. A new class `ExpressionsTest` in `src/test/java/org/eclipse/rdf4j/sparqlbuilder/constraints` sounds like a good approach.

Before you get started with your PR, please have a look at the [contributor guidelines](https://github.com/eclipse/rdf4j/blob/master/.github/CONTRIBUTING.md) if you haven't yet, in particular the points on how to sign the Eclipse ECA. Let me know if you need any help with any of it.

**Comment by jeenbroekstra** [comment]
Nice work, thanks @RoKish!
