### ISSUE TITLE
Upgrade JMH

### ISSUE THREAD

**Issue by hmottestad** [eclipse/rdf4j#1690]
Upgrade JMH to 1.19 (which is a known good version).

**Comment by hmottestad** [comment]
Doing 1.21 instead since we can piggy back.

**Comment by hmottestad** [comment]
Piggyback on 20517
Name: jmh-core version 1.21 (PB CQ20517)
Piggyback: CQ20517

**Comment by hmottestad** [comment]
Piggyback on 20518
Name: jmh-generator-annprocess version 1.21 (PB CQ20518)
Piggyback: CQ20518

**Comment by hmottestad** [comment]
http://dev.eclipse.org/ipzilla/show_bug.cgi?id=21182

http://dev.eclipse.org/ipzilla/show_bug.cgi?id=21181

**Comment by jeenbroekstra** [comment]
@hmottestad fwiw I just had a look at these two CQs and noticed that you said this dependency is distributed in a release as part of the test suite. I don't believe that that is actually the case (or if it is currently the case, it _shouldn't_ be). The intent is that these kinds of "Test and Build" dependencies are always "works-with" dependencies (which precisely means that they are _not_ distributed by us in our release, just used internally).

**Comment by jeenbroekstra** [comment]
Not a big deal, except that getting a works-with dependency approved takes a lot less time than a full dependency review (which is what probably needs to happen now). If you're happy to wait for the legal team to do their review, I suggest we leave it as-is.

**Comment by hmottestad** [comment]
I saw it was a dependency in the test-suite and saw that we publish this to maven central. Assumed that we are currently publishing with jmh. Didn’t try to verify though.
