### ISSUE TITLE
Could you add the xsd:dateTimeStamp datatype to the XMLSchema vocabulary?

### ISSUE THREAD

**Issue by tonicebrian** [eclipse/rdf4j#1729]
We are using the OWL Time ontology for defining time objects and we are heavy users of [time:inXSDDateTimeStamp](https://www.w3.org/TR/owl-time/#time:inXSDDateTimeStamp) that explicitly relays on [xsd:dateTimeStamp](https://www.w3.org/TR/xmlschema11-2/#dateTimeStamp) but this datatype doesn't appear in class ` org.eclipse.rdf4j.model.vocabulary.XMLSchema`. 

Is there something preventing to include that datatype in that file? I'm more than willing to provide a PR if some directions about where/how to place are provided.

**Comment by barthanssens** [comment]
Ah, presumably just an oversight when the class was updated from RDF 1.0 to RDF 1.1...
(and the reference in the javadoc should point to https://www.w3.org/TR/rdf11-concepts/#xsd-datatypes or https://www.w3.org/TR/rdf11-concepts/#xsd-datatypes) 

By the way, 3.1.0 will also include o.e.r.m.vocabulary.TIME (as part of #1580)

**Comment by barthanssens** [comment]
Might also have an impact on org.eclipse.rdf4j.model.datatypes.XMLDatatypeUtil
