### ISSUE TITLE
Questions about same Shacl shape could be added multiple times and about setUndefinedTargetValidatesAllSubjects

### ISSUE THREAD

**Issue by sava-savov-ontotext** [eclipse/rdf4j#1738]
**Description**

* Create a SHACL repository and select a logging option - Log executed validation plans

* Import a shape twice via SPARQL or Import :

prefix ex: <http://example.com/ns#> 
prefix sh: <http://www.w3.org/ns/shacl#> 
prefix xsd: <http://www.w3.org/2001/XMLSchema#> 
INSERT DATA
{
    GRAPH <http://rdf4j.org/schema/rdf4j#SHACLShapeGraph>
    {
        ex:PersonShape
            a sh:NodeShape  ;
            sh:targetClass ex:Person ;
            sh:property [
            sh:path ex:age ;
            sh:datatype xsd:integer ;
            ] .
    } 
}
* **Add some test data:**

prefix ex: <http://example.com/ns#> 
prefix sh: <http://www.w3.org/ns/shacl#> 
prefix xsd: <http://www.w3.org/2001/XMLSchema#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
INSERT DATA {
    ex:Alice
        rdf:type ex:Person ;
        ex:age 12 .
}

Notice that the executed validation plan is logged twice.

**Comment by hmottestad** [comment]
Hi @sava-savov-ontotext thanks for testing the ShaclSail. @jeenbroekstra mentioned you might be interested in getting Shacl support for GraphDB.

**Comment by hmottestad** [comment]
A bit off topic, I searched for SHACL on your website and found this little snippet:

> Unlike OWL, however, SHACL can be applied to validate data that is already available in the triplestore. In other words, it allows for inconsistent data to be loaded into the database.

FYI, the SHACL implementation in RDF4J works like a schema in an SQL database. You can not add invalid data. If you use SNAPSHOT or above for isolation it will provide you with SERIALIZABLE level validation with minimal overhead as well.

**Comment by hmottestad** [comment]
Does something like this work better?

`
prefix ex: http://example.com/ns#
prefix sh: http://www.w3.org/ns/shacl#
prefix xsd: http://www.w3.org/2001/XMLSchema#
INSERT DATA
{
GRAPH http://rdf4j.org/schema/rdf4j#SHACLShapeGraph
{
ex:PersonShape
a sh:NodeShape ;
sh:targetClass ex:Person ;
sh:property ex:personAge.

ex:personAge
sh:path ex:age ;
sh:datatype xsd:integer ;
] .
}
}

`

**Comment by sava-savov-ontotext** [comment]
Hello

Could you please explain to me what is the usage
of undefinedTargetValidatesAllSubjects property
and is it implemented, because I'm getting UnsupportedOperationException
when I try to use it.

Regards
Sava

**Comment by hmottestad** [comment]
From the docs:

> Implicit sh:targetClass is supported for nodes that are rdfs:Class and either of sh:PropertyShape or sh:NodeShape. Validation for all nodes, equivalent to owl:Thing in an environment with a reasoner, can be enabled by setting setUndefinedTargetValidatesAllSubjects(true).

Could you share your example code and shape if things are still unclear?

**Comment by hmottestad** [comment]
Btw. It’s not part of the SHACL spec in any way. Just something I found very useful in my previous couple of SHACL engine implementations.

**Comment by hmottestad** [comment]
A model in RDF4J is more like a Dataset in Jena. https://jena.apache.org/documentation/javadoc/arq/org/apache/jena/query/Dataset.html

**Comment by sava-savov-ontotext** [comment]
Hello,

Could you give me an example of the usage of the property, because it's
still unclear.

Regards,
Sava

**Comment by hmottestad** [comment]
@sava-savov-ontotext while trying to make an example for you I also got the same exception. I've logged a new issue for it: #1781

**Comment by hmottestad** [comment]
@sava-savov-ontotext I've fixed the issue and it will be part of either a 3.0.4 release or 3.1.0. Here is an example that uses the nightly build: https://github.com/hmottestad/setUndefinedTargetValidatesAllSubjects_example/blob/master/src/main/java/Main.java

It look slike its printing too many error messages. Minor issue though.

Can I ask what your interest in this feature is? Do you have a usecase for it?

**Comment by hmottestad** [comment]
Propose to close this soon.

**Comment by hmottestad** [comment]
3.0.4 is release
