### ISSUE TITLE
Strip away the context for a statement.

### ISSUE THREAD

**Issue by hmottestad** [eclipse/rdf4j#1739]
User submitted a usecase for being able to strip away the context for a statement

I propose the following:
 - `public static Model Models.extractContext(Model model, Resource context){...}`
    - extract all statements matching the context and strip away the context
 - `public static Statement SimpleValueFactory.asStatementWithoutContext(Statement statement){...}`
   - convert a statement with (or without) a context to a statement without a context
 - `public static CloseableIteration<Statement,...> QueryResults.stripContext(CloseableIteration<Statement, ...> iteration){...}`
   - create an iteration that strips away the context

**Comment by hmottestad** [comment]
@jeenbroekstra @barthanssens what do you guys think? I'm not in love with the method naming, but I like adding this option since it's not going to be the first time someone needs to strip away the context from some statements.

**Comment by barthanssens** [comment]
It certainly is a useful feature, I vaguely remember having to do something similar to clean up some stuff in an internal project.

Maybe allow multiple contexts to be stripped ? E.g. stripContext or `extractContext(Model m, Resource ctx...)`

**Comment by jeenbroekstra** [comment]
Very nice, thanks for this. 

I'd prefer to put the statement conversion method in the `Statements` util class rather than a factory. Have to have a think about method names but this covers the intended use case quite nicely I think.

Let's try and write some example user code that uses this, to see what it looks like and if we missed any gaps.

**Comment by jeenbroekstra** [comment]
Taking the example use case from the mailinglist, the original code was this:

`Model unionOfContexts = QueryResults.asModel(conn.getStatements(null, null, null, contextName1, contextName2)); `

with these new helper methods it could becomes something like this:

`Model unionOfContexts = QueryResults.asModel(QueryResults.stripContext(conn.getStatements(null, null, null, contextName1, contextName2))); `

Is there a more functional approach that we can support? All these wrapped static methods get on my nerves a bit :)

**Comment by hmottestad** [comment]
Try (... stream = Iterations.stream(conn.getState....){
    Model m = stream
        .map(Statements::stripContext)
        .collect(Models.toModel())
}

**Comment by hmottestad** [comment]
Would also work for models directly since you can stream models too. I still like to have helper methods for increased discoverability. Would also be nice to consider model1.stripContexts(), or model1.extractContexts(ctx1, ctx2).

**Comment by jeenbroekstra** [comment]
>  Would also be nice to consider model1.stripContexts(), or model1.extractContexts(ctx1, ctx2).

I'm leaning towards not doing that to be honest, we've deliberately kept the Model interface quite lean and put these kinds of sophisticated manipulations into the Models helper class instead. Unless we have a very strong use case in favor of it I'd rather we stick to that philosophy.

**Comment by jeenbroekstra** [comment]
On the naming thing: current gut preference is `stripContexts` over `extractContexts` as I think it more clearly communicates that the context bit is the thing being _removed_ .

**Comment by hmottestad** [comment]
Chaining is a good reason. And discoverability. And it’s more classic object orientation. But I agree that the model interface should be lean. 

But this is what it could look like:

boolean isomorphic = m1
.extractContext(ctx1)
.filter(null, RDF.type, null)
.isomorphic(m2)

**Comment by jeenbroekstra** [comment]
Fair point on classic object orientation. I'm less concerned about the discoverability as I think we make quite a point of `Models` being the go-to functional util class. As for chaining: in your particular example the static helper equivalent would be:

    boolean isomorphic = Models.stripContexts(m1, ctx1)
                                         .filter(null, RDF.TYPE, null)
                                         .isomorphic(m2);

It's not _that_ much more complicated (especially if you start working with static imports). 

I suggest we don't add this to `Model` itself in the first instance, and for now keep to the lean philosophy. If we find it limiting or confusing we can always change our mind and add it in, but once we add it in it's hard to take it back out again.

Summarizing, I suggest we should add the following as part of this issue:

-   `public static Model Models.stripContexts(Model model, Resource... contexts){...}`
        extract all statements matching the contexts and strip away the context. 
- `public static Statement Statements.stripContext(Statement statement){...}`
        convert a statement with (or without) a context to a statement without a context
- `public static CloseableIteration<Statement,...> QueryResults.stripContexts(CloseableIteration<Statement, ...> iteration, Resource... contexts){...}`
        create an iteration that strips away the provided contexts from the statements, or _all_ contexts if no contexts are provided

Lastly, we should add a custom implementation of a Collector class for models. We should probably treat that as a separate issue. 

Anything I overlooked?

**Comment by hmottestad** [comment]
> all contexts if no contexts are provided

Also for the Models.stripContexts I reckon. 

LGTM :)

**Comment by chris-no1** [comment]
From and outside perspective new to RDF4J, the concept of context is a bit enigmatic in the beginning. I’ve been using Apache Jena before, where consolidate/union of model(s) is explicit and [Jena](https://jena.apache.org/documentation/javadoc/jena/) has this functionality on its model interface.
My gut feeling in the beginning was to look for something like this.

`Model modelUnion = conn.union(context1, context2, ...)); `
Or for all contexts.
`Model modelUnion = conn.union()); `

**Comment by hmottestad** [comment]
FYI a context in RDF4J is what Jena calls a graph and what SPARQL calls a named graph.

**Comment by chris-no1** [comment]
Yes, but don’t remember if they are named graph’s?

What they do have is classes for manipulate Collections of statement like. Delta, DisjointUnion, Intersect .. and they are not static helper classes.

`public Difference(Graph L,  Graph R) //etc.`

**Comment by jeenbroekstra** [comment]
> Yes, but don’t remember if they are named graph’s?

Sorry, I'm not sure what you're asking here - can you clarify?

> What they do have is classes for manipulate Collections of statement like. Delta, DisjointUnion, Intersect .. and they are not static helper classes.
> 
> `public Difference(Graph L, Graph R) //etc.`

I assume "they" is Jena in this case? Fwiw RDF4J does have similar functionality for manipulating collections. There are several graph comparison methods in the `Models` class, and of course, RDF4J Models being Java Collections, you can use standard Java Collection operations for a lot of this kind of thing. 

But we're getting a bit off-topic here - the scope of this issue is look into functionality for "forgetting" the context/named graphs on a model. Happy to hear your thoughts on other improvements we can make / questions you have of course, but let's do those back on the mailinglist (or open a new issue here).

**Comment by chris-no1** [comment]
> Sorry, I'm not sure what you're asking here - can you clarify?
Only that Graph is unnamed Collection of statements.

> RDF4J Models being Java Collections
I understand, using Collections nomenclature instead of graph. Then I would say;

`model1.clearConstext(...)`

**Comment by jeenbroekstra** [comment]
> I understand, using Collections nomenclature instead of graph. Then maybe clear is "clear";
> 
> `model1.clearConstext(...)`

The problem I see with that is that it is very close to the already-existing `clear(Resource... contexts)` method. This is why I prefer something like 'strip' instead: it's sufficiently different from existing method names that it is more clear that it does something different.

**Comment by jeenbroekstra** [comment]
I'm leaving out the change to `CloseableIteration` for now, as we have no single concrete implementation of `ClosableIteration<Statement>`. I believe the use case is sufficiently covered by being able to stream and using the other util functions, for example:

    Iterations.stream(conn.getStatements(...))
           .map(st -> Statements.stripContext(st)).collect(Collectors.toList());
