### ISSUE TITLE
FilteredModel accept/matches dodgy code

### ISSUE THREAD

**Issue by barthanssens** [eclipse/rdf4j#1767]
Via findbugs: org.eclipse.rdf4j.model.impl.FilteredModel:

line 215, accept() always returns true in a complicated check

```
private boolean accept(Resource s, IRI p, Value o, Resource... c) {
   ...
   return (s == null || s instanceof Resource) && (p == null || p instanceof IRI);
}
```
line 233, similar issue in matches()

```
private boolean matches(Resource stContext, Resource... contexts) {
   ...
   return stContext == null || stContext instanceof Resource;
```

**Comment by jeenbroekstra** [comment]
Fwiw happy to consider this kind of thing a bug, rather than an enhancement. That gives us the option to just fix it on master and get it out with next patch release.
