### ISSUE TITLE
Avg aggregate doesnt return correct zero

### ISSUE THREAD

**Issue by pulquero** [eclipse/rdf4j#1774]
org.eclipse.rdf4j.query.algebra.evaluation.iterator.GroupIterator.AvgAggregate returns "0.0"^^xsd:double instead of "0"^^xsd:integer when count is zero.

spec says:

> Avg(M) = "0"^^xsd:integer, where Count(M) = 0

**Comment by barthanssens** [comment]
A GroupIteratorTest would also be nice, working on it
