### ISSUE TITLE
More seamless integration of FedX Repository into RDF4J workbench

### ISSUE THREAD

**Issue by aschwarte10** [eclipse/rdf4j#1787]
As of #1538 we integrated FedX into the RDF4J project. The code integration is looking quite fine, as validations using the current milestone reveal.

However, the integration into the RDF4J workbench is not as seamless as it could be:

* currently the rdf4j-tools-federation jar is not part of the rdf4j-server.war distribution (thus the binary repository implementation is not available in the workbench)
* the repository configuration template is not offered in the RDF4J workbench
* documentation is not provided for the integration

Currently FedX can be used in the RDF4J workbench with the following manual steps

1) Copy `rdf4j-tools-federation.jar` into the deployed rdf4j-server webapp (i.e. to `webapps/rdf4j-server/WEB-INF/lib`)
2) Manually create a repository folder in the RDF4J repositories dir with the federation config depicted below, e.g. to `/users/home/myuser/.RDF4J/server/repositories/my-federation/config.ttl`

```
#
# RDF4J configuration template for a FedX Repository
#
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>.
@prefix rep: <http://www.openrdf.org/config/repository#>.
@prefix fedx: <http://rdf4j.org/config/federation#>.

[] a rep:Repository ;
   rep:repositoryImpl [
      rep:repositoryType "fedx:FedXRepository" ;
      fedx:member [
         fedx:store "ResolvableRepository" ;
         fedx:repositoryName "repo1" 
      ] ,
      [
         fedx:store "ResolvableRepository" ;
         fedx:repositoryName "repo2" 
      ]
   ];
   rep:repositoryID "my-federation" ;
   rdfs:label "FedX Federation" .
```

This will create a federation repositoy in the RDF4J workbench (including all convenience like lifecycle management, SPARQL endpoint, ...). This example will have the two repositories "repo1" and "repo2" as members. The repositories are created and managed by the RDF4J Workbench (i.e. they can be created from the RDF4J workbench UI, for example as NativeStore)

**Comment by aschwarte10** [comment]
@jeenbroekstra can you comment on whether you see this in for 3.1? Also can you provide me with some pointer on what needs to be done to get the jar into the webapp?

Regarding the template: from my understanding it would currently mean to add it as a resource to `/core/repository/api/src/main/resources/org/eclipse/rdf4j/repository/config`, as only these are exposed to the RDF4J workbench UI

**Comment by jeenbroekstra** [comment]
From the top of my head: getting the jar into the server war should be as simple as making sure it's listed in the dependencies of the http-server pom. 

Config template in the location you mention sounds good, and it will make it immediately available as an option in the Console CLI. But if we want to expose the configuration template as an option in in the dropdown menu in the Workbench, we'll need to do some additional work: that dropdown is currently hardcoded unfortunately.

**Comment by aschwarte10** [comment]
@jeenbroekstra I was experimenting with this a bit: it looks like we could re-use the existing code for definining the federation and instead of creating a FederationSail create a FedXRepository. 

While doing my evaluation I however stumbled into a maven cyclic dependency issue: the 
`rdf4j-tools-federated` module currently has a test-scope dependency (i.e. only for tests) on `rdf4j-http-server-spring. In order to make the federation code available in the webapp I either need to add it as a dependency to rdf4j-server (which works out) or to the rdf4j-storage (which is transitively added). The latter would introduce cycles.

I personally would like to see `rdf4j-tools-federated` in `rdf4j-storage` at some point in time, but this would mean that the federation modulle may no longer depend on the `rdf4j-http-server-spring` module. This would be possible by moving all federation tests to another module, e.g. something like federated-integration. 

What is your opinion on this?

I am going to create a PR as a basis for discussion, as this makes things easier to explain. We can also discuss on the PR
