### ISSUE TITLE
standardize formatting for xml files

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#1798]
We have formatting standardized for java files, but unfortunately for xml files we do not, leading to regular merge conflicts and other issues on pom.xml files and other configuration files - some editors use tabs, others spaces, and it all quickly becomes messy.

**Comment by barthanssens** [comment]
So tabs all the way, I presume ? :-)

**Comment by jeenbroekstra** [comment]
Almost any convention will do as long as we stick with it, but since we use tabs in java, we might as well be consistent. Single tab per indent seems logical. Fwiw I'm not considering doing any sort of project tooling around this, to be honest, at least not as a first step. It will be up to everyone to tweak their editors to use the convention.

@hmottestad @aschwarte10 any strong opinions on using tabs as convention for xml file indentation?

**Comment by jeenbroekstra** [comment]
Fwiw I'm taking a quick look at the xml-format-maven plugin, which looks useful. Unfortunately, the current release does not support tab indents, so I've opened PR with a fix: https://github.com/acegi/xml-format-maven-plugin/pull/25

**Comment by jeenbroekstra** [comment]
I've reformatted our xml files on both main branches using `mvn xml-format:xml-format`, so everything is now indented with tabs. Please adjust your editors. The convention is not enforced by maven, but you can of course use `mvn xml-format:xml-format` yourself if you want, or `mvn xml-format:xml-check` to verify without changing.
