### ISSUE TITLE
FederationJoinOptimizer.getUnionArgs

### ISSUE THREAD

**Issue by pulquero** [eclipse/rdf4j#180]
Surely

> 	private List<TupleExpr> getUnionArgs(TupleExpr union, List<TupleExpr> list)
	{
		if (union instanceof Union)
		{
			getUnionArgs(((Union) union).getLeftArg(), list);
			getUnionArgs(((Union) union).getLeftArg(), list);
		}
		else
		{
			list.add(union);
		}
		return list;
	}

should be 

>	private List<TupleExpr> getUnionArgs(TupleExpr union, List<TupleExpr> list)
	{
		if (union instanceof Union)
		{
			getUnionArgs(((Union) union).getLeftArg(), list);
			getUnionArgs(((Union) union).**getRightArg**(), list);
		}
		else
		{
			list.add(union);
		}
		return list;
	}

**Comment by jeenbroekstra** [comment]
This seems likely :) well spotted, thanks. I'll take a closer look to make sure and put up a fix.
