### ISSUE TITLE
String literals are not properly escaped

### ISSUE THREAD

**Issue by RoKish** [eclipse/rdf4j#1815]
The approach used for escaping string literals doesn't work for all cases. For example, a string literal won't be properly escaped if its value ends with a single quote (i. e. `value'`). The values like `val'''ue` will also fail. Though the second case seems to be unlikely, I do have some literals ending with a single quote.

The following code fails with `MalformedQueryException`:

```
ConstructQuery query = Queries.CONSTRUCT().where(GraphPatterns.tp(SparqlBuilder.var("s"), RDFS.LABEL, Rdf.literalOf("value'")));
ParsedGraphQuery parsedGraphQuery = QueryParserUtil.parseGraphQuery(QueryLanguage.SPARQL, query.getQueryString(), null);
```

Does it make sense to use backslashes according to [SPARQL 1.1 Query Language – Escape sequences in strings](https://www.w3.org/TR/2013/REC-sparql11-query-20130321/#grammarEscapes). I.e. `value'` is escaped as `value\'`, `val"ue` becomes `val\"ue` etc.?

**Comment by jeenbroekstra** [comment]
Another solution in this case is to double quotes instead of single quotes. SparqlBuilderUtils currently indiscriminately uses single quotes for long-quoted strings, so you end up with:

    '''values''''

which, as you say, is not syntactically correct. However, if it (depending on whether the quoted string contains a ' or a ") has the choice between single and double quotes, it could produce this:

    """values'"""

which is legal. 

As you say, however, a backslash escape is another option.

**Comment by RoKish** [comment]
I didn't know of long double-quotes syntax. 

From my perspective, escaping with backslashes looks safer as it will correctly handle the cases when the string contains both single and double quotes (i. e. `"value'`). Am I missing some edge cases that can be handled with long double/single quotes and can't be handled with the backslash approach?

**Comment by jeenbroekstra** [comment]
No I agree that escaping is a better approach.

**Comment by fkleedorfer** [comment]
> As you say, however, a backslash escape is another option. In fact, I've noticed that SparqlBuilder doesn't seem to be handling any code point escaping, so there's a broader issue here.

Looking into this. Just to clarify what we want for string literals:
Java String | result of `.getQueryString()`
------------ | ------------------------------
`'` | `\'`
`"` | `\"`
(unescaped tab character) | `\t`
(unescaped newline character) | `\n`
(unescaped carriage return character)  | `\r`
(unescaped backspace character) | `\b`
(unescaped form feed character) | `\f`
`\` | `\\`

For code point escapes, I believe that they cannot be handled in any special way. If a character, say `\u2021`, somehow ends up in a Java String, it is already a unicode character and will be written to the query like that. If, on the other hand, the backslash is escaped in the String, it will be the String `\u2021`.

Opinions?
