### ISSUE TITLE
StatementAdded/Removed events for duplicate events in same txn

### ISSUE THREAD

**Issue by tcarpenter-chi** [eclipse/rdf4j#183]
Copying this issue over from JIRA. 

There is an issue with sail-memory and sail-nativerdf that causes a notification sail to receive duplicate notifications in a transaction as well as removal notifications when they shouldn't be. 

A discussion can be found here: [https://groups.google.com/forum/#!topic/rdf4j-users/FDRdfCq4Czc](https://groups.google.com/forum/#!topic/rdf4j-users/FDRdfCq4Czc)

**Comment by jeenbroekstra** [comment]
@hmottestad I seem to remember that you recently did something about this because you needed it for SHACL. Is this issue still relevant?

**Comment by hmottestad** [comment]
I fixed some issues with how the notifying sail works as part of getting the ShaclSail to work. I haven't had any issues since then, so I reckon it's fixed.
