### ISSUE TITLE
Regression: Nativestore memory consumption

### ISSUE THREAD

**Issue by barthanssens** [eclipse/rdf4j#1834]
3.1.0-snapshot Nativestore consumes much more (x 4 - 5) memory than 3.0.4 with IsolationLevels.SERIALIZABLE

See also #1031

**Comment by hmottestad** [comment]
This is due to the switch from TreeModel to LinkedHashModel. Switching model implementations solves a race condition issue for SERIALIZABLE transactions where the model was being read from different threads concurrently. The TreeModel does not support concurrent reads.

**Comment by hmottestad** [comment]
With a fix to the underlying issue, this is still an issue....but only in terms of GC. Because the LinkedHashModel uses more memory than the TreeModel, 3.1.0 will cause more GC. I'm not too worried though and I'm closing this now.
