### ISSUE TITLE
De-duplicate NTriples/Turtle code 

### ISSUE THREAD

**Issue by barthanssens** [eclipse/rdf4j#1839]
NTriplesUtil and TurtleUtil (and org.eclipse.rdf4j.common.text.ASCIIUtil) share some code on encoding/decoding Literals and URI, checking if a character is a number etc.
Shared code could perhaps go to o.e.r.c.t.ASCIIUtil or StringUtil.

**Comment by barthanssens** [comment]
Somewhat related to #1535

**Comment by jeenbroekstra** [comment]
This is possibly caused by (in the past) the rules for encoding special characters being not _entirely_ identical between the Turtle and N-Triples format. I would expect that that has been rectified in the latest specs, but might be good to double-check.

**Comment by barthanssens** [comment]
Good point. 
I think it should be possible to restructure the current code base so that the TurtleWriter extends NTripleWriter (and same goes probably for Parser) because some methods are just copy/paste.
Though it is indeed a good idea to double-check if that is actually the correct (per spec) behavior...
