### ISSUE TITLE
Adds xsd:duration arithmetics to SPARQL

### ISSUE THREAD

**Issue by Tpt** [eclipse/rdf4j#184]
It would be nice to add support of "+", "-", "<", ">", ">=" and "<=" operators on xsd:duration literal to SPARQL.

Jena already support such operators. see https://github.com/apache/jena/blob/master/jena-arq/src/main/java/org/apache/jena/sparql/expr/nodevalue/NodeValueOps.java

Probably blocked by #164

**Comment by jamesrdf** [comment]
Looks like a good idea, would need to target 2.3.0 though as it is a new feature. A Pull Request should be created in [/eclipse/rdf4j-storage/pulls](/eclipse/rdf4j-storage/pulls), as we are currently migrating storage/eval code to a separate project.
