### ISSUE TITLE
Statement controller doesn't take into account max execution time

### ISSUE THREAD

**Issue by nikolavp** [eclipse/rdf4j#187]
Max execution time is ignored in StatementController. This affects https://openrdf.atlassian.net/browse/SES-2174 and the linked issue for remote update queries (going through HTTPRepositoryConnection). This is already done in repository controller so the implementation can be taken from there.

This affects 2.9.0, not sure if it is implemented for 4.0.0

**Comment by jeenbroekstra** [comment]
Hm. It isn't documented that we support a timeout param on this operation, which is probably why it was overlooked. You're correct though that it should. I'll add the param and update the REST API documentation as well.
