### ISSUE TITLE
Incorrect/inconsistent cardinality calculation

### ISSUE THREAD

**Issue by pulquero** [eclipse/rdf4j#1873]
EvaluationStatistics.getCardinality() should use Set<Var> vars = pattern.getVars(new HashSet<>()) else
?s ?p ?o and ?s ?s ?s are considered to have the same cardinality.

**Comment by hmottestad** [comment]
@pulquero can you provide a link to exact line in the code in github?

**Comment by pulquero** [comment]
Sry, it's exactly in the fed version not the main one. 

https://github.com/eclipse/rdf4j/blob/d2a301dabcf9c051b019e3434327c15c29fc321e/core/sail/federation/src/main/java/org/eclipse/rdf4j/sail/federation/optimizers/EvaluationStatistics.java#L84

**Comment by hmottestad** [comment]
Thanks

**Comment by reeshabhkumarranjan** [comment]
Can I work on this issue?

**Comment by barthanssens** [comment]
Sure, it's an open source project, and any help is welcome and much appreciated.

If this is your first contribution to RDF4J, there is one small but necessary thing you have to do: register for a (free) Eclipse account and sign a form

See "Legal stuff" in https://github.com/eclipse/rdf4j-doc/blob/master/.github/CONTRIBUTING.md

**Comment by hmottestad** [comment]
@aschwarte10 is this class `org.eclipse.rdf4j.sail.federation.optimizers.EvaluationStatistics` used by FedX?

**Comment by reeshabhkumarranjan** [comment]
So as per I understood the code, and the solution suggested in this issue, I just need to make sure that only distinct elements are in the `vars` list in this [line](https://github.com/eclipse/rdf4j/blob/d2a301dabcf9c051b019e3434327c15c29fc321e/core/sail/federation/src/main/java/org/eclipse/rdf4j/sail/federation/optimizers/EvaluationStatistics.java#L84), right?

**Comment by hmottestad** [comment]
> So as per I understood the code, and the solution suggested in this issue, I just need to make sure that only distinct elements are in the `vars` list in this [line](https://github.com/eclipse/rdf4j/blob/d2a301dabcf9c051b019e3434327c15c29fc321e/core/sail/federation/src/main/java/org/eclipse/rdf4j/sail/federation/optimizers/EvaluationStatistics.java#L84), right?

I believe that is what is required. A test would also be nice.

**Comment by reeshabhkumarranjan** [comment]
Alright, I will link a pull-request for this shortly.

**Comment by reeshabhkumarranjan** [comment]
> Sure, it's an open source project, and any help is welcome and much appreciated.
> 
> If this is your first contribution to RDF4J, there is one small but necessary thing you have to do: register for a (free) Eclipse account and sign a form
> 
> See "Legal stuff" in https://github.com/eclipse/rdf4j/blob/master/.github/CONTRIBUTING.md

Thank you @barthanssens for linking the legal procedures.

**Comment by reeshabhkumarranjan** [comment]
I have made some changes to the code ([here](https://github.com/reeshabhkumarranjan/rdf4j/commit/8d0599eb829b836819c55d9db9cf2deea8f026c4)). If this is fine, I would like to proceed with the tests. Also, this will be my first contribution for this repository, so I am a bit unsure about where to write the tests. Should I make a new file under

`<project-root>/testsuites/sail/src/main/java/org/eclipse/rdf4j/sail` ?

**Comment by hmottestad** [comment]
How about in a new package `optimizers` in `core/sail/federation/src/test/java/org/eclipse/rdf4j/sail/federation`?

**Comment by reeshabhkumarranjan** [comment]
Alright, I will create a package `optimizers` and will create a test-file in it.

**Comment by reeshabhkumarranjan** [comment]
I missed adding the issue number in my first commit, so is that fine or should I do something about it?

**Comment by hmottestad** [comment]
You can always edit your commit messages afterwards and also squash multiple commits together. Just don't merge anything into your branch.

More importantly is that you sign off on your commits. 

> Every commit you make in your patch or pull request MUST be "signed off". You do this by adding the -s flag when you make the commit(s).

I found this helpful guide if you've never used sign off before: https://docs.pi-hole.net/guides/github/how-to-signoff/

**Comment by reeshabhkumarranjan** [comment]
I have linked the pull-request, kindly review it and let me know of any suggestions.
