### ISSUE TITLE
How to parse a huge file?

### ISSUE THREAD

**Issue by judeBayd** [eclipse/rdf4j#1875]
Parsing a huge file raises a an exception. The documentation 
`-Djdk.xml.totalEntitySizeLimit=0 -DentityExpansionLimit=0`

doesnt work.
Any help please?

**Comment by barthanssens** [comment]
Hi, could you provide some additional info, so we can investigate this ? Thanks.

- which version of RDF4J are you using ?
- what's the exact exception ?
- how huge is the file ? (a few gigabytes ? more ?)

**Comment by hmottestad** [comment]
FYI. 4.x parses large files into the NativeStore without much problems as long as you start a transaction with IsolationLevels.NONE.

**Comment by jeenbroekstra** [comment]
Possibly related to https://stackoverflow.com/questions/59889296/how-to-parse-a-big-rdf-file-in-rdf4j .

**Comment by jeenbroekstra** [comment]
It would also help if you could attach (or provide a link to) the actual rdf file you're trying to process.

**Comment by judeBayd** [comment]
@jeenbroekstra  @barthanssens  I tried to parse swetoDBLP (swetodblp_april_2008.rdf)
from this page http://oaei.ontologymatching.org/2009/instances/.
The size of the file is: 1086224 KB. 
The exception when executing: `mvn -Djdk.xml.totalEntitySizeLimit=0 -Djdk.xml.entityExpansionLimit exec:java` is the following:
```
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building HelloRDF4J 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] >>> exec-maven-plugin:1.2.1:java (default-cli) > validate @ rdf4j-getting-started >>>
[INFO]
[INFO] <<< exec-maven-plugin:1.2.1:java (default-cli) < validate @ rdf4j-getting-started <<<
[INFO]
[INFO]
[INFO] --- exec-maven-plugin:1.2.1:java (default-cli) @ rdf4j-getting-started ---
[WARNING]
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.eclipse.rdf4j.rio.RDFParseException: The parser has encountered more than "100,000" entity expansions in this document; this is the limit imposed by the application.
        at org.eclipse.rdf4j.rio.helpers.RDFParserHelper.reportFatalError(RDFParserHelper.java:403)
        at org.eclipse.rdf4j.rio.helpers.AbstractRDFParser.reportFatalError(AbstractRDFParser.java:657)
        at org.eclipse.rdf4j.rio.rdfxml.RDFXMLParser.reportFatalError(RDFXMLParser.java:1250)
        at org.eclipse.rdf4j.rio.rdfxml.RDFXMLParser.fatalError(RDFXMLParser.java:1406)
        at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source)
        at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
        at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
        at org.apache.xerces.impl.XMLEntityManager.startEntity(Unknown Source)
        at org.apache.xerces.impl.XMLEntityManager.startEntity(Unknown Source)
        at org.apache.xerces.impl.XMLScanner.scanAttributeValue(Unknown Source)
        at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanAttribute(Unknown Source)
        at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
        at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
        at org.eclipse.rdf4j.rio.rdfxml.RDFXMLParser.parse(RDFXMLParser.java:330)
        at org.eclipse.rdf4j.rio.rdfxml.RDFXMLParser.parse(RDFXMLParser.java:209)
        at ConvertOntology.main(ConvertOntology.java:38)
        ... 6 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.857 s
[INFO] Finished at: 2020-01-31T16:24:07-08:00
[INFO] Final Memory: 26M/2434M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:java (default-cli) on project rdf4j-getting-started: An exception occured while executing the Java class. null: InvocationTargetException: The parser has encountered more than "100,000" entity expansions in this document; this is the limit imposed by the application. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[tamouze@cdr768 rdf4j-getting-started]$ mvn -Djdk.xml.totalEntitySizeLimit=0 -Djdk.xml.entityExpansionLimit exec:java
```

**Comment by jeenbroekstra** [comment]
> The exception when executing: `mvn -Djdk.xml.totalEntitySizeLimit=0 -Djdk.xml.entityExpansionLimit exec:java` is the following:

There's a typo in there. It should be 

     mvn -Djdk.xml.totalEntitySizeLimit=0 -Djdk.xml.entityExpansionLimit=0 exec:java

Note the `=0` bit after the `entityExpansionLimit`.

>  	<dependency>
  		<groupId>org.eclipse.rdf4j</groupId>
  		<artifactId>rdf4j-runtime</artifactId>
  		<version>2.0</version>
  	</dependency>

Version 2.0 of RDF4J is over 4 years old. You might want to consider upgrading.

**Comment by judeBayd** [comment]
@jeenbroekstra Im sorry still with your command I get the same exception.

**Comment by hmottestad** [comment]
Try the newest 3.0.x version of rdf4j, it should have a limit of 64 000.

**Comment by hmottestad** [comment]
Btw. I just tested this and got the following:

```
org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; JAXP00010001: The parser has encountered more than "64000" entity expansions in this document; this is the limit imposed by the JDK.
```

**Comment by hmottestad** [comment]
I used `-Djdk.xml.totalEntitySizeLimit=0 -DentityExpansionLimit=0` while running my test and now it parses the file perfectly fine!

<img width="1114" alt="Screenshot 2020-02-01 at 19 38 48" src="https://user-images.githubusercontent.com/797185/73597277-7ad5db00-452a-11ea-8c37-270a64ee77de.png">

**Comment by judeBayd** [comment]
@hmottestad i tried to migrate to 3.0..4 version. can you please give the efficient dependency in your .pom file, please

**Comment by hmottestad** [comment]
Works perfectly fine in 2.0 as well. I think maybe your issue lies with java:exec.

This is what i tried for 3.0.4:

```
    <dependencies>
        <dependency>
            <groupId>org.eclipse.rdf4j</groupId>
            <artifactId>rdf4j-runtime</artifactId>
            <version>3.0.4</version>
        </dependency>
    </dependencies>
```

**Comment by judeBayd** [comment]
@hmottestad thank you for you help but unfortunately it is not working after moving to 3.0.4 version. 
I get the following:
`InvocationTargetException: The parser has encountered more than "100,000" entity expansions in this document; this is the limit imposed by the application. `

By the way, if you parser the file perfectly which is in rdf, can i get it is equivalent in .nt.

the code could be:
```
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;

import org.eclipse.rdf4j.model.Model;
import org.eclipse.rdf4j.model.Statement;
import org.eclipse.rdf4j.model.impl.LinkedHashModel;
import org.eclipse.rdf4j.rio.RDFFormat;
import org.eclipse.rdf4j.rio.RDFParser;
import org.eclipse.rdf4j.rio.RDFWriter;
import org.eclipse.rdf4j.rio.Rio;
import org.eclipse.rdf4j.rio.helpers.StatementCollector;
public class ConvertOntology {

	public static void main(String[] args) throws  IOException {
		// TODO Auto-generated method stub

		String file =  "./swetodblp_april_2008.rdf";
		// read the file 'example-data-artists.ttl' as an InputStream.
		File initialFile = new File(file);
		InputStream input = new FileInputStream(initialFile);


		RDFParser parser = Rio.createParser(RDFFormat.RDFXML);
		parser.setPreserveBNodeIDs(true); 

		Model model = new LinkedHashModel();
		parser.setRDFHandler(new StatementCollector(model));
		parser.parse(input, initialFile.getAbsolutePath());
		String test = "C:/Users/user/Desktop/eprints-rexa/pppp.tsv";
		FileOutputStream out = new FileOutputStream("./swetodblp_april_2008.nt");

		RDFWriter writer = Rio.createWriter(RDFFormat.TURTLE, out);
		
		  writer.startRDF();
		  for (Statement st: model) {

				  	writer.handleStatement(st);
		  }
		  writer.endRDF();
		
		
	}


}
```

**Comment by jeenbroekstra** [comment]
> @hmottestad thank you for you help but unfortunately it is not working after moving to 3.0.4 version.
I get the following:
InvocationTargetException: The parser has encountered more than "100,000" entity expansions in this document; this is the limit imposed by the application. 

I don't understand. Just above you mentioned that you figured out how to solve this. This is the exact same error you had earlier. The solution is also exactly the same.

**Comment by judeBayd** [comment]
@jeenbroekstra I dont mention it is solved. I just change the version of my rdf4j. So even with the lastest version with the rdf4j i get the same exception.

**Comment by jeenbroekstra** [comment]
>  @jeenbroekstra  I dont mention it is solved. I just change the version of my rdf4j. So  even with the lastest version of rdf4j i get the same exception

Ah my bad, that was @hmottestad who posted that it worked for him, I misread. 

I wonder if there's an issue with the specific XML parser implementation on your classpath. Which JDK version are you using?

**Comment by judeBayd** [comment]
@jeenbroekstra Im using jdk-12.0.2

**Comment by jeenbroekstra** [comment]
I just noticed in your error stacktrace that your program appears to be using the Apache Xerces XML parser, rather than the default JDK XML parser. I've ran a few tests locally and confirmed that that is the core of your problem: for some reason Apache Xerces ignores the JAXP `entityExpansionLimit` settting. 

I'm not sure if there is an alternative way to configure this in Apache Xerces, but unless you have a real strong need for including Apache Xerces, the simplest fix is to just remove that dependency from your classpath, and rely on the standard JDK XML parser.

**Comment by barthanssens** [comment]
Seems like the Xerces bug is still open https://issues.apache.org/jira/browse/XERCESJ-1654

So as Jeen mentioned, you probably have to switch to the default JDK XML parser...

**Comment by jeenbroekstra** [comment]
@judeBayd as an aside: the conversion java code example you posted is likely to cause out of memory errors, since you are first parsing the entire file into an (in-memory) model object before writing it back to file in a different format. There are more efficient ways to do this. See https://rdf4j.org/documentation/programming/rio/#writing-rdf for more details.

**Comment by judeBayd** [comment]
@jeenbroekstra I will thank you for sharing your knowledge and expertise. I just remove from .m2 folder  the xerces folder and then my code  (as you suggested) works fine. I appreciate your help and the hels of the rd44j fans :).
Please can you add this information to the documentation (In my case the xerces was used to parse excel file). Thank you again
