### ISSUE TITLE
Turtle not considering the subject's namespace

### ISSUE THREAD

**Issue by TriangularIT** [eclipse/rdf4j#1883]
I have tried to implement the introductory tutorial from the rdf4j homepage called [Getting Started with rdf4j, Maven, and Eclipse](https://rdf4j.org/documentation/maven-eclipse-project).

The last step, however, where the model is made aware of the namespaces, does not work correctly, because the output does not prefix the custom namespace defined in the project.

**Expected output:**
```
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix ex: <http://example.org/> .

ex:john a foaf:Person;
  rdfs:label "John" .
```

**Actual output:**
```
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

<http://example.org/john> a foaf:Person;
  rdfs:label "John" .
```

**Reason:**
[ArrangedWriter.getUsedNamespaces](https://github.com/eclipse/rdf4j/blob/7b1045db28eb524173babcfd412afd220403e962/core/rio/turtle/src/main/java/org/eclipse/rdf4j/rio/turtle/ArrangedWriter.java#L333) only considers the predicate and the object of a statement when collecting the namespaces.

Is this the intended behaviour?

**Comment by barthanssens** [comment]
Hmmz, seems like a bug to me

(arguably, it might be nice to have an option to disable the use of namespace prefixes on subjects)
