### ISSUE TITLE
SHACL validation report remote repository

### ISSUE THREAD

**Issue by barthanssens** [eclipse/rdf4j#1900]
See forum https://groups.google.com/forum/#!topic/rdf4j-users/VDlWNjQ5eHw

On a local repository, one can easily retrieve the ShaclSail validation report when a SHACL validation exception is thrown.

It would be nice to have an easy way to get/parse the same validation report in a client application, while the validation is done on a remote repository  / server (HTTPRepository)

**Comment by hmottestad** [comment]
Should we go for a streaming approach so that we can handle large validation reports?

**Comment by barthanssens** [comment]
Would definitely be a plus. 

E.g. in the context of the EU ISA2 programme, there is an "interop testbed" for validating with SHACL, and the EU open data portal has a similar "metadata quality service" for validating large(r) files (100 K - 1 M triples) harvested from national/regional data portals (PSI/Open data Directive).

A similar approach might be useful for Single Digital Gateway, Multi-Modal Travel Information Services, .... so there are use cases :-)

**Comment by jeenbroekstra** [comment]
Perhaps this should be a separate issue, but: I have been thinking if maybe we should decouple the reporting from the exception handling. I can imagine use cases where people might want to use validation and get a report about what's invalid, but still commit the data.

**Comment by hmottestad** [comment]
There is the revalidate method which returns a validation report. It’s a bit hidden though, since it’s on the shacl sail connection and it’s common to wrap the sail in the sail repository. 

Btw. The assumption within the shaclsail is that the underlying store is valid. The fast and efficient validation only works because it can assume that there is no need to check the data already in the store. 

We could create a model validator instead. Preferably based on a new SHACL engine that generates SPARQL queries. That is what Stardog does, which makes it fast at validating large datasets but slow at validating changes.

**Comment by jeenbroekstra** [comment]
> We could create a model validator instead. Preferably based on a new SHACL engine that generates SPARQL queries. That is what Stardog does, which makes it fast at validating large datasets but slow at validating changes.

Wouldn't that mean that we'd essentially have two completely separate SHACL implementations? It sounds like an awful maintenance burden to keep feature-parity between both.

Anyway, this is off-topic for this issue, sorry for hijacking. I'll do some thinking and open a new ticket to discuss further.

**Comment by hmottestad** [comment]
I've been looking at this one today a bit, but the server is old style spring magic. Been trying to change things to try to see what happens, thought I had found a short-term fix but then it only works if you speak to the server directly and not when you use the workbench. 

The biggest pain I have with the server and the benchmark is that I cant easily run them up for debugging, so I can't see what's actually going on. I remember having to work on something similar maybe 10 years ago and then we had a guru who helped us for a few days to get intellij to fire tomcat and connect to it for debugging. Today I'm much more used to Spring Boot, where you just run up the application in debug and add your break points. 

Anyone debugged the Server recently and could give me some pointers?

**Comment by hmottestad** [comment]
Btw. For the implementation, I was thinking maybe NTRIPLES (since it can be streamed) as the body and maybe introducing a new header for specifying which exception was thrown.

**Comment by barthanssens** [comment]
I like the N-Triples streaming part :-)

I haven't been working on the Server / Workbench since quite a while (other than upgrading the Spring version) , so I can't help much on the server part :-/
(on a related note: #1502)

**Comment by hmottestad** [comment]
Closing this so it becomes a part fo the next release. Can always be opened again for future development.
