### ISSUE TITLE
How many triples can we put into this triple store ?

### ISSUE THREAD

**Issue by Lanvin2219** [eclipse/rdf4j#191]
Hi,

I just have one question (cf. title)

Thank you

**Comment by pulquero** [comment]
Your question would probably be better placed in https://groups.google.com/d/forum/rdf4j-users. And which store are you referring to? The in-memory store or the disk store? If I remember correctly, the disk store can go up to 100 million triples. In fact here http://stackoverflow.com/questions/11403314/sesame-in-memory-triple-store it says 150 million.

**Comment by Lanvin2219** [comment]
Thanks for answering !
I wasn't thinking about any in particular so both I guess.
