### ISSUE TITLE
N3Parser ? just handling "=" sign

### ISSUE THREAD

**Issue by tfrancart** [eclipse/rdf4j#1913]
Hello

Some files out there are N3 files, just using the "=" sign as an alias of owl:sameAs, not using any of the others N3 features. (e.g. https://cdstar.shh.mpg.de/bitstreams/EAEA0-3DAE-E27B-4692-0/glottolog_language.n3.gz from https://glottolog.org/meta/downloads).

```
<http://glottolog.org/resource/languoid/id/cani1243> a dcterms:LinguisticSystem,
        gold:Language ;
    rdfs:label "Canichana"@en ;
    void:inDataset <http://glottolog.org/> ;
    = <http://dbpedia.org/resource/ISO_639:caz> ;
    geo:lat "-14.3058"^^xsd:float ;
    geo:long "-64.944455"^^xsd:float ;
.
```

It would be nice to have a basic N3Parser that can handle this special case, probably without other features of N3.

Could be a simple addition to the TurtleParser, too.

**Comment by jeenbroekstra** [comment]
Currently, Rio's N3Parser is just the TurtleParser, under the hood. Adding this feature would require introducing a subclass that extends the Turtle syntax (I don't think it's a good idea to add this to the TurtleParser itself - let's keep that standards-compliant as much as possible).

**Comment by tfrancart** [comment]
Sounds good. I'll see if I can propose something, bandwidth permitting.

**Comment by jeenbroekstra** [comment]
That'd be great @tfrancart! Before you get going, please have a look at the [contributor guidelines](https://github.com/eclipse/rdf4j/blob/master/.github/CONTRIBUTING.md), in particular the points on how to sign the Eclipse Contributor Agreement. Shouldn't take more than 10 minutes to get set up. Let me know if you need any help with any of it.

**Comment by tanishapandey** [comment]
Hello
I would like to work on this issue. I was hoping if the issue could be assigned to me. 
I have signed the Eclipse Contributor Agreement as mentioned in the contributor guidelines.

Thank you

**Comment by barthanssens** [comment]
Ok, thank you for your help !
