### ISSUE TITLE
Implement SPARQL 1.2 proposed extension of Duration, Date, and Time support

### ISSUE THREAD

**Issue by abrokenjester** [eclipse/rdf4j#1915]
See https://github.com/w3c/sparql-12/blob/master/SEP/SEP-0002/sep-0002.md

We already partially support these additional operations as part of the ExtendedEvaluationStrategy.

**Comment by jeenbroekstra** [comment]
Lovely. Java 8 xsd duration implementation is buggy. At least one failure detected that is fixed by just upgrading to Java 11.
