### ISSUE TITLE
Switch to github cli for release automation

### ISSUE THREAD

**Issue by hmottestad** [eclipse/rdf4j#1917]
https://github.blog/2020-02-12-supercharge-your-command-line-experience-github-cli-is-now-in-beta/

For use in the release script.

See also https://cli.github.com/

**Comment by jeenbroekstra** [comment]
Ah, to automate creation of a pull request? Could be nice. It does require people installing another third party tool though.

**Comment by hmottestad** [comment]
I’m considering if it’s worth it though for a one-click release process.

**Comment by jeenbroekstra** [comment]
Fair enough, I mean it's not a huge burden to install, and there's only a few of us who are ever even going to be using the script anyway :)

**Comment by jeenbroekstra** [comment]
Related: GH-1995. I used `hub` in the initial fix, but it's probably worth switching to github cli (`gh`). Both are github projects, and `hub` is the older of the two, but it seems `gh` has gotten the "official" sanction and is likely to be more actively developed in the future.
