### ISSUE TITLE
Potential implementation of RDFPatch

### ISSUE THREAD

**Issue by ansell** [eclipse/rdf4j#193]
There is an implementation of the proposed RDFPatch specification for RDF4J that has expressed interest in adding the implementation to Apache Marmotta:

https://lists.apache.org/thread.html/a89a96e377abbecfe09499c7664b5ea4375f11a9a02bad80d83fd593@%3Cdev.marmotta.apache.org%3E

However, discussion may enable the contribution to be done to the core RDF4J instead:

https://github.com/sisinflab-swot/marmotta-util-rdfpatch-rdf4j

This is not to be confused with LDPatch that is similar but a different spec.

**Comment by ansell** [comment]
This duplicates issue #194

**Comment by jeenbroekstra** [comment]
Sounds very useful. @ansell @wikier is either of you in a position to work on integrating this in the near future?

**Comment by wikier** [comment]
Sure, it' d be great. The implementation was done by @ja-fra and myself, so we' re happy to help.

**Comment by jeenbroekstra** [comment]
Sweet! There will be some legalities we need to take care of first (you two signing the Eclipse CLA, for one thing), see the [Contributor Guidelines](https://github.com/eclipse/rdf4j/blob/master/.github/CONTRIBUTING.md) for details. Let me know if you need any help with that stuff. 

I assume this is, in essence, a Rio implementation, so it should probably be packaged as a new module (rio-rdfpatch ?). Given it's a new feature, it should be inserted on the master branch I think (and scheduled for the 2.1 release). 

I guess we should also have a look at the REST API and where necessary extend it to deal with HTTP PATCH requests. Or should we treat that as a separate issue?

**Comment by wikier** [comment]
Yes, it could go its own module; `rio-rdfpatch` could be an option.

At HTTP level, you have all LDP-related details at [LdpWebService.java:584](https://github.com/apache/marmotta/blob/develop/platform/marmotta-ldp/src/main/java/org/apache/marmotta/platform/ldp/webservices/LdpWebService.java#L584), and the business logic at [LdpServiceImpl.java:566](https://github.com/apache/marmotta/blob/develop/platform/marmotta-ldp/src/main/java/org/apache/marmotta/platform/ldp/services/LdpServiceImpl.java#L566). Unless you want to generalize LDP in RDF4J, I would skip that part for now.

**Comment by jeenbroekstra** [comment]
This is currently planned for the 2.1 release (due october 20). Can you commit to having the feature done by then (leaving enough time for review and testing)? If not, no worries, we'll just reschedule this.

**Comment by wikier** [comment]
@jeenbroekstra it shouldn't be much work. I'll discuss [MARMOTTA-649](https://issues.apache.org/jira/browse/MARMOTTA-649), both at the technical and legal level with the project and foundation respectivelly. And either @ja-fra or myself will take care with the next couple of weeks.

**Comment by jeenbroekstra** [comment]
@ansell @wikier doing some backlog grooming/cleaning and came across this. Is this still on the horizon? What needs to happen to move this forward?

**Comment by barthanssens** [comment]
See also #86 , which is another way to provide PATCH
