### ISSUE TITLE
Custom character encoding in RDFWriter/QueryResultWriter

### ISSUE THREAD

**Issue by erikgb** [eclipse/rdf4j#1942]
**Background**
I am developing a simple REST service on top of our SPARQL endpoint, to provide our business people with some prepared SPARQL queries - with input parameters. The REST service supports various RDF serialization formats - based on the formats supported by RDF4J. It turns out that the CSV has become the most popular output format for tuple queries - because the users want the results in MS Excel. MS Excel will happily open any file with the csv file extension, but the problem is that MS Excel assumes CP-1250 (Windows-1250) character encoding. This becomes an issue when all character format writers in RDF4J produces UTF-8 characters....

**No solution**
"Transform" the character stream based on the _Accept-Encoding_ request HTTP header supplied to our REST service. Currently we are just supplying the HttpServletResponse#OutputStream to the selected writer, based on the _Accept_ request HTTP header. This is something that works good, and makes the code extremly simple.

**Minimal solution**
File a PR that allows me to supply a `java.io.Writer`, configured with the "correct" character encoding, to `SPARQLResultsCSVWriter` and `SPARQLResultsTSVWriter`. The problematic lines are here:
https://github.com/eclipse/rdf4j/blob/d2a301dabcf9c051b019e3434327c15c29fc321e/core/queryresultio/text/src/main/java/org/eclipse/rdf4j/query/resultio/text/csv/SPARQLResultsCSVWriter.java#L48
https://github.com/eclipse/rdf4j/blob/d2a301dabcf9c051b019e3434327c15c29fc321e/core/queryresultio/text/src/main/java/org/eclipse/rdf4j/query/resultio/text/tsv/SPARQLResultsTSVWriter.java#L52

**New writer setting solution**
I have been looking a bit at the source code in RDF4J and the specifications for the RDF serialization formats, and I think that there are a few formats that allows non-UTF-8 character encoding. What do you think about introducing a new `BasicWriterSettings`/`BasicQueryWriterSettings`? I would suggest the name CHARACTER_ENCODING for this new hypothetical setting. And I think the following formats could potentially support this new setting:
- RDF/XML
- JSON-LD
- RDF/JSON
- RDFa
- SPARQL/XML
- SPARQL/JSON
- SPARQL/CSV
- SPARQL/TSV

I could eventually prepare a PR, but before spending time on this I would like to know what you think.

**Comment by hmottestad** [comment]
I think it could be a good idea to be able to provide a `Writer` to all our `SPARQLResults...Writer` classes. What do you think @jeenbroekstra ?

**Comment by jeenbroekstra** [comment]
> I think it could be a good idea to be able to provide a `Writer` to all our `SPARQLResults...Writer` classes. What do you think @jeenbroekstra ?

Agreed, this seems the easiest way forward. 

I don't think there's a need for an additional configuration option really. Instead I would just provide the option to use a `Writer` instead of an OutputStream, and let that Writer control the encoding. For the RDFWriters, this is how this is supported as well: any writer that has an option for separate encodings just provides the option to instantiate it with your own Writer class, instead of an OutputStream, e.g.

	/**
	 * @param writer
	 */
	public SPARQLResultsCSVWriter(Writer writer) {
		this.writer = new BufferedWriter(writer, 1024);
	}

**Comment by jeenbroekstra** [comment]
Actually, my earlier response may have been a bit kneejerk - thinking about it a bit more I can see the potential use case of a configuration setting.

**Comment by erikgb** [comment]
@jeenbroekstra @hmottestad : Thank you for your feedback so far! I would suggest a two step change to the code:
1. Introduce a Writer-constructor on the relevant `RDFWriter` and `QueryResultWriter` classes
2. New "basic" writer configuration setting to control the character encoding.

The changes to the code should be quite simple and easy to do - as it would be most refactoring. But I am not sure what tests to implement for this new feature, and how to write the tests? Do you have something similar in the code base that could be used as a reference?

**Comment by jeenbroekstra** [comment]
Thanks @erikgb, we'd appreciate your contribution! Before you get started, please have a look at the [contributor guidelines](https://github.com/eclipse/rdf4j/blob/master/.github/CONTRIBUTING.md), in particular the points on how to sign the Eclipse ECA. It shouldn't take more than 10-15 minutes to get it all set up. Let me know if you need any help with any of it.

As for testing, some general pointers: 

1. we use Junit 4, in combination with AssertJ (3.x), and Mockito (2.x), for unit and integration testing. 
2. Unit tests live in the same module as the production code they test, in src/test/java (standard Maven layout).
3. Integration/compliance tests live in the compliance directory under the project root, in several submodules that correspond to the production code modules. 
4. Reusable integration/unit testsuites are mostly defined in the testsuites directory under the project root, and the compliance tests often inherit from those (in some cases the unit tests also do - we're not always fully consistent in our setup)

Now, for the Rio and query result writers specifically:

- In the `rdf4j-rio-api` module, you will find an abstract set of tests for RDFWriters: [RDFWriterTest](https://github.com/eclipse/rdf4j/blob/master/core/rio/api/src/test/java/org/eclipse/rdf4j/rio/RDFWriterTest.java). You can add tests to the abstract class, or if you feel that your testcases are more implementation-specific, you can add them to the concrete subclass of that test set (which you will find in src/test/java of each implementation module).
- for query result io testing, there is a separate testsuite module, which you can find in testsuites/queryresultio (module name is `rdf4j-queryresultio-testsuite`). Each of the query result io writers have concrete implementation of these abstract testsuites, for example [SPARQLXMLTupleTest.java](https://github.com/eclipse/rdf4j/blob/master/core/queryresultio/sparqlxml/src/test/java/org/eclipse/rdf4j/query/resultio/sparqlxml/SPARQLXMLTupleTest.java). Again, either add your tests to the generic test suite, or if you feel they are format-specific, add them to each individual test implementation.

Hope that helps! Feel free to put up early PRs if you need some feedback on the approach and setup.

**Comment by erikgb** [comment]
Just a short update on this, from my POV. I feel bad for not being able to move forward with the pull request(s). 😢 I started on the initial work of adding `Writer`-constructors to the relevant `RDFWriter`-classes on [this branch](https://github.com/erikgb/rdf4j/tree/GH-1942-writer-character-encoding). That was the easy part. But when I tried to integrate these new constructors into the Rio API, I struggled to find a good way of doing it. But I am still trying to find a way to do it.
The issue seems to boil down to the fact that the `RDFWriter`-settings (that could include a character encoding setting) are applied after the `RDFWriter ` is constructed. So in order to not introduce any breaking changes, I'll have to come up with something "smart"....

**Comment by jeenbroekstra** [comment]
No worries, @erikgb , in your own time, we've all got day jobs so we understand it's not always easy to find the time :) 

Feel free to put up a (draft) pull request if you want us to look in more detail and provide our perspective - even if it doesn't work yet, it's easier for us to look at a PR on github than it is to have to download your branch locally.

**Comment by erikgb** [comment]
@jeenbroekstra: I have prepared a pull request assuring all relevant writers (for character based format) have a `Writer` constructor. This PR implements the change suggested by @hmottestad. But I would really like to fix the rio API as well - as this will make the new constructors easier to use. But anyway I think this should be two separate PR to keep the separation of concern.

**Comment by jeenbroekstra** [comment]
Thanks for the PR @erikgb, it looks very straightforward and clean. I'm fine with separating out in separate PRs though if you do, let's also create a separate followup issue, so that we can close this one (otherwise our release notes become a bit tricky to maintain). Also fine with you deciding to put it all in the one PR after all, if you prefer.
