### ISSUE TITLE
Harden SPARQLConnection.commit() against empty transactions

### ISSUE THREAD

**Issue by knoan** [eclipse/rdf4j#1960]
**How to Reproduce**

Execute the following snippet against a SPARQL 1.1 Update Endpoint.

```java
final SPARQLRepository repository=new SPARQLRepository("{query/update endpoint}");

repository.init();

try (final RepositoryConnection connection=repository.getConnection()) {

	connection.begin();

	connection.prepareUpdate(
			"prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>\n"
			+"\n"
			+"delete data { rdf:nil rdf:value rdf:nil }"
	).execute();

	connection.commit();

} finally {
	repository.shutDown();
}
```

**Expected Results**

Update silently executed.

**Actual Results**

Exception is possibly thrown.

**Notes**

- updates on SPARQL endpoints are immediately executed rather than queued to the current transaction (see `org.eclipse.rdf4j.repository.sparql.query.SPARQLUpdate:41`)
- on commit an empty update is submitted to the endpoint (see `org.eclipse.rdf4j.repository.sparql.SPARQLConnection:394`) and if the endpoint doesn't gracefully handle the event an exception is thrown
- works as expected when replacing the SPARQL update with the functionally equivalent `connection.remove(RDF.NIL, RDF.VALUE, RDF.NIL)`
- removing transaction begin/commit is not an option in a real world setting, as the offending code is not necessarily aware of the specific type of the target repository

**Comment by knoan** [comment]
P.S. Possibly relevant also for other repository types…

**Comment by hmottestad** [comment]
> Exception is possibly thrown.

Are exceptions always thrown, or just sometimes? Which exceptions have you seen?

**Comment by knoan** [comment]
> Are exceptions always thrown, or just sometimes? Which exceptions have you seen?

It depends on the endpoint: some will simply ignore the empty update, while other will respond with something like `400 Bad Request`, causing an exception to be always thrown.

**Comment by jeenbroekstra** [comment]
Good find, thanks. I think there are two separate (though obviously related) issues here: the first is the fact that an empty commit string should not be transmitted, the second being that a SPARQL update that is part of a transaction should not be immediately executed, but should be appended. I'll separate that second problem out into its own ticket.
