### ISSUE TITLE
reintegrate test case data from W3C

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#20]
Current integration tests fail because the W3C test case data was not included in the initial contrib. We need to re-integrate this.

**Comment by ansell** [comment]
The most current test cases for the rdf format test suites are in GitHub at:

https://github.com/w3c/rdf-tests

Note that I had not had time to update our testsuites from that set for a while so there may be bugs that you find while integrating the newest versions.

**Comment by jeenbroekstra** [comment]
That's all to the good, I guess :) 

It does mean that I will need to doublecheck with the IP team if they're ok with this - we got approval on an older version, not necessarily on an ongoing development. But I guess that there will be no fundamental problems with that and we can quickly get the thumbs up for it.

**Comment by jeenbroekstra** [comment]
To get things in a buildable/testable state as soon as possible, I'll stick to integrating the 'old' testsuites for now. Will create a followup issue later to look into integrating newer versions.
