### ISSUE TITLE
Documentation on Windows / Netbeans 

### ISSUE THREAD

**Issue by barthanssens** [eclipse/rdf4j#2005]
Add some documentation on Windows development: git config (e.g. cr/lf), running a recent version of maven, working in Netbeans instead of Eclipse etc... 
And double check if all tests work on Windows when starting from scratch (git clone).

**Comment by jeenbroekstra** [comment]
I actually have a Windows machine somewhere in a cupboard. I'll give it a go as well using Eclipse, see what I bump into.
