### ISSUE TITLE
Build on Java 13

### ISSUE THREAD

**Issue by hmottestad** [eclipse/rdf4j#2009]
Since Java 14 is out now we should make sure that our code builds on java 13 (previous version) so that we do not end up too far behind. 

I also propose we switch from java 11 to 13 for our CI. 

We will still require backwards compatibility with have 8. This issue will have no effect on that.

**Comment by barthanssens** [comment]
Hmz, or just build with 14 (since it contains records preview, it may actually be a popular version) ?

**Comment by hmottestad** [comment]
I experienced quite a bit of instability during the first couple of months with java 13 on one of my own projects. One example was test failures in Github Actions, but not locally.

Since we are not using any of the new features in either 9, 10, 11, 12, 13 or now 14 due to having to be backwards compatible with java 8, I think we should let the dust settle around 14 before using it to build our tests.

**Comment by barthanssens** [comment]
FWIW, mvn clean install on dev branch was successful on AdoptOpenJDK 14 64-bit Windows with OpenJ9 VM.

I'm OK with using JDK 13, just wanted to share the good news.

**Comment by hmottestad** [comment]
Then Elasticsearch version we are using isn't compatible with Java 13. Jeen also fixed a final modifier that broke a test on Java 13. I believe you will find the same to be the case for 14. Try building this branch: `hmottestad-patch-1`
