### ISSUE TITLE
Update to Elasticsearch 6.8.x and Lucene to 7.7.x and Solr 7.7.x

### ISSUE THREAD

**Issue by hmottestad** [eclipse/rdf4j#2015]
Elasticsearch 6.8.7 is the latests version compatible with our current version 6.5.4.

Works-with:
- [x] CQ22007 elasticsearch-transport 6.8.7
- [x] CQ22008 elasticsearch-testframework 6.8.7
- [x] CQ22009 lucene-backward-codecs 7.7.2
- [x] CQ22010 lucene-spatial 7.7.2
- [x] CQ22011 solr-core 7.7.2

Normal:
- [x] CQ22012 solr-solrj 7.7.2
  - [x] Apache Commons IO 2.6 (existing CQ18796, PB not needed anymore under new eclipse rules)
  - [x] CQ22025 Apache Commons Math3 3.6.1
  - [x] CQ11713 Apache HTTP Client 4.5.10
  - [x] CQ11718 Apache HTTP Mime 4.5.10
  - [x] Apache Zookeeper 3.4.14 (existing CQ6031, PB not needed anymore under new eclipse rules)
  - [x] CQ16907 Woodstox Stax2-api 3.1.4
  - [x] CQ16906 Woodstox Core ASL 4.4.1
  - [x] CQ22028 Noggit 0.8
  - [x] CQ10578 JCL over Slf4j 1.7.26
- [x] lucene-core 7.7.2 (existing CQ21945, PB not needed anymore under new eclipse rules)
- [x] CQ22013 lucene-analyzers-common 7.7.2
- [x] CQ22014 lucene-highlighter 7.7.2
  - [x] CQ22023 lucene join 7.7.2
  - [x] CQ22022 lucene memory 7.7.2
- [x] CQ22016 lucene-queries 7.7.2
- [x] CQ22017 lucene-queryparser 7.7.2
  - [x] CQ22024 lucene-sandbox 7.7.2
- [x]  CQ22018 lucene-spatial-extras 7.7.2
  - [x] CQ22021 lucene-spatial3d 7.7.2
  - [x] CQ22121 s2-geometry-library-java 1.0.0

**Comment by hmottestad** [comment]
Find all original requests: https://dev.eclipse.org/ipzilla/buglist.cgi?component=technology.rdf4j

What we need:
- Elasticsearch
- Elasticsearch X-Content
 - elasticsearch transport
 - elasticsearch test framework

---
- Apache Solr SolrJ
 - Apache Solr Core

---
- Apache Lucene Core
- Apache Lucene Queryparser
 - Apache Lucene Misc
 - Apache Lucene Highlighter
 - Apache Lucene Join
 - Apache Lucene Memory
- Apache Lucene Backwards Codecs
 - Apache Lucene Queries
 - Apache Lucene Sandbox
 - Apache Lucene Spatial3D
 - Apache Lucene Spatial Extras

## For lucene, this is what we are actually referencing from our POMs

lucene-test-framework
lucene-core
lucene-queries
lucene-highlighter
lucene-analyzers-common
lucene-queryparser
lucene-spatial
lucene-spatial-extras
lucene-backward-codecs

**Comment by hmottestad** [comment]
@jeenbroekstra I've composed a list based on what we have requested before. Before I get started I'm wondering if we still need "Apache Lucene Misc" even though we don't reference it from a pom.xml anymore?

**Comment by jeenbroekstra** [comment]
In the current version, lucene-misc is a transitive dependency of both elasticsearch and solr, both of which are prerequisite dependencies of RDF4J. So yes, unfortunately, we do need that CQ (unless in the new versions of solr and elasticsearch this transitive dependency no longer exists).

**Comment by jeenbroekstra** [comment]
The only way we could change this and save ourselves this chore (for the most part) is if we redefine our dependencies on elasticsearh, solr, and lucene as works-with dependencies (see https://www.eclipse.org/projects/handbook/#ip-third-party for more details). 

A requirement of this, however, is that we mark these depencies as optional in our pom files, so that these dependencies are only included on a user's classpath if they themselves explicitly add them.

**Comment by hmottestad** [comment]
I thought the CQ team checked the transitive dependencies.

**Comment by jeenbroekstra** [comment]
> I thought the CQ team checked the transitive dependencies.

The IP team check only those dependencies for which we log CQs. They're not checking if we've missed applying for any transitive dependencies. It's our job to know and log what third party stuff we use in our project. 

However, part of the pre-release process is that our code base is verified against our IP log (our set of CQs), and any (transitive) dependencies for which no CQ is known is flagged, and this could be a blocker for release.

**Comment by jeenbroekstra** [comment]
Do you need a hand logging the CQs?

**Comment by jeenbroekstra** [comment]
Woops, clicked close accidentally.

**Comment by jeenbroekstra** [comment]
Hang on a sec. I just had a closer look and for rdf4j-sail-elasticsearch, the elasticsearch already appears to be declared as optional. If that is the case and we've done that consistently, it makes our CQ logging a lot easier. 

I'll need to doublecheck that we also do this correctly for Solr and Lucene (and also in the elasticsearch-store), and what the consequences are for the dependencies you have logged here, but if so, it might be a lot easier than I originally thought.

**Comment by jeenbroekstra** [comment]
> @jeenbroekstra I've composed a list based on what we have requested before. Before I get started I'm wondering if we still need "Apache Lucene Misc" even though we don't reference it from a pom.xml anymore?

Getting back to this question of yours, I went back over things, and what I said to your earlier was nonsense. You don't need to log a new CQ for this.

We depend transitively on lucene-misc in three places: 

1. the elasticsearch-compliance tests depend on elasticsearch-testframework, which includes it transitively. We log elasticsearch-testframework as a works-with dependency (we use it, but we don't distribute the compliance tests as part of our releases), so no transitive dependencies need to be logged.
2. the solr-compliance tests depend on solr-core, which includes it transitively. Same story as 1: solr-core should be logged as a works-with dependency. 
3. the rdf4j-elasticsearch-sail-store module depends on the elasticsearch-transport module, which includes it transitively. We do distribute this module of course, _but_ the elasticsearch-transport dependency is declared as optional, and should be logged as a works-with-dependency as well. 

I'll go over your list in a followup comment.

**Comment by jeenbroekstra** [comment]
Actually, looking at your list, at least part of those CQs are from before we made a lot of these dependencies optional - it was a nightmare to maintain that.

What I think we should do for this version bump, for ElasticSearch and Solr:

1. log a `works-with` CQ for elasticsearch-transport 6.8.7
2. log a `works-with` CQ for elasticsearch-testframework 6.8.7
3. log a `works-with` CQ  for solrj-core 7.7.2
4. log a normal CQ for solrj-solrj 7.7.2, which has a couple of transitive dependencies we may need to log CQs for as well - the ones listed for 7.5.0 are these but you may want to check if that changed in the new version:

 ```
 +- org.apache.solr:solr-solrj:jar:7.5.0:compile
[INFO] |  +- commons-io:commons-io:jar:2.6:compile
[INFO] |  +- org.apache.commons:commons-math3:jar:3.6.1:compile
[INFO] |  +- org.apache.httpcomponents:httpclient:jar:4.5.10:compile
[INFO] |  +- org.apache.httpcomponents:httpmime:jar:4.5.10:compile
[INFO] |  +- org.apache.zookeeper:zookeeper:jar:3.4.11:compile
[INFO] |  +- org.codehaus.woodstox:stax2-api:jar:3.1.4:compile
[INFO] |  +- org.codehaus.woodstox:woodstox-core-asl:jar:4.4.1:compile
[INFO] |  +- org.noggit:noggit:jar:0.8:compile
[INFO] |  \- org.slf4j:jcl-over-slf4j:jar:1.7.26:runtime
```

That's it.

For Lucene itself, we need a bit more:

1. log normal CQs for lucene-core 7.7.2 and its transitive dependencies (the older version doesn't have any but check)
2. log normal CQs for lucene-queries 7.7.2 and its transitive dependencies
3. log normal CQs for lucene-highlighter 7.7.2 and its transitive dependencies
4. log normal CQs for lucene-analyzers-common 7.7.2 and its transitive dependencies
5. log normal CQs for lucene-queryparser 7.7.2 and its transitive dependencies
6. log a works-with CQ for lucene-spatial 7.7.2
7. log a works-with CQ for lucene-spatial-extras 7.7.2 (I just noticed that this dependency is currently _not_ defined as optional in the rdf4j-sail-lucene pom, that should be fixed before the next release)
8. log a works-with CQ for lucene-backward-codecs 7.7.2

**Comment by hmottestad** [comment]
I have not taken the time to file any of these. It feels a bit daunting having to file to many CQs.

**Comment by barthanssens** [comment]
if it would help, I can file them tomorrow if you want

**Comment by jeenbroekstra** [comment]
@barthanssens I would really appreciate that, thanks. 

Please ping me as soon as they are approved. And please **do not merge the PR**, even if the CQs are all approved - I will need to respin the IP log for the release to include these, and I will need to make a judgment call on whether we can still get a revised IP log approved in time.

**Comment by barthanssens** [comment]
ok, on it, I'll start with the dependencies listed above and check their dependencies

**Comment by barthanssens** [comment]
@jeenbroekstra just waiting for solr-core (CQ22011) to be approved, and I probably have to file a CQ for s2-geometry 1.0.0 (there is only a CQ for version 1.0.1)

**Comment by barthanssens** [comment]
Looks like all dependencies now have approved CQ's, but perhaps someone could double-check in case I've missed a dependency
