### ISSUE TITLE
SHACL validation reporting improvements - sh:value

### ISSUE THREAD

**Issue by rdstn** [eclipse/rdf4j#2018]
At the moment SHACL error reports can be hard to decipher without access to the whole schema and the data. This may be an issue if users do not have domain knowledge or are interacting with the DB indirectly, via a wrapper API of some sort.

Consider the following shape and data:

```
:ObjectAShape    
  a sh:NodeShape ;    
  sh:targetClass :test ;
  sh:property [
        sh:path :propB ;
        sh:datatype xsd:string ;
        sh:minCount 1 ;
        sh:maxCount 4 ;   
 ] ;    sh:property [
        sh:path ont:propC ;
        sh:maxCount 1 ;
        sh:class :test ; 
]  .
=============

    :shapeA a :test .
    :shapeA :propB 12.1 .
    :shapeA :propC :shapeB .
    :shapeB a :test2 .
```

The problem is that there is no meniton of the value which invalidated the shape. This would return:

```
sh:result [
  a sh:ValidationResult;
  sh:focusNode <http://example.com/data/shapeA>;
  sh:resultPath <http://example.com/data/propB>;
  sh:sourceConstraintComponent sh:DatatypeConstraintComponent;
]  ;
sh:result [
  a sh:ValidationResult;
  sh:focusNode <http://example.com/data/shapeA>;
  sh:resultPath <http://example.com/data/propC>;
  sh:sourceConstraintComponent sh:ClassConstraintComponent;
] .
```

There are two things which can be fetched via inspecting the schema, which is an API call: the source shape and what was the supposed value. It would be ideal if those were included in the validation result to begin with, but it's not a big issue. The supposed value is not part of the standard validation report spec, so it probably must be included as a `sh:resultMessage`.

The problem is supporting `sh:Value` for big updates. In the small example, it is not an issue, but in some cases, we may be looking at tens or hundreds of insertions. Having the violating value also stored in the report would make it easier to debug.

**Comment by hmottestad** [comment]
You mean this? https://www.w3.org/TR/shacl/#results-value

**Comment by hmottestad** [comment]
Related to https://github.com/eclipse/rdf4j/issues/2019

**Comment by rdstn** [comment]
Sure, results value, as per the spec.

Actually, if we are OK with going off spec and implementing it as defined within in #2019, that would be a big improvement.

**Comment by hmottestad** [comment]
That's what I told the SHACL work group 4 years ago 😄

I'm not sure if we should go off spec. We should have that discussion over at #2019.

**Comment by VladimirAlexiev** [comment]
@hmottestad where is the documentation? You added then removed the respective tag, so I assume it was written

**Comment by hmottestad** [comment]
The examples in the documentation was updated with `sh:value`.

https://rdf4j.org/documentation/programming/shacl/#validation-results

The validation report in the link above includes `sh:value`. 

Other than that I just followed the SHACL spec for what node should be used. Which I honestly don't feel is all that intuitive. 

We didn't go any further with more advanced things like actual/expected.
