### ISSUE TITLE
Upgrade MapDB

### ISSUE THREAD

**Issue by barthanssens** [eclipse/rdf4j#2061]
Version 1.0.8 (and even v2) are not supported anymore, so upgrade to v3 or 4

**Comment by barthanssens** [comment]
Another Eclipse project has already got a CQ approved for MapDB 3.0.5 (CQ15650).

As the fine print on the Eclipse IP website mentions, we don't need to file a CQ anymore to piggyback on this approved use.

> Note: There is no longer a requirement to create third party requests for reuse (piggybacks).

**Comment by jeenbroekstra** [comment]
> As the fine print on the Eclipse IP website mentions, we don't need to file a CQ anymore to piggyback on this approved use.

Do you have a link? Anyway that's great to hear, saves a lot of hassle!

**Comment by barthanssens** [comment]
Weird, I'll have to check the Eclipse site and/or mailinglist

But if you go to https://projects.eclipse.org/projects/technology.rdf4j/cq/create, it is mentioned at the bottom (just above the continue button) that a piggyback CQ is not needed anymore

**Comment by jeenbroekstra** [comment]
I guess they just didn't update the handbook yet - it's mostly just Wayne editing that I think. I'll ping them and suggest an update.

**Comment by barthanssens** [comment]
Hmz, expireOverflow is not available for Sets, only for Maps :-(

**Comment by barthanssens** [comment]
After some research, I'd suggest to wait for MapDB 4 (when/if that release becomes available).
MapDB 3 still seems to be slower than version 1 :-/

And for the HDT writer (#232) I'm looking into other options (or stick with 1.0) / rewrite

**Comment by jeenbroekstra** [comment]
I'm taking another look at this because I think there are several features of MapDB 3 that are relevant to us, and if we can keep the performance loss at a minimum, it might be worth the cost.

**Comment by jeenbroekstra** [comment]
@barthanssens is it ok if I "take over" your issue branch for this? That is: I'll rebase it against the latest main / develop and do some measuring.

**Comment by barthanssens** [comment]
> @barthanssens is it ok if I "take over" your issue branch for this? That is: I'll rebase your existing branch against the latest main / develop and do some measuring.

Sure :-)
