### ISSUE TITLE
Create a pretty-printer for Turtle

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#207]
This comes up occasionally: people would like to have the option to 'pretty-print' turtle documents, that is 

- have it use label-less blank nodes where possible
- have it use nested triples where possible 
- have it use short notation for collections

This not possible to do in a streaming writer with uncertain statement ordering/grouping, but a utility that grabs a collection of statements and writes them out in the ideal order could be created to support this.

**Comment by jeenbroekstra** [comment]
Partial implementation now available: label-less blank nodes now supported, but nested triples and shorthand collections not yet.  @ansell should we close this issue and create a followup, or shall we just leave this open for now?

**Comment by ansell** [comment]
Closing is good for me. I will open specific issues for pretty-printing nested triples linked by blank nodes and for collections/lists.
