### ISSUE TITLE
Question: How to get named graph from Full Text search query

### ISSUE THREAD

**Issue by AlexTo** [eclipse/rdf4j#2077]
Hi 

I'm able to use full text query with Lucene (LuceneIndex) but can't figure out how to get the named graph of the subject. Is it also indexed with Lucene.

I've tried to modify the query as follows, to include ?graph but it doesn't show up in the results. Only ?subj and ?text can be found in the results
```
 val qry = "PREFIX search: <http://www.openrdf.org/contrib/lucenesail#> " +
      "SELECT ?subj ?graph ?text " +
      "WHERE { GRAPH ?graph { ?subj search:matches [" +
      " search:query ?term ; " +
      " search:snippet ?text ] }} ";
```

Thanks a lot

**Comment by hmottestad** [comment]
Could you post your question on the support forum?

https://groups.google.com/forum/#!forum/rdf4j-users

Please close this issue when you have done that.

**Comment by AlexTo** [comment]
Thanks, will do
