### ISSUE TITLE
Add import statement sorting to maven build process

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#2093]
See https://code.revelc.net/impsort-maven-plugin/ for a possible additional plugin we can use.

**Comment by jeenbroekstra** [comment]
Added comment to umbrella plugin CQ: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=20318

**Comment by hmottestad** [comment]
+1

**Comment by barthanssens** [comment]
Ow, nice !

**Comment by jeenbroekstra** [comment]
I'm going to be adding this ASAP and not wait for approval - it's more or less academic for these kinds of non-distributed dependencies anyway, and even in the _very_ unlikely event that they find some legal issue with it we can just remove it again without it blocking a release or anything like that.
