### ISSUE TITLE
Propogation of values into subquery

### ISSUE THREAD

**Issue by peterjohnlawrence** [eclipse/rdf4j#2096]
If a LIMIT is added to the subquery in the following SPARQL all subquery results are eliminated. The same does not happen with ORDER BY or OFFSET:

```
select *
WHERE {
	{	SELECT *
		{
			VALUES(?FileFormat_s){(<http://www.nationalarchives.gov.uk/PRONOM/fmt/100>)}
		}
	}
	{
		VALUES(?FileFormat_p){    (<http://www.w3.org/2000/01/rdf-schema#label>)}
    	?FileFormat_s ?FileFormat_p ?FileFormat_o .
	}
	UNION	{
		OPTIONAL{
			{SELECT ?FileFormat_s ?FileFormatfileFormat_FormatIdentifier_s {
					?FileFormat_s <http://data.nationalarchives.gov.uk/formatregistry/def/fileFormat.FormatIdentifier> ?FileFormatfileFormat_FormatIdentifier_s .
        		}  #LIMIT 2
			}
			VALUES(?FileFormatfileFormat_FormatIdentifier_p){(<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)(<http://www.w3.org/2000/01/rdf-schema#label>)}
			?FileFormatfileFormat_FormatIdentifier_s ?FileFormatfileFormat_FormatIdentifier_p ?FileFormatfileFormat_FormatIdentifier_o .
		}
	}
}
```
The LIMIT is commented out in the above example.
Various rearrangements of the query pattern have been tested but all exhibit the same issue.
The issue is the same with version 3.0.0 and 3.1.3

**Comment by hmottestad** [comment]
Could you add some example turtle data for us to be able to reproduce this issue?

**Comment by peterjohnlawrence** [comment]
Not really. I tried to create a very small sample set and unfortunately, maybe, it works as expected. However not in the full database.

```
<http://data.nationalarchives.gov.uk/formatregistry/id/FormatIdentifier/FI-6ffaad09c30216c38c8888e6d6757d2f>
  rdf:type <http://data.nationalarchives.gov.uk/formatregistry/def/FormatIdentifier> ;
  rdfs:label "text/html" ;
.
<http://data.nationalarchives.gov.uk/formatregistry/id/FormatIdentifier/FI-93ba72d72dacb9a35f957af5ed69439c>
  rdf:type <http://data.nationalarchives.gov.uk/formatregistry/def/FormatIdentifier> ;
  rdfs:label "public.html" ;
.
<http://www.nationalarchives.gov.uk/PRONOM/fmt/100>
  rdf:type <http://data.nationalarchives.gov.uk/formatregistry/def/FileFormat> ;
  <http://data.nationalarchives.gov.uk/formatregistry/def/fileFormat.FormatIdentifier> <http://data.nationalarchives.gov.uk/formatregistry/id/FormatIdentifier/FI-6ffaad09c30216c38c8888e6d6757d2f> ;
  <http://data.nationalarchives.gov.uk/formatregistry/def/fileFormat.FormatIdentifier> <http://data.nationalarchives.gov.uk/formatregistry/id/FormatIdentifier/FI-93ba72d72dacb9a35f957af5ed69439c> ;
  rdfs:label "Hypertext Markup Language(4.01)" ;
.
```

I've tried to make this small sample exhibit the same error, but I cannot.

**Comment by peterjohnlawrence** [comment]
My original store which exhibits this problem had a single context with 36 TTL files. 
I created a test store and loaded the TTL that contains the relevant data and executed the query: results were correct, as expected.
I then added all 36 TTL into individual contexts. Now the query fails, so I have to deduce that the issue is triple-volume related.

**Comment by hmottestad** [comment]
I am getting the following output:

#### NativeStore

With limit 2:
```
[FileFormat_o="Hypertext Markup Language(4.01)";FileFormat_p=http://www.w3.org/2000/01/rdf-schema#label;FileFormat_s=http://www.nationalarchives.gov.uk/PRONOM/fmt/100]
```

Without limit:
```
[FileFormat_o="Hypertext Markup Language(4.01)";FileFormat_p=http://www.w3.org/2000/01/rdf-schema#label;FileFormat_s=http://www.nationalarchives.gov.uk/PRONOM/fmt/100]
[FileFormatfileFormat_FormatIdentifier_s=http://data.nationalarchives.gov.uk/formatregistry/id/FormatIdentifier/FI-6ffaad09c30216c38c8888e6d6757d2f;FileFormatfileFormat_FormatIdentifier_o=http://data.nationalarchives.gov.uk/formatregistry/def/FormatIdentifier;FileFormatfileFormat_FormatIdentifier_p=http://www.w3.org/1999/02/22-rdf-syntax-ns#type;FileFormat_s=http://www.nationalarchives.gov.uk/PRONOM/fmt/100]
[FileFormatfileFormat_FormatIdentifier_s=http://data.nationalarchives.gov.uk/formatregistry/id/FormatIdentifier/FI-6ffaad09c30216c38c8888e6d6757d2f;FileFormatfileFormat_FormatIdentifier_o="text/html";FileFormatfileFormat_FormatIdentifier_p=http://www.w3.org/2000/01/rdf-schema#label;FileFormat_s=http://www.nationalarchives.gov.uk/PRONOM/fmt/100]
[FileFormatfileFormat_FormatIdentifier_s=http://data.nationalarchives.gov.uk/formatregistry/id/FormatIdentifier/FI-93ba72d72dacb9a35f957af5ed69439c;FileFormatfileFormat_FormatIdentifier_o=http://data.nationalarchives.gov.uk/formatregistry/def/FormatIdentifier;FileFormatfileFormat_FormatIdentifier_p=http://www.w3.org/1999/02/22-rdf-syntax-ns#type;FileFormat_s=http://www.nationalarchives.gov.uk/PRONOM/fmt/100]
[FileFormatfileFormat_FormatIdentifier_s=http://data.nationalarchives.gov.uk/formatregistry/id/FormatIdentifier/FI-93ba72d72dacb9a35f957af5ed69439c;FileFormatfileFormat_FormatIdentifier_o="public.html";FileFormatfileFormat_FormatIdentifier_p=http://www.w3.org/2000/01/rdf-schema#label;FileFormat_s=http://www.nationalarchives.gov.uk/PRONOM/fmt/100]
```

With limit 9999:
```
[FileFormat_o="Hypertext Markup Language(4.01)";FileFormat_p=http://www.w3.org/2000/01/rdf-schema#label;FileFormat_s=http://www.nationalarchives.gov.uk/PRONOM/fmt/100]
[FileFormatfileFormat_FormatIdentifier_s=http://data.nationalarchives.gov.uk/formatregistry/id/FormatIdentifier/FI-6ffaad09c30216c38c8888e6d6757d2f;FileFormatfileFormat_FormatIdentifier_o=http://data.nationalarchives.gov.uk/formatregistry/def/FormatIdentifier;FileFormatfileFormat_FormatIdentifier_p=http://www.w3.org/1999/02/22-rdf-syntax-ns#type;FileFormat_s=http://www.nationalarchives.gov.uk/PRONOM/fmt/100]
[FileFormatfileFormat_FormatIdentifier_s=http://data.nationalarchives.gov.uk/formatregistry/id/FormatIdentifier/FI-6ffaad09c30216c38c8888e6d6757d2f;FileFormatfileFormat_FormatIdentifier_o="text/html";FileFormatfileFormat_FormatIdentifier_p=http://www.w3.org/2000/01/rdf-schema#label;FileFormat_s=http://www.nationalarchives.gov.uk/PRONOM/fmt/100]
[FileFormatfileFormat_FormatIdentifier_s=http://data.nationalarchives.gov.uk/formatregistry/id/FormatIdentifier/FI-93ba72d72dacb9a35f957af5ed69439c;FileFormatfileFormat_FormatIdentifier_o=http://data.nationalarchives.gov.uk/formatregistry/def/FormatIdentifier;FileFormatfileFormat_FormatIdentifier_p=http://www.w3.org/1999/02/22-rdf-syntax-ns#type;FileFormat_s=http://www.nationalarchives.gov.uk/PRONOM/fmt/100]
[FileFormatfileFormat_FormatIdentifier_s=http://data.nationalarchives.gov.uk/formatregistry/id/FormatIdentifier/FI-93ba72d72dacb9a35f957af5ed69439c;FileFormatfileFormat_FormatIdentifier_o="public.html";FileFormatfileFormat_FormatIdentifier_p=http://www.w3.org/2000/01/rdf-schema#label;FileFormat_s=http://www.nationalarchives.gov.uk/PRONOM/fmt/100]
```

#### MemoryStore
With limit 2:
```
[FileFormat_o="Hypertext Markup Language(4.01)";FileFormat_p=http://www.w3.org/2000/01/rdf-schema#label;FileFormat_s=http://www.nationalarchives.gov.uk/PRONOM/fmt/100]
[FileFormatfileFormat_FormatIdentifier_s=http://data.nationalarchives.gov.uk/formatregistry/id/FormatIdentifier/FI-6ffaad09c30216c38c8888e6d6757d2f;FileFormatfileFormat_FormatIdentifier_o=http://data.nationalarchives.gov.uk/formatregistry/def/FormatIdentifier;FileFormatfileFormat_FormatIdentifier_p=http://www.w3.org/1999/02/22-rdf-syntax-ns#type;FileFormat_s=http://www.nationalarchives.gov.uk/PRONOM/fmt/100]
[FileFormatfileFormat_FormatIdentifier_s=http://data.nationalarchives.gov.uk/formatregistry/id/FormatIdentifier/FI-6ffaad09c30216c38c8888e6d6757d2f;FileFormatfileFormat_FormatIdentifier_o="text/html";FileFormatfileFormat_FormatIdentifier_p=http://www.w3.org/2000/01/rdf-schema#label;FileFormat_s=http://www.nationalarchives.gov.uk/PRONOM/fmt/100]
```

**Comment by hmottestad** [comment]
I believe I understand what is going on.

Your `LIMIT` has no `ORDER BY` so returns two random results. Then your first select limits which `?FileFormat_s` are legal.

An option for you could be to copy `VALUES(?FileFormat_s){(<http://www.nationalarchives.gov.uk/PRONOM/fmt/100>)}` inside your second select as well.

**Comment by peterjohnlawrence** [comment]
Thanks, I think your interpretation is correct, however should not the variable ?FileFormat_s be projected into the sub-select as a pre-bound value. If not how can the variable be projected into the sub-select without repeating the query that binds its value? The reason is that this overall query is greatly simplified: the preliminary query is more complex, and there are multiple sub-selects.

**Comment by hmottestad** [comment]
I usually use this method: https://rdf4j.org/javadoc/latest/org/eclipse/rdf4j/query/Operation.html#setBinding-java.lang.String-org.eclipse.rdf4j.model.Value-

**Comment by hmottestad** [comment]
@jeenbroekstra do you know how to simplify this
```
SELECT * WHERE {
        {
	        SELECT * WHERE {
			VALUES(?FileFormat_s){
			        (<http://www.nationalarchives.gov.uk/PRONOM/fmt/100>)
			}

			# .... some query here

		}
	}

	{
		VALUES(?FileFormat_p) {
		        (<http://www.w3.org/2000/01/rdf-schema#label>)
		}

    	        ?FileFormat_s ?FileFormat_p ?FileFormat_o .


	}

	UNION	{
		OPTIONAL{
			{
			        SELECT ?FileFormat_s ?FileFormatfileFormat_FormatIdentifier_s WHERE {
			                VALUES(?FileFormat_s){
                                	        (<http://www.nationalarchives.gov.uk/PRONOM/fmt/100>)
                                	}

					?FileFormat_s <http://data.nationalarchives.gov.uk/formatregistry/def/fileFormat.FormatIdentifier> ?FileFormatfileFormat_FormatIdentifier_s .
					
        		        }   LIMIT 1
			}

			VALUES(?FileFormatfileFormat_FormatIdentifier_p) {
			        (<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
			        (<http://www.w3.org/2000/01/rdf-schema#label>)
			}

			?FileFormatfileFormat_FormatIdentifier_s ?FileFormatfileFormat_FormatIdentifier_p ?FileFormatfileFormat_FormatIdentifier_o .
		}
	}
}
```

So that there is no need to have this twice:

```
VALUES(?FileFormat_s){
     (<http://www.nationalarchives.gov.uk/PRONOM/fmt/100>)
}
```

Currently it needs to be inside both of the subselects.

**Comment by jeenbroekstra** [comment]
> Thanks, I think your interpretation is correct, however should not the variable ?FileFormat_s be projected into the sub-select as a pre-bound value.

Unfortunately not. The SPARQL recommendation defines evaluation order as bottom-up, which means we can not inject pre-bound values into subselects (or indeed union clauses), as logically speaking the subselect is to be evaluated _before_ the outer part of the query sets the value.

For what it's worth you're not the first to be frustrated by this. 

> If not how can the variable be projected into the sub-select without repeating the query that binds its value? The reason is that this overall query is greatly simplified: the preliminary query is more complex, and there are multiple sub-selects.

The only way I can think of is to manually replace the variable with the fixed value throughout the query, or using the API method that @hmottestad suggested above (I'll take a closer look at why it doesn't work in this case, it should as far as I know - the `setBindings` mechanism is intended to inject values for _every_ occurrence of a variable throughout the query).

For what it's worth, and I realize I say this unburdened by any knowledge of your particular domain or use case, the query you're trying to do looks more complex than it needs to be. If I understand it correctly, the query is intended to retrieve for a particular file format, its label, and if present its fileformat identifier and the label of that identifier. Couldn't this far simpler query achieve the same thing: 
 
```
SELECT *
WHERE {
       VALUES(?FileFormat_s){  (<http://www.nationalarchives.gov.uk/PRONOM/fmt/100>) }
       ?FileFormat_s rdfs:label ?fileFormat_o .
       OPTIONAL {
                  ?FileFormat_s  <http://data.nationalarchives.gov.uk/formatregistry/def/fileFormat.FormatIdentifier> ?FileFormatfileFormat_FormatIdentifier_s .
                  OPTIONAL { 
                      ?FileFormatfileFormat_FormatIdentifier_s  rdfs:label ?FileFormatfileFormat_FormatIdentifier_o .
                   }
        }
}
```

**Comment by jeenbroekstra** [comment]
@hmottestad in looking at why using `setBinding` didnt' work for you, I couldn't reproduce the problem, it seems to work on my machine at least (testing with rdf4j 3.1.3). I've put a gist together:

https://gist.github.com/jeenbroekstra/5c3b9bb29bb474f70e1546ffba373f15

As I understand it, the outcome of that test is what we would expect (5 solutions in total). Could you take a quick glance and see if/how it's different from your attempt?

**Comment by jeenbroekstra** [comment]
Here's a gist with some code that loads the two test files into a native store, and executes the original query minus the VALUES clauses, instead using setBinding to inject the value: https://gist.github.com/jeenbroekstra/96d8c05ec4bbccbde3d329a227a1e6f0

@hmottestad I tried to reproduce the problem you were having with this but as far as I can tell it works as expected: it produces 5 results. Am I overlooking something? Was your test scenario different? Or did I misunderstand your comment?

**Comment by hmottestad** [comment]
:)

Just noticed my typo: `			tupleQuery.setBinding("FileFormat_s", SimpleValueFactory.getInstance().createIRI("http://www.nationalarchives.gov.uk/PRONOM/fmt/100>)"));
`

Forgot the remove the `>)` from the end there.

That's why it wasn't working for me :P 

Thanks @jeenbroekstra !

**Comment by peterjohnlawrence** [comment]
The example query was much reduced from a 'typical' query that is generated for this particular problem. 

The problem that the query is solving is visiting nodes in a graph, then visiting adjacent nodes, and so on, but not indefinitely. 

The first part of the query assemblies the 'start nodes' and picks up any datatype properties of those nodes.  The UNIONs then visit adjacent nodes, as defined by objectProperty edges, and then repeat the same. However to avoid a result-set explosion we only want to pick up a limited number of adjacent nodes, hence the LIMIT clause, but we want a count of the total number of nodes that were available, hence the aggregate select. We also limit how far removed from the original nodes we travel.

I have attached a fully formed query: please use coffee or something stronger before viewing this query as it might cause you consternation. Let me say before you look at it, RDF4J performs **incredibly well** and can easily handle queries of this complexity.

Since these queries are autogenerated it is possible to organize them in any, more optimal, way. However, as I saw these queries as typical nested-joins, I had not anticipated a query problem. I could even perform the graph iteration in code, but 'why buy a dog (SPARQL) then bark (Java) yourself':-)

Open to any suggestions.

BTW any easy access to the query plan that RDF4J is using in these cases?
[Actual Query.txt](https://github.com/eclipse/rdf4j/files/4491667/Actual.Query.txt)

**Comment by hmottestad** [comment]
We have an issue tracking work on making the query plans available: https://github.com/eclipse/rdf4j/issues/2044

Still in the design phase though.

I think it's great you are getting good performance out of RDF4J. I usually prefer somewhat complicated queries to writing Java code. Sometimes I will run into performance bottlenecks, at which point I may end up splitting a query into multiple queries and feeding the results from one into the next.

**Comment by jeenbroekstra** [comment]
Thanks @peterjohnlawrence, both for the kind words and for the background on why your queries are formed the way they are. That query is quite a beast, I must say! 

I'm afraid that the conclusion is that if you need to inject values into your query via a VALUES clause, you will have to make sure that this happens in multiple places so that the bindings are in scope. In particular, patterns that change the scope are UNION clauses, subselects, as well as any group of patterns that you put in curly braces. 

That being said, the eventual outcome of a query will likely not be different if you put the values clause in the outer scope, except in some very specific corner cases: one such case is your example, where a LIMIT is used to drop part of the solutions in the inner query. Another example would be if you did something like a BIND in your inner query, using the VALUES clause variable as the input.

**Comment by peterjohnlawrence** [comment]
Thanks for all of the clarifications
