### ISSUE TITLE
Additional vocabularies

### ISSUE THREAD

**Issue by barthanssens** [eclipse/rdf4j#211]
Hi,

just wondering if someone would be interested in additional vocabulary classes (org.eclipse.rdf4j.model.vocabulary package).

I'm working on a few small tools that use W3C Organization, Registered Organization, DCAT, VoID, so I'd be happy to contribute them if this would be useful.

**Comment by jeenbroekstra** [comment]
Thanks Bart, we'd definitely welcome your contribution! Please have a look at the [contributor guidelines](https://github.com/eclipse/rdf4j/blob/master/.github/CONTRIBUTING.md), in particular the point on how to sign the Eclipse CLA and how pick the right branch etc. Let me know if you need any help with any of it.
