### ISSUE TITLE
Group statement adds together in single INSERT DATA in SPARQLConnection

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#2121]
SPARQLConnection handles transaction by serializing updates to a sequence of SPARQL update operations. However, it treats each statement add/remove as a separate update, resulting in update sequences with a separate INSERT DATA clause for each triple. This is highly inefficient. 

A possible fix is to cache pending added/removed statements and only flush them to a serialized INSERT DATA operation when necessary.

**Comment by hmottestad** [comment]
On this note I think adding triple "A" in a transaction, then removing triple "A" again in the same transaction should be simplified to a no-op in the cases were there are no prior or subsequent updates or read queries.

**Comment by jeenbroekstra** [comment]
> On this note I think adding triple "A" in a transaction, then removing triple "A" again in the same transaction should be simplified to a no-op in the cases were there are no prior or subsequent updates or read queries.

I see what you're getting at, but given that the approach is to flush all added statements as soon as a remove comes in, we gain very little: only if the first statement in the remove batch happens to match one of the pending adds could we optimize, and even then we only optimize by only scrapping _one_ triple. I think the additional complexity in this case is not really worth it.

**Comment by hmottestad** [comment]
Ok
