### ISSUE TITLE
Refactor manifest testsuites 

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#2149]
The various manifest test suites (for SPARQL compliance, for example) still using Junit 3 constructions to create the suite. A major drawback is that because of the way the individual tests are created and run, it is virtually impossible to efficiently debug a single case. 

We should look into a more efficient test suite setup using parametrized tests.

**Comment by barthanssens** [comment]
is this related to #1563 ?

**Comment by jeenbroekstra** [comment]
Not necessarily - we can already make the manifest tests a lot easier to use in JUnit 4. I've already put some new code in place when I was doing fixes for named graph support in FedX - I now mostly need to find the time to apply it to the other testsuites and then phase out the antiquated junit3-based manifest tests.
