### ISSUE TITLE
Add BindingSets util for quick convenience processing of tuple query results

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#2158]
For example to quickly get all values for one particular variable out of a query result.

**Comment by navdhaagarwal** [comment]
Hi, 
We (Me and @shubhi0108) would like to work on this issue. Can you please elaborate more on the issue. We know that when the query is evaluated, the result goes in TupleQueryResult, and then in order to get the values we can iterate over the result to get BindingSets for each row. Now, how do we want to processes the tuples further?

**Comment by jeenbroekstra** [comment]
Sure thing! The idea for this issue was to have a new convenience function for working with tuple query results. I originally thought a separate BindingSets class, but thinking about it a bit more, I think adding a function to the QueryResults util makes more sense.

For example, I'd like to be able to do something like this:

     String query = "SELECT ?x ?y ?z { ?x ?y ?y }";
    TupleQueryResult result = conn.prepareTupleQuery(query).evaluate();

     List<Value> valuesOfX = QueryResults.getAllValues(result, "x");

so that `valuesOfX` would contain _all_ values for variable `?x` produced by the query.

Of course you can do this kind of thing already using a stream and a lambda:  

      List<Value> valuesOfX = result.stream().map(bs -> bs.getValue("x")).collect(Collectors.toList());

I'll be honest by the way that when I first wrote this issue I hadn't considered that it's already pretty easy to what I wanted using lambdas and streams, so there is less urgency for this. But a util function makes it a little bit easier, so it's still a useful addition.

**Comment by jeenbroekstra** [comment]
Great that you want to contribute by the way. Before you get started, please have a look at the [contributor guidelines](https://github.com/eclipse/rdf4j/blob/master/.github/CONTRIBUTING.md), in particular the points on how to sign the Eclipse ECA, and how to do commits and pull requests. Let me know if you need any help with any of it.

**Comment by navdhaagarwal** [comment]
Hi, 
We have added the asked function and a test for the same. According to our implementation, the function `getAllValues()` returns `null` when the user enters the binding element that does not exist in the result. Should there be some exception thrown or returning `null` is fine?

**Comment by jeenbroekstra** [comment]
> We have added the asked function and a test for the same. According to our implementation, the function `getAllValues()` returns `null` when the user enters the binding element that does not exist in the result. Should there be some exception thrown or returning `null` is fine?

I wouldn't throw an exception, but perhaps you can return an empty list instead of null?

**Comment by navdhaagarwal** [comment]
Hi, 
Please let me know whether some work in left regarding this issue.
Thanks

**Comment by jeenbroekstra** [comment]
All good, thanks. Normally issues close automatically when the PR is merged, not sure why this one didn't. Closing now to mark resolved.
