### ISSUE TITLE
Re-Include ManifestTest and testcases-dawg

### ISSUE THREAD

**Issue by pulquero** [eclipse/rdf4j#216]
This set of testcases was in the 4.0/master branch of sesame in sparql-testsuite but have now gone from rdf4j.

**Comment by jeenbroekstra** [comment]
They weren't reinserted because I considered them superceded by the sparql 1.1 testcases.

**Comment by pulquero** [comment]
I believe there are some important cases covered in dawg that are not present in sparql 1.1. Particularly the var-scope-join and OPTIONAL tests (I couldn't find many OPTIONAL tests in sparql 1.1 testcases). I think they are worth reconsidering for inclusion - they certainly have helped me find and detect bugs that I don't think I would have found otherwise.

**Comment by jeenbroekstra** [comment]
Fair point. We'll need a legal review on the material though and I don't want to have that hold up the 2.0 release - so I suggest we schedule this for inclusion in 2.1 instead.

**Comment by ansell** [comment]
Is there an issue open yet for updating all of the test cases from https://github.com/w3c/rdf-tests as some of the Rio testcases may have also drifted out of date since the last time I updated them?

**Comment by jeenbroekstra** [comment]
I completely forgot about this. Will file a CQ right away to see if we can get this in. If that can't be cleared in time we may have to postpone this further. 

@ansell I don't think we have an issue for that yet - feel free to open one.

**Comment by ansell** [comment]
Done, see issue #587

**Comment by jeenbroekstra** [comment]
CQ logged: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=12023

**Comment by jeenbroekstra** [comment]
Similar to what I said in #587 I will also have a look at using on-the-fly access to the website, rather than putting a dump of the test suite in our repo.

**Comment by jeenbroekstra** [comment]
CQ has been approved.
