### ISSUE TITLE
Parent link in QueryModelNode is set wrong in some cases

### ISSUE THREAD

**Issue by hmottestad** [eclipse/rdf4j#2187]
The parent link in QueryModelNode is set wrong in some cases when we reuse a node without cloning it first.

**Comment by hmottestad** [comment]
See https://github.com/eclipse/rdf4j/pull/2180 for example of failures.

**Comment by jeenbroekstra** [comment]
Can you point to somewhere where we reuse a node without cloning it first, or perhaps a particular example of a query where optimizing/evaluating results in the parent nodes being out of date? I've briefly gone over how some of our optimizers replace and move nodes, and from what I can tell they're fairly conscientious about the book keeping.
