### ISSUE TITLE
Upgrade JSON-LD and Jackson

### ISSUE THREAD

**Issue by barthanssens** [eclipse/rdf4j#2192]
Upgrade to 0.13.0, which uses jackson 2.10.

- [x]  CQ 22136, JSON-LD Java

Jackson core, databind and annotation already covered by  CQ21186, CQ21187 and CQ21280

As mentioned on the forum (https://groups.google.com/forum/#!topic/rdf4j-users/231Y18nIRLc), Jackson 2.9.x has a few open CVE issues (which may or may not have impact on RDF4J)

**Comment by barthanssens** [comment]
Bit puzzled why the test sometimes work on jenkins and sometimes don't, looking into it

**Comment by jeenbroekstra** [comment]
Given that this is merged, I think we can close it.
