### ISSUE TITLE
Graphviz DOT based query plans

### ISSUE THREAD

**Issue by hmottestad** [eclipse/rdf4j#2208]
Output plans in Graphviz DOT format. Use colors to highlight slow nodes.

**Comment by hmottestad** [comment]
Example.

![graphviz](https://user-images.githubusercontent.com/797185/81484347-1b801900-9245-11ea-9162-540cbd79fa38.png)

**Comment by hmottestad** [comment]
@jeenbroekstra @barthanssens what do you guys think of this?

**Comment by barthanssens** [comment]
Looks very, very nice !
