### ISSUE TITLE
Models in Changeset not protected against concurrent access

### ISSUE THREAD

**Issue by hmottestad** [eclipse/rdf4j#2209]
The MultithreadedNativeStoreTest for the ShaclSail has unearthed another race condition in the Changeset.

Changesets are shared among threads, which means that they need to be thread safe. Changesets use models, which are inherently not thread safe. Models will now apparently also throw ConcurrentModificationExceptions on concurrent reads with single writers. 

This bug is hard to trace down because of a number of issues.

1. It almost never happens
1. Changeset#setChangeset does not clone models, so we don't know if the same model is used between Changesets
1. Changeset#getApproved returns the actual model to an outside scope, which means we loose any synchronization ability

**Comment by hmottestad** [comment]
<img width="1183" alt="Screenshot 2020-05-10 at 21 16 45" src="https://user-images.githubusercontent.com/797185/81508634-78db9f00-9305-11ea-8e38-78ae3fa7bb64.png">

**Comment by jeenbroekstra** [comment]
Thanks for analyzing this. Changeset itself looks to be thread-safe. Would a fix be as simple as making sure the private Models in Changeset are never directly shared, but always cloned? I imagine this will cost performance, but it seems a relatively simple thing to do.

**Comment by hmottestad** [comment]
I think we should do two things. One is to remove the ability to retrieve the models. Instead introduce methods for the required interaction. Second is to make all interaction with the models synchronized. 

We also have to figure out why you can instantiate a changeset from another changeset and how that affects thread safety.
