### ISSUE TITLE
SPARQLRepository setBindings fails when query has GROUP BY

### ISSUE THREAD

**Issue by abrokenjester** [eclipse/rdf4j#2212]
The string replacement strategy SPARQLREpository uses to process bindings added programmatically to a query fails if the query involves a GROUP BY clause. 

For example, this query:

```
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT DISTINCT ?foo ?bar (COUNT(?bar) as ?c)
WHERE { 
        ?foo rdf:type ?bar .
} GROUP BY ?foo ?bar
```

When `?foo` is set using `TupleQuery.setBinding` to a value `http://example.org/foo`  the query becomes:

```
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT DISTINCT (<http://example.org/foo> as ?foo) ?bar (COUNT(?bar) as ?c)
WHERE { 
        <http://example.org/foo> rdf:type ?bar .
} GROUP BY <http://example.org/foo> ?bar
```

A fixed value in the GROUP BY clause is not valid SPARQL.

A possible fix is, to make sure the binding of the fixed value to the alias happens as part of the WHERE clause, and then let both the SELECT and GROUP BY clause remain as-is:

```
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT DISTINCT ?foo  ?bar (COUNT(?bar) as ?c)
WHERE { 
        BIND(<http://example.org/foo> as ?foo)
        <http://example.org/foo> rdf:type ?bar .
} GROUP BY ?foo ?bar
```
Note that we still replace all other occurrences of `?foo` in the WHERE clause, to deal with scoping issues in a consistent manner (the RDF4J `setBinding` mechanism is intended to be globally scoped).

**Comment by jeenbroekstra** [comment]
A closely related issue is that it doesn't deal with subselects correctly either - it replaces variable occurrences in the subselect's SELECT clause with just the value. This is not legal syntax as a select clause can only contain expressions or variables, not fixed values.

**Comment by jeenbroekstra** [comment]
I am at this point unsure if we should try and fix this utility, or if we should get rid of this string manipulation approach entirely and instead just properly parse the query, inject bindings at the algebra level, and then re-render. 

A third alternative is that we accept that scoping issues are a problem for this approach, and just stick with using a VALUES clause and not replacing any variable occurrences. This will work fine except in rare corner cases, e.g. where a subselect involves a LIMIT clause. 

To me personally, both string manipulation approaches feel like a workaround, not a proper fix, but I realize that getting full round-trip parsing and rendering working is not straightforward either.
