### ISSUE TITLE
website: fix link in release doc

### ISSUE THREAD

**Issue by barthanssens** [eclipse/rdf4j#2223]
Under heading Minor and Major release, links to project site and issue tracker are incorrect

**Comment by jeenbroekstra** [comment]
@barthanssens thanks for fixing this. Just as a heads up - unfortunately moving a card to the 'Done' column on the project board doesn't automatically close the issue. It only works the other way around: when you close the issue, it moves to the 'Done' column.

**Comment by barthanssens** [comment]
Ok, thanks, I’ll keep that in mind
