### ISSUE TITLE
release notes for rdf4j 3.3.0

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#2235]
Task to keep track of what needs to go into next release notes. 

See release milestone at https://github.com/eclipse/rdf4j/milestone/51

**Comment by jeenbroekstra** [comment]
PR up at https://github.com/eclipse/rdf4j-doc/pull/161

**Comment by reeshabhkumarranjan** [comment]
Hey @jeenbroekstra , here are our names:
me: Reeshabh Kumar Ranjan
@guvi007: Gaurav Agarwal
@prince17080: Prince Sachdeva

**Comment by SakshiSaini17092** [comment]
Hey @jeenbroekstra,
@SakshiSaini17092 : Sakshi Saini
@gauri-b : Gauri Bhatanagar
@raghav17083: Raghav Rathi

**Comment by barthanssens** [comment]
Thanks for your help, I've added the names to https://github.com/eclipse/rdf4j-doc/pull/161/files

**Comment by navdhaagarwal** [comment]
Hi @barthanssens .
@navdhaagarwal : Navdha Agarwal
@shubhi0108 : Shubhi Jain

**Comment by barthanssens** [comment]
Thank you, I've added your names to the release notes

**Comment by jeenbroekstra** [comment]
To do: add some notes about new transaction settings, new function interface, and other new features

**Comment by hmottestad** [comment]
Also update the SHACL example that explains how to validate large transactions (bulk).
