### ISSUE TITLE
Wrong generation of a Describe SPARQL query using QueryBuilderFactory.describe() for multiple resources

### ISSUE THREAD

**Issue by aantakli** [eclipse/rdf4j#226]
Hallo everybody,
by using QueryBuilderFactory.describe() to describe two input Resources I would expected a Describe query like the following:

`describe <http://example.org#something1> <http://example.org#something2>`

or 

```
construct{ ?descr_subj ?descr_pred ?descr_obj . } 
where{ ?descr_subj ?descr_pred ?descr_obj .
filter( sameTerm(<http://example.org#something1>, ?descr_subj ) ||
         sameTerm(<http://example.org#something1>, ?descr_obj ) ||
         sameTerm(<http://example.org#something2>, ?descr_subj ) ||
         sameTerm(<http://example.org#something2>, ?descr_obj ))).
 }
```

Instead, QueryFactoryBuilder.describe(Resources..) generates a query like the following, which does not work to describe multiple Resources.

```
construct{ ?descr_subj ?descr_pred ?descr_obj . } 
where{ ?descr_subj ?descr_pred ?descr_obj .
filter( sameTerm(<http://example.org#something1>, ?descr_subj ) ||
         sameTerm(<http://example.org#something1>, ?descr_obj )) .
filter( sameTerm(<http://example.org#something2>, ?descr_subj ) ||
         sameTerm(<http://example.org#something2>, ?descr_obj )).
 }
```

**Comment by jeenbroekstra** [comment]
We introduced a `DescribeOperator` into the algebra some time back, but it looks as if the QueryBuilder doesn't use it yet.

**Comment by jeenbroekstra** [comment]
`QueryBuilderFactory` has been deprecated in favor of the new SparqlBuilder module.

**Comment by woutermont** [comment]
> `QueryBuilderFactory` has been deprecated in favor of the new SparqlBuilder module.

It seems like `SparqlBuilder` does not provide the means to build a DESCRIBE query either (and neither does `Queries`). Am I missing something, or should this issue be reopened/renamed?
