### ISSUE TITLE
ModelBuilder adds xsd namespace when not necessary

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#2260]
When using ModelBuilder to create a Model, it automatically adds namespaces from a specified set of known ones when it detects they are needed.

However, it is slightly over-zealous: it adds the xsd namespace when any literal value is added, even if that literal is just a string (in which case we don't really need the xsd namespace present). 

Possible fix: in `ModelBuilder.add` (line 202) add a check before adding the namespace, to see if the supplied object value is a  literal with an xsd datatype.

**Comment by reeshabhkumarranjan** [comment]
@jeenbroekstra can me, @prince17080 and @guvi007 work on this issue?

**Comment by jeenbroekstra** [comment]
Please, go for it!
