### ISSUE TITLE
release notes for 3.2.2

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#2269]
Task to keep track of what needs to go into next release notes.

See release milestone at https://github.com/eclipse/rdf4j/milestone/53

**Comment by ishaanbassi** [comment]
Hey @jeenbroekstra, following are the details of my team who have worked on issue #399 via pull request #2248 which has been merged.
me : Ishaan Bassi
@Kvatsx : Kaustav Vats
@abhishekag03 : Abhishek Agarwal

**Comment by barthanssens** [comment]
I've created a first version of the notes, with the names in alphabetical order (like the upcoming 3.3.0 release notes)

**Comment by deepali17043** [comment]
The details of our team that worked on issue #543  (changes merged to master from the pull request #2290) are as follows:
@anmolsinghal98 - Anmol Singhal
@29kritika - Kritika Venkatachalam
@deepali17043  - Deepali Chawla
