### ISSUE TITLE
XMLSchema not found

### ISSUE THREAD

**Issue by hmottestad** [eclipse/rdf4j#2271]
Currently getting this build error for my branch:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:testCompile (default-testCompile) on project rdf4j-shacl: Compilation failure
4756
[ERROR] /home/runner/work/rdf4j/rdf4j/core/sail/shacl/src/test/java/org/eclipse/rdf4j/sail/shacl/AbstractShaclTest.java:[298,30] error: cannot find symbol
4757
[ERROR]   symbol:   variable XMLSchema
4758
[ERROR]   location: class AbstractShaclTest
4759
[ERROR] -> [Help 1]
4760
[ERROR] 
4761
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
4762
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
4763
[ERROR] 
4764
[ERROR] For more information about the errors and possible solutions, please read the following articles:
4765
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
4766
[ERROR] 
4767
[ERROR] After correcting the problems, you can resume the build with the command
4768
[ERROR]   mvn <args> -rf :rdf4j-shacl
4769
##[error]Process completed with exit code 1.
```

@jeenbroekstra is maybe using `extends` making the old XMLSchema class incompatible with the pervious implementation of that class?

**Comment by hmottestad** [comment]
Build failure: https://github.com/eclipse/rdf4j/pull/2229/checks?check_run_id=708561487

**Comment by jeenbroekstra** [comment]
This looks odd to me. As far as I know this kind of change should normally be binary compatible (a giveaway is also that none of our compatibility checkers failed).

**Comment by jeenbroekstra** [comment]
The only thing I can think of is that your branch is perhaps not fully rebased against develop, and because on develop I replaced the use of XMLSchema with XSD in that file, the CI build gets confused when it tries to do the merge build.

**Comment by jeenbroekstra** [comment]
I left a comment on your PR which I _hope_ explains what the problem is and how you can fix.
