### ISSUE TITLE
Site: broken images and numbering

### ISSUE THREAD

**Issue by barthanssens** [eclipse/rdf4j#2318]
Broken images on https://rdf4j.org/documentation/tutorials/getting-started/#introducing-rdf

And the line numbering in the code examples (e.g. Example 01: building a simple Model) is broken, at least when the line number is 10 or more (i.e. '1' and '0' on different lines)

(viewed on Windows 10 in Chrome and IE)

**Comment by jeenbroekstra** [comment]
Thanks for reporting, I'll take a quick look (I want to give that tutorial a bit of an update anyway).
