### ISSUE TITLE
Unicode in IRI fails parsing

### ISSUE THREAD

**Issue by elad-shaked** [eclipse/rdf4j#2323]
Though https://github.com/eclipse/rdf4j/pull/2316 fixed `unread`ing of unicode surrogates, parsing fails down the line.
For example, this fails:
```
new ParsedIRI("A:￼")
``` 
(The IRI to be parsed above contains an char right after the colon that does noprint in Github - copy pasting works well though)

This fails when a call is being made to `AbstractRDFParser.createURI` which makes sense as unicode is not allowed in URIs - but I am baffled as to why the IRI is forced into a URI

**Comment by jeenbroekstra** [comment]
It's a little hard to figure out from this example what's going on. Copy-pasting seems to just give me a whitespace. What unicode char (unicode number) are you passing in? And how is the character encoded? Also: what error does the parser give you?

The method name `createURI` is misleading. It's named that way for historic reasons (it predates the introduction of IRIs). So we are not converting/forcing the IRI into a URI here.

**Comment by elad-shaked** [comment]
Here is the char: https://en.wiktionary.org/wiki/%EF%BF%BC
And I isolated the "A:[char that is not printable]" string in a file with `hexdump`:
```
0000000 41 3a ef bf bc 0a
0000006
```
Which seems fine according to https://charbase.com/fffc-unicode-object-replacement-character: `ef bf bc`.
(The `oa` appears at the end of every file).

**Comment by jeenbroekstra** [comment]
Ah. The character in question is U+FFFC, which is a character from the "Specials" block of the Unicode standard. This block of characters is not allowed to occur un-encoded in an IRI, see RFC 3987 (https://tools.ietf.org/html/rfc3987#section-2.2):

```
   ucschar        = %xA0-D7FF / %xF900-FDCF / %xFDF0-FFEF
                  / %x10000-1FFFD / %x20000-2FFFD / %x30000-3FFFD
                  / %x40000-4FFFD / %x50000-5FFFD / %x60000-6FFFD
                  / %x70000-7FFFD / %x80000-8FFFD / %x90000-9FFFD
                  / %xA0000-AFFFD / %xB0000-BFFFD / %xC0000-CFFFD
                  / %xD0000-DFFFD / %xE1000-EFFFD
```

Note that the specials block ( %xFF00 - %xFFFF)  is not covered by this range. So this is not a legal character to include in an IRI in unescaped form.

**Comment by elad-shaked** [comment]
Thanks for the clarification. So now the question is what should happen once such a char is encountered. Currently an exception is thrown and parsing is halted. Ideally a parser configuration to control this should be in place, as we can still parse the statement and mark it as illegal (passing it to some handler perhaps)

**Comment by jeenbroekstra** [comment]
Rio allows you to disable IRI syntax validation (see https://rdf4j.org/documentation/programming/rio/#configuring-the-parser--writer). You can also configure to still verify but not treat it as a fatal error.
