### ISSUE TITLE
rdf4j-workbench does not search repository templets in $RDF4J_DATA/templates

### ISSUE THREAD

**Issue by jgrzebyta** [eclipse/rdf4j#234]
It would be helpful if **rdf4j-workbench**  webapp search new custom templates in  `$RDF4J_DATA/templates/` and add to the list of possible types into the drop down  _Type:_ field in the _/create_ page. 

Particularly I have config file for native and memory repositories with the Lucene index which I   'instantiate' by sending the `.ttl` file into **System** repository.

**Comment by jeenbroekstra** [comment]
Unfortunately the way this is currently set up makes it difficult to do this - workbench requires not just a template file, but also an xsl file for each template - so it's hard to make this dynamic in the current design.

I agree though that it would a great enhancement if we could make this properly dynamic so people can just 'drop in' templates.
