### ISSUE TITLE
Fail to create Rio parser for JSONLD

### ISSUE THREAD

**Issue by swc-kdzekov** [eclipse/rdf4j#2352]
Hi all,

Recently I found that the creation of Rio parser for some data formats (jsonld, trix) fails. 
I'm using rdf4j 3.2.0, but also, i observed this on rdf4j 3.1.4. 
I just use this command:

RDFParser parser = Rio.createParser(RDFFormat.JSONLD);

As for the jsonld library I initially used com.github.jsonld-java version 0.10.0, but also, the same happens for the version 0.13.0.

What I got in the log is:
"java.lang.NoClassDefFoundError: com/github/jsonldjava/core/JsonLdError
org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: com/github/jsonldjava/core/JsonLdError"

P.s in the older version of the application I'm working, where rdf4j 2.3.3 is used, this problem does not appear.

**Comment by barthanssens** [comment]
Could you provide some more information on your application (e.g. pom.xml or gradle) ? 
It seems like a missing dependency... have you included the `rdf-rio-jsonld` artifact ?

**Comment by swc-kdzekov** [comment]
In the meantime I tried with included "rdf-rio-jsonld" as dependency. I set the related jar file in the classpath as well (tomcat lib folder). Still i get the same runtime error.
I use maven pom file. This is the file:
[pom.zip](https://github.com/eclipse/rdf4j/files/4889972/pom.zip)

**Comment by barthanssens** [comment]
Hmz, what happens if you build a small "hello-world" like (command line jar, not a war in an application server) RDFParser application, with only the rdf4j-rio-jsonld as explicit dependency in the pom, does that work ?
Manually including (just) rdf4j-rio-jsonld should also automatically include the rdf4j-model, rdf4j-rio-api and jsonld-java dependencies...

It could be Tomcat issue, e.g. Tomcat not picking up the libraries while running, or some older version of jsonld-java in the classpath...

**Comment by swc-kdzekov** [comment]
Hi, i tried small console application and i had to include these dependencies to work:
`<dependency>
               <groupId>org.eclipse.rdf4j</groupId>
               <artifactId>rdf4j-core</artifactId>
               <version>3.2.0</version>
               <type>pom</type>
           </dependency>
             <dependency>
                  <groupId>org.eclipse.rdf4j</groupId>
                  <artifactId>rdf4j-rio-api</artifactId>
                  <version>3.2.3</version>
              </dependency>
            
              <dependency>
                  <groupId>org.eclipse.rdf4j</groupId>
                  <artifactId>rdf4j-rio-jsonld</artifactId>
                  <version>3.2.3</version>
              </dependency>`

However, having these dependencies on my web project (which is large , containing multiple modules) does not work. It simply can not instantiate "new JSONLDParser();".  :(

**Comment by barthanssens** [comment]
(Minor detail perhaps, the pom of the console app contains different versions (3.2.0 and 3.2.3) of rdf4j modules.

Ok, and still the same ClassNotFound error in Tomcat (version 7, if I understood the POM correctly)  ?
Since the command line app works, it really looks like a Tomcat or a war issue, though I'm not an Tomcat expert ...
The shared tomcat lib would be the  $CATALINA_BASE/lib or  $CATALINA_HOME/lib ?

I'd suggest to:

- first remove the explicit reference to jsonld-java 0.13.0 from the pom, since including `rdf4j-rio-jsonld` should implicitly add jsonld-java (0.12.x)
- build the war, but not deploy it
- check if the jars + libraries are present in the war (copy the war and unzip it to look at the contents, IIRC there should be a WEB-INF/lib containing the jars, jsonld-java 0.12 should be in it), if that's not the case then it looks like a maven-war-plugin issue
- check for conflicting versions of jsonld-java: maybe the other dependencies drag in an older version of jsonld-java as well, in that case the conflict should be resolved (use e.g. mvn `dependency:tree -Dverbose` to check)
- if there is only 1 jsonld-java jar, check the version (0.12.x when using rdf4j 3.2.x) unzip it to see if it indeed contains the `com/github/jsonldjava/core/JsonLdError` class
- if all of the above is OK, it is yet another issue... (in that case a longer log might be useful)

**Comment by swc-kdzekov** [comment]
Hello @barthanssens , thanks for helping me. 

[first remove the explicit reference to jsonld-java 0.13.0 from the pom, since including rdf4j-rio-jsonld should implicitly add jsonld-java (0.12.x)]
I did.

[build the war, but not deploy it]
built.

[check if the jars + libraries are present in the war (copy the war and unzip it to look at the contents, IIRC there should be a WEB-INF/lib containing the jars, jsonld-java 0.12 should be in it), if that's not the case then it looks like a maven-war-plugin issue]
The necessary libraries are present. Including jsonld-java-0.12-5.jar. 

[check for conflicting versions of jsonld-java: maybe the other dependencies drag in an older version of jsonld-java as well, in that case the conflict should be resolved (use e.g. mvn dependency:tree -Dverbose to check)]
No conflicting jsonld-java files.

[if there is only 1 jsonld-java jar, check the version (0.12.x when using rdf4j 3.2.x) unzip it to see if it indeed contains the com/github/jsonldjava/core/JsonLdError class]
Yes, the jar file (jsonld-java-0.12.5.jar) contains com/github/jsonldjava/core/JsonLdError class.

Still, JSONLDParser fails to be created with the same error message. I increased the log level (in log4j2.properties) to trace. What I'm getting is this:

> 2020-07-09 17:15:50 [ERROR] FrontendControllerBase [POST] /PoolParty/!/import - Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: com/github/jsonldjava/core/JsonLdError
org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: com/github/jsonldjava/core/JsonLdError
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1055) [spring-webmvc-5.1.15.RELEASE.jar:5.1.15.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943) [spring-webmvc-5.1.15.RELEASE.jar:5.1.15.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) [spring-webmvc-5.1.15.RELEASE.jar:5.1.15.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) [spring-webmvc-5.1.15.RELEASE.jar:5.1.15.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:688) [javax.servlet-api-3.0.1.jar:3.0.1]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) [spring-webmvc-5.1.15.RELEASE.jar:5.1.15.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:770) [javax.servlet-api-3.0.1.jar:3.0.1]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) [catalina.jar:7.0.77]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.77]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat7-websocket.jar:7.0.77]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.77]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.77]
	at biz.poolparty.thesaurus.notification.frontend.MessageHandlerFilter.doFilter(MessageHandlerFilter.java:72) [classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.77]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.77]
	at biz.poolparty.thesaurus.web.support.filter.SpringLocaleFilter.doFilter(SpringLocaleFilter.java:35) [classes/:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.77]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.77]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320) [spring-security-web-5.1.10.RELEASE.jar:5.1.10.RELEASE]

**Comment by barthanssens** [comment]
Weird... any idea of the Java version Tomcat is using ?

**Comment by swc-kdzekov** [comment]
It is in the class loading after all. I created very basic web application (maven, spring) with one test controller, where i test the creation of jsonld parser. I set the same dependencies as for the console application and the code breaks on:

> RDFParser parser = Rio.createParser(RDFFormat.JSONLD);

The stack trace that I got is:

> root cause
java.lang.ClassNotFoundException: com.github.jsonldjava.core.JsonLdError
	java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	eclipse.rdf4j@3.2.0-onejar/org.eclipse.rdf4j.rio.jsonld.JSONLDParserFactory.getParser(JSONLDParserFactory.java:28)
	eclipse.rdf4j@3.2.0-onejar/org.eclipse.rdf4j.rio.Rio.createParser(Rio.java:98)
	com.controll.TestController.getTestData(TestController.java:25)

The question here is, how would i change the class loading (Tomcat 7, using java 11)?
I found a solution but not for Tomcat. It should probably something like: https://www.win.tue.nl/promforum/discussion/1223/exception-for-jdk-internal-loader-classloaders-appclassloader-with-prom-with-uitopia-workshop

**Comment by barthanssens** [comment]
Could it have something to do with OSGi ?
The manifest of jsonld-java seems to contain OSGi bundle info

**Comment by jeenbroekstra** [comment]
@swc-kdzekov could you make your small test web app available to us so we can try it ourselves on our end? Either a link to a git repo or just zipping it up and attaching to this issue will do - whatever is easiest for you.

**Comment by swc-kdzekov** [comment]
HI @jeenbroekstra. Yes sure. I just created i git repository for it. The git url is: https://github.com/swc-kdzekov/JsonLd-test

Btw, we use java 11 with tomcat 7. For that purpose we set 'jaxb-api-2.3.1.jar' to tomcat shared lib. If there are some issues regarding the repository please write.
Thank you.

**Comment by jeenbroekstra** [comment]
> Btw, we use java 11 with tomcat 7. For that purpose we set 'jaxb-api-2.3.1.jar' to tomcat shared lib. 

I don't know if that is related to your problem but but just thought it worth pointing out that since release 3.0, RDF4J requires Tomcat 8 or better due to the fact that it needs Servlet spec 3.1. Tomcat 7 only support up to 3.0.

**Comment by swc-kdzekov** [comment]
@jeenbroekstra you are right. Just checked on Tomcat 8. The ticket can be closed. 
@jeenbroekstra  and @barthanssens , thank you for processing the issue and the help.

**Comment by jeenbroekstra** [comment]
That's great! Glad that solved it :)
