### ISSUE TITLE
Make current connection state available for custom function evaluation

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#2362]
As a custom function creator, I want to be able to inspect the current state of the underlying sailconnection, so that I can calculate the output of my function based on a combination of input params and the existence or non-existence of certain data in the store.

A possible way to approach this is to extend the use of the `QueryContext` interface, which was introduced as part of the SpinSail. Alternatively, we could just look at injecting the SailConnection or the tripleSource into the custom function directly.

Related: #92

**Comment by peterjohnlawrence** [comment]
[Function and TupleFunction Uses Case.docx](https://github.com/eclipse/rdf4j/files/4925034/Function.and.TupleFunction.Uses.Case.docx)

Lengthy I am afraid, but I thought I would paint the complete picture.

**Comment by jeenbroekstra** [comment]
> [Function and TupleFunction Uses Case.docx](https://github.com/eclipse/rdf4j/files/4925034/Function.and.TupleFunction.Uses.Case.docx)
> 
> Lengthy I am afraid, but I thought I would paint the complete picture.

This is great, thanks!

The simplest possible (backwards-compatible, easy to implement) change we could do on our end, is to make the [TripleSource](https://rdf4j.org/javadoc/latest/index.html?org/eclipse/rdf4j/query/algebra/evaluation/TripleSource.html) interface available in the function, by adding a `evaluate(TripleSource tripleSource, Value... args)` method. This will make it possible to access the data source that is being used to evaluate the query on. I have only looked through your requirements document once but I have the impression this might solve most of your issues. What do you think?

**Comment by peterjohnlawrence** [comment]
<< make the TripleSource interface available in the function>> 

That would be a significant help. I guess that precludes the use of SPARQL within these functions. However, most of my use-cases could be solved with the getStatements() method instead.

Slightly different issue, but could this also be applied to TupleFunction/InverseMagicProperty as well as moving these interfaces/classes out of SPIN into the core (please:-))

**Comment by jeenbroekstra** [comment]
> << make the TripleSource interface available in the function>>
> 
> That would be a significant help. I guess that precludes the use of SPARQL within these functions. However, most of my use-cases could be solved with the getStatements() method instead.

Good to know. I don't think we will ever be able to support the use of SPARQL _within_ a function, at least not in a way that would make evaluation perform anywhere near acceptable levels.  

> Slightly different issue, but could this also be applied to TupleFunction/InverseMagicProperty as well as moving these interfaces/classes out of SPIN into the core (please:-))

We have an open issue to look at supporting custom virtual properties (see #92), that encompasses TupleFunctions as well. 

To be honest, I feel we took our eye of the ball a bit as a project when the SPIN stuff was added to the code base, and it will take time (and willing hands and minds) to tidy it all up. I'm particularly unhappy with the way parts of it are available in the core, but then depend on SPIN-specific code to actually work.
