### ISSUE TITLE
Enhance code quality by fixing SonarQube warnings

### ISSUE THREAD

**Issue by henry-lp** [eclipse/rdf4j#2363]
[SonarQube](https://www.sonarqube.org/) is used to scan for bad coding patterns. I want to provide some fix suggestions produced automatically by [Repairnator](https://github.com/eclipse/repairnator) as PR to fix the warnings found in this code base as an experiment.

**Comment by jeenbroekstra** [comment]
Thanks @henry-lp. I'm not really familiar with either project you mention. Can you elaborate a little on how SonarQube and Repairnator relate to each other? Does this mean you (or some bot/script running as part of Repairnator) is regularly scanning the RDF4J code base?

**Comment by henry-lp** [comment]
Hi @jeenbroekstra . First of all, thanks for considering this issue.
> Can you elaborate a little on how SonarQube and Repairnator relate to each other? 

Repairnator is related to SonarQube through the tool [Sorald](https://github.com/SpoonLabs/sorald) which use SonarQube and [Spoon](https://github.com/INRIA/spoon) (a Java source code analyzer) to detect the bad code patterns. By far SonarQube organization itself is unaware of the development of Sorald since it's quite young and we are currently only use it for research purpose. 

> Does this mean you (or some bot/script running as part of Repairnator) is regularly scanning the RDF4J code base?

I am scanning this with my Jenkins CI with repairnator as a build step by clicking the build button, so it is kind of being a script. Regarding scanning regularly, my initial intention was only to submit some patches per violated rule found in this repo. 

The violated rules found for this repo are the following (the number on the right of the equal symbol is how many):
* [3032](https://rules.sonarsource.com/java/type/Bug/RSPEC-3032) - GetClassLoaderCheck=65
* [2184](https://rules.sonarsource.com/java/type/Bug/RSPEC-2184) - CastArithmeticOperandCheck=15
* [2095](https://rules.sonarsource.com/java/type/Bug/RSPEC-2095) - UnclosedResourcesCheck=12
* [2164](https://rules.sonarsource.com/java/type/Bug/RSPEC-2164) - MathOnFloatCheck=11
* [2272](https://rules.sonarsource.com/java/type/Bug/RSPEC-2272) - IteratorNextExceptionCheck=9
* [4973](https://rules.sonarsource.com/java/type/Bug/RSPEC-4973) - CompareStringsBoxedTypesWithEqualsCheck=4
* [2111](https://rules.sonarsource.com/java/type/Bug/RSPEC-2111) - BigDecimalDoubleConstructorCheck=2
* [1656](https://rules.sonarsource.com/java/type/Bug/RSPEC-1656) - SelfAssignementCheck=1

**Comment by jeenbroekstra** [comment]
Thanks, that looks useful. My experience with this kind of code analysis is that there are often a lot of false positives, but these numbers you quote don't look staggering to me, it would be interesting to see the patch suggestions Repairnator can come up with.
