### ISSUE TITLE
Allow custom ExecutorService to be injected in FedX for parallel query execution

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#2366]
FedX has built-in functionality for parallel query execution. To facilitate this, the FedX FederationManager creates an ExecutorService thread pool internally. However, the thread pool configuration can currently not be influenced from outside, which makes it hard to tune behavior for some use cases (for example, if security tokens that are tied to the current thread need to be passed on to allow each parallel query to execute succesfully).

We should allow injection of a custom executor service (similar to how we already allow this for the handling of background parsing in the http clients). 

Possible approach: add a `withExecutorService` method to `FedXConfig`, allowing the user to optionally pass an `ExecutorService` of their own creation/configuration. This can then be passed on to the FederationManager to use instead of its own internal thread pool object.

**Comment by jeenbroekstra** [comment]
As an aside the `SharedHttpClientSessionManager` (used in SPARQLRepository and HTTPRepository to have a shared thread pool and HttpClient between various repositories) also creates its own ExecutorService and optionally allows a custom executor service to be injected. 

Instead of doing custom injection in FedX directly, should we consider reusing that same SessionManager mechanism in FedX? Although it's not necessarily used for querying over HTTP, it's still valid to say that a single shared thread pool for RDF4J as a whole makes sense.

**Comment by jetztgradnet** [comment]
I guess it makes sense to allow both use cases, i.e. inject an external one and/or use the shared one (and falling back to current behavior of creating one for itself).
IIRC, this is also relevant wrt cleaning up (i.e. shutting down) the executor, so there needs to be some additional tracking there, similar to how it's done for the HttpClient.

**Comment by jeenbroekstra** [comment]
> I guess it makes sense to allow both use cases, i.e. inject an external one and/or use the shared one (and falling back to current behavior of creating one for itself).
> IIRC, this is also relevant wrt cleaning up (i.e. shutting down) the executor, so there needs to be some additional tracking there, similar to how it's done for the HttpClient.

Just to be clear if we start relying on the shared one we _automatically_ also have a way to inject an external one, because the SharedHttpClientSessionManager allows this, and we can even, I think, have separate threadpools via this mechanism, that is not a pool that is shared between fedx and the httpclients.

I'll try and take a closer look at how this was supposed to work again (it's not something we have great documentation for, although there is some javadoc).

**Comment by jeenbroekstra** [comment]
I understood from Andreas that FedX in fact keeps two separate thread pools (though I have yet to figure out where the second one is configured) and that it needs them separate because of deadlock issues. So perhaps reusing the SharedHttpClientSessionManager's threadpool is not a good solution in this case.
