### ISSUE TITLE
Introduce Eclipse RDF4J SHACL Extensions

### ISSUE THREAD

**Issue by hmottestad** [eclipse/rdf4j#2371]
Introduce Eclipse RDF4J SHACL Extensions in order to develop our own extensions to SHACL. This comes as a result of discussions on the SHACL mailing list where we proposed a new feature sh:targetShape that allows a shape to be the target for a constraint. This feature was initially accepted by the community, but due to other implementation's performance considerations it was dropped as being too complex to implement.

The result is that RDF4J will add this feature to our own namespace and publish it online for others to use. Similarly to how TopQuadrant has published their DASH extension (which we have implemented partial support for).

 - prefix: rsx
 - namespace: http://rdf4j.org/shacl-extensions#

Tasks:
 - switch to using the rsx namespace in our shacl implementation
 - publish the namespace as
     - Respec page
     - http://rdf4j.org/shacl-extensions.ttl file

**Comment by jeenbroekstra** [comment]
Should this issue have been closed? If not, it's on the wrong milestone.

**Comment by jeenbroekstra** [comment]
We merged this feature, I'm sure, this was a big part of the 3.3 release, so assuming it can be closed.
