### ISSUE TITLE
Docker build should act like the maven build and use the local code instead of downloading a different version of RDF4J

### ISSUE THREAD

**Issue by hmottestad** [eclipse/rdf4j#2374]
The docker build currently has three different dockerfiles that use two different approaches for building. One uses the local code and another uses a downloaded version of rdf4j. We should always use the local code. If we want to build an older version we should checkout git branch instead.

**Comment by jeenbroekstra** [comment]
This issue is still in the inbox/triage column, but it has an associated pull request (closed, unmerged, unsure why). What's the status?

**Comment by hmottestad** [comment]
Need to fix one thing based on feedback from Bart.

**Comment by barthanssens** [comment]
See also #1439

**Comment by jeenbroekstra** [comment]
@hmottestad has this now been addressed?

**Comment by barthanssens** [comment]
If I understand the files correctly, docker will now indeed use the local version.

Perhaps useful to include the experimental docker option "--squash" to squash layers: if not, the COPY to copy the rdf4j.zip (which is only use to obtain the wars) from the local build directory into the docker image will make the docker image at lot larger, even if the file is removed from docker image afterwards

removing the file in docker and squashing should remove the temporary zip from the docker file system
