### ISSUE TITLE
SPARQL query execution result with no PREFIX

### ISSUE THREAD

**Issue by AkbarKazimov** [eclipse/rdf4j#2380]
The result of a SPARQL query execution does not return any PREFIX which is already defined in the query. Is there a way to parse the query in order to get Namespaces/Prefixes from the query? 
Is there a way to execute a query in such a way that the result contains Prefixes as well?

**Comment by damyan-ognyanov** [comment]
Not quite sure what you are after ...

what about assigning those explicitely in the body of the query? e.g.:
```
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix p1: <http://p1.org/>
prefix p2: <http://p2.org/>
prefix p3: <http://p3.org/>

select * {
    {
        values ?prefix {p1: p2: p3: rdfs:}
    } union {
        bind (1 as ?other)
    }
}
```

**Comment by AkbarKazimov** [comment]
> Not quite sure what you are after ...
> 
> what about assigning those explicitely in the body of the query? e.g.:
> 
> ```
> PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
> prefix p1: <http://p1.org/>
> prefix p2: <http://p2.org/>
> prefix p3: <http://p3.org/>
> 
> select * {
>     {
>         values ?prefix {p1: p2: p3: rdfs:}
>     } union {
>         bind (1 as ?other)
>     }
> }
> ```

So following is the query I use:

```
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX welcome: <http://welcome/services/1.0/>
				CONSTRUCT {
					?dip rdf:type welcome:DIP_request_info .
					?dip welcome:dip_age ?age .
					?dip welcome:dip_residence_address_city ?city .
				}
				WHERE {
					?dip rdf:type welcome:DIP_request_info .
					?dip welcome:dip_age ?age .
					?dip welcome:dip_residence_address_city ?city .
				}
```
Here is the result I get:

> <http://welcome/services/1.0/dip1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://welcome/services/1.0/DIP_request_info>
> <http://welcome/services/1.0/dip1>  <http://welcome/services/1.0/dip_age>  "26"
> <http://welcome/services/1.0/dip1>  <http://welcome/services/1.0/dip_residence_address_city>  "unknown"

In the Construct query I define PREFIXes, but the result has no Prefix. Therefore, the model which is generated from the above statements have no Namespaces. I tried to parse SPARQL query and set namespaces manually but unfortunately couldn't find anything to do that. 

Honestly, I don't know how to assign prefixes in the body of the query.

**Comment by damyan-ognyanov** [comment]
just provide a suitable RDF format for the result of your query that support such feature as `prefix` - e.g. `Accept: text/turtle` format for instance

**Comment by AkbarKazimov** [comment]
Thank you very much :)
I was using Repositories class to execute queries instead of RepositoryConnection.
