### ISSUE TITLE
SHACL Object Model

### ISSUE THREAD

**Issue by tfrancart** [eclipse/rdf4j#2381]
Is there a plan to provide an object model of a SHACL graph in the context of SHACL implementation ? something equivalent to https://github.com/TopQuadrant/shacl/tree/master/src/main/java/org/topbraid/shacl/model ?

**Comment by hmottestad** [comment]
We don't really have any plans for that no. Our abstract syntax tree would serve the purpose, and we are working on a new implementation to cover the entire SHACL spec, but neither of these are designed to be used by our users.

**Comment by jeenbroekstra** [comment]
@tfrancart do you have a particular use case in mind where you think this would be beneficial? If you have a use case that the current SHACL support in combination with RDF model support does not adequately provide for, we can transform this into a feature request and see if anybody is willing to work on it.

**Comment by tfrancart** [comment]
I run [SHACL Play!](http://shacl-play.sparna.fr/) which is a free online SHACL validator based on TopQuadrant's SHACL implementation. I see 2 use-cases :
1. One of the benefit (and challenge) of such an end-user oriented tool is its ability to display human-readable validation reports ([example of a validation report](http://shacl-play.sparna.fr/validate?shapes=shaclplay-catalog&url=https://raw.githubusercontent.com/sparna-git/SHACL-Catalog/master/shacl-catalog.ttl)). A validation report displays the report but necessarily needs to fetch and display information from the shapes graph, hence the need to have any way to retrieve e.g. shape information (label, description, set of constraints, etc.); I doubt the validation report alone is sufficient to provide human-readable information;
2. I would also simply like to print a shape graph to the end-user, just so people can read the content of a set of constraints; including UML-like visualisation of Shapes;

**Comment by tfrancart** [comment]
Another possible use-case include programmatically create Shapes (e.g. analyse a dataset and create Shapes corresponding to the structure of graph). Ability to use an object model of the Shapes might be easier than creating the raw triples.

**Comment by hmottestad** [comment]
The new abstract syntax tree I’m developing for the ShaclSail has a toModel method that generates triples from the java objects. So overall I think it would be a good fit.

**Comment by jeenbroekstra** [comment]
I suggest that we close this issue for now assuming the AST work (#2083 ) will solve this use case, we can always reopen (or log new issues for further AST extensions) if necessary.
