### ISSUE TITLE
Stop producing nightly snapshot maven builds

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#2388]
We currently have Jenkins set up to deploy nightly snapshot builds of our maven artifacts to Sonatype. There are several reasons we do this:

1. when we still had a multi-repository setup, it was _necessary_ to publish maven artifacts in a place where the other repo could get them - so for example rdf4j-storage needed to be able to download rdf4j artifacts as part of its build. 
2. we provide these nightly snapshot builds as a courtesy to developers who want to try out the latest/greatest (see https://rdf4j.org/download/#source-code-and-nightly-builds).

However, there are some downsides as well:

1. when a developer runs a maven command the first time every day, maven will check and download the latest snapshot dependencies from sonatype (even if the developer uses their own local build process) - not harmful, but it can take a long time, which is annoying.
2. it can sometimes cause confusion for developers to know which exact version of the code they are depending on (they changed something locally in a module they depend on, but the build still uses the downloaded snapshot , causing odd errors).
3. the Jenkins deployment process is not 100% reliable, and sometimes falls over with errors. 

So the question is: do we still want to provide nightly snapshot builds on Sonatype?

**Comment by hmottestad** [comment]
I really like it for testing the newest features. Essentially I have some projects that use rdf4j and if I've added some new features I want to test out to develop, then I'll use the SNAPSHOT version in one of my projects. It's a lot simpler than having to checkout code from github and building it locally within that project.

**Comment by jeenbroekstra** [comment]
> really like it for testing the newest features. Essentially I have some projects that use rdf4j and if I've added some new features I want to test out to develop, then I'll use the SNAPSHOT version in one of my projects. It's a lot simpler than having to checkout code from github and building it locally within that project.

You'd still be able to do that though - the snapshots would just come from your own local maven repo rather than from sonatype (assuming you've ran mvn install on the rdf4j project recently). I mean, you already _have_ the rdf4j project checked out from github, right?

Still, I see your point, this is essentially advantage #2 from my list. 

What we're struggling with is that for developing RDF4J itself, having these snapshots is a hindrance. However, like you mention as well, for doing feature testing in a separate project there's clearly an advantage.

It should be possible to set things up in such a way that we still deploy snapshots for reuse in separate projects, but make sure that RDF4J's own build process doesn't depend on them. That would be the best of both worlds. I'll take a look at this.

**Comment by hmottestad** [comment]
My own projects use docker to build or a build server. So I would have to add a new step to checkout the develop branch and mvn install it. That's such a big hassle I would probably not bother anymore.

**Comment by jeenbroekstra** [comment]
Fwiw I am now unsure there is a problem worth solving here. Having trouble reproducing the snapshot download during build thing.

**Comment by hmottestad** [comment]
I think I have seen it in my logs every once in a while. Cant reproduce now. Maybe it'll happen if you remove the rdf4j cache from your .m2 folder and try to mvn install from inside one module in the rdf4j project.

**Comment by jeenbroekstra** [comment]
> I think I have seen it in my logs every once in a while. Cant reproduce now. Maybe it'll happen if you remove the rdf4j cache from your .m2 folder and try to mvn install from inside one module in the rdf4j project.

That is, now that I think about it, normal/by design: the idea of the snapshot repo was (also) to make it possible to compile individual modules without having to first build the entire project. However, what I was trying to solve was that it occassionally downloads these snapshots even when building from the project root (when it definitely _shouldn't_ happen, because everything it needs is in the reactor).

I've just found that it happens on the project root level as part of the enforcer plugin firing its `enforce-bytecode-version` goal. I think this is because that plugin fires _before_ compilation (in the validation phase) - so it can't use the locally compiled code, and instead downloads the snapshot build to check its bytecode version. That's a bit backward, I'll try to move that check to somewhere after the compilation phase (probably `verify`), so it doesn't need the download.

**Comment by jeenbroekstra** [comment]
We could also just get rid of the plugin altogether and instead rely on the fact that we run a github action CI with the full testsuite on Java 8.
