### ISSUE TITLE
Missing unit tests for spin:functions

### ISSUE THREAD

**Issue by jgrzebyta** [eclipse/rdf4j#239]
I am working on simple unit tests for spin functions.

**Comment by pulquero** [comment]
Note there are some existing ones for some functions in rdf4j-sail-spin/org.eclipse.rdf4j.sail.spin.

**Comment by jeenbroekstra** [comment]
Current merge has caused a test failure on hudson. I am re-opening this issue and reverting the merge.

**Comment by jeenbroekstra** [comment]
See https://hudson.eclipse.org/rdf4j/job/rdf4j-2.0-verify/43/ for details on test failure.

**Comment by jgrzebyta** [comment]
This issue was not finish yet. I will put new PR for that.
