### ISSUE TITLE
Documentation for Eclipse RDF4J SHACL extensions

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#2390]
Followup of #2371:

publish the namespace as

- Respec page
-  http://rdf4j.org/shacl-extensions.ttl file

See open PR at https://github.com/eclipse/rdf4j-doc/pull/177

(split into separate issue to allow closing the original feature ticket for the release milestone)

**Comment by jeenbroekstra** [comment]
What's the status of this? There's an open and approved pull request, are we ready to merge and publish the first working draft?

**Comment by hmottestad** [comment]
I need to double check this after a bug I found.
