### ISSUE TITLE
Upgrade to ES 7.8.x, Lucene 8.5.x, Solr 8.4.x

### ISSUE THREAD

**Issue by barthanssens** [eclipse/rdf4j#2392]
Upgrade to latest elasticsearch and lucene, this would also solve the guava dependency issue #1097.

To be tested:
 - [x] lucene 7->8
 - [x] embedded solr 7->8
 - [x] elasticsearch 6->7
 - [x] elasticsearch store

Related to #2273 

Works with CQ:
- [x] ElasticSearch Cluster Runner 7.8.1.0 (CQ22480)

Solr 8.4.1
 - [x] Solr-Core (CQ22486)
 - [x] Solr-Solrj (CQ22487)

Lucene 8.5.1
 - [x] Lucene Core (CQ22512) 
 - [x] Lucene Analyzers Common (CQ22513) 
 - [x] Lucene Backwards Codecs (CQ23614)
 - [x] Lucene Highlighter (CQ22514)
 - [x] Lucene Memory (CQ22515)
 - [x] Lucene Queries (CQ22516)
 - [x] Lucene Queryparser (CQ22518)
 - [x] Lucene Sandbox (CQ22520)
 - [x] Lucene Spatial 3D (CQ22524)
 - [x] Lucene Spatial Extras (CQ22521)

Elasticsearch 7.8.1 Works-with
 - [x] Elasticsearch Transport Client (CQ22488)
 - [x] Elasticsearch Test Framework (CQ22489)

 Netty 4.1.29
 - [x] Netty Buffer (CQ13511, license certified)
 - [x] Netty Codec (CQ13512, license certified)
 - [x] Netty Common  (CQ13516, license certified)
 - [x] Netty Handler (CQ13517, license certified)
 - [x] Netty Resolver (CQ13518, license certified)
 - [x] Netty Transport (CQ13519, license certified)
 - [x] Netty Transport Native Epoll (CQ22683)
 - [x] Netty Transport Native Unix Common (CQ22684)

**Comment by jeenbroekstra** [comment]
Sounds good. Any possible migration issues for users of older versions of Lucene / Elasticsearch?

**Comment by barthanssens** [comment]
To be tested of course, but for any major upgrade Solr recommends to re-index... so some migration effort is to be expected

**Comment by barthanssens** [comment]
One minor difference is the ES-port being used, so that might be useful to add to the release notes (i.e. might require a change in firewall rules)

https://www.elastic.co/guide/en/elasticsearch/client/java-rest/master/_changing_the_client_8217_s_initialization_code.html

**Comment by barthanssens** [comment]
For starters, see https://github.com/eclipse/rdf4j/issues/2015 for the list of dependencies (may not be exactly the same for the new versions)

**Comment by barthanssens** [comment]
One additional issue is that the "Embedded Elasticsearch" project (used in testing the ES-store) is no longer maintained https://github.com/allegro/embedded-elasticsearch, and it is suggested to use the (docker-based ?)  TestContainers

**Comment by jeenbroekstra** [comment]
> Another option seems to be https://github.com/codelibs/elasticsearch-cluster-runner (seems easier to integrate in our current setup)

Good find!

**Comment by barthanssens** [comment]
Some tweaking is probably needed to make the tests work. Obviously, the cluster runner is for running, well, clusters... i.e. somewhat memory intensive. Using one node only didn't work for at least one test, so I'll try fiddling with some parameters.

**Comment by barthanssens** [comment]
As mentioned on Gitter, some SolrSailTest and SolrSailIndexedPropertiesTest fail with Solr 8.5 while Solr 8.4 (and Lucene 8.5) tests are just fine. It looks like an issue with Solr Highlighting (SolrIndex.query gets the results, but in 8.5 the highlight list per SolrDocument is empty...)

So upgrading Lucene to 8.5, but Solr to 8.4

**Comment by barthanssens** [comment]
A note about possible (in)compatible elasticsearch major versions and re-indexing for Lucene should be added to #2547

**Comment by barthanssens** [comment]
As mentioned during the planning meeting: upgrade to the latest ES (7.10.x) that uses the old Apache 2 license 
(to be verified if the newer versions licensed under Elastic License v2 are compatible with Eclipse license)

**Comment by barthanssens** [comment]
Marking documentation / not backwards compatible because we cannot be sure that e.g. new ES client can communicate with old ES server.

Also (manual) re-indexing might be needed.

**Comment by barthanssens** [comment]
Might be useful to include lucene-backward-codec-8.5, or at least include it in the server war.
Doing this allows the Workbench/server 4.0 to use a Lucene 7.x index created by RDF4J 3.x.

Though the best way to handle this is to use the lucene IndexUpgrader tool (to be included in the notes) https://lucene.apache.org/core/8_5_0/core/org/apache/lucene/index/IndexUpgrader.html (which may require having backward-codecs in the classpath)
If needed, one can download a 7.x version of Lucene to upgrade a Lucene 6.x index created by RDF4J 2.x to Lucene 7.x, then repeat with a 8.x version of Lucene to upgrade the index to 8.x
(the Lucene upgrade process only works one major version a time)
