### ISSUE TITLE
Rewrite the workbench from scratch

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#2423]
The RDF4J workbench is quite old, using various technologies for which newer, easier to use/maintain variants now exist. It has become hard to maintain, and frankly, it also looks its age (the UI hasn't had a facelift since the early 2000s). 

We should consider a completely new implementation of the workbench application, or some web application with similar functionality. I am at this point open to the precise technology stack, though NodeJs / Vue / React or something of that ilk seems a natural choice.

**Comment by barthanssens** [comment]
Related to #1901

**Comment by jeenbroekstra** [comment]
Thanks Bart, I'd forgotten about that - I'll close this as a duplicate for now.
