### ISSUE TITLE
Simplify creation of RDF* triples from existing statements

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#2430]
For even simple jobs involving annotating existing facts, currently the API is a bit clunky. For example, imagine we have a simple RDF model, involving data about a person:

```java
String ex = "http://example.org/";
ValueFactory vf = SimpleValueFactory.getInstance();
IRI bob = vf.createIRI(ex, "bob");
IRI endDate = vf.createIRI(ex, "endDate");
IRI startDate = vf.createIRI(ex, "startDate");

// say some stuff about Bob
Model model = new ModelBuilder().setNamespace(FOAF.NS)
		.setNamespace("ex", ex)
		.subject(bob)
			.add(RDF.TYPE, FOAF.PERSON)
			.add(FOAF.GIVEN_NAME, "Robert")
			.add(FOAF.FAMILY_NAME, "Example")
			.add(FOAF.MBOX, "bob@hisfirst.job")
		.build();
```

Now imagine Bob changed jobs today, and their e-mail address changed. We want to use RDF* to annotate the existing mbox statement and give it an end date, and also assert a new mbox, and give that a start date.

```java
Literal today = vf.createLiteral(new Date());
Literal newMbox = vf.createLiteral("bob@newjob.job");

for (Statement mboxSt : model.getStatements(bob, FOAF.MBOX, null)) {
	// annotate the statement with the end date
	model.add(vf.createTriple(mboxSt.getSubject(), mboxSt.getPredicate(), mboxSt.getObject()), endDate, today);
}

// first create the triple for annotation, then use that to assert both the annotation and the ground statement itself.
Triple t = vf.createTriple(bob, FOAF.MBOX, newMbox);
model.add(t, startDate, today);
model.add(t.getSubject(), t.getPredicate(), t.getObject());
```

As can be seen, we can't easily reuse the existing `Statement` object for its corresponding `Triple`, nor vice versa. We forced to create new Statement / Triple objects whenever we switch.

There are several possibilities to make this easier for a user:

## option 1: add conversion methods to the `Statements` utility:

```
for (Statement mboxSt : model.getStatements(bob, FOAF.MBOX, null)) {
	// annotate the statement with the end date
	model.add(Statements.asTriple(mboxSt), endDate, today);
}
Triple t = vf.createTriple(bob, FOAF.MBOX, newMbox);
model.add(t, startDate, today);
model.add(Statements.asStatement(t));
```

Advantage: 

- lightweight and flexible

Disadvantage: 

- needs good documentation, not easily discoverable
- still involves creating / keeping track of two separate objects 

## option 2: make `Statement` inherit from `Triple`

```
for (Statement mboxSt : model.getStatements(bob, FOAF.MBOX, null)) {
	// annotate the statement with the end date
	model.add(mboxSt, endDate, today);
}
Triple t = vf.createStatement(bob, FOAF.MBOX, newMbox);
model.add(t, startDate, today);
model.add((Statement)t); // or even just model.add(t);
```

Advantage:

-  intuitive, and seemless
- no need to have two separate objects

Disadvantage: 

- `Statement` becomes a subclass of `Value`: possibility of runtime / casting issues in unexpected places?

**Comment by hmottestad** [comment]
I guess the underlying issue is that there is no graph support for rdf*. 

This actually makes me wonder, how do you annotate a triple that is in more than one graph?

**Comment by jeenbroekstra** [comment]
> I guess the underlying issue is that there is no graph support for rdf*.
> This actually makes me wonder, how do you annotate a triple that is in more than one graph?

RDF* triples are subject (or object) values of statements, and those statements can occur in named graphs, same as any other statement.  I think you'd just assert the annotation as part of whichever named graph you want to assert it. 

In other words, if you have:

```
:g1 { :bob foaf:name "Bob". }
:g2 { :bob foaf:name "Bob". }
```

And you want to annotate the statement in `g2` only, you'd do this:

```
:g1 { :bob foaf:name "Bob" }
:g2 { :bob foaf:name "Bob" .
        <<:bob foaf:name "Bob">> ex:certainty 0.9 .
}
```

But this doesn't address the issue in our API that conversion between statement and triple is more difficult than it should be. I'm not so worried about "loss" of the context part of a statement in this conversion: after all an RDF* triple in itself doesn't _have_ a context (just as an IRI or a Literal on its own doesn't have a context). It's purely about the ease of switching between the two object types.

**Comment by damyan-ognyanov** [comment]
I preffer option 1. 

for option 2 (making Statement inherit Triple) I have concern that it may cause all sorts of unexpected issues with a third party/existing user code/ where the type of Value instances is checked and the code pattern is usually looks like `if (x instanceof IRI) {} else if (x instanceof BNode) else { // handling literal}` ...

**Comment by hmottestad** [comment]
I had another idea about this. Our MemoryStore interns all resources and values so that they can have lists that point to where the resource is used as subject or object and so on. Maybe we want the same for statements. So that we intern statements and allow for them to point to where they exist as triples as subjects or objects. 

Would this way of thinking have any effect for the choice of inheritance?

**Comment by damyan-ognyanov** [comment]
@hmottestad the existence of Triple do not imply that a Statement with same subject, predicate and object is also present/asserted in the data

**Comment by jeenbroekstra** [comment]
Fair points all, thanks. I am happy to go with option 1, it's a low-risk option even if we later decide we need something more/different.

**Comment by jeenbroekstra** [comment]
> for option 2 (making Statement inherit Triple) I have concern that it may cause all sorts of unexpected issues with a third party/existing user code/ where the type of Value instances is checked and the code pattern is usually looks like if (x instanceof IRI) {} else if (x instanceof BNode) else { // handling literal} ...

@damyan-ognyanov for what it's worth, this is a problem even in the current setup, as `Triple` itself is a new type of `Value` that existing code may not "play nice" with in this kind of pattern. But for now as said I'll stick with option 1, and we can perhaps revisit this later, if necessary.
