### ISSUE TITLE
SHACL property sh:uniqueLang seems not to be working

### ISSUE THREAD

**Issue by semantickyweb** [eclipse/rdf4j#2451]
Hello all,

I am new to this group but working with RDF4J for some time. We are evaluating **SHACL** features of RDF4J and I cannot put the sh:uniqueLabel work. We are using 3.1.4 version, where the property is supported (when I call the ShaclSail.getSupportedShaclPredicates().toString() method, I can see the property listed).

I attached very simple data (4 triples): **testdata-01-simplest.ttl**
```
<https://poolparty.biz/test/1> a <http://www.w3.org/2004/02/skos/core#Concept> ; 
<http://www.w3.org/2004/02/skos/core#prefLabel> "Monitors"@en .
<https://poolparty.biz/test/2> a <http://www.w3.org/2004/02/skos/core#Concept> ;
<http://www.w3.org/2004/02/skos/core#prefLabel> "Monitors"@en .
```
as well as little enriched: **testdata-02-simple.ttl**
```
<http://www.w3.org/2004/02/skos/core#Concept> a <http://www.w3.org/2000/01/rdf-schema#Class> .
<https://poolparty.biz/test/1> a <http://www.w3.org/2004/02/skos/core#Concept> ; 
<http://www.w3.org/2004/02/skos/core#prefLabel> "Monitors"@en .
<https://poolparty.biz/test/2> a <http://www.w3.org/2004/02/skos/core#Concept> ;
<http://www.w3.org/2004/02/skos/core#prefLabel> "Monitors"@en .
<https://poolparty.biz/test/1> <http://www.w3.org/2002/07/owl#differentFrom> <https://poolparty.biz/test/2> .
```
However, following shape doesn't find the desired inconsistencies in both testdata triples: **prefLabel-shape.shacl**
```
prefix sh: <http://www.w3.org/ns/shacl#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix pp: <https://poolparty.biz/>

pp:ConceptShape
        a sh:NodeShape ;
        sh:targetClass skos:Concept ;
        sh:property 
        [
        sh:path skos:prefLabel ;
        sh:uniqueLang true ;
        ] .
```
I tried lots of approaches, even use this method  shaclSail.setUndefinedTargetValidatesAllSubjects(true);

but still cannot get those inconsistencies. However, when I create a different shape, for example with sh:maxCount/sh:minCount, this is working. So  I suspect maybe there is a bug in SHACL validation of sh:uniqueLang property. 

May I ask you for help? Whether there is a bug or I am doing something wrong?

Kind regards
Miro
[testdata+shaclshape.zip](https://github.com/eclipse/rdf4j/files/5098752/testdata%2Bshaclshape.zip)

**Comment by jeenbroekstra** [comment]
@semantickyweb I'm not sure I follow. You are asserting the _exact same_ statement a second time, so there is no uniqueness constraint being violated. RDF graphs are sets so the second statement is simply ignored.

**Comment by jeenbroekstra** [comment]
Closing this issue as resolved.
