### ISSUE TITLE
Use the SHACL reference implementation to validate test cases

### ISSUE THREAD

**Issue by hmottestad** [eclipse/rdf4j#2457]
It would be good to validate that all our test cases are compliant with the reference implementation by:

 - checking the shapes against the SHACL spec
 - checking each test case to make sure the validation result is the same

**Comment by hmottestad** [comment]
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=22578

**Comment by hmottestad** [comment]
I have a CQ pending here, but now I'm starting to wonder....do we need to do CQs for test dependencies anymore @jeenbroekstra ? The IP team hasn't done anything with my CQ since I opened it.

**Comment by barthanssens** [comment]
Hmz, I think we still need CQ for test dependencies, but it's not required anymore to get approval before it can go into the dev branch (approval is of course still needed upon release)

https://www.eclipse.org/projects/handbook/#ip

You may want to add a kind reminder as comment in IPZilla (works for me :-))

**Comment by hmottestad** [comment]
Would very much like to merge this so I can use it in one of my other branches.
