### ISSUE TITLE
Settle on a single collection utility library

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#2475]
We currently include two collection utility libraries in RDF4J: Apache Commons Collections, and Google Gauva. This is redundant as both provide pretty similar functionality. 

Having both included is a burden on our users who will need to include _both_ transitive dependencies in their own project, doubling the risk of potential version conflicts when combining RDF4J with other libraries.  

I have no strong opinion on which one is the "better" library, both are solid and well-maintained, however we use guava in more places, so replacing apache commons collections (which is only used in the internals of the native store and the extensible store) is probably the simplest approach.

**Comment by jeenbroekstra** [comment]
@hmottestad I had a quick look at what we use commons-collections for, and in both instances it seems to be used only to create an internal cache based on `ReferenceMap` (that is, a Map object with weak references for its values so they can GCd when no longer referenced elsewhere). Guava [MapMaker](https://www.baeldung.com/guava-mapmaker) seems to offer very similar functionality. We may want to run some comparitive performance tests but off the top of your head do you see any reason not replace commons-collections with guava in both instances?

**Comment by jeenbroekstra** [comment]
Just to throw a bit more confusion into the discussion: we could even consider getting rid of _both_, and switching to [Eclipse Collections](https://www.eclipse.org/collections/) which claims to have unparalleled memory footprint/performance characteristics. Also saves us having to do CQs :)

**Comment by hmottestad** [comment]
Btw. The use of ReferenceMap is for hard keys and soft values. We don't use weak references. 

The use of hard keys and soft values makes for a simple cache that can be cleared during a GC if we run low on memory. 

As long as guava can do the same I'm perfectly happy to switch.

**Comment by jeenbroekstra** [comment]
> Btw. The use of ReferenceMap is for hard keys and soft values. We don't use weak references.
> The use of hard keys and soft values makes for a simple cache that can be cleared during a GC if we run low on memory.
> 
> As long as guava can do the same I'm perfectly happy to switch.

I'm a little rusty on this, but isn't a soft reference just a specific type of weak reference? If I remember correctly the only difference is that weak references are GC'd more eagerly. Do you consider the difference important for this use case?

**Comment by hmottestad** [comment]
Yes. The difference is very important. We don't keep any other references to the values, so if we use a map with weak references the cache would just get cleared on every GC cycle. Soft references stay around as long as there isn't a high memory pressure.

**Comment by jeenbroekstra** [comment]
Fair enough. It's the kind of thing Guava supports through a `CacheBuilder` I believe (which, come to think of it, I think we also use in several places).

**Comment by hmottestad** [comment]
Feel free to swap it for the CacheBuilder if you feel like it. Just make sure it's unlimited in size.

**Comment by jeenbroekstra** [comment]
I've done a quick spike on this, running comparative benchmarks, and at least there seems to be no real performance difference. PR will follow.
