### ISSUE TITLE
The issue of handling the percent character in IRI.

### ISSUE THREAD

**Issue by yayamamo** [eclipse/rdf4j#2481]
Hi, I'm using RDF4J 3.4.0.
When loading a RDF dataset in N-Triples including the following IRI, I've encountered the error saying that "Illegal percent encoding U+25 ...".
`<http://lod.ac/bdls/term/50%致死量>`

Do we need to encode the percent character into "\u25"?
According to the [N-Triple spec.](https://www.w3.org/TR/n-triples/), we seem not to encode.

Thanks.

**Comment by jeenbroekstra** [comment]
If your intent is to have a literal '%' character in the IRI, you actually need to percent-encode it. To quote [RFC 3986](https://www.ietf.org/rfc/rfc3986.txt):

> Because the percent ("%") character serves as the indicator for
   percent-encoded octets, it must be percent-encoded as "%25" for that
   octet to be used as data within a URI.

**Comment by jeenbroekstra** [comment]
I hope this addresses your issue, closing now, but do feel free to comment / reopen if you have any further issues.

**Comment by yayamamo** [comment]
Thank you for your reply.
So, do we need to percent-encode only the character of '%' or any other characters, too?
It is confusing for me which character should be encoded if I build data in N-Triples.
There are three choices as follows:
1. percent-encode
2. utf-8 "\uxxx" encode
3. plain utf8 (no special encode)
I cannot find any library for any programming languages to handle the encoding properly.

**Comment by jeenbroekstra** [comment]
Have a closer look at the `ParsedIRI` class. In particular, the `ParsedIRI.create` utility method is your friend. It attempts to construct a legal IRI from string input by automatically percent-encoding anything that needs percent-encoding. 

Unicode `\u` escape sequences are not normally necessary unless you are trying to use a Unicode char that is somehow non-printable, for example the control / punctuation chars like the left-to-right override character (\u202E), or where using the code point escape keeps things more legible (for example some characters may not have a representation in common display fonts).
