### ISSUE TITLE
Clarify behaviour of ValueFactory.createLiteral for RDF-1.1 conformance

### ISSUE THREAD

**Issue by ansell** [eclipse/rdf4j#249]
The javadoc for the ValueFactory.createLiteral methods do not currently explicitly conform to RDF-1.1. In particular, a user asked on the mailing list why they could not create a Literal with an actual missing/null datatypeIRI, which doesn't exist in RDF-1.1 but is not explicitly catered for in the current javadoc.

**Comment by ansell** [comment]
I am going to work on this btw. Forgot to mention that above.

**Comment by jeenbroekstra** [comment]
Thought I'd pick this up, then decided I really need lunch.
