### ISSUE TITLE
Importing ESCO ontology into RDF4J

### ISSUE THREAD

**Issue by vujasm** [eclipse/rdf4j#2504]
Hi,

I attempted several times to import ESCO RDF/SKOS ontology into RD4J latest version, native non-in-memory store, but never managed to import it.  I was trying to add/import it with rdf-workbench 'add' feature. Web page uploads the file (progressing from 0 - 99%) but after the upload is finished, it look like nothing went into the triple store. I tried also with rdf4j console.
Would you be available to try to import this dataset into RDF4J, just to understand if there is a constraint due high number of triples or different issue has emerged out. The Dataset, named ESCO v1 classification Full RDF v1.0.8 (687MB) can be downloaded from this url https://ec.europa.eu/esco/portal/download

Thanks a lot in advance

**Comment by barthanssens** [comment]
Hi,

interesting use case. I'd argue that the workbench might not be the best way to import such a large dataset. Presumably it will have thrown an time-out error somewhere, or is still busy storing/creating data or indexes ...

I'm downloading the dataset to see how can easily be loaded in the native store on modest hardware.
Depending on the number of triples, the native store may not be the best solution, but there are backends supporting RDF4J that can scale further if needed...

Best regards

Bart

**Comment by barthanssens** [comment]
Meanwhile I've downloaded the file, looks like it's only 8 M triples, so the Nativestore itself should be just fine (up to 150 M should be ok). So next step: loading into the nativestore.

**Comment by barthanssens** [comment]
Note that loading 8M into a Nativestore via the Workbench can take a fair amount of time (e.g. the ESCO dataset is still loading an hour after uploading on my old machine, IIRC it is all wrapped in one big transaction). So it may look like the loading into the workbench is finished, while the data is still being processed...

FYI: we're currently looking into developing a bulk upload tool to speed up the process (see also #507 )

If you would have direct access to the server hosting the repositories, I'd recommend to write a small program using the https://rdf4j.org/javadoc/latest/org/eclipse/rdf4j/rio/helpers/AbstractRDFHandler.html that commits every 50.000 statements.
That should bring down load time to a few minutes, depending on configuration. I can provide a quick'n'dirty example if needed.

If you don't have access to the server, splitting the dataset into smaller chunks should help.

**Comment by barthanssens** [comment]
For instance, this could be used to load files into a nativestore,

```
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

import org.eclipse.rdf4j.IsolationLevels;
import org.eclipse.rdf4j.model.Statement;
import org.eclipse.rdf4j.repository.RepositoryConnection;
import org.eclipse.rdf4j.repository.sail.SailRepository;
import org.eclipse.rdf4j.rio.RDFFormat;
import org.eclipse.rdf4j.rio.RDFParser;
import org.eclipse.rdf4j.rio.Rio;
import org.eclipse.rdf4j.rio.helpers.AbstractRDFHandler;
import org.eclipse.rdf4j.rio.helpers.BasicParserSettings;
import org.eclipse.rdf4j.sail.nativerdf.NativeStore;

public class Main {
	
	public static void main(String[] args) throws IOException {
		final Path ESCO = Paths.get("C:/Data/esco-bundle/v1.0.8/esco_v1.0.8.ttl");
		final Path NATIVE_DIR = Paths.get("C:/Data/tmp11");

		NativeStore store = new NativeStore(NATIVE_DIR.toFile());
		store.setDefaultIsolationLevel(IsolationLevels.NONE);
		SailRepository repo = new SailRepository(store);

		RDFParser parser = Rio.createParser(RDFFormat.TURTLE);
		parser.set(BasicParserSettings.VERIFY_LANGUAGE_TAGS, false);
		parser.set(BasicParserSettings.VERIFY_RELATIVE_URIS, false);
		parser.set(BasicParserSettings.VERIFY_DATATYPE_VALUES, false);
		parser.set(BasicParserSettings.VERIFY_URI_SYNTAX, false);		
			
		try(RepositoryConnection conn = repo.getConnection()) {
			conn.begin();
			parser.setRDFHandler(new AbstractRDFHandler() {
				private long i;

				@Override
				public void handleStatement(Statement stmt) {
					conn.add(stmt);
					if (i++ % 100_000 == 0) {
						conn.commit();
						System.err.println(i);
						conn.begin();
					}
				}
			});
			parser.parse(Files.newBufferedReader(ESCO), "");
			conn.commit();
		}
	}
}
```

**Comment by jeenbroekstra** [comment]
As a minor alternative, instead of setting the default isolation level of the database to NONE, you can also just set it for the current transaction: `conn.begin(IsolationLevels.NONE);`

@barthanssens as an aside since you said this dataset is only 8M triples, I'm surprised you even _need_ to do this custom handling and splitting.

**Comment by barthanssens** [comment]
@jeenbroekstra I'll have to doublecheck on another machine, but I had to set the IsolationLevel (with the default level it was slowing down considerably after +/- 3 M triples)
Not sure if the other settings make that much of a difference, and splitting may indeed not be needed for 8 M triples...

Note that the machine I used may not be a good benchmark (Core i5 laptop with an SSD, but on Windows with company policies and AV running which I can't turn off...)

To give a rough idea on the performance, on this machine the data was loaded in a new nativestore in +/- 7 minutes.

**Comment by vujasm** [comment]
Hi @barthanssens , @jeenbroekstra , thanks for the help. I successfully imported the dataset by running the small program that you've provided in your earlier post. It took few minutes to finish the upload, but that's fine for my purpose. Afterwards, I included it (native store) under rdf4j-server/workbench by making a config.ttl and was able to execute SPARQLs from rdf4j-workbench. 
Kind regards

**Comment by hmottestad** [comment]
This process would be worthwhile to document.
