### ISSUE TITLE
Broken project URL in the root pom

### ISSUE THREAD

**Issue by knoan** [eclipse/rdf4j#2520]
The project URL currently declared by the root [pom](https://github.com/eclipse/rdf4j/blob/master/pom.xml) (https://rdf4j.eclipse.org/) seems to be defunct.

This is inconvenient, as it ends up in a number of automatically generated documents (e.g maven dependency records), wrecking havoc on link integrity checks.

**Comment by jeenbroekstra** [comment]
The rdf4j.eclipse.org was recently removed (Eclipse foundation is moving away from using `<project>.eclipse.org` for project pages, and besides we have our own domain). I had not realised we still used the domain in places.

**Comment by jeenbroekstra** [comment]
I have also asked Eclipse webmaster to temporarily reinstate the DNS mapping, so that in the short term these links resolve again.

**Comment by jeenbroekstra** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=551274

**Comment by jeenbroekstra** [comment]
rdf4j.eclipse.org now (temporarily) resolves again. We'll update the pom and other places where this domain is still used.
