### ISSUE TITLE
IRI spaces inconsistency

### ISSUE THREAD

**Issue by elad-shaked** [eclipse/rdf4j#2525]
IRIs with spaces are allowed
```
// Will succeed
SimpleValueFactory.getInstance.createIRI("ns:", "with space")
```

But when serialized using `TurtleWriter`, the space is encoded as %20
Then, when deserializing with `TurtleParser`, the IRI local name comes back as "with%20space"

The assertion in the following self-contained Scala code fails and prints:

"(ns:with%20space, ns:with%20space, ns:with%20space)"

```
    val iri: IRI = SimpleValueFactory.getInstance.createIRI("ns:", "with space")

    val writer: StringWriter = new StringWriter()
    val rdfWriter: RDFWriter = Rio.createWriter(RDFFormat.TURTLE, writer)
    rdfWriter.startRDF()
    rdfWriter.handleStatement(SimpleValueFactory.getInstance.createStatement(iri, iri, iri))
    rdfWriter.endRDF()
    writer.close()

    val parser: RDFParser = Rio.createParser(RDFFormat.TURTLE)
    parser.setRDFHandler(new AbstractRDFHandler {
      override def handleStatement(st: Statement): Unit = {
        println(st)
        assert(st.getSubject.asInstanceOf[IRI].getLocalName == "with space")
      }
    })
    parser.parse(new StringReader(writer.toString), "dummy_base_uri")
```

(I tried to keep the code as little Scala'y as possible)

**Comment by elad-shaked** [comment]
I just realized that had I used `ValidatingValueFactory`, an exception would have been thrown at IRI creation. I am fine with closing this ticket, but it it up to you.

**Comment by jeenbroekstra** [comment]
Yes, this is more or less as expected. The SimpleValueFactory does not do any extensive syntax validation on IRIs for performance reasons.
