### ISSUE TITLE
Exclude (unneeded ?) guava transitive dependencies

### ISSUE THREAD

**Issue by barthanssens** [eclipse/rdf4j#2552]
Upgrading guava  (https://github.com/eclipse/rdf4j/issues/1097) seems to introduce new dependencies that may not be necessary (or may need a CQ if they are necessary, since they are distributed in the SDK zip)

Check if we can exclude 

- [x] failureaccess-1.0.1.jar (CQ22654)
- [x] listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar (CQ22657)
- [x] jsr305-3.0.2.jar (CQ18738)
- [x] checker-qual-2.11.1.jar (CQ22650)
- [x] error_prone_annotations-2.3.4.jar (CQ21492)
- [x] j2objc-annotations-1.3.jar (CQ21995)

See also https://github.com/google/guava/issues/3437

**Comment by jeenbroekstra** [comment]
Since we already did a release with these included, we'll need to get them CQ'd and approved.

**Comment by barthanssens** [comment]
Ow OK... on it...

**Comment by jeenbroekstra** [comment]
Thanks Bart!

**Comment by barthanssens** [comment]
@jeenbroekstra (former) dependencies approved, so we're good :-) Only keeping 2 dependencies that seem to be sometimes required
