### ISSUE TITLE
oer.model.impl.AbstractModel.hashCode() and equals() violate contract

### ISSUE THREAD

**Issue by knoan** [eclipse/rdf4j#2560]
**How to reproduce**

Run the attached test.

**Expected behaviour**

Test passes with equal hash codes.

**Actual behaviour**

Test fails with different hash codes, violating the general `Object.equals()/hashCode()` contract, which requires that `x.equals(y) => x.hashCode() == y.hashCode()`

**Notes**

- the issue lies with the usage if the `Models.isomorphic()` method in the `AbstractModel.equals()` method, which causes bnode ids to be ignored in equality tests while they are being considered in hash code computation
- in a real-world context, the issue is not systematic, as it depends on specific combinations of randomly generated bnode ids
- the issue is probably not critical, as models are unlikely to be used as map keys

[AbstractModelTest.java.zip](https://github.com/eclipse/rdf4j/files/5306220/AbstractModelTest.java.zip)

**Comment by jeenbroekstra** [comment]
Yeah that's not right. We should not be using the isomorphic comparison as part of the object equality check. Good find.

**Comment by hmottestad** [comment]
Btw. If we stop using isomorphic as part of the model equality code we could break existing code. I recommend we release this as part of a minor release rather than a patch release.

**Comment by jeenbroekstra** [comment]
I agree. I think we can treat this as a bug and therefore not backwards-incompatible (so it doesn't require a major release) but it's been wrong sufficiently long that I think fixing this as a patch is going to catch people out. We'll need to add something relevant to the release notes as well.

**Comment by jeenbroekstra** [comment]
The simplest fix for this is to just remove the use of Models.isomorphic from the equals method (and in fact just not overriding the equals method at all and just relying on the superclass equals method). With the test case @knoan provided above, that will result in the equals method no longer returning true for the two models with different bnodes.
