### ISSUE TITLE
Specify Triple.equals()/.hashCode() implementation

### ISSUE THREAD

**Issue by knoan** [eclipse/rdf4j#2564]
Given that the general contrat for `Object.equals()/.hasCode()` requires that

```java
x.equals(y) => x.hashCode() == y.hashCode()
```

and `Value/Statement` interfaces defines specific requirements for the `.equals()` method, e.g.

```java
/**
 * Compares a statement object to another object.
 *
 * @param other The object to compare this statement to.
 *
 * @return <tt>true</tt> if the other object is an instance of {@code Statement}
 * and if their subjects, predicates,objects and contexts are equal.
 */
```

all implementations **must** share the same `.hashCode()` algorithm: they are currently not at liberty to define their own hashing strategy.

Incompatible definitions would break places where different instances are used as map keys/values or collection entries relying on the hashing strategy implemented by the different classes, e.g.

```java
package org.eclipse.rdf4j.sail.memory.model;

public class MemValueFactory extends AbstractValueFactory {
    
	private synchronized MemTriple getMemTriple(Triple triple) {
		if (isOwnMemValue(triple)) {
			return (MemTriple) triple;
		} else {
			return tripleRegistry.get(triple);
		}
	}
    
}
```

Here `tripleRegistry.get(triple)` won't locate an existing triple unless `triple` shares the `.hashCode() `  algorithm with `MemTriple`…

---

Unfortunately I don't think we have an easy way to enforce this constraint, unless we turn `Value/Statement` interfaces into abstract base classes with `final` implementations for `.equals()/.hasCode()` methods…

Default implementations in interfaces are also not viable as default interface methods can't override `Object` methods.

For the time being:

- the issue must be prominently documented in javadocs
- all implementations must be reviewed to ensure uniformity (e.g. `MemTriple` doesn't extend a base class and directly implements `.hashCode()` using Guava's `Objects.hashCode()`, which is by chance equivalent to the `java.util.Objects.hash()` method used elswehere)

**Comment by knoan** [comment]
Some implementations (e.g.`ExtensibleContextStatement`) are actually overriding `.equals()/.hashCode()` and are at risk of inconsistencies when mixed with different implementations.

**Comment by knoan** [comment]
> the issue must be prominently documented in javadocs

Initially addressed as part of PR #2546

**Comment by knoan** [comment]
>  I don't think we have an easy way to enforce this constraint

As a stopgap measure, we could:

- make all `.equals()/hashCode()` methods final in `oer.model.base.Abstract*` base classes being defined in  #2546
- require in the companion `oer.model.*Test` abstract test suite that value implementations extends the corresponding abstract base class
- make sure that every value implementation has a test suite extending the corresponding abstract one

**Comment by jeenbroekstra** [comment]
I am not really happy that we are mixing this up with the PR about migrating to a standalone API. It would have been easier to deal with in a separate PR. It is not trivial to deal with in a backward compatible manner.

> all implementations must share the same .hashCode() algorithm: they are currently not at liberty to define their own hashing strategy.

This is true for `Statement` and `Triple`, but not for `Value` in general, which doesn't have an interface-level contract on the equals method. 

For the various Value subtypes, the state of affairs is as follows I think:

   - [Literal](https://rdf4j.org/javadoc/latest/index.html?org/eclipse/rdf4j/model/Literal.html) and [BNode](https://rdf4j.org/javadoc/latest/index.html?org/eclipse/rdf4j/model/BNode.html) have properly addressed their hashCode and equals contracts and need no further work.
  - IRI has a possible improvement by switching to explicitly using `stringValue` (issue #2565) . I think it is a good idea but it _is_ backward incompatible, so we'll need to do that as part of a major release.
 - Statement is mostly fine except the `hashCode` implementation is not fully specified in the javadoc. But I see you've dealt with that as part of #2538 .
 - Triple is currently underspecified, and that needs addressing. I am fine with addressing that on this ticket, and given that `Triple` is still experimental I see no objection to treating this as a bug fix.

**Comment by knoan** [comment]
> I am not really happy that we are mixing this up with the PR about migrating to a standalone API. It would have been easier to deal with in a separate PR. 

That was my goal in opening this ticket. The idea is to explicitly document in #2538 the current state of affairs and to deal with any refinement in future PRs:

- IRI improvements are already on #2565
- I'll decouple immediately additional specs on Triple to a separate PR referencing this issue

> This is true for Statement and Triple, but not for Value in general, which doesn't have an interface-level contract on the equals method.

AFAIU, the current javadocs actually include equals/hashCode contracts for BNode/IRI/Literal, e.g.

> @return <tt>true</tt> if the other object is an instance of {@link BNode} and their IDs are equal, <tt>false</tt> otherwise.
> The hash code of a blank node is defined as the hash code of its identifier: <tt>id.hashCode()</tt>.

> 
 #2538:

- clarifies some details (e.g. IRIs being compared on toString()) without introducing further constraints
- adds an interface-level warning about the presence of an equal/hashCode contract

Let mew know if you deem more appropriate to decouple these edits to a separate PR.

**Comment by knoan** [comment]
> clarifies some details … without introducing further constraints

Possibly beyond this definition:

- the addition of  an interface-level .equals()/.hashCode() contract on Namespace (already discussed elsewhere)
- the documentation of the _de facto_ hashing algorithm on Statement, which isn't included the current javadocs

> @return a hash code for this statement computed as {@link java.util.Objects#hash Objects.hash}(
        {@link #getSubject()}, {@link #getPredicate()}, {@link #getObject()}, {@link #getContext()})

**Comment by jeenbroekstra** [comment]
> > I am not really happy that we are mixing this up with the PR about migrating to a standalone API. It would have been easier to deal with in a separate PR.
> 
> That was my goal in opening this ticket. The idea is to explicitly document in #2538 the current state of affairs and to deal with any refinement in future PRs:
> 
> * IRI improvements are already on #2565
> * I'll decouple immediately additional specs on Triple to a separate PR referencing this issue

That sounds like a good approach, and apologies if my remark sounded a bit surly.

> > This is true for Statement and Triple, but not for Value in general, which doesn't have an interface-level contract on the equals method.
> 
> AFAIU, the current javadocs actually include equals/hashCode contracts for BNode/IRI/Literal, e.g.
> 
> > @return true if the other object is an instance of {@link BNode} and their IDs are equal, false otherwise.
> > The hash code of a blank node is defined as the hash code of its identifier: id.hashCode().

Yes, true. My point was that it does this for the individual subtypes of Value, not for Value itself.

> #2538:
> 
> * clarifies some details (e.g. IRIs being compared on toString()) without introducing further constraints
> * adds an interface-level warning about the presence of an equal/hashCode contract
> 
> Let mew know if you deem more appropriate to decouple these edits to a separate PR.

I think with what we have right now in the PR for #2538, I'm fine (I'll try and do another review today btw but I think we're about ready to merge), but I suggest that we do any further clarification and editing on this issue in a separate PR.
