### ISSUE TITLE
Improve Literal.hashCode() contract

### ISSUE THREAD

**Issue by knoan** [eclipse/rdf4j#2566]
The current contract for `Literal/.hashCode()` is based only on `getLabel()` value.

>  @return a hash code for this literal computed as {@link #getLabel()}{@code .hashCode()}

While not incorrect, the requirement could be improved upon by including also the `.getLanguage()/.getDatatype()` values already considered in `.equals()`, as

> @return a hash code for this literal computed as {@link java.util.Objects#hash(Object...)}({@link #getLabel()}, {@link #getLanguage()}, {@link #getDatatype()})

Concrete implementations currently overriding these methods must be aligned as per #2564.

**Comment by jeenbroekstra** [comment]
This was done before (#649), and then reverted (#668). See extensive discussion on #665.

**Comment by knoan** [comment]
Got it. Added an implementation not as part of #2546
