### ISSUE TITLE
Errors in custom functions are not thrown

### ISSUE THREAD

**Issue by D063520** [eclipse/rdf4j#2578]
Hello,

I noticed the following .... an error thrown in a custom function is not thrown to the user but null is returned instead in the result set.

To reproduce just take the class Example15SimpleSPARQLQuery in org.eclipse.rdf4j.examples.repository and substitute the give query with:

```
String queryString = "PREFIX ex: <http://example.org/> \n";
			queryString += "PREFIX foaf: <" + FOAF.NAMESPACE + "> \n";
			queryString += "SELECT ?s (<http://example.org/custom-function/palindrome>(?palindrom, ?s) as ?n) \n";
			queryString += "WHERE { \n";
			queryString += "    ?s a ex:Artist; \n";
			queryString += "       foaf:firstName ?palindrom .";
			queryString += "}";
```

which is calling the palindrom function defined in the repo. The result is:

```
?s = http://example.org/Picasso
?n = null
?s = http://example.org/VanGogh
?n = null
``` 

**Note: I'm passing two arguments even if the function takes only one. So instead of trowing an error the variable is set to null.**

The workflow:

In the class org.eclipse.rdf4j.examples.function.PalindromeFunction the following is throw:

```
throw new ValueExprEvaluationException(
					"palindrome function requires" + "exactly 1 argument, got "
							+ args.length);
```

but this is catched in org.eclipse.rdf4j.query.algebra.evaluation.iterator.ExtensionIterator line 45

```
} catch (ValueExprEvaluationException var7) {
                    targetBindings.setBinding(extElem.getName(), (Value)null);
 }
```

So the user never sees the error but only that the value is null. I would say this is a bug, or is this expected behavieur?

Salut
D063520

**Comment by barthanssens** [comment]
Well, this behavior seems to match the SPARQL query specification, section 10 (https://www.w3.org/TR/sparql11-query/#assignment),

> If the evaluation of the expression produces an error, the variable remains unbound for that solution but the query evaluation continues.

So I'd say that RDF4J is correct in not throwing an error and returning null ... (@jeenbroekstra  ?)

**Comment by jeenbroekstra** [comment]
@barthanssens that is exactly right.

**Comment by jeenbroekstra** [comment]
I hope that answers your qestion @D063520 .

**Comment by D063520** [comment]
Thank you for the explanation!
