### ISSUE TITLE
Unused Field

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [eclipse/rdf4j#2584]
https://github.com/eclipse/rdf4j/blob/6ac2054b4f9bcbb94dc9250eebca3d76d76b20e5/core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/ast/ASTUpdateContainer.java#L14

This field is never used.

**Comment by hmottestad** [comment]
Generated by javacc.
