### ISSUE TITLE
Unused variable

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [eclipse/rdf4j#2585]
https://github.com/eclipse/rdf4j/blob/6ac2054b4f9bcbb94dc9250eebca3d76d76b20e5/core/spin/src/main/java/org/eclipse/rdf4j/spin/function/spif/ConvertSpinRDFToString.java#L56

This variable is never used.

**Comment by hmottestad** [comment]
This is in the deprecated spin module.
