### ISSUE TITLE
Decouple vocabularies to a dedicated maven module

### ISSUE THREAD

**Issue by knoan** [eclipse/rdf4j#2589]
As suggested in the initial discussion for #2538.

> I would ideally like things split up even further, for example a separate 'rdf4j-vocabularies' module would be useful

Standalone vocabularies would improve modularisation and portability to limited devices.

PR in progress (branched from `develop` to leverage the abstract value base classes introduced with #2546).

**Comment by barthanssens** [comment]
Would also make it easier to add additional vocabulary modules from other sources.

IIRC most (all ?) of the vocabularies are either RDF4j-specific vocabularies or W3C vocabularies, but in the future there could also be a separate e.g. rdf4j-vocabularies-schemaorg and rdf4j-vocabularies-semiceu.

**Comment by knoan** [comment]
> most (all ?) of the vocabularies are either RDF4j-specific vocabularies or W3C vocabularies

Most, but not all: we have things like DC, GEO, FOAF/DOAP, …

**Comment by knoan** [comment]
PR submitted; I opted for naming the new module `rdf4j-model-vocabulary`, after the migrated `o.e.r.model.vocabulary` package and to keep things consistent with #2546.
