### ISSUE TITLE
Workbench does not support setting the empty prefix

### ISSUE THREAD

**Issue by manuelfiorelli** [eclipse/rdf4j#262]
Inside the Workbench, binding the empty prefix to a namespace causes the definition of a prefix named "namespaces".

This behavior may be determined by a bug in the server-side implementation the [REST API for setting the namespace for prefixes](http://rdf4j.org/doc/the-rdf4j-server-rest-api/#Set_the_namespace_for_a_specific_prefix)

To set the empty prefix, the relevant URL has this form: ``http://....../rdf4j-server/repositories/mem-rdf/namespaces/``

(Note that this URL differs from the one for bulk operations on namespaces, which does not end with a trailing slash)

The buggy behavior may be determined by the following piece of code:

https://github.com/eclipse/rdf4j/blob/releases/2.0.x/core/http/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/namespaces/NamespaceController.java#L54

```
String pathInfoStr = request.getPathInfo();
String[] pathInfo = pathInfoStr.substring(1).split("/");
String prefix = pathInfo[pathInfo.length - 1];
```

Based on the documentation of [String.split(String)](https://docs.oracle.com/javase/8/docs/api/java/lang/String.html#split-java.lang.String-),  in case of a path such as ".../mem-rdf/namespaces/", the last element in the array would be "namespaces" (because trailing empty strings are ignored)

**Comment by manuelfiorelli** [comment]
Hi @jeenbroekstra, I've noticed that you assigned this issue to yourself. In fact, I've developed a solution to this issue together with an associated test. However, I didn't make a PR because of the issue #280, which prevents me from compiling the whole project, and thus execute all the tests.

If you haven't already solved this issue by yourself, I could make a pull request by tomorrow.

**Comment by jeenbroekstra** [comment]
@manuelfiorelli ok that'd be great, saves me some time :) 

I'll have a quick look at #280 as well to see if I can disable it for the time being.

**Comment by manuelfiorelli** [comment]
Hi @jeenbroekstra I've pushed my proposed solution to a dedicated branch in my fork of the rdf4j project.

I can compile the whole project (after disabling the tests), and then the relevant tests for the issue pass.

(Also, I've manually checked that now the workbench works)

Do you think that this is enough to make a PR?

**Comment by jeenbroekstra** [comment]
Sounds good to me - just put it up and we can take a look.

**Comment by manuelfiorelli** [comment]
I've created the PR #285

**Comment by jeenbroekstra** [comment]
Marking this as resolved. Can be reopened if you do decide to tweak the csv parsing.
