### ISSUE TITLE
Update installation notes for debian/ubuntu access control restrictions

### ISSUE THREAD

**Issue by rob-metalinkage** [eclipse/rdf4j#2620]
As per discussion here https://groups.google.com/g/rdf4j-users/c/CBDlXBnJIPE deployments fail on current default tomcat9 install for debian and ubuntu ( at least) if the application directory not under /var/lib/tomcat9

Need to update https://rdf4j.org/documentation/tools/application-directory/ at the very least to reflect valid options.

**Comment by barthanssens** [comment]
So in brief: add a `ReadWritePaths` in e.g. /etc/systemd/system/tomcat9.service and do a  `systemctl daemon-reload` and `systemctl restart tomcat9.service`
