### ISSUE TITLE
[SHACL] sh:minInclusive ignores datatype

### ISSUE THREAD

**Issue by veleda** [eclipse/rdf4j#2623]
Property shape:
```
:ageShape

    a sh:PropertyShape ;

    sh:path ex:age ;

    sh:minInclusive 20 ;

    sh:minCount 1 ;

    sh:maxCount 1 ;

    sh:datatype unit:YR .
```

Data graph:
`ex:Subject ex:age "50"^^unit:YR .`

Triggers violation and produces validation report. 
```
_:node1elqq60dmx138 a sh:ValidationResult;
  sh:focusNode <https://www.example.org/Subject>;
  sh:sourceConstraintComponent sh:MinInclusiveConstraintComponent;
  sh:sourceShape <https://www.example.org/ageShape>;
  sh:resultPath <https://www.example.org/age>;
  sh:value "50"^^<http://qudt.org/vocab/unit/YR> .
```

**Comment by hmottestad** [comment]
I've asked on the SHACL mailing list about this. Essentially shacl.org and the reference shacl validator are giving different results for this example. So I'm asking on the mailing list to see if this is expected, and also if there is some way of using `sh:minInclusive` with custom datatypes.

**Comment by hmottestad** [comment]
Quote from Holger

> Hi Håvard,

> yes this is how it is supposed to work, because sh:minInclusive (etc) rely on the SPARQL operators such as < and those operators don't support user-defined datatypes. The SHACL Playground has slightly incorrect handling of datatypes. I guess the best thing you could do is to define a SPARQL-based solution that does something like 

    FILTER (xsd:decimal(?value) < xsd:decimal($minInclusive))

> Holger
