### ISSUE TITLE
TurtleParser does not report line numbers / location in file

### ISSUE THREAD

**Issue by rwm** [eclipse/rdf4j#264]
The class `org.eclipse.rdf4j.rio.turtle.TurtleParser` does not report location info while parsing. Only during start of parsing (line number 1) and after processing a comment (e.g. line that starts with '#').

Instead of during processing comments, the `reportLocation()` method should be called after incrementing the line number  in the method `skipWSC()`.

I also suggest changing the visibility of the method `getLineNumber()` to protected (instead of private). This would allow subclasses to access line number information directly, instead of relying on reportLocation to do the job.

**Comment by ansell** [comment]
Those changes sound good to me, they are proposed in pull request #264 for review.

**Comment by rwm** [comment]
Upon review of the changes, I think I found another bug with the line counting in TurtleParser:
The method `processComment()` does on increase the lineNumber, even though it may/will read a line feed.
To fix this, the `lineNumber` should be incremented in `processComment()` after having read `0x0D`.

Maybe a unit test which verifies the correct line count after reading an example file will help..

**Comment by ansell** [comment]
hi @rwm, I will look into processComment then create a regression test for it and add it to the pull request

**Comment by ansell** [comment]
I added regression tests and a fix for line number counting within comments to the pull request

**Comment by ansell** [comment]
This can be closed as the pull request has been merged.
