### ISSUE TITLE
sh:message ignored when reporting validation result

### ISSUE THREAD

**Issue by abrokenjester** [eclipse/rdf4j#2642]
The `sh:resultMessage` property is intended to provide an easy to read message for a particular shape violation, and is recommended to be  based on the value of the `sh:message` property for a particular shape. For example, when we have the shape:

```
:groupShape a sh:NodeShape ;
   sh:property [
     sh:path :member ;
     sh:minCount 1 ;
     sh:message "There should be at least 1 member in each group" . 
   ].
```

Any group instance that violates this shape constraint should be reported as:

```
[] a sh:ValidationResult;
  sh:resultSeverity sh:Violation;
  sh:sourceShape :groupShape;
  sh:sourceConstraintComponent sh:MinCountConstraintComponent;
  sh:focusNode :group_1;
  sh:resultPath :member;
  sh:resultMessage "There should be at least 1 member in each group" .
```

The current validation report, however, ignores these messages - they are not included in the validation report at all.

**Comment by hmottestad** [comment]
I've changed this issue and the other one from bug to enhancement since it's not something we have implemented or document that we support. It's part of the spec, but we're clear that we haven't implemented the entire spec yet.

**Comment by jeenbroekstra** [comment]
That's up to you, but calling it an enhancement rather than a bug means we can not include a fix for this in a patch release.

**Comment by hmottestad** [comment]
It's consistent with how we have treated SHACL features so far.

**Comment by jeenbroekstra** [comment]
Scheduling to include for 3.6.0, where (if I understand correctly) this will be fixed "for free" by the SHACL AST rewrite.

**Comment by hmottestad** [comment]
We now parse the field, but we don't do anything with it really.
