### ISSUE TITLE
RDF4J SDK download does not work 

### ISSUE THREAD

**Issue by skrobec** [eclipse/rdf4j#2653]
Hello. 

Downloading from - https://rdf4j.org/download/ results in no response. Same for onejar.

**Comment by barthanssens** [comment]
Hmz, strange, works for me, so it could just be a network glitch... Which mirror site are you using ? Could you perhaps try to select another mirror when the download screen appears (I'm using the download server from Twente / The Netherlands) ?

**Comment by skrobec** [comment]
Works today. Did not change anything. Seems fine now.

**Comment by barthanssens** [comment]
Ok, good to know.
