### ISSUE TITLE
Workbench error 

### ISSUE THREAD

**Issue by skrobec** [eclipse/rdf4j#2660]
Hello. 

I´m trying to use rdf4j server and rdf4j workbench on Apache Tomcat 9 Version 9.0.39. After deploying war files in Tomcat manager and clicking on workbench i get the following error. 

![image](https://user-images.githubusercontent.com/22374751/99150892-c9a6c880-2697-11eb-8343-e2a933a2c534.png)

Do you have any idea what might be wrong ?

I downloaded latest SDK RDF4J 3.4.4 . Using java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08). Tried to use OpenJDK 15 but that produced another error. Thanks for help or any ideas.

**Comment by barthanssens** [comment]
Hi,

perhaps it might have something to do with file (write) permissions ... 
Do you use a Linux machine, or was it on Mac or Windows ?

**Comment by skrobec** [comment]
Windows 10 machine. Upon your comment i tried to run Tomcat as admin but it did not change. Still same error. Any idea where could be permission problems on Windows ?

**Comment by barthanssens** [comment]
Strange... is it a new install ? I.e. did you have older versions installed previously, that may left some data files behind ?

This is what worked for me on a Windows 10 machine, with JDK 8 (1.8.0_201):

- downloaded the Tomcat 9.0.39 64-bit zip, and unzipped it in a new directory
- downloaded the latest RDF4J 3.4.4 zip,
- copied the 2 war files to $TOMCAT/webapps
- opened a windows console and started Tomcat (I had to set a JRE_HOME)
- went to http://localhost:8080/rdf4j-workbench/ and created a new repository

By default, data and config files should be created in C:\Users\windows-user-name\AppData\Roaming\RDF4J, so you may want to check if there are two subdirectories (Workbench and a Server) on your machine.

**Comment by barthanssens** [comment]
By any chance, could there be any antivirus/firewall or replication software (network drive / OneDrive sync...) that may interfere with writing / reading files ?

(I haven't encountered such issues with RDF4J, but on my company machine I sometimes do have problems with locked files / directories that can't be written for a brief moment in other applications)

**Comment by skrobec** [comment]
Tomcat is new instalation. With war files, i tried to undeploy them several times, because there was another error before, which was solved by changing java. Could that be problem ?

Also i deployed war files via Tomcat manager, not by copying them as you did. When i click on server, it works. Only workbench throws error. 

In  C:\Users\windows-user-name\AppData\Roaming\RDF4J there indeed are both files as they should be. 

Hmmm im using only windows defender. And i have dead McAffee. Its out of subscription but still is on the PC. Do you think even inactive it could cause some problems ?

Only other thing, that is different is that i run apache on port 8182.

**Comment by barthanssens** [comment]
What might help is (if you haven't tried this already) 

- shut down tomcat and wait until it has stopped completely
- remove the C:\Users\windows-user-name\AppData\Roaming\RDF4J  directory (and subdirectories)
- start tomcat again
- wait a little bit (say, 30 seconds) and then open the workbench in the browser

This should re-create the directories.

If that still does not help: you've mentioned the workbench showed a different error message when using a different Java version (v15). Could you perhaps share that error message as well ? Maybe that one might be easier to fix...

**Comment by tioannid** [comment]
Hi!
I have a similar problem. And I have found a workaround which might help locate the problem.
My configuarion is: VirtualBox v6.0.22 Guest Ubuntu 18.04LTS, 24GB Ram, 4 v-cores,  RDF4J Server 3.4.3+7ffffb7, JDK 1.8.0_211, Tomcat v9.0.1.
Problem: When I start the Worbench war from the tomcat manager page, the url for the workbench tab is "http://localhost:8081/rdf4j-workbench/repositories/NONE/repositories" and it stays there with an empty page indefinitely.
If the user replaces the url with "http://localhost:8081/rdf4j-workbench/repositories" and presses ENTER, the proble is solved, because the page is loaded and after that the url reads "http://localhost:8081/rdf4j-workbench/repositories/NONE/repositories"!!

I hope this helps

**Comment by barthanssens** [comment]
@tioannid thank you for providing the information and workaround !

**Comment by skrobec** [comment]
Thanks for suggestions. 

I tried multiple things but what helped me was to run Tomcat as service, make sure it uses default java path and it is only instance running. I think that at one point i was running 2 intsances of tomcat for some reason and that caused problems, but im not sure exactly what of those things actually helped because i restarted and redoed everything multiple times. 

Again thanks for help.
