### ISSUE TITLE
JSONLDWriter::getSupportedSettings() throws exception

### ISSUE THREAD

**Issue by ignazio1977** [eclipse/rdf4j#2661]
https://github.com/eclipse/rdf4j/blob/0483e977fb6fe945e29e6340620c379b182d279e/core/rio/jsonld/src/main/java/org/eclipse/rdf4j/rio/jsonld/JSONLDWriter.java#L184

This code adds supported settings to the list provided by the ancestor, but in the default implementation that list is an immutable empty list. Calling this method results in an exception:

    java.lang.UnsupportedOperationException
	at java.base/java.util.AbstractList.add(AbstractList.java:153)
	at java.base/java.util.AbstractList.add(AbstractList.java:111)
	at org.eclipse.rdf4j.rio.jsonld.JSONLDWriter.getSupportedSettings(JSONLDWriter.java:184)

**Comment by jeenbroekstra** [comment]
There's actually a broader problem as well, which that several of our writers do not return a complete set of all supported settings.
