### ISSUE TITLE
Workbench + Console cannot load N-Triple file

### ISSUE THREAD

**Issue by tioannid** [eclipse/rdf4j#2667]
Hi,
My configuarion is: VirtualBox v6.0.22 Guest Ubuntu 18.04LTS, 24GB Ram, 4 v-cores, RDF4J Server 3.4.3+7ffffb7, JDK 1.8.0_211, Tomcat v9.0.1.
I am trying to load the following GeoSPARQL N-Triple file (basic1.nt) which contains absolute URIs with Workbench and Console, but it gives error messages.
When I introduce namespace prefixes the same triples (basic1.ttl) which now contain relative IRIs are imported. Obviously this is not N-Triples format, it's Turtle.
In both cases I use the default NativeStore with default vaules.

[BasicTest.zip](https://github.com/eclipse/rdf4j/files/5568023/BasicTest.zip)
I am uploading both files.

For the basic1.nt file I get the following error from the workbench:
![WorkbenchLoadError_basic1_nt](https://user-images.githubusercontent.com/15914587/99691337-cc3b6080-2a91-11eb-911a-b8d9d06504eb.PNG)

For the basic.nt file I get the following error from the verify command of the console:
```
RDF Format is N-Triples
Verifying data...
FATAL ERROR: Not a valid (absolute) IRI: someroad  [line 1]
Unexpected RDFParseException: Not a valid (absolute) IRI: someroad [line 1]
```

For the basic.ttl file I get the following error from the verify command of the console:
```
RDF Format is Turtle
Verifying data...
Data verified, no errors were found
File contains 5 statements
```

Regards

**Comment by tioannid** [comment]
Additionally, I found out that by adding "http://" prefix on the subject IRIs of the basic1.nt N-Triples file the records are imported!!

**Comment by barthanssens** [comment]
Hi,

thanks for reporting.

I have to check the specs, but IIRC N-Triples can only contain absolute IRIs (or blank node) subjects, so basically the baseURI gets ignored when importing N-Triples files.

**Comment by barthanssens** [comment]
Admittedly it may need some more attention in the documentation and tools, but indeed, N-Triple files may only contain absolute IRIs https://www.w3.org/TR/n-triples/#sec-iri, 2.2:

> IRIs may be written only as absolute IRIs

@tioannid  You mentioned that you were able to upload the file when changing the subject IRIs , so would it OK for you if we close the ticket ?
