### ISSUE TITLE
Fix version discrepancies for httpclient/httpcore/commons-lang

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#267]
We currently include httpcore 4.4.4 and httpclient 4.5.2, but have only filed CQs for 4.4 and 4.5. 
Conversely we currently include commons-lang 2.6, but have only filed a CQ for 3.3.2. 

See https://dev.eclipse.org/ipzilla/show_bug.cgi?id=11710

We need to either align our version numbers with the approved CQs or if that's not possible, file new CQs. 

In addition we need to have a quick look at the animal-sniffer annotation package, it looks as if it might accidentally be included in the distribution packages.

**Comment by jeenbroekstra** [comment]
Not sure why we ever filed commons-lang 3.3.2, AFAICT we never actually used that version. Filed a new CQ for inclusion of 2.6: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=11711 . It's a previously approved version so should be resolved quickly.

**Comment by ansell** [comment]
In the short-term, downgrading the 4.4 and 4.5 apache httpclient/httpcore versions should be okay as they generally break the API on minor version bumps, not patch version bumps, but I have only tested JSONLD-Java with the latest versions:

https://github.com/jsonld-java/jsonld-java/blob/master/pom.xml#L42

**Comment by jeenbroekstra** [comment]
Well I already filed CQs for the 4.4.4/4.5.2 releases. Given that they can do these as simple diff reviews I'm hoping they can process them quickly.

**Comment by jeenbroekstra** [comment]
Just noticed that commons-lang3 3.3.2 _is_ included in our download distribution. I'm assuming it's a transitive dependency of sorts. Will verify to see where it comes from and if we can resolve to one or the other version somehow.

**Comment by ansell** [comment]
Opencsv can be replaced by jackson-csv to reduce dependencies if you would like. I have migrated between the two in other projects.

**Comment by ansell** [comment]
Ie, this library: https://github.com/FasterXML/jackson-dataformat-csv

**Comment by ansell** [comment]
You cannot resolve commons-lang3 to commons-lang:2 or vice-versa btw, as they have different package/class names, by the intention of the Apache Commons project strategy for major version bumps.

**Comment by jeenbroekstra** [comment]
I figured as much. I think that for this release I will simply accept the duplication, and we can migrate to a jackson csv in a later patch release.

**Comment by jeenbroekstra** [comment]
All CQs have been turbo-approved.
