### ISSUE TITLE
remove requirement for java 8 environment in release script

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#2698]
The release script checks if the java environment is Java 8. This check is not necessary as the maven build itself ensures our code is compatible with Java 8, and none of the binaries produced on the local system make it into the final release deployment. 

It also makes doing releases harder now that we've chosen to use Java 11 as our default environment for development.

**Comment by hmottestad** [comment]
It was introduced back when the build would fail when producing the javadocs on 9+. May still be a good idea to keep some sort of check, since I’ve especially found that maven plugins have a tendency to break for new java versions.

**Comment by hmottestad** [comment]
Maybe we can have a soft check. Like “You are on version 15, which has not been tested...are you sure you want to continue (y/n)?”
