### ISSUE TITLE
Increase test coverage of QueryBindingSet methods

### ISSUE THREAD

**Issue by JervenBolleman** [eclipse/rdf4j#2724]
Related to #2715, for developing a new QueryBindingSet implementation needs good tests

**Comment by jeenbroekstra** [comment]
Good point. Could perhaps be done as an extension of the abstract `BindingSetTest` (https://github.com/eclipse/rdf4j/blob/master/core/query/src/test/java/org/eclipse/rdf4j/query/BindingSetTest.java)  class.
