### ISSUE TITLE
use release flag for javac to ensure compiled classes are consistent

### ISSUE THREAD

**Issue by JervenBolleman** [eclipse/rdf4j#2739]
I think it would be useful to use `<release>1.8</release>` instead of `<source>1.8</source><target>1.8</target>` in the pom.xml to ensure all compiled code is consistent no matter which version of javac is used to compile it.

This would require that every developer compiles with a javac newer than 1.8.

**Comment by JervenBolleman** [comment]
Reason  I am asking is that I just spend 45 minutes trying to figure out why the native store tests where failing. In the end it was because my javac was newer than my jvm (I had been playing for dayjob with ea vector api).

**Comment by jeenbroekstra** [comment]
I'm not sure I understand what this flag does. There seems to be little documentation (I can't find any reference on the compiler plugin help page at https://maven.apache.org/plugins/maven-compiler-plugin/examples/set-compiler-source-and-target.html). Can you explain the probem you encountered and how this flag will fix it?

Also note: in addition to compiler settings we have the animal-sniffer plugin as part of the build to ensure we don't use non-Java 8 API features. We also _used_ to use the enforcer plugin to ensure produced bytecode was Java 8 compatible but we recently took it out (reasoning that Github action support for Java 8 builds was safe enough - see #2396 ).

**Comment by JervenBolleman** [comment]
[JEP-247](http://openjdk.java.net/jeps/247) explains the reasoning behind the javac level `--release` flag. What happened to me was that I had native store bytebuffer using classes compiled against JDK-11+ using methods that don't exist in 1.8. (new overloads of certain buffer operations). So when running the tests against 1.8 I had `method not found exceptions` when running the tests on the comandline (but being fine in eclipse). The `--release` flag makes sure that such new APIs/methods would not have been compiled into the jar.

**Comment by jeenbroekstra** [comment]
Should that not have been caught by the animal-sniffer plugin then? I'm not against adding this flag, I'm just trying to get clear what it does and doesn't cover. If it overlaps with that plugin we might take the plugin out, and hopefully improve our build time.

**Comment by jeenbroekstra** [comment]
Now that we are over to Java 11 for the develop branch, I'll put this in place and remove the animal-sniffer plugin (because, as far as I can tell, this flag checks exactly the same thing).

**Comment by jeenbroekstra** [comment]
I'll also take the opportunity to bump a few plugin versions and do some more Java 11-related cleanups.
