### ISSUE TITLE
Replace use of `@deprecated` tag with `@apiNote` to document internal use only

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#2755]
In several packages and classes that we have marked `@InternalUseOnly` we have _also_ marked the package/class `@Deprecated`, and are in addition using a `@deprecated` javadoc tag to document the fact that the class is for internal use only. 

While the intent of this is to make it really obvious to third parties that their use of a particular package or class is discouraged (because we don't consider it part of the public API), it is a bit of an "abuse" of the deprecation mechanism. 

It also irritates the heck out of me having to code things within RDF4J where basically _everything_ flags a "deprecated" warning at me. Apart from being annoying it also has the risk of overlooking genuine deprecation warnings.

I suggest that we stop using the deprecation mechanism to mark classes and packages that are for internal use only, and instead just stick to our custom `@InternalUseOnly` annotation, with an `@apiNote` javadoc comment to make it more obvious in the documentation. So for example, this:

```java
/**
 * Processes the prefix declarations in a SPARQL query model.
 *
 * @author Arjohn Kampman
 *
 * @deprecated since 3.0. This feature is for internal use only: its existence, signature or behavior may change without
 *             warning from one release to the next.
 */
@Deprecated
@InternalUseOnly
public class PrefixDeclProcessor {
```

becomes this:

```java
/**
 * Processes the prefix declarations in a SPARQL query model.
 *
 * @author Arjohn Kampman
 *
 * @apiNote This feature is for internal use only: its existence, signature or behavior may change without
 *             warning from one release to the next.
 */
@InternalUseOnly
public class PrefixDeclProcessor {
```

I am not proposing a massive refactor to take care of this everywhere at once by the way - happy to just fix this as we go.

**Comment by jeenbroekstra** [comment]
@hmottestad @barthanssens would appreciate your opinion. Obviously not suggesting to do this in cases that are genuinely considered deprecated.

**Comment by barthanssens** [comment]
Absolutely agree on using InternalUseOnly

(otherwise we'll spend too much time figuring out what really deprecated methods/classes can be removed in, say, major release v4)

**Comment by hmottestad** [comment]
Yeah. It annoys me too. 

One other alternative is to use google guava's annotation `@beta` which at least in IntelliJ gets flagged when you use it, similarly but different from deprecation. 

https://guava.dev/releases/15.0/api/docs/com/google/common/annotations/Beta.html

Also worth noting that in java 9+ deprecation annotation can have a message string. This doesn't really help us though since it would still be too easy to overlook real deprecation.

**Comment by jeenbroekstra** [comment]
I'd rather stick with our own custom annotation than Google's, at least for now - if we adopt `@beta` we'd have to include Guava as a dependency everywhere. And it doesn't seem to be a widely supported annotation (Eclipse does not flag it, for one).

Unless something comes along that solves this in a standardized way, I suggest that for now we just rely on our own custom annotation, prominent mentions in javadoc, and perhaps adding a bit about this to the general programming documentation as well.

**Comment by jeenbroekstra** [comment]
This might allso be something worth looking into: https://stackoverflow.com/questions/1752607/how-to-intentionally-cause-a-custom-java-compiler-warning-message .

**Comment by barthanssens** [comment]
> Unless something comes along that solves this in a standardized way

IIRC shielding internal APIs was one of the objectives for creating the Java modules system, so for JDK9 projects once could argue it has been "solved" (but of course that does not work for JDK8 ...)
