### ISSUE TITLE
Utility functions for easy mapping between prefixed names and IRIs in SPARQL queries

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#2765]
It would be useful to be able to quickly convert from a prefixed name to a full IRI, and the other way around, when working with SPARQL queries in code.

Example uses:

```java
Namespace ex = new SimpleNamespace("ex", "http://example.org");

IRI fullIRI = Values.iri("ex:foo", ex); // fullIRI is http://example.org/foo
String prefixedName = Values.prefixedName(fullIRI, ex); // prefixedName is "ex:foo"
```

Working with a collection of namespaces (e.g. from a Model or a RepositoryConnection):

```java
IRI fullIRI = Values.iri("ex:foo", connection.getNamespaces()); // fullIRI is http://example.org/foo
```

A side utility that would also be useful is a quick way to convert that same collection of namespaces to a SPARQL query prefix declaration header, so that we could for example do something like this:

```java
try(var conn = rep.getConnection) {
   String query = SPARQLQueries.prefixes(conn.getNamespaces) 
                         + "SELECT ?s ?o "
                         + "WHERE {  ?s ex:property ?o . }");
}
```

Up for discussion is exact naming and location of these functions. 

One possibility is  to abstract away from the specifics of SPARQL and instead offer something based on the CURIE spec (https://www.w3.org/TR/curie/). The problem with that is that SPARQL is slightly more restrictive, so not every legal CURIE is also a legal SPARQL prefixed name.

See also user group discussion at https://groups.google.com/d/msgid/rdf4j-users/a8a97b0a-5aae-48ed-a356-15f76ef0d41bn%40googlegroups.com .

**Comment by hmottestad** [comment]
@jeenbroekstra did you ever implement: `String prefixedName = Values.prefixedName(fullIRI, ex); // prefixedName is "ex:foo"` ?

**Comment by jeenbroekstra** [comment]
Huh. No don't think so, completely overlooked that. 

I think its practical use would be limited but if you want we can add a follow-up issue for it.
