### ISSUE TITLE
Reimplement graph isomorphism

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#2768]
The current implementation of graph isomorphism in `Models.isomorphic` is a naive depth-first search that has very poor average-case performance and even potential non-completing (or at least not in reasonable time) performance on even fairly small test cases.

In a technical paper by Aidan Hogen (see http://aidanhogan.com/docs/rdf-canonicalisation.pdf) a more optimized algorithm for isomorphism is proposed. Bonus advantage is that it also offers (sub)algorithms for canonicalizing blank nodes that would be useful for things like skolemization (see also #2734). 

I've done a quick scratchpad spike of comparitive performance of this algorithm against what we have in RDF4J, and it's looking promising. This task is about translating that spike into a full new reimplementation.

**Comment by hmottestad** [comment]
Ooohhhh :)

Would be awesome. I've noticed one of the SHACL tests I have that uses isomorphism to compare results will not complete (AFIK) when the models are sorted. 

I've also in a previous project ended up using Jena specifically for isomorphic, since it's pretty much always faster and always seems to complete. 

Do you know what algorithm Jena uses?

**Comment by jeenbroekstra** [comment]
> Do you know what algorithm Jena uses?

I don't (I do not, as a rule, look at Jena, as I'd rather not be accused of plagiarism). But I imagine it's close to Hogen's algorithm. The notion of using a canonical blank node mapping as a basis for comparison is a fairly well-known one, even from before this paper I believe. And you need a solid theoretical foundation for an algorithm that actually does well on non-trivial examples (graph isomorphism in general is an NP problem).

**Comment by jeenbroekstra** [comment]
> Would be awesome. I've noticed one of the SHACL tests I have that uses isomorphism to compare results will not complete (AFIK) when the models are sorted.

Could you share that with me as an example? I could perhaps use it as one of the tests for the new implementation.

**Comment by jeenbroekstra** [comment]
So the annoying thing is I have this functionally correct now... But it's slightly slower on most benchmarks. The good news is that I suspect I can optimise quite a bit in how data structures are handled internally. 

I also _suspect_ that it's less prone to endless loops depending on sorting of statements. But I need a test case that reproduces that problem to verify that.

**Comment by hmottestad** [comment]
Sorry for being slow @jeenbroekstra . Here is the example that is super slow for me: https://github.com/eclipse/rdf4j/pull/2786

I don't actually know how long time it takes.

**Comment by hmottestad** [comment]
I also added a couple of comments here: https://github.com/eclipse/rdf4j/commit/16a211cc011b29164955491dbb5c591ab946e72d

Dunno if any of them are going to be helpful at all, they are just my immediate thoughts from looking through the code.

**Comment by jeenbroekstra** [comment]
Thanks for that, be aware though I haven't pushed my recent changes yet.

**Comment by hmottestad** [comment]
Could I recommend checking some examples with only blank nodes and plenty of cycles? I reckon those should typically be slow. 

Also just checking two models of the same data that have had their order randomized.

**Comment by somanythings** [comment]
@jeenbroekstra, I'd be keen to see this. I've got a number of cases where on the same dataset it can take anywhere from <1s to 10mins (or never). Not particularly large < 10k triples!. I've been trawling through the code when I finally thought to check if there was an open issue, and well, here it is! :-)

**Comment by jeenbroekstra** [comment]
@somanythings I'd welcome your feedback! Btw I think you may have tried to provide some feedback on a specific commit - could I ask you to instead comment on the pull request (#2787)? Unfortunately I've found the Github UI is a little unreliable  when commenting on commits - it's hard to find those comments back later.
