### ISSUE TITLE
Sparql query parser prefixes support 

### ISSUE THREAD

**Issue by AlyHdr** [eclipse/rdf4j#2769]
Is it possible to tell the query parser to activate some default prefixes so that they don't have to be defined in the SPARQL query. In the code below I'm using the _QueryParserUtil_ to parse the given query, however I might expect some queries that may consider some default prefixes and it will fail with an exception `QName 'ontolex:lexicalForm' uses an undefined prefix` for example.

```
ParsedQuery parsedQuery =
                QueryParserUtil.parseQuery(QueryLanguage.SPARQL, sparqlQuery, null);


        RepositoryConnection connection = repository.getConnection();
        if (parsedQuery instanceof ParsedTupleQuery) {
            TupleQuery query = connection.prepareTupleQuery(sparqlQuery);
            ByteArrayOutputStream out = new ByteArrayOutputStream();
            TupleQueryResultHandler writer = new SPARQLResultsJSONWriter(out);
            query.setMaxExecutionTime(timeout);
            try {
                query.evaluate(writer);
            } catch (QueryEvaluationException q){
                logger.error("This exception was caught ["+q+"]");
            }
            return out.toString("UTF8");
        } 
```

**Comment by hmottestad** [comment]
Unrelated to this issue. Just wanted to let you know that the connection object needs to be closed. Query results typically need to be closed too, but they usually get closed automatically if completely consumed.

**Comment by AlyHdr** [comment]
@hmottestad Ok thanks I will modify this in the code!

**Comment by hmottestad** [comment]
@AlyHdr is this issue related to your issue? https://github.com/eclipse/rdf4j/issues/2765

**Comment by AlyHdr** [comment]
@hmottestad Yes thank you I think the utility provided in #2765 will be useful for my issue.

**Comment by hmottestad** [comment]
Should we close this issue then?
