### ISSUE TITLE
Automate release notes

### ISSUE THREAD

**Issue by hmottestad** [eclipse/rdf4j#2784]
Today we are automating major parts of the release process which makes creating a patch release very comfortable. 

It would be great to extend this to the release notes too, so we don't need to do so much copy pasting. 

What we could potentially automate:
 - closing milestone
 - creating news item with "x number of closed issues"
 - creating release notes with links to milestone
 - updating download links and version numbers
 - creating a GitHub release with a link to the release notes

There would still be a few things that could be hard to automate (like the acknowledgments section), but we could still allow for that to be filled in my hand.

**Comment by hmottestad** [comment]
I would like to recommend something as simple as `sed` but I've run into too many issues between the versions that OS X use and the ones that Linux uses. 

An alternative could be a mustache template.

**Comment by hmottestad** [comment]
Or maybe this: https://www.gnu.org/software/gettext/manual/html_node/envsubst-Invocation.html

**Comment by hmottestad** [comment]
@jeenbroekstra do you think this would be a good idea?

**Comment by jeenbroekstra** [comment]
Anything that makes it easier is good I think, as long as we still have the freedom to adapt/enrich things at the end.

**Comment by barthanssens** [comment]
@hmottestad probably  BSD sed vs GNU sed ?

IIRC gnu-sed can be installed via Homebrew, but I don't know much about MacOS, so I don't know if installing gnu-sed also has an impact on other system scripts (if any) on Mac ...

**Comment by hmottestad** [comment]
> @hmottestad probably  BSD sed vs GNU sed ?
 
Sounds likely. I think I'll try with env replace tool I found. Since that should work the same on both Mac and Linux and not require anyone to install anything special.

**Comment by jeenbroekstra** [comment]
I'm not entirely sure I understand what you have in mind with sed or replace. Isn't this mostly a matter of interacting with the github API ? 

Btw not sure it fits our purpose but this might be worth a look: http://maven.apache.org/plugins/maven-changes-plugin/

**Comment by jeenbroekstra** [comment]
Another approach might be to step away from specific tools, and instead just pick a nice light scripting language that we rely on for this kind of thing, like ruby or python

**Comment by hmottestad** [comment]
Im thinking about creating template files with variables for the various parts. Then fill them in with a bash script (or other scripting language) and then create a PR and push them. 

I was thinking about templates for at least:
 - news post
 - release page
 
And maybe for the download page.

**Comment by hmottestad** [comment]
Btw. The maven changes plugin looks a bit old. Newest version is from 2016.

**Comment by hmottestad** [comment]
Closing the milestone and creating the GitHub release would naturally be GitHub client things.
