### ISSUE TITLE
[Question:] Disable SSL certificate checks for one repo only

### ISSUE THREAD

**Issue by reckart** [eclipse/rdf4j#2793]
I am working with a RepositoryManager that manages several local and remote (SPARQL) repositories. No, some of the remote repositories may have a self-signed SSL certificate and I would like to be able to connect to these while still using proper SSL certificate checking for others.

Is there some way to e.g. to tell the RepositoryManager to inject a non-SSL-validating HTTPClient into certain repositories but not into others or some other way of configuring SSL checking on a per-repository basis?

I could set a non-validating HTTPClient when working directly with SPARQLRepositories in unit tests, but I did not find a way of doing it (in a simple thread-safe way that does not require type-casts) with the RepositoryManager.

**Comment by jeenbroekstra** [comment]
The RepositoryManager currently assumes it uses a single HttpClient object for all remote communication, so it's not currently possible to make it use different instances of HttpClient for different endpoints.

I'm a little rusty on the details of Apache HttpClient itself, but isn't it possible to configure an SSL trust strategy that does certificate checking on some domains but not others? Have a look at https://stackoverflow.com/questions/1828775/how-to-handle-invalid-ssl-certificates-with-apache-httpclient#1828840 for some examples.

**Comment by reckart** [comment]
I'm experimenting now with a custom SSL connection factory which acts as a switch controlled a thread-local variable to decide whether to do certificate verification or not. Doing it simply by URL/domain won't work for me because there might be multiple repositories with the same endpoint but different choices of whether to perform SSL verification or not (because there can be multiple users on the system not knowing of each others repos and they should not have a "shared state").

**Comment by barthanssens** [comment]
Hmz, wouldn't it be easier to just add the certificate to the local truststore and use  HttpClientBuilder with useSystemProperties() to read javax.net.ssl.keyStore ?

**Comment by reckart** [comment]
@barthanssens I am dealing with a web application. The users of the application can register connections to remote SPARQL endpoints. However, the users may not be able to access the trust store and/or change system properties. It could even be that user A registers a connection to SPARQL endpoint X with SSL certificate checking while user B registers the same connection without SSL certificate checking. From the perspective of the system it may not make too much sense. But from the perspective of user A it would be strange if the system would not complain about an invalid certificate while from the perspective of user B, it would be strange if the system did complain.

Having the switching factory I outlined earlier unfortunately does not do the trick - at least not alone. The HTTP client internally uses a connection pool. So I also need to inject information about the SSL certificate checking into the whole thing so that the pool returns a checking/non-checking connection depending on the circumstances. I am trying now to use a custom "UserTokenHandler" for this purpose. The UserTokenHandler is normally used to discern between connections using different credentials - but in theory at least it should also be usable for for my purpose.

**Comment by jeenbroekstra** [comment]
@reckart just coming back to this, a possible workaround would be that you inject a custom-configured HttpClient into a repository _after_ receiving the repository from the manager, via `SPARQLRepository.setHttpClient`. It does mean that you become responsible for managing the lifecycle of that HttpClient.

**Comment by reckart** [comment]
I have built a solution which uses a custom HTTP Client Builder which eventually uses a thread-local variable to determine if a request is done via a certificate-checking or non-checking client... but it feels so hacky that I haven't been brave enough yet to merge it ;) 

https://github.com/inception-project/inception/pull/1976/files

So thanks for the pointer... not sure yet how to proceed. Indeed, we have another issue that we cannot change the remote URL of a SPARQL repository without having to restart the entire application... I guess fixing that would also be related to taking more control over the lifecycle of a repository.

**Comment by jeenbroekstra** [comment]
No worries. I'll close this issue for now. If you feel that there's a specific improvement or fix that needs to happen at the RDF4J end in relation to this, feel free to log a new ticket for that.
