### ISSUE TITLE
SPARQLRepository.add() does not work with blank nodes on Virtuoso

### ISSUE THREAD

**Issue by vemonet** [eclipse/rdf4j#2796]
## The issue in brief

We are trying to load a RDF turtle file containing blank nodes to a Virtuoso SPARQL endpoint using the SPARQLRepository `.add()` method, but Virtuoso does not accept blank nodes with `INSERT DATA`

Is there a way to fix this issue currently? Maybe a parameter to use `INSERT` instead of `INSERT DATA` when doing a `.add()`?

## The issue in detail

We are using the latest tag of the `tenforce/virtuoso` docker image: https://hub.docker.com/r/tenforce/virtuoso 

Code to add the RDF:

```java
File inputFile = new File(filePath);
SPARQLRepository repo = new SPARQLRepository(endpointUrl);
repo.setUsernameAndPassword(username, password);
repo.initialize();
RepositoryConnection conn = repo.getConnection();
conn.add(inputFile, null, Rio.getParserFormatForFileName(inputFile.getName()).get());
```

Error raised:

```
[main] WARN org.eclipse.rdf4j.http.client.SharedHttpClientSessionManager$2 - Server reports problem: Virtuoso 37000 Error SP031: SPARQL compiler: Blank node '_:node1eth5r7vtx1' is not allowed in a constant clause

SPARQL query:
define sql:big-data-const 0 INSERT DATA 
{ 
<http://bio2rdf.org> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://rdfs.org/ns/void#Dataset> . 
<http://bio2rdf.org> <http://rdfs.org/ns/void#classPartition> _:node1eth5r7vtx1 . 
_:node1eth5r7vtx1 <http://rdfs.org/ns/void#class> <http://www.w3.org/2000/01/rdf-schema#Class> . 
_:node1eth5r7vtx1 <http://rdfs.org/ns/void#distinctSubjects> "1"^^<http://www.w3.org/2001/XMLSchema#integer> .
}
```

The issue is that on Virtuoso `INSERT DATA` does not seems to accept blank nodes.

Running the same query with `INSERT` instead of `INSERT DATA` works on Virtuoso 

```sparql
INSERT { 
<http://bio2rdf.org> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://rdfs.org/ns/void#Dataset> . 
<http://bio2rdf.org> <http://rdfs.org/ns/void#classPartition> _:node1eth5r7vtx1 . 
_:node1eth5r7vtx1 <http://rdfs.org/ns/void#class> <http://www.w3.org/2000/01/rdf-schema#Class> . 
_:node1eth5r7vtx1 <http://rdfs.org/ns/void#distinctSubjects> "1"^^<http://www.w3.org/2001/XMLSchema#integer> .
}
```

Note that this query does not work on RDF4J servers (e.g. GraphDB), because RDF4J seems to have implemented SPARQL properly, and requires a `WHERE` clause with `INSERT`, as defined in the w3c recommendation: https://www.w3.org/TR/sparql11-update/#insertData

Is there a way to fix this issue currently? Maybe a parameter to use `INSERT` instead of `INSERT DATA` when doing a `.add()`?

**Comment by barthanssens** [comment]
FWIW , see also discussion on https://github.com/openlink/virtuoso-opensource/issues/126 (appears to be fixed in Virtuoso 8, but not yet in the open source version, so it won't fix this issue :-(  )

**Comment by barthanssens** [comment]
I don't think there is an option to use INSERT instead of INSERT DATA (see https://github.com/eclipse/rdf4j/blob/master/core/repository/sparql/src/main/java/org/eclipse/rdf4j/repository/sparql/SPARQLConnection.java)

Perhaps it could be an option to skolemize the blank nodes ?
I.e.

```
RDFParser  parser = Rio.createParser(RDFFormat...);
parser.getParserConfig().set(BasicParserSettings.SKOLEMIZE_ORIGIN, "http://www.example.com");
```

**Comment by vemonet** [comment]
Thanks a lot for the tips!

Skolemizing is a good work around, hoping the Virtuoso open source release comes soon (maybe every 3 years!)

**Comment by MPParsley** [comment]
@vemonet, would you care to share your docker setup with rdf4j+virtuoso?
