### ISSUE TITLE
OOM in MemoryOverflowModel

### ISSUE THREAD

**Issue by mannyrivera2010** [eclipse/rdf4j#2799]
Given following code.  using http://purl.obolibrary.org/obo/ncit.owl
 ```
    private static ValueFactory vf = SimpleValueFactory.getInstance();

    public static void main(String[] args) throws IOException {
        private static String indexes = "spoc,posc,cosp"; 

         private static String data_directory = "data2";

         File dataDir = new File(data_directory);
         Repository repo1 = new SailRepository(new NativeStore(dataDir, indexes));
         repo1.init();


           try (RepositoryConnection conn = repo1.getConnection();
                     FileInputStream fis = new FileInputStream("ncit.owl");
                ) {
                    conn.begin();
                    conn.add(fis, "", RDFFormat.RDFXML, vf.createIRI(g+i));
                    conn.commit();
                }
                
```

You get following issue: 
```
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at org.eclipse.rdf4j.model.impl.LinkedHashModel$ModelNode.<init>(LinkedHashModel.java:344)
	at org.eclipse.rdf4j.model.impl.LinkedHashModel.asNode(LinkedHashModel.java:554)
	at org.eclipse.rdf4j.model.impl.LinkedHashModel.add(LinkedHashModel.java:150)
	at org.eclipse.rdf4j.model.impl.LinkedHashModel.add(LinkedHashModel.java:48)
	at org.eclipse.rdf4j.sail.nativerdf.MemoryOverflowModel.add(MemoryOverflowModel.java:129)
	at org.eclipse.rdf4j.sail.nativerdf.MemoryOverflowModel.add(MemoryOverflowModel.java:42)
	at org.eclipse.rdf4j.sail.base.Changeset.approve(Changeset.java:276)
	at org.eclipse.rdf4j.sail.base.SailSourceBranch.flush(SailSourceBranch.java:493)
	at org.eclipse.rdf4j.sail.base.SailSourceBranch.compressChanges(SailSourceBranch.java:325)
	at org.eclipse.rdf4j.sail.base.SailSourceBranch.merge(SailSourceBranch.java:302)
	at org.eclipse.rdf4j.sail.base.SailSourceBranch$1.flush(SailSourceBranch.java:175)
```

previous version of RDF4J like 2.5.5 did not have this outOfMemory Issue.

**Comment by hmottestad** [comment]
Try with IsolationLevels.NONE in your begin method. Does that help?

**Comment by hmottestad** [comment]
We should still consider this a bug though since it's an out of memory error in the memory overflow model which is supposed to handle low mem gracefully.

**Comment by hmottestad** [comment]
@jeenbroekstra I presume the problem here is that the LinkedHashModel resizes as it grows so adding an item could trigger it so suddenly use 2x as much memory. Previously we used the TreeModel, but it has some concurrency issues that have been hard to nail down. Maybe a solution would be to reimplement the TreeModel in a more straightforward way with less complexity that could cause concurrency issues.

**Comment by mannyrivera2010** [comment]
Is there a PR that has that change (TreeModel to using LinkedHashModel)?

**Comment by hmottestad** [comment]
https://github.com/eclipse/rdf4j/pull/1523

**Comment by hmottestad** [comment]
Took a quick look at this now, thought I could just throw in the DynamicModel with a TreeMap inside. Unfortunately it's not that simple since the MemoryOverflowModel inherits from the AbstractModel.

**Comment by jeenbroekstra** [comment]
@hmottestad I'm not sure what exactly you have in mind when you say "reimplement the TreeModel in a more straightforward way with less complexity". But it sounds like a lot of work. Perhaps, as a short-term fix, we could look at just reusing TreeModel as-is, but wrapping it in a `Models.synchronizedModel`. It's possible that won't fix it completely as iterators will still not be thread-safe, but it's worth a try.

**Comment by hmottestad** [comment]
I tried the synchronized model and it didn't work.

**Comment by hmottestad** [comment]
By that I mean that when I was trying to figure out the concurrency issues with the native store then first thing I did was to synchronize the tree model, but that didn't help.

**Comment by hmottestad** [comment]
We could instead lower the point where we overflow to disk. So we overflow a little bit earlier than today.

**Comment by jeenbroekstra** [comment]
> We could instead lower the point where we overflow to disk. So we overflow a little bit earlier than today.

Or initialize the internal HashSets with a fixed initial size that is equal to `load_factor * block_size` (or something along those lines) - that should prevent it from resizing before we flush it to disk.
