### ISSUE TITLE
spif:Test-dateFormat-1 test in module rdf4j-spin-sail fails when using the Italian locale

### ISSUE THREAD

**Issue by manuelfiorelli** [eclipse/rdf4j#280]
When compiling the 2.0.x branch, the compilation fails at the module `rdf4j-spin-sail` because of a test failure.

The code below is an actual test report.
```
Running org.eclipse.rdf4j.sail.spin.SpifSailTest
Tests run: 13, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 48.194 sec <<< FAILURE! - in org.eclipse.rdf4j.sail.spin.SpifSailTest
runTests(org.eclipse.rdf4j.sail.spin.SpifSailTest)  Time elapsed: 4.219 sec  <<< FAILURE!
java.lang.AssertionError: http://spinrdf.org/spif#Test-dateFormat-1 expected:<"February 13, 2008"^^<http://www.w3.org/2001/XMLSchema#string>> but was:<"febbraio 13, 2008"^^<http://www.w3.org/2001/XMLSchema#string>>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.eclipse.rdf4j.sail.spin.SpifSailTest.runTests(SpifSailTest.java:94)
```

The actual value contains the word "febbraio", which is the Italian word for February. 

The code below should be the failing test case.

```
spif:Test-dateFormat-1
  rdf:type spl:TestCase ;
  spl:testExpression [
      rdf:type spif:dateFormat ;
      arg:date "2008-02-13"^^xsd:date ;
      arg:pattern "MMMMMMMMM dd, yyyy" ;
    ] ;
  spl:testResult "febbraio 13, 2008"^^xsd:string ;
  rdfs:label "Test-date format"^^xsd:string ;
.
```

Indeed, it requires that the structured date `"2008-02-13"^^xsd:date` is formatted according to the template `"MMMMMMMMM dd, yyyy"`.

The implementation of `spif:dateFormat` seems to use the default locale, which explains the observed behavior.

If the implementation is right, then the tests should be updated to avoid the failure.

**Comment by jeenbroekstra** [comment]
@pulquero I had a quick look around but I can't find any sort of 'official' description of the `spif:dateFormat` function. Is there such a document? In any case - I guess it makes sense that it either uses the platform locale, or the user can somehow _specify_ the locale. It does mean that the test is overly restrictive.

**Comment by pulquero** [comment]
http://spinrdf.org/spif
 

    On Wednesday, 10 August 2016, 22:16, Jeen Broekstra <notifications@github.com> wrote:
 

 @pulquero I had a quick look around but I can't find any sort of 'official' description of the spif:dateFormat function. Is there such a document? In any case - I guess it makes sense that it either uses the platform locale, or the user can somehow specify the locale. It does mean that the test is overly restrictive. —

**Comment by pulquero** [comment]
Can we set the locale for the test by using Locale.setDefault() and restoring it afterwards?
 

    On Wednesday, 10 August 2016, 22:16, Jeen Broekstra <notifications@github.com> wrote:
 

 @pulquero I had a quick look around but I can't find any sort of 'official' description of the spif:dateFormat function. Is there such a document? In any case - I guess it makes sense that it either uses the platform locale, or the user can somehow specify the locale. It does mean that the test is overly restrictive. —

**Comment by jeenbroekstra** [comment]
I found http://spinrdf.org/spif earlier, but  that document does not contain anything about a `spif:dateFormat` function. In fact the only reference to 'dateFormat' I find there is for the `spif:parseDate` function, which is the inverse (creating a dateTime literal from a semi-formatted string).

**Comment by jeenbroekstra** [comment]
Thanks, that sounds like a decent short-term fix. I'll tweak the locale in the test to at least make it succeed for @manuelfiorelli . 

But in the longer run I guess we need to take a look at where this function comes from, and whether it should be included in the set of supported spin functions at all.

**Comment by manuelfiorelli** [comment]
I am unsure whether a should log a separate bug, but after fetching recent commits I've found another test failing for exactly the same locale-dependent behavior:

```
  <testcase name="testFatalErrorPrologContent" classname="org.eclipse.rdf4j.rio.rdfxml.RDFXMLParserTest" time="0.013">
    <failure message="expected:&lt;[Content is not allowed in prolog]. [line 1, column 1]&gt; but was:&lt;[Il contenuto non è consentito nel prologo]. [line 1, column 1]&gt;" type="org.junit.ComparisonFailure"><![CDATA[org.junit.ComparisonFailure: expected:<[Content is not allowed in prolog]. [line 1, column 1]> but was:<[Il contenuto non è consentito nel prologo]. [line 1, column 1]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.eclipse.rdf4j.rio.rdfxml.RDFXMLParserTest.testFatalErrorPrologContent(RDFXMLParserTest.java:137)
]]></failure>
  </testcase>
```

**Comment by jeenbroekstra** [comment]
Can I just say it's great to have you on board @manuelfiorelli  - this should keep us on our toes to take proper care of locale issues :) 

I'll take a look at both problems at the same time - even if it is in a different test suite.

**Comment by ansell** [comment]
@manuelfiorelli That failing test was a test I just added yesterday in pull request #282 so sorry for that regression. It may be easiest to disable that line in RDFXMLParserTest and the equivalent line in TriXParserTest.

**Comment by jeenbroekstra** [comment]
PR up with fixes/workarounds for both issues.

**Comment by manuelfiorelli** [comment]
@jeenbroekstra @ansell Following this example, I was able to [skip tests](http://maven.apache.org/surefire/maven-surefire-plugin/examples/skipping-test.html) during the compilation, by executing Maven as follows:
```
mvn install -Dmaven.test.skip=true
```
In fact, I've used the nice checkbox provided by Eclipse.

**Comment by ansell** [comment]
In general you will want to be running the following command if you are developing new code and tests, as it has slightly different consequences. In the command below Maven attempts to compile the tests, so will pick up any syntax errors that are in tests, but will not execute them. In your version, it doesn't attempt to compile tests, so won't pick up any syntax errors in the test code. 

```
mvn install -DskipTests
```

I don't think RDF4J has any inherited test-jar dependencies, as we do them slightly differently just using jar and dedicated testsuite modules, but in some maven projects -Dmaven.test.skip can cause compilation to also fail.

**Comment by manuelfiorelli** [comment]
Hi @ansell I was not aware of the difference between the two options. Thank you for the explanation.

**Comment by jeenbroekstra** [comment]
Merged, marking this as closed. @pulquero still curious about the origin of `spif:dateFormat` though :)

**Comment by pulquero** [comment]
Does tbc not have it?


Sent from Samsung Mobile

-------- Original message --------
