### ISSUE TITLE
move dependency scope declaration to actual dependency instead of management

### ISSUE THREAD

**Issue by reckart** [eclipse/rdf4j#2812]
When a downstream project imports the RDF4J management, it also gets the dependency management for commons-codec bound as a "runtime" dependency from `org.eclipse.rdf4j:rdf4j:pom:3.5.1`

```
			<dependency>
				<groupId>commons-codec</groupId>
				<artifactId>commons-codec</artifactId>
				<version>1.13</version>
				<scope>runtime</scope>
			</dependency>
```

This implicitly turns all the dependencies that the downstream project may have on commons-codec from compile scope (default) to the runtime scope and breaks compilation.

In my experience, it is generally a good idea not to specify scopes in the dependency management section at all and use it only in the dependencies section.

**Comment by jeenbroekstra** [comment]
Why would a downstream project ever import our root pom directly?

**Comment by jeenbroekstra** [comment]
It's easy enough to fix btw, I'll put up a PR in a sec. But I'd appreciate it if you could give me some background on when this is a problem.

**Comment by reckart** [comment]
Well, yes - I was as surprised as you are. I didn't import the root POM - just the BOM. But still Maven picks up the managed dependency from the root POM. Here is an example:

```
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>test</groupId>
  <artifactId>rdf4j-dependeny-import-test</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.eclipse.rdf4j</groupId>
        <artifactId>rdf4j-bom</artifactId>
        <version>3.5.1</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>commons-codec</groupId>
      <artifactId>commons-codec</artifactId>
    </dependency>
  </dependencies>
</project>
```

Result:

<img width="550" alt="2021-02-10_09-10-36" src="https://user-images.githubusercontent.com/1410238/107482526-18250f80-6b80-11eb-9434-7f64f7e0f3b6.png">

**Comment by reckart** [comment]
I guess one could also take the perspective: the actual issue is that importing the BOM does not only import RDF4J versions but also versions of third-party libraries.

**Comment by jeenbroekstra** [comment]
> I guess one could also take the perspective: the actual issue is that importing the BOM does not only import RDF4J versions but also versions of third-party libraries.

But that is a feature, not a bug :) You can of course always override this if you want. The idea is that you don't have to figure out for yourself what versions of third party libraries are compatible with rdf4j.

**Comment by reckart** [comment]
True - but then we're back at: we want to have the managed versions, but managing the scope does more harm than good.

**Comment by jeenbroekstra** [comment]
Yeah fair enough - though there too you can of course override locally, but I'll grant you that it is less obvious. PR is up.

**Comment by jeenbroekstra** [comment]
By the way you mentioned commons-codec here specifically, but presumably the principle applies for any dependencies managed in the root pom.

**Comment by reckart** [comment]
Well yeah probably so. But unless they override the scope they do not interfere with the rest of my project setup. In JAR module POMs, I declare compile dependencies plain (i.e. without scope or version) fully relying on dependency management. That works fine and largely as expected. But if the imported dependency management starts changing the default scope of dependencies from compile to something else (e.g. to runtime), then the compilation breaks because the classes of that dependencies can no longer be found during the compile stage.
