### ISSUE TITLE
Maven lifecycle mapping errors when importing into Eclipse

### ISSUE THREAD

**Issue by reckart** [eclipse/rdf4j#2813]
When importing the develop branch into Eclipse, I get this error basically on every project:

```
Plugin execution not covered by lifecycle configuration: au.com.acegi:xml-format-maven-plugin:3.1.2:xml-format (execution: default, phase: process-resources)
```

**Comment by jeenbroekstra** [comment]
Thanks, I kept meaning to get back to that, but it slipped my mind. 

Btw, a workaround for this is to just disable the formatting profile in Eclipse:

![Screenshot from 2021-02-10 14-51-36](https://user-images.githubusercontent.com/728776/107462167-9baa2500-6baf-11eb-8c6e-d7f6b122535f.png)

To get there, right-click on the project in Eclipse, and select "Maven" -> "Select Maven Profiles...".
