### ISSUE TITLE
RDFLoader doesn't follow redirections from HTTP to HTTPS

### ISSUE THREAD

**Issue by manuelfiorelli** [eclipse/rdf4j#2828]
The following piece of code should resolve the IRI of a DBpedia resource into its RDF description.

```java
RDFLoader rdfLoader = new RDFLoader(new ParserConfig(), SimpleValueFactory.getInstance());
RDFHandler rdfHandler = new StatementCollector();
rdfLoader.load(new URL("http://dbpedia.org/resource/Rome"), null, null, rdfHandler);
```

Unfortunately, the code throws this exception:

```
Exception in thread "main" org.eclipse.rdf4j.rio.UnsupportedRDFormatException: Could not find RDF format for URL: /resource/Rome
	at org.eclipse.rdf4j.repository.util.RDFLoader.lambda$null$1(RDFLoader.java:137)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.eclipse.rdf4j.repository.util.RDFLoader.lambda$load$2(RDFLoader.java:136)
	at java.util.Optional.orElseGet(Optional.java:267)
	at org.eclipse.rdf4j.repository.util.RDFLoader.load(RDFLoader.java:135)
	at TestRDFLoader.main(TestRDFLoader.java:17)
```

The issue can be replicated using RDF4J 3.6.0-M3 and AdoptOpenJDK 1.8.0_252

The issue seems to be caused by the fact that when asked to resolve a resource IRI (e.g. 'http://dbpedia.org/resource/Rome'), DBpedia first redirects the client to an address using `HTTPS` (e.g. 'https://dbpedia.org/resource/Rome'), which in turn returns the appropriate representation (e.g. HTML, Turtle, RDF/XML, etc.) by content negotiation.

Under the hoods, `RDFLoader` uses `java.net.URL`, which seems not to follow such redirects, seemingly because of security concerns.

My workaround was to copy the implementation of `RDFLoader`, while switching to `HttpClient`: https://bitbucket.org/art-uniroma2/semantic-turkey/src/7708c555f5b86e2628a1084cdebb7233ac6e4cb2/core-services/src/main/java/it/uniroma2/art/semanticturkey/services/core/ResourceView.java#lines-1108

**Comment by manuelfiorelli** [comment]
If you are interested I can upstream my change.

**Comment by jeenbroekstra** [comment]
Thanks for reporting this @manuelfiorelli. I read up a bit on the potential security concern and am a little on the fence over whether we should automatically redirect. Then again, Apache HttpClient make it their default behavior, and of course it's still possible to disable it using a system property if desired, so I think we are safe enough. 

A pull request would be appreciated! Against master branch if you can please, let's classify this as a bug.

**Comment by manuelfiorelli** [comment]
Hi @jeenbroekstra Unfortunately, I realized that my workaround is not a good fit for the general implementation inside the `RDFLoder`. Since I use `HttpClient`, I can only handle HTTP(S) URLs. Beyond uncommon situations (e.g. SFTP URLs), we would break legitimate code such as the following:
```
RDFLoader rdfLoader = new RDFLoader(new ParserConfig(), SimpleValueFactory.getInstance());
RDFHandler rdfHandler = new StatementCollector();
rdfLoader.load(TestRDFLoader.class.getResource("test.owl"), null, null, rdfHandler);
```
Indeed, the method `getResource` may use a range of protocols, in including `file`, `jar`, etc., which are definitely not supported by an HTTP-only implementation.

We might decide to use `java.net.URL`, while switching to `HttpClient` for HTTP(S) requests: however, I doubt whether this approach might seem arbitrary and introduce inconsistencies in the behavior of the loader.

**Comment by jeenbroekstra** [comment]
Fair point. An alternative solution would be to just stick with java.net.URL for everything, but to do redirect handling ourselves when the response is a 302: we can inspect the redirect target and if it is a simple http -> https redirect follow it ourselves.

**Comment by manuelfiorelli** [comment]
Hi @jeenbroekstra I'm sorry for the late reply, but these days were very busy. I think that that the idea to use `java.net.URL` and manually follow redirects if necessary is fine (and similar to what is proposes in most places on the Web). I'll try to come up with a implementation by the start of next week.

**Comment by jeenbroekstra** [comment]
@manuelfiorelli that would be great, thanks. Keep us posted. We are planning a to do a 3.6.1 patch release very soon (end of this week), do you think you'll be be able to submit something in time for that?

**Comment by manuelfiorelli** [comment]
Hi @jeenbroekstra . Apologize for the late reply. I eventually made a PR.
Since the creation of the issue, I noticed that DBpedia happens to do multiple redirects alternative HTTP and HTTPS:
So I decided to follow all redirects by hand. My code honors `http.maxRedirects`. Not sure if further checks should be implemented.
