### ISSUE TITLE
Release notes and news item 3.6.0

### ISSUE THREAD

**Issue by hmottestad** [eclipse/rdf4j#2838]
Using this issue to discuss what should be included.

Milestone: https://github.com/eclipse/rdf4j/milestone/63?closed=1

**Comment by hmottestad** [comment]
Got a bit late tonight. Will have to look at this tomorrow.

**Comment by jeenbroekstra** [comment]
Acknowledgements to include (apart from the usual suspects) Richard Eckart de Castilho.

**Comment by jeenbroekstra** [comment]
I think nice things to call out in the news item are (in no particular order):

1. new font for the Workbench UI (with a little screenshot perhaps);
2. new implementation of SHACL and what that means for ShaclSail users (better, faster, more coverage, etc) 
3. new graph isomorphism algorithm

On the graph isomorphism thing, some draft copy:

> ## faster isomorphism detection
> The graph isomorphism algorithm (used to check if models are equivalent under a blank node mapping by the `Models.isomorphic` utility function) has been completely reimplemented. Where the previous naive depth-first search approach had very poor performance (sometimes not terminating at all even on relatively small models), the current implementation, based on an approach outlined by Aidan Hogan in his 2017 paper "Canonical Forms for Isomorphic and Equivalent RDF Graphs: Algorithms for Leaning and Labelling Blank Nodes"([PDF](http://aidanhogan.com/docs/rdf-canonicalisation.pdf) ) has been shown to have very good performance characteristics for almost all practical cases, and is guaranteed to terminate in reasonable time.

**Comment by jeenbroekstra** [comment]
(as an aside I don't want to call attention in the release announcement to the fact that the legacy algorithm is still available - let's keep that for when people explicitly ask about it)

**Comment by hmottestad** [comment]
Got late today again. Spent the time I had available tracking down a really annoying bug in InnerJoin algorithm. The kind of bug that hides when you start poking around.

**Comment by jeenbroekstra** [comment]
That's all good. Fwiw if time is short we can of course do the release over several days. Just because the artifacts are available on central does not mean we _have_ to officially announce it right away. So if necessary you can do the build this weekend to have it "unoffically" available for download, and then we finish the official release notes + announcement early next week.
