### ISSUE TITLE
Introduce RDFParser and RDFWriter implementation for Newline Delimited JSON-LD format

### ISSUE THREAD

**Issue by desislava-hristova-ontotext** [eclipse/rdf4j#2840]
A "Newline Delimited JSON" exists, see [NDJSON website](http://ndjson.org/) and [specification](https://github.com/ndjson/ndjson-spec). Similar to it, a multiline JSON-LD is used in the community, i.e in [Springer Nature SciGraph dataset](https://sn-scigraph.figshare.com/).

Implement an RDFParser and RDFWriter that reads/writes such a format and thereby formalize the format:

- Each line is a JSON-LD object
- Empty lines allowed (same as Newline Delimited JSON) as it is more flexible
- MIME type: **application/x-ld+ndjson** derived from the existing MIME type for JSON-LD **application/ld+json** and the MIME type of Newline Delimited JSON **application/x-ndjson**
- File extension: **.ndjsonld** derived from the file extension for JSON-LD **.jsonld** and the file extension for Newline delimited JSON **.ndjson**.

**Comment by VladimirAlexiev** [comment]
@desislava-hristova-ontotext @jeenbroekstra 
There is https://w3c.github.io/json-ld-streaming/ which says things like "put `@context` first in file" and "put `@id` first in object".
So it doesn't rely on newline markers for streaming, but on a slightly restricted JSON structure.
Implementation:
- https://github.com/rubensworks/jsonld-streaming-parser.js
  - NDJSONLD support may also be added: https://github.com/rubensworks/jsonld-streaming-parser.js/issues/64
- https://github.com/rubensworks/jsonld-streaming-serializer.js

Is that any better or more "standards compliant"?
