### ISSUE TITLE
Upgrade JUnit to Junit5/Jupiter

### ISSUE THREAD

**Issue by JervenBolleman** [eclipse/rdf4j#2876]
We should try to upgrade to Junit5. Just a small maintenance task, not urgent.

**Comment by hmottestad** [comment]
Same as https://github.com/eclipse/rdf4j/issues/1563

**Comment by JervenBolleman** [comment]
@hmottestad thanks, I had done an issue search but it had not shown up :( I did notice that a lot of tasks where already done. So I will have a look and see if I can finish it.

**Comment by jeenbroekstra** [comment]
> @hmottestad thanks, I had done an issue search but it had not shown up :( I did notice that a lot of tasks where already done. So I will have a look and see if I can finish it.

I see you've already started using this issue, so I'll just close the older issue as a duplicate.

**Comment by jeenbroekstra** [comment]
CQ for wiremock version bump: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23133

**Comment by jeenbroekstra** [comment]
CQ approved
