### ISSUE TITLE
Add setting to skip using abbreviated numeric literals in Turtle/TriG writer when pretty-printing

### ISSUE THREAD

**Issue by daltontc** [eclipse/rdf4j#2886]
I noticed that when writing out a Turtle/TriG file with the Rio Writer that double datatype literals are converted into scientific notation. Is there a way to preserve the exact format with the datatype when writing out for Turtle/TriG? RDFXML works as expected and writes the datatype and value as expected. Perhaps there is a writer/parser setting that I am missing?

Here is a demo project that writes the files into the different format. https://github.com/daltontc/rdf4jTest/tree/doubleDatatypeWriter

For example, this double `32412341.12312` is written as `3.241234112312E7` with the Turtle/TriG writers. I was expecting it to maintain the original form and have the XSD type on it as well, but instead I get:

```
<https://mobi.com/ontologies/3/2021/A#Adf> <https://mobi.com/ontologies/3/2021/A#prop> 3.241234112312E7 .
```

**Comment by jeenbroekstra** [comment]
This is a consequence of enabling pretty-printing, which in the case of Turtle, uses abbreviated syntax for numeric datatypes if possible (see https://www.w3.org/TR/turtle/#turtle-literals). So if you don't want this, make sure `BasicWriterSettings.PRETTY_PRINT` is set to `false`. 

Just to be clear though: the notation as used is fully standards-compliant rendering of an xsd:double value in Turtle syntax. There is no loss of information here. 

The only reason it doesn't happen in RDF/XML is that RDF/XML syntax has no such rule for rendering these kinds of data types.

**Comment by daltontc** [comment]
That makes sense, but it seems somewhat problematic that the two are considered equivalent statements, but can be loaded in as separate statements in the repo. Wouldn't it make sense for the repository to normalize the data to a single format rather than allow both versions?

Is there a way to keep pretty print but not change the double literals?

**Comment by jeenbroekstra** [comment]
> That makes sense, but it seems somewhat problematic that the two are considered equivalent statements, but can be loaded in as separate statements in the repo. Wouldn't it make sense for the repository to normalize the data to a single format rather than allow both versions?

Normalizing on parsing is not enabled by default but you can enable it, by setting `BasicParserSettings.NORMALIZE_DATATYPE_VALUES` (or the equivalent system property if you want a blanket rule for all parsers). 

> Is there a way to keep pretty print but not change the double literals?

Afraid not, not in the current Turtle writer. But I agree with you that it might be useful to make control over what pretty printing in Turtle does and doesn't touch a little more fine-grained. A new `TurtleWriterSettings.ABBREVIATE_NUMBERS` setting (default to true and only affects output when pretty-printing but you can switch it off) would suit your use case I think.

**Comment by jeenbroekstra** [comment]
This should be relatively straightforward to fix:

1. a new `TurtleWriterSettings` class a boolean setting `ABBREVIATE_NUMBERS` (default to true), controlling how numeric literals are serialized when writing in pretty-print mode;
2. a fix in `TurtleWriter.java`, lines 636-653 to check if this setting is true before applying numeric abbreviation.

**Comment by barthanssens** [comment]
Should be fixed in the PR.

Note that it also affects values with Boolean datatype (which is allowed by the Turtle spec)
