### ISSUE TITLE
Add Path interface to rdf4j-model-api module

### ISSUE THREAD

**Issue by knoan** [eclipse/rdf4j#2890]
In support of use cases like data modelling and linked data navigation, it would be very useful to be able to describe RDF property paths in a consistent way.

`rdf4j-sparqlbuilder` and `rdf4j-queryalgebra` modules contain path-related classes, but they are deeply ingrained with the respective operational internals and not immediately available for declarative path description.

Submitting a PR for `Path` interface in the `rdf4j-model-api` module.

**Comment by jeenbroekstra** [comment]
Can you give an example/use case to illustrate what this is  about?

**Comment by knoan** [comment]
> Can you give an example/use case to illustrate what this is about?

See https://github.com/eclipse/rdf4j/pull/2891#issuecomment-791961433

**Comment by jeenbroekstra** [comment]
@knoan I hope I didn't discourage you... I'm happy to have a chat about any improvements for linked data architectures you have in mind.

**Comment by knoan** [comment]
Never mind… I wasn't that happy with this approach and your feedback motivated me to look for something cleaner.
