### ISSUE TITLE
Upgrade animal-sniffer to version 1.20

### ISSUE THREAD

**Issue by JervenBolleman** [eclipse/rdf4j#2899]
The current version does not understand multi-release jars.
This might affect upgrading other dependencies to their current versions.
I suggest we just upgrade to the current version 1.20.

- [ ] CQ 23136

**Comment by barthanssens** [comment]
Good idea, though it might require a new "works-with" CQ (https://dev.eclipse.org/ipzilla/show_bug.cgi?id=20318 mentions animal sniffer up to 1.18)

**Comment by jeenbroekstra** [comment]
@barthanssens fwiw there was  a clarification by the EMO that we're not really required to file CQs for maven plugins. Quote:

> [..] The idea of grouping many "build and test" libraries was to avoid requiring that project teams create dozens or hundreds of CQs.
>
> Naturally, there is some gray area here: technically, the Java compiler and Maven are a build and test dependencies. We don't want to see CQs for the Java compiler or standard Maven. You will notice that some of the build and test CQs do mix in some standard Maven plugins; it's not wrong to do this, it's just not required.

See https://www.eclipse.org/lists/incubation/msg00732.html for details. 

Like EMO said: it's not wrong to file a CQ for this, it's just not really required (though I guess it depends on which of the maven plugins we consider "standard"). I see you already logged a CQ, let's keep that for approval (should be quick), but I'm happy to be a little more cavalier with this kind of dependency from here on in.

**Comment by barthanssens** [comment]
@jeenbroekstra ah, sorry, missed that one ...

**Comment by jeenbroekstra** [comment]
CQ approved
