### ISSUE TITLE
Introduce an easy to configure read only sparql interface for public endpoints

### ISSUE THREAD

**Issue by JervenBolleman** [eclipse/rdf4j#2904]
The workbench is great for read/write access and using lot's of the different capabilities of the RDF4J framework.
However, sometimes people want to just expose the SPARQL read only API on the public web.

RDF4J does not yet have an easy to setup solution for this.

**Comment by jeenbroekstra** [comment]
This introduces new dependencies for spring boot version 2.4.3. We'll need to check if one or more CQs are necessary to cover these.

**Comment by jeenbroekstra** [comment]
We're in the clear, CQ-wise (see PR for details).

**Comment by jeenbroekstra** [comment]
Awesome work @JervenBolleman , thanks!
