### ISSUE TITLE
Upgrade spring-framework to v5.3.4

### ISSUE THREAD

**Issue by JervenBolleman** [eclipse/rdf4j#2909]
Maintenance with side benefit of allowing current spring-boot apps to be added to the tools directory.

**Comment by barthanssens** [comment]
Good idea, this one does require CQ's (if they are not already used by other Eclipse projects), so I guess I better look into filing them :-)

https://github.com/eclipse/rdf4j/issues/1640 is a good start

**Comment by barthanssens** [comment]
Simply replacing produces an missing class error on JDK 15, so probably needs an explicit include of one or more dependencies

**Comment by barthanssens** [comment]
Springframework can use servlet API 3.1.0 in production, but requires 4.0 in mock tests (seems to be an accidental change when going from 5.3.3 to 5.3.4)

So I'd suggest to wait for the springframework 5.3.5 release, since that release will fix this without requiring to upgrade to servlet 4.0
