### ISSUE TITLE
NativeStore constructor to default to temporary data directory

### ISSUE THREAD

**Issue by barthanssens** [eclipse/rdf4j#2940]
For a few projects I'm using the NativeStore (instead of the MemoryStore, since the number of statements exceeds the 150k triples the MemoryStore is designed for) to load triples, perform some queries, extract the results and delete the NativeStore files.
I.e. in this case I'm not really interested where the store is kept, nor do I want to reuse the store afterwards.

Suggestion is to add a convenience method `setTempDir` (perhaps in sail.helpers.AbstractSail) that uses `Files.createTempDirectory` and (recursively) deletes it on `shutdown()`

Admittedly this only saves a few lines of code, but IMHO it's a nice little touch.

**Comment by jeenbroekstra** [comment]
I get the use case but I'm not comfortable with sticking that directly in AbstractSail. 

I've been thinking that instead, we offer a utility class somewhere that does a one-line configuration of a Repository with a native store, backed up with a temp dir. We could call it "CommonConfig" or something like that. Also gives us the option of offering quick convenience methods for other config stacks.

**Comment by jeenbroekstra** [comment]
Perhaps another alternative is to let the native store handle this internally, directly. It currently craps out with an exception if you haven't set a datadir, we could change its behavior to automatically create a tempDir (and clear it on shutDown) if you initialize it without a datadir.

**Comment by barthanssens** [comment]
That was actually my initial idea, so works for me.

**Comment by jeenbroekstra** [comment]
I'm just happy I managed to make a suggestion _other_ than "stick it in a utility class" - I'm aware I say that a lot :)
