### ISSUE TITLE
Project vserver - OS support change

### ISSUE THREAD

**Issue by eclipsewebmaster** [eclipse/rdf4j#2975]
Webmaster has been notified that the version of Ubuntu your project vserver is running will no longer be supported after April 30, 2021.  That means no new security patches will be issued and our cloud tools will have reduced functionality.

If the vserver is still needed we can coordinate its replacement via this issue.

Otherwise Webmaster will remove the instance after May 28, 2021 if there hasn't been a response on this issue.

-M.

**Comment by jeenbroekstra** [comment]
Thanks for the heads up. We actively use the vserver (the project main website https://rdf4j.org/ runs from it), so it would be ideal if we could manage an upgrade with minimal downtime. 

Can I just run a command line distribution upgrade (`sudo do-release-upgrade`) from an ssh session, or is there more involved?

**Comment by jeenbroekstra** [comment]
The actual website itself is all in git, but I'l make sure to create backups of config files (such as cronjobs, apache config, etc).

**Comment by jeenbroekstra** [comment]
Upgrade to 20.04.2 LTS has been completed and everything appears to be running smoothly. @eclipsewebmaster I don't know if you want to do any further checks from your end, let me know, otherwise I think we can call this done.

**Comment by eclipsewebmaster** [comment]
Great, lets close this. Much like https://github.com/eclipse/hono/issues/2588 I can't see the update reflected in my admin panel, so be warned I may show up again when another LTS release goes out of service whilst freaking out about you being on Ubuntu 16.
