### ISSUE TITLE
website javadoc for 3.6.2 release is malformed

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#2981]
See https://rdf4j.org/javadoc/latest  

For some reason the index page is badly formatted. Not sure what's different, the javadoc for 3.6.1 (https://rdf4j.org/javadoc/3.6.1 ) still looks normal.

**Comment by jeenbroekstra** [comment]
It appears to be a problem related to my local environment. The 3.6.1 release was handled by @hmottestad , the 3.6.2 release by me. I just tried building the javadoc after checking out the 3.6.1 tag, and get the same strange result. Possibly related to the default version of javadoc?

**Comment by jeenbroekstra** [comment]
It looks as if the notion of framed javadocs is being deprecated. The javadoc I created is done using javadoc from JDK 11. See https://stackoverflow.com/questions/51992347/missing-iframe-view-for-javadocs-jdk-11 .

Instead of forcing it back to the familiar frame layout, I will perhaps try and look at making the new search-based setup easier.

**Comment by jeenbroekstra** [comment]
Search does not work properly because it includes an `/undefined` in the path. [Stackoverflow](https://stackoverflow.com/questions/52326318/maven-javadoc-search-redirects-to-undefined-url) suggests a solution is to add this config flag to the plugin:

```xml
<additionalJOption>--no-module-directories</additionalJOption>
```

**Comment by jeenbroekstra** [comment]
The above works, but I'm not happy with the fact that whether or not we get frames depends on the dev's version of javadoc. Looking into setting some config options for the javadoc plugin to force a layout regardless of jdk version.

**Comment by hmottestad** [comment]
Good catch!

**Comment by jeenbroekstra** [comment]
I use java 11 on command line, java 13 in Eclipse (at the moment). 

If all else fails I'll switch back to java 8 for command line. Seriously put out with the javadoc devs that they just introduce such a massive non-compatible change.

**Comment by hmottestad** [comment]
We could always move to java 11 for the release script and embrace the new layout.

**Comment by jeenbroekstra** [comment]
Yeah, possibly. Though to be honest I'm not a massive fan of what it looks like right now. 

Unfortunately I can't quite see any other way. According to the docs, the `--frames` options should force the old layout, but I'm not succeeding in making the javadoc plugin accept that flag.

**Comment by jeenbroekstra** [comment]
I suggest for now, we stick with the old frame layout - I'll just make sure I use Java 8 when doing releases. 

If and when we go over to Java 11 as our default, we can also choose to embrace the new search-based Javadoc layout. 

I'll prep a new tar file for the 3.6.2 javadoc and put up a PR so that the website, at least, is updated.
