### ISSUE TITLE
Lower q value for RDF+XML format

### ISSUE THREAD

**Issue by RickMoynihan** [eclipse/rdf4j#299]
I've just ran into an issue where `CONSTRUCT` queries that constructed a predicate of the URI form: `http://blah.com/blah/(tailing-element-in-parens)` were failing.

It turns out that the above is a valid URI (though it contains reserved characters - this is legal).  This works fine for all serialisations except RDF+XML which fails.  Some more digging and it turns out that it only fails for URI's of this form in predicates; because of this [documented limitation of RDF+XML](https://www.w3.org/TR/REC-rdf-syntax/#section-Serialising).

I realise we currently use an algorithm to determine these qValues for `CONSTRUCTS` preferring Turtle the most, and then weighting it based upon whether we need named graphs etc; however given the limitations of RDF+XML I think we should also be penalising it by giving it a significantly lower qValue, ideally something like `;q=0.1`.

Are there any reasons not to do this?

**Comment by ansell** [comment]
I don't see any reasons not to do it. Definitely need to keep application/rdf+xml on the list for compatibility, but a low q value is a good idea IMO. I wouldn't lower it further than 0.5 at first though. Even 0.5 should ensure with a properly implemented content negotiation process that you never get it if you say you can handle turtle with no q value or q=1.0. If we go lower than 0.5, it seems like we have issues processing/roundtripping it, as is the case for text/csv for Tuple results (per its ill designed spec), for instance. In this case we don't have round tripping issues, there are just issues generating it from triple stores in some cases.

**Comment by jeenbroekstra** [comment]
Agreed with Peter on all points: no reason not to lower it, but 0.1 might be a bit harsh - 0.5 seems good, and gives you sufficient "wiggling room" on both ends of the scale to later fit in other formats with higher (or lower) preference. 

Of course an rigorous alternative (if you _really_ wish to avoid ever getting back RDF/XML) is to remove the RDF/XML from your runtime classpath; then the client library will not send that mime type in the Accept header at all. Of course this is at the cost of not being able to read the format if you're communicating with a service that has no alternatives (though in that case, changing the q-value won't make a difference either :)).
