### ISSUE TITLE
Remove SeRQL query language from RDF4J

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#2992]
The SeRQL language was the predecessor to SPARQL (and one of its main inspirations), but given the state of SPARQL as the standard language for RDF query, it is obsolete. The engine is still present in the code of course, and still works, but it has received no maintenance or updates, and the language is no longer documented in the RDF4J documentation.

In order to start supporting possible improvements to components like the evaluation strategies, query optimizers, and the algebra representation to more closely align with what SPARQL needs, it would be helpful to remove SeRQL support, so that we do not have to update it whenever we change something in another component. 

I suggest to remove SeRQL completely for the next major release (4.0), but am looking for feedback from the community on whether this is acceptable. Is anybody out there still using SeRQL?

**Comment by jeenbroekstra** [comment]
@eclipse/technology-rdf4j-committers

**Comment by barthanssens** [comment]
AFAIK we only use SPARQL in federal (.be) and regional (Flanders) applications, no SeRQL

**Comment by JervenBolleman** [comment]
We are pure SPARQL users as well, and have no objection to this being removed.
