### ISSUE TITLE
Set up upload of artifacts to maven central

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#3]
Current maven configuration still relies on old Sesame project settings for syncing with sonatype OSS (and from there syncing to maven central). This needs to be tweaked/reconfigured according to what Eclipse projects do for maven artifact deployment.

**Comment by ansell** [comment]
There is a very long unresolved discussion about this, including people who may still be using oss.sonatype.org:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=283745

Does Eclipse require that RDF4J convert to using P2 repositories as the main distribution channel with Maven being a secondary or otherwise unofficial channel?

**Comment by jeenbroekstra** [comment]
I don't believe so, that may have been the older solution, but I believe nowadays it's fine to set up a direct OSSRH link and upload to central via Sonatype. I can find at least one Eclipse project that has done this, see https://bugs.eclipse.org/bugs/show_bug.cgi?id=481404 

I will doublecheck with PMC though.

**Comment by jeenbroekstra** [comment]
Waiting for HIPP instance + project genie ( = project-wide e-mail account) to be set up before filing a request at Sonatype. See #12

**Comment by jeenbroekstra** [comment]
From my understanding, the Eclipse webmaster will actually take care of Sonatype registration and setting GPG keys, which will be linked to our HIPP.

**Comment by jeenbroekstra** [comment]
Logged request to set up sonatype connection, to be run using our HIPP. See https://bugs.eclipse.org/bugs/show_bug.cgi?id=492784

**Comment by jeenbroekstra** [comment]
HIPP setup complete, first snapshot build has been deployed to OSSRH. I'll keep this open until we've completed our first release milestone and managed to push it all the way to centraql.

**Comment by jeenbroekstra** [comment]
First build successfully promoted.
