### ISSUE TITLE
Adds Literal.durationValue method

### ISSUE THREAD

**Issue by Tpt** [eclipse/rdf4j#300]
xsd:duration is one of the basic XSD datatype. It probably makes sense to add a Literal.durationValue() method that would returns a javax.xml.datatype.Duration object.

Between other things, it would ease the implementation of issues #184 and #185

**Comment by jeenbroekstra** [comment]
I'd suggest a slight change: instead of adding this to the `Literal` interface (which places a burden on third party implementations) we could provide this as a utility method in the `org.eclipse.rdf4j.model.util.Literals` class: `Literals.getDurationValue(Literal)`.

**Comment by jeenbroekstra** [comment]
@Tpt a Pull request is up for this, see #588. Feedback welcome.
