### ISSUE TITLE
Referring to snapshot release repo in pom.xml file may cause issues in IntelliJ

### ISSUE THREAD

**Issue by hmottestad** [eclipse/rdf4j#3005]
See discussion here: https://www.eclipse.org/lists/rdf4j-dev/msg01815.html

**Comment by jeenbroekstra** [comment]
I am not 100% sure but this seems to be causing problems on the command line. I am getting very strange test failures when running `mvn verify`, in particular in the SHACL tests.

**Comment by jeenbroekstra** [comment]
@hmottestad out of curiosity did commenting this out actually fix the problem you were having in IntelliJ?

**Comment by jeenbroekstra** [comment]
Assuming that we keep this change in place, a possible workaround for myself and for others who wish to still use the Sonatype snapshot repo is to create a `settings.xml` file in `~/.m2/` with the following contents:

```xml
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
	<profiles>
		<profile>
			<id>sonatype-snapshots</id>
			<activation>
				<activeByDefault>true</activeByDefault>
			</activation>
			<repositories>
				<repository>
					<releases>
						<enabled>false</enabled>
					</releases>
					<snapshots>
						<enabled>true</enabled>
					</snapshots>
					<id>oss-sonatype-snapshots</id>
					<url>https://oss.sonatype.org/content/repositories/snapshots</url>
				</repository>
			</repositories>
		</profile>
	</profiles>
</settings>
```

**Comment by jeenbroekstra** [comment]
Alternatively, we actually stick this profile in the project root pom, so that this works out of the box for most users, and then those people who have problems with this can choose to deactivate the profile (no idea how that works in IntelliJ but I assume it has an option for that).

**Comment by hmottestad** [comment]
I'm not 100% sure. I ended up making some changes to the maven settings in IntelliJ and since then I haven't seen the issue. 

I can try to uncomment the snapshot repo again and see if that breaks IntelliJ. 

Btw. What sort of issues are you getting? I kinda feel that if we are getting issues building or testing the code because we can't download a snapshot build, then there is something funky going on under the hood.

**Comment by jeenbroekstra** [comment]
Oh I think it's more that I tend to rely on not having to build the entire project myself. With the snapshot repo it just grabs the latest nightly build, and I can concentrate on the specific thing I'm fixing.

Let's put it back in, but as a profile, so you can choose to disable it locally.
