### ISSUE TITLE
Values in path expressions

### ISSUE THREAD

**Issue by fragosog** [eclipse/rdf4j#3008]
Hello, we ran into sparql performance issues during testing of rdf4j 3.6.2.  A query like the one below using inlined ```values``` completes quickly and comparable to sesame 2.7.12 (where we are upgrading from),

```
prefix foo:  <http://example.com/voc#>
select (count(distinct ?subject) as ?total_concept_count)
where 
{
  values ?superclass { foo:bar }
  ?subject (rdfs:subClassOf|(owl:equivalentClass/owl:intersectionOf/rdf:rest*/rdf:first) )* ?superclass . 
}
``` 

However, adding more triple patterns to the above query, such as

```
{
  values ?superclass { foo:bar }
  ?subject (rdfs:subClassOf|(owl:equivalentClass/owl:intersectionOf/rdf:rest*/rdf:first) )* ?superclass ;
     owl:equivalentClass ?an .
}
```

results in the query running longer in rdf4j in comparison to sesame 2.7.12, in this particular instance 35 secs vs 190 ms in sesame using a memory store with 2.2 million triples (with 8.5 million triples the query terminates in sesame - just as quickly - but not in rdf4j).

If we eliminate "values" and instead use foo:bar as the object in the query

```
{
  ?subject (rdfs:subClassOf|(owl:equivalentClass/owl:intersectionOf/rdf:rest*/rdf:first) )* foo:bar ;
     owl:equivalentClass ?an .
}
```

 
this query (and others like it that include the same path expression) then terminates in about 7 secs with 8.5 million triples in the memory store.  The use of ```values``` in queries without a path expression finish in about the same time as sesame, so the issue appears to be restricted to its use in a path expression like the ones above.  Hopefully the treatment of ```values``` can be reviewed?

Please let me know if you need additional details.
  
Thank you!

**Comment by jeenbroekstra** [comment]
It sounds like a glitch in the query planner. Could you your query through the [explanation](https://rdf4j.org/documentation/programming/repository/#explaining-queries) tool (using `Optimized` level) on your store and post the outcome here?

**Comment by fragosog** [comment]
Yes, I'm attaching the output of explain for the query with the ```values``` keyword at the ```Unoptimized``` and ```Timed``` levels:  

[values-unoptimized.txt](https://github.com/eclipse/rdf4j/files/6372196/values-unoptimized.txt)
[values-timed.txt](https://github.com/eclipse/rdf4j/files/6372197/values-timed.txt)

And just in case it helps, I'm also attaching the output of explain where the object in the triple pattern is a constant, at the ```Timed``` level:
 
[const-timed.txt](https://github.com/eclipse/rdf4j/files/6372203/const-timed.txt)

Thanks!

**Comment by jeenbroekstra** [comment]
Thanks for that. The relevant bit is this section of the plan: 

```
      ╠══Join (JoinIterator) (resultSizeActual=0, totalTimeActual=41.5s, selfTimeActual=1.59ms)
      ║  ├──BindingSetAssignment ([[superclass=http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C25791]]) (costEstimate=1, resultSizeEstimate=1, resultSizeActual=1, totalTimeActual=0.028ms, selfTimeActual=0.028ms)
      ║  └──Join (JoinIterator) (resultSizeActual=0, totalTimeActual=41.5s, selfTimeActual=4.04ms)
      ║     ╠══StatementPattern (costEstimate=123, resultSizeEstimate=370, resultSizeActual=370, totalTimeActual=6.76ms, selfTimeActual=6.76ms)
      ║     ║     Var (name=subject)
      ║     ║     Var (name=_const_aabebca2_uri, value=http://www.w3.org/2002/07/owl#equivalentClass, anonymous)
      ║     ║     Var (name=an)
      ║     ╚══ArbitraryLengthPath (costEstimate=9.7K, resultSizeEstimate=4.4M, resultSizeActual=0, totalTimeActual=41.5s, selfTimeActual=41.5s)
```

It looks as if the problem is that the BindingSetAssignment is not "pushed down" enough into the algebra tree, leading to a combinatorial explosion of values for ?subject and ?subclassof. 

There currently is no optimizer in the pipeline for this case, but what we want to achieve is basically that the join arguments of the first and second join (that is, the binding set assignment and the statement pattern, respectively) switch places. This is analogous to what we do with filter expressions, and will ensure that we get an early exit from ArbitraryLengthPath.

This is not completely trivial to add, so may take a while. Workaround fix (apart from inlining) is to replace  the VALUES clause with a FILTER condition: `FILTER(?subclassof = <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C25791>)` .

**Comment by jeenbroekstra** [comment]
A simpler fix for now may be to internally "inline" values clauses where possible. This only works if the values clauses specifies a single value for each variable assigned, though: so in the example query here it would work but as soon as you modify the values clause to something like 

    VALUES ?superclass { foo:bar foo:bar2 } 

it will revert back to poor performance.

**Comment by fragosog** [comment]
Hello, I can confirm that using the filter workaround works well.

We have a number of queries with multiple values, but these don't include a path expression.

Thanks again!
