### ISSUE TITLE
String encoding in binary RDF format

### ISSUE THREAD

**Issue by frensjan** [eclipse/rdf4j#3010]
I've been tinkering with the binary RDF format support in RDF4J. I noticed that string encoding in `BinaryRDFWriter#writeString` uses two bytes per character.

I guess this is sort of UTF-16 encoding? I'm not sure what happens with characters that would require 4 bytes though. But that's sort of besides the point. At the same time, `BinaryQueryResultWriter#writeString` writes UTF-8 using a `CharsetEncoder`. This makes more sense to me; probably given the area I'm in.

I've been tinkering a little bit, and for some benchmark data (links available via https://github.com/dice-group/triplestore-benchmarks) there is some substantial savings in disk space:

file | size
----|----
fishmark/data.nt | 1.8G
fishmark/data-utf16.brf | 585M
fishmark/data-utf8.brf | 350M
sp2b/data.n3 | 2.7G
sp2b/data-utf16.brf | 2.4G
sp2b/data-utf8.brf | 1.0G
swdf/data.nt | 58M
swdf/data-utf16.brf1 | 32M
swdf/data-utf8.brf | 17M

Is there a particular reason for this encoding? Would a v2 of the format with UTF-8 make sense?

**Comment by barthanssens** [comment]
Have to look into it, don't know by heart why this 2-byte approach was chosen.

On a somewhat related note, as you probably know there is also a binary format called HDT, which uses different compression techniques to reduce the file size even more.
Unfortunately RDF4j only supports (experimental) reading HDT: problem is that the (open source) reference implementation and the specification document are not aligned, so it is somewhat time consuming to figure out what the most interoperable solution would look like...

And there is RDF Thrift

**Comment by jeenbroekstra** [comment]
Relevant: https://rdf4j.org/documentation/reference/rdf4j-binary/

So, you're right, it uses what is essentially UTF-16. This decision was made _way_ back so I'm a little foggy, but if I remember correctly it may have had something to do with the fact that Java internally keeps strings as UTF-16, and using this same representation would mean less conversion. 

I am not sure that rationale really holds water, and the size data you've posted is a good argument to revisit this. We should probably also do some performances benchmarks on (de)serialization speed of both encodings to be sure.
 
The good thing is that the format has a header with a version number built in, so we can potentially support this in a backward-compatible fashion.

**Comment by frensjan** [comment]
In the end it's probably a matter of balancing characteristics like space and time complexity. Note that since Java 9, strings are treated a little different (see e.g. https://www.baeldung.com/java-9-compact-string). I doubt there is much of an advantage in terms of read/write speed from using UTF-16. I very limited stab at a parse benchmark shows me that for the fishmark dataset the UTF-8 version reads at ~2.7m statements / second while the original version reads at ~1.9m statements / second. I do reckon that this is highly dependent on the character sets used in an RDF file though.

There are other things that can be done of course. Using variable length integers for IDs and length fields can shave another ~15% for the fishmark datasets. Using LZ4 can reduce the size by ~50% in comparison to the UTF-8 case.

If there is an interest from the RDF4J community, I'd be interested in doing some work on this. If so, I'd be happy to take some "requirements" (benchmark datasets and metrics of interest, how to share results, etc.).

**Comment by jeenbroekstra** [comment]
> If there is an interest from the RDF4J community, I'd be interested in doing some work on this. If so, I'd be happy to take some "requirements" (benchmark datasets and metrics of interest, how to share results, etc.).

We'd be overjoyed to have your contribution in this! Please have a look at the [contributor guidelines](https://github.com/eclipse/rdf4j/blob/main/.github/CONTRIBUTING.md) to get started, in particular the points on how to sign the Eclipse ECA. There's also pointers there on how to work with our branching model, and how to prepare your pull request.

A dataset that we use in several places for benchmark testing at (some) scale is `datagovbe-valid.ttl`, which is a 892,555 line turtle file. We've been a bit sloppy about reuse so there's several copies in different modules, feel free to make another copy for easy inclusion in your tests. Other than that I'd suggest some small (synthetic) datasets that use some non-Western unicode chars, that would  be more for correctness than for performance testing though (I've noticed that unfortunately, test coverage is not great for the binary parser/writer). 

For testing we use JUnit 5 with AssertJ and Mockito (just have a browse to see how tests are implemented). For benchmarking we use JMH. I guess the most important measurements for this improvement are (de)serialization speed and size of the serialized file. 

That's all I can think of from the top of my head. Don't hesitate to reach out here (or via Gitter or the mailinglist) with anything that's unclear or any suggestions you have.

**Comment by frensjan** [comment]
I've started work on this, and in the process I think I have found a memory leak in `BinaryRDFWriter`. Essentially what happens is that values (subjects, predicates, objects and contexts) that occur twice or more in the writer's buffer are assigned an ID. There is a FIXME with the following code commented out:
```java
// FIXME: This loop is very slow for large datasets
for (Value key : valueIdentifiers.keySet()) {
    if (!valueFreq.containsKey(key)) {
        id = valueIdentifiers.remove(key);
        break;
    }
}
```
So while value frequency data is cleaned up (in `decValueFreq` called from `writeStatement`), the identifiers assigned aren't.

The images below show the growth of the heap with the current version (top image) and the recycling of IDs enabled by uncommenting the FIXME mentioned (bottom image) for transforming a N-Triples file (the ~25 GB bsbm dump from [the HOBBIT project](https://hobbitdata.informatik.uni-leipzig.de/benchmarks-data/datasets-dumps/)) into BRF (~18 GB).

<img width="692" alt="Screenshot 2021-04-30 at 21 58 02" src="https://user-images.githubusercontent.com/3985389/116748936-7683c080-aa00-11eb-8bcf-532345d34ffb.png">
<img width="690" alt="Screenshot 2021-04-30 at 22 06 52" src="https://user-images.githubusercontent.com/3985389/116748953-80a5bf00-aa00-11eb-8d39-3afe766f3a4b.png">

The code ran is something like:
```java
CountingOutputStream os = new CountingOutputStream(NULL_OUTPUT_STREAM);
RDFWriter writer = new BinaryRDFWriter(os);
RDFParser parser = Rio.createParser(...);
parser.setRDFHandler(writer);
parser.parse(is);
os.getByteCount();
```

So - for this dataset - it leaks ~10% memory relative to the dataset size.

Note that enabling the recycling / cleaning of IDs will result in larger BRF files! Even when increasing the buffer size from 100 (default) to 10k the output is ~ 20% larger for the `datagovbe` file. With the default buffer size, the increase is ~50%.

a) Is this something that we want to fix? I'd be happy to dig into this. Periodic bulk cleaning (e.g. every n statements) and using a priority queue sorted by frequency come to mind as possible directions.
b) Is this something that should be fixed together with other changes for the binary RDF format? I think that would be more efficient from a development point of view. I don't see them as completely unrelated, but if preferred I'm happy to tackle this separately.

When tackling this as one issue, I see the following 'requirements':
* decrease file size for (mostly) latin data (literals and IRIs);
* have limited to no file size increase for non-latin data;
* no degradation in throughput (any improvement is always good);
* remove the memory leak;
* allow for a larger default memory footprint to achieve the above if necessary (should still be configurable).

**Comment by jeenbroekstra** [comment]
Good find on the memory leak. I traced the commenting of that cleanup loop back to a performance testing flurry we did back in 2014 (see https://bitbucket.org/openrdf/sesame/commits/f4b69365ad21b0f2553c933e7aa3c31aa75f6d8f). Unfortunately there is not a lot of context, but presumably at the time the thinking was that we'd sacrifice memory for speed - though of course at the _very least) that memory should be freed up once the writer is done.  

Of course the main reason we do id recycling is to stop us from potentially running out of integer values. Rather than using long of BigInteger (which would require more bytes to serialize) we opted for this recycling technique. 

> Note that enabling the recycling / cleaning of IDs will result in larger BRF files! Even when increasing the buffer size from 100 (default) to 10k the output is ~ 20% larger for the datagovbe file. With the default buffer size, the increase is ~50%.

That is surprising. The id recycling may slow things down but it writes the same number of bytes whether using a new number or a recycled one. Any thoughts on why this would result in a larger file size? Also, looking at that default buffer size, we honestly need to set that a bit higher I think, to allow a larger window of reference reuse.

> a) Is this something that we want to fix? I'd be happy to dig into this. Periodic bulk cleaning (e.g. every n statements) and using a priority queue sorted by frequency come to mind as possible directions.
> b) Is this something that should be fixed together with other changes for the binary RDF format? I think that would be more efficient from a development point of view. I don't see them as completely unrelated, but if preferred I'm happy to tackle this separately.

I'd certainly be happy for you to take a look as part of this, it's closely enough related, I agree. And periodic bulk cleaning (either every n statements or perhaps when `maxValueId` reaches a certain threshold close to `Integer.MAX_VALUE` ) might be a good approach. And I agree with all your requirements I think. We'll need to keep an eye on both ends though: deserialization speed (parser performance) is equally important.

**Comment by jeenbroekstra** [comment]
Another option to consider: get rid of the id recycling altogether, and just stop assigning new ids when the counter reaches MAX_INT. You can still write the remeaning values once you run of out of ids, but they will be written as-is instead of as a reference. I mean we're talking over 2 billion values before we reach this point anyway - for the vast majority of cases, we can relatively safely assume we don't have to recycle ids.

**Comment by frensjan** [comment]
It is not so much whether IDs are reused or not that is causing the memory issue. It is the fact that the IDs are never removed from the `valueIdentifiers` map that causes the memory usage to grow.

As an example: I am not able to write out the bsbm dump from the [Hobbit project](hobbitdata.informatik.uni-leipzig.de/benchmarks-data/datasets-dumps/) if the VM has only 1GB of heap. Now that isn't all that much heap, I know. I guess that's also why this never surfaced. So one might say this is a somewhat theoretical issue.

> Any thoughts on why this would result in a larger file size?

This is caused by the fact that the current implementation essentially has an infinite window for values that have been assigned an ID. So with the current implementation, if a value is ever assigned an ID, it willen be written out as a reference. Even if in that window of statements it only occurs once. From a file size point of view this is good, but it is at a memory cost.

> Also, looking at that default buffer size, we honestly need to set that a bit higher I think, to allow a larger window of reference reuse.

Agreed. 100 is _really_ conservative.

> We'll need to keep an eye on both ends though: deserialization speed (parser performance) is equally important.

Check, I'll add comparison benchmarks for both parsing and writing.

As a final comment: recycling IDs may be of interest if we would change the format of the IDs to variable length integers instead of plain integers. But this is subject to benchmarking. I'll get back on this.

**Comment by frensjan** [comment]
I've pushed work into https://github.com/frensjan/rdf4j/tree/GH-3010-improve-binary-rdf-format and created a PR: https://github.com/eclipse/rdf4j/pull/3052. Note that tests for V1 compatibility need to be added.

As for some initial output size benchmarks:
```
             swdf.nt    31,85 MB in PT2.017272S    - binary v1, buffer size = 100
             swdf.nt    29,13 MB in PT0.898222S    - binary v1, buffer size =  8k
             swdf.nt    22,07 MB in PT1.031359S    - binary v2, buffer size = 100, UTF-16
             swdf.nt    21,77 MB in PT0.913684S    - binary v2, buffer size =  8k, UTF-16
             swdf.nt    12,61 MB in PT0.697705S    - binary v2, buffer size = 100, UTF-8
             swdf.nt    12,47 MB in PT0.882551S    - binary v2, buffer size =  8k, UTF-8
             swdf.nt    40,02 MB in PT0.832878S    - binary v2, buffer size = 100, UTF-16, with id-recycling
             swdf.nt    29,89 MB in PT0.976627S    - binary v2, buffer size =  8k, UTF-16, with id-recycling
             swdf.nt    21,04 MB in PT0.603252S    - binary v2, buffer size = 100, UTF-8, with id-recycling
             swdf.nt    16,32 MB in PT0.748196S    - binary v2, buffer size =  8k, UTF-8, with id-recycling

        datagovbe.nt    64,77 MB in PT2.438171S    - binary v1, buffer size = 100
        datagovbe.nt    55,92 MB in PT2.171483S    - binary v1, buffer size =  8k
        datagovbe.nt    55,97 MB in PT2.550505S    - binary v2, buffer size = 100, UTF-16
        datagovbe.nt    48,44 MB in PT2.517981S    - binary v2, buffer size =  8k, UTF-16
        datagovbe.nt    31,87 MB in PT2.083066S    - binary v2, buffer size = 100, UTF-8
        datagovbe.nt    28,19 MB in PT2.259788S    - binary v2, buffer size =  8k, UTF-8
        datagovbe.nt   111,36 MB in PT2.098135S    - binary v2, buffer size = 100, UTF-16, with id-recycling
        datagovbe.nt    93,46 MB in PT2.410202S    - binary v2, buffer size =  8k, UTF-16, with id-recycling
        datagovbe.nt    57,98 MB in PT1.622503S    - binary v2, buffer size = 100, UTF-8, with id-recycling
        datagovbe.nt    50,12 MB in PT1.971276S    - binary v2, buffer size =  8k, UTF-8, with id-recycling
```

I'll run more tonight.

As for some performance benchmarks:
```
Version 1:
parse         .brf  avgt    2  0,978           s/op
write         .brf  avgt    2  0,467           s/op

Version 2:
parse         .brf  avgt    2  0,919           s/op
write         .brf  avgt    2  0,315           s/op
```

Note that these numbers are obtained with the default settings:

version 1:
* buffer size = 100

version 2:
* buffer size = 8192
* charset = UTF-8
* identifier recycling enabled

**Comment by frensjan** [comment]
I've placed the size benchmark results into some charts:

Average relative size over all datasets for different variants:
![image](https://user-images.githubusercontent.com/3985389/118391018-80c5d180-b632-11eb-8f6b-c92f4708bbdc.png)

Output size in MB for the datagov.be file:
![image](https://user-images.githubusercontent.com/3985389/118390958-2a589300-b632-11eb-9621-543e768141bf.png)

Output size in MB for the Berlin SPARQL Benchmark file:
![image](https://user-images.githubusercontent.com/3985389/118390984-48be8e80-b632-11eb-80b8-e8652605d773.png)

**Comment by frensjan** [comment]
From these measurements I think that a binary RDF encoding with:
* UTF-8 string encoding
* variable length IDs and string lengths
* recycling of IDs
is decent improvement over the current format.

The use of UTF-8 encoding has a persuasive positive effect. ID recycling removes a memory issue but at the cost of larger files. However, variable length encoding of string lengths and IDs combined with ID recycling reduces this negative effect.

Speed performance-wise, the implementation of the V2 encoding brings some improvement; in particular during writing.

I'd like to hear your thoughts and feedback.

**Comment by frensjan** [comment]
To drive the memory leak point home again:

<img width="690" alt="CPU usage" src="https://user-images.githubusercontent.com/3985389/118408071-13429100-b684-11eb-8c52-c783034a1c30.png">
<img width="688" alt="Heap usage" src="https://user-images.githubusercontent.com/3985389/118408079-1d648f80-b684-11eb-8ece-5b6440f35ad8.png">

The first 5 minutes are spent writing the Berlin SPARQL Benchmark file out with the V2 implementation with ID recycling. From 20:16 in the charts the V1 implementation is used to write out the same file ending in a `java.lang.OutOfMemoryError` after a few minutes of GC trashing.

**Comment by jeenbroekstra** [comment]
Compelling figure @frensjan, thanks for that. From this data I agree with you that going with UTF-8 + id recycling as the default is the best tradeoff. 

Have you made the use of id-recycling configurable somehow, or have you hardcoded the change between benchmark runs?

**Comment by frensjan** [comment]
Good to hear!

The use of id-recycling is configurable indeed: there is a constructor for the V2 writer with a parameter for that: https://github.com/eclipse/rdf4j/pull/3052/files#diff-aa747cbb28c73e81e9da469f6c35ac098a18c361278988d814c3f1269edaf52fR70
