### ISSUE TITLE
Invalid query result - blank node instead of resource

### ISSUE THREAD

**Issue by jakubklimek** [eclipse/rdf4j#3011]
Input data:
```turtle
<https://test> a <http://www.w3.org/ns/dcat#Catalog> .
```
Query:
```sparql
PREFIX dcat: <http://www.w3.org/ns/dcat#>

CONSTRUCT {
<http://a> <http://b> ?x .
  ?x <http://c> ?x .
}
WHERE {
  ?x a dcat:Catalog .
}
```
Expected result (received in rdf4j 3.2.3):
```turtle
<https://test> <http://c> <https://test> .
<http://a> <http://b> <https://test> .
```

Actual result (received in rdf4j 3.6.2):
```turtle
<https://test> <http://c> _:node1f3ptt8olx1 .
<http://a> <http://b> <https://test> .
```

The blank node should not be there, it should be `<https://test>`.

**Comment by jeenbroekstra** [comment]
Thanks for reporting, confirmed. It appears that this was introduced in release 3.5.1 (possibly as a side effect of rewriting the path expression handling).

**Comment by jeenbroekstra** [comment]
@hmottestad I've got a possible fix for this, will put up a PR in a moment. Would be great if we can still include in the patch release.
