### ISSUE TITLE
Migrate metaphacts internal query renderer to RDF4J

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#3012]
subtask of #71

metaphacts has an internal query renderer implemention that is being donated to the RDF4J code base.

**Comment by hmottestad** [comment]
That's very kind.

**Comment by jeenbroekstra** [comment]
This has now been integrated as a separate renderer implementation. It is considered an experimental feature, future work will be about merging with or replacing the older renderer impl. See #3041
