### ISSUE TITLE
Remove SPIN sail and migrate SPIN tuple functions

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#3015]
The SPIN sail is deprecated and is to be removed. However, its custom (tuple) function collection in `org.eclipse.rdf4j.spin.function` is generally useful even outside SPIN and should be preserved, possibly migrated.

**Comment by hmottestad** [comment]
Some background on some of the issues with the SPIN sail. 

 - performance issues
 - transactional issues

Performance wise SPIN just doesn't scale in a good way. SPIN being very powerful also means it's hard to optimize. 

Transactional issues are essentially grounded in how SPIN uses SPARQL and that we don't know if a change in a transaction will affect any rules or constraints. The SPIN sail attempts to analyze the transaction, but it only handles the most rudimentary patterns. This means that it is easy to create a transaction that should trigger a rule, but doesn't. The only way to fix this would be to rerun all rules and constraints on every transaction, which would not be good for performance. 

The one use-case that the SPIN sail would still be decent at is forward-chaining small datasets as a one-time operation.
