### ISSUE TITLE
JUnit not a dependency for rio-trix on master

### ISSUE THREAD

**Issue by ansell** [eclipse/rdf4j#304]
Somehow the pom.xml change in the following commit did not make it to master (was "git merge --ours" used to avoid conflicts and it avoided making the relevant pom.xml change??)

https://github.com/eclipse/rdf4j/commit/70fde6f5fd39bede881e8a2db0215c7d777f6d20

@jeenbroekstra Could you cherry-pick the pom.xml change from that commit onto master? This should fix the broken hudson build.

**Comment by jeenbroekstra** [comment]
Ah right, that's exactly what happened. I eyeball the poms before doing this, but must have overlooked this. I'll fix.

**Comment by jeenbroekstra** [comment]
Should be fixed now.
