### ISSUE TITLE
Getting access to all binding variables with SAIL when implementing BindingSet or Statement Iteration.getNext()

### ISSUE THREAD

**Issue by peterjohnlawrence** [eclipse/rdf4j#3047]
I am developing a SAIL class  which extends from NotifyingSailWrapper. The purpose of this class is to change the rendering of literals when returned via getNext(). However I need access to all variables within the TupleExpr.

If the tuplexpr is associated with a QueryType.TUPLE query it appears the BindingSet available via next() is the projected variable.
If the tuplexpr is associated with a QueryType.GRAPH query it appears the Statement available via next()  is the projected s,p,o variables within one of the MultiProjections.

Is it possible for a SAIL to access all of the variables defined within the TupleExpr behind the current binding set (to view only)? If so how?

Many thanks

**Comment by jeenbroekstra** [comment]
`TupleExpr` has a `getBindingNames()` method which returns all variable names that are, or can be, returned by this tuple expression when it is evaluated. It also has `getAssuredBindingNames()` which is more restrictive in that it only returns the variable names that are _guaranteed_ to be present in the result (an example of where this makes a difference is in an optional / LeftJoin: the binding names will return every var in both of its arguments, while the assured binding name will only return the left arg variables as the right-arg may remain unbound).

**Comment by peterjohnlawrence** [comment]
Thanks for the response, and following your description I have engineered a workaround (:-()
