### ISSUE TITLE
Replace Google Group with Github Discussions

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#3056]
Github is becoming more and more the "everything and the kitchen sink" platform for software development. One new feature is Github Discussions: https://docs.github.com/en/discussions .

I'm thinking it might be a good idea to switch our main user forum over to that from Google groups. It has several advantages:

1. everything in one place
2. easy linking to issues and code samples
3. if anybody creates an issue ticket that really should be a question, we can do a one-click transfer.
4. it offers both "discussion" style forums as well as more "Q&A" style interactions

Possible downsides:

1. it requires a github account to participate
~2. it does not allow interaction via e-mail~ EDIT this is perhaps not right, I think it may be possible to reply to e-mail notifications from discussion via mail (similar to how this works for issues) - I haven't tested this yet though.
3. it's in beta, which means there may be bugs
4. it's relatively unknown, which means it may be hard to find/figure out for our users

I'm also not sure if the EMO has any views on the use of this as opposed to the more classical mailinglist, but before I bother them with I thought I'd sound you all out first. Any thoughts? 

If you want to have a play, I've created a throwaway test repo with dicussions enabled, see https://github.com/jeenbroekstra/test-github/discussions

**Comment by jeenbroekstra** [comment]
Of course, another option we have is to start using the Eclipse Forum at https://www.eclipse.org/forums/index.php/f/316/ .

It's a little old-fashioned perhaps but it's hosted and maintained for us, and seems easy enough to use.

**Comment by jeenbroekstra** [comment]
@eclipse/technology-rdf4j-committers I'd like to hear your opinions on this. 

I'm personally inclined to just do it. I find the Google group painful to work with, myself. But I'd prefer not to make this decision unless I have some support from others :)

**Comment by hmottestad** [comment]
I have not tried the GitHub based forum before. I'm very open to new things though as I find Google Groups to be absolutely terrible on mobile!

**Comment by jeenbroekstra** [comment]
Request to enabled logged at https://bugs.eclipse.org/bugs/show_bug.cgi?id=573860

**Comment by jeenbroekstra** [comment]
Discussions are enabled, but we've hit a problem: I should be able to post in announcements category as maintainer, but for some reason I can't. This looks like a bug at Github's side. See https://github.com/github/feedback/discussions/4063 .

**Comment by jeenbroekstra** [comment]
Bug is fixed. We're up and running. We'll trial for a while in parallel and once we're confident we'll shut down the Google group.

I'll add a link to our support page.
