### ISSUE TITLE
JsonLd parsing - a number of expected triples is not being generated.

### ISSUE THREAD

**Issue by naturzukunft** [eclipse/rdf4j#3064]
As discussed [here](https://groups.google.com/g/rdf4j-users/c/dGYocmaJl2A/m/Il5HhOteBgAJ)
There seems to be a problem in the jsonLd Parser.

See this [gist](https://gist.github.com/naturzukunft/ff1c7fd746904da3649d147dccdd6c7b) for reproducing it.
I also added the problematic jsonld file, in case the end point causes problems.

**Comment by jeenbroekstra** [comment]
As I also pointed out in the mailinglist discussion, as far as I'm aware there is no bug in the parser. Can you clarify  which exact triple you were expecting to show up, and what exactly you are getting?

**Comment by naturzukunft** [comment]
I was following Jerven Bolleman's wish to open an issue. 
Since i added `Model model = Rio.parse(sr, "http://example.org/base/uri/", RDFFormat.JSONLD);`
It looks fine for me.
