### ISSUE TITLE
Unify SparqlBuilder RDF value interfaces with RDF4J Model API

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#3073]
The SparqlBuilder currently allows use of RDF4J Model values in some places but not others, insisting on its own implementations. We need to find a way to streamline this.

**Comment by fkleedorfer** [comment]
I am running into this again. My biggest issue is with only some of the sparqlbuilder's methods allowing IRI parameters, while others insist on Iri, making it cumbersome to use the usual vocabulary classes as provided by rdf4j for standard ontologies. I am very tempted to just add the IRI methods and delegate them to the existing ones. Any opinions?

**Comment by fkleedorfer** [comment]
Oh and the same with `RdfPredicate`

**Comment by jeenbroekstra** [comment]
That's what we've done part of the way already I think. I'd like a cleaner solution than that in the end but I must admit I don't know what that looks like, so perhaps this is the quickest way to make progress for now.
