### ISSUE TITLE
rdf4j-queryresultio-sparqljson incompatible with Jackson 2.7+

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#308]
Related to #273 

Currently the RDF4J code is using a method in rdf4j-queryresultio-sparqljson (Lf2SpacesIndenter) that doesn't exist in Jackson 2.7+ as Jackson have a policy where they remove public APIs across minor versions. 

See user forum report at https://groups.google.com/d/msg/rdf4j-users/hE74OxX9Ijw/vVF9gUf5AQAJ

**Comment by ansell** [comment]
For reference, the discussion between myself and the Jackson maintainer relating to this is at:

https://github.com/FasterXML/jackson-core/issues/308

**Comment by ansell** [comment]
I will work on this btw.

**Comment by ansell** [comment]
Would it be an inconvenience if I updated the 2.0.1-SNAPSHOT Jackson dependency to 2.8.2 that was released 48 hours ago as part of this pull request?

I had two pull requests for jackson-dataformat-csv merged in 2.8.2 and it would be great to be able to reuse them both here in the near future to replace opencsv.

**Comment by ansell** [comment]
I have verified with the changes I am making so far that both 2.6.2 and 2.8.2 work, so I can leave the version bump for another time if that suits.

**Comment by jeenbroekstra** [comment]
I'd prefer not doing this in the release branch as it means we will be blocked from doing a patch release until we have approval for the new version of Jackson (and also because bumping major dependency versions as part of a patch release is not quite kosher). I suggest we only do the quick fix to make the immediate problem go away in the release branch, and schedule a jackson version bump for the master branch instead.
