### ISSUE TITLE
QueryJoinOptimizer should prefer BindingSetAssignment if it binds variables in the rest of the query

### ISSUE THREAD

**Issue by hmottestad** [eclipse/rdf4j#3102]
BindingSetAssignment is typically given a constant cost of 1, which usually makes the QueryJoinOptimizer prioritise it for the left part of the join. One edge case occurs because the statistics doesn't account for data added during a transaction, so could return 0 as the cost for a statement pattern even though the pattern matches data added during the transaction.

Essentially this is a issue for the ShaclSail if the user adds a lot of data to an empty store without using IsolationLevel.NONE.

BindingSetAssignment will anyways always be an upper bound for a query as long as it binds one or more variables in the rest of the query. And since statistics is meant to provide estimates, then a known low cost should be preferred over an unknown cost.

```
SELECT ?book ?title ?price
{
   VALUES ?book { :book1 :book3 }
   ?book dc:title ?title ;
         ns:price ?price .
}
```

vs.

```
SELECT ?book ?title ?price
{
   VALUES ?x { :book1 :book3 } # <-- ?x instead of ?book
   ?book dc:title ?title ;
         ns:price ?price .
}
```

**Comment by jeenbroekstra** [comment]
IMO this is just an example of "cardinality inflation". The cost for a statement pattern match should _never_ be 0, not even if all composite terms are constants. It should be _at least_ 1. The only expression that should have a cost of 0 is the empty node.

**Comment by jeenbroekstra** [comment]
Ah, looking a bit further, what I missed in this is that, for example, the MemoryStore cardinality calculator assigns 0 to a StatementPattern if it "knows" there are no matching statements in the store. I think I understand the corner case a bit better now. Let's continue discussion on the PR.
