### ISSUE TITLE
Update to Jackson-2.8.2

### ISSUE THREAD

**Issue by ansell** [eclipse/rdf4j#311]
I had two pull requests accepted for jackson-dataformat-csv in 2.8.2 that I would like to use to remove our dependency on the comparatively slow opencsv parser library ( https://github.com/uniVocity/csv-parsers-comparison ). Together they improve the fluency of using Jackson for CSV parsing and writing and would be useful to have access to for RDF4J.

This would involve getting Eclipse Legal Team to verify that we can use Jackson-2.8.2 which was released about 48 hours ago so they would not likely have approved it internally yet.

So as not to delay any patch releases on 2.0.x, this would be targeted at 2.1.x (currently master).

**Comment by jeenbroekstra** [comment]
To be specific, we currently (directly) use three Jackson modules:
- jackson-core
- jackson-databind
- jackson-annotations

If I understand correctly, you want to add a new dependency for jackson-dataformat-csv, and also update to 2.8.2. Is that correct?

**Comment by ansell** [comment]
Yes, it would be nice to have the jackson-dataformat-csv module added to the list of approved modules as part of the same step if that is easier to do in a single step.

**Comment by jeenbroekstra** [comment]
CQs logged: 

Core: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=11930
Databind: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=11931
Annotations: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=11932
dataformat-csv: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=11933

**Comment by jeenbroekstra** [comment]
Sorry for delay, all CQs have been approved (in fact happened a while back) so we're good to go on bumping to 2.8.2.
