### ISSUE TITLE
Update queries performance problem with MINUS operators

### ISSUE THREAD

**Issue by AlyHdr** [eclipse/rdf4j#3111]
When executing long update queries that contains MINUS operator a performance issue is noticed, where such queries perform so poorly compared to running the same queries without the MINUS.

Here's one of the queries being executed (truncated with the MINUS part longer):
```
DELETE {
  ?s ?p ?o .
}
 WHERE {
  VALUES ?entity {
     <https://linkedopendata.eu/entity/Q2605861> <https://linkedopendata.eu/entity/Q2549773> <https://linkedopendata.eu/entity/Q136> <https://linkedopendata.eu/entity/Q2616388> <https://linkedopendata.eu/entity/Q2651539> <https://linkedopendata.eu/entity/Q2557122> <https://linkedopendata.eu/entity/Q2738805> <https://linkedopendata.eu/entity/Q2603812> <https://linkedopendata.eu/entity/Q2584> <https://linkedopendata.eu/entity/Q8988> <https://linkedopendata.eu/entity/Q2650084> <https://linkedopendata.eu/entity/Q2570> <https://linkedopendata.eu/entity/Q2563291> <https://linkedopendata.eu/entity/Q2573576> <https://linkedopendata.eu/entity/Q240339> <https://linkedopendata.eu/entity/Q4551> <https://linkedopendata.eu/entity/Q236714> <https://linkedopendata.eu/entity/Q2643393> <https://linkedopendata.eu/entity/Q6193> <https://linkedopendata.eu/entity/Q2643177> <https://linkedopendata.eu/entity/Q2576426> <https://linkedopendata.eu/entity/Q2502380> <https://linkedopendata.eu/entity/Q16> <https://linkedopendata.eu/entity/Q1048> <https://linkedopendata.eu/entity/Q4557> <https://linkedopendata.eu/entity/Q5866> <https://linkedopendata.eu/entity/Q2650897>
  
  }
    ?s <http://schema.org/about> ?entity .
  ?s ?p ?o    .
  MINUS {
    VALUES ( ?s ?p ?o ) {
      ( <https://ro.wikipedia.org/wiki/New_York_(ora%C8%99)> <http://schema.org/name> "New York (ora?)"@ro )
( <https://lv.wikipedia.org/wiki/Futbols> <http://schema.org/about> <https://linkedopendata.eu/entity/Q8988> )
( <https://hu.wikipedia.org/wiki/Andrzej_Duda> <http://schema.org/isPartOf> <https://hu.wikipedia.org/> )
( <https://hu.wikipedia.org/wiki/Hiiumaa_(megye)> <http://schema.org/isPartOf> <https://hu.wikipedia.org/> )
( <https://pl.wikipedia.org/wiki/Austro-W%C4%99gry> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://schema.org/Article> )
( <https://sk.wikipedia.org/wiki/Vladimir_Vladimirovi%C4%8D_Putin> <http://schema.org/name> "Vladimir Vladimirovi? Putin"@sk )
.
.
.
.
.
    }
  }
}
```
It could be that this operator to exclude the triples is not well optimized, by looking at the iterator SPARQLMinusIteration https://github.com/eclipse/rdf4j/blob/e3548a79f754361695283acf9fe752b37071c186/core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/iterator/SPARQLMinusIteration.java#L81

It appears that for every given binding set there is a loop which in theory could be a quadratic complexity, and this could be optimised by using a hashset to store all the triples to be excluded and for every given binding set we can check if it has to be excluded in constant time and not linear.

**Comment by jeenbroekstra** [comment]
> It appears that for every given binding set there is a loop which in theory could be a quadratic complexity and this could be optimised by using a hashset to store all the triples to be excluded and for every given binding set we can check if it has to be excluded in constant time and not linear.

I am a little confused about what you're proposing. The bindingsets to be excluded _are_ internally cached (that's the `excludeSet` field), which seems to be precisely the solution to the perceived performance issue you're proposing.
