### ISSUE TITLE
RDF4J on Debian 10: Logging problems

### ISSUE THREAD

**Issue by volkerjaenisch** [eclipse/rdf4j#3128]
Dear RDF4J People!

The last two days I struggled to install RDF4J on a plain new Debian 10 system.

The RDF4J-Server component I run in Tomcat as RAW with the following result.

`Invocation of init method failed; nested exception is java.io.IOException: Unable to create logging directory /.RDF4J/server/logs
`
Setup:
From debian packages:
* openjdk-11
* tomcat9
* libslf4j-java
* liblog4j1.2-java

RDF4J from the current tar.gz install. WAR files copied to /var/lib/tomcat/webapps/.

I think this is a not too exotic setup.

Running the same WAR in jetty I get the same exception but with a bit more friendly path:

`Invocation of init method failed; nested exception is java.io.IOException: Unable to create logging directory /.RDF4J/server/logs`

When I run the code in eclipse (the console application) the same logging code produces /home/<user>/.RDF4J/server/logs

Any cases are for from optimal. No one likes to give write a web app access to paths like that :-).

The strace's I did show me that RDF4J does look for logging config files but at weird positions e.g.

```
/var/lib/tomcat9/webapps/rdf4j-server/WEB-INF/classes/org/eclipse/rdf4j/common/app/config/defaults/logging.properties
/var/lib/tomcat9/lib/org/eclipse/rdf4j/common/app/config/logging.properties
```

But RDF4J never ever ask for a logback.xml file which is given by the WAR.

Surely I miss something here.

Any help appreciated,

Volker

**Comment by barthanssens** [comment]
Hi Volker,

have you tried setting the `org.eclipse.rdf4j.appdata.basedir`  (and if you're running tomcat as a systemd service, you might also need to modify the service file) ? That might do the trick...

See also
* https://rdf4j.org/documentation/tools/server-workbench/#application-directory-configuration
* https://rdf4j.org/documentation/tools/server-workbench/#logging-configuration

**Comment by volkerjaenisch** [comment]
@barthanssens 

Thank you so much for the fast answer. I have solved the problem in no time.

I really missed that documentation bit. Installation is a quite complex case and if you are not familiar with Java and the where abouts you can get lost quickly. 

Same with Python installation in principal. If you come from Java you will be lost at first.

But : In the python plane there are for any application some "walk through" tutorials for some platforms. These are not complete, nor accurate, nor perfect but they give you a base line, something to work with. I really miss such a thing in the java plane.

I did not found any base line tutorial to setup RDF4J for non Java Programmers.
The RDF4J Documentation may be complete in a mathematical sense for the JAVA programmer, but for the beginners they are of no use.  

I have the experience of 40 years of programing and I stuck. 

Cheers,
Volker

**Comment by barthanssens** [comment]
Hi Volker,

glad it worked that way... admittedly the getting started part of the documentation can be improved, most of the documentation is indeed written for/by Java developers.
FWIW, we're also working on a more easy way to set up a read-only endpoint (#2904) and integration with Spring framework (#3059)
