### ISSUE TITLE
RepositoryManager should validate input configuration on add

### ISSUE THREAD

**Issue by volkerjaenisch** [eclipse/rdf4j#3169]
Hi RDF4J developers!

Yesterday I spent 4 hours finding the cause that I could no longer delete any repository (Via workbench or programmatically).

The cause was a memory-custom repository with bogus SPARQL that a test run had created.

Utilizing the following repo config via the restAPI  ...

```
print(repo_config) 
#
# Sesame configuration template for a main-memory repository with
# a custom graph query inference rule.
#
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>.
@prefix rep: <http://www.openrdf.org/config/repository#>.
@prefix sr: <http://www.openrdf.org/config/repository/sail#>.
@prefix sail: <http://www.openrdf.org/config/sail#>.
@prefix cgqi: <http://www.openrdf.org/config/sail/customGraphQueryInferencer#>.
@prefix ms: <http://www.openrdf.org/config/sail/memory#>.
@prefix sp: <http://spinrdf.org/sp#>.
@prefix sb: <http://www.openrdf.org/config/sail/base#>.
[] a rep:Repository ;
   rep:repositoryID "memory_customrule" ;
   rdfs:label "memory_customrule" ;
   rep:repositoryImpl [
      rep:repositoryType "openrdf:SailRepository" ;
      sr:sailImpl [
         sail:sailType "openrdf:CustomGraphQueryInferencer" ;
         cgqi:queryLanguage "SPARQL" ;
         cgqi:ruleQuery [
         	a sp:Construct ;
         	sp:text '''This is bogus'''
         ];
         cgqi:matcherQuery [
         	a sp:Construct ;
         	sp:text '''This is bogus'''
         ];
         sail:delegate [
            sail:sailType "openrdf:MemoryStore" ;
	        sail:iterationCacheSyncThreshold "10000";
            ms:persist false ;
            ms:syncDelay 0;
            sb:evaluationStrategyFactory "org.eclipse.rdf4j.query.algebra.evaluation.impl.StrictEvaluationStrategyFactory"
         ]
      ]
   ].

```
... with HTTP PUT on /repositories/memory_customrule one will create successfully a repository. 

![Bildschirmfoto vom 2021-07-13 21-19-28](https://user-images.githubusercontent.com/2539336/125512204-f493ecdc-7043-4dbc-91c2-550eec3348e0.png)

The exceptions in the next screen shot indicate that the system is out of order: 

![Bildschirmfoto vom 2021-07-13 21-19-39](https://user-images.githubusercontent.com/2539336/125512222-9ecb1a45-734a-4113-8d6a-da6ae9d7c989.png)

that effectively stalls deletion of any repository (not only itself!). 

![Bildschirmfoto vom 2021-07-13 21-25-16](https://user-images.githubusercontent.com/2539336/125512914-72c70f1d-46d3-4f08-9b47-a1123930c10c.png)

The weirdest part is the distance effect of this bug. I single bogus repository stalls operation on ALL  repositories. The only explanation for this behavior is the following:

When deleting a repository via the RestAPI RDF4J looks up all repositories available to find the correct repository to delete. While looking up the repositories the repository configuration of each repository is parsed.
While parsing the bogus SPARQL the parser faults and the whole delete process goes to hell.

Cheers,
Volker

**Comment by jeenbroekstra** [comment]
This is actually not restricted to the REST API but is a bug in the LocalRepositoryManager. It currently fails to validate a repository config on adding.
