### ISSUE TITLE
Building main on Windows / AdoptOpenJDK16 fails

### ISSUE THREAD

**Issue by barthanssens** [eclipse/rdf4j#3253]
### Current Behavior

`mvn clean install` fails on Windows 10 with AdoptOpenJDK 16, both in git cmd and in Windows command prompt

```
[ERROR] Failed to execute goal com.github.siom79.japicmp:japicmp-maven-plugin:0.14.3:cmp (default) on project rdf4j-model-api: Execution default of goal com.github.siom79.japicmp:japicmp-maven-plugin:0.14.3:cmp failed: An API incompatibility was encountered while executing com.github.siom79.japicmp:japicmp-maven-plugin:0.14.3:cmp: java.lang.ExceptionInInitializerError: null
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>com.github.siom79.japicmp:japicmp-maven-plugin:0.14.3
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/c:/java/mvnrepo/com/github/siom79/japicmp/japicmp-maven-plugin/0.14.3/japicmp-maven-plugin-0.14.3.jar
import: Entry[import  from realm ClassRealm[project>org.eclipse.rdf4j:rdf4j:3.7.2-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]]
...
[ERROR]
[ERROR] -----------------------------------------------------
[ERROR] : Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @4b6d3351
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :rdf4j-model-api
```

### Expected Behavior

Build should complete without errors

### Steps To Reproduce

- MS-Windows 10 R2 64-bit
- AdoptOpenJDK 16.0.1 with OpenJ9 0.26
- Maven 3.8.1
- JAVA_HOME en PATH correctly set

### Version

3.7.2-SNAPSHOT

### Are you interested in contributing a solution yourself?

Yes

### Anything else?

Probably due to `--illegal-access` now defaulting to `deny` instead of `permit`

**Comment by barthanssens** [comment]
Looks like an japicmp issue: upgrading to 0.15.3 fixes the issue

**Comment by barthanssens** [comment]
v0.15.1 has a license score 60 on ClearlyDefined, so I guess this qualifies

https://clearlydefined.io/definitions/maven/mavencentral/com.github.siom79.japicmp/japicmp/0.15.1

**Comment by jeenbroekstra** [comment]
Given that this is maven plugin that we use but don't distribute, I'm kind of fine with not filing a CQ for it, as long as we've done a quick sanity check ourselves that the license is not something exotic.

**Comment by barthanssens** [comment]
Seems to be Apache 2.0... and the plugin is part of the same repo as the japicmp tool so it should be covered by the CD overall project score... So, good to go.
