### ISSUE TITLE
Provide constants for the LDP namespace

### ISSUE THREAD

**Issue by knoan** [eclipse/rdf4j#326]
(Migrated from https://openrdf.atlassian.net/browse/SES-2380)

Package `org.openrdf.model.vocabulary` should be extended with a utility class for the Linked Data Platform namespace, as defined in the attached file.

---

[LDP.java.zip](https://github.com/eclipse/rdf4j/files/456048/LDP.java.zip)

**Comment by barthanssens** [comment]
I'm not using the LDP in our projects, but if (and only if) people are still interested in it, I could make a vocabulary (just like the ROV etc I've added),

**Comment by knoan** [comment]
Still definitely interested. And a useful companion to https://github.com/eclipse/rdf4j/issues/800, imho.
