### ISSUE TITLE
SHACL - ShaclSailConnection should use bulk validation if the underlying store is empty

### ISSUE THREAD

**Issue by hmottestad** [eclipse/rdf4j#3260]
When initially loading data into the ShaclSail we should use bulk validation since we will anyway be validating the entire store. Bulk validation is faster.

**Comment by jeenbroekstra** [comment]
This, to me, sounds like an enhancement, rather than a bug fix. It sounds like substantial change to the behavior of SHACL sail, and potential risk of unintended consequences for existing users.

**Comment by hmottestad** [comment]
The only difference between bulk validation and transactional validation is performance. They both offer the same guarantees and work at the same points during the transaction.

**Comment by hmottestad** [comment]
The ShaclSailConnections already has some code that detects that the underlying sail is empty so that we don't need to track changes with the notifying sail and then does some nifty stuff depending on what isolation level you are using and if the base sail is a memory store or not. This was all prior to the bulk validation support though, so should have been cleaned up when that was introduced.

**Comment by hmottestad** [comment]
However, all that being said I might end up adding this in as part of 4.0.0 through https://github.com/eclipse/rdf4j/pull/3245
