### ISSUE TITLE
Use a OpenAPI specification to drive the REST API documentation

### ISSUE THREAD

**Issue by abrokenjester** [eclipse/rdf4j#3267]
### Problem description

The current RDF4J REST API documentation (at https://rdf4j.org/documentation/reference/rest-api/)  is hand-written markdown text. This is hard to maintain and also doesn't offer some nice features that typical OpenAPI documentations do (like automatic copy-paste of curl requests to try out).

We do seem to have an openapi specification by the way (in `tools/server/src/main/webapp/swagger.yaml`) but this has not been updated in a long time and has no connection to the documentation.

### Preferred solution

A openapi configuration + setup that allows us to generate documentation for the website in a way that fits in, and makes future maintenance eaiser.

### Are you interested in contributing a solution yourself?

Yes

**Comment by seralf** [comment]
Do you plan to add the java annotation for generating swagger by jaxrs or spring?

Recently, working with Quarkus, I found that it's also possible to have a static swagger file on quarkus, but I found no way to do this with spring boot. Having the latest swagger definition somewhere in the distribution may help people who need (for example) to generate a skeleton of a client, from swagger.
