### ISSUE TITLE
Website: link template code not replaced

### ISSUE THREAD

**Issue by barthanssens** [eclipse/rdf4j#3270]
### Current Behavior

The documentation on https://rdf4j.org/documentation/programming/repository/#creating-retrieving-removing-individual-statements shows a (template) link code `{{ < javadoc “Values” “model/util/Values.html” > }} `, but it is not rendered as a link.

### Expected Behavior

Template engine should replace this code with a link to the Values.html page

### Version

3.7.2-SNAPSHOT

### Are you interested in contributing a solution yourself?

Perhaps?

### Anything else?

At first sight, I don't see a difference with the other links that are correctly rendered... So perhaps the page just needs to be regenerated ?

**Comment by jeenbroekstra** [comment]
It might be as simple/stupid as some whitespaces where they shouldn't be... Haven't looked in detail but this has caught me out in the past. From the top of my head it should be `{{< javadoc .... `, not `{{ < javadoc ...`

**Comment by barthanssens** [comment]
Indeed, looks like a whitespace issue, thanks
