### ISSUE TITLE
Mime-type 'text/xml' as alternative to 'application/xml' 

### ISSUE THREAD

**Issue by outofbits** [eclipse/rdf4j#328]
Few vocabularies, when dereferenced, use **text/xml** for describing the returned content type, which is RDF/XML. According to RFC:
> If an XML document -- that is, the unprocessed, source XML document
   -- is readable by casual users, text/xml is preferable to
   application/xml.  MIME user agents (and web user agents) that do not
   have explicit support for text/xml will treat it as text/plain, for
   example, by displaying the XML MIME entity as plain text.
   Application/xml is preferable when the XML MIME entity is unreadable
   by casual users. ([RFC3023](https://www.ietf.org/rfc/rfc3023.txt), Chapter 3)

Currently the mime-types for RDFXML are ["application/rdf+xml", "application/xml"], so I want to ask, if **text/xml** may be a good enhancement of this list to support more vocabularies out there.l  

An example is [http://www.opengis.net/ont/geosparql#](http://www.opengis.net/ont/geosparql#).

**Comment by ansell** [comment]
I have no issues with adding text/xml based on its references in the RFC. application/rdf+xml will remain the preferred type (although we want to reduce its q-value given its issues with supporting legal IRIs as predicates #299 ). The addition of a low q-value text/xml in an Accept header should not change any existing responses that follow the preferred types and the others can be fixed for particular servers individually if they respond with non-RDF when text/xml is in the list at a low q-value.
