### ISSUE TITLE
RdfCollection.collectionOf() should return RdfCollection 

### ISSUE THREAD

**Issue by reckart** [eclipse/rdf4j#3320]
### Current Behavior

```
public static RdfObject collectionOf(QueryElement... aElements)
    {
        return new RdfCollection(asList(aElements));
    }
```

### Expected Behavior

```
    public static RdfCollection collectionOf(QueryElement... aElements)
    {
        return new RdfCollection(asList(aElements));
    }
```

Note that RdfCollection implements RdfObject, so the change should be backwards compatible.

### Steps To Reproduce

This does not compile without a typecast.

```
((RdfCollection) collectionOf(VAR_SUBJECT, VAR_SCORE, VAR_MATCH_TERM)).has(...)
```

Full example in a query to a Fuseki repo:

```
((RdfCollection) collectionOf(var("subj"), var("score"), var("match"))
  .has(iri("http://jena.apache.org/text#query"),
    collectionOf(var("match"), literalOf("john smith")));
```

### Version

3.7.2

### Are you interested in contributing a solution yourself?

Perhaps?

**Comment by jeenbroekstra** [comment]
This sounds like an Apache Jena problem, rather than an Eclipse RDF4J one.

For one thing, RDF4J does not _have_ a class called RdfCollection, though we have an `RDFCollections` util class - but it has no `collectionOf` method.

**Comment by reckart** [comment]
Right ;) There is no such class in RDF4J - actually not in Jena either, it's in our very own INCEpTION code ;) Sorry for the noise.

But that said, having such a class in RDF4J would be good! But that's a different issue.
