### ISSUE TITLE
Massive performance degradation and loss of results in SPARQL queries between RDF4J 2.5.2 and 3.7.2

### ISSUE THREAD

**Issue by PravinPrameKumar** [eclipse/rdf4j#3322]
### Current Behavior

We are currently running RDF4J version 2.5.2 but need to upgrade to the latest version for security reasons. We tried upgrading to 3.7.2 but we found that the performance of many of our SPARQL queries have massively degraded - actually, they don't even complete execution. These same queries complete in under 20 milliseconds in version 2.5.2.
We can roughly see that the problematic queries have UNIONs in them. For one of these queries that hangs forever, we found a way to rewrite it without the UNION keyword which caused it to work again. This was not a trivial exercise, so it is not feasible for us to replace the hundreds of queries we have in our system. 

I isolated and stripped down a query and RDF store data to repro this. I found that the performance of this query scales with the (decreasing) size of the RDF store. A full TTL export of our test RDF store is about 15 MB. The query hangs when run on the full store (I didn’t bother waiting after many minutes). When I cut down the store to 7 MB, the query took about 56 seconds. From 5 to 2 MB, the query went from 46 to 8 seconds. Note that the sizes I refer to here are the ttl export sizes. The memorystore.data file for the attached example RDF store comes to 509 KB.
 I also found that the problematic queries run on 3.7.2 don’t return any results at all (they should and do return results on 2.5.2).

The attached zip file contains the following files, which describe and can be used to reproduce this issue:
Screenshots show the query running in the workbench and in our internal tool.
Logs are prefixed by 252 for the test machine with RDF4J 2.5.2 and 372 for version 3.7.2.
Here are some extracts showing the time difference for the two versions:
372:
2021-09-08 12:07:35,424 10008 [repositories/NativeJStore] DEBUG c.g.z.f.c.CompressingHttpServletResponse - Committing response without compression
2021-09-08 12:07:42,949 17533 [repositories/NativeJStore] INFO  o.e.r.h.s.r.TupleQueryResultView - Request for query -2131556384 is finished

252:
2021-09-08 12:07:23,803 28861 [repositories/NativeJStore] DEBUG c.g.z.f.c.CompressingHttpServletResponse - Committing response without compression
2021-09-08 12:07:23,805 28863 [repositories/NativeJStore] INFO  o.e.r.h.s.r.TupleQueryResultView - Request for query 3392903 is finished

I include two sets of logs (example1 and 2), no functional difference, I just ran the test twice.

### Expected Behavior

The same query run on RDF4J 2.5.2 and 3.7.2 should complete in similar times and return the same results.

### Steps To Reproduce

[rdf4j_query_bug3.zip](https://github.com/eclipse/rdf4j/files/7141442/rdf4j_query_bug3.zip)

(EDIT I updated this zip file with new data, new file is called rdf4j_query_bug3.zip).

Repro steps:
	1. Create a memory store repository and fill it with data from rdfstore_clean.ttl using Add RDF. See screenshots. 
	2. In repro_query_clean.rq, there are two queries available. Run the stripped-down one to get similar test results as I've described. I've also included our full actual query that does not complete even with this cut-down RDF store (> few minutes). Note the stripped-down query may not make sense, I obtained it by just removing stuff out of the full query to get it as simple as possible while still demonstrating this problem.
	3. Observe that when run on a machine with RDF4J 2.5.2, the query completes in under 20 ms; whereas when run on a machine with RDF4J 3.7.2, the query takes about 8 to 9 seconds to complete. 
	4. Also observe that the query returns no results when run on 3.7.2, while it does on 2.5.2.

### Version

3.7.2

### Are you interested in contributing a solution yourself?

Perhaps?

### Anything else?

Recall that this is a heavily stripped-down example - in our production environments, this query never finishes.

If relevant, version of tomcat used on our systems:
server.info=Apache Tomcat/9.0.43
server.number=9.0.43.0
server.built=Jan 28 2021 20:25:45 UTC

Thanks for your help with this.

**Comment by barthanssens** [comment]
Thanks for reporting the issue and the detailed test material. 
Would it perhaps be possible to do a quick test with e.g. version 3.4.0, to narrow down a bit the version(s) where the degradation occurs ?

**Comment by PravinPrameKumar** [comment]
Hi Bart, thanks for your response - we reproduced this issue in 3.3.1

**Comment by jeenbroekstra** [comment]
It appears the problem was first introduced in release 3.0.3. The full query executes for me in ~130ms (with 8 results) when using version 3.0.2, but does not complete in reasonable time when using 3.0.3. A likely suspect is that this is a side effect of the fix we did for GH-1642. I'll take a look at the query plans.

**Comment by jeenbroekstra** [comment]
```
Projection (resultSizeActual=8)
╠══ProjectionElemList
║     ProjectionElem "property"
║     ProjectionElem "EggplantName" AS "TreeName"
║     ProjectionElem "upperParamName" AS "paramName"
║     ProjectionElem "TreeId"
║     ProjectionElem "paramId"
╚══Extension (resultSizeActual=8)
      Join (HashJoinIteration) (resultSizeActual=8)
      ╠══BindingSetAssignment ([[property=Eggplant:example.com,2012:Lion/Pummelo#_123456Beetroot_1BeetrootCucumber_BeetrootMango_Property;TreeId=Eggplant:example.com,2012:Lion/Pummelo#_123456.Squirrel.Beetroot_1_Cucumber;EggplantName="Beetroot_1_Cucumber";upperParamName="Tomato"], [property=Eggplant:example.com,2012:Lion/Pummelo#_123456Beetroot_1Ginger_GingerSugar_Property;TreeId=Eggplant:example.com,2012:Lion/Pummelo#_123456.Squirrel.Beetroot_1_Ginger;EggplantName="Beetroot_1_Ginger";upperParamName="OP"], [property=Eggplant:example.com,2012:Lion/Pummelo#_123456Beetroot_1Ginger_GingerMango_Property;TreeId=Eggplant:example.com,2012:Lion/Pummelo#_123456.Squirrel.Beetroot_1_Ginger;EggplantName="Beetroot_1_Ginger";upperParamName="Tomato"], [property=Eggplant:example.com,2012:Lion/Pummelo#_123456Beetroot_1SecureZoneInterfacePepperProximityShallot_ShallotMango_Property;TreeId=Eggplant:example.com,2012:Lion/Pummelo#_123456.Squirrel.Beetroot_1_ShallotState;EggplantName="Beetroot_1_ShallotState";upperParamName="Tomato"]]) (costEstimate=1, resultSizeEstimate=1, resultSizeActual=4)
      ╚══Union (new scope) (resultSizeActual=733.9K)
         ├──Join (JoinIterator) (resultSizeActual=366.9K)
         │  ╠══StatementPattern (costEstimate=18, resultSizeEstimate=1.3K, resultSizeActual=1.3K)
         │  ║     Var (name=TreeId)
         │  ║     Var (name=_const_61b7e9d0_uri, value=http://www.example.com/models/Walnut/Possum/Wombat/1.0#hasTaros, anonymous)
         │  ║     Var (name=_anon_c2ddd072_9e39_49a9_80cd_1c44e5a61ff8, anonymous)
         │  ╚══Join (JoinIterator) (resultSizeActual=366.9K)
         │     ├──StatementPattern (costEstimate=22, resultSizeEstimate=2.0K, resultSizeActual=253.5K)
         │     │     Var (name=_anon_c2ddd072_9e39_49a9_80cd_1c44e5a61ff8, anonymous)
         │     │     Var (name=_const_709173aa_uri, value=http://www.example.com/models/Walnut/Possum/Wombat/1.0#containsTaro, anonymous)
         │     │     Var (name=paramId)
         │     └──StatementPattern (costEstimate=1, resultSizeEstimate=2.4K, resultSizeActual=366.9K)
         │           Var (name=paramId)
         │           Var (name=_const_60b107d7_uri, value=http://www.example.com/models/Walnut/Possum/Wombat/1.0#hasAlias, anonymous)
         │           Var (name=upperParamName)
         └──Join (JoinIterator) (resultSizeActual=366.9K)
            ╠══StatementPattern (costEstimate=25, resultSizeEstimate=2.4K, resultSizeActual=2.4K)
            ║     Var (name=paramId)
            ║     Var (name=_const_60b107d7_uri, value=http://www.example.com/models/Walnut/Possum/Wombat/1.0#hasAlias, anonymous)
            ║     Var (name=upperParamName)
            ╚══Join (JoinIterator) (resultSizeActual=366.9K)
               ├──StatementPattern (costEstimate=22, resultSizeEstimate=2.0K, resultSizeActual=2.4K)
               │     Var (name=TaroSet)
               │     Var (name=_const_709173aa_uri, value=http://www.example.com/models/Walnut/Possum/Wombat/1.0#containsTaro, anonymous)
               │     Var (name=paramId)
               └──Join (JoinIterator) (resultSizeActual=366.9K)
                  ╠══StatementPattern (costEstimate=8, resultSizeEstimate=288, resultSizeActual=2.5K)
                  ║     Var (name=_anon_49f55533_f877_467a_a7d8_28025a6b0bf0, anonymous)
                  ║     Var (name=_const_d3644a5f_uri, value=http://www.example.com/models/Walnut/Possum/Wombat/1.0#hasTaroSet, anonymous)
                  ║     Var (name=TaroSet)
                  ╚══Join (JoinIterator) (resultSizeActual=366.9K)
                     ├──StatementPattern (costEstimate=33, resultSizeEstimate=4.3K, resultSizeActual=11.2M)
                     │     Var (name=TreeId)
                     │     Var (name=_const_f5e5585a_uri, value=http://www.w3.org/1999/02/22-rdf-syntax-ns#type, anonymous)
                     │     Var (name=type)
                     └──ArbitraryLengthPath (costEstimate=1, resultSizeEstimate=86.0K, resultSizeActual=366.9K)
                           Var (name=type)
                           StatementPattern (resultSizeEstimate=410)
                              Var (name=type)
                              Var (name=_const_4592be07_uri, value=http://www.w3.org/2000/01/rdf-schema#subClassOf, anonymous)
                              Var (name=_anon_49f55533_f877_467a_a7d8_28025a6b0bf0, anonymous)
                           Var (name=_anon_49f55533_f877_467a_a7d8_28025a6b0bf0, anonymous)
      ExtensionElem (TreeName)
         Var (name=EggplantName)
      ExtensionElem (paramName)
         Var (name=upperParamName)
```

**Comment by yuandalixiang** [comment]
Hi Jeen,

Thank you so much for the fix you came up with in such a short time (and on your weekend time)!

We spent sometime on last Friday/Saturday to try 10+ times using different versions/commits and did identify the exact code change which brought us this issue -- yes, the same one you mentioned before; we thought it'd be fine to update you here later on Monday. But then we found out that you're very much proactive and  had already posted not only the identified code change, but also the commit of fix! Wow, that's amazing!

Earlier today, we did a quick test using the v3.7.2 code plus your commit, and confirmed that the issue was gone. We still need to do a full regression testing to verify if this new version works fine with our application. So we'll update you guys a little bit later (like tomorrow). But here we'd like to say a big thank-you, before posting our final testing result.

Appreciated your help, and will update you soon!

**Comment by jeenbroekstra** [comment]
Thanks for confirming the fix works! Please note it may still need a small refinement, but I'm hoping to find time to get that sorted and do a patch release this weekend.

**Comment by RobinatGithhub** [comment]
Hi Jeen,

Good to hear that a patch release is coming this weekend! 
We did run a regression today with our real testing data and we can confirm that the fix did work. So we'll have another round of testing with the coming release. Look forward to that!

- Robin

**Comment by PravinPrameKumar** [comment]
Jeen, thank you very much for your work and the super-fast release.
It looks good in our quick tests and I'm sure it will be fine for the full test.
Thanks again, we really appreciate it. :)
