### ISSUE TITLE
SparqlBuilder: Using the filter() method multiple times just uses the last filter

### ISSUE THREAD

**Issue by macks36** [eclipse/rdf4j#3349]
### Current Behavior

Using the filter() method multiple times simply overrides the last filter so that only the last filter that was added is actually part of the query. 

So
```
graphPattern.filter(Expressions.regex(var1, "test", "i"));
graphPattern.filter(Expressions.equals(var1, var2));
```

produces just
```
FILTER ( ?var1 = ?var2 )
```

### Expected Behavior

Everytime I add a filter using the filter() method, another seperate filter should be added to the query.

So
```
graphPattern.filter(Expressions.regex(var1, "test", "i"));
graphPattern.filter(Expressions.equals(var1, var2));
```

should produce

```
FILTER ( REGEX( ?var1, "test", "i" ) )
FILTER ( ?var1 = ?var2 )
```

### Version

3.7.2

### Are you interested in contributing a solution yourself?

No

### Anything else?

This problem was already mentioned in https://github.com/eclipse/rdf4j/discussions/3205. However, I didn't find an issue related to it so I am creating one myself now.

I know from the linked discussion that there is a workaround for this by using the "and" Expression to use the filter() method only once:
```
graphPattern.filter(Expressions.and(Expressions.regex(var1, "test", "i"), Expressions.equals(var1, var2)));
```
However, that doesn't really help me in my case, since in want to add filters to the query dynamically based on certain conditions. With the workaround I would need to pass my previous Expressions around, making it less dynamic.

**Comment by jeenbroekstra** [comment]
Thanks for reporting this @macks36
