### ISSUE TITLE
Compile JDK17

### ISSUE THREAD

**Issue by barthanssens** [eclipse/rdf4j#3350]
### Problem description

Check if RDF4J compiles on JDK17. Probably not an issue since we already compile on JDK16.

### Preferred solution

Compiles without changes

### Are you interested in contributing a solution yourself?

Yes

**Comment by hmottestad** [comment]
Also need to update maven-source-plugin to the newest version covered by that CQ.

**Comment by hmottestad** [comment]
And update the base docker image to jdk11 since jdk8 won't read the code compiled with jdk17.
