### ISSUE TITLE
Add User Documentation for rdf4j-spring module

### ISSUE THREAD

**Issue by fkleedorfer** [eclipse/rdf4j#3387]
### Problem description

The module `rdf4j-spring` has been added to the repository recently. Javadoc is present, but better user documentation has been requested, leading a new user to building a simple spring-boot application that uses an RDF4J repository as its data backend.

### Preferred solution

Two aspects seem necessary
1. Build a small demo project 
2. Write some user documentation, pointing to the demo project when appropriate and using it for creating source code or config snippets.

### Are you interested in contributing a solution yourself?

Yes

### Alternatives you've considered

The right location for the demo project is a bit unclear. It has been suggested to make it a submodule of the rdf4j-examples module. This is a straightforward choice for us working on the codebase, but for someone who actually wants to tinker with the demo project, it is cumbersome: they would have to check out the whole huge rdf4j project. Also, linking to the demo from somewhere else isn't super straightforward, and it's not even easy to find it in the checked out project, let alone build it quickly. If we could create a `rdf4j-spring-demo` project in the eclipse organization, users could clone just that, which would be a lot easier and faster to do. I am not sure, however, if we have that option.

**Comment by fkleedorfer** [comment]
@jeenbroekstra I'll start work on the demo as an rdf4j-examples module, for now, but as I said, I'd prefer it to be a top-level project on github somewhere.

**Comment by fkleedorfer** [comment]
Correction: It can't be a submodule of `rdf4j-examples` as that module is has `jar` packaging, not `pom` packaging. I'll add the demo as a toplevel module for now, until it finds its final home. 

Apparently, some rdf4j examples are just demos of java code with essentially the same project config, for which it's ok to have them all in the same module. On the other hand, at least `rdf4j-spring-demo` requires its own module, as the project config is part of the demo. I don't know if there are other use cases for demos with dedicated modules/projects, but at least for `rdf4j-spring-demo`, it may be necessary in the future to maintain different versions of the demo for different spring versions. 

Options:
1. Refactor rdf4j-examples such that it becomes a parent module and put all the existing examples in a submodule; add `rdf4j-examples-rdf4j-spring` (as it would have to be called according to the naming convention) as another submodule 
2. Add another rdf4j submodule (`rdf4j-demos` maybe?) as a parent for all demos/examples that need a dedicated module, put `rdf4j-demo-rdf4j-spring` there
3. Create a separate toplevel project on github, e.g. `eclipse/rdf4j-examples`, which has one submodule for each example
4. Leave `rdf4j-spring-demo` as a toplevel module in the `rdf4j` project

My priorities would be 3 > 1 > 2 > 4

**Comment by fkleedorfer** [comment]
... 
5. put it as a submodule in `rdf4j-spring-components`

My updated preferences: 3 > 1 > 5 > 2 > 4

**Comment by jeenbroekstra** [comment]
My personal preference is for option 1. Fixing that will require tweaks to the links in the tutorial though.

**Comment by fkleedorfer** [comment]
Resolved with PR #3398
