### ISSUE TITLE
Implement alternative embedded persistent backend

### ISSUE THREAD

**Issue by kenwenzel** [eclipse/rdf4j#3416]
### Problem description

RDF4J's embedded persistent backend is fast and supports ACID properties, but on the downside it lacks support to shrink its database file for values (value store).

### Preferred solution

The value store (or also the BTree-based triple store) may be replaced by an embedded KV store. A perfomant store is LMDB (see benchmarks below).

Since [LMDB is written in C](https://github.com/LMDB/lmdb) an adapter for Java is required. 
LWJGL is a high performance library for 3D application and game development with Java (also used for Minecraft) and has bindings for LMDB and [a liberal BSD-Style license](https://www.lwjgl.org/license).

### Are you interested in contributing a solution yourself?

Yes

### Alternatives you've considered

Two promising options are:
- [LevelDB](https://en.wikipedia.org/wiki/LevelDB) with its Java port [LevelDB](https://github.com/pcmind/leveldb)
- [LMDB](https://en.wikipedia.org/wiki/Lightning_Memory-Mapped_Database) with [LWJGL Java bindings](https://github.com/LWJGL/lwjgl3)

While LevelDB may have better write performance and generally is more space efficient, LMDB has full ACID properties and excellent read performance for random reads.
Some benchmarks can be found here:
http://www.lmdb.tech/bench/microbench/

**Comment by jeenbroekstra** [comment]
LMDB dependencies included are:

```
INFO] +- org.lwjgl:lwjgl-lmdb:jar:3.3.0:compile
[INFO] |  \- org.lwjgl:lwjgl:jar:3.3.0:compile
[INFO] +- org.lwjgl:lwjgl-lmdb:jar:natives-linux:3.3.0:compile
[INFO] +- org.lwjgl:lwjgl-lmdb:jar:natives-macos-arm64:3.3.0:compile
[INFO] +- org.lwjgl:lwjgl-lmdb:jar:natives-macos:3.3.0:compile
[INFO] +- org.lwjgl:lwjgl-lmdb:jar:natives-windows:3.3.0:compile
[INFO] +- org.lwjgl:lwjgl:jar:natives-linux:3.3.0:compile
[INFO] +- org.lwjgl:lwjgl:jar:natives-macos:3.3.0:compile
[INFO] +- org.lwjgl:lwjgl:jar:natives-macos-arm64:3.3.0:compile
[INFO] +- org.lwjgl:lwjgl:jar:natives-windows:3.3.0:compile
```

How we file our CQs depends on whether we can switch the natives extensions over to optional runtime dependencies.

**Comment by jeenbroekstra** [comment]
CQs: 
- [ ]  org.lwjgl:lwjgl-lmdb:jar:3.3.0 -> https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23838

**Comment by jeenbroekstra** [comment]
@kenwenzel I've reopened this so we can track things like adding documentation and minor improvements. If there's larger pieces of additional work I'd suggest creating a new ticket for those though.

**Comment by kenwenzel** [comment]
@jeenbroekstra Where should the documentation be added?

**Comment by jeenbroekstra** [comment]
> @jeenbroekstra Where should the documentation be added?

I think a seperate page underneath https://rdf4j.org/documentation/programming/ would be good. In git that lives in `site/content/documentation/programming/` - just add a new file called `lmdb-sail.md` there (copy paste some relevant template/header info from one of the other files there), and we can write some basic "how to use" instructions (I guess the main thing is some instructions on getting the right native extensions installed).
