### ISSUE TITLE
design new logo

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#35]
We need a new logo (and house style) for the rdf4j project, to visually distinguish ourselves from the 'old' Sesame project. This issue can be used to propose and discuss designs.

**Comment by jeenbroekstra** [comment]
First attempt at a new logo, using the 'chain link' metaphor. Comments welcome. I can easily produce modified versions of this (different colors, fonts, etc). Thoughts?

![rdf4j-logo-224](https://cloud.githubusercontent.com/assets/728776/14126569/4bae6342-f66e-11e5-876a-f6da9ff7be0c.png)

**Comment by dwvisser** [comment]
I like the idea of 3 links in the chain, evocative of RDF statements: Conceptually, this: http://www.clker.com/cliparts/a/1/5/1/13769478621002404530chain_link_3.png though stylistically I like your graphic

**Comment by jeenbroekstra** [comment]
Nice thought - I hadn't even considered that when designing it - I just played with the notion of "linking data".

**Comment by jeenbroekstra** [comment]
I made a minor variation on the logo - it's slightly narrower. I think that this makes it more visually obvious that these are chain links, and it fits in better with the (very condensed) font choice.

full size
![rdf4j-logo-v2-224](https://cloud.githubusercontent.com/assets/728776/14128329/5b632968-f67c-11e5-8206-20a9f1d10c3d.png)

smaller
![rdf4j-logo-v2-100](https://cloud.githubusercontent.com/assets/728776/14128332/61c39e3c-f67c-11e5-8100-85aeba1607ea.png)

**Comment by jeenbroekstra** [comment]
Also the more I look at the color I picked, the more I dislike it. I'll cook up some alternative colors later. Any special requests?

**Comment by jeenbroekstra** [comment]
Orange : ![rdf4j-logo-orange-224](https://cloud.githubusercontent.com/assets/728776/14130034/1a5d1842-f68c-11e5-8d60-fabde64ad5b7.png)
Dark blue: ![rdf4j-logo-darkblue-224](https://cloud.githubusercontent.com/assets/728776/14130035/1bf9b32c-f68c-11e5-8cea-a58d24af8004.png)

**Comment by aschwarte10** [comment]
The proposal looks good to me. For me the orange version looks "strongest" and can give best identification

**Comment by dwvisser** [comment]
FWIW, I like dark blue best. Orange looks great, too.

**Comment by jeenbroekstra** [comment]
I personally like orange best I think - blue looks good but it's such a 'generic' color. Thanks for your feedback sofar, everyone. I'll start tinkering with a new site design and a new look and feel for the webapps. 

On that note, @dwvisser , I know you are on a different project now, but any chance that you can find a few spare hours to help with a UI overhaul for the workbench and server? It's mainly about removing old logos and updating names and copyright notices, etc.

**Comment by jeenbroekstra** [comment]
Orange it is then.
