### ISSUE TITLE
More query benchmarks

### ISSUE THREAD

**Issue by hmottestad** [eclipse/rdf4j#3521]
Create more query benchmarks.

**Comment by kenwenzel** [comment]
I would suggest to base the benchmarks for insertion performance and the benchmarks for query performance on the same data.
I've created a generator function for extended FOAF data but I am also fine with DCAT data:
https://github.com/kenwenzel/rdf4j/commit/882f2672934457a81d9e2d7566a23a3106bc5c71

**Comment by hmottestad** [comment]
`loadRealData()` in the `LoadingBenchmark` uses the same DCAT file as the query benchmarks. The other benchmarks were created to compare some performance improvements I worked on for handling duplicate data in the MemoryStore.

**Comment by kenwenzel** [comment]
Do you think that its possible to completely generate "real" data that is very similar to the one contained in the DCAT file? I think it would be helpful to have data sets in different sizes (1k, 100k, 1mio, 100mio etc.)
It would also be cool if the benchmarks for memory store, native store and others are all the same....

**Comment by hmottestad** [comment]
The biggest benefit of the real data is that queries can be more realistic. The generated data is particularly useful for being able to generate different sizes so we can see how things scale.

I would like to be able to share the benchmarks between all the different stores. My issue at the moment is that if I create a shared class that can be extended with each stores, then it becomes really hard to run just one benchmark method with the JMH plugin for IntelliJ.

**Comment by hmottestad** [comment]
Ill leave this open for now if we want to do more work on the benchmarks.
