### ISSUE TITLE
Upgrade JMH to 1.33

### ISSUE THREAD

**Issue by JervenBolleman** [eclipse/rdf4j#3535]
### Problem description

The included JMH version is 1.21. Newer versions make it easier to run JFR profiling. e.g.

```
java -Xms2G -Xmx2G -Xmn1G -XX:+UseSerialGC -jar core/sail/memory/target/jmh-benchmarks.jar -f 0 -prof jfr QueryBenchmark
```

Without needing to change the java code.

### Preferred solution

jmhVersion in pom.xml = 1.33

### Are you interested in contributing a solution yourself?

Yes

**Comment by barthanssens** [comment]
Would 1.32 also work ? (since Eclipse IPZilla already has entries CQ23499 and CQ23500 for jmh-core and jmh-generator-annprocess 1.32)

**Comment by JervenBolleman** [comment]
It would. We need to have an IPZilla task as the [clearly defined license score](https://clearlydefined.io/?sort=releaseDate&sortDesc=true&name=jmh-core) is below 60 the [cutoff](https://www.eclipse.org/projects/handbook/#ip-clearlydefined-using).

I still need to read up on how to deal with this correctly. So I think it would be worth the effort for me to do it so that I learn how to.

**Comment by JervenBolleman** [comment]
Made a CQ23887 for jmh-core 1.33, will do the same for jmh-generator-annprocess once that is approved.

**Comment by barthanssens** [comment]
It is a fairly easy process
(downloading the source jar from e.g. https://repo1.maven.org/maven2/org/openjdk/jmh/ before creating the ticket is probably convenient , because you'll have to attach the source after creating the ticket)

**Comment by JervenBolleman** [comment]
jmh-core CQ is [accepted](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23887). Now I will make one for the jmh-generator-annprocess.

**Comment by JervenBolleman** [comment]
waiting for [23894](http://dev.eclipse.org/ipzilla/show_bug.cgi?id=23894)

**Comment by JervenBolleman** [comment]
And approved.
