### ISSUE TITLE
Send single Accept header with comma-separated values

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#359]
(Migrated from https://openrdf.atlassian.net/browse/SES-2383)

Sesame's SPARQL client currently sends multiple Accept headers with its query requests, to indicate which response formats it can process. For example:

{noformat}
 Accept: text/csv;q=0.8
 Accept: application/sparql-results+xml 
{noformat}

While this is technically correct (see [section 4 in RFC2616|https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2] for details), it appears many SPARQL endpoint implementations have trouble processing request headers in this form. E.g. in the above example, they will choose to use text/csv (even if they do support application/sparql-results+xml). 

To facilate better interoperability, we should instead compose a single accept header, with the supported formats as comma-separated values:

{noformat}
Accept: text/csv;q=0.8, application/sparql-results+xml
{noformat}

**Comment by barthanssens** [comment]
Seems to be fixed org.openrdf.http.client.SparqlSession.java in RDF4J 2.1 uses "commaJoiner", and the class is deprecated in 2.2 (by SPARQLProtocolSession, which also uses comma separated accept header)

**Comment by jeenbroekstra** [comment]
Yes, pretty sure this is a duplicate. Can't immediately find the other issue though. Closing. Thanks!

**Comment by jeenbroekstra** [comment]
Duplicate of #228, which was fixed in release 2.0.
