### ISSUE TITLE
StatementAdded/Removed events for duplicate events in same txn

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#360]
(Migrated from https://openrdf.atlassian.net/browse/SES-2382)

See dicussion on https://groups.google.com/d/msgid/sesame-users/daef45b8-a3ba-43c6-bc21-88da64112289%40googlegroups.com?utm_medium=email&utm_source=footer

**Comment by barthanssens** [comment]
Is this a duplicate of #183 ?
