### ISSUE TITLE
SHACL - Support validation of named graph

### ISSUE THREAD

**Issue by hmottestad** [eclipse/rdf4j#3622]
Support `sh:shapesGraph`

See: https://www.w3.org/TR/shacl/#sh-shapes-graph

Find out how to handle the unnamed graph (or union graph).

**Comment by VladimirAlexiev** [comment]
Hi @hmottestad I think we'll need this in a current project, will check with @rdstn .

But I think you mean the previous sec section? sh:shapesGraph is just advisory and the validator has no business interpreting it

**Comment by hmottestad** [comment]
I've started implementing support for specifying named graphs when generating the validation plans. This is the first step for this feature, but don't lock us into any particular way for how we allow the user to specify which graphs should be validated by which shapes. 

`sh:shapesGraph` is one way to expose this feature to users. 

Which section was it you were thinking of?

**Comment by hmottestad** [comment]
What I'm working on is:
 1. Support for keeping shapes in any graph (named or default). 
 1. Support for passing one or more named graph when generating validation plans from the parsed shapes. 
 1. Support for `sh:shapesGraph` as a way for users to inform the ShaclSail which shapesGraph(s) should be used to validate which dataGraph(s)

As a user I can keep my shapes in `ex:dcatShapesGraph` and my data in `ex:norwayDcatData` and `ex:belgiumDcatData`, as well as some other data in `ex:notDcatData`. 

Then specify that only the Norwegian and Belgium DCAT data should be validated against the DCAT shapes:

```
ex:norwayDcatData sh:shapesGraph ex:dcatShapesGraph. 

ex:belgiumDcatData sh:shapesGraph ex:dcatShapesGraph. 
```

These two triples could potentially be kept in any graph, but I think it is sound to specify that they have to be kept in a graph that already contains shapes. 

I was also thinking it would be a good idea to add some sail config options for limiting which graphs we need to search for shapes. That would also allow users to limit which graphs can contain shapes, to stop externally loaded data from also containing shapes.

**Comment by VladimirAlexiev** [comment]
Ok, so you're working on both 3.2 and 3.3. Maybe change the title to "SHACL - Support validation of named data graph, from named shape graphs".

I'm clueless whether SHACL defines an API, but I see this:
- https://www.w3.org/TR/shacl/#dfn-validation
  Validation of a data graph against a shapes graph: Given a data graph and a shapes graph, the validation results are the union of results of the validation of the data graph against all shapes in the shapes graph.
  (and 3 more)
- https://github.com/TopQuadrant/shacl/blob/master/src/main/java/org/topbraid/shacl/validation/ValidationEngine.java
  has some of the above 3 but I can't find `validateGraph` or something similar
- https://jena.apache.org/documentation/shacl/index.html has
  `ShaclValidator.get().validate(shapes, dataGraph);`
- https://rdf4j.org/documentation/programming/shacl/#validation-results shows validation on commit(), 
   i.e. the whole transaction is validated.

Actually, with some careful thinking, this can work in our project.
