### ISSUE TITLE
QueryJoinOptimizer does not process subqueries / BIND clauses

### ISSUE THREAD

**Issue by nguyenm100** [eclipse/rdf4j#3667]
### Current Behavior

QueryJoinOptimizer can skip whole sections of the query when trying to optimize

### Expected Behavior

Optimize the entire query

### Steps To Reproduce

What I'm seeing is that the tuplexpr in the priorityJoin is never optimized

If I add  priorityJoins.visit(this); right before the line below, it seems to work.

https://github.com/eclipse/rdf4j/blob/3.7.4/core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/impl/QueryJoinOptimizer.java#L176

### Version

3.7.4

**Comment by jeenbroekstra** [comment]
Thanks for reporting this @nguyenm100 - could you provide a minimal example that demonstrates the issue?

**Comment by nguyenm100** [comment]
I will try and find something but I think it has to do with the replacement join from priorityJoin replacing the leftArgs of the parent. Basically replacing the branch that the optimization is currently on.

**Comment by jeenbroekstra** [comment]
The `priorityArgs` in `JoinOptimizer` are subselects and `BIND`/`VALUES` clauses. So I think it should be possible to construct a query with a subselect where we can see that after optimization the subselect is not properly rearranged.

**Comment by nguyenm100** [comment]
I'll confirm tomorrow but pretty sure the query resemble

select
  optional
  optional
  select
     select

there's a filter and group in the subquery iirc. hth

**Comment by hmottestad** [comment]
Is this related to https://github.com/eclipse/rdf4j/issues/2258 ?

**Comment by nguyenm100** [comment]
Hi, to complete this loop I had to also save/restore the boundVars prior to the priorityJoins.visit() call like elsewhere in the code.
eg.
					if (priorityJoins != null) {
						Set<String> origbv = boundVars;

						try {
							boundVars = new HashSet<>(origBoundVars);
							priorityJoins.visit(this);
						}
						finally {
							boundVars = origbv;
						}

						replacement = new Join(priorityJoins, replacement);
					}

**Comment by jeenbroekstra** [comment]
> Is this related to #2258 ?

I think it might be the same issue, yes. But if I understand correctly, @nguyenm100 has been able to pinpoint the cause. 

@nguyenm100 would you be interested in providing a pull request with a test case and a fix? It looks like you've done most of the hard work already...

**Comment by nguyenm100** [comment]
sorry. been busy with work. will take a look. still new to rdf4j code and still compiling with -DskipTests :-)

**Comment by jeenbroekstra** [comment]
> sorry. been busy with work. will take a look. still new to rdf4j code and still compiling with -DskipTests :-)

No rush, we're all busy 😁
Have a look at the contributor guidelines when you can, and don't hesitate to shout out if you need a hand with anything!
