### ISSUE TITLE
BigInteger/BigDecimal missing from Values.literal() support.

### ISSUE THREAD

**Issue by pulquero** [eclipse/rdf4j#3677]
### Current Behavior

`Literal Values.literal(ValueFactory vf, Object object, boolean failOnUnknownType)` does not support BigInteger or BigDecimal.

### Expected Behavior

`Literal Values.literal(ValueFactory vf, Object object, boolean failOnUnknownType)` should support BigInteger and BigDecimal. TemporalAmount is also missing. I feel literal(...) should (at least) support all the same types that the ValueFactory.createLiteral(...) do.

### Steps To Reproduce

`Values.literal(SimpleValueFactory.getInstance(), new BigInteger(4), true)`

### Version

3.7.4

### Are you interested in contributing a solution yourself?

Perhaps?

**Comment by barthanssens** [comment]
Hmz yes, that is a bit odd indeed
