### ISSUE TITLE
Add option to have NTriples and NQuads parser process relative IRIs

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#368]
(Migrated from https://openrdf.atlassian.net/browse/SES-2367)

The N-Triples and N-Quads syntax formats officially do not support relative IRIs. However, in some cases, it is useful to be able to process an N-Triples document that contains relative IRIs, using the externally-supplied base URI to resolve them. 

This should be offered as a configurable option on the parser and definitely not be standard behavior.

**Comment by jamesrdf** [comment]
The syntax of these formats is simple enough that a preparsers wouldn't be hard to write that reformat them into a standard format. N-Triples can be parsed using the turtles parser as-is and N-Quads could be sorted and reformatted into TriG.
