### ISSUE TITLE
TupleQueryResult deadlocks within hasNext()

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#369]
(Migrated from https://openrdf.atlassian.net/browse/SES-2362)

I have used the {{while (nameResult.hasNext())}} pattern as shown in [1] for close to a decade now,
but I have twice recently run into a situation where TupleQueryResult seems to deadlock within {{hasNext()}} when running as a MemoryStore in a webapp deployed via Tomcat.

I see in SES-2323 that "the user is responsible for properly closing a QueryResult", which I believe I do as per [1], shown below.

In this particular application, the error occurs during the "wrap up phase" of a crawl of about a 1,000 linked data requests. By this point, a handful of "what to crawl" queries had already been run, and a size query was also run for each linked data request. The TupleQueryResult deadlock only appears at the same point in the "wrap up phase", regardless of how large the preceding linked data crawl phase is.

In the prior application, the TupleQueryResult deadlock appeared against a simple <s> <p> ?o query against a graph of a few hundred triples, so the deadlock seems to not depend on graph size or number of prior queries.

In the logging shown below, a "before hasNext()" is the last message.

Any suggestions on how to break through to "free from hasNext()!" ?

Many thanks,
Tim Lebo

{code}
try {  
   conn = repository.getConnection();

   TupleQuery       tupleQuery  = conn.prepareTupleQuery(QueryLanguage.SPARQL, queryString);
   TupleQueryResult result      = tupleQuery.evaluate();

   try {  
      while( result.hasNext() ) {
         logger.fine("after hasNext()");
         BindingSet bindings = result.next();
         logger.fine("after next()");
         handler.handleBindingSet(bindings);
         logger.fine("before hasNext()");
      }  
      logger.fine("free from hasNext()!");
      handler.finish(numResults);
      logger.fine("finished!");
   }catch (Exception e) {
      logger.finest("The brand new catch!");
      e.printStackTrace();
   }finally {
      logger.finest("finally Closing result");
      if( result != null ) { 
         logger.finest("Closing result");
         result.close();
      }  
   }  
{code}

[1] http://rdf4j.org/sesame/2.8/docs/programming.docbook?view#section-repository-api3

**Comment by jamesrdf** [comment]
I can't reproduce this. Please post more information on how to reproduce this to the mailing list please.
