### ISSUE TITLE
BIND seems over zealous 

### ISSUE THREAD

**Issue by peterjohnlawrence** [eclipse/rdf4j#3696]
### Current Behavior

I have a particular query in which a variable that is later used in a BIND expression, is used in two basic graph patterns. However, the query only seems to execute one of these BGPs before it applies the BIND. 
The test query is 
```
 { 
  ?bind   rdfs:label ?b1 .
  ?bind   a def:Unit  . 
  FILTER (?b1 = 'Unit2') . 
  BIND(?bind   as ?n0)
  ?n0 def:hasProductBatteryLimit ?n1 
 }
```

This incorrectly returns a value of :Unit2 for the variables ?bind and ?n0

### Expected Behavior

I would expect the query to satisfy the two BGPs 

```
  ?bind   rdfs:label ?b1 .
  ?bind   a def:Unit  . 
```

and then apply the filter.

### Steps To Reproduce

Using the two attached  *.TTL files in any repository (memory seems to exhibit the issue)

This query should return no records:

```
PREFIX def: <http://inova8.com/calc2graph/def/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT  *
 { 
  ?bind   rdfs:label ?b1 
  ?bind   a def:Unit  .
  FILTER (?b1 = 'Unit2') . 
  BIND(?bind   as ?n0)
  ?n0 def:hasProductBatteryLimit ?n1 
 }
```

However, it returns with the variable ?bind set to  :Unit2, which is incorrect . 
:Unit2 does satisfy the BGP { ?bind   a def:Unit  .} but not the  { ?bind   rdfs:label ?b1  . FILTER (?b1 = 'Unit2') . } pattern.

Rearranging the query, or including {...}, does not seem to change the behaviour.

[Calc2Graph.zip](https://github.com/eclipse/rdf4j/files/8134980/Calc2Graph.zip)

### Version

3.7.4

### Are you interested in contributing a solution yourself?

Perhaps?

**Comment by jeenbroekstra** [comment]
what does the (optimized) query plan look like when you try to `explain()` it?

**Comment by peterjohnlawrence** [comment]
Projection (resultSizeActual=0, totalTimeActual=0.647ms, selfTimeActual=0.003ms)
╠══ProjectionElemList
║     ProjectionElem "bind"
║     ProjectionElem "b1"
║     ProjectionElem "n0"
║     ProjectionElem "n1"
╚══Join (JoinIterator) (resultSizeActual=0, totalTimeActual=0.644ms, selfTimeActual=0.006ms)
   ├──Extension (resultSizeActual=0, totalTimeActual=0.638ms, selfTimeActual=0.003ms)
   │  ╠══Join (JoinIterator) (resultSizeActual=0, totalTimeActual=0.635ms, selfTimeActual=0.62ms)
   │  ║  ├──StatementPattern (costEstimate=0, resultSizeEstimate=0, resultSizeActual=0, totalTimeActual=0.015ms, selfTimeActual=0.015ms)
   │  ║  │     Var (name=bind)
   │  ║  │     Var (name=_const_f5e5585a_uri, value=http://www.w3.org/1999/02/22-rdf-syntax-ns#type, anonymous)
   │  ║  │     Var (name=_const_3433d213_uri, value=http://defaultUnit, anonymous)
   │  ║  └──Filter (costEstimate=0, resultSizeEstimate=0)
   │  ║     ╠══Compare (=)
   │  ║     ║     Var (name=b1)
   │  ║     ║     ValueConstant (value="Unit1")
   │  ║     ╚══StatementPattern (costEstimate=11, resultSizeEstimate=119)
   │  ║           Var (name=bind)
   │  ║           Var (name=_const_9285ccfc_uri, value=http://www.w3.org/2000/01/rdf-schema#label, anonymous)
   │  ║           Var (name=b1)
   │  ╚══ExtensionElem (n0)
   │        Var (name=bind)
   └──StatementPattern (costEstimate=0, resultSizeEstimate=0)
         Var (name=n0)
         Var (name=_const_eec771f2_uri, value=http://defaulthasProductBatteryLimit, anonymous)
         Var (name=n1)

**Comment by jeenbroekstra** [comment]
I'm not sure I follow - you claim this query shouldn't give back a result because:

> :Unit2 does satisfy the BGP { ?bind a def:Unit .} but not the { ?bind rdfs:label ?b1 . FILTER (?b1 = 'Unit2') . } pattern.

However, looking at your example data file, I see this:

```turtle
id:Unit2
  a def:Unit ;
...
  rdfs:label "Unit2" ;
```

If I'm missing something, can you try and compose a more minimal example that demonstrates the issue?

**Comment by peterjohnlawrence** [comment]
Indeed the first 5 'patterns' in the query
```
  ?bind   rdfs:label ?b1 .
  ?bind   a def:Unit  .
  FILTER (?b1 = 'Unit2') . 
  BIND(?bind   as ?n0)
```
 would be satisfied by `n0 -> id:Unit2`
However, the final BGP ` ?n0 def:hasProductBatteryLimit ?n1 ` cannot be satisfied by `n0 -> id:Unit2` using the example data I sent. Evenso, the query returns incorrect results with n1 bound to` id:BatteryLimit2`, and `id:Batterylimit1`

It is only a guess on my part but it seems as if the final BGP, ` ?n0 def:hasProductBatteryLimit ?n1 `  is being resolved in the query execution plan at a time when ?n0 is unbound.

**Comment by jeenbroekstra** [comment]
Ah, I see the problem now. Yes, looks like a bug. We've done some work in this area relatively recently, I wonder if this is an edge case regression.

**Comment by JervenBolleman** [comment]
I just noticed that in the pasted query plan the filter is on the literal 'Unit1' while in the pasted query the filter is on 'Unit2'.

```
Projection (resultSizeActual=0, totalTimeActual=0.647ms, selfTimeActual=0.003ms)
╠══ProjectionElemList
║     ProjectionElem "bind"
║     ProjectionElem "b1"
║     ProjectionElem "n0"
║     ProjectionElem "n1"
╚══Join (JoinIterator) (resultSizeActual=0, totalTimeActual=0.644ms, selfTimeActual=0.006ms)
   ├──Extension (resultSizeActual=0, totalTimeActual=0.638ms, selfTimeActual=0.003ms)
   │  ╠══Join (JoinIterator) (resultSizeActual=0, totalTimeActual=0.635ms, selfTimeActual=0.62ms)
   │  ║  ├──StatementPattern (costEstimate=0, resultSizeEstimate=0, resultSizeActual=0, totalTimeActual=0.015ms, selfTimeActual=0.015ms)
   │  ║  │     Var (name=bind)
   │  ║  │     Var (name=_const_f5e5585a_uri, value=http://www.w3.org/1999/02/22-rdf-syntax-ns#type, anonymous)
   │  ║  │     Var (name=_const_3433d213_uri, value=http://defaultUnit, anonymous)
   │  ║  └──Filter (costEstimate=0, resultSizeEstimate=0)
   │  ║     ╠══Compare (=)
   │  ║     ║     Var (name=b1)
   │  ║     ║     ValueConstant (value="Unit1")
********************> Shouldn't this be Unit2 ?
   │  ║     ╚══StatementPattern (costEstimate=11, resultSizeEstimate=119)
   │  ║           Var (name=bind)
   │  ║           Var (name=_const_9285ccfc_uri, value=http://www.w3.org/2000/01/rdf-schema#label, anonymous)
   │  ║           Var (name=b1)
   │  ╚══ExtensionElem (n0)
   │        Var (name=bind)
   └──StatementPattern (costEstimate=0, resultSizeEstimate=0)
         Var (name=n0)
         Var (name=_const_eec771f2_uri, value=http://defaulthasProductBatteryLimit, anonymous)
         Var (name=n1)
```

**Comment by peterjohnlawrence** [comment]
> I just noticed that in the pasted query plan the filter is on the literal 'Unit1' while in the pasted query the filter is on 'Unit2'.
> 
> ```
> Projection (resultSizeActual=0, totalTimeActual=0.647ms, selfTimeActual=0.003ms)
> ╠══ProjectionElemList
> ║     ProjectionElem "bind"
> ║     ProjectionElem "b1"
> ║     ProjectionElem "n0"
> ║     ProjectionElem "n1"
> ╚══Join (JoinIterator) (resultSizeActual=0, totalTimeActual=0.644ms, selfTimeActual=0.006ms)
>    ├──Extension (resultSizeActual=0, totalTimeActual=0.638ms, selfTimeActual=0.003ms)
>    │  ╠══Join (JoinIterator) (resultSizeActual=0, totalTimeActual=0.635ms, selfTimeActual=0.62ms)
>    │  ║  ├──StatementPattern (costEstimate=0, resultSizeEstimate=0, resultSizeActual=0, totalTimeActual=0.015ms, selfTimeActual=0.015ms)
>    │  ║  │     Var (name=bind)
>    │  ║  │     Var (name=_const_f5e5585a_uri, value=http://www.w3.org/1999/02/22-rdf-syntax-ns#type, anonymous)
>    │  ║  │     Var (name=_const_3433d213_uri, value=http://defaultUnit, anonymous)
>    │  ║  └──Filter (costEstimate=0, resultSizeEstimate=0)
>    │  ║     ╠══Compare (=)
>    │  ║     ║     Var (name=b1)
>    │  ║     ║     ValueConstant (value="Unit1")
> ********************> Shouldn't this be Unit2 ?
>    │  ║     ╚══StatementPattern (costEstimate=11, resultSizeEstimate=119)
>    │  ║           Var (name=bind)
>    │  ║           Var (name=_const_9285ccfc_uri, value=http://www.w3.org/2000/01/rdf-schema#label, anonymous)
>    │  ║           Var (name=b1)
>    │  ╚══ExtensionElem (n0)
>    │        Var (name=bind)
>    └──StatementPattern (costEstimate=0, resultSizeEstimate=0)
>          Var (name=n0)
>          Var (name=_const_eec771f2_uri, value=http://defaulthasProductBatteryLimit, anonymous)
>          Var (name=n1)
> ```

There are two use-cases, only differing by the filter value. The query plan is identical for both. The results should be different, but they are not.

**Comment by JervenBolleman** [comment]
Ah I see, in any case I have a minimal unit test.

**Comment by JervenBolleman** [comment]
Ok, a few details after a long debugging session. Filters, etc. are not the problem. The issue is that the deepest join gets evaluated in an unexpected order. We first call on the pattern `?n0 ex:hasProductBatteryLimit ?n1` which is then used to join against the extension/bind etc. This means that before we even get to the bind `?n1` is set to `"Unit1"` and `?n0` is set to the `:Unit1` before we even execute the join logic. So the BindingSet when entering the bind operator has `n0 = :Unit1` which is then overwritten by `n0 = :Unit2`. Very confusing to be honest and I am not sure where the fix is supposed to be, in parsing or evaluation?
