### ISSUE TITLE
Calling HEAD on Graph protocol is not graph specific

### ISSUE THREAD

**Issue by abrokenjester** [eclipse/rdf4j#371]
(Migrated from https://openrdf.atlassian.net/browse/SES-2153)

I want to get the Last-Modified time of a graph using something like curl -I http://localhost/sparql?graph=urn:graph.ttl but I noticed that each graph I call this for returns the same time. Perhaps it is reporting a modification time for the default store. Can it be made graph specific?

Even more confusing is that if I give a non-existent graph URI then I still get the same result. This doesn't seem right.

**Comment by jeenbroekstra** [comment]
There is currently no support at all for giving back a Last-Modified that is in any way related to the state of the graph or the repo. I'm assuming what is given back is some default value that Tomcat sets. It would be useful to add this though.
