### ISSUE TITLE
Maven artifacts aren't fully Java 8 compatible.

### ISSUE THREAD

**Issue by pulquero** [eclipse/rdf4j#3737]
### Current Behavior

Trying to use the workbench webapp on Java 8 gives:
`
java.lang.NoSuchMethodError: java.nio.ByteBuffer.rewind()Ljava/nio/ByteBuffer;
	org.eclipse.rdf4j.sail.nativerdf.datastore.HashFile.<init>(HashFile.java:125)
`

### Expected Behavior

No error to occur.

### Steps To Reproduce

OpenJDK 1.8.0_322 Temurin
Use tomcat 9 to run RDF4J workbench.

### Version

3.7.5

### Anything else?

Issue seems to be due to not using the new release argument for the maven-compiler-plugin.

See https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#release and https://github.com/eclipse/jetty.project/issues/3244 for a similar issue.

**Comment by jeenbroekstra** [comment]
We should check the Jenkins config. I vaguely remember setting the JVM used for release deployment to 11 for the 4.0 milestones, we may have forgotten to switch it back Java 8 for the patch release.

**Comment by jeenbroekstra** [comment]
I'll take a closer look at adding that release argument, but for now I have created separate Jenkins jobs specifically for deploying releases using Java 8:

- https://ci.eclipse.org/rdf4j/view/release%20deployment/job/rdf4j-java8-deploy-release-ossrh/
- https://ci.eclipse.org/rdf4j/view/release%20deployment/job/rdf4j-java8-deploy-release-sdk/

**Comment by jeenbroekstra** [comment]
We went with setting the compiler flags (using profiles for different JDK versions) in the end, so those separate Jenkins jobs are no longer necessary.

**Comment by pulquero** [comment]
Will there be a 3.7.6 (re-)release of 3.7.5? 3.7.5 is un-usuable for me, and it contains a fix I need for my testing?
