### ISSUE TITLE
Explore page leaves Resource field empty in IE

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#374]
(Migrated from https://openrdf.atlassian.net/browse/SES-2143)

With Compatibility View on, YASQE doesn't work. So I turned Compatibility View off. This allowed YASQE to work, but then I see this issue. See SES-1106 for a bit of history on IE Compatibility Mode and Workbench.

**Comment by barthanssens** [comment]
Time to upgrade to a newer Yasqe version / jQuery version ?
Latest Yasqe seems to be  2.11.19, while rdf4j source contains 2.7.2
