### ISSUE TITLE
YASQE presentation bugs, varies by browser

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#376]
(Migrated from https://openrdf.atlassian.net/browse/SES-2140)

1) YASQE doesn't work with Chrome, but do with FF and IE

2) the Clear Button in Query doesn't clear the request and doesn't show prefixes with YASQE in both FFand IE ( still ok in chrome as Yasqe seems  not used)

3) loading a .TTL file on disk with "Data format autodetect" works  with chrome but not with FF or IE : must choose "Turtle" after the file selection. 

4)Explore in IE clear the Resource field (shown empty). Ok in FF and Chrome. 

5)sparql update show an empty field in Chrome (why not), an example of INSERT in FF(why not), but show the html source  in the textbox in IE(!) . 

my opinion:
2 is not user friendly and frustrating as YASQE is a so good improvment.
3: i spent some time to find why it says something like error char 1 col 1 ..
HTH

thanks

**Comment by barthanssens** [comment]
See also #374
