### ISSUE TITLE
Uploading RDF-star via Workbench does not work

### ISSUE THREAD

**Issue by robertbbb** [eclipse/rdf4j#3765]
### Current Behavior

Dear all,

I am not able to upload Turtle-star or Trig-star to a repository via the Add screen in the workbench. When using those formats I get the exception 

org.eclipse.rdf4j.repository.RepositoryException: value parameter should be a URI, BNode or Literal

### Expected Behavior

When uploading Turtle-star data via the Add screen the data should be uploaded. Instead, it corrupts the repository.

### Steps To Reproduce

1. I use versions RDF4J 3.7.6 on Tomcat 9.0.62, JRE 1.8.0_321
2. I try to upload the following via the Add screen, with Turtle-star format set

```
@prefix : <http://example.org/>.
<<:a :b :c>> :d :e.
```

3. I get back an Internal Server Error with message: org.eclipse.rdf4j.repository.RepositoryException: value parameter should be a URI, BNode or Literal

4.Afterwards the whole repository gets corrupted, nothing else can be loaded in it.

### Version

3.7.6

### Are you interested in contributing a solution yourself?

No

**Comment by jeenbroekstra** [comment]
I can reproduce the error. It turns out the data is actually added to the store, and it also accepts additional data being added - so the repository is not actually corrupted. However, the Workbench UI keeps showing 500 errors.

**Comment by jeenbroekstra** [comment]
Cause is a bug in the memory store: although the store itself supports RDF-star, its on-disk persistence mechanism does not.

**Comment by jeenbroekstra** [comment]
Thanks for reporting this @robertbbb. Working on a fix, will be available in the next patch release (3.7.7) when that becomes available.
