### ISSUE TITLE
Create/update namespace endpoint does not validate the prefix and the URI

### ISSUE THREAD

**Issue by nikolaykolev** [eclipse/rdf4j#3781]
### Current Behavior

I can create/update a prefix with invalid prefix and URI, there's no validation in the endpoint.

### Expected Behavior

There should be a validation of the URI at least, I'm not sure about the prefix, but I guess creating a prefix with a space or < > in it should not be allowed as well.

### Steps To Reproduce

1. Execute the following:
curl 'http://localhost:7222/repositories/x/namespaces/asd%20c' -X 'PUT' --data-raw 'http://xxx.com'
2. The namespace is created successfully although the prefix has a space in it (asd c)

1. Execute the following
curl 'http://localhost:7222/repositories/x/namespaces/asd' -X 'PUT' --data-raw 'httpxxxcom'
2. The namespace is created with URI httpxxxcom

### Version

4.0.0-M2

**Comment by damyan-ognyanov** [comment]
There is a regression in the `NamespaceController` introduced with the previous fix. The controller accepts invalid prefixes like `22` or `2abc` but reject some valid prefixes, like `abc-de` or `abc.de`
