### ISSUE TITLE
RDFS Reasoner Challenge

### ISSUE THREAD

**Issue by hmottestad** [eclipse/rdf4j#3789]
@justin2004 has posted an RDFS Reasoner Challenge:

https://gist.github.com/justin2004/f9d07adf4e7c2c422be3e0ba92f278d2

This is a great little challenge to see how good the SchemaCachingRDFSInferencer in RDF4J is in comparison to other graph databases. The basic challenge is to load in a large Tbox and a tiny Abox to answer a simple query that should return 80 results, all without using more than 12 GB of memory.

**Comment by hmottestad** [comment]
With the fixes in https://github.com/eclipse/rdf4j/pull/3790 the challenge runs in **3 minutes** using the MemoryStore (no persistence) with -Xmx12G.

**Comment by hmottestad** [comment]
The RDFS Reasoner Challenge take 6 minutes to complete with 24GB of memory on my laptop. With the fixes in https://github.com/eclipse/rdf4j/pull/3790 it manages to run in 3 minutes on 12GB of memory.

**Comment by kenwenzel** [comment]
@hmottestad I'm just curious: Have you also tried the test with the LMDB store?

**Comment by hmottestad** [comment]
No I haven't. I tried with the NativeStore, but it was slow. I also found out that the SchemaCachingRDFSInferencer was locked to a minimum isolation level of READ_COMMITTED, which meant that a lot of data had to be kept in memory (or spill to disk). My PR removes this restriction, which is one of the main reasons it now runs on 12 GB of memory.

**Comment by hmottestad** [comment]
@kenwenzel you can checkout my branch ( GH-3789-rdfs-challenge ) and modify this [file](core/sail/inferencer/src/test/java/org/eclipse/rdf4j/sail/inferencer/fc/RDFSChallenge.java) to use the LMDB store. 

Here are the two referenced turtle files: [challenge.zip](https://github.com/eclipse/rdf4j/files/8463077/challenge.zip)

**Comment by kenwenzel** [comment]
@hmottestad Thank you - it helped me to find some issues with the autogrow logic of the LMDB store.

I have another question: Is the size of the fixed point iteration somehow deterministic? One run worked with -Xmx4G and started to insert the statements in the store (with OOM at a later point) but now I get an OOM with -Xmx8G directly after the first log message of this kind:
```
16:46:58.008 [main] DEBUG Fixed point iteration new size 18754664
```

**Comment by hmottestad** [comment]
It'll probably depend on the insertion order or retrieval order of the `rdfs:subClassOf` statements. The implementation of the algorithm uses lists and not sets, so the size of intermediate steps can be larger than the final result which is stored in sets.

**Comment by kenwenzel** [comment]
@hmottestad To Speed up the inference with NativeStore and LmdbStore it would be best if the algorithm could work with the internal value IDs. That would prevent the materialization of the concrete values and the algorithm should probably perform almost as the memory store.

Maybe we could introduce some interface for internal value IDs?

**Comment by hmottestad** [comment]
We could try for lazy loading materialization. IRIs, Bnodes and Literals that only contain their internal IDs, but can be materialized if certain methods are called. Being able to call .equals(...) and .hashCode() without materializing would be great, but I'm not sure if that's going to be all that easy because the contract for .hashCode() says that it should produce the same result for the same value even when one value is a MemIRI and another is a LmdbIRI.

**Comment by kenwenzel** [comment]
That's exactly what the LMDBStore does. But as you said, hashCode() must be stable across different implementations and therefore triggers materialization.
I thought that it might be possible to store the hash code within the ID: lower 8 bytes are the hash code and upper 8 bytes are a sequence number including some bits as a type marker (IRI, blank node, literal, ...)
To do this we need stable hash codes (across different versions of RDF4J). It would also mean that we have to store IDs with at least 8 bytes.

**Comment by kenwenzel** [comment]
Should we create a ticket: "Use persistable hash codes for values"?

The alternative would be some kind of global ID-service for values...

**Comment by hmottestad** [comment]
Would be great if you want to give it a go to see what's possible and what isn't. You can create an issue with your thoughts and experiment a bit to see how things could be designed.

**Comment by kenwenzel** [comment]
We can continue the discussion here: #3797

**Comment by jeenbroekstra** [comment]
@hmottestad are you planning to report your (intermediate) results back to the original challenge?

**Comment by hmottestad** [comment]
I was, but it wanted to add one more thing for multithreaded forward chaining.
