### ISSUE TITLE
SPARQL result sensitive on statement order

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#380]
(Migrated from https://openrdf.atlassian.net/browse/SES-2116)

Steps to reproduce:
- create in-memory/native store repository with OpenRDF Workbench
- add data from attachment (input.ttl)
- execute both queries (query-good.txt, query-bad.txt)
- the results I got are also attached and they are not the same

Each query give different result despite the fact that the only difference between them is position of:
  ?subject  loc:kodAgendy ?kodAgendy; 
    loc:platnostOd ?platnostOd;
In the good query it's at the end of WHERE section while in the bad query it's located on the beginning.

Test data:
The test data represents two entities and related tabular data. I can provide more info in case of need.

Result problem:
The "row" and "_tableName"  can be easily used to identify the problem. Based on the queries the "row" should belong to the table, but as the wrong result shows there are "row"s for different table then the one specified by "_tableName".

We originally experienced this problem with sail-nativerdf used from our java project. The workbench was only used to verify and report the issue.

**Comment by jamesrdf** [comment]
There is no guarantee of the result order if there is no order by clause

**Comment by barthanssens** [comment]
The way I read the original report (on atlassian), it's not about results being produced in a different order, but different results altogether depending on the order of variables in the SELECT statement...

**Comment by barthanssens** [comment]
Queries still yield very different results in RDF4J 2.2 (2 results with the "good" query, vs 10 with the bad), while they do produce the same results in Jena... It might be related to #79, since it seems that moving some statements before/after the BIND makes a difference

**Comment by barthanssens** [comment]
Simplified, there is a difference in the number of results between

```
SELECT ?subject ?name ?row
WHERE {
  ?subject <http://localhost/table_1> ?uri .
  ?table <http://linked.opendata.cz/ontology/odcs/tabular/hasRow> ?row .
  BIND(STR(?uri) AS ?name)
  ?table <http://linked.opendata.cz/ontology/odcs/tabular/symbolicName> ?name .
}
```

and

```
SELECT ?subject ?name ?row
WHERE {
  ?subject <http://localhost/table_1> ?uri .
  BIND(STR(?uri) AS ?name)
  ?table <http://linked.opendata.cz/ontology/odcs/tabular/hasRow> ?row .
  ?table <http://linked.opendata.cz/ontology/odcs/tabular/symbolicName> ?name .
}
```

**Comment by damyan-ognyanov** [comment]
Yes, it is the evaluation of the BIND that is problematic ... it is translated to an Extention and upon evaluatation, if the Var is bound with some value, it simply overwrites it instead of filtering out the solution. see ExtensionIterator.convert()

**Comment by barthanssens** [comment]
Well I'm not that familiar with the code base, but I'd guess the problem would rather be in the `TupleExprBuilder.visit(ASTBind node, Object data)`. line 2730

If I change this
```
GraphPattern replacementGP = new GraphPattern(graphPattern);
replacementGP.addRequiredTE(result);
graphPattern = replacementGP;
```
into
```
GraphPattern replacementGP = new GraphPattern(graphPattern);
for (TupleExpr te : graphPattern.getRequiredTEs()) {
	replacementGP.addRequiredTE(te);
}
replacementGP.addRequiredTE(result);
graphPattern = replacementGP;
```
it seems to work for this query, but I'm not sure that it won't cause side-effects for other queries...
(and also wondering if there should be a similar for-each loop for optionalTE)

**Comment by barthanssens** [comment]
Or just don't create a new GraphPattern at all, and simply do
```
graphPattern.addRequiredTE(result);
````

**Comment by jamesrdf** [comment]
Looks like this is a problem with the query join optimizer. It does not prioritize evaluating the BIND prior to the graph patterns that depend on the result.
