### ISSUE TITLE
SPARQL Service Block without a Select Clause Fails

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#382]
(Migrated from https://openrdf.atlassian.net/browse/SES-2103)

Sesame's SPARQL parser fails on at least some queries that include a SERVICE clause where the SERVICE clause does not contain an embedded SELECT clause.

A workaround exists by including an inner SELECT clause.  However, this requirement is contrary to the SPARQL 1.1 specification.

**Comment by jamesrdf** [comment]
SELECT clause is not always needed in the tests I have run
