### ISSUE TITLE
Fix branch protection to no longer required Java 8 build on main branch

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#3828]
Since the main branch now requires Java 11, there should no longer be a branch protection rule that requires a Java 8 build. ~We are currently blocked from merging into main because of this.~ EDIT turns out we're not blocked, but it still should be fixed.

I'll raise this with the Eclipse helpdesk.

Cc @hmottestad

**Comment by jeenbroekstra** [comment]
Issue raised: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1203

**Comment by hmottestad** [comment]
I did a quick fix by making a dummy action with the same name as the required one. It's what github recommends.

**Comment by jeenbroekstra** [comment]
This has been addressed on the branch protection end. I'll put up a PR to remove the dummy job.

**Comment by hmottestad** [comment]
Looks good! I merged your branch.
