### ISSUE TITLE
Support Commons RDF

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#386]
(Migrated from https://openrdf.atlassian.net/browse/SES-2091)

The Commons RDF project is aiming to provide a common set of interfaces for RDF-1.1 components, based on Java-8.

More details can be found at GitHub:

https://github.com/wikier/commons-rdf

**Comment by barthanssens** [comment]
Is this still an issue ? It seems that Apache Commons-RDF has implemented an RDF4J  binding (https://commons.apache.org/proper/commons-rdf/implementations.html), so perhaps this ticket can be closed ?

**Comment by jeenbroekstra** [comment]
Agreed.
