### ISSUE TITLE
Allow new default methods and static methods on interfaces

### ISSUE THREAD

**Issue by hmottestad** [eclipse/rdf4j#3905]
Allow new default methods and static methods on interfaces

**Comment by jeenbroekstra** [comment]
I'm not happy with the way this has been pushed through.

**Comment by jeenbroekstra** [comment]
Actually, sorry, bit of a kneejerk on my end. The change as you've done it looks reasonable I think. I'll post some followup thoughts on _why_ we configure this the way we do to the rdf4j-dev list.
