### ISSUE TITLE
Deprecate Iteration interface in favour of only using CloseableIteration

### ISSUE THREAD

**Issue by hmottestad** [eclipse/rdf4j#3907]
`CloseableIteration` extends `Iteration` and adds a close method through `AutoCloseable`. Because of how the JVM deals with interfaces there is an increased need to itable stubs when calling methods in a class that implements `CloseableIteration` from variable declared as `Iteration`.

**Comment by hmottestad** [comment]
@jeenbroekstra 

I would like to deprecate the `Iteration` interface because of the performance improvements I'm able to get by only using `CloseableIteration`. I don't know exactly why it makes such a big difference, but it's got something to do with how interface calls are made in Java compared to regular virtual calls. There is a slow path where the JVM creates a stub code that gets optimized later on. In my profiler this shows up as `itable stub`. I think that the reason this affects us so much is that we have a lot of short lived iterations, for instance during join operations where we create a new iteration for the right side for every element on the left side.

Here is some background info I found: 
 - https://wiki.openjdk.java.net/display/HotSpot/InterfaceCalls
 - https://shipilev.net/blog/2015/black-magic-method-dispatch/

I have a PR open here: https://github.com/eclipse/rdf4j/pull/3909

I'm not sure how to do a clean break from using the `Iteration` interface. Currently I'm leaning towards reimplementing all the classes that use `Iteration` in new packages. An example would be for the package `org.eclipse.rdf4j.common.iteration` I would create a new package `org.eclipse.rdf4j.common.iteration2` with a copy of all the classes but swapping out the use of `Iteration` with `CloseableIteration`. Would definitely come up with a better name instead of `iteration2` :P

**Comment by jeenbroekstra** [comment]
I have no objection to marking it deprecated. 

As for replacing/renaming: I have long thought that maybe we no longer really need the iteration classes - their main reason for existing was that we needed an iterator that can throw a checked exception. Since RDF4J Exceptions are now all unchecked, perhaps we really no longer need Iteration and its subtypes, and we can in fact just work with Iterator implementations. This performance issue you found might be a good excuse to revisit that idea.

**Comment by hmottestad** [comment]
We still want to have AutoCloseable, which I'm not able to find as a combination with Iterator or Iterable. I did find https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/stream/BaseStream.html which might be a good choice if it means that we can take advantage of the stream optimizations in GraalVM.

**Comment by hmottestad** [comment]
@jeenbroekstra In my branch I've only deprecated the `Iteration` interface itself. I think it's a good idea to deprecate all classes/methods/constructors that use the interface too. I don't want to start reimplementing things just yet. That means that there will be a bunch of classes/methods/constructors that are deprecated but with no recommended replacement. I want to have replacements available for our users in a 4.x release before potentially removing the deprecated code in 5.0.0.

**Comment by jeenbroekstra** [comment]
> We still want to have AutoCloseable, which I'm not able to find as a combination with Iterator or Iterable.

Couldn't we solve that with our own upper class/interface that extends both? Or does that just reintroduce the same performance issue? 

> I did find https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/stream/BaseStream.html which might be a good choice if it means that we can take advantage of the stream optimizations in GraalVM.

From an API point of view getting rid of Iteration and its subtypes should not be too hard - the good thing is that the `RepositoryConnection` interface abstracts away and has generic `RepositoryResult` / `QueryResult` interfaces (which we can keep fairly stable while switching out the underlying implementation quite drastically, I think). 

The hardest bit is just that Iterations are bloody everywhere in our own code base - rewriting the SPARQL engine in particular is going to be a massive job. Which I'm why somewhat in favor of sticking with something that looks a lot _like_ an Iteration/Iterator. But perhaps I'm overestimating the difficulty of switching to a stream-based approach.

**Comment by hmottestad** [comment]
`CloseabldIteration` is the way I want to go. The performance issue seems to be related to methods that use `Iteration` in their signature but receive `CloseableIteration`. Essentially just swapping out all use of `Iteration` with `CloseableIteration` made a big performance improvement.

**Comment by hmottestad** [comment]
We can keep BaseStream in the back of our minds as the next step, especially if GraalVM becomes the defacto JVM.

**Comment by hmottestad** [comment]
Realized I had misunderstood you Jeen. If we drop checked exceptions we could very well have extend the Iterator interface instead of declaring our own iterator-like interface with checked exceptions.
