### ISSUE TITLE
Ability to set fuzzy prefix on Lucene SAIL

### ISSUE THREAD

**Issue by reckart** [eclipse/rdf4j#3940]
### Problem description

The default fuzzy matching prefix in the Lucene QueryParser is / FuzzyQuery is 0. This makes fuzzy queries very slow. The query parse is created by `org.eclipse.rdf4j.sail.lucene.LuceneIndex.getQueryParser(IRI)`. The parser then has a `setFuzzyPrefixLength(int)` method that it inherits from `QueryParserBase`. 

There is currently no way of configuring the fuzzy prefix which makes fuzzy search basically unusable with larger KBs.

### Preferred solution

It would be nice if this prefix length could be set from a configuration parameter of the Lucene SAIL (via `LuceneSailConfig`) or alternatively locally via a property in the SPARQL query directly.

### Are you interested in contributing a solution yourself?

Perhaps?

### Alternatives you've considered

Possibly using a custom query parser, but there also does not seem to be a way to configure RDF4J to use a custom parser for a given Lucene SAIL.

**Comment by patrickwyler** [comment]
I added the functionality to change the prefix length of the lucene sail with a configuration parameter. Just don't know where to add a good test case.
