### ISSUE TITLE
Subquery (nested SELECT *) fails in INSERT WHERE clause

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#396]
(Migrated from https://openrdf.atlassian.net/browse/SES-2048)

A nested SELECT *, inside an INSERT WHERE clause fails, but it works if the projected variable is listed explicitly, such as SELECT ?foo.

Steps to reproduce this bug:
[[
CLEAR SILENT ALL ;

INSERT DATA { http://example/foo a http://FooClass .  } ;

INSERT { http://example/s http://example/p ?foo .  }
WHERE {
  { SELECT \* { 
    ?foo a http://FooClass  .  
  } }
}
]]

At this point, there should be two triples in the store, but there is only one.  However, it works if the "SELECT *" is changed to "SELECT ?foo".

The bug also shows up in 2.7.11.

**Comment by jamesrdf** [comment]
Works for me
