### ISSUE TITLE
JavaCC - scripts, documentation and git patches

### ISSUE THREAD

**Issue by hmottestad** [eclipse/rdf4j#3962]
We use JavaCC for generating our Java code for the SPARQL parser.

It would be nice with:
 - some documentation
 - a script for automation
 - a way to handle changes we need to make to the generated Java code

**Comment by hmottestad** [comment]
From @jeenbroekstra 

> We should do several things:
> 
>  - create a patch file with this specific fix, so that we can reapply on the generated code after rerunning javacc. I suggest separate patch files for each specific fix.
>  - add info in a readme file on the how/why of the fix. This is necessary to help fix if the patch file no longer applies without problems (e.g when we bump javacc versions).

**Comment by jeenbroekstra** [comment]
I will try and make a start on this somewhere this week.

**Comment by hmottestad** [comment]
[large-method-jvm-C2-compiler-patch.diff.zip](https://github.com/eclipse/rdf4j/files/8851612/large-method-jvm-C2-compiler-patch.diff.zip)

Here is a patch for the changes I made. Github doesn't like .diff files, so I had to zip it.
