### ISSUE TITLE
Comment before SELECT causes 500 Internal Error / XML Parsing Error

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#397]
(Migrated from https://openrdf.atlassian.net/browse/SES-2047)

In 2.7.11 the following query:
[[
# 

SELECT ?p
WHERE { ?s ?p ?v . } 
LIMIT 1
]]

causes this error (when invoke via OpenRDF Workbench):
[[
XML Parsing Error: no element found
Location: http://192.168.1.125:8080/openrdf-workbench/repositories/chcs/query?action=exec&queryLn=SPARQL&query=%23%0ASELECT%20%3Fp%0AWHERE%20%7B%20%3Fs%20%3Fp%20%3Fv%20.%20%7D%20%0ALIMIT%201%0A&limit=100&infer=false&
Line Number 1, Column 1:
^
]]

But if I delete the comment line, it works:
[[
SELECT ?p
WHERE { ?s ?p ?v . } 
LIMIT 1
]]

Or if I add a character after the hash -- any char seems to work, including a space or another hash -- then it also works:
[[
# x

SELECT ?p
WHERE { ?s ?p ?v . } 
LIMIT 1
]]
I am guessing that the XML Parsing error is masking a 500 Internal Server error, because when I tried this query in Sesame 2.6.10 it also fails, but the error is:
[[
HTTP Status 500 -

type Exception report

message

description The server encountered an internal error () that prevented it from fulfilling this request.

exception

javax.servlet.ServletException: org.openrdf.repository.http.HTTPQueryEvaluationException: Server responded with an unsupported file format: application/sparql-results+xml
    org.openrdf.workbench.base.TransformationServlet.service(TransformationServlet.java:85)
    org.openrdf.workbench.base.BaseServlet.service(BaseServlet.java:40)
    org.openrdf.workbench.proxy.ProxyRepositoryServlet.service(ProxyRepositoryServlet.java:93)
    org.openrdf.workbench.proxy.WorkbenchServlet.service(WorkbenchServlet.java:131)
    org.openrdf.workbench.proxy.WorkbenchServlet.service(WorkbenchServlet.java:90)
    org.openrdf.workbench.proxy.WorkbenchGateway.service(WorkbenchGateway.java:109)
    org.openrdf.workbench.base.BaseServlet.service(BaseServlet.java:40)
    org.openrdf.workbench.proxy.CookieCacheControlFilter.doFilter(CookieCacheControlFilter.java:52)

root cause

org.openrdf.repository.http.HTTPQueryEvaluationException: Server responded with an unsupported file format: application/sparql-results+xml
    org.openrdf.repository.http.HTTPGraphQuery.evaluate(HTTPGraphQuery.java:48)
    org.openrdf.workbench.commands.QueryServlet.evaluateGraphQuery(QueryServlet.java:231)
    org.openrdf.workbench.commands.QueryServlet.service(QueryServlet.java:152)
    org.openrdf.workbench.commands.QueryServlet.service(QueryServlet.java:99)
    org.openrdf.workbench.commands.QueryServlet.service(QueryServlet.java:72)
    org.openrdf.workbench.base.TransformationServlet.service(TransformationServlet.java:78)
    org.openrdf.workbench.base.BaseServlet.service(BaseServlet.java:40)
    org.openrdf.workbench.proxy.ProxyRepositoryServlet.service(ProxyRepositoryServlet.java:93)
    org.openrdf.workbench.proxy.WorkbenchServlet.service(WorkbenchServlet.java:131)
    org.openrdf.workbench.proxy.WorkbenchServlet.service(WorkbenchServlet.java:90)
    org.openrdf.workbench.proxy.WorkbenchGateway.service(WorkbenchGateway.java:109)
    org.openrdf.workbench.base.BaseServlet.service(BaseServlet.java:40)
    org.openrdf.workbench.proxy.CookieCacheControlFilter.doFilter(CookieCacheControlFilter.java:52)

root cause

org.openrdf.repository.RepositoryException: Server responded with an unsupported file format: application/sparql-results+xml
    org.openrdf.http.client.HTTPClient.getRDF(HTTPClient.java:1203)
    org.openrdf.http.client.HTTPClient.sendGraphQuery(HTTPClient.java:523)
    org.openrdf.http.client.HTTPClient.sendGraphQuery(HTTPClient.java:498)
    org.openrdf.repository.http.HTTPGraphQuery.evaluate(HTTPGraphQuery.java:41)
    org.openrdf.workbench.commands.QueryServlet.evaluateGraphQuery(QueryServlet.java:231)
    org.openrdf.workbench.commands.QueryServlet.service(QueryServlet.java:152)
    org.openrdf.workbench.commands.QueryServlet.service(QueryServlet.java:99)
    org.openrdf.workbench.commands.QueryServlet.service(QueryServlet.java:72)
    org.openrdf.workbench.base.TransformationServlet.service(TransformationServlet.java:78)
    org.openrdf.workbench.base.BaseServlet.service(BaseServlet.java:40)
    org.openrdf.workbench.proxy.ProxyRepositoryServlet.service(ProxyRepositoryServlet.java:93)
    org.openrdf.workbench.proxy.WorkbenchServlet.service(WorkbenchServlet.java:131)
    org.openrdf.workbench.proxy.WorkbenchServlet.service(WorkbenchServlet.java:90)
    org.openrdf.workbench.proxy.WorkbenchGateway.service(WorkbenchGateway.java:109)
    org.openrdf.workbench.base.BaseServlet.service(BaseServlet.java:40)
    org.openrdf.workbench.proxy.CookieCacheControlFilter.doFilter(CookieCacheControlFilter.java:52)

note The full stack trace of the root cause is available in the Apache Tomcat/6.0.35 logs.
Apache Tomcat/6.0.35
]]

**Comment by jamesrdf** [comment]
Doesn't seem to be an issue with the latest version
