### ISSUE TITLE
Invalid UPDATE queries are only flagged up when executing the query rather than at parse time

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#399]
(Migrated from https://openrdf.atlassian.net/browse/SES-2041)

Invalid update queries seem to parse OK - they only fail when calling the execute method on them

{code}
public class InvalidUpdateQueryTest extends TestCase {

```
private Repository m_repository;

@Override
protected void setUp() throws Exception {
    super.setUp();
    m_repository = new SailRepository(new MemoryStore());
    m_repository.initialize();
}

@Override
protected void tearDown() throws Exception {
    super.tearDown();
    m_repository.shutDown();
}

public void testInvalidUpdate() throws Exception {
    RepositoryConnection connection = m_repository.getConnection();

    try {
        Update update = connection.prepareUpdate(QueryLanguage.SPARQL, "insert data { ?s ?p ?o }");
        // should have failed already - NOT in the call below
        update.execute();
    }
    finally {
        connection.close();
    }
}
```

}
{code}

I would have expected the query to fail on prepareUpdate rather than execute

NB this appears to be a regression issue as this worked in 2.7.7

**Comment by ishaanbassi** [comment]
Hi! We (Me, [Kvatsx](https://github.com/Kvatsx), [abhishekag03](https://github.com/abhishekag03)) would like to work on this issue. 
As of now we have run the above test case and managed to successfully get RDFParseException when prepareUpdate is called. We have used the TurtleParser.java code which is called on datablocks only when executeInsertData is called during execution. We have done the same for delete data case.

It would be great if you could assign us the issue. Meanwhile, we will work on creating a pull request as soon as possible.

**Comment by barthanssens** [comment]
Great, thank you !
