### ISSUE TITLE
Add a CONTRIBUTING.md file to display the guidelines when opening issues or pull requests

### ISSUE THREAD

**Issue by ansell** [eclipse/rdf4j#4]
Eclipse recommends that contributors be shown or directed to the following text when attempting to make a contribution:

    Before your contribution can be accepted by the project, you need to create and 
    electronically sign the Eclipse Foundation Contributor License Agreement (CLA) and sign 
    off on the Eclipse Foundation Certificate of Origin. 
    
    For more information, please visit
    
    http://wiki.eclipse.org/Development_Resources/Contributing_via_Git

This can be done for GitHub issues and pull requests by adding a file to the repository named either CONTRIBUTING or CONTRIBUTING.md:

https://help.github.com/articles/setting-guidelines-for-repository-contributors/

**Comment by jeenbroekstra** [comment]
Fixed, merged.
