### ISSUE TITLE
Create script to automatically fix pom.xml merge conflicts

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#403]
(Migrated from https://openrdf.atlassian.net/browse/SES-2010)

While we are maintaining more than 2 concurrent maintenance branches in Git, we need to easily be able to merge earlier versions into the current versions. Git handles merges fairly well in most cases where the code hasn't diverged very far, but does not handle pom.xml version changes. 

So far I have been doing it using a directory wide find-replace in JEdit, which isn't too difficult, but isn't ideal in the long term. It would be nice for this to be done in a script in future.

**Comment by jamesrdf** [comment]
The only version we currently support are in develop and master branch, which can be merged without pom.xml conflicts.
