### ISSUE TITLE
Review the Namespace.equals and hashCode contracts

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#404]
(Migrated from https://openrdf.atlassian.net/browse/SES-2009)

The current Namespace.equals and hashCode contract uses both the prefix and the URL for equality.

However, in the context of most operations, the prefix must be a unique key, and hence should be the only field used in equals and hashCode.

I think this is a minor enough change to apply to 2.8.0, but if others feel differently then we can retarget it at 4.0.0-alpha1.

**Comment by jeenbroekstra** [comment]
Copying you in @ansell since you originally raised this issue (years ago). 

I'm not sure I agree with the reasoning here. You're right that the spec says that the prefix for a namespace must be unique key, but the `Namespace` object represents not just the key, but the binding.  Consider comparing namespaces from two different repos. If you compare only on the key you could get strange results...

**Comment by ansell** [comment]
Looking back at it, it isn't an issue that seems like something that needs to be changed. There are cases where if the prefix was the only key it would be easier to locate, but the difference is marginal. Probably best to encapsulate the Namespace objects in a `Map<String, Namespace>` where the prefix is necessary as a key. Feel free to close this.
