### ISSUE TITLE
Invalid query result if query contains ORDER BY clause with a variable not used in the body

### ISSUE THREAD

**Issue by aschwarte10** [eclipse/rdf4j#4041]
### Current Behavior

We noticed some strange behavior when executing a query with an ORDER BY clause, where the ORDER BY clause contains a variable not introduced inside the WHERE block.

The outcome is that query engine seems to duplicate the first encountered result binding set.

Example:

**Data:**

```
:bob1 a foaf:Person ; rdfs:label "Bob1" .
:bob2 a foaf:Person ; rdfs:label "Bob2" .
```

**Query fetching persons**

```
SELECT * WHERE { ?person a foaf:Person }
```

=> correctly yields {:bob1, :bob2}

Adding an ORDER BY clause with a variable that does not occur inside the WHERE block leads unexpected results

```
SELECT * WHERE { ?person a foaf:Person } ORDER BY ?score
```

=> yields two bindings and duplicates either result, e.g. [:bob1, :bob1] 
=> :bob2 is no longer part of the result

### Expected Behavior

As a user I would expect that all result binding sets are returned, even if I accidentially specify an ORDER BY clause with a variable not defined in the WHERE block

### Steps To Reproduce

Unit test for reproducing this using a memory store

```
@Test
    public void testOrderMemoryStorer() throws Exception {
        
        final IRI bob1 = Values.iri("http://example.org/bob1");
        final IRI bob2 = Values.iri("http://example.org/bob2");

        Repository repo = new SailRepository(new MemoryStore());
        
        try (RepositoryConnection conn = repo.getConnection()) {
            
            Model m = new ModelBuilder()
                    .subject(bob1)
                            .add(RDF.TYPE, FOAF.PERSON)
                            .add(RDFS.LABEL, "Bob1")
                    .subject(bob2)
                            .add(RDF.TYPE, FOAF.PERSON)
                            .add(RDFS.LABEL, "Bob2")
                         .build();
            conn.add(m);
            
            // Query for checking correctness
            String query1 = "SELECT * WHERE { ?person a <" + FOAF.PERSON.stringValue() + "> }";
            try (TupleQueryResult res = conn.prepareTupleQuery(query1).evaluate()) {
                Assert.assertEquals(Set.of(bob1, bob2),
                        res.stream().map(bs -> bs.getValue("person")).collect(Collectors.toSet()));
            }

            // Note the ?score in the ORDER BY clause which is not defined
            String query2 = "SELECT * WHERE { ?person a <" + FOAF.PERSON.stringValue() + "> } ORDER BY ?score";

            // returns two bindingsets, twice :bob1
            try (TupleQueryResult res = conn.prepareTupleQuery(query2).evaluate()) {
                Assert.assertEquals(Set.of(bob1, bob2),
                        res.stream().map(bs -> bs.getValue("person")).collect(Collectors.toSet()));
            }
        }
        
    }
```

### Version

4.0.3

### Anything else?

To be considered for a patch release?

My assumption is that this is a regression in RDF4J 4.x - we haven't see this behavior in 3.x (however I did not double check)

**Comment by kenwenzel** [comment]
Maybe this is also related to #4020

**Comment by jeenbroekstra** [comment]
This looks like it might be related to some of the recent optimizations in the query engine, in particular the introduction of the ArrayBindingSet. @JervenBolleman do you think you have time to take a look at this?

**Comment by JervenBolleman** [comment]
In two and a half weeks from now.
