### ISSUE TITLE
Missing copyright headers

### ISSUE THREAD

**Issue by JervenBolleman** [eclipse/rdf4j#4043]
### Current Behavior

A few files miss the eclipse copyright headers

### Expected Behavior

All files should have a copyright header

### Version

4.0.0-develop

### Are you interested in contributing a solution yourself?

Yes

### Anything else?

We should also have github workflow to ensure we don't forget again.

**Comment by jeenbroekstra** [comment]
Nice addition @JervenBolleman , thanks! One thing we could do an extension at some point is make it also check that the _correct_ (and correctly formatted) header is present.
