### ISSUE TITLE
add rdf:Alt, rdf:Bag, rdf:Seq to org.eclipse.rdf4j.model

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#405]
(Migrated from https://openrdf.atlassian.net/browse/SES-2008)

In many cases it is very convenient to create statements with java/scala in a typesafe controlled manner and without SPARQL string evaluation. But it is not possible with current API as there are no (rdf:Alt, rdf:Bag, rdf:Seq) That means that  in many cases instead of writing several lines of scala/java code users have to write SPARQL Update/Insert quries that are not only often inconvenient and potential source of bugs (as they are not typesafe) but also have SPARQL parsing overhead (esp. in such intensive operations like generating SPIN SPARQL rules from quires in embedded storages for instance).

**Comment by guvi007** [comment]
Hi @jeenbroekstra, I would like to know if this issue is still open and if I could work on this.

**Comment by jeenbroekstra** [comment]
@guvi007 it's certainly still open and we'd welcome your input. The requirements here are a little vague though. Do you have a particular design in mind so we can discuss the approach?

If you need inspiration, one approach might be something similar to what we did for RDF collections: a couple of utility methods to convert to/from Java collections.

**Comment by reeshabhkumarranjan** [comment]
We are thinking to refer to RDFCollections.java and code a similar class for RDFContainers. We will create a base class RDFContainer, and will extend it from Bag, Sequence and Alt. We might need to copy some code from RDFCollection, if that's fine. This is because much of the basic implementation might be the same. Also, I would like to tell you that three people- me, @prince17080, @guvi007 ) will be working on this issue, and the pull request will be done by Gaurav

**Comment by jeenbroekstra** [comment]
Sounds good, although I wonder if it is necessary to have separate classes for Bag, Sequence and Alt - the only structural difference is just the type, so a single RDFContainers util that has methods for producing the three different kinds of container (represented as Model objects) might be easier. Feel free to put up an early pull request to discuss what you've got, even if it's not complete yet. 

Also: before you get started, please have a look at the [contributor guidelines](https://github.com/eclipse/rdf4j/blob/master/.github/CONTRIBUTING.md), in particular the points on how to sign the Eclipse ECA. Since you will be working with multiple authors, be aware that _every_ person who adds a commit to your change will need to sign this ECA. It should be straightforward, it's an online form, shouldn't take more than 10 minutes to sort out. Let me know if you need any help with any of it.

**Comment by reeshabhkumarranjan** [comment]
Alright, we will sign the Eclipse ECA and will follow the contributor guidelines. We will put up a pull request as soon as we get on it and write some basic code. Thanks!

**Comment by reeshabhkumarranjan** [comment]
@jeanbrekstra we apologise since it is taking some time. We are college students caught in lots of assignment and projects deadlines lately, we are trying our best to get this done ASAP.

**Comment by jeenbroekstra** [comment]
> @jeenbroekstra we apologise since it is taking some time. We are college students caught in lots of assignment and projects deadlines lately, we are trying our best to get this done ASAP.

No worries, in your own time!

**Comment by reeshabhkumarranjan** [comment]
@jeenbroekstra we have added an early pull request as you suggested to see if we are on the right track, please review it.
