### ISSUE TITLE
Typo Github Release 4.1.0

### ISSUE THREAD

**Issue by patrickwyler** [eclipse/rdf4j#4114]
### Current Behavior

There is a typo in the Github release name of version 4.1.0.

https://github.com/eclipse/rdf4j/releases/tag/4.1.0

![Screenshot 2022-08-11 at 16 35 08](https://user-images.githubusercontent.com/23375188/184158908-6fc4296d-758e-4cf2-ba88-7fafe18c3dae.png)

### Expected Behavior

4.10 => 4.1.0

### Version

4.1.0

### Are you interested in contributing a solution yourself?

No

**Comment by jeenbroekstra** [comment]
Good spot, thanks! Fixed.
