### ISSUE TITLE
DRY up query optimizer pipeline so that deprecated classes don't duplicate code

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#4129]
As part of GH-3927 the query optimizer classes have all been moved to a new package. However, the existing classes are still present and while they have been marked deprecated, no clear instructions for migration are given (there's no pointer in the javadoc to the new location), and more importantly they  are just straight code duplications. This leads to problems whenever an implementation still relies on the deprecated classes, especially when fixes or improvements are done in the new optimizers but not copied over to the deprecated classes.

To fix we should do two things:

1. DRY the code up by making the deprecated classes empty subclasses of the new classes;
2. add Javadoc with a deprecation comment pointing to the new class.

**Comment by hmottestad** [comment]
Are you able to get anywhere with this? The reason I duplicated the code was that I wanted to optimize the code by switching the superclass, which is not a backwards compatible change. 

Maybe we could add `assert false : "This code is deprecated and should not be used";` so that it trips our tests. I think the chances that anyone is using this in production with assertions enabled is very low.

**Comment by jeenbroekstra** [comment]
> Are you able to get anywhere with this? The reason I duplicated the code was that I wanted to optimize the code by switching the superclass, which is not a backwards compatible change.

Yeah, got a draft PR up (was a bit hampered with laptop upgrade shenanigans so it's not fully complete yet), but I've managed to wrangle something that is at least compatible enough for the 4.2.0 release. Needs a bit of a cleanup before it's ready, but shouldn't hold you up if you want to run a 4.1.1 release. 

> Maybe we could add `assert false : "This code is deprecated and should not be used";` so that it trips our tests. I think the chances that anyone is using this in production with assertions enabled is very low.

That's a great idea, thanks - I was first thinking of throwing UnsupportedOperationExceptions but that would have been too drastic - yours is much better.
