### ISSUE TITLE
Test LmdbStore with the ShaclSail

### ISSUE THREAD

**Issue by hmottestad** [eclipse/rdf4j#4134]
> The use of LMDB should allow the LmdbStore to scale better than the NativeStore. When testing the LmdbStore with the ShaclSail it seems that the NativeStore is often faster for smaller datasets when faced with a concurrent workload of small queries. We should try to improve the performance for these workloads by profiling the code and testing out new approaches.

The performance isn't a problem anymore, so I've updated this issue to just simply add the tests that I created.

**Comment by hmottestad** [comment]
That was in fact one issue I found. It's not so much the quality of the statistics but rather that it take a lot of time to calculate them because of the read locks and IO. Adding a cache with a very short eviction helped in my testing.

**Comment by kenwenzel** [comment]
Maybe we could also have a look on zetasketch https://github.com/google/zetasketch

**Comment by kenwenzel** [comment]
https://datasketches.apache.org/docs/Theta/ThetaSketchFramework.html
