### ISSUE TITLE
Isolation Levels on REST api not working?

### ISSUE THREAD

**Issue by nguyenm100** [eclipse/rdf4j#4146]
### Current Behavior

Has anyone been able to set isolation levels via the REST api?

Processing code appears to be here: https://github.com/eclipse/rdf4j/blob/main/tools/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/transaction/TransactionStartController.java#L89 but can't get it to accept anything.

Deprecated approach (param isolation-level) is still documented in use: https://rdf4j.org/documentation/reference/rest-api/#starting-transactions and still supported in code but code wants the isolation-level to be an IRI (https://github.com/eclipse/rdf4j/blob/main/tools/server-spring/src/main/java/org/eclipse/rdf4j/http/server/repository/transaction/TransactionStartController.java#L91).   Getting past that, the matching logic is always trying to match against "org.eclipse.rdf4j.common.transaction.IsolationLevel".  standardLevel.getName() in the code appears to be faulty.

With the new approach (transaction-setting__), how should the variable be set?

Anyone have any examples that work either old or new way?

### Expected Behavior

setting isolation levels via REST api to work.

### Steps To Reproduce

run rdf4j locally and issue a curl command like:

curl -X POST "http://localhost:19440/rdf4j-server/repositories/bql/transactions?isolation-level=SNAPSHOT"  <- this complains that SNAPSHOT is not an IRI

curl -X POST "http://localhost:19440/rdf4j-server/repositories/bql/transactions?isolation-level=http://SNAPSHOT"  <- doesn't complain but never finds a match for SNAPSHOT due to bug in standardLevel.getName()

curl -X POST "http://localhost:19440/rdf4j-server/repositories/bql/transactions?transaction-setting__  <- not sure what to set here.

### Version

4.1

**Comment by hmottestad** [comment]
Related: https://github.com/eclipse/rdf4j/discussions/3876

**Comment by nguyenm100** [comment]
thanks I can fix this however I don't know what to do on the transaction-setting__ approach. any docs or discussion I can spin up on? current implementation appears to try and use some factory classes to interpret the value but still not exactly sure what the parameters/behaviors should be.

**Comment by jeenbroekstra** [comment]
That is just very odd. I must admit I have no idea why that legacy param would expect the value to be an IRI at the server end. In any case I agree the new approach should be the documented one.

As for the new approach, what would you like to know precisely? It's a prefixing mechanism that allows passing through any transaction setting, by name and value. So if you wanted to set the isolation level to SNAPSHOT, you'd use `?transaction-setting__isolation-level=SNAPSHOT`. 

I don't think the approach is really documented anywhere (which is an oversight), but the RDF4JProtocolSession class is a good place to look at how this works from the client perspective.

**Comment by nguyenm100** [comment]
ok thx. I really had no context so wasn't sure what it was trying to do on the new path. The example you gave doesn't work bc it appears to want a fully qualified setting name. I assume that's not intended? will have another go at it tomorrow.

**Comment by hmottestad** [comment]
It is intended for the full qualified name to be used, since transaction settings are extensible through the java service loader.
