### ISSUE TITLE
Include Sesame Cookbook content in the official documentation

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#415]
(Migrated from https://openrdf.atlassian.net/browse/SES-1954)

I propose to take the valuable content at http://rivuli-development.com/further-reading/sesame-cookbook/ and incorporate it directly into appropriate places in the Sesame official documentation at http://openrdf.callimachus.net/documentation.docbook?view, with attribution back to the original blog posts of course.

**Comment by barthanssens** [comment]
Hi, 

Is this still relevant / content still available ? (rivuli website seems to be offline...)

**Comment by jamesrdf** [comment]
Most of it has already been incorporate, but some of the rdf4j.org doc still link to the rivuli site, which can still be accessed through the wayback machine:
https://web.archive.org/web/20170607020414/http://www.rivuli-development.com/further-reading/sesame-cookbook/

**Comment by jeenbroekstra** [comment]
FWIW I intend to have a look at making the website available again.

**Comment by jeenbroekstra** [comment]
There's nothing in the cookbook that isn't already added to the RDF4J documentation, with the exception of the HTTP security chapter. Unfortunately, that recipe got mangled beyond repair in my weblog backup, so it will probably need to be rewritten from scratch.
