### ISSUE TITLE
Support for xsd:date cast function

### ISSUE THREAD

**Issue by jetztgradnet** [eclipse/rdf4j#4158]
### Problem description

SPARQL defines a number of casting functions for various XSD datatypes as described in https://www.w3.org/TR/sparql11-query/#FunctionMapping.

When porting an application from Jena, we encountered one that is implemented there, but missing in RDF4J: `xsd:date()`. This function is not described in the SPARQL standard, hence likely left out in RDF4J, but as SPARQL allows for additional casts, it would be great to have this function also in RDF4J.

Our ported code currently throws an RDF4J exception when encountering this funciton in a (generated) query.

See https://github.com/apache/jena/blob/main/jena-arq/src/main/java/org/apache/jena/sparql/function/CastXSD.java and https://github.com/apache/jena/blob/main/jena-arq/src/main/java/org/apache/jena/sparql/function/FunctionCastXSD.java for the Jena casting functions.

### Preferred solution

Support for `xsd:date()` casting function.

**Comment by hmottestad** [comment]
If you would like to contribute a fix for this you can take inspiration from the [code that casts xsd:dateTime](https://github.com/eclipse/rdf4j/blob/b849630bfac9c84e0444390179409456da043b15/core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/function/xsd/DateTimeCast.java).

Don't forget to update the [service file](https://github.com/eclipse/rdf4j/blob/75b97f6106e6a73776d7f0f663f18a3edfb0a4ae/core/queryalgebra/evaluation/src/main/resources/META-INF/services/org.eclipse.rdf4j.query.algebra.evaluation.function.Function) with your new class.
