### ISSUE TITLE
SPARQLQueryComplianceTest Regression: sparql11-sum-04

### ISSUE THREAD

**Issue by nguyenm100** [eclipse/rdf4j#4164]
### Current Behavior

Running: https://github.com/eclipse/rdf4j/blob/main/testsuites/sparql/src/main/java/org/eclipse/rdf4j/testsuite/query/parser/sparql/manifest/SPARQLQueryComplianceTest.java

Test: sparql11-sum-04 (https://github.com/eclipse/rdf4j/tree/main/testsuites/sparql/src/main/resources/testcases-sparql-1.1/aggregates)

returning incorrect results as compared to GraphDB 9.7

A | Total
-- | --
ex:y | 8
ex:z | 10.0
ex:x | 10

### Expected Behavior

GraphDB returns:
a | total |
-- | -- 
ex:x | "10"^^xsd:integer
ex:y |  
 ex:z | "10.0"^^xsd:decimal

### Steps To Reproduce

using dataset:

 @prefix : <http://example.org/> .

:x :p 1, 2, 3, 4 .
:y :p 1, _:b2, 3, 4 .
:z :p 1.0, 2.0, 3.0, 4 .

run query:

PREFIX : <http://example.org/>
SELECT ?a (SUM(?x) AS ?total)
WHERE {
  ?a :p ?x.
}
GROUP BY ?a

### Version

4.1.2-SNAPSHOT

This may have been this way for some time.  I'm just going back through some of the regressions.

**Comment by hmottestad** [comment]
Should be fixed once this PR is merged: https://github.com/eclipse/rdf4j/pull/4132
