### ISSUE TITLE
SPARQLQueryComplianceTest Regression: sparql11-sum-03

### ISSUE THREAD

**Issue by nguyenm100** [eclipse/rdf4j#4165]
### Current Behavior

Running: https://github.com/eclipse/rdf4j/blob/main/testsuites/sparql/src/main/java/org/eclipse/rdf4j/testsuite/query/parser/sparql/manifest/SPARQLQueryComplianceTest.java

Test: sparql11-sum-03 (https://github.com/eclipse/rdf4j/tree/main/testsuites/sparql/src/main/resources/testcases-sparql-1.1/aggregates)

returning incorrect results as compared to GraphDB 9.7

Total
--
0
0

### Expected Behavior

total
--  
 
"7"^^xsd:integer

### Steps To Reproduce

using dataset:

@prefix : <http://example.org/> .

:a :p "1" .
:a :p 1 .
:b :p 3 .
:b :p 4 .

run query:

PREFIX : <http://example.org/>
SELECT (SUM(?x) AS ?total)
WHERE {
  ?a :p ?x.
}
GROUP BY ?a

### Version

4.1.2-SNAPSHOT 

Though may have been this way for some time.

**Comment by hmottestad** [comment]
Should be fixed once this PR is merged https://github.com/eclipse/rdf4j/pull/4132
