### ISSUE TITLE
Some of the resources results for SPARQLQueryComplianceTest are wrong

### ISSUE THREAD

**Issue by nguyenm100** [eclipse/rdf4j#4167]
### Current Behavior

for: https://github.com/eclipse/rdf4j/blob/main/testsuites/sparql/src/main/java/org/eclipse/rdf4j/testsuite/query/parser/sparql/manifest/SPARQLQueryComplianceTest.java, some of the results are incorrect: https://github.com/eclipse/rdf4j/tree/main/testsuites/sparql/src/main/resources/testcases-sparql-1.1

The tests runs through a bunch of data files that specifiecs data, queries, and results.  I found the following tests to specify incorrect results data and thus fails when running this testsuit:

sparql11-wildcard-cycles-04 - https://github.com/eclipse/rdf4j/blob/main/testsuites/sparql/src/main/resources/testcases-sparql-1.1/property-paths/sparql11-wildcard-cycles-04.srx

sparql11-not-in-02 - https://github.com/eclipse/rdf4j/blob/main/testsuites/sparql/src/main/resources/testcases-sparql-1.1/builtin/sparql11-not-in-02.srx

sparql11-sum-02  - https://github.com/eclipse/rdf4j/blob/main/testsuites/sparql/src/main/resources/testcases-sparql-1.1/aggregates/sparql11-sum-02.srx

### Expected Behavior

The response files to be correct

### Steps To Reproduce

Run SPARQLQueryComplianceTest against these files.

### Version

4.1.2-SNAPSHOT

**Comment by nguyenm100** [comment]
Ontop of which, should we delete: 

sparql11-sequence-04 (https://github.com/eclipse/rdf4j/blob/main/testsuites/sparql/src/main/resources/testcases-sparql-1.1/property-paths/sparql11-sequence-04.rq)
sparql11-sequence-05
sparql11-sequence-06

which tests the occurrence specifiers that didn't make it to SPARQL1.1 and thus not implemented in RDF4J

**Comment by nguyenm100** [comment]
PR https://github.com/eclipse/rdf4j/pull/4168

**Comment by jeenbroekstra** [comment]
That set of tests is no longer in use. I don't necessarily object to the quick fix but we should probably just remove that directory.
