### ISSUE TITLE
Reverting to told statements when deleting an inferred statement using the NativeStore

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#419]
(Migrated from https://openrdf.atlassian.net/browse/SES-1937)

NB. I originally posted this observation on the mailing list. It was confirmed by Dale Visse, who suggested a bug report.

To replicate: Create a NativeStore instance and add some RDF such that an Inferencer creates an inferred statement; you override the inferred statement with a told statement; then you remove the told statement. I would expect the deletion to remove the told statement but for the inferred statement to be re-inferred and replace it.

I have included a unit test which illustrates the bug. Dale ran the unit test against a MemoryStore which does not show this issue; there is an inconsistency between the two stores.

**Comment by barthanssens** [comment]
Seems to work in RDF4J 3.0.4 and 3.1.0-snapshot (and probably a few older versions), and the example uses the (since 2.5) deprecated ForwardChainingRDFSInferencer.

Also works correctly with the new SchemaCachingRDFSInferencer, so closing this issue as already fixed.
