### ISSUE TITLE
Regression: Subquery

### ISSUE THREAD

**Issue by nguyenm100** [eclipse/rdf4j#4209]
### Current Behavior

test https://github.com/eclipse/rdf4j/blob/main/testsuites/sparql/src/main/resources/testcases-sparql-1.1/subquery/sparql11-subquery-05.rq is failing

it uses data: https://github.com/eclipse/rdf4j/blob/main/testsuites/sparql/src/main/resources/testcases-sparql-1.1/subquery/data-04.ttl

and expects results: https://github.com/eclipse/rdf4j/blob/main/testsuites/sparql/src/main/resources/testcases-sparql-1.1/subquery/sparql11-subquery-05.srx

### Expected Behavior

results to match expected

### Steps To Reproduce

use dataset:

@prefix ex: <http://example.org/> .

ex:a0 ex:p0 "a0+p0" .
ex:a0 ex:p1 "a0+p1" .
ex:a1 ex:p2 "a1+p2" .

with query:

SELECT * 
WHERE { 
    {
	  SELECT ?s 
	  WHERE {?s ?p ?o}
	  LIMIT 1 
    }
    {?s ?p ?o} 
    UNION 
    {} 
}

Expected bindings:

o="a0+p0" p=http://example.org/p0 s=http://example.org/a0 
o="a0+p1" p=http://example.org/p1 s=http://example.org/a0 
s=http://example.org/a0 

Actual bindings:

s=http://example.org/a0 

### Version

4.1.3

### Anything else?

has probably been broken prior to latest.  GraphDB 9.8 returns correct results for the same test.

**Comment by hmottestad** [comment]
I've created a branch to run the old tests here: https://github.com/eclipse/rdf4j/pull/4211

This particular test is passing for me. I'm testing against the main branch which is currently at 4.2.0, but I don't think we changed anything that should affect this test.

**Comment by nguyenm100** [comment]
Hm.. What's a little odd is that:

1. I can manually run the test through the docker instance of rdf4j 4.1.2 by inserting the dataset & query specified here and it returns the correct result.
2. If I run all the tests in the SPARQLQueryComplianceTest in isolation it works (eg just that file)
3. If I run ComplexSPARQLQueryTest first then SPARQLQueryComplianceTest it fails (2 files in the test run).  ComplexSPARQLQueryTest causes some failures with the SetVar assertions so not sure if that's causing some side effects (though each test should be isolated).  Oddly if I run SPARQLQueryComplianceTest first then ComplexSPARQLQueryTest, it works.

Based on above I think it's working ok but will probably look at it some more to see what's going on. tx

**Comment by jeenbroekstra** [comment]
@nguyenm100 have you been able to check if this is an RDF4J bug or an issue at the Halyard side? Given we can't reproduce it here I'm suspecting the latter, but would be good to get that confirmed.
