### ISSUE TITLE
Align contributor guidelines on rdf4j and github

### ISSUE THREAD

**Issue by barthanssens** [eclipse/rdf4j#4237]
### Current Behavior

The steps in https://rdf4j.org/documentation/developer/workflow/#patch-requests are slightly different from the steps in https://github.com/eclipse/rdf4j/blob/main/CONTRIBUTING.md

(e.g code formatting is not mentioned)

### Expected Behavior

IMHO it would be better if those lists are the same

### Version

n/a

### Are you interested in contributing a solution yourself?

Perhaps?

**Comment by barthanssens** [comment]
In addition, the notion that `develop` is preferred when developing a new feature is somewhat hidden in a paragraph after a bulleted list mentioning `main` several times

**Comment by jeenbroekstra** [comment]
Actually might be a good idea to get rid of one of these pages, or at least just have it link to the other one, so that we don't publish the same info twice.

> In addition, the notion that `develop` is preferred when developing a new feature is somewhat hidden in a paragraph after a bulleted list mentioning `main` several times

<insert my once-a-year grumble about our duo branch workflow being way too complicated>

**Comment by jeenbroekstra** [comment]
I'll do some work on this. Currently thinking that perhaps we should move _all_ developer documentation to github directly. I don't think we necessarily want it all inside the README or the contributor guidelines, but perhaps a docs/ directory with some additional markdown docs in it.
