### ISSUE TITLE
BindingSet.getValue("variable") returns with wrong results with SPARQL with FILTER (!bound())

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#425]
(Migrated from https://openrdf.atlassian.net/browse/SES-1912)

I was writing unit tests (JUnit) for my RDF creation process for Open PHACTS, end wanted to test that all molecular structures (CHEMINF_000000 is a 'chemical entity') have labels, so I ended up with this code (Groovy):

{code}
    // all molecules have a label
    @Test
    void moleculesHaveLabels() {
        def con = myRepository.getConnection()
        String queryString = """
SELECT ?mol ?label WHERE {
  ?mol http://www.w3.org/2000/01/rdf-schema#subClassOf http://semanticscience.org/resource/CHEMINF_000000 .
  OPTIONAL { ?mol http://www.w3.org/2000/01/rdf-schema#label ?label }
  FILTER (!bound(?label))
}

"""
        TupleQuery tupleQuery = con.prepareTupleQuery(QueryLanguage.SPARQL, queryString);
        TupleQueryResult results = tupleQuery.evaluate();
        if (results.hasNext()) {
            def next = results.next()
            println "" + next
            Assert.fail("Molecule without a label: " + next.getValue("mol").stringValue())
        }
        con.close()
    }
{code}

I would expect output of a URI of the CHEMINF_000000 subclass resource, and not what I get instead:

java.lang.AssertionError: Molecule without a label: http://semanticscience.org/resource/CHEMINF_000000

When I remove the FILTER line (of course, the test is then no longer testing the right thing), then ?mol does get bound to the ?mol resource URI...

This sounds like a bug, but may be I am doing something wrong in my code?

**Comment by jamesrdf** [comment]
Not enough information to reproduce.
