### ISSUE TITLE
Not being able to evaluate query when COUNT and ORDER BY used together in a single statement.

### ISSUE THREAD

**Issue by MartinaDimova** [eclipse/rdf4j#4290]
### Current Behavior

Following query:
```
select (count(*) as ?c) where { 
	?s ?p ?o .
} 
order by (?s)
```
is not evaluated.

### Expected Behavior

A behavior of one of the functions /COUNT or ORDER BY/ is expected.

### Version

4.2.0

### Anything else?

A test class is created to check the behavior of a such a query, both tests are failing with NullPointerException in rdf4j project.

```
public class AggregateTestCountOrderBy {

	private static SailRepository rep;

	private String query = "select (count(<http://example/book7>) as ?c) where { <http://example/book7> ?p ?o . } order by ?c ";


	@BeforeAll
	public static void setUp() throws IOException {
		rep = new SailRepository(new MemoryStore());
		addData();
	}

	private static void addData() throws IOException {
		try (RepositoryConnection conn = rep.getConnection()) {
			conn.add(new StringReader(" <http://example/book1> <urn:n> \"12.5\"^^xsd:float .\n"
					+ "    <http://example/book1> <urn:n1> \"12.5\"^^xsd:float .\n"
					+ "    <http://example/book1> <urn:n1> \"12.6\"^^xsd:float .\n"
					+ "    <http://example/book2> <urn:n> \"6\"^^xsd:int .\n"
					+ "    <http://example/book3> <urn:n>  \"12.5\"^^xsd:double .\n"
					+ "    <http://example/book4> <urn:n>  31.3 .\n"
					+ "    <http://example/book5> <urn:n>  \"311.11241cawda3\" .\n"
					+ "    <http://example/book5> <urn:n1> 311 .\n"
					+ "    <http://example/book6> <urn:n>  0.090000200001 .\n"
					+ "    <http://example/book7> <urn:n>  31.3 .\n"
					+ "    <http://example/book7> <urn:n>  29.243564 .\n"
					+ "    <http://example/book8> <urn:n>  3 ."), "", RDFFormat.TURTLE);
		}
	}

	@Test
	public void testCountOrderBy_ShouldItEvaluateByOrderBy() {
		try (RepositoryConnection conn = rep.getConnection()) {
			TupleQuery tupleQuery = conn.prepareTupleQuery(query);
			try (TupleQueryResult result = tupleQuery.evaluate()) {
				assertThat(result.next().getValue("c").stringValue()).isEqualTo("http://example/book7");
				assertThat(result.next().getValue("c").stringValue()).isEqualTo("http://example/book7");
				assertThat(result.hasNext()).isFalse();
			}
		}
	}

	@Test
	public void testCountOrderBy_ShouldItEvaluateByCount() {
		try (RepositoryConnection conn = rep.getConnection()) {
			TupleQuery tupleQuery = conn.prepareTupleQuery(query);
			try (TupleQueryResult result = tupleQuery.evaluate()) {
				assertThat(result.next().getValue("c").stringValue()).isEqualTo("2");
				assertThat(result.hasNext()).isFalse();
			}
		}
	}
}
```

**Comment by jeenbroekstra** [comment]
I can reproduce and it seems to be specific to the inclusion of the order clause. If I remove the order clause the query evaluates as expected. Also odd: if I add an explicit group by clause, it suddenly works as well. For example:

```
select (count(*) as ?c) where { ?s ?p ?o . } group by ?s order by ?c
```

executes normally and produces the expected result.

However,


```
select (count(*) as ?c) where { ?s ?p ?o . }  order by ?c
```

produces a result with just empty solutions.

**Comment by jeenbroekstra** [comment]
@JervenBolleman I had a look at things but couldn't quite get to the bottom of it. I note that in the ExtensionIterator, the `buildLambdaToEvaluateTheExpressions` method explicitly ignores the case of an aggegrate operator argument for the extension (see line 56). Could it be that this problem is some edge case in that compilation setup that we haven't covered?

**Comment by JervenBolleman** [comment]
@jeenbroekstra  I don't know. This should have been a problem with 3.7.7 as well as far as I can see. As the same check was present on line 42 in the pre-precompile code :( but I am going to have a look.

**Comment by JervenBolleman** [comment]
Eclipse editor upgrade solved that blocker :)

I think the problem is not in the ExtensionIterator, but I think in the fact that we are not doing an GroupIterator which is what we should have here. 

The reason this is an edge case, is that sorting the input into an aggregate should normally be equivalent to a non-operation. e.g. min of [3,4,1,2] is 1 just like min of [1,2,3,4].

Will sleep some more on this.

**Comment by JervenBolleman** [comment]
I now suspect that the error is somewhere [around here](https://github.com/eclipse/rdf4j/blob/b155a14d0f98120077596b549f2765e75a5123f1/core/queryparser/sparql/src/main/java/org/eclipse/rdf4j/query/parser/sparql/TupleExprBuilder.java#L612)

More spelunking and thinking to do.

**Comment by jeenbroekstra** [comment]
@JervenBolleman good spot. I won't have much time until next weekend but let me know if/when you need a second pair of eyes.

**Comment by JervenBolleman** [comment]
@jeenbroekstra I need a second pair of eyes, or at least a bit of figuring out how this code works. I am happy to pair program with you at a time of your convenience.

**Comment by jeenbroekstra** [comment]
@JervenBolleman sure thing! I'll flick you a couple of date/time suggestions over the weekend. I'll also try and take another glance myself this weekend (also to re-familiarize myself with the problem :) )
