### ISSUE TITLE
concurrent updates to namespace declarations throws java.util.ConcurrentModificationException 

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#437]
(Migrated from https://openrdf.atlassian.net/browse/SES-1861)

I have a small Ruby HTTP client that interleaves namespace prefix declarations, deletions, and lists. If I run two instances in parallel, one client almost immediately sees '500 "Internal Server Error"'. The server log shows java.util.ConcurrentModificationException. Source code and log fragments are attached.

**Comment by jamesrdf** [comment]
I cannot reproduce this
