### ISSUE TITLE
Support Skolemization of blank nodes

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#438]
(Migrated from https://openrdf.atlassian.net/browse/SES-1858)

Skolemization of blank nodes is being standardised as part of RDF-1.1.

We should support this somewhere in the OpenRDF API to enable users to transparently map skolemized blank node IRIs back to blank nodes and vice versa as necessary.

http://www.w3.org/TR/rdf11-concepts/#section-skolemization

**Comment by barthanssens** [comment]
should this be a setting, e.g. RioSetting<String> BasicParserSettings.SKOLEMIZE_BASE ?

**Comment by seralf** [comment]
Hi I wonder if there were news about this implementation?

**Comment by jamesrdf** [comment]
No development has yet to be made on this AFAIK. Are you interested in helping out?

**Comment by seralf** [comment]
yes, it would be very helpful to introduce well-know uri.


2017-12-08 21:22 GMT+01:00 James Leigh <notifications@github.com>:

**Comment by jamesrdf** [comment]
@seralf can you take a look at the PR and let me know if that will work for your use case.

**Comment by seralf** [comment]
Hi @jamesrdf  sorry for slow replies, I wasn't able to look at it yet!
I'm not sure if I correctly understand the implication of this change: could it be used as a base for providing custom ways to create well-known id for blanknodes maybe?

**Comment by jamesrdf** [comment]
It provides a parser setting of the scheme+authority used to skolemize the blanks nodes that are parsed. What is your use case?
