### ISSUE TITLE
Support queries on vocabularies in model module

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#440]
(Migrated from https://openrdf.atlassian.net/browse/SES-1850)

The vocabularies in the model module contain hardcoded static URIs, which are not able to be automatically queryable.

In the simplest case it would be useful to be able to query for all of the URIs in the vocabulary. Possibly: 

```
Set<URI> allURIs = OWL.getAllURIs();
```

This should all still be possible while maintaining backwards compatibility with the current fields, as the changes would be done in new super-classes/interfaces for the most part, and singletons would be used to create the public static final URI constants.

**Comment by barthanssens** [comment]
Could perhaps be implemented using reflection, assuming that the vocabulary's classes and properties are the only public IRIs in the java class, e.g.

```
Class vocab = OWL.class;
List<IRI> lst = new ArrayList<>();
for(Field f: vocab.getFields()) {
    if (f.getType().equals(IRI.class) && Modifier.isPublic(f.getModifiers())) {
        lst.add((IRI) f.get(f));
    }
}
```

Would it be useful to turn this into a org.eclipse.rdf4j.model.util.VocabUtil or is it a nice-to-have/wont-fix ?

**Comment by jeenbroekstra** [comment]
I think it's certainly useful as a utility class. If you're thinking of picking this up, please name it `Vocabularies` - we try to stick to the 'XXXs' convention (as opposed to 'XXXUtil') for naming utility classes.

**Comment by barthanssens** [comment]
OK, that should be rather trivial to add 

It might be overkill, but for a future RDF4J release (3.0 ?) would it be worthwhile to rework  the vocabularies to make a distinction between properties and classes IRI (either add them to a list / array in the vocab class, or subclass IRI into e.g. PropertyIRI and ClassIRI) ?
