### ISSUE TITLE
Integrate SPARQL-1.1 Service Description for SPARQL endpoints

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#441]
(Migrated from https://openrdf.atlassian.net/browse/SES-1848)

http://www.w3.org/TR/sparql11-service-description/

**Comment by barthanssens** [comment]
Is this related to #418 ?

**Comment by RickMoynihan** [comment]
Yeah, I'd say they're pretty much the same ticket.

VOID appears to reference the sparql service description vocab here, with guidance about implementing it too: https://www.w3.org/TR/void/#sparql-sd

We should close one of them as a dupe and combine them.
