### ISSUE TITLE
ParsedUpdate always has sourceString = null.

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#442]
(Migrated from https://openrdf.atlassian.net/browse/SES-1847)

It is a little bit annoying because ParsedUpdate extends ParsedOperation, so I was expecting to be able to get raw query with getSourceString. But it is always null.

I've found the reason, in the SPARQLParser:
         ParsedUpdate update = new ParsedUpdate();

**Comment by barthanssens** [comment]
Seems to be fixed since Sesame 2.9 (https://github.com/ansell/openrdf-sesame/commit/c230fdcbc4ae59836975f29976847958fb4a339d#diff-6e01ef502429555a71ea90d9d4e2e7b8)
