### ISSUE TITLE
Use third-party TSV parser/writer for SPARQL TSV parser/writers

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#443]
(Migrated from https://openrdf.atlassian.net/browse/SES-1845)

There are some issues with newline handling and quote recognition in the SPARQL Results TSV parser that may be easier to fix in the long term if we use a third-party, well-tested, TSV utility library for the implementation.

The tests for these issues are currently disabled as they fail solely for the TSV parser:

https://bitbucket.org/openrdf/sesame/pull-request/140/preserve-literal-whitespace-in-sparql/diff

**Comment by ansell** [comment]
This relates to issue #311, as the jackson-dataformat-csv parser can be configured to be a TSV parser.

**Comment by jeenbroekstra** [comment]
This has been fixed previously: we use opencsv to process both csv and tsv files.
