### ISSUE TITLE
Replace tomcat7-maven-plugin with jetty-maven-plugin

### ISSUE THREAD

**Issue by erikgb** [eclipse/rdf4j#4446]
### Problem description

After struggling to verify the workbench in https://github.com/eclipse/rdf4j/pull/4375 using Docker, I tried using `tomcat7-maven-plugin`, which is configured in the server module. But I realized that this plugin had its [latest release in 2013](https://tomcat.apache.org/maven-plugin-2.2/index.html) and seems abandoned.

For this reason, I am suggesting migrating to `jetty-maven-plugin`, which is [much better documented](https://www.eclipse.org/jetty/documentation/jetty-9/index.html#maven-and-jetty) and seems to work pretty well. I actually have prepared a branch, and will submit a PR for review right after getting the issue number. 😉 

### Are you interested in contributing a solution yourself?

Yes

**Comment by barthanssens** [comment]
Excellent idea, thanks !

**Comment by erikgb** [comment]
> Excellent idea, thanks !

Thanks @barthanssens! Please review https://github.com/eclipse/rdf4j/pull/4447.
