### ISSUE TITLE
Communicate client parser configuration settings and server parse warnings/non fatal errors

### ISSUE THREAD

**Issue by abrokenjester** [eclipse/rdf4j#446]
(Migrated from https://openrdf.atlassian.net/browse/SES-1833)

To allow remote clients to configure parser strictness, we need a mechanism in place to allow the http repository to communicate parser settings to the server, and the server to send back parse warnings and non-fatal errors.

**Comment by jeenbroekstra** [comment]
We should possibly split this in two: one issue for config settings, one for communicating back server errors/warnings.

**Comment by Richard-Degenne** [comment]
Hello,

Is there any advancement on this? This is a feature I have been expecting for a long time.
