### ISSUE TITLE
Add RepositoryConnection.setWriterConfig

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#448]
(Migrated from https://openrdf.atlassian.net/browse/SES-1828)

Need to add RepositoryConnection.setWriterConfig and RepositoryConnection.getWriterConfig to enable users to specify the writer configuration to use when exporting statements.

Scheduling this tentatively for 2.8.0 as it is adding to a major public interface, but feel free to schedule it to a 2.7.x release instead.

Being able to specify the writer config enables users to change the pretty-print setting, and change other settings that are relevant to specific file formats, especially JSON-LD where users need to be able to customise how the documents are structured using WriterConfig and JSONLDSettings.

**Comment by jamesrdf** [comment]
The export functions on RepositoryConnection take an RDFHandler, which does not expose the setWriterConfig method. A method like this on RepositoryConnection would have limited use.
