### ISSUE TITLE
AbstractLiteral toString is comparing a CoreDatatype with an IRI

### ISSUE THREAD

**Issue by ate47** [eclipse/rdf4j#4482]
### Current Behavior

at the line 195 we have `datatype.equals(CoreDatatype.XSD.STRING`, but datatype is of type IRI and CoreDatatype.XSD.STRING of type CoreDatatype, making it false all the time.

https://github.com/eclipse/rdf4j/blob/78771b7161f6b5a84b237db597b53a8842935860/core/model-api/src/main/java/org/eclipse/rdf4j/model/base/AbstractLiteral.java#L195

Making the toString value of an IRI leading to that:

```turtle
"abdc"^^<http://www.w3.org/2001/XMLSchema#string>
```

### Expected Behavior

printing the literal without the XSD.STRING datatype like with all the other version of the toString
```turtle
"abdc"
```

### Steps To Reproduce

I'm using a custom ValueFactory using the Abstract one, but this one is also doing it:

```java
System.out.println(
  new AbstractValueFactory() {}
     .createLiteral(("abcd"))
);
```

### Version

4.2.3

### Are you interested in contributing a solution yourself?

Yes

**Comment by abrokenjester** [comment]
Thanks @ate47 , good find!
