### ISSUE TITLE
sh:severity not supported ?

### ISSUE THREAD

**Issue by barthanssens** [eclipse/rdf4j#4497]
### Current Behavior

~ShaclValidator~ SHACL Sail warns about  sh:severity not being supported, while code and test cases suggest otherwise 

`WARN org.eclipse.rdf4j.sail.shacl.ast.ShaclProperties - Unsupported SHACL feature detected sh:severity in statement`

### Expected Behavior

No warning on sh:severity

### Version

4.3.0-M1

### Are you interested in contributing a solution yourself?

Perhaps?

### Anything else?

Also happening in test cases

`WARN org.eclipse.rdf4j.sail.shacl.ast.ShaclProperties - Unsupported SHACL feature detected sh:severity in statement (http://datashapes.org/sh/tests/core/misc/severity-002.test#TestShape2, http://www.w3.org/ns/shacl#severity, http://www.w3.org/ns/shacl#Info) [http://rdf4j.org/schema/rdf4j#SHACLShapeGraph`

**Comment by hmottestad** [comment]
ShaclValidator hasn't been merged into develop yet. I'm still working on it here: https://github.com/eclipse/rdf4j/pull/3951

**Comment by barthanssens** [comment]
I could be wrong of course, but it looks like severity actually isn't supported (i.e. report always returns default sh:Violation, even if sh:severity is set to e.g. sh:Warning on a NodeShape)

**Comment by hmottestad** [comment]
I've implemented support for it in https://github.com/eclipse/rdf4j/pull/3951 . Could you test that branch to see if it works for you?

**Comment by barthanssens** [comment]
Great, I was working on pretty much the same thing, so I guess this ticket can be closed.

Only suggestion perhaps is to also list `SHACL.SEVERITY_PROP` in the `ShaclSail.getSupportedShaclPredicates()`

**Comment by barthanssens** [comment]
Closing since being developed in #3951
