### ISSUE TITLE
SPARQL issue: scope of FILTER

### ISSUE THREAD

**Issue by janvoskuil** [eclipse/rdf4j#4499]
It seems that in (RDF4J 4.2.2) FILTER EXISTS and FILTER NOT EXISTS interact in unexpected ways with BIND. 

Thus, the query in [1] works as expected, it returns a few solutions.
However, the query in [2] does not:

* FILTER EXISTS is ignored
* FILTER NOT EXISTS causes nothing to pass, i.e., the result set is empty, even though a small subset of cases in the dataset matches the filter pattern

Thus, in other words, taking out the FILTER NOT EXISTS filter results in too many solutions including ones that should not pass the FILTER EXISTS filter.

According to the spec, filters apply to the entire group graph pattern: scope is not restricted to the basic graph pattern. Although BIND in [2] ends the preceding basic graph pattern, the scope of the filters should not be affected (if I understand the spec correctly). 

The two variants of the query work the same when I tested this on a Jena database.
Is this a known issue? Or am I overlooking something?
(I can send the data graph if you like.)

Best regards, -Jan
 
[1]
```
SELECT *
    WHERE {
            BIND ( <https://identifier.overheid.nl/tooi/def/thes/kern/skosCollection_475dff96> AS ?root )
            BIND ( <https://identifier.overheid.nl/tooi/set/ccw_plooi/> AS ?workURI )
            ?root skos:member* ?collection .
            FILTER EXISTS { ?collection rdf:type skos:Collection }
            FILTER NOT EXISTS { ?collection tooiont:expandeert ?_expansion}
}
```
 
[2]
```
SELECT *
    WHERE {
            FILTER EXISTS { ?collection rdf:type skos:Collection }
            FILTER NOT EXISTS { ?collection tooiont:expandeert ?_expansion}
            BIND ( <https://identifier.overheid.nl/tooi/def/thes/kern/skosCollection_475dff96> AS ?root )
            BIND ( <https://identifier.overheid.nl/tooi/set/ccw_plooi/> AS ?workURI )
            ?root skos:member* ?collection .
}
```

**Comment by hmottestad** [comment]
I haven't read up on that part of the spec. When I write SPARQL queries I typically put my BIND or VALUES clauses at the beginning of the query and my FILTER clauses at the end, but that's mostly for readability.

**Comment by abrokenjester** [comment]
I haven't fully verified this, but from a cursory re-read of the scoping rules I believe you are correct that this is a bug. I've got some tests replicating the problem, will try and find some time soon to come up with a root cause and hopefully a fix :)
