### ISSUE TITLE
Cannot upload language literal to repository in workbench

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#450]
(Migrated from https://openrdf.atlassian.net/browse/SES-1823)

Issue reported by Ravish Bhagdev on mailing list:

"I just tried uploading the example webdatacommons RDF file: (http://webdatacommons.org/samples/data/ccrdf.html-rdfa.sample.nq)

Into Sesame 2.7.0 and get a message:

"'洪雄熊' was not recognised as a language literal, and could not be verified, with language zh_tw [line 3931]"

I checked that line in the file and it is as follows:

http://bearhungfactory.mysinablog.com/index.php http://creativecommons.org/ns#attributionName "\u6D2A\u96C4\u718A"@zh_tw http://bearhungfactory.mysinablog.com/index.php   .

Longer description at answers.semanticweb.com:

http://answers.semanticweb.com/questions/22526/unable-to-upload-webdatacommons-example-file-into-openrdf-sesame-270-seemingly-because-of-encoded-chinese-characters

**Comment by jamesrdf** [comment]
Underscore is not permitted in the language tag. Use a dash instead.
