### ISSUE TITLE
"Unescaped backslash" error during import

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#451]
(Migrated from https://openrdf.atlassian.net/browse/SES-1820)

The following error occurs during import:

[WARN ] 2012-11-26 17:54:51,007 [repositories/NatJSGnd251012] [Rio error] Unescaped backslash in: http://www.kurszentrum-ballenberg.ch/cms/cms.asp?page=213&p=ASP\Pg213.asp (7943291, -1)

[WARN ] 2012-12-02 19:50:58,192 [repositories/NatJSGnd251012] [Rio error] Unescaped backslash in: http://www.die-gdi.de/CMS-Homepage/openwebcms3_e.nsf/%28ynDK_contentByKey%29/MSIN-7FCH3R?Open&nav=active:Staf                    f\Research%20Staff;expand:Staff\Research%20Staff (148768440, -1)

This is not a fatal error, just a warning. But URL parameters may not contain unescaped backslashes?

Best regards,
Sorin

**Comment by jamesrdf** [comment]
Backslashes are not permitted in an IRI
