### ISSUE TITLE
MemStatementList can safely make assumptions about how it is used

### ISSUE THREAD

**Issue by hmottestad** [eclipse/rdf4j#4511]
The MemStatementList uses a lock-free approach for adding and retrieving items. When adding items the MemStatementList will expand its underlying array if it is full. Support lock-free expanding and removal of items at the same time is far from trivial, so I've used a StampedLock to make sure that the remove method runs exclusively. 

The remove method is only used from the snapshot cleanup thread, so we can assume single threaded access. Further more, when adding an item, we can assume that if the item was removed by the snapshot cleanup thread then it doesn't matter if we add the item back again or not.

When inserting an item into the array we need to consider the following scenarios:
- The place in the array was already taken
- The array was being expanded while we inserted our item
- The item was removed immediately after we inserted it

The first scenario is handled by using CAS when writing to the array. The second scenario is handled by checking if the array is the same array after we've written our item, and if not then we can check if our item is still there. 

The third scenario can safely be ignored because we can assume that the snapshot cleanup thread doesn't clean any active snapshots. Furthermore we can assume that if it did, then adding the item back would be safe since it would just be cleaned up in the next cleanup run.

**Comment by abrokenjester** [comment]
Possibly related to #4468 ?

**Comment by hmottestad** [comment]
Hopefully yes.

**Comment by hmottestad** [comment]
I should pick this back up again.
