### ISSUE TITLE
Remove automatic activation of snapshot repo when building

### ISSUE THREAD

**Issue by hmottestad** [eclipse/rdf4j#4542]
Remove automatic activation of use-sonatype-snapshots.

The original intention of allowing maven to download snapshots instead of building them was to make it easier to build just a single submodule. 

Maven has support for building a single submodule through the `-pl` and `-am` options.

Example: `mvn install -pl :rdf4j-sail-memory -am` builds just the Memory Store and any dependencies.

Using the maven command for building a submodule is preferred to using the snapshot repo because it guarantees that dependencies are up to date with your code, there is no guarantee that there is an up to date snapshot build of your dependencies, even if you've not made any changes to those modules yourself.

**Comment by abrokenjester** [comment]
I have no real objection, but you may want to pass this by on the dev list, as it may affect other committers too. 

Question: if we're getting rid of this, should we also consider getting rid of our nightly snapshot builds (at least for the develop branch)? Or at least make them less frequent? We're burning through a lot of potentially unnecessary traffic there...

**Comment by hmottestad** [comment]
I presumed that the snapshot builds were primarily for users who wanted to stay up to date on the latests developments and changes. Those who build products on top of RDF4J could have a continuous integration running to ensure that there aren't any breaking changes in the next patch or minor release. It could also be used as an alternative to a milestone releases if you just need to test some specific new features in RDF4J together with your own code, assuming that you wait 24 hours for the snapshot build to update.

**Comment by hmottestad** [comment]
While thinking about this again I came to realise that we could just make the `use-sonatype-snapshots` profile **inactive** as default instead of removing it outright. 

Today it is enabled if you use java 11 or higher, which is our minimum requirement anyways resulting in the profile always being active.

**Comment by abrokenjester** [comment]
I've ran a few tests with my IDE with this profile disabled as well, just to check that it doesn't cause issues if we remove it. It doesn't seem to cause any problem or significant slowdown. 

> I presumed that the snapshot builds were primarily for users who wanted to stay up to date on the latests developments and changes. Those who build products on top of RDF4J could have a continuous integration running to ensure that there aren't any breaking changes in the next patch or minor release. It could also be used as an alternative to a milestone releases if you just need to test some specific new features in RDF4J together with your own code, assuming that you wait 24 hours for the snapshot build to update.

I think it's a bit of both tbh: they were originally intended to speed up local builds _as well as_ to provide a daily snapshot to third parties. I'm not sure the speeding up really holds up as an argument anymore (compilation is a _lot_ quicker these days :) ). I'm also seriously doubtful many people make use of the daily snapshots. But we can tackle that issue separately. 

> While thinking about this again I came to realise that we could just make the use-sonatype-snapshots profile inactive as default instead of removing it outright.

I think that's a good compromise.
