### ISSUE TITLE
Allow deferral of inferred statement updates

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#462]
(Migrated from https://openrdf.atlassian.net/browse/SES-1777)

Currently, the way that {{InferencerConnectionWrapper}} is implemented, repository update performance can be severely degraded for large repositories or frequently updated repositories. From the user's guide:

{quote}
However, a word of warning: the Sesame inferencers add a significant performance overhead when adding and removing data to a repository, an overhead that gets progressively worse as the total size of the repository increases. For small to medium-sized datasets it peforms fine, but for larger datasets you are advised not to use it and to switch to alternatives.
{quote}

The main issue is that the inferencers attempt to fully update inferred statements any time {{InferencerConnectionWrapper.flushUpdates()}} is called, and it gets called for just about every kind of data access operation. By adding a mode whereby {{InferencerConnectionWrapper.flushUpdates()}} only calls {{flushUpdates()}} on the wrapped connection when explicitly requested, this overhead can be mostly removed.

Also, as part of this feature, state will be added to the underlying repository such that it can be queried for when the last update of inferred statements was, as well as when the most recent change that would necessitate updating inferred statements was. Displaying these pieces of information in Workbench and Console, and giving the user commands for manually invoking inferred statement updates is another goal.

**Comment by reckart** [comment]
> The main issue is that the inferencers attempt to fully update inferred statements any time {{InferencerConnectionWrapper.flushUpdates()}} is called, and it gets called for just about every kind of data access operation. By adding a mode whereby {{InferencerConnectionWrapper.flushUpdates()}} only calls {{flushUpdates()}} on the wrapped connection when explicitly requested, this overhead can be mostly removed.

Is it as easy as that? I had the impression that the inferencer requires the flush such that the inferred statements become visible to the next inference round in order to generate second- and higher-order inferred statements.

**Comment by jeenbroekstra** [comment]
This issue has become obsolete due to the fact that we have switched to the new Schema-Caching inferencer implementation, which has much better performance.
