### ISSUE TITLE
Some QueryModelNode implementations are not serializable (e.g. StatementPattern)

### ISSUE THREAD

**Issue by pulquero** [eclipse/rdf4j#4625]
### Current Behavior

```
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;

import org.eclipse.rdf4j.query.algebra.StatementPattern;
import org.junit.jupiter.api.Test;

public class QuickTest {
	@Test
	public void test() throws IOException {
		StatementPattern sp = new StatementPattern();
		sp.getBindingNames();
		new ObjectOutputStream(new ByteArrayOutputStream()).writeObject(sp);
	}
}

```

### Expected Behavior

Test passes.

### Version

4.3.1

### Are you interested in contributing a solution yourself?

None

### Anything else?

SmallStringSet is not Serializable and thus breaks the serialization of StatementPattern.

**Comment by hmottestad** [comment]
Could you explain why the StatementPattern needs to be serializable since we don't have any tests that cover this feature?

**Comment by hmottestad** [comment]
Ok. I remember that the group by operator or something spilled to disk using serialization, so I had thought that maybe you had run into an edge case in the code where a StatementPattern object would be serialized. 

Shouldn’t be too hard to fix it, but I think we need to add a serialization/de-serialization step to our tests.

**Comment by hmottestad** [comment]
Btw. I think that this issue has been present since 4.1.0. Does that sound correct to you?

**Comment by pulquero** [comment]
Yes, some 4.x version for sure, because I didnt have any issues with 3.x.

**Comment by hmottestad** [comment]
I have a PR open for this now, but there are more issues with serialization than just StatementPattern. 

https://github.com/eclipse/rdf4j/pull/4626
