### ISSUE TITLE
Untyped string literals in Explore view don't match to literals with type xsd:string and vice versa

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#465]
(Migrated from https://openrdf.atlassian.net/browse/SES-1761)

This bug bubbled up when I applied my fix for SES-1753. 

Repro Steps: Populate a new repository with the following SPARQL Update statement:

{code}
prefix :http://www.example.org/
prefix rdfs:http://www.w3.org/2000/01/rdf-schema#
prefix xsd:http://www.w3.org/2001/XMLSchema#

insert data
{
   :alice rdfs:label "Alice" .
   :alice2 rdfs:label "Alice"^^xsd:string .
}
{code}

Exploring on {{"Alice"}} only shows the triple for {{http://www.example.org/alice}}. To see the triple for {{http://www.example.org/alice2}}, you must explore on {{"Alice"^^http://www.w3.org/2001/XMLSchema#}}. 

However, the Workbench displays both literals the same in tables: {{"Alice"}}

**Comment by jamesrdf** [comment]
In 2.3-SNAPSHOT both resources come up for me when exploring "Alice"
