### ISSUE TITLE
Docker v4.3.3 fails to create native or memory repo on WSL

### ISSUE THREAD

**Issue by nguyenm100** [eclipse/rdf4j#4657]
### Current Behavior

using docker image 4.3.3 on wsl2 and seeing crash when trying to create a native or memory repo.

Type Exception Report

Message org.eclipse.rdf4j.repository.RepositoryException: could not find instance of Repository class in config

Description The server encountered an unexpected condition that prevented it from fulfilling the request.

Exception

javax.servlet.ServletException: org.eclipse.rdf4j.repository.RepositoryException: could not find instance of Repository class in config
	org.eclipse.rdf4j.workbench.commands.CreateServlet.doPost(CreateServlet.java:64)
	org.eclipse.rdf4j.workbench.base.TransformationServlet.service(TransformationServlet.java:98)
	org.eclipse.rdf4j.workbench.base.AbstractServlet.service(AbstractServlet.java:129)
	org.eclipse.rdf4j.workbench.proxy.ProxyRepositoryServlet.service(ProxyRepositoryServlet.java:100)
	org.eclipse.rdf4j.workbench.proxy.WorkbenchServlet.service(WorkbenchServlet.java:215)
	org.eclipse.rdf4j.workbench.proxy.WorkbenchServlet.handleRequest(WorkbenchServlet.java:137)
	org.eclipse.rdf4j.workbench.proxy.WorkbenchServlet.service(WorkbenchServlet.java:112)
	org.eclipse.rdf4j.workbench.proxy.WorkbenchGateway.service(WorkbenchGateway.java:119)
	org.eclipse.rdf4j.workbench.base.AbstractServlet.service(AbstractServlet.java:129)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:115)
	org.eclipse.rdf4j.workbench.proxy.CacheFilter.doFilter(CacheFilter.java:64)
	org.eclipse.rdf4j.workbench.proxy.CookieCacheControlFilter.doFilter(CookieCacheControlFilter.java:56)
Root Cause

org.eclipse.rdf4j.repository.RepositoryException: could not find instance of Repository class in config
	org.eclipse.rdf4j.workbench.commands.CreateServlet.lambda$updateRepositoryConfig$0(CreateServlet.java:118)
	java.base/java.util.Optional.orElseThrow(Unknown Source)
	org.eclipse.rdf4j.workbench.commands.CreateServlet.updateRepositoryConfig(CreateServlet.java:118)
	org.eclipse.rdf4j.workbench.commands.CreateServlet.createRepositoryConfig(CreateServlet.java:106)
	org.eclipse.rdf4j.workbench.commands.CreateServlet.doPost(CreateServlet.java:62)
	org.eclipse.rdf4j.workbench.base.TransformationServlet.service(TransformationServlet.java:98)
	org.eclipse.rdf4j.workbench.base.AbstractServlet.service(AbstractServlet.java:129)
	org.eclipse.rdf4j.workbench.proxy.ProxyRepositoryServlet.service(ProxyRepositoryServlet.java:100)
	org.eclipse.rdf4j.workbench.proxy.WorkbenchServlet.service(WorkbenchServlet.java:215)
	org.eclipse.rdf4j.workbench.proxy.WorkbenchServlet.handleRequest(WorkbenchServlet.java:137)
	org.eclipse.rdf4j.workbench.proxy.WorkbenchServlet.service(WorkbenchServlet.java:112)
	org.eclipse.rdf4j.workbench.proxy.WorkbenchGateway.service(WorkbenchGateway.java:119)
	org.eclipse.rdf4j.workbench.base.AbstractServlet.service(AbstractServlet.java:129)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:115)
	org.eclipse.rdf4j.workbench.proxy.CacheFilter.doFilter(CacheFilter.java:64)
	org.eclipse.rdf4j.workbench.proxy.CookieCacheControlFilter.doFilter(CookieCacheControlFilter.java:56)
Note The full stack trace of the root cause is available in the server logs.

### Expected Behavior

no crash.  was able to create a native-store in v 4.2.3

### Steps To Reproduce

1. pulled down 4.3.3 docker image on wsl2. 
2. able to connect to localhost:8080 and interact with workbench (rdf4j-server connects)
3. attempt to create a repo with native store (and memory store)

see crash

### Version

4.3.3

### Are you interested in contributing a solution yourself?

None

**Comment by hmottestad** [comment]
This has been fixed in 4.3.4. 

@barthanssens And chance you could build and push a new docker image?
