### ISSUE TITLE
Internal use of Java 8 new features and patterns in Sesame 4 code base

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#476]
(Migrated from https://openrdf.atlassian.net/browse/SES-1691)

Java-7 adds some new language features, including:
- try-with-resources blocks, which operate on implementations of the new java.lang.AutoCloseable interface. These can be used to avoid manual handling for the closing of resources where possible.
- improved File IO, using the new java.nio.file.Path interface as the basic object
- multi-catch exception blocks, syntactic sugar to avoid having to write multiple catch blocks for the same handling
- generics diamond syntax, syntactic sugar to avoid having to write generic types as often

http://docs.oracle.com/javase/7/docs/technotes/guides/language/enhancements.html

Java-8 adds Lambda expressions, which can be used to reduce code complexity in user code and internally

**Comment by RickMoynihan** [comment]
Is the plan to avoid using Java 8 enhancements on public API interfaces?

I ask because I use RDF4j/Sesame from Clojure, and Java 8 features make things a little a little harder (though not impossible) to access.

**Comment by ansell** [comment]
We have some backported Java-7 code (the version 1.x series) that has had the Java-8 code removed from it, but it will not be receiving any feature updates, only bug fixes. We will only be porting bug fixes to the 1.x series while it has active users. 

We don't have plans to avoid Java-8 enhancements on public API interfaces for version 2.x and above. However, so far, their use is limited to Optional and a few generic lambda classes such as Supplier and Consumer. Future versions will see those extended in cases where it is simpler to use them then to use the current APIs.

**Comment by barthanssens** [comment]
Is this still an issue ? Because 2.x uses Java 8-code with try-with-resources etc, and 1.x is Java 7, so perhaps this issue can be closed ?
