### ISSUE TITLE
UnsupportedRDFormatException in transaction mode

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#486]
(Migrated from https://openrdf.atlassian.net/browse/SES-1103)

When I turn on transaction mode (con.setAutoCommit(false);), I always get UnsupportedRDFFormatException when trying to add new files. It does not matter if I have turtle or ntriple or ... files. I add files using method add(File file, String baseURI, RDFFormat dataFormat, Resource... contexts). When not using transaction mode everything works fine.

**Comment by barthanssens** [comment]
Is this still an issue ? Loading a  turtle file into a MemoryStore seems to work just fine with `conn.add(f, "http://example.com", RDFFormat.TURTLE)` (and `setAutocommit()` is deprecated anyway)

**Comment by jamesrdf** [comment]
Transaction handling has since been rewritten
