### ISSUE TITLE
SERVICE calls not working from Workbench through proxy (using OWLIM 5.2)

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#492]
(Migrated from https://openrdf.atlassian.net/browse/SES-1093)

I'm using sesame 2.6.8 with owlim 5.2 and I'm not able to get SERVICE calls working from the workbench through our internal proxy. I traced the problem down the fact that proxy settings seem to be ignored when working in the workbench. If I hardcode the proxy settings on the HTTPClient in org.openrdf.repository.sparql.query.SPARQLQuery then it all works fine. I'm also a bit suspicious about the code used to configure the proxy in org.openrdf.http.client.HTTPClient. You are using System.getenv when it would be better to call System.getProperty. My bash shell wouldn't let me set an environment variable on a UNIX systems with a . in the name (e.g. http.proxyHost). If I set the property on the jvm using -Dhttp.proxyHost then System.getenv returns null. It seemed to work when I changed the code to use System.getProperty.

**Comment by jamesrdf** [comment]
2.3-SNAPSHOT uses system properties to configure default clients, so this is no longer an issue
