### ISSUE TITLE
Add triple count design criteria to MemoryStore and NativeStore javadoc, suggested text included

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#500]
(Migrated from https://openrdf.atlassian.net/browse/SES-1037)

I would like to suggest the following javadoc additions based on help offered by James Leigh in response to a note I posted to the sesame-general email list, see this thread for his original comments: http://sesame-general.435816.n3.nabble.com/Low-storage-rate-to-Sesame-2-6-6-in-memory-repository-with-persistence-via-http-for-4-M-triples-td4025042.html Add this paragraph to the top of sail/memory/src/main/java/org.openrdf.sail.memory.MemoryStore.java \* The memory store is designed for datasets with fewer than 100,000 triples. \* The memory store uses hash tables, and when these hash tables fill up it \* copies the values to larger hash tables. This can cause strain on the gc due \* to lots of memory being allocated and freed. Add this paragraph to the top of sail/nativerdf/src/main/java/org.openrdf.sail.nativerdf.NativeStore.java \* The native store is designed for datasets between one hundred thousand and \* one hundred million triples. On most operating systems, if there is \* sufficient physical memory, the native store will act like an in-memory \* store, because the read/write commands will be cached in memory by the OS. \* This technique allows the native store to operate quite well for hundreds of \* millions of triples. HTH

**Comment by barthanssens** [comment]
Extra javadoc already added in previous releases
