### ISSUE TITLE
Cannot set connection timeout on HTTPClient

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#509]
(Migrated from https://openrdf.atlassian.net/browse/SES-978)

It is not possible to set a connection timeout for the org.openrdf.http.client.HTTPClient, which is relevant when it attempts to connect to an unknown host, and therefore uses a timeout of 0, which ends up meaning some annoyingly large amount of time. Being able to set the parameter on the HttpConnectionManagerParams seems reasonable.

**Comment by barthanssens** [comment]
Is this still an issue ? There's no org.eclipse.rdf4j.http.client.HTTPClient due to refactoring (in Sesame 2.8 ?), and at least org.eclipse.rdf4j.http.client.query.AbstractHTTPQuery.java has a setMaxExecutionTime method

**Comment by jamesrdf** [comment]
The timeout setting can now be set on the repositorymanager or repository by providing a custom httpClient built with custom settings. This is not an issue with 2.3-SNAPSHOT
