### ISSUE TITLE
Second GROUP_CONCAT in SPARQL query gives error

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#513]
(Migrated from https://openrdf.atlassian.net/browse/SES-941)

The following query: SELECT ?a (GROUP_CONCAT(DISTINCT ?b ; SEPARATOR=",") AS ?T4s) (GROUP_CONCAT(DISTINCT ?c ; SEPARATOR=",") AS ?T5s) WHERE { {?a http://www.semanticpublishing.eu/dokuwiki#status ?b} UNION {?a http://www.semanticpublishing.eu/dokuwiki#deadline ?c}} Gives the following error: javax.servlet.ServletException: org.openrdf.repository.http.HTTPQueryEvaluationException: Node is not a child node: BNodeColumn u2.s0pred (name=-const-1, value=http://www.semanticpublishing.eu/dokuwiki#status)

**Comment by jamesrdf** [comment]
I can't reproduce this
