### ISSUE TITLE
Native sail leaks RandomAccessFiles if files are corrupted

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#523]
(Migrated from https://openrdf.atlassian.net/browse/SES-804)

DataFile, IDFile and HashFile all create a NioFile at the start of their constructors, which opens a RandomAccessFile, but then may throw IOExceptions later in their constructor, without then closing the NioFile, thus leaking the open handle.

**Comment by barthanssens** [comment]
Is this still an issue ? It seems that NioFiles are now closed in a try / catch block (since Sesame 2.6)

**Comment by jeenbroekstra** [comment]
Happy to close, as I agree this is probably dealt with (and we don't have enough details about the original issue to try and test).
