### ISSUE TITLE
support math operations on calendar datatypes

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#524]
(Migrated from https://openrdf.atlassian.net/browse/SES-803)

Currently Sesame only supports mathematical operations (-,+, etc.) on numerical literals, which is conform a minimal interpretation of the SPARQL spec. An extended interpretation would allows us to support such operations on other datatypes, such as xsd:dateTime. An alternative solution would be to not extend defaut builtin operators, but instead offer a set of custom functions for this purpose. This has the advantage of being much more explicit about being an extension. Overloading the default operators is really not very nice and is asking for confusion about interoperability.

**Comment by pulquero** [comment]
Another option is to add support to ExtendedEvaluationStrategy. I guess, ideally, you would want both, functions for strict users, and a way to map overloaded operators to those functions as part of ExtendedEvaluationStrategy. Maybe via an Operator annotation added to impls of BinaryFunction?
