### ISSUE TITLE
MemoryStore does not handle well named graphs

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#526]
(Migrated from https://openrdf.atlassian.net/browse/SES-765)

invoking RepositoryConnection.remove over a MemoryStore does not have an effect when supplying named graph (if null, all is ok) some queries (sparql) return no records when supplying named graphs, but the triples are stored with.. this behavior does not show up with the persistent store, but the problem above affects gravely our unit tests 10x in advance

**Comment by jamesrdf** [comment]
I cannot reproduce this
