### ISSUE TITLE
SailBase default connection timeout cannot be changed.

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#535]
(Migrated from https://openrdf.atlassian.net/browse/SES-673)

SailBase default connection timeout cannot be changed. The constant DEFAULT_CONNECTION_TIMEOUT is copied into a member variable (connectionTimeOut) but this variable is not used and there is no setter method. the shutDown() method should use the connectionTimeOut variable and there should be a setter method for it.

**Comment by jeenbroekstra** [comment]
Looks good. To complete though, could you add a property for this to SailConfigSchema (and make the config parser read it)? Similar to how ITERATION_CACHE_SYNC_THRESHOLD is done. Shout out if unclear what I mean.

**Comment by barthanssens** [comment]
OK, I've added a property to the schema and getter/setter to the AbstractSailImplConfig.
Should there be a getConnectionTimeOut on the SailImplConfig interface as well ?
