### ISSUE TITLE
Query objects returned by repositories should close the connections that they opened to evaluate the query

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#541]
(Migrated from https://openrdf.atlassian.net/browse/SES-595)

Objects such as SailTupleQuery open a new connection on the underlying repository to evaluate the query. This connection, however, does not appear to be closed.

**Comment by ansell** [comment]
I will work on this as part of pull request #294 as it doesn't yet seem to be fixed there but other similar patterns are fixed in it.

**Comment by ansell** [comment]
SailTupleQuery doesn't actually open any new connections. The getConnection and getSailConnection methods that may give this impression, actually return constant objects that are cleaned up in SailRepositoryConnection.close. I did make a change to SailRepositoryConnection.close to ensure that SailConnection.close is always called though.

**Comment by jeenbroekstra** [comment]
This was fixed as part of #294
