### ISSUE TITLE
Loading RDFXML where rdf:parseType="Literal" contains xml with namespace can go wrong

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#543]
(Migrated from https://openrdf.atlassian.net/browse/SES-586)

For example, loading this: 

```
<?xml version='1.0' encoding='UTF-8' ?>
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
<xmlns:test="http://test.org/testing/">
<test:AnObject rdf:about="http://test.org/testing/itsme"> 
<test:somedata rdf:parseType="Literal"> 
<test:datapart>Literal</test:datapart> 
<test:datapart>0</test:datapart> 
<test:datapart>0</test:datapart> 
</test:somedata>
</test:AnObject>
</rdf:RDF>
```

 with code like: connection.add(inputStream,...) the test:somedata value becomes: 

```
"<test:datapart xmlns:test="http://test.org/testing/">Literal</test:datapart> 
<test:datapart>0</test:datapart>
<test:datapart>0</test:datapart>"^^http://www.w3.org/1999/02/22-rdf-syntax-ns#XMLLiteral
```
the namespace info is added only to the first test:datapart tag (gives problems when saving to rdfxml without explicitly setting the namespace test)

**Comment by barthanssens** [comment]
Looks like the issue is in the `insertUsedContextPrefixes()`  method in org.eclipse.rdf4j.rio.rdfxml.SAXFilter.
Only the first element gets namespace(s)

**Comment by anmolsinghal98** [comment]
I, @29kritika and @deepali17043 would like to look into this problem, could you please guide us with it?

**Comment by anmolsinghal98** [comment]
@jeenbroekstra @barthanssens We have solved the above issue. However, there is a test case which expects the original version where the namespace prefix is added only to the first tag. Our output adds it to all the tags as expected. I am attaching a screenshot for the same. Kindly let us know if we can change the test case to incorporate the changes we have made. 

The path to the test case is as follows- testsuites/rio/src/main/resources/testcases/rdfxml/w3c-approved/rdfms-xml-literal-namespaces/test002.nt:


<img width="1035" alt="Screenshot 2020-05-24 at 7 06 43 PM" src="https://user-images.githubusercontent.com/30462646/82755652-9d01aa80-9df2-11ea-955b-f7e2329352da.png">

**Comment by anmolsinghal98** [comment]
Also we have not made any pull requests yet because of the above failing test case. Kindly let us know what can be done.

**Comment by jeenbroekstra** [comment]
@anmolsinghal98 thanks for looking into this. The test case specifies correct behavior, so you shouldn't change the test (which is not our own test in fact, but is one specified by the W3C, see https://www.w3.org/2000/10/rdf-tests/rdfcore/) . 

The problem with your solution is that you are adding the `xmlns` attribute to _every_ tag in the XML literal, but it is only necessary for the outer element (`<apply>` in case of the test) - every other element in that literal is nested inside the `<apply>` tag, so they don't need the xmlns definition added: the definition from the outer element applies (see the [XML 1.1 specification](https://www.w3.org/TR/2006/REC-xml-names11-20060816/#scoping-defaulting) for more info on namespace scoping). 

Notice that the case specified in this bug report is different: the XML literal in this case _has_ no single outer element, but has three separate outer elements, un-nested. Currently we only add the xmlns definition to the first one, but we really should apply it to _all_ outer elements.

**Comment by anmolsinghal98** [comment]
@jeenbroekstra thanks for the clarification. We have made the changes in the code to add namespaces only to the outer elements. However, we are trying to figure out how to add a test for the same. All existing tests have been specified by the W3C, as you mentioned. Please suggest how and at what location that can be done.

**Comment by barthanssens** [comment]
Hi @anmolsinghal98, @29kritika and @deepali17043, could you also add your full names in a comment to #2269, so we can thank you in the release notes ?
