### ISSUE TITLE
BTree reads sometime fail to find all data when data is added concurrently

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#547]
(Migrated from https://openrdf.atlassian.net/browse/SES-527)

An iterator that iterates over the records in a BTree sometimes stops prematurely when the BTree is expanded with a new root node as a result of a concurrent update.

**Comment by ansell** [comment]
This may be affected or fixed by my changes to this code in pull request #294 . Having a semi-reliable test case for this would be great though to verify both the regression and fix.

**Comment by jeenbroekstra** [comment]
The history of this issue is quite old and I am relatively certain that I have never encountered the problem in any more recent version of the native store (it might also have been switched by general concurrency improvements and optimistic locking in Sesame 2.8). Regardless, I am happy to close this issue.
