### ISSUE TITLE
Query result should report total result count

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#556]
(Migrated from https://openrdf.atlassian.net/browse/SES-411)

Queries should return information the total number of returned entries, and the the total result set (which might be different if LIMIT and/or OFFSET was used in the query), this is required for building Web (or other) user interfaces that support paging through large datasets (while displaying the total number). For example consider the following; open this URL, http://www.google.com/search?q=java it will say Result 1 to 10 of ~ 233 million. It should preferably be implemented in the org.openrdf.query.QueryResult interface so that all query results would have this information, and could be the two following method stubs: // Return the size of the current result set. public void size(); // Return the total size of the query result set (as if the query was executed with-out OFFSET and LIMIT even if it was used in the query). public void getTotalResultSize();

**Comment by ansell** [comment]
This may require a major version bump, as it is a significant addition to require the full result set size to be precomputed and attached to the result. 

The reference to the way Google does it is not helpful though. They have a known approximate algorithm that doesn't attempt to deduplicate and massively overestimates the number of matches even without deduplication.

However, even if we did support it exactly (nominally/optionally), we would need to allow some database backends to approximate it to preserve their performance characteristics that are much more important than knowing the size of a result set ahead of time. The lack of general ordering constraints for result iterators is probably a more prominent issue to focus on than this, and even in the case, we only need to do that for the Workbench. 

I vote we close this as will not happen in terms of API changes. If users want to build interfaces themselves with this functionality they can pre-stream entire results sets to their local disk/memory and count/iterate/randomly-access the result sets themselves. If we wanted to support this for the Workbench it may require us to stream full results sets to disk and iterate over those separate from the original Sail/Repository, but that would probably be more appropriate for a separate issue.

**Comment by pulquero** [comment]
I don't think this is a good idea either, it basically requires materialising the whole result set and goes against the streaming nature of the codebase. Some of the arguments for removing distinct from CONSTRUCT apply here.

I would also like to point out that JDBC doesn't have such a method, but that hasn't stopped db paging web apps from being built. The solution is to issue a select count(*) to get the total number. It is a problem for the back-end, not the query language or supporting API, to optimise a select count(*) followed by a select. This issue tries to solve the problem in the wrong place.
