### ISSUE TITLE
Transaction logging mechanism

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#560]
(Migrated from https://openrdf.atlassian.net/browse/SES-249)

A (optional) transaction logging mechanism will enable many interesting new features for Sesame 2. First of all, transaction logging can help ensure Durability of the store. Second, it may be leveraged to enable a more fine-tuned store event handler mechanism (for example where the contentsChanged event carries a transaction id which a listener can then fetch to get a detailed report on what exactly the transaction was, in terms of triples added/removed).

**Comment by ansell** [comment]
This may already be suppoorted by a custom Sail in SesameTools, which Jeen has already invited to join RDF4J, but I am not sure what Josh thinks about that yet. I don't think it is necessary for it to be a native feature of the Sail API though.
