### ISSUE TITLE
Allow storage and retrieval of relative URIs

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#561]
(Migrated from https://openrdf.atlassian.net/browse/SES-151)

See forum thread at http://www.openrdf.org/forum/mvnforum/viewthread?thread=296 Allowing relative URIs to be stored in Sesame would enable upload of RDF documents with relative URIs and not resolving them until extracting them from Sesame again. A requirement here is that the API allows for the optional specification of a base URI at retrieval time. If not specified, a default base URI can be used for serializing to formats that require absolute URIs, such as NTriples.

**Comment by ansell** [comment]
I vote not to continue this feature request, as it removes all of the basis for the IRI/URI class contract, effectively making it impossible to compare two different IRIs at any point for equality.

Further support for writing relative IRIs would be useful, but not pushing them into the Model/Repository/Sail APIs.

**Comment by jeenbroekstra** [comment]
Agreed.
