### ISSUE TITLE
SPIN: Constructor Slow/Nonlinear Execution Time

### ISSUE THREAD

**Issue by gwcox66** [eclipse/rdf4j#568]
I posted a question regarding a slow SPIN constructor [as a question on StackOverflow](http://stackoverflow.com/q/39212922/6501799) a couple weeks ago.  I also discussed this in a related [question about profiling RDF4J on StackOverflow](http://stackoverflow.com/q/39360178/6501799).  Basically, I have two versions of the same single SPIN constructor operating on a small data set (< 3000 statements in total and one instance of the constructor's class) that take dramatically different amounts of time to execute.  

I'm using a repository with RDFS+SPIN support.  I believe I set it up as an in-memory store, but I'm not certain.  I don't see a way in the workbench to determine a repository's type once it's set up, but I could be missing something.

This [RDF file](https://drive.google.com/file/d/0B5rex-PdunMsdkxMUm1faFdsTDA/view?usp=sharing) contains a single constructor on the `sxxicc:Pub7Proposal` class that **takes 20 seconds to execute** using the two SPARQL Update queries (below) used to instantiate an example proposal. The second SPARQL Update query invokes the constructor in question, and I time it from submission to completion via the RDF4J workbench interface.

This [second RDF file](https://drive.google.com/file/d/0B5rex-PdunMsVW81U2ZnbDlqVVU/view?usp=sharing) contains a slightly simpler single constructor on the `sxxicc:Pub7Proposal` class that **takes under 2 seconds to execute** using the two SPARQL Update queries (below) used to instantiate an example proposal.

I used Java VisualVM's Sampler to look at the execution time for the longer example, and the RDF4J org.eclipse.rdf4j.common.concurrent.locks.LockManager$1.release() and org.eclipse.rdf4j.common.concurrent.locks.LockManager.createLock() methods dominate the Self Time.  I also see two threads that activate during the rule's slow run.  Is there some sort of contention or deadlock issue between threads?

I'm operating in the default graph/context.  I load one of the two RDF files (workbench Add RDF) with "use base URI as context identifier" unchecked.  I run the following two SPARQL Update queries in sequence, timing the execution of the second one:

```
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX sxxicc: <http://www.disa.mil/dso/a2i/ontologies/PBSM/Interface/SXXIComplianceCheck#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX sp: <http://spinrdf.org/sp#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX smf: <http://topbraid.org/sparqlmotionfunctions#>
PREFIX fn: <http://www.w3.org/2005/xpath-functions#>
PREFIX spl: <http://spinrdf.org/spl#>
PREFIX spin: <http://spinrdf.org/spin#>
PREFIX arg: <http://spinrdf.org/arg#>
PREFIX SXXIComplianceCheckIndividuals: <http://www.disa.mil/dso/a2i/ontologies/PBSM/Interface/SXXIComplianceCheckIndividuals#>
PREFIX sxxicci: <http://www.disa.mil/dso/a2i/ontologies/PBSM/Interface/SXXIComplianceCheckIndividuals#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>


INSERT DATA
{
   sxxicci:testPub7Proposal_DataItem110 a sxxicc:Pub7DataItem110 ;
           sxxicc:pub7DataItemHasRawStringValue "(C) M221.5"^^xsd:string .  

   sxxicci:testPub7Proposal_DataItem500 a sxxicc:Pub7DataItem500 ;
           sxxicc:pub7DataItemHasRawStringValue "S181"^^xsd:string .

   sxxicci:testPub7Proposal_DataItem300 a sxxicc:Pub7DataItem300 ;
           sxxicc:pub7DataItemHasRawStringValue "DC"^^xsd:string .

   sxxicci:testPub7Proposal_DataItem113 a sxxicc:Pub7DataItem113 ;
           sxxicc:pub7DataItemHasRawStringValue "FX"^^xsd:string .

   sxxicci:testPub7Proposal_DataItem511 a sxxicc:Pub7DataItem511 ;
           sxxicc:pub7DataItemHasRawStringValue "SIGHT SEEING"^^xsd:string .

   sxxicci:testPub7Proposal_DataItem501 a sxxicc:Pub7DataItem501 ;
#            sxxicc:pub7DataItemHasRawStringValue "M002"^^xsd:string .
           sxxicc:pub7DataItemHasRawStringValue "M018,     160727"^^xsd:string .

   sxxicci:testPub7Proposal_DataItem503 a sxxicc:Pub7DataItem503 ;
           sxxicc:pub7DataItemHasRawStringValue "CUBESAT, TOM"^^xsd:string .

   sxxicci:testPub7Proposal_DataItem504a a sxxicc:Pub7DataItem504 ;
           sxxicc:pub7DataItemHasRawStringValue "FAS Agenda line 1"^^xsd:string ;
           sxxicc:pub7DataItemHasOrdinalNumber "1"^^xsd:integer .

   sxxicci:testPub7Proposal_DataItem504b a sxxicc:Pub7DataItem504 ;
           sxxicc:pub7DataItemHasRawStringValue "FAS Agenda line 2"^^xsd:string ;
           sxxicc:pub7DataItemHasOrdinalNumber "2"^^xsd:integer .           

   sxxicci:testPub7Proposal_DataItem504c a sxxicc:Pub7DataItem504 ;
           sxxicc:pub7DataItemHasRawStringValue "FAS Agenda line 3"^^xsd:string ;
           sxxicc:pub7DataItemHasOrdinalNumber "3"^^xsd:integer .

   sxxicci:testPub7Proposal_DataItem504d a sxxicc:Pub7DataItem504 ;
           sxxicc:pub7DataItemHasRawStringValue "FAS Agenda line 4"^^xsd:string ;
           sxxicc:pub7DataItemHasOrdinalNumber "4"^^xsd:integer .         

   sxxicci:testPub7Proposal_DataItem504e a sxxicc:Pub7DataItem504 ;
           sxxicc:pub7DataItemHasRawStringValue "FAS Agenda line 5"^^xsd:string ;
           sxxicc:pub7DataItemHasOrdinalNumber "5"^^xsd:integer .

   sxxicci:testPub7Proposal_DataItem504f a sxxicc:Pub7DataItem504 ;
           sxxicc:pub7DataItemHasRawStringValue "FAS Agenda line 6"^^xsd:string ;
           sxxicc:pub7DataItemHasOrdinalNumber "6"^^xsd:integer .

   sxxicci:testPub7Proposal_DataItem144 a sxxicc:Pub7DataItem144 ;
           sxxicc:pub7DataItemHasRawStringValue "Y"^^xsd:string .

   sxxicci:testPub7Proposal_DataItem005 a sxxicc:Pub7DataItem005 ;
           sxxicc:pub7DataItemHasRawStringValue "SF"^^xsd:string .

   sxxicci:testPub7Proposal_DataItem102 a sxxicc:Pub7DataItem102 ;
           sxxicc:pub7DataItemHasRawStringValue "S   881234"^^xsd:string .

   sxxicci:testPub7Proposal_DataItem017 a sxxicc:Pub7DataItem017 ;
           sxxicc:pub7DataItemHasRawStringValue "C"^^xsd:string .
}

```

```
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX sxxicc: <http://www.disa.mil/dso/a2i/ontologies/PBSM/Interface/SXXIComplianceCheck#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX sp: <http://spinrdf.org/sp#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX smf: <http://topbraid.org/sparqlmotionfunctions#>
PREFIX fn: <http://www.w3.org/2005/xpath-functions#>
PREFIX spl: <http://spinrdf.org/spl#>
PREFIX spin: <http://spinrdf.org/spin#>
PREFIX arg: <http://spinrdf.org/arg#>
PREFIX SXXIComplianceCheckIndividuals: <http://www.disa.mil/dso/a2i/ontologies/PBSM/Interface/SXXIComplianceCheckIndividuals#>
PREFIX sxxicci: <http://www.disa.mil/dso/a2i/ontologies/PBSM/Interface/SXXIComplianceCheckIndividuals#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

INSERT DATA
{

   sxxicci:TestPub7Proposal a sxxicc:Pub7Proposal ;
           sxxicc:pub7ProposalHasDataItem sxxicci:testPub7Proposal_DataItem005 ;
           sxxicc:pub7ProposalHasDataItem sxxicci:testPub7Proposal_DataItem017 ;
           sxxicc:pub7ProposalHasDataItem sxxicci:testPub7Proposal_DataItem102 ;
           sxxicc:pub7ProposalHasDataItem sxxicci:testPub7Proposal_DataItem110 ;
           sxxicc:pub7ProposalHasDataItem sxxicci:testPub7Proposal_DataItem113 ;
           sxxicc:pub7ProposalHasDataItem sxxicci:testPub7Proposal_DataItem144 ;
           sxxicc:pub7ProposalHasDataItem sxxicci:testPub7Proposal_DataItem300 ;
           sxxicc:pub7ProposalHasDataItem sxxicci:testPub7Proposal_DataItem500 ;
           sxxicc:pub7ProposalHasDataItem sxxicci:testPub7Proposal_DataItem501 ; 
           sxxicc:pub7ProposalHasDataItem sxxicci:testPub7Proposal_DataItem503 ;
           sxxicc:pub7ProposalHasDataItem sxxicci:testPub7Proposal_DataItem504a ;
           sxxicc:pub7ProposalHasDataItem sxxicci:testPub7Proposal_DataItem504b ;
           sxxicc:pub7ProposalHasDataItem sxxicci:testPub7Proposal_DataItem504c ;
           sxxicc:pub7ProposalHasDataItem sxxicci:testPub7Proposal_DataItem504d ;
           sxxicc:pub7ProposalHasDataItem sxxicci:testPub7Proposal_DataItem504e ;
#           sxxicc:pub7ProposalHasDataItem sxxicci:testPub7Proposal_DataItem504f ;
           sxxicc:pub7ProposalHasDataItem sxxicci:testPub7Proposal_DataItem511 .


}
```

Here's the Java VisualVM Sampler output... domination by createLock and release (which I assume are running under streamRead).
![image](https://cloud.githubusercontent.com/assets/20132242/18483118/7c32a7d6-79a8-11e6-81fa-ba86908429ff.png)

**Comment by pulquero** [comment]
See https://openrdf.atlassian.net/browse/SES-2388. SPIN tends to exacerbate performance issues in the base sail.

**Comment by gwcox66** [comment]
Thanks @pulquero   This is interesting, especially since I interacted with Jeen on one of the two questions I posted on StackOverflow (profiling, not the slow constructor question itself).

**Comment by pulquero** [comment]
Now the issue with background cleanup has been fixed in the memory store, it is probably worth checking if things have improved.

**Comment by gwcox66** [comment]
@pulquero, I'm now running RDF4J 2.0.1... is that the version I should try?  Thanks.

**Comment by pulquero** [comment]
No, you will have to checkout master, or maybe there is a snapshot in maven.

**Comment by gwcox66** [comment]
@pulquero, I'm not yet set up for that, so there will be some delay before I can try it.  I'm also loaded up with some other tasks at the moment.  I will try when I get the chance and let you know.  Thanks!

**Comment by jeenbroekstra** [comment]
@gwcox66 relevant link with instructions (when you get around to it): http://rdf4j.org/download/#Source_code_and_nightly_builds . The fix Mark mentioned is available in the current nightly build.

**Comment by pulquero** [comment]
No hurry, in your own time.
 

    On Thursday, 6 October 2016, 0:57, gwcox66 <notifications@github.com> wrote:
 

 @pulquero, I'm not yet set up for that, so there will be some delay before I can try it. I'm also loaded up with some other tasks at the moment. I will try when I get the chance and let you know. Thanks!—

**Comment by gwcox66** [comment]
@pulquero, thanks to @jeenbroekstra note, I was able to get the snapshot working.  I'm using the snapshot workbench and have directed it to the snapshot RDF4J server (http://localhost:8088/rdf4j-http-server-2.1-20161003.062009-1 in my case).  I created a new In Memory Store with RDFS+SPIN support, and I repeated the test I did in the StackOverflow posting using the new repository.  Unfortunately, **the result was the same.**  Execution of my second SPARQL update query (which triggers the problematic SPIN constructor) still takes over 20 seconds, about 28 seconds to be precise.   Java VisualVM sampler still shows createLock() and release() taking large amounts of time (15.5 and 11.7 seconds respectively).

**Comment by pulquero** [comment]
OK, thanks for trying, I guess we know it wasnt down to the cleanup then.
 

    On Thursday, 6 October 2016, 17:01, gwcox66 <notifications@github.com> wrote:
 

 @pulquero, thanks to @jeenbroekstra note, I was able to get the snapshot working. I'm using the snapshot workbench and have directed it to the snapshot RDF4J server (http://localhost:8088/rdf4j-http-server-2.1-20161003.062009-1 in my case). I created a new In Memory Store with RDFS+SPIN support, and I repeated the test I did in the StackOverflow posting using the new repository. Unfortunately, the result was the same. Execution of my second SPARQL update query (which triggers the problematic SPIN constructor) still takes over 20 seconds, about 28 seconds to be precise. Java VisualVM sampler still shows createLock() and release() taking large amounts of time (15.5 and 11.7 seconds respectively).—

**Comment by gwcox66** [comment]
This seems to have improved substantially under 2.2.1.  However, a new bug with using VALUES in spin:constructors (posted separately) prevents many of my rules from firing and asserting new facts, so the re-test is not quite fair.

**Comment by sranger** [comment]
We have a similar issue (if it's not directly related please let me know and I can make a new ticket) but when adding resources to a RepositoryConnection it creates and releases a lock every time we add which is ridiculously slow for large datasets. Is there a way to tell the connection to only lock once? We're calling connection.open() before we begin but it doesn't seem to help.
