### ISSUE TITLE
GROUP BY produces 1 (empty) result when no solutions present

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#573]
Example:

    select ?x where {?x ?p ?o} group by ?x

on an empty repository returns 1 result, with `?x` unbound, while 

    select ?x where {?x ?p ?o} 

returns 0 results.

It is not immediately clear whether this is a bug in terms of the SPARQL spec, but it is confusing.

**Comment by pulquero** [comment]
I don't believe this is a bug. I raised a similar issue way back. You can probably find your old response  ;)

**Comment by pulquero** [comment]
Here you go https://openrdf.atlassian.net/plugins/servlet/mobile#issue/SES-2117

**Comment by jeenbroekstra** [comment]
Thanks for digging that up, it's definitely relevant!

I don't think it's completely the same issue though. Note that your issue was about the output of the `GROUP_CONCAT` operator, whereas I am raising something about the output of the `GROUP BY` modifier itself - which outputs an empty result regardless of whether an aggregate operator is used or not.

**Comment by pulquero** [comment]
Good point.

**Comment by jeenbroekstra** [comment]
Going by the [formal definition of the Group function](https://www.w3.org/TR/sparql11-query/#defn_algGroup):

> Group evaluates a list of expressions against a solution sequence, producing a set of partial functions from keys to solution sequences.
> 
> Group(exprlist, Ω) = { ListEval(exprlist, μ) → { μ' | μ' in Ω, ListEval(exprlist, μ) = ListEval(exprlist, μ') } | μ in Ω }

In our case, Ω = ∅, therefore no μ in Ω, therefore the result is an empty (multi)set. So AFAICT this is indeed a bug.
