### ISSUE TITLE
Allow store-specific custom parameters to be injected via Repository/SAIL API

### ISSUE THREAD

**Issue by abrokenjester** [eclipse/rdf4j#576]
The Repository and SAIL APIs should be extended to allow for custom (store-specific) parameters to be injected.

**Comment by jeenbroekstra** [comment]
More generally, we need a generalized parameter mechanism instead of (or rather, next to) the current store-specific getters and setters (setForceSync, setIterationCacheSyncThreshold, setDatadir, etc etc).
