### ISSUE TITLE
RDF4J Elastic Search shows only INFO level logs

### ISSUE THREAD

**Issue by jgrzebyta** [eclipse/rdf4j#577]
I use the tests quite intensively and need have more detailed logs than INFO. I will replace *slf4j-simple* implementation to *log4j2* one but for tests only.

**Comment by jeenbroekstra** [comment]
Alternatively, you could stick with using SFL4J SimpleLogger, and just configure it to enable debug-level logging. See http://www.slf4j.org/api/org/slf4j/impl/SimpleLogger.html for details.
