### ISSUE TITLE
Obtain legal approval to use current RDF format tests from W3C

### ISSUE THREAD

**Issue by ansell** [eclipse/rdf4j#587]
The current W3C RDF format tests are located in Github at:

https://github.com/w3c/rdf-tests 

Eclipse legal procedures require a review before updating our testsuites here to ensure we pass the updated testsuites.

In particular, a set of testsuites were removed in the conversion to RDF4J, although not sure what the specifics of the removal were. More information at issue #216

**Comment by jeenbroekstra** [comment]
I haven't looked in detail but do you think it's an option to change our test rig to download these test suites on the fly? If we do that we do not need to include them in our repo, and therefore have no need to get permission to distribute them.

**Comment by ansell** [comment]
Great thought, I didn't realise there was a technical option available, thought it was just a legal obstacle.

It is definitely possible although there would be a few different mechanisms available. The Semargl codebase already does this with the JSON-LD (at least) testuites so it has a precedent.

**Comment by jeenbroekstra** [comment]
FWIW the option is actually built-in in our SPARQL manifest test rig. We just don't use it (currently) because it takes longer to execute the tests that way. Or at least that was the situation a decade ago. We may have some options to improve this :)
