### ISSUE TITLE
Need StatementHandler for RepositoryConnection.add() methods

### ISSUE THREAD

**Issue by sdmonroe** [eclipse/rdf4j#589]
I would like to build alerts in my application which trigger based on the semantics of incoming graphs. It would be nice if I could register a StatementHandler with the  RepositoryConnection.add() which has a StatementHandler.handle(Statement st) method. Otherwise, I will need to continuously poll the repo, or parse and iterate all incoming RDF in addition to this being done on RepositoryConnection.add().

**Comment by jeenbroekstra** [comment]
Can't you  register a `RepositoryConnectionListener` implementation instead? All you'd need to do is wrap your `Repository` object in a `NotifyingRepositoryWrapper` and register your custom listerner.

**Comment by ansell** [comment]
RepositoryConnection implementors are free to not use the add method for update queries which run through prepareUpdate and may be optimised in other ways.

If your Repository has a Sail under it (not all Repositories do), then you can attach listeners at the Sail level where all updates can be monitored consistently. One example of code to record operations at the Sail level is:

https://github.com/joshsh/sesametools/blob/develop/replay-sail/src/main/java/net/fortytwo/sesametools/replay/RecorderSailConnection.java

**Comment by sdmonroe** [comment]
Thanks so much, these both seem like promising solutions. I will try them each.

**Comment by sdmonroe** [comment]
RepositoryConnectionListener is what I was looking for, thanks again!!
