### ISSUE TITLE
Bump Spatial4J version to 0.6

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#597]
[Spatial4J](https://locationtech.github.io/spatial4j/) is a LocationTech project, which means we can use it without having to get legal approval every time we update (Eclipse and LocationTech are BFFs).

The current version we include, however, is 0.4.1, which is from _before_ Spatial4J moved to LocationTech. This means it actually requires legal approval.  

The simplest solution would be to just bump the version to 0.6. @pulquero do you have time to have a quick look at this, see if it's possible without too much trouble?

**Comment by jeenbroekstra** [comment]
Actually taking a look at this myself. A drop-in replacement seems to work (after fixing imports) - as in it compiles. Will run some tests and if it greenlines, put up a PR.

**Comment by jeenbroekstra** [comment]
@pulquero There's an issue branch `issues/#597-spatial4j` for this which attempts to bump to 0.6, but as you can see it has compilation errors because of API changes in Spatial4J. 

What's your preference? Are you able to fix the errors in time for the 2.1 release? Or should I file for legal approval of the older version instead?

**Comment by jeenbroekstra** [comment]
There appears to be some confusion over at the Eclipse side on whether we can use the pre-LocationTech spatial4j without approval or not (we originally filed for approval, but this was withdrawn at the direction of the legal team). Trying to figure out whether we actually need to do anything urgently or not. Stay tuned.

Relevant IPZilla links:

- https://dev.eclipse.org/ipzilla/show_bug.cgi?id=12058
- https://dev.eclipse.org/ipzilla/show_bug.cgi?id=10532

**Comment by pulquero** [comment]
I'll see if I can give it a go (bumping to LocationTech) today.
 

    On Wednesday, 5 October 2016, 1:45, Jeen Broekstra <notifications@github.com> wrote:
 

 There appears to be some confusion over at the Eclipse side on whether we can use the pre-LocationTech spatial4j without approval or not (we originally filed for approval, but this was withdrawn at the direction of the legal team). Trying to figure out whether we actually need to do anything urgently or not. Stay tuned.Relevant IPZilla links:   
   - https://dev.eclipse.org/ipzilla/show_bug.cgi?id=12058
   - https://dev.eclipse.org/ipzilla/show_bug.cgi?id=10532

**Comment by jeenbroekstra** [comment]
Cool, thanks. Use my issue branch as a starting point if you want.

**Comment by pulquero** [comment]
The compile errors are because we need to bump lucene to a compatible version.
 

    On Wednesday, 5 October 2016, 7:37, Jeen Broekstra <notifications@github.com> wrote:
 

 Cool, thanks. Use my issue branch as a starting point if you want. —

**Comment by pulquero** [comment]
API for lucene has changed a lot. We would need to bump both lucene and solr to their next major versions. Won't be something I can do in a hurry. So really this is about deciding when we should upgrade our lucene version, spatial4j follows from that.
 

    On Wednesday, 5 October 2016, 19:41, Mark Hale <mj_hale@yahoo.com> wrote:
 

 The compile errors are because we need to bump lucene to a compatible version.
 

    On Wednesday, 5 October 2016, 7:37, Jeen Broekstra <notifications@github.com> wrote:
 

 Cool, thanks. Use my issue branch as a starting point if you want. —

**Comment by jeenbroekstra** [comment]
Ok, thanks for that @pulquero. In that case I'll take this out of the 2.1 planning, and I'll check with Eclipse if we can just proceed with release using 0.4.1.

**Comment by jeenbroekstra** [comment]
Legal team says CQ is necessary for using 0.4.1 unfortunately, but they promised to try and process very quickly.

**Comment by jeenbroekstra** [comment]
CQ for spatial4j 0.4.1 has been approved so we're good to go with release 2.1.

**Comment by barthanssens** [comment]
Related to https://github.com/eclipse/rdf4j-storage/issues/89, so I guess this can be closed ?

**Comment by jeenbroekstra** [comment]
Yup, thanks!
