### ISSUE TITLE
rename OpenRDFException

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#6]
Possible candidates are `RDFException` or `RDF4JException`. I personally prefer the first since it's shorter. OpenRDFException should remain as a deprecated class for backward compatibility.

**Comment by ansell** [comment]
RDFException is probably simpler in the long term.

**Comment by nikolavp** [comment]
I think that RDF4JException is better because it indicates that the this is an exception from the framework.

RDFException looks like an error in the RDF format when in fact it can be thrown from other places that are not RDF related.

**Comment by ansell** [comment]
@nikolavp, they are good reasons to use RDF4JException. I am switching to preferring that.

**Comment by jeenbroekstra** [comment]
Duly noted, and I agree with the both of you. Thanks for the feedback!
