### ISSUE TITLE
Log level options for SPIN evaluation

### ISSUE THREAD

**Issue by rob-metalinkage** [eclipse/rdf4j#601]
It would be good to be able to set the log level for SPIN evaluation to be able to get more verbose feedback. (and specify which log this would appear in)

Related issue #599

**Comment by jeenbroekstra** [comment]
The main thing to do would be to add more info- and debug-level logging to the SPIN reasoner. Once we have put sufficiently verbose logging in place you could easily tweak which log file it goes to yourself, by configuring the logger for `org.eclipse.rdf4j.spin` to append to a log file of your choice.
