### ISSUE TITLE
Enable specification of output format/location in Console 

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#603]
RDF4J Console currently outputs the result of any query directly to STDOUT, in a fixed format (N-TRIPLES for graph queries, a home-baked table format for tuple queries). To make the console more generally useful as a SPARQL endpoint client, we should add options to specify the preferred output format as well as an option to redirect the query result to file.

**Comment by barthanssens** [comment]
Related to #1104

**Comment by barthanssens** [comment]
@jeenbroekstra  can this be closed (as it is implemented for sparql/serql), or do you have extra functionality in mind ?

**Comment by jeenbroekstra** [comment]
@barthanssens I think what you implemented was _exactly_ what I had in mind here, thanks! I'll close this as a duplicate.
