### ISSUE TITLE
Console should allow definition of namespaces

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#604]
(related to #539 )

The RDF4J Console should have an option to define/set namespaces (especially on SPARQL endpoint repositories) to facilitate SPARQL querying without having to define namespace clauses in every single query.

**Comment by jeenbroekstra** [comment]
@barthanssens given eclipse/rdf4j-doc#72, am I correct in thinking this feature has already been implemented? Is this a duplicate issue?

**Comment by barthanssens** [comment]
Yes, the code is in dev tree, and it's indeed a duplicate of #1100
