### ISSUE TITLE
Provide constants for the SKOS-XL vocabulary

### ISSUE THREAD

**Issue by manuelfiorelli** [eclipse/rdf4j#609]
Package `org.eclipse.rdf4j.model.vocabulary` should be extended with a utility class for the [SKOS eXtension for Labels (SKOS-XL)](https://www.w3.org/TR/skos-reference/#xl) vocabulary. It is worth mentioning that the aforementioned package already contains a utility class for the SKOS vocabulary. Therefore, the addition of another class for a standard extension (supporting reified labels) should be acceptable.

**Comment by ansell** [comment]
This sounds useful given it has been standardised as part of the W3C SKOS standard.

**Comment by manuelfiorelli** [comment]
I've already written the utility class. If you like, I can make a pull request in a day or two.
