### ISSUE TITLE
RioFileTypeDetector does not recognise file types

### ISSUE THREAD

**Issue by jgrzebyta** [eclipse/rdf4j#613]
The file detector does not recognise the data file. In the following code just returns null.

```
RioFileTypeDetector det = new RioFileTypeDetector();
		log.debug("file type: {}", det.probeContentType(resource));
```
The original file comes from **Any23**. The second one is made by **rapper** and is *rdfxml-abbrev* type. Both files were passed by W3 validator (at https://www.w3.org/RDF/Validator/). Neither *turtle* file made by *rapper* was recognised.

All example files and unit tests are available in my local branch *issues/#613-detector* commit 21730c1546eb9c65485953e044ebba15a272921a

**Comment by jgrzebyta** [comment]
This bug affects files detection on the rdf4j workbench page during repository loading.

**Comment by ansell** [comment]
It is possible that Path.getFileName returns the Jar file. You need to extract the resources from the JAR file before your test will work.

**Comment by ansell** [comment]
To be clear, there is no content detection happening so it doesn't matter what is in the files, it is all based on the file name.

**Comment by jgrzebyta** [comment]
Thanks for pointing me out that. That's important information. The path
passed to detector is not jar file. Files in src/test/resources are not
packed into jar. Thus probably there is error in the RE. By the way maybe
it is worth to use java.nio Path to detect the file extension. I need to
look at deeper in the code.

**Comment by jgrzebyta** [comment]
It was my fault I missed `rdf4j-rio-* packages`. I need to go somewhere else in the code to find the other error reason.
