### ISSUE TITLE
System repository does not sync the first commit [Sesame 2.8.9]

### ISSUE THREAD

**Issue by elky87** [eclipse/rdf4j#623]
System repository is a memory repository which is created with syncdelay of 0L and persist = true

The first time I make changes to the system repository and commit the changes the commitInternal Method of MemoryStoreConnection first calls scheduleSyncTask and then calls notifySailChanged.

ScheduleSyncTask calls sync() which syncs on the following condition: 

if (persist && contentsChanged) 

persist is true but contentsChanged is false, because notify context changed is called after scheduleSyncTask.

If a sync delay of >0 is used this shouldn't cause a problem because then notifySailChanged is already called before sync() is called.

Proposed bugfix: In MemoryStoreConnection.java method commitInternal
First: call notifySailChanged
then: call scheduleSyncTask

**Comment by ansell** [comment]
Is this causing data loss? For example, when you shutdown the sail does it fail to sync at that point?

**Comment by elky87** [comment]
It leads to data loss when you don't shut it down correctly. When you shut it down correctly everything is synched just fine.

**Comment by jeenbroekstra** [comment]
Related issue https://openrdf.atlassian.net/browse/SES-2346.
