### ISSUE TITLE
Default evaluation strategy factory is missing

### ISSUE THREAD

**Issue by edwardsph** [eclipse/rdf4j#625]
The default evaluation strategy used for memory and native stores in version 2.1 is: org.eclipse.rdf4j.query.algebra.evaluation.impl.SimpleEvaluationStrategyFactory yet this no longer exists. It seems to have been renamed as org.eclipse.rdf4j.query.algebra.evaluation.impl.StrictEvaluationStrategyFactory as part of #164.

If you accept the default whilst creating a repository, you can't then open the repository.

**Comment by jeenbroekstra** [comment]
Professional opinion: drat.

 Expect a patch early next week.

**Comment by jeenbroekstra** [comment]
Bug does not affect programmatic configuration or RDF4J Workbench, but only RDF4J Console. .ttl config templates were overlooked when renaming.

**Comment by jeenbroekstra** [comment]
Given that the default value can be overridden simply by typing in a different value, this is not quite as critical as I thought it was. Still very inconvenient of course.

**Comment by jeenbroekstra** [comment]
Also noticed that only memory.ttl and native.ttl templates have added the new strategy parameter. Derived variants (e.g. memory-spin or native-rdfs) do not. Will fix that as part of this patch.
