### ISSUE TITLE
ModelBuilder does not map object string to prefixed name

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#632]
The new ModelBuilder accepts string values of the form "ex:foo" for the subject and predicate, and behind the scenes maps and converts this to an IRI (either by mapping the prefix `ex:` to a full namespace, or by just treating the entire string as an IRI).

However, for object values, it currently doesn't do this. An object value passed as a string is always translated to a Literal. So, for example:

    new ModelBuilder.subject("ex:Cat").add(RDF.TYPE, "ex:Animal")

will result in "ex:Cat" being an IRI, but "ex:Animal" being a Literal. This is inconsistent, and moreover the only alternative is to use a ValueFactory to forcedly create the IRI - which is clumsy.

To fix, the ModelBuilder should try and make an educated guess - first try and see if the string is a valid prefixed name (with a known prefix). Only if it isn't should it be mapped to a string-literal instead.

In the corner case where a user actually _intends_ to create a literal-value for a string that looks like a prefixed name, that user will still have to use a ValueFactory. Arguably this is the exception rather than the common scenario, though.

**Comment by ansell** [comment]
Adding a new method specifically for the IRI Subject case could be useful, but not sure what to name it.

Ie, the method would have both addIRI(IRI, IRI) and addIRI(IRI, String) versions.

Another corner case is relative URIs, if they are supported....
