### ISSUE TITLE
Can we make repository id to be only alphanumerics plus underscore

### ISSUE THREAD

**Issue by nikolavp** [eclipse/rdf4j#637]
We are a hitting a problem where on some operating systems(Windows) some characters are not allowed in the filesystem. Sadly there is one to one correlation to repository ids and a storage folder in the data directory. Also the error messages are not descriptive enough to be useful, files in that directories cannot be created.

@damyan-ognyanov @avataar

**Comment by jeenbroekstra** [comment]
Actually, `RepositoryManager` has a public method `getNewRepositoryID` which is exactly intended for this kind of sanitizing of a repository id string. But the strange thing is that this method is not actually used in either the Console or the Workbench app.
