### ISSUE TITLE
Improvement: Create logger warning if rollback is called without an active transaction

### ISSUE THREAD

**Issue by elky87** [eclipse/rdf4j#648]
Use case:

I had a sail-memory repository and was wondering why my changes where not rolled back although I called the rollback method. I later found out that I forgot to start the transaction with begin().

I would propose to add a logger warning if someone tries to rollback changes without an active transaction as this would make debugging a lot easier.

I would propose to make the changes in AbstractSailConnection:453

if (txnActive) {
 //do internal commit
}else{
 logger.warn("Cannot rollback transaction because transaction is not active", new Throwable());
}

**Comment by ansell** [comment]
Hi @elky87, I have created a pull request to fix this issue at https://github.com/eclipse/rdf4j/issues/669

**Comment by jeenbroekstra** [comment]
Given that this is such a trivial enhancement it can be scheduled as a hotfix in a patch release.

**Comment by elky87** [comment]
Super, thank you guys!
