### ISSUE TITLE
change of page size from 100 -> 10 in workbench causes error 

### ISSUE THREAD

**Issue by dockstreet** [eclipse/rdf4j#659]
When trying to page with rdf4j 2.1.2 ; if I change the page size from 100 -> 10 

The following error is logged:
21-Nov-2016 20:39:07.145 INFO [http-nio-8080-exec-8] org.apache.coyote.http11.Ht
tp11Processor.service Error parsing HTTP request header
 java.lang.IllegalArgumentException: Invalid character found in the request targ et. The valid characters are defined in RFC 7230 and RFC 3986

This was on Tomcat 8.5.8

**Comment by jeenbroekstra** [comment]
I can not immediately reproduce this. Can you show me the exact SPARQL query you do when you experienced this? Also: which internet browser are you using?

**Comment by dockstreet** [comment]
I had to redact this some

I went to the query panel in the workbench then ran  :
select ?s ?p ?o where {?s ?p ?o} 

I then navigated to a record : 
http://localhost:8080/rdf4j-workbench/repositories/MyVirt9/explore?resource=%3Chttp%3A%2F%2Fontologies.example.com%2FETL%2Fentity%23104%3E

Then navigated again and got the error:
http://localhost:8080/rdf4j-workbench/repositories/MyVirt9/explore?resource=%3Chttp%3A%2F%2Fontologies.example.com%2FETL%2Fentity%23104%3E&limit_explore=10&know_total=23&query=select%20?s%20?p%20?o%20where%20{?s%20?p%20?o}&ref=

I just read something about so , not sure if that is what it's about.
"Neither '{' nor '}' are permitted characters in a URI and that includes
the query string."

**Comment by jeenbroekstra** [comment]
Although I still can not reproduce the exact error you're getting, I believe I have found the cause. If I produce a patched build of the workbench, could you test it locally and see if it fixes the problem?

**Comment by jeenbroekstra** [comment]
Patched version of workbench: [rdf4j-workbench-2.2p659.war.zip](https://github.com/eclipse/rdf4j/files/605352/rdf4j-workbench-2.2p659.war.zip)

Simply rename to rdf4j-workbench.war (you don't need to unzip first, the .zip extension was only added because github does not allow upload of .war files) and deploy. Since the fix involves clientside Javascript you may need to clean your browser cache as well.

**Comment by dockstreet** [comment]
Confirmed!!! This patch corrected the issue!

**Comment by jeenbroekstra** [comment]
Awesome, thanks for confirming. I'll reopen because I haven't actually integrated this patch in codebase yet.
