### ISSUE TITLE
repository needs to be created first from console 

### ISSUE THREAD

**Issue by dockstreet** [eclipse/rdf4j#660]
If the repository is created in the workbench in Tomcat 8.5.8, options will not be enabled to manipulate the repository other than deleting it.

If it is created from the console, the repository can be altered from the workbench.

**Comment by jeenbroekstra** [comment]
Possible duplicate of #640 (assuming that you're using Google Chrome).

**Comment by dockstreet** [comment]
duplicate; let's close this
