### ISSUE TITLE
Workbench: LIMIT clause works even in a comment

### ISSUE THREAD

**Issue by jondoig** [eclipse/rdf4j#679]
The LIMIT clause limits the number of solutions returned even when it is commented out.

E.g. this query will return only one solution:

```
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX myspace: <http://example.com/somepath/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

CONSTRUCT {
    myspace: a skos:ConceptScheme, owl:Ontology
} WHERE {}
# LIMIT 1
```

Changing the last line to:
```
# LIMIT 2
```
will cause the query to return two solutions.

**Comment by jeenbroekstra** [comment]
I haven't verified this, but if memory serves the Workbench implements some "dirty tricks" to implement pagination. In particular it does a quick regex match on the supplied query to find the LIMIT clause. Looks like that regex match is not specific enough to deal with comments. 

We should probably look at completely removing this regex match and seeing about using alternative means to get pagination to work (should be possible now we have REST API parameters for this kind of thing, see #575).

**Comment by jeenbroekstra** [comment]
Relevant code is in `org.eclipse.rdf4j.workbench.util.PagedQuery`. Probably needs replacement by just adding request parameters.
