### ISSUE TITLE
Clean up compliance tests to avoid resource leaks

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#682]
Current compliance test implementations often fail to properly close connections or shut down repositories, especially if an error occurs during testing. This produces a lot of unnecessary error output on the build log, and in addition may interfere with subsequent tests. 

To fix, the compliance tests should make rigorous use of `try-with-resources`, ensuring RepositoryConnections and QueryResults are always properly closed even when exceptions occur.

**Comment by ansell** [comment]
I am going to work on this, found some new stacktraces (mixed into all of the previous stacktraces) in the debugging logs from the new close operations added to Background(Graph/Tuple)Result.run and want to make sure things will still work as expected.

In particular, I want to remove e.printStackTrace from places where we are expecting or allowing an exception to occur. They are possibly masking other cases where tests may have started silently failing and we didn't notice them in the jumble.

**Comment by jeenbroekstra** [comment]
Go for it @ansell . I can't assign this to you (still need to ask about allowing contributors to be assignee) but it's all yours.
