### ISSUE TITLE
SPARQL parser fails to parse integer object value immediately followed by full stop

### ISSUE THREAD

**Issue by aindlq** [eclipse/rdf4j#685]
Here is sparql query which RDF4J fails to parse properly:
```
select ?Concept where { 
  ?Concept a 1. 
  ?Concept2 a 1.
} LIMIT 100
```
Probably this is a bug in RDF4J parser, but I'm not quite sure.
Tested with RDF4J workbench v2.1.2.

See also discussion at https://github.com/RubenVerborgh/SPARQL.js/pull/33

**Comment by ansell** [comment]
The Turtle and Trig parsers were both updated to handle the horrible "1." syntax but the SPARQL-1.1 parser may not have been done.

**Comment by jeenbroekstra** [comment]
It looks as if the SPARQL grammar was silently tweaked at some point to deal with this. Our implemented grammar accepts a decimal with a floating point but no decimal digits (e.g. '1.'). However this production does not exist in the current spec.
