### ISSUE TITLE
Add Literals.getLabel method that accepts Optional input value

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#688]
`Literals.getLabel` only accepts actual `Value` objects (with a fallback when the Value is null or not a Literal).

In combination with, for example, `Models.object()` this leads to slightly convulated code:

    String label = Literals.getLabel(Models.object(m.filter(...)).orElse(null), fallback);

If `Literals.getLabel` also accepted an Optional value directly, we could do this instead:

    String label = Literals.getLabel(Models.object(m.filter(...)), fallback);

**Comment by raghav17083** [comment]
in the implementation of getLabel() is overloaded.
```public static String getLabel(Literal l, String fallback) {
		return l != null ? l.getLabel() : fallback;
	}

	/**
	 * Returns the result of {@link #getLabel(Literal, String) getLabel((Literal)v, fallback} in case the supplied value
	 * is a literal, returns the fallback value otherwise.
	 */
	public static String getLabel(Value v, String fallback) {
		return v instanceof Literal ? getLabel((Literal) v, fallback) : fallback;
	}
```

Is this issue fixed, since getLabel can now handle null values also?

**Comment by jeenbroekstra** [comment]
@raghav17083 not really - this issue is about having a `Literals.getLabel` method that accepts a `java.util.Optional` instead of only a `Value` or `Literal` as its first argument. 

This:

     String label = Literals.getLabel(Models.object(m.filter(...)), fallback);

won't work right now, because the result of the `Models.object` call is an `Optional`, not a `Value` or `Literal`.

It's a fairly minor thing but having this option will make for slightly cleaner and easier to read code when using these functions.

**Comment by raghav17083** [comment]
So, does this mean that we just have to overload the getLabel() method to account for an 'Optional' call?

**Comment by jeenbroekstra** [comment]
Yes, exactly

**Comment by jeenbroekstra** [comment]
@SakshiSaini17092 thanks for the pull request. Are you and @raghav17083 working together on this?

**Comment by raghav17083** [comment]
> @SakshiSaini17092 thanks for the pull request. Are you and @raghav17083 working together on this?

Yes!
