### ISSUE TITLE
Upgrade  standard taglibs to 1.2.5 and commons-fileupload for 1.3.2

### ISSUE THREAD

**Issue by tommytan27** [eclipse/rdf4j#696]
The latest version of RDF4J is using old version of standard-1.1.2 (taglibs) and commons-fileupload-1.3.1

The latest version of standard taglibs is 1.2.5. The version used by the latest RDF4J is 1.1.2 which has a known (published) critical vulnerability.
The latest version of commons-fileupload is 1.3.2, while the version used by the latest RDF4J is 1.3.1, which also has known (published) security vulnerability.

Would it be possible to get these 2 libraries updated to their latest versions, to minimize the vulnerability?

**Comment by jeenbroekstra** [comment]
I filed for legal review of both dependencies: 

- CQ for commons-fileupload 1.3.2: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=12403
- CQ for taglib 1.2.5: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=12404 

Once we have approval we can look at upgrading to these new versions.

**Comment by ansell** [comment]
You can rebuild RDF4J locally with the latest versions if you are worried about the vulnerabilities in the meantime by checking out the code, updating the versions in the Maven pom.xml file and repackaging.

**Comment by jeenbroekstra** [comment]
Both CQs are approved so we can go ahead with this.

**Comment by tommytan27** [comment]
That is great!!! Does it mean that it would be included in the next milestone?
