### ISSUE TITLE
Decimals that are referenced only with a dot are not interpreted properly by the parser

### ISSUE THREAD

**Issue by nikolavp** [eclipse/rdf4j#704]
By the spec you can reference decimals with a dot only. So for example if I have this in the database:
```
<u:s> <u:p> 456.0
```
and then I run the query

```sparql
select * {
   ?s ?p 456.
}
```
I should the subject and predicate of the statement but It is not returned. Also the following which is part of the conformance suite of the parser is throwing a parser error

```sparql
select * {
   ?s ?p 456. . 
}
```

**Comment by jeenbroekstra** [comment]
See #685 . I'm currently on holiday so can't check thoroughly, but pretty sure this is incorrect. Grammar for decimals changed between SPARQL 1.0 and 1.1, in the new version dot-only is no longer legal.

**Comment by nikolavp** [comment]
Sorry for the invalid report, it seems the grammar was changed.
