### ISSUE TITLE
Support BIND in SparqlQueryRenderer

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#71]
(Migrated from https://openrdf.atlassian.net/browse/SES-2206 )

SPARQL 1.1 constructs cannot be rendered via the SparqlQueryRenderer class.  

### Subtasks

- [x] support BIND 
- [x] migrate metaphacts internal query renderer to RDF4J (#3012 )
- [ ] Integrate experimental new renderer with existing renderer code (#3041)
- [ ] support aggregates (#3000)
- [ ] support subqueries (#3001)

### Examples

For example If I parse this query with QueryParserUtil.parseQuery:

```
SELECT \* WHERE {
  ?s ?p ?o .
  BIND(uri("http://test-graph.com/") AS ?foo) .
}
```

And then render the ParsedQuery back out again with SPARQLQueryRenderer, it appears to lose the binding clause, returning the following string:

```
select ?g ?s ?p ?o ?g2
where {
  GRAPH ?g {
    ?s ?p ?o.
}}
```

Looking at renderTupleExpr in SparqlTupleExprRenderer I can see that the following lines are commented out:

        // aRenderer.mProjection = new ArrayList<ProjectionElemList>(mProjection);
        // aRenderer.mDistinct = mDistinct;
        // aRenderer.mReduced = mReduced;
        // aRenderer.mExtensions = new HashMap<String, ValueExpr>(mExtensions);
        // aRenderer.mOrdering = new ArrayList<OrderElem>(mOrdering);
        // aRenderer.mLimit = mLimit;
        // aRenderer.mOffset = mOffset;

With the following commented out in SPARQLQueryRenderer:

                        // SPARQL does not support this, its an artifact of copy and
                        // paste from the serql stuff
                        // aQuery.append(mRenderer.getExtensions().containsKey(aElem.getSourceName())
                        // ?
                        // mRenderer.renderValueExpr(mRenderer.getExtensions().get(aElem.getSourceName()))
                        // : "?"+aElem.getSourceName());
                        //
                        // if (!aElem.getSourceName().equals(aElem.getTargetName()) ||
                        // (mRenderer.getExtensions().containsKey(aElem.getTargetName())
                        // &&
                        // !mRenderer.getExtensions().containsKey(aElem.getSourceName())))
                        // {
                        // aQuery.append(" as ").append(mRenderer.getExtensions().containsKey(aElem.getTargetName())
                        // ?
                        // mRenderer.renderValueExpr(mRenderer.getExtensions().get(aElem.getTargetName()))
                        // : aElem.getTargetName());
                        // }

I believe these lines are commented out in error and that they should be commented back in in order to get be able to round trip queries from SPARQL text into the AST and back out again.  

Other SPARQL 1.1 queries that fail include:

`SELECT (COUNT (*) as ?c) WHERE { ?s ?p ?o }`

is rendered as

`select ?c where { ?s ?p ?o }`

and the query

`SELECT (?p as ?x) WHERE { ?s ?p ?o }`

is rendered as

`select ?p WHERE { ?s ?p ?o }`

**Comment by jeenbroekstra** [comment]
The basic problem is that the QueryRenderer was implemented against the SPARQL 1.0 standard, and has never been extended to include the new SPARQL 1.1 features (even though RDF4J's query engine fully supports SPARQL 1.1). The renderer should be extended to be able to process these features.

**Comment by jeenbroekstra** [comment]
We need to have a discussion about the query render and the query builder tools, and the newly integrated spanqit module.

**Comment by timbaer** [comment]
Hi evrybody,

so as this ticket is closed, is there any way to create an AST based on a SPARQL Query, modify it, and transform it back to SPARQL? I believe this is a very viable feature for this project. 

Regards

**Comment by jeenbroekstra** [comment]
Creating an AST from a query is what the SPARQL parser package (specifically the class `org.eclipse.rdf4j.query.parser.sparq.ast.SyntaxTreeBuilder`) does. There's support for modifying it as well through the `SyntaxTreeBuilderVisitor` interface. 

The only thing we don't really have full support for is serializing an AST back into a SPARQL query string. The SparqlQueryRenderer discussed in this issue has partial support, but as the ticket says, it's never been updated to deal with SPARQL 1.1.

**Comment by jeenbroekstra** [comment]
This got closed accidentally a while ago by merging a fix that had nothing to do with this, but which (accidentally) used this issue's ticket number.

**Comment by jeenbroekstra** [comment]
Thanks @RedCrusaderJr, your fix for BIND has been merged in!

I am planning to pick up further improvements as subtasks of this issue.

**Comment by jeenbroekstra** [comment]
Closing this as complete, further improvements will be taken care of as followup tasks.
