### ISSUE TITLE
Configure Travis build to skip install step

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#710]
Travis currently runs a pre-build install command, executing `mvn install`. This is redundant as the maven build step (`mvn verify`) will take care that all necessary dependencies are downloaded and installed. 

To tweak this, we should add the following to the travis config:

    install: true

**Comment by ansell** [comment]
There will be issues if there are circular build dependencies, as may be the case on that pull request.

**Comment by ansell** [comment]
Looking at the pull request it doesn't look like anything circular could have been introduced though, so may be another cause.

**Comment by jeenbroekstra** [comment]
@ansell even if there are, those will be picked up by the actual build step, won't they? I don't think running an explicit install _before_ running the verify really solves anything.

**Comment by jeenbroekstra** [comment]
btw just found the problem in that PR, it was a simple compile failure after all, no idea why it was so hard to track down.

**Comment by ansell** [comment]
"mvn install" runs verify prior to the install lifecycle step. When mvn verify runs, the compilation should have all completed and only tests will be run. I usually leave the defaults for Java on TravisCI as I haven't seen any case where they fail, and they isolate compile errors from test errors nicely.

**Comment by jeenbroekstra** [comment]
Hm, perhaps you're right.
