### ISSUE TITLE
Provide optional syntax validation for IRIs when using ValueFactory.createIRI

### ISSUE THREAD

**Issue by elky87** [eclipse/rdf4j#712]
I had a bug where my problem was, that I created an IRI with a leading whitespace so:

ValueFactory.createIri(" http://something.com") 

instead of 

ValueFactory.createIri("http://someting.com")

In my opinion it would be a good idea if the createIri method would trim whitespaces before creating the IRI or maybe throw an error if an IRI is created with whitespaces.

**Comment by jeenbroekstra** [comment]
Related issue: #69

**Comment by jeenbroekstra** [comment]
A slight complication in this is that validation slows down object creation, and ValueFactories are not only used by users, but also by the various parsers (which already do their own validation) and by the actual database itself. Adding mandatory syntax checking in the create method would be a significant performance burden on both parsers and databases.

However it should be possible to make this a configurable/optional choice for users. Possibly the simplest way is to have a specific ValueFactory implementation that provides this.

**Comment by elky87** [comment]
Yes, this sounds like a good idea. But isn't it a bit of an inconsistency that ValueFactory checks if a ":" is inside the string? Either check for everything (with a specfific ValueFactory implementation) or check for nothing I would say.

**Comment by jeenbroekstra** [comment]
@elky87 I kind of agree it is inconsistent, but that check on a column has been present since forever, possible even Sesame 1. Purely for backward compatibility reasons we can't easily remove it, but I don't want to add further performance burdens by adding more validation without the means to turn it on or off.

**Comment by tfrancart** [comment]
I am also facing the same problem and I think the best solution would be to provide a check at ValueFactory level.
