### ISSUE TITLE
SPIN Constructor: FILTER with floating-point comparison fails when OPTIONAL in same WHERE clause

### ISSUE THREAD

**Issue by gwcox66** [eclipse/rdf4j#717]
I'm using RDF4J Workbench and Server version 2.1.4:

System Information
Application Information
Application Name	RDF4J Workbench
Version	2.1.4
Runtime Information
Operating System	Windows 8.1 6.3 (amd64)
Java Runtime	Oracle Corporation Java HotSpot(TM) 64-Bit Server VM (1.8.0_101)
Process User	Greg
Memory
Used	305 MB
Maximum	3463 MB

I'm editing ontologies including SPIN constructors using TopBraid Composer FE and importing them into RDF4J as RDF files.  The ontology of interest is pub7.rdf using prefix pub7: and available here: [https://drive.google.com/file/d/0B5rex-PdunMsY1BQRVh5bkFOejg/view?usp=sharing](url)

The example of this bug is the lone SPIN constructor for `pub7:Pub7TestClass`.  The constructor is:

```
# test constructor for FILTER comparison bug
CONSTRUCT {
    ?this Nuvio:hasDataValue "hit"^^xsd:string .
}
WHERE {
    OPTIONAL {
        ?this Nuvio:hasObjectQuantity ?someObjectQuantityURI .
    } .
    BIND ("5.0000"^^xsd:double AS ?radiusValue) .
    FILTER (?radiusValue != 0.0) .
}
```

As written, this constructor should fire on any instantiation of `pub7:Pub7TestClass`.  In my case, I use a simple SPARQL update query from RDF4J workbench: 

```
PREFIX Nuvio: <http://cogradio.org/ont/Nuvio.owl#>
PREFIX inst: <http://www.disa.mil/dso/a2i/ontologies/PBSM/Sharing/Instantiations#>
PREFIX pub7: <http://www.disa.mil/dso/a2i/ontologies/PBSM/Interface/Pub7#>

INSERT DATA
{
  inst:aPub7TestClass_test3 a pub7:Pub7TestClass .
}
```

The result is an instance of pub7:Pub7TestClass without the "hit" string but with indication that the constructor did run:

```
Subject                      Predicate                                        Object
inst:aPub7TestClass_test3    <http://www.openrdf.org/schema/spin#executed>    _:node1b67vn8agx60123
inst:aPub7TestClass_test3    rdf:type                                         pub7:Pub7Concept
inst:aPub7TestClass_test3    rdf:type                                         rdfs:Resource
inst:aPub7TestClass_test3    rdf:type                                         owl:Thing
inst:aPub7TestClass_test3    rdf:type                                         pub7:Pub7TestClass

```

Now if I run the constructor query below (with a triple thrown in to define `?this`) in the RDF4J workbench, I get the result shown further below, showing the expected triple:

```
PREFIX Nuvio: <http://cogradio.org/ont/Nuvio.owl#>
PREFIX inst: <http://www.disa.mil/dso/a2i/ontologies/PBSM/Sharing/Instantiations#>
PREFIX pub7: <http://www.disa.mil/dso/a2i/ontologies/PBSM/Interface/Pub7#>

# test constructor for FILTER comparison bug
CONSTRUCT {
    ?this Nuvio:hasDataValue "hit"^^xsd:string .
}
WHERE {
    ?this a pub7:Pub7TestClass .
    OPTIONAL {
        ?this Nuvio:hasObjectQuantity ?someObjectQuantityURI .
    } .
    BIND ("5.0000"^^xsd:double AS ?radiusValue) .
    FILTER (?radiusValue != 0.0) .
}
```

```
Subject                    Predicate           Object
inst:aPub7TestClass_test3  Nuvio:hasDataValue  "hit"
```

So, the constructor query produces the expected triple when run manually but does NOT produce the expected "hit" triple when run automatically as a constructor.  

If I vary the constructor by eliminating the OPTIONAL clause and instantiate my test instance as above, then I do get my "hit" triple, as expected:

```
# test constructor for FILTER comparison bug
CONSTRUCT {
    ?this Nuvio:hasDataValue "hit"^^xsd:string .
}
WHERE {
    BIND ("5.0000"^^xsd:double AS ?radiusValue) .
    FILTER (?radiusValue != 0.0) .
}
```

![image](https://cloud.githubusercontent.com/assets/20132242/21903402/6425ef78-d8c5-11e6-99c0-e25bfe769750.png)

Similarly, if I OR in a boolean true condition in my FILTER but keep the OPTIONAL clause: 

![image](https://cloud.githubusercontent.com/assets/20132242/21903498/c68e7054-d8c5-11e6-897f-70a971bf6ad3.png)

Then I get my "hit" triple upon instantiation of my pub7:Pub7TestClass using the same Update query as above:

![image](https://cloud.githubusercontent.com/assets/20132242/21903579/0e64b87a-d8c6-11e6-84bb-cdcbe3e91b81.png)

This looks like a bug.  It reminds me of [https://github.com/eclipse/rdf4j/issues/298](url)

Note that the constructor used to illustrate this bug is acknowledged as quite impractical.  I simplified it to illustrate the bug.  The constructor I'm actually working on (that does have practical application) is in the `pub7:Pub7Proposal` class:

![image](https://cloud.githubusercontent.com/assets/20132242/21903719/936bee3a-d8c6-11e6-8301-0fd1912cccf5.png)

**Comment by gwcox66** [comment]
The last example shown above of the "real" constructor should have the following OPTIONAL clause:

```
    OPTIONAL {
        ?this soo:hasSCMReceiverModel ?existingReceiverModelURI .
    } .
```

I'm omitting this clause for the moment in order to avoid the bug documented in this posting.  However, it could lead to problems in the future if other rules generate an existing model triple and this rule generates another one...

**Comment by gwcox66** [comment]
I updated to 2.1.5 to see whether this bug persisted and actually worsened.

![image](https://cloud.githubusercontent.com/assets/20132242/22069983/f7f74906-dd5f-11e6-84c7-c6c608570995.png)

It now appears that if the `OPTIONAL `clause does not match, then the entire encompassing `WHERE `clause does not match or that the evaluation of the constructor ceases prematurely.  Simplifying my test constructor for my `pub7:Pub7TestClass` as follows: 

```
# test constructor for FILTER comparison bug
CONSTRUCT {
    ?this Nuvio:hasDataValue "hit"^^xsd:string .
}
WHERE {
    OPTIONAL {
        ?this Nuvio:hasObjectQuantity ?someObjectQuantityURI .
    } .
}
```

It seems to me that this constuctor's `WHERE `clause should _always_ match because it only contains an `OPTIONAL `clause.    However, in the above example instantiating with the same UPDATE query where `?this` does not have a `Nuvio:hasObjectQuantity`, I don't get my "hit":

![image](https://cloud.githubusercontent.com/assets/20132242/22070191/c424f4f6-dd60-11e6-8f43-5b71568a7684.png)

So now, if I change my `OPTIONAL `clause to find a match:

```
# test constructor for FILTER comparison bug
CONSTRUCT {
    ?this Nuvio:hasDataValue "hit"^^xsd:string .
}
WHERE {
    OPTIONAL {
        ?this a ?someType .
    } .
}
```

I do get my "hit" with all other conditions remaining the same:

![image](https://cloud.githubusercontent.com/assets/20132242/22070359/548ea1d6-dd61-11e6-8e1c-a87b632b830c.png)

Perhaps another clue in this result is that when the `OPTIONAL ` clause failed (first case in this comment) , other constructors which should have run did not.  When the `OPTIONAL ` clause matched (second case in this comment), other constructors which should have run did run (the second and third SPIN executed triples).  Did the failure to find a match in the `OPTIONAL ` clause of this constructor prematurely terminate the execution of _both_ this test constructor and all other applicable constructors?

**Comment by gwcox66** [comment]
I've upgraded to 2.1.6, and the problem with the OPTIONAL clause persists precisely as shown in my previous comment for 2.1.5.  As things stand, I'm trying not to use OPTIONAL, MINUS or UNION in my constructors, but my application will demand use of these eventually.  Help?

**Comment by gwcox66** [comment]
This issue remains under 2.2.1.

**Comment by jeenbroekstra** [comment]
Apologies for leaving this unopened and unanswered for so long, I'm not entirely sure how this remained unnoticed, especially with such an extensive report of the issue. 

I will have to close this issue as the SPIN Sail has been made deprecated, and no further development of the SPIN functionality is planned.
