### ISSUE TITLE
Loss of bound values for variables assigned in a SERVICE graphPattern

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#72]
(Migrated from https://openrdf.atlassian.net/browse/SES-2209 )

Federated queries like the following won't return bound values for variables assignments defined in the SERVICE graph pattern.

{code}
SELECT ?s ?bindingS ?now 
WHERE {
    SERVICE http://dbpedia.org/sparql {
        ?s a ?someType .
        BIND (?s as ?bindingS)
        BIND (now() as ?now)
    }
} LIMIT 1
{code}

**Comment by jamesrdf** [comment]
This works as expected with the #812 fix
