### ISSUE TITLE
SPARQLRepository sends non-standard parameters

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#721]
SPARQLRepository, when sending requests to a SPARQL endpoint, sends non-standard request parameters, including `queryLn`. 

While this is not a problem for most endpoint implementations (they simply ignore them), a few known endpoint implementations (such as MarkLogic) choke on this. It would be good to remove these parameters from SPARQLRepository requests.

**Comment by jeenbroekstra** [comment]
On closer inspection, this is not actually a bug - there is nothing in the SPARQL protocol spec that prevents sending parameters other than the ones documented there. Still, to improve compatibility, it would be good to clean this up.

**Comment by jeenbroekstra** [comment]
As part of this, I also want to slightly refactor (rename, and perhaps partly simplify) the XXXSesssion and XXXClientImpl classes.

**Comment by elky87** [comment]
Is there already a rough estimation when 2.2 will be released? (sorry for spamming on this post)

**Comment by jeenbroekstra** [comment]
@elky87 we're aiming for a February 2 release.
