### ISSUE TITLE
Add methods on org.eclipse.rdf4j.rio.RDFHandler to help with pretty-printing

### ISSUE THREAD

**Issue by sesuncedu** [eclipse/rdf4j#722]
It could be useful to be able to have advisory methods that signal: 
1. that a blank node that will only be use for a relatively short time is about to be used.
2. that the last statement using such a blank node has been seen. 

The idea is to be able to signal that turtle/TriG '[]' formatting may be possible, without having to rely on a fixed size buffer. ( I think I'm missing a semantic condition here. )

This could be generalized to signaling the start of a sequence of statements that will contain all uses of an identifier in a subject position, as well as indicating that no more statements using that identifier as subject will be used.

It would also be useful to be able to signal that a blank node will identify an rdf:List instance that is 
1. the object of precisely one property, and that that property is not rdf:rest, and 
2. that the instance is the subject of precisely two statements, one of which has a property of rdf:first and the other has a property of rdf:rest, and 
3. the object of the rdf:rest property is either nil, or an instance of rdf:List satisfying conditions 2 and 3., and which is the object of no other statement. 

The idea is to be able to signal that '(...)' abbreviation is possible.

All of these methods could have default implementations that are no-ops.

**Comment by ansell** [comment]
+1, would be very useful to use default methods in this way to add optionally supported methods. In this case, if the writer/handler doesn't recognise the signal they are free to ignore it without corrupting any data.

**Comment by jgrzebyta** [comment]
`Rio.write(Iterable<Statement> model, RDFHandler writer)` method checks if a model is instance of `Model` class. In practice namespaces are printed only in case of Model.

**Comment by sesuncedu** [comment]
Release related question:

As a matter of release engineering policy, do team rdf4j consider default methods on interfaces like RDFHandler to be Major or Minor? 

The Java language specification explicitly classes them as binary compatible; however the eclipse classification treats them as generally breaking iff the interface may be implemented by outside classes. 

This is because there is an edge case where under release n, such a class might implement an interface that has a  default method with the same ; if the added default method has the same signature and name, (and is used but not implemented, IIR), there can be a run time error. 

If such a clash is unlikely, the guidelines say it can be treated as non breaking. I'd say this is the case here. 

If the change is still pending, when are the cutoff dates for the next minor, or the next major if appropriate? 


(I have been spending an ungodly amount of time examining backwards compatibility in all OSGI bundle series on maven central. Exploratory data analysis indicates that almost everyone lies about semantic versioning. I have to post my hypotheses before running real experiments)

**Comment by ansell** [comment]
There is the possibility that default methods could be binary incompatible if another interface defines the same method name already with a different signature. Having said that, there is no way to know what users are currently inheriting besides our classes (and we have a fairly high chance of noticing if we made that mistake ourselves).

Personally I am all in for adding default methods to interfaces in minor releases, not patch releases. It is one of the best lifecycle features Java has ever thought up IMO.

**Comment by ansell** [comment]
New interfaces can also be added in minor releases as long as they don't break any existing public APIs. I will add a new interface for ``NamespaceAware`` or similar, with the naming open for discussion still. The existing ``Rio.write`` methods will need to stay, but I will modify the instanceof check internally for the new interface. 

``RepositoryResult<Statement>`` is difficult as it is an iteration of ``Statement``, not a collection of ``Statement`` with ``Namespace`` attached. Not sure how to fix that one other than to also support another ``Rio.write`` signature, but will also explore that in a PR.
