### ISSUE TITLE
AddRDF form -> Data format 'Autodetect' does not work

### ISSUE THREAD

**Issue by jgrzebyta** [eclipse/rdf4j#723]
Affected version: 2.1.2 but probably the latest as well because I had that error for long time. (since sesame times).

Servlet is not able to identify Turtle format data file if I add RDF using input form. Data format: 'Autodetect' option returns following error: 

![error](https://cloud.githubusercontent.com/assets/6738268/21997541/c2c077e6-dc27-11e6-8af3-8ecc207dbade.jpg)

**Comment by jeenbroekstra** [comment]
This looks like the same issue as #647.

**Comment by jgrzebyta** [comment]
Closed because It was repeated #67 .
