### ISSUE TITLE
Add japicmp maven plugin to check API changes

### ISSUE THREAD

**Issue by ansell** [eclipse/rdf4j#732]
The japicmp maven plugin can be used to programmatically generate reports about API changes. This is useful even before we define the Public API, so we can get a feel for how likely refactorings are to effect users:

https://siom79.github.io/japicmp/MavenPlugin.html

My previous use has been in JSONLD-Java where it works fairly well so far:

https://github.com/jsonld-java/jsonld-java/blob/f713c7e53e57c173da532ab66facc1e793bdc1d0/pom.xml#L328

**Comment by ansell** [comment]
Relates to #619 and #724

**Comment by ansell** [comment]
I will add some initially to the api modules that are definitely on the Public API but not others which we are not sure about per #619. They will only generate reports so far, so they won't fail the build if incompatible changes are found, but that is an option in future.

**Comment by jeenbroekstra** [comment]
Sounds good. Can you point us to an example of what one of these reports looks like?

**Comment by jeenbroekstra** [comment]
Never mind, found an example on the plugin page itself: https://siom79.github.io/japicmp/Examples.html . Looks pretty straightforward?

**Comment by ansell** [comment]
Yes, they are very straightforward as long as you turn on the "onlyModified" setting. They are generated on build into the target/japicmp/ directory as HTML files. The files are basically empty if no interfaces have changed, and populated with all of the relevant classes/methods/fields if any were added/removed/changed.

The reports differentiate between source and binary compatible. "Binary incompatible changes are marked with (!) while source incompatible changes are marked with (*)." I don't think we expect our code to be binary compatible (based on past behaviour), but we do want it to be source compatible as far as practical.

The default is also to look at protected/public, which I think is relevant for us in some cases with our Abstract implementations that we intend third-parties to reuse. We could change it to "public-only" but it wouldn't be as useful.

We can also customise it to only particular packages or classes, which will help for some of the embedded "impl" packages inside of api modules.

The code also shows up serialisation issues, which we have some of between 2.0 and 2.2-SNAPSHOT.

It is a little annoying in our large scale case that the reports are not yet aggregated to the reactor parent, but it should still be useful for us to review pull requests.

If you run "mvn clean install -DskipTests" on the pull request #733 code you can get a fairly quick idea of what some of the reports look like.
