### ISSUE TITLE
Individual rdf4j jars could be turned into OSGi bundles

### ISSUE THREAD

**Issue by sesuncedu** [eclipse/rdf4j#737]
Currently, the only bundle information in any of the rdf4j artifacts is in the aggregated osgi-runtime bundle.  It can be useful to have each artifact be a bundle so they can be deployed separately. 
 I am currently rejiggering the OWLAPI osgi distribution as part of setting up a move to gradle, and I've put together some code to do some basic bundle wrapping of any non-bundle dependencies, but that's just using the jar versions as the package versions, which is not ideal. 

Also, naive packaging doesn't distinguish between packages that are part of the public API, and packages that are internal to the module. This distinction is also relevant for jigsaw  (which also decides visibility at the package level, with the extra nuance that modules can limit which other modules have access to their contents).

**Comment by ansell** [comment]
Would using rdf4j-runtime-osgi help in the short term:

https://search.maven.org/#search%7Cga%7C1%7Ca%3A%22rdf4j-runtime-osgi%22

Unfortunately, none of the regular RDF4J developers work on OSGI-reliant projects, so it doesn't get much love.

**Comment by sesuncedu** [comment]
The big bundle can be dependency mangled by consumers.  It's still nice to have the individual modules bundled, and not too much extra work to do it the lazy way. I'm surprised it's not mandatory for Eclipse :)
