### ISSUE TITLE
Pull based parsers for RDF & Tuple formats

### ISSUE THREAD

**Issue by RickMoynihan** [eclipse/rdf4j#738]
The current parsers in RDF4j all follow a push based model, where they control the execution flow entirely - firing events at a statement handler.

This makes it awkward to support certain use cases which are better suited to a pull based parser.  For example currently if you wanted to display a paginated list of statements/tuples without consuming the whole stream, you'd have to run the parser on a separate thread and block the parser with something like a `java.util.concurrent.BlockingQueue` to communicate results to your display; then when a page is displayed stop the parser by signaling your handler to raise an exception.

Another more general use case is in supporting a functional/lazy programming style where the amount of data to be processed is decided by a `take`that occurs outside of the parse code.  Grafter (a Clojure wrapper for RDF processing over sesame) takes this approach and has to jump through some of [the hoops mentioned above](https://github.com/Swirrl/grafter/blob/master/src/rdf-common/grafter/rdf/io.clj#L534) to allow an RDF stream to be viewed as a lazy sequence.  I suspect also that trying to do things like this with Java 8 streams will result in the same kinds of work around.

It would be nice if all the sesame parsers, for both RDF and Tuple formats could support these use cases.  One approach would be to provide a pull based interface to all of the parsers.  Another might be to provide a method for the current push based parsers to terminate the parse as either a success or a failure early.

Obviously also the pull based interface could theoretically be built on top of the push based implementation or vice versa.

**Comment by ansell** [comment]
The entire implementation of the current parsers is based around the handler methodology. 

Blocking as you say can already be done by blocking inside of handleStatement/etc using a Blocking Queue. The lazy approach is simply a BlockingQueue limited to size 1.

Pagination is easily supported using counting handlers along with aborting inside of handleStatement, without changing the internal implementation of the parsers.

**Comment by ansell** [comment]
I was wrong about pagination being easy though, because of blank nodes. However, blank nodes make all RDF decomposition difficult, so nothing new there though.

**Comment by ansell** [comment]
PR #741 has some enhancements related to this issue. In particular, you will be able to use the QueryResults.parseGraphBackground and QueryResultIO.parseTupleBackground methods, along with the QueryResults.limitResults methods to achieve most of what you expect, without having to modify the way any of the parsers internally work. 

This is done using BlockingQueue.put and/or BlockingQueue.offer(e, time, unit) (where the offer is used to check for interruptions before offering the item again without returning from the handlers handle method.

In particular, it is definitely possible not to have to parse an entire InputStream now, as the queue will feed back to kill the parser if/when you close the TupleQueryResult/GraphQueryResult object.

**Comment by ansell** [comment]
I may not have been clear above with the comment about chaining methods together. To enable limits and offsets using a pull based approach you would use code like:

```
try (final GraphQueryResult queryResult = QueryResults.limitResults(
             QueryResults.parseGraphBackground(inputStream, baseURI, rdfFormat), limit, offset);) {
    while(queryResult.hasNext()) {
        queryResult.next();
    }
}
```

or:

```
try (final TupleQueryResult queryResult = QueryResults.limitResults(
             QueryResultIO.parseTupleBackground(inputStream, queryResultFormat), limit, offset);) {
    while(queryResult.hasNext()) {
        queryResult.next();
    }
}
```

Both of those will give you a simulated pull-based parser that can return slices from within a set of results, and in the current code, will not attempt to parse more than 1 Statement/BindingSet past the last accessed result.

Note that any BNode's returned from QueryResults.limitResults are not likely to match any of the BNode's returned from other calls to QueryResults.limitResults, so use slicing with caution. Given the background parsing on its own simulates a pull based parser it may be enough on its own without the call to limitResults.

**Comment by ansell** [comment]
@RickMoynihan was the addition of the background parsing helper methods, which hooked into existing functionality to simulate a pull-based parser, satisfactory progress to closing this issue?
