### ISSUE TITLE
Turtle parser returns equivalent bnodes for successive parse operations

### ISSUE THREAD

**Issue by ansell** [eclipse/rdf4j#745]
The Turtle parser does not appear to be updating the bnode assignment state between calls to parse to make sure that successive parse operations do not return the same bnodes. Do we formally support multiple calls to RDFParser.parse btw? I thought that parsers in general were one-use but now I am not sure.

**Comment by jeenbroekstra** [comment]
I don't think we document one way or the other, really. How difficult would it be to support multiple uses? Apart from this particular issue there's little I can think of in any of the parsers that is stateful and/or needs to be reinitialized. 

Advantage of reusing a parser is that you get to retain any custom parser configuration.

**Comment by ansell** [comment]
There is a protected method call on the abstract parser class that should be done at the start of every parse method if we want to support it, IIRC.

**Comment by ansell** [comment]
https://github.com/eclipse/rdf4j/blob/master/core/rio/api/src/main/java/org/eclipse/rdf4j/rio/helpers/AbstractRDFParser.java#L340

**Comment by ansell** [comment]
it is actually documented that it needs to be called at the end of parse, but I would prefer if it were (also?) called at the start, given we aren't storing the bnodes in a map anymore and the rest of the storage doesn't explode in terms of memory usage.

**Comment by ansell** [comment]
The PR for this is ready for review/merging, and would fix both this issue and #778 if merged, so could be useful to do before the next patch release
