### ISSUE TITLE
Transaction broken during long session

### ISSUE THREAD

**Issue by jgrzebyta** [eclipse/rdf4j#750]
My rdf loader is fragile for longer session (jgrzebyta/sesame-loader#24). When I try to upload (via HTTConnection) mid size RDF file (~33M, RDF/XML) I have following error in the beginning of session:

```
Caused by: java.lang.IllegalStateException: Transaction URL has not been set
	at org.eclipse.rdf4j.http.client.SesameSession.rollbackTransaction(SesameSession.java:547)
	at org.eclipse.rdf4j.repository.http.HTTPRepositoryConnection.rollback(HTTPRepositoryConnection.java:353)
	... 17 more
```

Also ref #728

**Comment by jgrzebyta** [comment]
@jeenbroekstra Which module is good for keeping in integration tests? I want to build test with uploading one of the uniprot's file. For example taxonomy 1G.

**Comment by jeenbroekstra** [comment]
@jgrzebyta not sure it's wise to make that part of the integration tests - it's likely to take a long time, so I wouldn't want it to be executed every time we do a maven build. I guess we need a separate module for scalability and benchmarking tests. Perhaps have a look at including it in the new benchmark root module?

**Comment by jeenbroekstra** [comment]
Btw that stacktrace is not really enough to tell what's going wrong. The error indicates that you tried to do a rollback while the SesameSession object does not have an active transaction registered on the client-side. AFAIK the only way that can happen, really, is if you're trying to do a rollback on a HTTPRepositoryConnection that doesn't have a transaction started.
