### ISSUE TITLE
org.eclipse.rdf4j.model.impl.AbstractValueFactory#createLiteral(Date) depends on the default system TimeZone

### ISSUE THREAD

**Issue by petervanthof** [eclipse/rdf4j#753]
The implementation of org.eclipse.rdf4j.model.impl.AbstractValueFactory#createLiteral(Date) depends on the default system TimeZone, which can differ from OS to OS, from machine to machine. This will lead to different results on different environments.

Maybe this could be documented :-) Furthermore, maybe adding a createLiteral(Calendar) or createLiteral(ZonedDateTime) would be nice.

**Comment by ansell** [comment]
Can you give an example of where the Locale would influence a Literal created from createLiteral(Date) and what a fix may be?

**Comment by petervanthof** [comment]
Hi Peter,

Thanks for the quick reply.

Here is some test code. I hope this clarifies things.

```
  @Test
  public void test() {
    ValueFactory factory = SimpleValueFactory.getInstance();

    // UTC +02
    ZonedDateTime zonedDateTime = ZonedDateTime.parse("2007-12-03T10:15:30+01:00[Europe/Athens]");

    // Prints "zonedDateTime: 2007-12-03T10:15:30+02:00[Europe/Athens]"
    System.out.println(String.format("zonedDateTime: %s", zonedDateTime));

    Date date = Date.from(zonedDateTime.toInstant());

    // The default time zone at my machine is Europe/Berlin
    // ValueFactory#createLiteral(Date) will create a Literal with this time zone,
    // meaning I have no control over the output
    Literal result = factory.createLiteral(date);

    // Prints "2007-12-03T09:15:30.000+01:00"
    System.out.println(result.stringValue());
  }
```

The implementation of AbstractValueFactory#createLiteral(Date) creates a GregorianCalendar with the default TimeZone. Possible fixes:

* Add a createLiteral(Date, TimeZone); // Use the TimeZone to create the Calendar with
* Add a createLiteral(Calendar); // Hand over control of creating the Calendar to the caller
* Add a createLiteral(ZonedDateTime); // Java 8 only

**Comment by jeenbroekstra** [comment]
Given that we are moving to the new Java time API it is unlikely that we'll fix this directly.
