### ISSUE TITLE
versions conflict in rdf4j-sail-elasticsearch

### ISSUE THREAD

**Issue by jgrzebyta** [eclipse/rdf4j#756]
I found there is problem with Lucene version in `rdf4j-sail-elasticsearch`. Currently that package (through org,elasticsearch/elasticsearch) depends on lucene v 5.1.1 where the rest of package depends on 5.2.1.

I build *elastic search test* which throws missing class which exists only in the newer version. I guess it is worth to update elastic version to the latest 5.1.1 which depends on lucene 6.3.0.

After all it will be:
- Lucene v 6.3.0
- elasticsearch v 5.1.1

**Comment by jeenbroekstra** [comment]
Note that these updates require a significant number of new CQs - we will need to submit for approval for all Lucene modules as well as as the new elasticsearch dependencies. Currently we only have approval for elasticsearch 1.7.0, and lucene 5.2.1. If at all possible, we should fix the sail to consistently depend on those versions - unless there are good technical reasons to upgrade.

**Comment by jgrzebyta** [comment]
@jeenbroekstra OK. Thanks for explanation. I found the error is probably because the elastic search test uses module which was compiled using another lucene version (5.2.1) and now it misses needed class in CLASSPATH (that is org.apache.lucene.index.LeafRef). Excluding all lucene-X from elasticsearch did not help. I will create a branch with my fix #739 .

**Comment by jgrzebyta** [comment]
I will remove the elasticsearch test into locals unit test and convert to use the standard memory repository.
