### ISSUE TITLE
Maven package aborts due to multi languages

### ISSUE THREAD

**Issue by pirelaurent** [eclipse/rdf4j#759]
Maven compile works fine, but maven package abort on rio test . trace below.
Errors comes from a translated error message returned by rio ( my PC is a french one ). 
I don't know how to tell the test to work in english, neither where it took the language. 
As a workaround, i can comment the assert, but it could be better to find how to enforce current language in english or to have multilanguage assert in a case .

### i found issue #280 and #284 and do a **mvn install -Dmaven.test.skip=true** that works without running tests. So this step is closed. 

But if someone has ideas to works WITH tests and locale, thanks. 

-------------------------------------------------------------------------------
Test set: org.eclipse.rdf4j.rio.rdfxml.RDFXMLParserTest
-------------------------------------------------------------------------------
Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.485 sec <<< FAILURE! - in org.eclipse.rdf4j.rio.rdfxml.RDFXMLParserTest
testFatalErrorPrologContent(org.eclipse.rdf4j.rio.rdfxml.RDFXMLParserTest)  Time elapsed: 0.037 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:**<[Rio fatal] Conten[t is not allowed in prolog]. (1, 1)**> but was:**<[Rio fatal] Conten[u non autorisé dans le prologue]. (1, 1)>**
	at org.eclipse.rdf4j.rio.rdfxml.RDFXMLParserTest.testFatalErrorPrologContent(RDFXMLParserTest.java:153)

**Comment by ansell** [comment]
Thanks for the report. I will fix see how I can fix that test, likely by setting the Locale to english just for that test.
