### ISSUE TITLE
FROM clause does not work on remote RDF resource 

### ISSUE THREAD

**Issue by jgrzebyta** [eclipse/rdf4j#761]
I found my following SPARQL request does not work: 

```
SELECT * FROM <http://dbpedia.org/data/Edinburgh.ttl>  
WHERE {  
  ?s ?p ?o . 
} LIMIT 10
```
I built unit test (see aca01bef72d4af6b2f7a43a15b51cc10d711f492) for that in `org.eclipse.rdf4j.repository.sail.SPARQLFROMClauseTest`.

Please could anybody check if that is correct in terms of all java machinery? 
I mean usually there is separation between the triple population and requesting using `connection.commit()` inbetween. Here where the population is in the request it should be solved in different way. Shouldn't be?

**Comment by jeenbroekstra** [comment]
This is a misunderstanding of how the `FROM` clause works. `FROM` merely identifies a graph in the dataset being queried. In RDF4J, that means it maps onto a context identifier in the queried repository. It does not automatically resolve and retrieve data from a remote endpoint.

**Comment by jgrzebyta** [comment]
So the feature that FROM allowed to populate was a side effect?

**Comment by ansell** [comment]
Dereferencing is an optional feature, similar to Federated queries. It is a security risk in general and is only referred to in an informative (not normative) security note in the SPARQL-1.1 spec:

https://www.w3.org/TR/sparql11-query/#security

**Comment by jeenbroekstra** [comment]
FWIW the DataSetRepository does have functionality along these lines.

**Comment by jgrzebyta** [comment]
@jeenbroekstra  That is exactly I looked for. Thanks a lot.
