### ISSUE TITLE
rdf4j-workbench Add RDF Microsoft Edge 

### ISSUE THREAD

**Issue by emberey** [eclipse/rdf4j#763]
Using the workbench within Edge most things work except the ability to add RDF as the upload button gets written into textarea that RDF data woulf be added and is not therefore available.

A quick fix for this is to modify \rdf4j-workbench\transformations\add.xsl to force some text into the textarea.

<textarea id="text" name="content" rows="6" cols="70"
	onchange="workbench.add.enabledInput('text')">Microsoft Edge Fix
</textarea>

Needless to say you will have to remove this text when adding RDF.

**Comment by josephw** [comment]
Sounds like Edge may be transforming it into  an empty `<textarea/`> element and then parsing that as HTML.

Does [this question](http://stackoverflow.com/questions/37351438/why-is-my-xslt-formatting-not-working-correctly-in-microsoft-edge-on-the-windows)'s advice, to add `<xsl:output method="html"/>` to the `add.xsl` stylesheet, work?

**Comment by emberey** [comment]
No - doesn't help. Not a problem as my suggested change is good enough. Thanks anyway.

Same problem occurs with Sparql Update.

Similar fix adding Microsoft Edge Fix to the textarea causes the page to display correctly.

No reply needed.
