### ISSUE TITLE
Support for OWL2 vocabulary

### ISSUE THREAD

**Issue by barthanssens** [eclipse/rdf4j#766]
OWL2 uses the same namespace as OWL, but adds some properties like owl:deprecated

See also https://www.w3.org/TR/owl2-overview/

**Comment by seralf** [comment]
Hi what is needed for adding OWL2? "only" the vocabulary, or there is also some test to be implemented?

**Comment by barthanssens** [comment]
As far as I'm concerned, it's only about adding the vocabulary (I just wanted to use the owl:deprecated property in a project, without OWL2 reasoning)
So if you think it would be a good idea, it can be added very quickly.

**Comment by seralf** [comment]
Hi do you have a link to the full vocabulary?

2017-08-01 19:35 GMT+02:00 Bart Hanssens <notifications@github.com>:

**Comment by barthanssens** [comment]
https://www.w3.org/2002/07/owl# (OWL2 reuses the OWL 1 namespace, and IIRC they are very similar)
