### ISSUE TITLE
RDFJson parser checks for null instead of not null in the parse method for reader

### ISSUE THREAD

**Issue by nikolavp** [eclipse/rdf4j#773]
Look at line https://github.com/eclipse/rdf4j/blob/master/core/rio/rdfjson/src/main/java/org/eclipse/rdf4j/rio/rdfjson/RDFJSONParser.java#L157

**Comment by jeenbroekstra** [comment]
It looks as if three different people have now independently implemented a fix for this. Only barthanssens has actually put up a Pull Request though.
