### ISSUE TITLE
All SPARQL hash functions like MD5 ignores the trailing zeros

### ISSUE THREAD

**Issue by vassilmomtchev** [eclipse/rdf4j#775]
The SPARQL query below skips the trailing zeros for all hash functions:

`select *
where {
    BIND(md5("363") as ?md5)
}`

Here is what I get:

00411460f7c92d2124a67ea0f4cb5f85 (with 'md5 -s 363')
___411460f7c92d2124a67ea0f4cb5f85 (with the SPARQL query)

Check the suspected code:

https://github.com/eclipse/rdf4j/blob/2.2/core/queryalgebra/evaluation/src/main/java/org/eclipse/rdf4j/query/algebra/evaluation/function/hash/HashFunction.java#L30-L36

**Comment by barthanssens** [comment]
Message digest length should be checked... I'm looking into it

**Comment by barthanssens** [comment]
pull request added, might be a bit too low-level / bit-banging (can also use String.format, or Arrays.fill... many ways to do it)
