### ISSUE TITLE
IRI with space

### ISSUE THREAD

**Issue by skodapetr** [eclipse/rdf4j#780]
File ```input.ttl``` contains IRI with encoded space:
```
_:b25978837	a <http://purl.bioontology.org/ontology/UATC/\u0020SERINE\u0020\u0020> .
```
The Turtle parser is able to read this IRI (with encoded spaces) as a valid IRI.  
However Turtle writer does not encode the space on  output, resulting in:
```
_:genid-ca45343d5be841429acf1ca16a6fe928-b25978837 a <http://purl.bioontology.org/ontology/UATC/ SERINE  > .
```
When we try to load this statement the parser fail with:
```
Exception in thread "main" org.eclipse.rdf4j.rio.RDFParseException: IRI included an unencoded space: '32' [line 2]
	at org.eclipse.rdf4j.rio.helpers.RDFParserHelper.reportError(RDFParserHelper.java:322)
	at org.eclipse.rdf4j.rio.helpers.AbstractRDFParser.reportError(AbstractRDFParser.java:601)
...
```
A simple program can be utilized to reproduce this error:
```
    public static void main(String[] args) throws Exception {
        try (InputStream input = new FileInputStream(new File("input.ttl"));
                OutputStream output = new FileOutputStream(new File("output.ttl"))) {
            RDFParser parser = Rio.createParser(RDFFormat.TURTLE);
            parser.setRDFHandler(Rio.createWriter(RDFFormat.TURTLE, output));
            parser.parse(input, "http://localhost/base/");
        }
        try (InputStream input = new FileInputStream(new File("output.ttl"))) {
            RDFParser parser = Rio.createParser(RDFFormat.TURTLE);
            parser.parse(input, "http://localhost/base/");
        }
    }
```
This problem also propagates to the querying remote SPARQL endpoints.

The same issue can be experienced when using N-Triples, however for JSON-LD and RDF/XML no error is given. 
The comment  in [TurtleParser](https://github.com/eclipse/rdf4j/blob/master/core/rio/turtle/src/main/java/org/eclipse/rdf4j/rio/turtle/TurtleParser.java#L921) suggest that the \n and similar (spaces?) should be handled as errors.

It's not clear what is an intended behaviour.

Tested with rdf4j 2.2 .

**Comment by barthanssens** [comment]
I assume this is related to #69 (and that there is no strict checking on generating/writing IRIs because it impacts performance)

**Comment by jeenbroekstra** [comment]
Also related to #712

**Comment by KnowledgeGarden** [comment]
Importing a ttl file with the TURTLE format, line 1 of which is this:
<http://dbpedia.org/property/name> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/1999/02/22-rdf-syntax-ns#Property> .
landed this log statement:
org.eclipse.rdf4j.rio.RDFParseException: IRI included an unencoded space: '32' [line 1]
	at org.eclipse.rdf4j.rio.helpers.RDFParserHelper.reportError(RDFParserHelper.java:322)

**Comment by KnowledgeGarden** [comment]
I now believe that my errors reported here were based on inappropriate use of the APIs. By switching to Model-based parsing before adding to the repo, all errors disappeared.
