### ISSUE TITLE
Missing results while evaluating multiple ArbitraryLengthPath in same query

### ISSUE THREAD

**Issue by damyan-ognyanov** [eclipse/rdf4j#781]
to reproduce:
 - create an empty memory store
 - insert following sample data:

```
insert data {
<class:4> rdfs:subClassOf <class:3> .
<class:3> rdfs:subClassOf <class:2> .
<class:2> rdfs:subClassOf <class:1> .

<inst:1> a <class:4> .
}
```

-evaluate a query like:
```
select * {
    values (?expectedTargetClass1 ?expectedTargetClass2) {(<class:1> <class:1>)}.

    <inst:1> a ?linkTargetClass1 .
    ?linkTargetClass1 rdfs:subClassOf* ?expectedTargetClass1 .

    <inst:1> a ?linkTargetClass2 .
    ?linkTargetClass2 rdfs:subClassOf* ?expectedTargetClass2 .
}
```

It does not return any results. But if we change the names of any of the variables, e.g. `?expectedTargetClass2` to `?expectedTargetClass21` for instance the query return a single solution.

Looking at the 2.1 codebase, the PathIteration creates intermediate anonymous variables while searching for paths of different length using the hashcode of the pathExpression:
```
				Var replacement = createAnonVar(
						JOINVAR_PREFIX + currentLength + "-" + pathExpression.hashCode());
```

It turn out that the hashCode() for both pathExprssions in the same query is exactly the same so the names of the intermediate variables end up also the same:
```

StatementPattern
   Var (name=linkTargetClass2)
   Var (name=_const_4592be07_uri, value=http://www.w3.org/2000/01/rdf-schema#subClassOf, anonymous)
   Var (name=expectedTargetClass2)

Var (name=intermediate-join-1--1524416206, anonymous)
```

Tried a workaround by creating unique var names (by overriding PathIteration.createAnonVar()) but that one failed because the same var naming scheme is used in getNextElement() in order to get the value bound from the previous step from the bindingset based on the current step / path length. 

One possioble solution could be to append also the System.identityHashCode(pathExpression) while constucting the var name or if we stick with unique var names, a list/stack of used vars should be used so one to be able to access the intermediate var by position from the current binding set.

**Comment by jeenbroekstra** [comment]
If I understand your proposed solution using `System.identityHashCode` correctly, that would solve the issue without the need for keeping track of used names in a list: `getNextElement` only needs to be able to refer back to intermediate vars within the same path expression, so it can use the same method to generate the name of the preceeding var on the fly.

**Comment by damyan-ognyanov** [comment]
Yes, can confirm that appending the System.identityHashCode to the names of the intermediate/end vars in the PathIteration solves the issue.

**Comment by damyan-ognyanov** [comment]
@jamesrdf alough the change to the StatementPattern makes it more selective it does not solve the original issue. I applied your proposed change into a local branch and plaed a bit with the variable names so was able to find quickly a set such that still trigger the original issue:
 ```
select * {
	values (?expectedTargetClass1 ?expectedTargetClass5544T) {(<class:1> <class:1>)}.
	<inst:1> a ?linkTargetClass1 .
	?linkTargetClass55555 rdfs:subClassOf* ?expectedTargetClass55555 .
	<inst:1> a ?linkTargetClass55556 .
	?linkTargetClass55556 rdfs:subClassOf* ?expectedTargetClass5544T .
}
```

and here is the output of toString() for both ArbitraryLenthPath nodes along with the pathExpression's hashCode(). As you coudl see, the hashCode() ends up the same thus, when used in the PathIteration  later it still will trigger the names for the intermediate valiables 

```
ArbitraryLengthPath
   Var (name=linkTargetClass55555)
   StatementPattern
      Var (name=linkTargetClass55555)
      Var (name=_const_4592be07_uri, value=http://www.w3.org/2000/01/rdf-schema#subClassOf, anonymous)
      Var (name=expectedTargetClass55555)
   Var (name=expectedTargetClass55555)
, expr hash:441684442
ArbitraryLengthPath
   Var (name=linkTargetClass55556)
   StatementPattern
      Var (name=linkTargetClass55556)
      Var (name=_const_4592be07_uri, value=http://www.w3.org/2000/01/rdf-schema#subClassOf, anonymous)
      Var (name=expectedTargetClass5544T)
   Var (name=expectedTargetClass5544T)
, expr hash:441684442

```
