### ISSUE TITLE
SPARQLProtocolSession ignores some query parameters

### ISSUE THREAD

**Issue by peterneorr** [eclipse/rdf4j#784]
RDF4J does not send all the same HTTP parameters that the older sesame library used to, and this significantly alters the results returned by the endpoint my team uses. (Stardog)  

Specifically SPARQLProtocolSession.java used to send an "includeInferred" parameter.  Since it no longer does so, I cannot use RDF4J for any queries to my database that require reasoning.

Some digging indicated that this was a changed in commit related to issue #721.   
Here is the commit: https://github.com/eclipse/rdf4j/commit/570abf3820a5716e0ef45dab7dc67740ec1761d9

I've cloned the repo and confirmed that that adding the "includeInferred" parameter back to the getQueryMethodParameters method resolved my particular issue of a Stardog endpoint not including inferred statements in it's response.

**Comment by jeenbroekstra** [comment]
This effectively reverts improvement #721 , which deals with the SPARQL protocol client sending non-standard parameters. In other words these parameters were removed intentionally to be more strictly compliant with the SPARQL Protocol standards.

If you are communicating with a server that understands RDF4J extensions to SPARQL protocol, why don't use you an RDF4JProtocolClient instead?

**Comment by hmottestad** [comment]
I think that extensions to the header are more likely to be compatible with stores like mark logic that don't follow the standards. Any thoughts on this?

**Comment by peterneorr** [comment]
@jeenbroekstra, I think your suggestion of using RDF4JProtocolSession will work for me.  Either this, I can create my own subclass of SPARQLRepository that overrides createHTTPClient() to return my own subclass of SPARQLProtocolSession.  

That said, it's a little weird that the API has methods that don't do anything. (e.g. Operation.setIncludeInferred() etc)

Thanks for the suggestion. :)
