### ISSUE TITLE
Add code quality plugins to jenkins build

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j#790]
We should look into adding some code quality plugins (like FindBugs, PMD, and/or CheckStyle) to the Jenkins build. This will make it easier for contributors to understand where their contributions need to be updated and will help us produce overall better code. 

- [x] CQ22184: Spotbugs 4.0.3
- [x] CQ22185: Spotbugs maven plugin 4.0.0

**Comment by barthanssens** [comment]
FWIW, I've started using Netbeans Inspect and Transform.
When enabling all the bells and whistles, there are a few thousands suggestions in the report, although most of them can be either ignored (e.g. using static imports, that's a matter of taste IMHO, I prefer not to use static imports) or are easy to "fix" (missing override annotation or javadoc param etc...)

**Comment by barthanssens** [comment]
On a related note, there is also SpotBugs, available as Eclipse and maven plugin https://spotbugs.readthedocs.io/en/latest/maven.html

**Comment by barthanssens** [comment]
FWIW, I'm currently looking into spotbugs, looks promising:
* there is a Jenkins plugin (https://wiki.jenkins.io/display/JENKINS/Warnings+Next+Generation+Plugin)
* supported by maven, Eclipse (and older Netbeans, unfortunately not yet for recent Netbeans)
* an additional plugin for extra security checks is also available (OWASP, CWE) https://find-sec-bugs.github.io/

**Comment by barthanssens** [comment]
Created  CQ 21366 (PB) in IpZilla

**Comment by barthanssens** [comment]
Creating a new one for more recent spotbugs version + plugins

**Comment by jeenbroekstra** [comment]
I closed this because the associated PR was closed - I get the feeling there was little enthusiasm for the idea in the end. Feel free to correct me and reopen though.
