### ISSUE TITLE
hbase support

### ISSUE THREAD

**Issue by hbasejanitor** [eclipse/rdf4j#816]
hbase backend for SAIL.

I'm going to use this issue to track my patches for an hbase sail backend.

**Comment by barthanssens** [comment]
FWIW, there seems to be a somewhat similar project (Apache licensed) https://merck.github.io/Halyard/

**Comment by hbasejanitor** [comment]
Thanks for the pointer.

My RDFJ stuff in on hold right now due to work schedule.

**Comment by jeenbroekstra** [comment]
Given there is a solid third-party open source alternative for this I am closing this for now. Feel free to re-open if/when you want to start working on this again.
