### ISSUE TITLE
Memory leak with user VisaulVM 1.3.8

### ISSUE THREAD

**Issue by inem88** [eclipse/rdf4j#821]
I have some problem with memory leak in rdf4j. I start VisualVM as usual and start monitor. Than I repair all my exceptions, but RDF4J eat more and more memory when i make many queries.
But when I start VisualVM 1.3.9 - there is not any problem.

**Comment by barthanssens** [comment]
Could it be a visualvm bug ?

**Comment by jamesrdf** [comment]
The JVM might allocate more and more memory if it stays within its assigned threshold. Do you know how much memory it is using and what the maximum memory it is configured to use?
