### ISSUE TITLE
Disconnect the benchmark pom so that it doesn't get released 

### ISSUE THREAD

**Issue by hmottestad** [eclipse/rdf4j#823]
The benchmark module gets released on sonatype, which shouldn't happen.

Consider removing the parent tag from the pom, but double check that the benchmarks still run on the correct version of the code.

**Comment by jamesrdf** [comment]
If it is disconnected then it's version might not get updated: #751

**Comment by jeenbroekstra** [comment]
It's worth thinking about moving the benchmarks to separate git repo.
