### ISSUE TITLE
Update guava dependency

### ISSUE THREAD

**Issue by jimkont** [eclipse/rdf4j#826]
The guava dependency in this project is too old and creates conflicts in projects that use a newer version. The error I currently get is
`Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;)V`

If you google this, this issue happened in other projects like 
 - https://github.com/appium/java-client/issues/588
 - https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/7940
 - https://github.com/SeleniumHQ/selenium/issues/3540
 - https://github.com/google/guava/issues/2380

Propose to update the quava version from version 18 to version 21

**Comment by Hronom** [comment]
I'm suggesting to upgrade up to 22
