### ISSUE TITLE
Feature: JDBC-like driver

### ISSUE THREAD

**Issue by barthanssens** [eclipse/rdf4j#838]
Would be nice to have a JDBC-like driver (so one can access an RDF-store in reporting tools etc) similar to Jena's JDBC framework.
No SPARQL-to-SQL translation needed, just the connection and getting results from a SPARQL query.

**Comment by seralf** [comment]
what about using [Calcite](https://calcite.apache.org/docs/)?

**Comment by barthanssens** [comment]
Thanks for the link. I'm not familiar with Calcite, but it looks like Calcite either needs a JDBC connection (so this enhancement would come in handy) or a yet-to-be-written RDF4J adapter (which would also be useful, and perhaps less work) ?

**Comment by seralf** [comment]
I have to study it better, but it seems something that should simplify the
development of an adapter

2017-07-06 7:46 GMT+02:00 Bart Hanssens <notifications@github.com>:

**Comment by VladimirAlexiev** [comment]
We at Ontotext also want a JDBC driver, as mentioned at https://docs.google.com/document/d/1guwFHi9p4-ujFkrHF6dwMUZndzCmlX_gPyiBi6JlPTs/pub#h.etad8qvxqd6t (2017)

- Jena: http://jena.apache.org/documentation/jdbc/
- (older) jdbc4sparql: https://code.google.com/archive/p/jdbc4sparql/
- (older) SCON: https://code.google.com/archive/p/scon/wikis/Introduction.wiki

**Comment by VladimirAlexiev** [comment]
For the record, here's the doc of GraphDB's JDBC "connector": https://graphdb.ontotext.com/documentation/10.0/sql-access-over-jdbc.html. It uses Apache Calcite and "stored SPARQL views" exposed as relational tables

**Comment by VladimirAlexiev** [comment]
@seralf I doubt this will be open sources, but I'll ask
