### ISSUE TITLE
unqualified attribute 'lang' not allowed [line 2, column 21]

### ISSUE THREAD

**Issue by KnowledgeGarden** [eclipse/rdf4j#841]
Importing the file dbpedia_2016-04.owl using RepositoryConnection. RDFXML format.
Specific error message is this:
org.eclipse.rdf4j.rio.RDFParseException: unqualified attribute 'lang' not allowed [line 2, column 21]
	at org.eclipse.rdf4j.rio.helpers.RDFParserHelper.reportError(RDFParserHelper.java:322)
In fact, the owl file had many instances of "lang", and they all look something like this line from the file:
<dcterms:title xml:lang="en">The DBpedia Ontology</dcterms:title>

Those are the only instances of "lang", 61 of them. The first one seems nowhere near line 2.

Snippet of the code:
RepositoryConnection con = repo.getConnection();
try {
   URL url = new URL(baseURI);
   con.add(url, url.toString(), format);
}

Full disclosure: the baseURI is the baseURI for my project, not the base for this file, which is
http://dbpedia.org/ontology/

I chose that because when importing ttl files and so forth, it's non-trivial to establish a base.

It's a mystery to me. Thanks in advance for advice.

**Comment by jamesrdf** [comment]
This looks like a problem with the XML parser setup, as the code works for me. Can you post your question to the mailing list with more information about your environment?
