### ISSUE TITLE
SPARQLConnection remove(st, contexts) method cannot handle null values in statement object

### ISSUE THREAD

**Issue by elky87** [eclipse/rdf4j#849]
Problem is in SPARQLConnection::createDataBody

The method does not check if st.getSubject() is null and so fails on .stringValue(line:886) with a nullpointer exception.

**Comment by jamesrdf** [comment]
How did you get a statement with a null subject?

**Comment by elky87** [comment]
Honestly cannot remember. 

I tested a lot of different rdf4j store implementations so maybe some store's ValueFactory let me create such a statement.

I will take another look tomorrow and let you know.

**Comment by jamesrdf** [comment]
Re-open (or create a new) issue when you have more information about this.
