### ISSUE TITLE
Transaction Isolation with HTTPRepositories

### ISSUE THREAD

**Issue by elky87** [eclipse/rdf4j#854]
HTTPRepositories still do not properly support transaction isolation. See the following pseduo example code:
    
    try (HTTPRepositoryConnection repCon=.......) {
        repCon.begin();
        repCon.add(statement1);
        repCon.getStatements(statement1); //here we will get no result
        repCon.commit();
        repCon.getStatements(statement1); //here we will get a result
    }

This issue already should have been fixed according to https://openrdf.atlassian.net/browse/SES-1652 but it seems to still exist in RDF4J 2.2.1

**Comment by ansell** [comment]
It looks like a test still exists for that sequence, unless it is incompatible with IsolationLevels.READ_UNCOMMITTED:

https://github.com/eclipse/rdf4j/blob/master/testsuites/store/src/main/java/org/eclipse/rdf4j/repository/RepositoryConnectionTest.java#L331

And it isn't disabled by the relevant compliance test (as some tests are in some cases):

https://github.com/eclipse/rdf4j/blob/master/compliance/store/src/test/java/org/eclipse/rdf4j/repository/http/HTTPStoreConnectionTest.java

**Comment by elky87** [comment]
Just tried it out again and it indeed works. Don't know what my issue was before, this ticket can be closed
