### ISSUE TITLE
Bind in combination with nested optional does not work

### ISSUE THREAD

**Issue by kenwenzel** [eclipse/rdf4j#879]
When using the following query the variable ?currentLang seems to be unbound in the filter (the filter fails) even though it is bound to a value at the start of the query:

```sparql
SELECT DISTINCT ?this ?firstIns ?ins ?v ?insText WHERE {
	bind (if(bound(?lang), ?lang, "de") as ?currentLang)

	optional {
		?this <http://linkedfactory.org/vocab/maintenance#action> ?firstIns . 
		?firstIns lf-maint:next* ?ins . 
		optional {
			?ins <http://linkedfactory.org/vocab/maintenance#next> ?v . 
		}
		optional {
			?ins <http://linkedfactory.org/vocab/maintenance#text> ?insText . 
			filter (lang(?insText) = ?currentLang)
		}
	}
}
```

The above query also fails to deliver any results if ?currentLang is given a value via the values keyword 
```sparql
values ?currentLang { "de" }
````
or by using the subquery 
```sparql
{ SELECT ?currentlang WHERE bind (if(bound(?lang), ?lang, "de") as ?currentLang) }
```

If I don't use a nested optional block then the query succeeds:

```sparql
SELECT DISTINCT ?this ?firstIns ?ins ?v ?insText WHERE {
	bind (if(bound(?lang), ?lang, "de") as ?currentLang)

	?this <http://linkedfactory.org/vocab/maintenance#action> ?firstIns . 
	?firstIns lf-maint:next* ?ins . 

	optional {
		?ins <http://linkedfactory.org/vocab/maintenance#next> ?v . 
	}
	optional {
		?ins <http://linkedfactory.org/vocab/maintenance#text> ?insText . 
		filter (lang(?insText) = ?currentLang)
	}
}
```

I tested the query with the MemoryStore of RDF4J version 2.2.2.

**Comment by jamesrdf** [comment]
The last query is well design and behaves accordingly. The first query, however, is not well designed and appears to be behaving as expected for these type of unnatural queries. Take a look at section 4.2 of "Semantics and Complexity of SPARQL", 2006, Jorge Pérez et al for an explanation of why this is expected SPARQL behaviour.
