### ISSUE TITLE
missing jdk.tool dependency for rdf4j-sail-solr

### ISSUE THREAD

**Issue by seralf** [eclipse/rdf4j#881]
Hi 
after a new clone/import of the latest source in eclipse, I've found this error:

![missing_jdk_rdf4j_solr](https://user-images.githubusercontent.com/88188/29243459-c1ab4d6a-7f9f-11e7-9110-97f8f1a1b09a.png)

then, searching on the issues/pr I suppose it could be a sort of side-effect of issue #137.

**Comment by jamesrdf** [comment]
What version are you using? Can you provide steps to reproduce this? What version of jdk are you using? The jdk7 backport seems to be the only place this artifact is mentioned in rdf4j. Are you using the jdk7 backport branch?

**Comment by seralf** [comment]
I'm using the main branch from last version on github.
The Screenshot is on Eclipse after a maven import, using latest JDK 8 build.

The same issue is cited in other places for other libraries, I suppose is related to changes from jdk 1.7 and later.
For example: http://hadoopinrealworld.com/missing-artifact-jdk-tools-jar/

**Comment by jamesrdf** [comment]
Hadoop uses the path ${java.home}/../lib/tools.jar in their pom file, which works on my machine. What OS are you using?

I used the following command to find the value of ${java.home}:
$ jrunscript -e 'println(java.lang.System.getProperty("java.home"))'

Does ${java.home}/../lib/tools.jar point to tools.jar on your system?

**Comment by seralf** [comment]
The problem was using windows, while on linux it seems to work ok, very
strange.
The path you proposed seems to work well on my ubuntu

2017-08-18 17:38 GMT+02:00 James Leigh <notifications@github.com>:

**Comment by jamesrdf** [comment]
If the path Hadoop provides is not working then this sounds like an upstream issue and you should speak with Hadoop community directly to sort it out. I don't want to introduce OS specific workarounds here for potential upstream bugs.
