### ISSUE TITLE
RepositorySail: wrapping third party in a Sail object?

### ISSUE THREAD

**Issue by seralf** [eclipse/rdf4j#883]
Hi
While experimenting with `SailRepository` and `LuceneSail` for a project I'm working on, I've notice that while a `SailRepository` instance expose a `getSail()` method for obtain the underlying implementation, there seems to be no way to wrap a `Repository` back into a working `Sail` instance.

I know it could probably introduce a lot of issues in some cases, it could be anyway very useful on some specific scenario: for example I'm trying to adopt virtuoso into a `LuceneSail`, and then it seems that if I could write something like:

```java
Sail sailVirtuoso = new RepositorySail(new VirtuosoRepository(...))
```

I could then try to log all the activities on the new `sailVirtuoso` object (a sort of naive transaction log) and also try to use it as a base sail for `LuceneSail`.

If I'm not wrong something similar was implemented in Ripple, but since as far as i know it was not updated to RDF4J, I'm trying to re-start a partial implementation for my tests.

What do you think about it?

**Comment by jamesrdf** [comment]
Post questions to the mailing list. This is for requesting changes to the RDF4J project.

**Comment by seralf** [comment]
It is a request indeed, with attached a basic idea for an implementation.
My apologies if it looks not in the right form

**Comment by jamesrdf** [comment]
Thanks for the code. However, I think this needs more discussion on the mailing list. You can post to the rdf4j-dev mailing list to get more detailed feedback.
