### ISSUE TITLE
Workbench Modify html page error

### ISSUE THREAD

**Issue by BowenFu** [eclipse/rdf4j#908]
Html page errors exist on Workbench Modify page.
![image](https://user-images.githubusercontent.com/5812640/30142976-17ac8222-93b6-11e7-9921-351728582f64.png)

**Comment by jamesrdf** [comment]
What os/browser/tomcat/rdf4j versions are you using? What steps can I take to reproduce this?

**Comment by BowenFu** [comment]
@jamesrdf I use win 10/Microsoft edge/Tomcat 8 (I'll check it later) /RDF4J 2.2.2.
Nothing special has been done. The 'query' page is ok. But the 'update' page is like in the image.

**Comment by barthanssens** [comment]
Related to #373 ?
