### ISSUE TITLE
RepositoryConnection::add(...) createLock, releaseLock issues

### ISSUE THREAD

**Issue by sranger** [eclipse/rdf4j#914]
We have an issue when adding resources to a RepositoryConnection where it creates and releases a lock every time we add which is ridiculously slow for large datasets. Is there a way to tell the connection to only lock once? We're calling connection.open() before we begin but it doesn't seem to help. The create/release ends up using the majority of CPU time. Even with IsolationLevels.NONE used when the connection is opened doesn't seem to alleviate the amount of locking done.

We're on rdf4j 2.2.2 if it helps.

![create_release_jvisualvm](https://user-images.githubusercontent.com/430220/30276108-bc97f2a8-96d1-11e7-9177-b900ec386dc2.png)

**Comment by jakubklimek** [comment]
We have too experienced a major slowdown when upgrading from 2.2.0 to 2.2.2. Try 2.2.0 and see if it solves your issue.

**Comment by jamesrdf** [comment]
Perform your operations in a transaction to make them more efficient and grouped together. You can also do less concurrently by creating your own queue/locking mechanism.
