### ISSUE TITLE
Travis error: Build times out because no output was received

### ISSUE THREAD

**Issue by jgrzebyta** [eclipse/rdf4j#918]
I found in my PR travis does not receive any response for 10 minutes. I suggest adding more initial memory "-Xms1024" and increase waiting time till 15 mins.

This issue will be solved in PR #887 .

**Comment by jamesrdf** [comment]
This issue is fixed in PR eclipse/rdf4j-testsuite#6, which (among other things) outputs a message every five minutes while it's waiting for the test to finish. Once PR #916 is merged it will take effect.

**Comment by jgrzebyta** [comment]
@jamesrdf OK  Thanks. So I will revert changes in my PR.
