### ISSUE TITLE
missing support for valid xsd:gYear values

### ISSUE THREAD

**Issue by jimkont** [eclipse/rdf4j#934]
based on `xsd` spec values like `-20000`, `20000` and `0000` should be accepted by RDF4J for the `xsd:gYear` datatype but are currently not.

Quoting https://www.w3.org/TR/xmlschema-2/#gYear
> 3.2.11.1 Lexical representation
> 
 >[...] To accommodate year values outside the range from 0001 to 9999, additional digits can be added to the left of this representation and a preceding "-" sign is allowed.

A related PR that adds these values to the test suite and verifies they are not supported is in  https://github.com/eclipse/rdf4j/pull/931

**Comment by jimkont** [comment]
wrt to value `0000`, see 
https://www.w3.org/TR/xmlschema11-2/#vp-dt-year

> [...] Note: In version 1.0 of this specification, the ·year· property was not permitted to have the value zero. [...] 
> In this version of this specification, two changes are made in order to agree with existing usage. First, ·year· is permitted to have the value zero. [...]

**Comment by jamesrdf** [comment]
WRT year zero, RDF4J uses the JVM's validation that is based on XMLSchema 1, which does not have a lexical representation for year zero.

That being said, the values "-20000" and "20000" should be a simple change to support in a future version.
