### ISSUE TITLE
Certain SPARQL query very slow

### ISSUE THREAD

**Issue by jakubklimek** [eclipse/rdf4j#938]
I have come across a query that executes very slow in RDF4J (2.2.2, 2.2.1). It executes within seconds using Apache Jena Fuseki, and was running for 24 hours using RDF4J, before I killed it.
Data: [data.ttl.gz](https://github.com/eclipse/rdf4j/files/1451070/data.ttl.gz)
Query:
``` sparql
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

PREFIX report: <https://vocabulary.etl.linkedpipes.com/report/>
PREFIX httpList: <http://plugins.linkedpipes.com/ontology/e-httpGetFiles#>

SELECT ?publisherName ?status ?message (count(?downloadURL) as ?count) WHERE 
{ 
?s a dcat:Dataset;
        dcat:distribution ?distribution ;
        dcterms:publisher ?publisher .
?distribution dcterms:license ?downloadURL .
?report report:task ?downloadURL ;
            report:status ?status ;
            report:duration ?duration .

OPTIONAL {
?report report:exception ?exception .
?exception report:message ?message .
}

?publisher foaf:name ?publisherName .
}
GROUP BY ?publisherName ?status ?message
ORDER BY DESC(?count) ?publisherName
```

**Comment by jamesrdf** [comment]
The optimizer is not choosing the best plan in this case. There are only 16 report:task statements and it chooses to start there, but the optimizer is under estimating the cost of following back dcat:distribution, of which there are over 100k statements. The optimizer goes on to look at 26 foaf:name and ends up doing a cross join to find matching dcat:Dataset, but there are over 100k of those and it can't find a match in a reasonable amount of time.

Unfortunately, there is no easy fix for this as the optimizer uses a hill climber algorithm and only considers one step at a time and doesn't get into trouble until dcat:distribution.

However, you can force the optimizer to choose more wisely using the query below.
```sparql
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

PREFIX report: <https://vocabulary.etl.linkedpipes.com/report/>
PREFIX httpList: <http://plugins.linkedpipes.com/ontology/e-httpGetFiles#>

SELECT ?publisherName ?status ?message (count(?downloadURL) as ?count) WHERE 
{ 
?s a dcat:Dataset;
        dcat:distribution ?distribution ;
        dcterms:publisher ?publisher .
?distribution dcterms:license ?downloadURL .
OPTIONAL {
?report report:task ?downloadURL ;
            report:status ?status ;
            report:duration ?duration .

OPTIONAL {
?report report:exception ?exception .
?exception report:message ?message .
}
} FILTER bound(?report)

?publisher foaf:name ?publisherName .
}
GROUP BY ?publisherName ?status ?message
ORDER BY DESC(?count) ?publisherName
```

**Comment by jakubklimek** [comment]
OK, adding the OPTIONAL clause indeed fixed the performance issue. Is there any tips & tricks library this could go to?
