### ISSUE TITLE
Enable setBinding for parameters inside a VALUES clause

### ISSUE THREAD

**Issue by axthosarouris** [eclipse/rdf4j#939]
Hi,

Given a desired query of the following form :

        CONSTRUCT {?subject ?p ?o} WHERE {
                     ?subject ?p ?o .
                     VALUES (?p) {<IRI1> <IRI2> <IRI3> }
                   }

 it would be useful if there was a possibility to construct the above query by using variables  for the IRIs and then use the function setBinding to replace the variables with IRIs. For instance:

            IRI subject=defineSubject()
            IRI iri1= defineIRI1()
            IRI iri2= defineIRI2()
            IRI iri3= defineIRI3()

            String query="CONSTRUCT {?subject ?p ?o} WHERE {"
				+ "?subject ?p ?o . "
				+ "VALUES (?p) "
				+ "{?iri1, ?iri2 ?iri3}"
				+ "}";

	 Repositories.consume(blazegraphService.getRepository(), connection -> {
			GraphQuery graphQuery = connection.prepareGraphQuery(query);
			graphQuery.setBinding("subject",subject);
			graphQuery.setBinding("iri1",iri1);
			graphQuery.setBinding("iri2",iri2);
			graphQuery.setBinding("iri3",iri3);
                       GraphQueryResult evaluate = graphQuery.evaluate();
			model.addAll(QueryResults.asModel(evaluate));
		});

Now, the query parser throws a MalformedQueryException 
    
     org.eclipse.rdf4j.query.MalformedQueryException: Encountered " <VAR1> "?pred0 "" at line 1, column 63.
    Was expecting one of:
       "}" ...
        "true" ...
       "false" ...
       "UNDEF" ...
       <Q_IRI_REF> ...
       <PNAME_NS> ...
       <PNAME_LN> ...
        <INTEGER> ...
        <INTEGER_POSITIVE> ...
        <INTEGER_NEGATIVE> ...
        <DECIMAL> ...
        <DECIMAL_POSITIVE> ...
        <DECIMAL_NEGATIVE> ...
        <DOUBLE> ...
        <DOUBLE_POSITIVE> ...
        <DOUBLE_NEGATIVE> ...
        <STRING_LITERAL1> ...
        <STRING_LITERAL2> ...
        <STRING_LITERAL_LONG1> ...
        <STRING_LITERAL_LONG2> ...

**Comment by jeenbroekstra** [comment]
Near-duplicate to #505
