### ISSUE TITLE
Add SILENT option to SPARQLRepository 

### ISSUE THREAD

**Issue by mhedenus** [eclipse/rdf4j#956]
According to SPARQL 1.1 Update many commands may fail depending on the existance of data.
This leads to different behaviors of  methods, e.g. RepositoryConnection.clear(context) is succesful for GraphDB but Stardog fails if the context does not exist.

SPARQL allows a SILENT option that should be added somehow to the RepositoryConnection interface.
This could be done adding extra methods like clearSilent() or add option setSilent(boolean).

The current SPARQLRepositoryConnection cannot be overwritten because it uses private members in public methods (which is always an anit-pattern).

**Comment by mhedenus** [comment]
Hi folks,
I wonder why this issue not considered to be more important.
Any idea when it is going to be done?

**Comment by jeenbroekstra** [comment]
> I wonder why this issue not considered to be more important.
> Any idea when it is going to be done?

This wasn't really on my radar for some reason (I think it may just have gotten lost in the backlog).

However, we already provide functionality to facilitate this. You can use the `Repositories` helper class around any (sequence of) repository operation(s):
    
    Repositories.consumeSilent(endpoint, conn -> conn.clear());

**Comment by mhedenus** [comment]
Hello Jeen,

thanks for considering this issue. But I'd like to reopen it because your solution is simply suppressing an error. This is (1) bad practice in general (2) something different from supporting a language feature like "silient" in SPARQL. 

So why not adding a silent option? Implementation should be very simple.

**Comment by jeenbroekstra** [comment]
I'm not entirely sure I understand what your use case is. 

If this is about being able to do Repository API operations on a (non-rdf4j) SPARQL endpoint, then that is fully supported. The Repository API in general has no notion of "silent" clear, we instead offer the option to catch and ignore the error. The net effect is the same. 

If this is specifically about the ability to be able to use a SPARQL construct like "CLEAR SILENT", you can also do that, e.g. something like this:

     conn.prepareUpdate("CLEAR SILENT ALL").execute();

So what can't you currently do that adding a `clearSilent()` would remedy?

**Comment by mhedenus** [comment]
The actual use case is this: The line  "repositoryConnection.clear(context);" fails if the graph does not exist and the database is Stardog but is executed silently if the database is Oracle. Ideally the behavior of the API should be the same for both databases. This would be possible is a silent option exists. Also, the API would then support SPARQL more fully.

The solution to write "conn.prepareUpdate("CLEAR SILENT <...>").execute();" is okay for me but it feels like a workaround.

**Comment by jeenbroekstra** [comment]
Thanks for clarifying. I still don't think introducing this as a separate method at the RepositoryConnection interface level is the way to go. 

However, a configuration option at the level of the SPARQLRepository/SPARQLConnection might be useful. Something similar to the `enableQuadMode` configuration option.

**Comment by SakshiSaini17092** [comment]
Hey, I have added the Silent mode option just like enableQuadMode in SparqlConnection. Can you please tell me how can I check that functionality? 
The enable option is available in SparqlRepository. But the present SparqlConnectionTest doesn't pass the SparqlRepository as null.

**Comment by SakshiSaini17092** [comment]
I am sorry to remove the assignment. That was done by mistake can you please assign it back to me.

**Comment by jeenbroekstra** [comment]
> Hey, I have added the Silent mode option just like enableQuadMode in SparqlConnection. Can you please tell me how can I check that functionality?
> The enable option is available in SparqlRepository. But the present SparqlConnectionTest doesn't pass the SparqlRepository as null.

I think the best thing to do is introduce a new mock for SPARQLRepository:

      repository = mock(SPARQLRepository.class);

similarly to how the SPARQLPRotocolSession is already mocked out. Pass that into the connection instead of `null`.

Then in your test, you can configure this mock to return `true` is `isSillent is called:

   when(repository.isSilentMode()).thenReturn(true);

and then do your testing to check that the mocked SPARQLProtocolSession receives the correct SPARQL update operation (with the SILENT added in there).

**Comment by SakshiSaini17092** [comment]
I added the test case also. Kindly look into this and tell me if it is correct.

**Comment by raghav17083** [comment]
@jeenbroekstra Kindly look in to the PR by @SakshiSaini17092
