### ISSUE TITLE
Repository data lost after Windows 10 update

### ISSUE THREAD

**Issue by estiqaatsi** [eclipse/rdf4j#958]
Hi, I have RDF4J v. 2.2.2 running with Apache Tomcat 9.0 on Windows 10.

Today I noticed that my RDF repository is no more available, and I only see the "SYSTEM" one.
Then I switched to a mirror-backup install, running on another machine (same configuration) and another network, but the repository is missing there too.

Do you have any idea on why this happened? Do you know how is it possible to recover the repository data? Where are they located in the local filesystem?

Thank you in advance for your replies.

Regards.

**Comment by jamesrdf** [comment]
This is better handled on the mailing list. Please don't create an issue unless you have sufficient information and steps to reproduce. However, you can take a look at http://docs.rdf4j.org/server-workbench-console/#_application_directory_configuration

**Comment by estiqaatsi** [comment]
Thank you for your reply, and sorry if I did not follow the community rules.
May you please tell me how to access the mailing list?
Furthermore, I did not find anything related to my issue in the link you provided, which I already visited before raising the issue.
Last, I don't have any more information about my issue: I had a working repository, Windows 10 updated, now I don't have any repository. That's all.
Thank you again.
