### ISSUE TITLE
Extremely poor performance of OrderIterator

### ISSUE THREAD

**Issue by SWCbelks** [eclipse/rdf4j#971]
We encountered several issues dealing with queries containing an "ORDER BY" clause. Simple queries (like "SELECT ?o WHERE {?s ?p ?o} ORDER BY ASC(?o) LIMIT 100000") with large LIMIT values and/or over large data sets (>100000 statements) would take minutes or longer. On the other hand, if we fetch all the objects without the "ORDER BY" clause the query plus ordering the results in Java afterwards is just a matter of seconds.

We found out that the reason for this is the implementation of the OrderIterator.class which uses a TreeMap for the ordering. This works fine for very small LIMIT values, but it a terrible idea when dealing with larger LIMIT values and a large amount of binding sets. We compared it with a modified OderIterator working with a simple List implementation instead of the TreeMap, which just collects all BindingSet values and does one single sorting run afterwards. 

While the List implementation's runtime only depends on the number of binding sets to sort and does not depend of the size of the LIMIT parameter (of course, since if always collects all binding sets and sorts them), the current TreeMap implementation seems to perform exponentially worse depending on the size of the LIMIT parameter. See attached images below.

The one and only case where the current TreeMap implementation is in any way useful, is with very large binding sets (see image test3 with 1.5 million statements) in combination with small limit values (in our case less than 15000). There it can skip a some operations while our List based implementation needs to collect all the results and sort all of them. In all other cases of large or small number of binding sets, and large or small limit values a simple list and sorting was always significantly faster. In the worst case we tested it was 16 seconds vs more than 252 seconds (more than 4 minutes!!!). See attached images below.

The values shown in the images are the runtime in milliseconds for the simple query stated above using various LIMIT values. The "-1" LIMIT value in the pictures denotes the runtime of the example query without any limit clause. We tested it with 50000, 250000 and 1.5 million statements and LIMIT values between 100 and 50000. You can reproduce the behaviour by simply creating some artificial statements in an empty MemoryStore, e.g.:

for (int i=0; i<250000; i++) {
    connection.add(RDFS.CLASS, RDFS.LABEL, connection.getValueFactory().createLiteral(i+"bla"));
}

And then execute the query mentioned above with the various limits . 

String query = "SELECT * WHERE {?s ?p ?o} ORDER BY ASC(?o) "+limit;
logger.warn("executing query: "+query);
long start = System.currentTimeMillis();

try (TupleQueryResult result = connection.prepareTupleQuery(query).evaluate()) {
	int count = 0;
	while (result.hasNext()) {
		result.next();
		count++;
	}
	logger.warn(count+" statements");
} finally {
	logger.warn("Query took "+(System.currentTimeMillis()-start)+" ms");
}

We stopped testing at LIMIT values of 50000, because the current TreeMap implementation would take forever to finish with larger values (or at least take more time than we were willing to invest).

I also added our modified OrderIterator in the attached ZIP file for you to have a look at. We moved the existing TreeMap code from the main createIteration method to a createTreeMapIteration method and added a createListIteration implementation to test the performance and switch between the implementation. We did not touch the disk-syncing TreeMap code which was never executed in our tests anyway.

![test1](https://user-images.githubusercontent.com/26894849/34685049-621059d6-f4a7-11e7-9214-3abf0ab8f6d6.jpeg)
![test2](https://user-images.githubusercontent.com/26894849/34685051-63934b74-f4a7-11e7-91a9-0a39a311f9df.jpeg)
![test3](https://user-images.githubusercontent.com/26894849/34685052-651add04-f4a7-11e7-8f89-f13fd2471af6.jpeg)
[OrderIterator.java.zip](https://github.com/eclipse/rdf4j/files/1612663/OrderIterator.java.zip)

**Comment by jamesrdf** [comment]
This is really interesting results! How would Arrays.parallelSort compare with List.sort?

**Comment by SWCbelks** [comment]
I get even better results when using Arrays.parallelSort + remembering the currently largest binding set and only adding it to the List if smaller + using LinkedList instead of ArrayLists to avoid array copying. Named it "Smart List" in the images attached below. Also tested it with a fixed limit and larger and larger amounts of statements. Simple list sort starts to fail around 3 million statements, but the improved version (new zip file attached) handles that easily. 

Please consider replacing the current TreeMap implementation ASAP. There is sooo much improvement potential there.

![test4](https://user-images.githubusercontent.com/26894849/34716788-351bc4b2-f531-11e7-9737-da8652899664.jpeg)
![test5](https://user-images.githubusercontent.com/26894849/34716792-37a167a0-f531-11e7-94cb-7dcaa61a433d.jpeg)
[OrderIterator.java.zip](https://github.com/eclipse/rdf4j/files/1614763/OrderIterator.java.zip)
