### ISSUE TITLE
Serializing Illegal IRIs

### ISSUE THREAD

**Issue by jamesrdf** [eclipse/rdf4j#986]
Using the ValueFactory interface it is possible to create an illegal IRI. However, RIO writers/parsers fail if some of these illegal IRIs are present. The writers/parser should not fail on these illegal IRIs when verify IRI syntax is disabled.

**Comment by barthanssens** [comment]
Well, per Postel's Law... perhaps the writer should fail (at least produce a warning), but the parser should be able to process them ?

**Comment by jamesrdf** [comment]
If the writer fails, the user will have no easy way to recover, which is the case with rdf4j 2.2.

**Comment by jamesrdf** [comment]
If verify IRI syntax is disabled the parser will (with what's in develop branch) percent encode illegal characters in IRIs
