### ISSUE TITLE
AbstractSPARQLJSONParser fails on unknown properties in the JSON response

### ISSUE THREAD

**Issue by aindlq** [eclipse/rdf4j#994]
`org.eclipse.rdf4j.query.resultio.sparqljson.AbstractSPARQLJSONParser` fails on unknown properties in the JSON response (see https://github.com/eclipse/rdf4j/blob/master/queryresultio/sparqljson/src/main/java/org/eclipse/rdf4j/query/resultio/sparqljson/AbstractSPARQLJSONParser.java#L335), but according to the specification:

> Other keys, with different names, may be present in the JSON Results Object but are not defined by this specification.
https://www.w3.org/TR/sparql11-results-json/#json-result-object

**Comment by andriy-nikolov** [comment]
After the fix the org.eclipse.rdf4j.query.resultio.sparqljson.AbstractSPARQLJSONParser can process non-standard keys with string values (e.g., `"other": "Other keys, with different names, may be present in the JSON Results Object"`), but it fails if the value is an array: (e.g., `"otherArray": [ "Other keys, with different names, ", "may be present in the JSON Results Object" ]`). I prepared a fix for this edge case, can this issue be re-opened?
