### ISSUE TITLE
Provide diagnostics for rule execution (SPIN, SHACL etc)

### ISSUE THREAD

**Issue by rob-metalinkage** [eclipse/rdf4j#998]
Rule execution is hard to debug - particularly when rules may interact by injecting new data, and be explicitly chained or executed in arbitrary order.
A minimal capability would be option for logging rule and instance that triggered a rule.  An ability to dynamically monitor running queries, including identification of the source of the query would also support debugging long running queries.

Logged as feature request as per suggestion in thread 
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/rdf4j-users/hlxxU9BszsM

**Comment by jeenbroekstra** [comment]
@hmottestad do you consider this issue complete for now? If so we can close it now. If there's a later need for more advanced logging/diagnostics we can always open a followup.

**Comment by hmottestad** [comment]
With regards to SHACL, yes. I consider it complete. For SPIN I don’t have any intention of doing anything.

**Comment by jeenbroekstra** [comment]
I'll close this for now. For SPIN support, the jury is out on whether we want to fully deprecate it and focus our resources fully on SHACL instead.

**Comment by hmottestad** [comment]
Even though this is closed. @jeenbroekstra SPIN can be used to "infer" new triples based on SPARQL-like syntax. It can also be used to validate data. SHACL is only for data validation. But I would love to see SPIN deprecated. It gives semantic web a bad rap, because it's fairly easy to use but slow as hell.
